// $Id: gnuplot_io.C,v 1.1 2005-06-06 16:24:14 knezed01 Exp $

// The libMesh Finite Element Library.
// Copyright (C) 2002-2005  Benjamin S. Kirk, John W. Peterson
  
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
  
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
  
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

// C++ includes
#include <fstream>

// Local includes
#include "mesh_base.h"
#include "gnuplot_io.h"

GnuPlotIO::GnuPlotIO(const MeshBase& mesh, const std::string& title, bool grid)
  :
  MeshOutput<MeshBase> (mesh),
  _title(title),
  _grid(grid)
{
}

void GnuPlotIO::write(const std::string& fname)
{

  if(libMesh::processor_id() == 0)
    this->write_solution(fname);

}

void GnuPlotIO::write_nodal_data (const std::string& fname,
                       const std::vector<Number>& soln,
                       const std::vector<std::string>& names)
{
  if(libMesh::processor_id() == 0)
    this->write_solution(fname, &soln, &names);

}




void GnuPlotIO::write_solution(const std::string& fname,
   			       const std::vector<Number>* soln,
			       const std::vector<std::string>* names)
{
  assert(libMesh::processor_id() == 0);

  const MeshBase& mesh = MeshOutput<MeshBase>::mesh();
  
  // This class is designed only for use with 1D meshes
  assert (mesh.mesh_dimension() == 1);
  

  // Create an output stream for script file
  std::ofstream out(fname.c_str());

  if (!out.good())
    {
      std::cerr << "ERROR: opening output file " << fname
		<< std::endl;
      error();
    }

  // The number of variables in the equation system
  const unsigned int n_vars = names->size();
  
  // Write header to stream
  out << "# This file was generated by gnuplot_io.C\n"
      << "# Stores 1D solution data in GNUplot format\n"
      << "# Execute this by loading gnuplot and typing "
      << "\"call '" << fname << "'\"\n"
      << "reset\n"
      << "set title \"" << _title << "\"\n"
      << "set xlabel \"x\"\n"
      << "set autoscale\n"
      << "set xtics nomirror\n";
      
  if(_grid)
  {
    // construct string for xtic positions at element edges
    std::string xtics;
    std::stringstream xtics_stream;

    MeshBase::const_element_iterator it = mesh.active_local_elements_begin();
    const MeshBase::const_element_iterator end_it =
      mesh.active_local_elements_end();

    unsigned int count = 0;
    unsigned int n_active_elem = mesh.n_active_elem();

    for( ; it != end_it; ++it)
    {
      Elem* el = *it;
      
      // if el is the left edge of the mesh, print its left node position
      if(el->neighbor(0) == NULL)
      {
        xtics_stream << "\"\" " << (*(el->get_node(0)))(0) << ", \\\n";
      }
      xtics_stream << "\"\" " << (*(el->get_node(1)))(0);

      if(count+1 != n_active_elem)
      {
         xtics_stream << ", \\\n";
      }
      count++;
    }
    xtics = xtics_stream.str();
    
  
    out << "set x2tics (" << xtics << ")\nset grid noxtics noytics x2tics\n";
  }

  out << "plot \"data\" using 1:2 title \"" << (*names)[0]
      << "\" with lines";
  if(n_vars > 1)
  {
    for(unsigned int i=1; i<n_vars; i++)
    {
      out << ", \\\n\"data\" using 1:" << i+2 
          << " title \"" << (*names)[i] << "\" with lines";
    }
  }

  out.close();


  // Create an output stream for data file
  std::ofstream data("data");

  if (!data.good())
    {
      std::cerr << "ERROR: opening output data file " << std::endl;
      error();
    }

  data << "# This file contains libMesh solution data "
       << "to be plotted in GNUplot\n\n";

  std::vector<double> ordered_nodes;
  // First we need to put the nodes in increasing order
  for(unsigned int i=0; i<mesh.n_nodes(); i++)
  {
    ordered_nodes.push_back(mesh.point(i)(0));
  }
  sort(ordered_nodes.begin(), ordered_nodes.end());

  for(unsigned int i=0; i<mesh.n_nodes(); i++)
  {
    data << ordered_nodes[i] << "\t";
    // write the corresponding solution values
    if( (names != NULL) && (soln != NULL) )
    {
      assert(soln->size() == mesh.n_nodes()*n_vars);
    
      for(unsigned int c=0; c<n_vars; c++)
      {
        // index == node number of ordered_nodes[i] in mesh
        for(unsigned int index=0; index<mesh.n_nodes(); index++)
        {
          if(mesh.point(index)(0) == ordered_nodes[i])
            data << (*soln)[index*n_vars + c] << "\t";
        }
      }
    }
    data << "\n";
  }

  data.close();
}
