#
# How to make the dependencies
#
all:
	$(MAKE) -C sfcurves $(MAKECMDGOALS)



#
# How to clean the packages
#
clean:
	rm -f *~
	$(MAKE) -C sfcurves $(MAKECMDGOALS)

#
# How to clobber the packages
#
clobber:
	$(MAKE) clean
	$(MAKE) -C sfcurves $(MAKECMDGOALS)
