
#include "libmesh_config.h"

#ifdef LIBMESH_ENABLE_HIGHER_ORDER_SHAPES

#include "fe_test.h"

INSTANTIATE_FETEST(FIRST, BERNSTEIN, EDGE2);
INSTANTIATE_FETEST(FIRST, BERNSTEIN, TRI3);
INSTANTIATE_FETEST(FIRST, BERNSTEIN, QUAD4);
INSTANTIATE_FETEST(FIRST, BERNSTEIN, TET4);
INSTANTIATE_FETEST(FIRST, BERNSTEIN, HEX8);

INSTANTIATE_FETEST(SECOND, BERNSTEIN, EDGE3);
INSTANTIATE_FETEST(SECOND, BERNSTEIN, TRI6);
INSTANTIATE_FETEST(SECOND, BERNSTEIN, QUAD9);
INSTANTIATE_FETEST(SECOND, BERNSTEIN, TET10);
INSTANTIATE_FETEST(SECOND, BERNSTEIN, HEX27);

INSTANTIATE_FETEST(THIRD, BERNSTEIN, EDGE3);
INSTANTIATE_FETEST(THIRD, BERNSTEIN, TRI6);
INSTANTIATE_FETEST(THIRD, BERNSTEIN, QUAD9);
INSTANTIATE_FETEST(THIRD, BERNSTEIN, HEX27);

#endif // LIBMESH_ENABLE_HIGHER_ORDER_SHAPES
