
#include "fe_test.h"

INSTANTIATE_FETEST(FIRST, HIERARCHIC, EDGE2);
INSTANTIATE_FETEST(SECOND, HIERARCHIC, EDGE3);
INSTANTIATE_FETEST(THIRD, HIERARCHIC, EDGE3);
INSTANTIATE_FETEST(FOURTH, HIERARCHIC, EDGE3);

#if LIBMESH_DIM > 1
INSTANTIATE_FETEST(FIRST, HIERARCHIC, TRI3);
INSTANTIATE_FETEST(SECOND, HIERARCHIC, TRI6);
INSTANTIATE_FETEST(THIRD, HIERARCHIC, TRI6);
INSTANTIATE_FETEST(FOURTH, HIERARCHIC, TRI6);

INSTANTIATE_FETEST(SECOND, HIERARCHIC, TRI7);
INSTANTIATE_FETEST(THIRD, HIERARCHIC, TRI7);
INSTANTIATE_FETEST(FOURTH, HIERARCHIC, TRI7);

INSTANTIATE_FETEST(FIRST, HIERARCHIC, QUAD4);
INSTANTIATE_FETEST(SECOND, HIERARCHIC, QUAD9);
INSTANTIATE_FETEST(THIRD, HIERARCHIC, QUAD9);
INSTANTIATE_FETEST(FOURTH, HIERARCHIC, QUAD9);
#endif

#if LIBMESH_DIM > 2
INSTANTIATE_FETEST(FIRST, HIERARCHIC, HEX8);
INSTANTIATE_FETEST(SECOND, HIERARCHIC, HEX27);
INSTANTIATE_FETEST(THIRD, HIERARCHIC, HEX27);
INSTANTIATE_FETEST(FOURTH, HIERARCHIC, HEX27);

INSTANTIATE_FETEST(FIRST, HIERARCHIC, PRISM6);
INSTANTIATE_FETEST(FIRST, HIERARCHIC, PRISM15);
INSTANTIATE_FETEST(SECOND, HIERARCHIC, PRISM18);
INSTANTIATE_FETEST(SECOND, HIERARCHIC, PRISM20);
INSTANTIATE_FETEST(THIRD, HIERARCHIC, PRISM20);
INSTANTIATE_FETEST(FOURTH, HIERARCHIC, PRISM20);
INSTANTIATE_FETEST(SECOND, HIERARCHIC, PRISM21);
INSTANTIATE_FETEST(THIRD, HIERARCHIC, PRISM21);
INSTANTIATE_FETEST(FOURTH, HIERARCHIC, PRISM21);

INSTANTIATE_FETEST(FIRST, HIERARCHIC, TET4);
INSTANTIATE_FETEST(SECOND, HIERARCHIC, TET10);
INSTANTIATE_FETEST(THIRD, HIERARCHIC, TET14);
INSTANTIATE_FETEST(FOURTH, HIERARCHIC, TET14);
#endif
