
#include "fe_test.h"

INSTANTIATE_FETEST(FIRST, HIERARCHIC, EDGE2);
INSTANTIATE_FETEST(FIRST, HIERARCHIC, TRI3);
INSTANTIATE_FETEST(FIRST, HIERARCHIC, QUAD4);
INSTANTIATE_FETEST(FIRST, HIERARCHIC, HEX8);

INSTANTIATE_FETEST(SECOND, HIERARCHIC, EDGE3);
INSTANTIATE_FETEST(SECOND, HIERARCHIC, TRI6);
INSTANTIATE_FETEST(SECOND, HIERARCHIC, QUAD9);
INSTANTIATE_FETEST(SECOND, HIERARCHIC, HEX27);

INSTANTIATE_FETEST(THIRD, HIERARCHIC, EDGE3);
INSTANTIATE_FETEST(THIRD, HIERARCHIC, TRI6);
INSTANTIATE_FETEST(THIRD, HIERARCHIC, QUAD9);
INSTANTIATE_FETEST(THIRD, HIERARCHIC, HEX27);
