
#include "fe_test.h"

INSTANTIATE_FETEST(THIRD, HERMITE, EDGE3);
#if LIBMESH_DIM > 1
INSTANTIATE_FETEST(THIRD, HERMITE, QUAD9);
#endif
#if LIBMESH_DIM > 2
INSTANTIATE_FETEST(THIRD, HERMITE, HEX27);
#endif
