
#include "fe_test.h"

INSTANTIATE_FETEST(FIRST, LAGRANGE, EDGE2);
INSTANTIATE_FETEST(FIRST, LAGRANGE, TRI3);
INSTANTIATE_FETEST(FIRST, LAGRANGE, QUAD4);
INSTANTIATE_FETEST(FIRST, LAGRANGE, TET4);
INSTANTIATE_FETEST(FIRST, LAGRANGE, HEX8);
INSTANTIATE_FETEST(FIRST, LAGRANGE, PRISM6);
INSTANTIATE_FETEST(FIRST, LAGRANGE, PYRAMID5);

INSTANTIATE_FETEST(SECOND, LAGRANGE, QUAD8);
INSTANTIATE_FETEST(SECOND, LAGRANGE, HEX20);
INSTANTIATE_FETEST(SECOND, LAGRANGE, PRISM15);
INSTANTIATE_FETEST(SECOND, LAGRANGE, PYRAMID13);

INSTANTIATE_FETEST(SECOND, LAGRANGE, EDGE3);
INSTANTIATE_FETEST(SECOND, LAGRANGE, TRI6);
INSTANTIATE_FETEST(SECOND, LAGRANGE, QUAD9);
INSTANTIATE_FETEST(SECOND, LAGRANGE, TET10);
INSTANTIATE_FETEST(SECOND, LAGRANGE, HEX27);
INSTANTIATE_FETEST(SECOND, LAGRANGE, PRISM18);
INSTANTIATE_FETEST(SECOND, LAGRANGE, PYRAMID14);
