#include "fe_test.h"

// The C0 Gauss-Lobatto basis needs a node for each entity that owns degrees of freedom, so
// order two and above wants mid-edge nodes in two dimensions and face nodes as well in three.

INSTANTIATE_FETEST(FIRST,  LAGRANGE_GLL, EDGE2);
INSTANTIATE_FETEST(SECOND, LAGRANGE_GLL, EDGE2);
INSTANTIATE_FETEST(SECOND, LAGRANGE_GLL, EDGE3);
INSTANTIATE_FETEST(THIRD,  LAGRANGE_GLL, EDGE3);
INSTANTIATE_FETEST(FOURTH, LAGRANGE_GLL, EDGE3);

#if LIBMESH_DIM > 1
INSTANTIATE_FETEST(FIRST,  LAGRANGE_GLL, QUAD4);
INSTANTIATE_FETEST(SECOND, LAGRANGE_GLL, QUAD8);
INSTANTIATE_FETEST(SECOND, LAGRANGE_GLL, QUAD9);
INSTANTIATE_FETEST(THIRD,  LAGRANGE_GLL, QUAD9);
INSTANTIATE_FETEST(FOURTH, LAGRANGE_GLL, QUAD9);
#endif

#if LIBMESH_DIM > 2
INSTANTIATE_FETEST(FIRST,  LAGRANGE_GLL, HEX8);
INSTANTIATE_FETEST(SECOND, LAGRANGE_GLL, HEX27);
INSTANTIATE_FETEST(THIRD,  LAGRANGE_GLL, HEX27);
INSTANTIATE_FETEST(FOURTH, LAGRANGE_GLL, HEX27);
#endif
