#include "fe_test.h"

// The L2_LAGRANGE_GLL basis is a tensor product, so it lives on the tensor product element
// types alone. Every one of its degrees of freedom belongs to the element, so it asks
// nothing of the element's node count and an order above two runs on a first order type.

INSTANTIATE_FETEST(FIRST,  L2_LAGRANGE_GLL, EDGE2);
INSTANTIATE_FETEST(SECOND, L2_LAGRANGE_GLL, EDGE2);
INSTANTIATE_FETEST(SECOND, L2_LAGRANGE_GLL, EDGE3);
INSTANTIATE_FETEST(THIRD,  L2_LAGRANGE_GLL, EDGE3);
INSTANTIATE_FETEST(FOURTH, L2_LAGRANGE_GLL, EDGE3);

#if LIBMESH_DIM > 1
INSTANTIATE_FETEST(FIRST,  L2_LAGRANGE_GLL, QUAD4);
INSTANTIATE_FETEST(SECOND, L2_LAGRANGE_GLL, QUAD4);
INSTANTIATE_FETEST(SECOND, L2_LAGRANGE_GLL, QUAD9);
INSTANTIATE_FETEST(THIRD,  L2_LAGRANGE_GLL, QUAD9);
INSTANTIATE_FETEST(FOURTH, L2_LAGRANGE_GLL, QUAD9);
#endif

#if LIBMESH_DIM > 2
INSTANTIATE_FETEST(FIRST,  L2_LAGRANGE_GLL, HEX8);
INSTANTIATE_FETEST(SECOND, L2_LAGRANGE_GLL, HEX8);
INSTANTIATE_FETEST(SECOND, L2_LAGRANGE_GLL, HEX27);
INSTANTIATE_FETEST(THIRD,  L2_LAGRANGE_GLL, HEX27);
#endif
