
#include "fe_test.h"

INSTANTIATE_FETEST(FIRST, L2_HIERARCHIC, EDGE2);
INSTANTIATE_FETEST(FIRST, L2_HIERARCHIC, TRI3);
INSTANTIATE_FETEST(FIRST, L2_HIERARCHIC, QUAD4);
INSTANTIATE_FETEST(FIRST, L2_HIERARCHIC, HEX8);

INSTANTIATE_FETEST(SECOND, L2_HIERARCHIC, EDGE3);
INSTANTIATE_FETEST(SECOND, L2_HIERARCHIC, TRI6);
INSTANTIATE_FETEST(SECOND, L2_HIERARCHIC, QUAD9);
INSTANTIATE_FETEST(SECOND, L2_HIERARCHIC, HEX27);

INSTANTIATE_FETEST(THIRD, L2_HIERARCHIC, EDGE3);
INSTANTIATE_FETEST(THIRD, L2_HIERARCHIC, TRI6);
INSTANTIATE_FETEST(THIRD, L2_HIERARCHIC, QUAD9);
INSTANTIATE_FETEST(THIRD, L2_HIERARCHIC, HEX27);
