
#include "fe_test.h"

INSTANTIATE_FETEST(FIRST, MONOMIAL, EDGE2);
INSTANTIATE_FETEST(FIRST, MONOMIAL, TRI3);
INSTANTIATE_FETEST(FIRST, MONOMIAL, QUAD4);
INSTANTIATE_FETEST(FIRST, MONOMIAL, TET4);
INSTANTIATE_FETEST(FIRST, MONOMIAL, HEX8);
INSTANTIATE_FETEST(FIRST, MONOMIAL, PRISM6);

INSTANTIATE_FETEST(SECOND, MONOMIAL, QUAD8);
INSTANTIATE_FETEST(SECOND, MONOMIAL, HEX20);
INSTANTIATE_FETEST(SECOND, MONOMIAL, PRISM15);

INSTANTIATE_FETEST(SECOND, MONOMIAL, EDGE3);
INSTANTIATE_FETEST(SECOND, MONOMIAL, TRI6);
INSTANTIATE_FETEST(SECOND, MONOMIAL, QUAD9);
INSTANTIATE_FETEST(SECOND, MONOMIAL, TET10);
INSTANTIATE_FETEST(SECOND, MONOMIAL, HEX27);
INSTANTIATE_FETEST(SECOND, MONOMIAL, PRISM18);

INSTANTIATE_FETEST(THIRD, MONOMIAL, QUAD8);
INSTANTIATE_FETEST(THIRD, MONOMIAL, HEX20);
INSTANTIATE_FETEST(THIRD, MONOMIAL, PRISM15);

INSTANTIATE_FETEST(THIRD, MONOMIAL, EDGE3);
INSTANTIATE_FETEST(THIRD, MONOMIAL, TRI6);
INSTANTIATE_FETEST(THIRD, MONOMIAL, QUAD9);
INSTANTIATE_FETEST(THIRD, MONOMIAL, TET10);
INSTANTIATE_FETEST(THIRD, MONOMIAL, HEX27);
INSTANTIATE_FETEST(THIRD, MONOMIAL, PRISM18);
