
#include "libmesh_config.h"

#ifdef LIBMESH_ENABLE_HIGHER_ORDER_SHAPES

// Only test equal-order elements; that's all we support for now.
//
// Only test simplices in the linear case; we don't have a good
// higher order rational basis function unit test for those.

#include "fe_test.h"

INSTANTIATE_FETEST(FIRST, RATIONAL_BERNSTEIN, EDGE2);
INSTANTIATE_FETEST(SECOND, RATIONAL_BERNSTEIN, EDGE3);

#if LIBMESH_DIM > 1
INSTANTIATE_FETEST(FIRST, RATIONAL_BERNSTEIN, TRI3);
//INSTANTIATE_FETEST(SECOND, RATIONAL_BERNSTEIN, TRI6);

INSTANTIATE_FETEST(FIRST, RATIONAL_BERNSTEIN, QUAD4);
INSTANTIATE_FETEST(SECOND, RATIONAL_BERNSTEIN, QUAD9);
#endif

#if LIBMESH_DIM > 2
INSTANTIATE_FETEST(FIRST, RATIONAL_BERNSTEIN, TET4);
//INSTANTIATE_FETEST(SECOND, RATIONAL_BERNSTEIN, TET10);

INSTANTIATE_FETEST(FIRST, RATIONAL_BERNSTEIN, HEX8);
INSTANTIATE_FETEST(SECOND, RATIONAL_BERNSTEIN, HEX27);
#endif

#endif // LIBMESH_ENABLE_HIGHER_ORDER_SHAPES
