
#include "fe_test.h"

INSTANTIATE_FETEST(FIRST, XYZ, EDGE2);
INSTANTIATE_FETEST(FIRST, XYZ, TRI3);
INSTANTIATE_FETEST(FIRST, XYZ, QUAD4);
INSTANTIATE_FETEST(FIRST, XYZ, TET4);
INSTANTIATE_FETEST(FIRST, XYZ, HEX8);
INSTANTIATE_FETEST(FIRST, XYZ, PRISM6);

INSTANTIATE_FETEST(SECOND, XYZ, QUAD8);
INSTANTIATE_FETEST(SECOND, XYZ, HEX20);
INSTANTIATE_FETEST(SECOND, XYZ, PRISM15);

INSTANTIATE_FETEST(SECOND, XYZ, EDGE3);
INSTANTIATE_FETEST(SECOND, XYZ, TRI6);
INSTANTIATE_FETEST(SECOND, XYZ, QUAD9);
INSTANTIATE_FETEST(SECOND, XYZ, TET10);
INSTANTIATE_FETEST(SECOND, XYZ, HEX27);
INSTANTIATE_FETEST(SECOND, XYZ, PRISM18);

INSTANTIATE_FETEST(THIRD, XYZ, QUAD8);
INSTANTIATE_FETEST(THIRD, XYZ, HEX20);
INSTANTIATE_FETEST(THIRD, XYZ, PRISM15);

INSTANTIATE_FETEST(THIRD, XYZ, EDGE3);
INSTANTIATE_FETEST(THIRD, XYZ, TRI6);
INSTANTIATE_FETEST(THIRD, XYZ, QUAD9);
INSTANTIATE_FETEST(THIRD, XYZ, TET10);
INSTANTIATE_FETEST(THIRD, XYZ, HEX27);
INSTANTIATE_FETEST(THIRD, XYZ, PRISM18);
