Attributes {
    S1 {
        v3 {
          Int32 a1 32;
	}
    }
    GLOBAL {
	Int32 globalattr 177;
    }
    CoreMetadata {
        OrbitNumber {
            Int32 Value 375;
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
        RangeBeginningDate {
            String Value "1997/12/21";
            String Data_Location "PGE";
            String Mandatory "FALSE";
        }
    }
}


