#define dS3 {2 d6 hF
#define dR3 " "q91
#define dQ3 " "h1},
#define dP3 {1 d6 gQ
#define dO3 " >= "
#define dN3 " <= "
#define dM3 -40,40,
#define dL3 q12"  "
#define dK3 wV2"  "
#define dJ3 " "m3
#define dI3 " != "
#define dH3 " < "
#define dG3 oL2"  "
#define dF3 " +   "
#define dE3 mY2"  "
#define dD3 40000.0
#define dC3 "x*0+ "
#define dB3 ")) + "
#define dA3 mZ1") "
#define d93 h03" "
#define d83 dS1" "
#define d73 dZ" "
#define d63 "abs(x)"
#define d53 d43 o02
#define d43 "-125"
#define d33 d92"1 > "
#define d23 a72"1"dH3
#define d13 d82"0 > "
#define d03 a62"0"dH3
#define hZ3 "!x * !y"
#define hY3 wS2" !!y"
#define hX3 " if(x"o0
#define hW3 "-125)"
#define hV3 "!x & !y"
#define hU3 "!x | !y"
#define hT3 q4 Negneg
#define hS3 "abs"g51
#define hR3 "abs"aN1
#define hQ3 {1 d6 hF
#define hP3 g02"1 >= "
#define hO3 d72"1 <= "
#define hN3 qZ2"0 >= "
#define hM3 d62"0 <= "
#define hL3 "floor"wW2
#define hK3 "acos"g51
#define hJ3 "ceil"qF1
#define hI3 "y,y,x)"
#define hH3 "y,x,y)"
#define hG3 "25"o02
#define hF3 "y,"w02
#define hE3 o3"   "
#define hD3 hL1" "
#define hC3 "0.0625)"
#define hB3 hR3" "
#define hA3 "sin(x))"},
#define h93 "y,y,"oS2
#define h83 "if("qT1"  "
#define h73 "acos"oB g81
#define h63 "(5.0625 "
#define h53 mG1"        "
#define h43 "-0.015625)"
#define h33 d4"5.0625 "
#define h23 "y, 0,1"o02
#define h13 "0.0625"o02
#define h03 dF3" "
#define gZ3 "-0.015625"o02
#define gY3 q42},{1
#define gX3 2,-4,4,
#define gW3 )*fp_or(
#define gV3 1.1l))+
#define gU3 )*a;}q3
#define gT3 qO-hU))
#define gS3 -6,6,wB
#define gR3 1 qM,g3
#define gQ3 N(.1),
#define gP3 wJ"4"
#define gO3 fp_exp(x
#define gN3 q0(dK))
#define gM3 hQ1"))"
#define gL3 {1 w42
#define gK3 mD" | "
#define gJ3 +q0(6l))
#define gI3 Asinhf_deg
#define gH3 fp_cos(
#define gG3 gH3 y
#define gF3 -400,400,
#define gE3 Asinf_deg
#define gD3 Acosf_deg
#define gC3 1,-10,10,
#define gB3 1.061l),x
#define gA3 qM1" | "
#define g93 Acoshf_deg
#define g83 -1000,1000,
#define g73 N(3.0,0.0),
#define g63 +fp_min(x,
#define g53 h3"x)"
#define g43 );}}namespace
#define g33 N(-6.0,0.0),gD1
#define g23 4.0l d1
#define g13 4.0f d1
#define g03 q0(2.0l
#define qZ3 0l);}q3
#define qY3 wV gT x
#define qX3 log(1.1
#define qW3 d8 0l),
#define qV3 oH 0l),
#define qU3 ")*0"},
#define qT3 Abseq0,
#define qS3 ")*5"},
#define qR3 ")*a"},
#define qQ3 ")/a"},
#define qP3 Sqrneq0
#define qO3 q42" +"
#define qN3 "m_deg",
#define qM3 "hm_deg",
#define qL3 ")"mO"+"
#define qK3 {1 hZ
#define qJ3 "exp"g51
#define qI3 ") + ("
#define qH3 Gt1_abs
#define qG3 Gt0_abs
#define qF3 Ge1_abs
#define qE3 Ge0_abs
#define qD3 Cmp_sqr
#define qC3 Cmp_neg
#define qB3 "=-2)"q22
#define qA3 "=-2"o8
#define q93 Cmp_add
#define q83 Absneq0
#define q73 " + 1/"
#define q63 " + "o21"*"
#define q53 2 aG gQ
#define q43 "expex"
#define q33 -2,2,hF
#define q23 "acosh"
#define q13 "*z) +"
#define q03 "<=y &"
#define mZ2 "),if("
#define mY2 ",-"mG1
#define mX2 m7" | "
#define mW2 m7" & "
#define mV2 Xaddnot
#define mU2 Sqr_yxx
#define mT2 Sqr_xnx
#define mS2 Sqr_nxx
#define mR2 "x))"},
#define mQ2 Absnzlt
#define mP2 Absnzge
#define mO2 "x"gR
#define mN2 "x,y,z"
#define mM2 wJ"-4"
#define mL2 y,q0(6l
#define mK2 mflit7_1
#define mJ2 wH1);}q0
#define mI2 qC qA(
#define mH2 gM;}q0
#define mG2 *q0(0 gC1
#define mF2 mflit0_25
#define mE2 {using namespace FUNCTIONPARSERTYPES;q0
#define mD2 ));}q0
#define mC2 a51 wS
#define mB2 ))gT x
#define mA2 ))-hV1
#define m92 {1,-g2
#define m82 "xp"w9
#define m72 ")+(x"
#define m62 "exp("
#define m52 gD aA1
#define m42 "x",oF
#define m32 {1 d5
#define m22 mflit2_5
#define m12 q0(0))+
#define m02 q0(1))
#define aZ2 *q0(2))
#define aY2 d2r(wW
#define aX2 5),q0(4)
#define aW2 true q4
#define aV2 hA-1,1,
#define aU2 +fp_not(
#define aT2 *fp_sin(
#define aS2 fp_not(z
#define aR2 -q0 m01
#define aQ2 qZ1 gL)
#define aP2 qV1 gL)
#define aO2 fp_cosh(
#define aN2 ,y);}q3
#define aM2 (q0(0.75l)
#define aL2 (y+q0(1l
#define aK2 q0(0l qP
#define aJ2 qL x+mB1
#define aI2 "a,b",oF
#define aH2 "atan2"
#define aG2 qH3,
#define aF2 qG3,
#define aE2 qF3,
#define aD2 qE3,
#define aC2 q83,
#define aB2 "abs(b"
#define aA2 "abs(a"
#define a92 "(x*"gX2
#define a82 Multodiv
#define a72 " > 1"o8
#define a62 " > 0"o8
#define a52 oA"-5)"
#define a42 oA"5)"
#define a32 "(1))"
#define a22 "    8"
#define a12 N(.2)mK1
#define a02 N(.5)mK1
#define wZ2 qG1"))*"
#define wY2 "x+-x+-"
#define wX2 "log(x+"
#define wW2 "(x)"aC1
#define wV2 "7/2) +"
#define wU2 "(x*"qD1
#define wT2 N(0.25),
#define wS2 "!!x *"
#define wR2 "180/pi"
#define wQ2 dW",y,z"
#define wP2 Lt_or_ne
#define wO2 Lt_or_le
#define wN2 Lt_or_gt
#define wM2 Lt_or_ge
#define wL2 Lt_or_eq
#define wK2 Le_or_ne
#define wJ2 Le_or_eq
#define wI2 L_notnot
#define wH2 L_mulneg
#define wG2 L_mulabs
#define wF2 Ifmerge,
#define wE2 Gt_or_ne
#define wD2 Gt_or_le
#define wC2 Gt_or_ge
#define wB2 Gt_or_eq
#define wA2 Ge_or_ne
#define w92 Ge_or_le
#define w82 Ge_or_eq
#define w72 ") = "hY
#define w62 ") <= "hY
#define w52 ") > "hY
#define w42 ,0,1,gQ
#define w32 mN2 dY
#define w22 {3 w42
#define w12 "x,y"q6"/"
#define w02 "x"mF1
#define oZ2 "x",o6
#define oY2 mQ2,
#define oX2 "1,4,0"
#define oW2 mP2,
#define oV2 Xxsqrdup
#define oU2 Sqr_yxnx
#define oT2 Sqr_ynxx
#define oS2 "x)"},
#define oR2 =vars[1]
#define oQ2 gN;}q0
#define oP2 *x*x w7
#define oO2 (m02+
#define oN2 h0;}q0
#define oM2 " + (x*"
#define oL2 "x!=y) +"
#define oK2 dM qS qO
#define oJ2 dM qR qO
#define oI2 dM qQ qO
#define oH2 "*(x"
#define oG2 -10,10,dB1
#define oF2 "x,y"dY
#define oE2 {1,-5,5,
#define oD2 dM qU qO
#define oC2 qI gC dO))
#define oB2 qI-gC
#define oA2 "sinh"
#define o92 ,o6 dA" "
#define o82 ")"dI3 hY
#define o72 ") >= "hY
#define o62 (qT qO
#define o52 N(.1)mK1
#define o42 gC1 1.2l)*
#define o32 gC1 1.1l)*
#define o22 (qT qI gC
#define o12 {2,3,5,hF
#define o02 ")"},
#define dZ2 mflit1_1*
#define dY2 mflit1_5*
#define dX2 qW q0(d31
#define dW2 -mM qM qB
#define dV2 atan2l(
#define dU2 sqrtl(x*x
#define dT2 ((g42 mI)*
#define dS2 {3 d6 hF
#define dR2 0,qH"/sin"
#define dQ2 0 gG1
#define dP2 atan2f(
#define dO2 sqrtf(x*x
#define dN2 "^1506"},
#define dM2 "0.7"gH
#define dL2 +fp_less(
#define dK2 )*oH1*x*x
#define dJ2 ,o6",if("
#define dI2 q0(3l))
#define dH2 (fp_exp(
#define dG2 /gL a2-gF
#define dF2 /gL a2+gF
#define dE2 /gL)+mB
#define dD2 fp_tan(
#define dC2 ")/log("
#define dB2 "(1.0"
#define dA2 "(x) +"
#define d92 dH3"1"hZ1
#define d82 dH3"0"hZ1
#define d72 " >= 1"o8
#define d62 " >= 0"o8
#define d52 ")+x+("
#define d42 N(.15)mK1
#define d32 "   if(x"
#define d22 "(x^2"o02
#define d12 "pow(x"
#define d02 Nor2plus,
#define hZ2 Lt_and_ne
#define hY2 Lt_and_le
#define hX2 Lt_and_gt
#define hW2 Lt_and_ge
#define hV2 mD" & "
#define hU2 Lt_and_eq
#define hT2 Le_and_ne
#define hS2 Le_and_eq
#define hR2 Ifmerge2,
#define hQ2 Gt_and_ne
#define hP2 Gt_and_le
#define hO2 Gt_and_ge
#define hN2 Gt_and_eq
#define hM2 Ge_and_ne
#define hL2 Ge_and_le
#define hK2 Ge_and_eq
#define hJ2 ") > "dU1 oV
#define hI2 ") <= "dU1 aE
#define hH2 ")"dH3 dU1
#define hG2 " > 6)"oV
#define hF2 " > 6"o02
#define hE2 " = 6"o02
#define hD2 Notnotnot
#define hC2 Dupminmax
#define hB2 ,o6", y"
#define hA2 N(0.25)qM
#define h92 hW1 1.1f
#define h82 x dG)gC1
#define h72 q0(7l)
#define h62 fp_pow aG1
#define h52 fp_pow gN2
#define h42 gC1 1l)/
#define h32 fp_sqrt(
#define h22 q0(4l)
#define h12 h22 qP
#define h02 qS qI gC
#define gZ2 q0(1l)))
#define gY2 "(1,0,1"
#define gX2 "5"o02
#define gW2 ">-4)"wF
#define gV2 "<-4)"wD
#define gU2 "=-4)"wC
#define gT2 "cmp_ex"
#define gS2 "    16"
#define gR2 "pi/180"
#define gQ2 qM1" & "
#define gP2 h71"*y)"
#define gO2 {2 d6 wB
#define gN2 dH2 a0),
#define gM2 q0(0l)
#define gL2 N(1.0,0.0)qM,q2
#define gK2 x+x+x+x+
#define gJ2 ,q2 mV2
#define gI2 +(fp_sin(oF1
#define gH2 (x,fp_max(
#define gG2 qL fp_and(x
#define gF2 gM2;}q3
#define gE2 (d2r(1.1)hY1
#define gD2 q0(0.5l
#define gC2 const q0
#define gB2 N(0.01)gF1
#define gA2 y),w3,y)gC1
#define g92 fp_max(q0(
#define g82 oS 1l);}q3
#define g72 "(-"oS2
#define g62 qW fp_not(
#define g52 *q0(5l qP
#define g42 q0(1l)/
#define g32 1l))qR q0(1l),
#define g22 1l))qU q0(1l),
#define g12 1l)d8 1l),
#define g02 " <= 1"hZ1
#define qZ2 " <= 0"hZ1
#define qY2 Cmp_mulpos
#define qX2 "<4)"wD
#define qW2 "=4)"wC
#define qV2 Cmp_mulneg
#define qU2 "(x*z+17)"
#define qT2 wQ2 dY
#define qS2 "   10*"o6
#define qR2 "sub(sub("
#define qQ2 Nand2plus,
#define qP2 Ifmerge2b,
#define qO2 " >= 6)"aD
#define qN2 " <= 6)"aE
#define qM2 dH3"6)"
#define qL2 " <= 6"o02
#define qK2 " >= 6"o02
#define qJ2 Notnotnot2
#define qI2 Dupxmuladd
#define qH2 Dupminmax3
#define qG2 Dupminmax2
#define qF2 Dupaddmul7
#define qE2 N(2.0,0.0)
#define qD2 "z+y+z+y+"
#define qC2 qW fp_less(
#define qB2 -fp_int(
#define qA2 dD2 y)
#define q92 N(0.1)gF1
#define q82 fp_atan2(
#define q72 gL/q0(3l)
#define q62 qW q0(h7
#define q52 fp_abs(a
#define q42 "sin(x)"
#define q32 "<=-4)"wE
#define q22 h03"2"
#define q12 "sin("wX
#define q02 " "gO",2)"
#define mZ1 " "gO",3"
#define mY1 "(x>4"o02
#define mX1 gX3 gQ
#define mW1 mflit0_7 d1
#define mV1 dE y:x gC1
#define mU1 dE x:y gC1
#define mT1 dE y:wA
#define mS1 fp_less(q0(
#define mR1 N(4.0,0.0),
#define mQ1 " & (y+2"o02
#define mP1 ,"log(x)"},
#define mO1 " cos(x)"},
#define mN1 Cmp_sqr_neg
#define mM1 ",max(x,ma"
#define mL1 ")"m71
#define mK1 qM,qZ
#define mJ1 dW q6"/pow"
#define mI1 2,2,gR3
#define mH1 Xaddnotnot,
#define mG1 "x)) +"
#define mF1 ",y"o02
#define mE1 Addconstmul
#define mD1 "dupminmax"
#define mC1 ))+fp_equal(gM2,
#define mB1 y;}q3
#define mA1 "*("wN
#define m91 w9"  32"
#define m81 "*("aR
#define m71 "^(1/"
#define m61 +mflit1_2*
#define m51 gG3)+
#define m41 fp_sin(y)+
#define m31 fp_equal(x,y
#define m21 fp_or(y,z)
#define m11 (1.1f d1
#define m01 wV+q0(
#define aZ1 1l))+oH 1l),
#define aY1 fp_sin(x
#define aX1 oB2 hI))
#define aW1 x),hP gL))
#define aV1 x),gU gL
#define aU1 gB h8 gL))
#define aT1 gB-q0(2l
#define aS1 gB-gL)
#define aR1 x),h8 gL
#define aQ1 d2r(x qP
#define aP1 d6 gR3
#define aO1 ,"(sin(x)"
#define aN1 oB d63
#define aM1 ,"(abs(x)"
#define aL1 h4")"
#define aK1 d9"pow"
#define aJ1 {1,-4,4,wB
#define aI1 "*((-x)"
#define aH1 "<=4)"wE
#define aG1 (x*z+q0(17l),
#define aF1 {1,-36,36,wB
#define aE1 {1 d6 wB
#define aD1 {gC3 wB
#define aC1 ",ceil(x))+"
#define aB1 hL1 o0"))"},
#define aA1 "cmple_"
#define a91 "cmpeq_"
#define a81 "cbrt(x^6"
#define a71 ")), int("
#define a61 a51 g0
#define a51 dW",y"
#define a41 Mergemulabs,
#define a31 3 d6 gQ
#define a21 Cmpzz_minmax
#define a11 Cmpne_minmax
#define a01 dI3"6)"
#define wZ1 Cmplt_minmax
#define wY1 Cmple_minmax
#define wX1 Cmpgt_minmax
#define wW1 Cmpge_minmax
#define wV1 wJ"4*y)"
#define wU1 Cmpeq_minmax
#define wT1 Addnegmulpos
#define wS1 Addnegmulneg
#define wR1 aG 2 qM,q2
#define wQ1 Absnotnotnot
#define wP1 "y) + x/"
#define wO1 {1,q8
#define wN1 w9 gS2
#define wM1 w9 a22
#define wL1 *fp_and(
#define wK1 gG3*q0(1.5l))
#define wJ1 (q0(0.0l))+
#define wI1 " + "o11"*"
#define wH1 mflit0_5
#define wG1 (1.1l d1
#define wF1 qW r2d(
#define wE1 *x,q0(25l)gC1
#define wD1 (x);}q0
#define wC1 ")"dI3 dU1 dD
#define wB1 ") >= "dU1 aD
#define wA1 {2,q9
#define w91 10,10,gR3
#define w81 If_join_mul2,
#define w71 If_join_add2,
#define w61 Cmpzz_add_imm
#define w51 Cmpne_add_imm
#define w41 Cmplt_add_imm
#define w31 Cmple_add_imm
#define w21 Cmpgt_add_imm
#define w11 Cmpge_add_imm
#define w01 Cmpeq_add_imm
#define oZ1 ,N(0.25,0.0)
#define oY1 fp_and(y,z)
#define oX1 qL q0(h7 x*
#define oW1 "!=4"o02
#define oV1 " "gO",-2)"
#define oU1 " "gO",-3)"
#define oT1 q2 Mixedminmax,
#define oS1 "(x = y"o02
#define oR1 oN"(abs(x))"
#define oQ1 oN"(x)"
#define oP1 {2 aG 2 qM q4
#define oO1 "x,y"g0
#define oN1 " "wV1
#define oM1 q0(5)gC1 1)/
#define oL1 {1,N(-5.0,0.0),N(5.0,0.0),qE2 qM,q2
#define oK1 "x"q6"/"
#define oJ1 q0(fp_abs(x)
#define oI1 wF1 q0
#define oH1 fp_pow(o2
#define oG1 fp_pow(x*x
#define oF1 x)+gG3))*
#define oE1 0l))qR gM2,
#define oD1 0l))qU gM2,
#define oC1 /q0(3l)hI
#define oB1 x),-q0(2l
#define oA1 gD"cmpne_"
#define o91 gD"cmplt_"
#define o81 gD"cmpgt_"
#define o71 gD"cmpge_"
#define o61 "1.1^x*4.1"o02
#define o51 "!=-2"o02
#define o41 w9"    4"
#define o31 w9"    2"
#define o21 "sin(x-pi"
#define o11 "sin(x+pi"
#define o01 "((-5.1)*x*y)"
#define dZ1 0,q7"/pow"
#define dY1 If_extract_mul
#define dX1 If_extract_min
#define dW1 If_extract_add
#define dV1 If_extract_abs
#define dU1 "(y+6))"
#define dT1 mM2"*y)"
#define dS1 "_rev",o6
#define dR1 Addmulconstmul
#define dQ1 N(0.05)qM qB
#define dP1 d01 h42
#define dO1 qW fp_nequal(
#define dN1 fp_lessOrEq(
#define dM1 -6,6,N(0.5)qM,qG
#define dL1 q0(4l qP
#define dK1 q0(4l qF
#define dJ1 "(x"dI3"y"o02
#define dI1 "*(if"hQ1")"
#define dH1 d9"powx"
#define dG1 "(2))"},
#define dF1 " cos(x-pi*"
#define dE1 ",y"q6"/pow"
#define dD1 "*(5+"o6
#define dC1 fp_not(-fp_not(
#define dB1 1 mK1
#define dA1 If_extract_mul2
#define d91 If_extract_mul1
#define d81 If_extract_add2
#define d71 If_extract_add1
#define d61 fp_notNot(x
#define d51 fp_abs(x qP
#define d41 ">=4)"dJ3
#define d31 0x0001)*fp_less(
#define d21 *x,q0(25l qP
#define d11 userDefFuncSqr<q0>((
#define d01 q0(5l)
#define hZ1 ") +  8*("
#define hY1 )+x;}q3
#define hX1 },{1,0,1,1 qM,hG
#define hW1 qW logf(
#define hV1 fp_int(q0(
#define hU1 gC1 5l);}q3
#define hT1 *d01;}q3
#define hS1 5l),dI2+x
#define hR1 x),-gL)
#define hQ1 "(1,1,1"
#define hP1 "*(if(1,0,0)"
#define hO1 gD"cmpzz_pow"
#define hN1 "(x <= y)"
#define hM1 Cmpzz_minmax_rev
#define hL1 " if(x"
#define hK1 Cmpzz_addadd_imm
#define hJ1 Cmpne_minmax_rev
#define hI1 Cmpne_addadd_imm
#define hH1 Cmplt_minmax_rev
#define hG1 Cmplt_addadd_imm
#define hF1 Cmple_minmax_rev
#define hE1 Cmple_addadd_imm
#define hD1 Cmpgt_minmax_rev
#define hC1 Cmpgt_addadd_imm
#define hB1 Cmpge_minmax_rev
#define hA1 Cmpge_addadd_imm
#define h91 Cmpeq_minmax_rev
#define h81 Cmpeq_addadd_imm
#define h71 " "mM2
#define h61 o7"+y)"
#define h51 40,40,3 qM,qG
#define h41 "((1/   abs(b))*"
#define h31 If_extract_or2_l,
#define h21 If_extract_or1_l,
#define h11 Cmpzz_mul_imm_pos
#define h01 Cmpzz_mul_imm_neg
#define gZ1 Cmpzz_add_reduce,
#define gY1 Cmpne_mul_imm_pos
#define gX1 Cmpne_mul_imm_neg
#define gW1 Cmpne_add_reduce,
#define gV1 Cmplt_mul_imm_pos
#define gU1 Cmplt_mul_imm_neg
#define gT1 Cmplt_add_reduce,
#define gS1 Cmple_mul_imm_pos
#define gR1 Cmple_mul_imm_neg
#define gQ1 Cmple_add_reduce,
#define gP1 Cmpgt_mul_imm_pos
#define gO1 Cmpgt_mul_imm_neg
#define gN1 Cmpgt_add_reduce,
#define gM1 Cmpge_mul_imm_pos
#define gL1 Cmpge_mul_imm_neg
#define gK1 Cmpge_add_reduce,
#define gJ1 Cmpeq_mul_imm_pos
#define gI1 Cmpeq_mul_imm_neg
#define gH1 Cmpeq_add_reduce,
#define gG1 ,qH"/"
#define gF1 ,true qB
#define gE1 ,N(0.5,0.0)qM,
#define gD1 N(6.0,0.0)gE1 qG
#define gC1 )+q0(
#define gB1 fp_acos(x
#define gA1 gB1),gL)
#define g91 log(x+sqrt(x*x
#define g81 "acos(x)"
#define g71 "pow(-4,y))"
#define g61 {1 aG N(0.41)qM q4
#define g51 "(x))"},
#define g41 gG3*mflit1_5)
#define g31 d2r(1.1l)d1
#define g21 d2r(1.1f)d1
#define g11 d2r(x mD2
#define g01 fp_greater(
#define qZ1 fp_tanh(x),
#define qY1 x*x),-q0(16l
#define qX1 x*x),q0(16l
#define qW1 gO3),-
#define qV1 fp_asin(x),
#define qU1 hJ x+y+x+x-z+x;}q3
#define qT1 "1,0,0)) +"
#define qS1 "*(sinh(x)"
#define qR1 "*(atan(x)"
#define qQ1 "(pow(2,x)"
#define qP1 ,N(0.0,0.0)qK
#define qO1 If_extract_or2_nl,
#define qN1 qN"if_ex"
#define qM1 ,"(x > y)"
#define qL1 If_extract_or1_nl,
#define qK1 If_extract_and2_l,
#define qJ1 If_extract_and1_l,
#define qI1 fp_less(y,q0(1l
#define qH1 dN1 q0(
#define qG1 "(sin(x)+cos(y"
#define qF1 "(x),floor(x))+"
#define qE1 ") + cos(x+pi*"
#define qD1 "if(1,-1,0))"},
#define qC1 0,4,N(0.1)qM q4
#define qB1 (fp_sin(y),gG3)):
#define qA1 fp_not(x)*fp_not(y)
#define q91 "pow(1.5,x))"
#define q81 If_extract_and2_nl,
#define q71 If_extract_and1_nl,
#define q61 )*(d01+(
#define q51 {2,-460,100,8 qM,qG
#define q41 (aY1)+mflit1_2)
#define q31 ,gM2 gJ x:-x)gC1
#define q21 Cmpzz_mulmul_imm_pos
#define q11 Cmpzz_mulmul_imm_neg
#define q01 Cmpne_mulmul_imm_pos
#define mZ Cmpne_mulmul_imm_neg
#define mY Cmplt_mulmul_imm_pos
#define mX Cmplt_mulmul_imm_neg
#define mW Cmple_mulmul_imm_pos
#define mV Cmple_mulmul_imm_neg
#define mU Cmpgt_mulmul_imm_pos
#define mT Cmpgt_mulmul_imm_neg
#define mS Cmpge_mulmul_imm_pos
#define mR Cmpge_mulmul_imm_neg
#define mQ Cmpeq_mulmul_imm_pos
#define mP Cmpeq_mulmul_imm_neg
#define mO "     "
#define mN +q0(0x0020)*fp_equal(
#define mM 40000,40000,5
#define mL N(0.01)qM qB
#define mK dE x:y);}q3
#define mJ ((x*q0(g8
#define mI fp_abs(b)
#define mH fp_exp2(x),-
#define mG mN2 q6"/"
#define mF 2,-2,2,gQ
#define mE (fp_truth(
#define mD ,"(x"dH3"y)"
#define mC wQ2 q6"/"
#define mB gH3 x
#define mA N(0.1)qM qB
#define m9 qX3+sqrt(1.1*
#define m8 "(1.1"gH qM q4
#define m7 "(x >= y)"
#define m6 +q0(0x0010)*fp_nequal(
#define m5 ,gM2 gJ-x:x)gC1
#define m4 qI 1.1l),x)*q0(4.1l qP
#define m3 "+ 32"
#define m2 +q0(0x0008)*fp_greaterOrEq(
#define m1 +q0(0x0004)*g01
#define m0 qW logl(
#define aZ N(1e-6),400,mA
#define aY aX,h22 gJ
#define aX fp_less(x
#define aW x*x,-q0(125l qP
#define aV qW fp_greaterOrEq(
#define aU "^6.1))"
#define aT ">=-2) +  32"
#define aS "<-2)"h03"4"
#define aR "exp(x)"
#define aQ "*((1-x+x+5)"
#define aP -10,10,N(0.8)qM q4
#define aO +q0(0x0002)*dN1
#define aN fp_or(fp_not(x),fp_not(y
#define aM {2,-g2
#define aL d6 2 qM,q5
#define aK 0,q7"/sin"
#define aJ ,N(-1.0,0.0)qK
#define aI {1,N(0.5),3,oZ
#define aH N(-.1),gQ3 N(0.01)qM q4
#define aG ,-3,3,
#define aF {1 aG oZ
#define aE g1"0004 *"
#define aD g1"0010 * "
#define aC g1"0002 *"
#define aB *x*x,-q0(125l)gC1
#define aA qX"+y+"qD2"z"
#define a9 fp_and(fp_not(x),fp_not(y
#define a8 d61)*fp_notNot(y)
#define a7 /gL*x*-d01),
#define a6 /gL*x*d01),
#define a5 ">-2) +"gS2
#define a4 "<=-2) +"a22
#define a3 g71},
#define a2 )+aY1
#define a1 fp_pow((q0(-5.1l))*x
#define a0 q0(1.0l)
#define wZ qL fp_pow((mflitm5_1)*x*y,
#define wY N(-1.25),N(1.25),hA2
#define wX "0.75)) +"
#define wW mflit1_1)d1
#define wV (4l),y gJ3
#define wU ,0 g5
#define wT dW,"03unit_constants/"
#define wS ,"02unit_functions"
#define wR 0 mC2
#define wQ ,g42 q0(
#define wP A_very_long_variable_name_1
#define wO "*((x*x)"
#define wN "log2(x)"
#define wM "1.1)+x"},
#define wL "1.1"gH,aW2
#define wK q91},
#define wJ "((x*"
#define wI -2,2,1 qM,qG
#define wH {2 w42
#define wG {2,qJ
#define wF dF3"16"
#define wE dF3"8"
#define wD dF3"4"
#define wC dF3"2"
#define wB 1 qM q4
#define wA x);}q3
#define w9 "(2)) +"
#define w8 N(-7.25),N(7.25),N(0.5)qM,qG
#define w7 ,q0(1)/q0(
#define w6 "((-1.061)^x))"
#define w5 "(1.061^(x/3)))"
#define w4 qO-gL),q0(0.0625l)gC1
#define w3 fp_nequal(x
#define w2 x)gC1 4l)*fp_less
#define w1 aY1),q0(
#define w0 fp_abs(x),q0(
#define oZ N(0.5)qM q4
#define oY 1 d6 oZ
#define oX {1 aG N(0.1)qM q4
#define oW 0 wT
#define oV g1"0008 *"
#define oU "sin(x))"h03"4*(sin(x)"
#define oT h3"(x/3))"
#define oS *gM2+y*q0(0l gC1
#define oR qI 2l),x),qI-4l),y))
#define oQ (qC g4
#define oP gB1),q0(
#define oO "*(tanh(x)"
#define oN "*(log"
#define oM "*(a"q42
#define oL "*("g81
#define oK 5.0625l),qI 1.5l),x))
#define oJ x=vars[2],&y=vars[3]qA(o5 mE y gJ
#define oI g01 x
#define oH gL*qH1
#define oG {2,q8
#define oF "50regressions/"
#define oE oB2),qI-gB3
#define oD gO3),fp_exp(gL
#define oC 3 aJ
#define oB "(x))"h03"4*("
#define oA "*((x/2*x*"
#define o9 "*(exp2(x)"
#define o8 ")"q22"*("
#define o7 "((x+4"
#define o6 "if(x"
#define o5 fp_truth(x gJ
#define o4 dN1 x
#define o3 "(x^-6.1)) +"
#define o2 x*x*x*x*x
#define o1 qO-gL),q0(0.0625l qP
#define o0 "<4, cos(y),sin(y+1"
#define dZ "((((x*5/2)+x*x-2))"
#define dY ,"99misc/"
#define dX a51 dY
#define dW ,0,"x"
#define dV dW dY
#define dU ",y,z"q6"/if_ex"
#define dT N(-3.0,0.0),g73 gL2
#define dS N(-2.0,0.0),qE2 gE1 q2
#define dR qI 2l),x),qI-4l),y qP
#define dQ fp_sinh(x),fp_sinh(gL
#define dP (fp_cos aL2)),fp_sin aL2)qP
#define dO /dI2,qI-gB3
#define dN fp_exp2(x),fp_exp2(gL
#define dM h22)
#define dL fp_atan(x),fp_atan(gL
#define dK 1l)-x+x+d01),q0(4l
#define dJ "*(log10(x)"
#define dI 5.0625l),qI 1.5l),x qP
#define dH h22*mL2)gC1
#define dG +h22+mL2
#define dF h22*mL2 qP
#define dE ,y)!=gM2)?
#define dD " +  0x0020 * "
#define dC ,"0x0001 *"
#define dB ,N(-7.25,0.0),N(7.25,0.0)gE1 qG
#define dA "<4, sin(y),cos(y+1))"
#define d9 0 g5"cmp_"
#define d8 gC1 8l)*fp_greaterOrEq(q0(
#define d7 qO-dI2,-q0(0.015625l
#define d6 ,-1,1,
#define d5 d6 hA2 q4
#define d4 "pow_imm_pospos_base","("
#define d3 "pow_imm_pospos",gO",2)"
#define d2 ,0 wU
#define d1 )+x;}q0
#define d0 "pow_imm_posneg",gO",3)"
#define hZ ,0,1,wB
#define hY dU1},
#define hX fp_greaterOrEq(x
#define hW "*(log2(abs(x))"
#define hV gG qO q0(6.1l)
#define hU gG qO-q0(6.1l)
#define hT "pow_imm_negpos",gO",-2)"
#define hS "pow_imm_negneg",gO",-3)"
#define hR "*(log10(abs(x))"
#define hQ oE2 2 qM,q2
#define hP fp_log(
#define hO {2,N(-4.0,0.0),mR1 gL2
#define hN 2 qP1
#define hM 2,N(-3.0,0.0),g73 qE2 qM,q2
#define hL qZ1 fp_tanh aM2
#define hK qV1 fp_asin aM2
#define hJ (qD,&y oR2,&z=vars[2]qA
#define hI ),qI gB3/q0(3l)
#define hH gB1),fp_acos aM2
#define hG cpp_03unit_constants::
#define hF N(0.5)qM,q2
#define hE {1,wT2 3,hA2 q4
#define hD N(-6.0,-3.0),N(6.0,+3.0),N(0.5,+0.25)qM,qG
#define hC "powpow_imm_base",qQ1
#define hB "a,b",qE
#define hA "(x)"},{1,
#define h9 N(-1.0,0.0),N(1.0,0.0)gE1 q2
#define h8 fp_log2(
#define h7 0x0001l)*fp_less(
#define h6 N(-1.75),N(1.75),hA2,qG
#define h5 "*((x^5.1)"
#define h4 "*((x^-5.1"
#define h3 "*((2.051^"
#define h2 h22,y+q0(6l qP
#define h1 wJ"5/2)+abs(x)))"
#define h0 -q0(2)),mflit0_0625)
#define gZ g73 N(5.0,0.0)gE1 q2
#define gY (gK2 gK2 x+x+x+y gA+y+z+y+z+y+z+y+z)
#define gX {1,N(1e-6,0.0),N(4000.0,0.0),N(0.1,0.0)qM qB
#define gW 0x0010l)*fp_nequal(
#define gV mflit1_1 d1
#define gU fp_log10(
#define gT +q0(0x0020l)*fp_equal(
#define gS 0x0004l)*g01
#define gR ",y","10optimizer_bytecode/"
#define gQ 1 qM,q2
#define gP 0x0002l)*dN1
#define gO "(pow(x"
#define gN mflit5_0625,fp_pow(mflit1_5,x))
#define gM qO-q0(3)),-mflit0_015625)
#define gL q0(2l)
#define gK N(-1.75,0.0),N(1.75,0.0)oZ1 qM,qG
#define gJ )!=gM2?
#define gI 0x0008l)*fp_greaterOrEq(
#define gH ")+x"},{1,0,1,1
#define gG q0(5.1l)),
#define gF fp_const_pi<q0>()
#define gE N(-2.0,0.0),qE2,gL2
#define gD 0,oK1
#define gC 2.051l),x
#define gB fp_abs(x)),
#define gA +z+y+z+y+z+y+z+y+z
#define g9 {1,N(-0.7),N(0.7),N(0.28)qM q4
#define g8 5l)/gL)+x*x-gL),((x*d01/gL)+fp_abs(x)
#define g7 "*(((-2.051)^x)"
#define g6 N(-1.0,0.0),N(1.0,0.0),qE2 qM,q5
#define g5 ,q7"/"
#define g4 ,&b oR2 qA
#define g3 cpp_50regressions::
#define g2 15,15,2 qM,q5
#define g1 h03"0x"
#define g0 ,"01unit_operators/"
#define qZ cpp_99misc::
#define qY qD,&y oR2,&z=vars[2]qA o5
#define qX "+"qD2 qD2"z+y+z"
#define qW (qD qA
#define qV qD qA q0::
#define qU +gL*fp_less(
#define qT qD qA q0(1l)*fp_equal(
#define qS +q0(16l)*fp_greaterOrEq(
#define qR +q0(8l)*g01
#define qQ +h22*dN1
#define qP ));}q3
#define qO fp_pow(x,
#define qN ,w12
#define qM ,false
#define qL (qD,&y oR2 qA
#define qK ,N(1.0,0.0),gL2
#define qJ -6,6,gQ
#define qI fp_pow(q0(
#define qH 0,"x"wS
#define qG cpp_01unit_operators::
#define qF )gC1 32l)*fp_nequal(
#define qE "11optimizer_constaddmul/"
#define qD gC2 q1
#define qC gC2*vars){gC2&a=vars[0]
#define qB ,cpp_02unit_functions::
#define qA ;return
#define q9 N(-15.0,0.0),N(15.0,0.0),qE2 qM,q5
#define q8 N(-6.0,0.0),N(6.0,0.0),gL2
#define q7 "x","10optimizer_bytecode"
#define q6 ,"20optimizer_optimizations"
#define q5 cpp_11optimizer_constaddmul::
#define q4 ,cpp_10optimizer_bytecode::
#define q3 template<typename q0>static q0
#define q2 cpp_20optimizer_optimizations::
#define q1 *vars){gC2&x=vars[0]
#define q0 Value_t
#define APP(x,y) x##y
#define S {2,-h51 Add_i,0,qG Add_i,oO1"add_i","x+y"},
#define T {3,-h51 Addsub_i,0,qG Addsub_i,mN2 g0"addsub_i","x+y+x+x-z+x"},
#define U {2,wI And_i,0,qG And_i,oO1"and_i","x&y"},
#define W {2,wI Cmpeq_i,0,qG Cmpeq_i,oO1"cmpeq_i","x=y"},
#define Y {2,wI Cmpge_i,0,qG Cmpge_i,oO1"cmpge_i","x>=y"},
#define S1 {2,wI Cmpgt_i,0,qG Cmpgt_i,oO1"cmpgt_i","x>y"},
#define T1 {2,wI Cmple_i,0,qG Cmple_i,oO1"cmple_i","x<=y"},
#define U1 {2,wI Cmplt_i,0,qG Cmplt_i,oO1"cmplt_i","x<y"},
#define W1 {2,wI Cmpne_i,0,qG Cmpne_i,oO1"cmpne_i","x!=y"},
#define Y1 q51 Div_i,0,qG Div_i,oO1"div_i","x/(y+3"o02
#define S2 {3,-46,40,2 qM,qG Divmul_i,0,qG Divmul_i,mN2 g0"divmul_i","x*y*x*x/(z+3)*(x+4"o02
#define T2 {1,-41,40,3 qM,qG Inv_i,0,qG Inv_i,"x"g0"inv_i","1/x"},
#define U2 q51 Mod_i,0,qG Mod_i,"x,z"g0"mod_i","x%(z+3"o02
#define W2 q51 Mul_i,0,qG Mul_i,oO1"mul_i","x*(y+4"o02
#define Y2 {1,-h51 Neg_i,0,qG Neg_i,"x"g0"neg_i","-x"},
#define S3 {1,wI Not_i,0,qG Not_i,"x"g0"not_i","!x"},
#define T3 {1,wI Notnot_i,0,qG Notnot_i,"x"g0"notnot_i","!!x"},
#define U3 {2,wI Or_i,0,qG Or_i,oO1"or_i","x|y"},
#define W3 {2,-h51 Sub_i,0,qG Sub_i,oO1"sub_i","x-y"},
#define Y3 {1,-40000,40000,1 qM qB Abs_i,0 qB Abs_i,"x"wS"/abs_i",d63},
#define S4 {3,-2,2,1 qM qB If_i,0 qB If_i,mN2 wS"/if_i",o6",y,z"o02
#define T4 {gX3 1 qM qB Max qB Max qB Max,"x,y"wS"/max","max(x"mF1
#define U4 {gX3 1 qM qB Min qB Min qB Min,"x,y"wS"/min","min(x"mF1
#define W4 qK3 Abs q4 Abs q4 Abs g5"abs","(abs(-3))+x"},
#define Y4 aE1 Absnot q4 Absnot q4 Absnot g5"absnot","!(abs"g51
#define S5 aE1 wQ1 q4 wQ1 q4 wQ1 g5"absnotnotnot","!(!!((x*x)))"},
#define T5 oE2 wB mP2 q4 mP2 q4 mP2 g5"absnzge","sub(abs(x) >= 4, "d63" >= 0"o02
#define U5 oE2 wB mQ2 q4 mQ2 q4 mQ2 g5"absnzlt","sub(abs(x)"dH3"4, "d63 dH3"0"o02
#define W5 aE1 Abssqr q4 Abssqr q4 Abssqr g5"abssqr","abs(x)*abs(x)"},
#define Y5 {1 aG wB qF2 q4 qF2 q4 qF2 g5"dupaddmul7","(x+x)*7"},
#define S6 aD1 hC2 q4 hC2 q4 hC2 g5 mD1,"sub(min(x,x), max(x,"mR2
#define T6 aD1 qG2 q4 qG2 q4 qG2 g5 mD1"2","sub(x+min(x,x), x+max(x,"mR2
#define U6 {2,-2,2,wB qH2 q4 qH2 q4 qH2,mO2 mD1"3","sub(min(min(y,x),x), max(max(y,x),"mR2
#define W6 aD1 qI2 q4 qI2 q4 qI2 g5"dupxmuladd","x+(x*4"o02
#define Y6 oP1 Invmul q4 Invmul q4 Invmul,mO2"invmul","y*(1/x)"},
#define S7 qK3 Max q4 Max q4 Max g5"max","max(5,4)+x"},
#define T7 qK3 Min q4 Min q4 Min g5"min","min(4,5)+x"},
#define U7 qK3 Mul2 q4 Mul2 q4 Mul2 g5"mul2","x*2"},
#define W7 {2 aG wB Mul4 q4 Mul4 q4 Mul4,mO2"mul4","y*(x*2)*2 + (y*2)*2"},
#define Y7 aE1 Negabs q4 Negabs q4 Negabs g5"negabs","abs"g72
#define S8 aE1 Negdiv q4 Negdiv q4 Negdiv g5"negdiv","(-x)/5"},
#define T8 {1 aG 2 qM hT3 hT3 hT3 g5"negneg","-(-(-(-(-(-(x))))))"},
#define U8 aE1 Negnot q4 Negnot q4 Negnot g5"negnot","!"g72
#define W8 aE1 Negsqr q4 Negsqr q4 Negsqr g5"negsqr","(-x)*(-"oS2
#define Y8 {2 hZ Not_eq q4 Not_eq q4 Not_eq,mO2"not_eq","!"oS1
#define S9 {2 hZ Not_ge q4 Not_ge q4 Not_ge,mO2"not_ge","!"m7},
#define T9 {2 hZ Not_gt q4 Not_gt q4 Not_gt,mO2"not_gt","!(x > y"o02
#define U9 {2 hZ Not_le q4 Not_le q4 Not_le,mO2"not_le","!"hN1},
#define W9 {2 hZ Not_lt q4 Not_lt q4 Not_lt,mO2"not_lt","!(x"dH3"y"o02
#define Y9 {2 hZ Not_ne q4 Not_ne q4 Not_ne,mO2"not_ne","!"dJ1
#define SA aE1 Notnot q4 Notnot q4 Notnot g5"notnot","!!(x)"},
#define TA aE1 hD2 q4 hD2 q4 hD2 g5"notnotnot","!!!(x)"},
#define UA aE1 qJ2 q4 qJ2 q4 qJ2 g5"notnotnot2","!x&!x"},
#define WA aE1 mS2 q4 mS2 q4 mS2 g5"sqr_nxx","(-x)*x"},
#define YA aE1 mT2 q4 mT2 q4 mT2 g5"sqr_xnx","x*(-"oS2
#define SB aE1 Sqr_xx q4 Sqr_xx q4 Sqr_xx g5"sqr_xx","x*x"},
#define TB gO2 oT2 q4 oT2 q4 oT2,mO2"sqr_ynxx","y*-x*x"},
#define UB gO2 oU2 q4 oU2 q4 oU2,mO2"sqr_yxnx","y*x*-x"},
#define WB gO2 mU2 q4 mU2 q4 mU2,mO2"sqr_yxx","y*x*x"},
#define YB oE2 wB mV2 q4 mV2 q4 mV2,q7"/xaddnot","!(x+4"o02
#define SC oE2 wB Xaddnotnot q4 Xaddnotnot q4 mH1 q7"/xaddnotnot","!!(x+4"o02
#define TC aE1 Xxdup q4 Xxdup q4 Xxdup,q7"/xxdup","sub(x,"oS2
#define UC gO2 oV2 q4 oV2 q4 oV2,"x,y","10optimizer_bytecode/xxsqrdup","y*abs(x)*abs(x)"},
#define WC oE2 gQ oW2 q2 oW2 q2 oW2 oK1"absnzge","sub(abs(x) >= if("oX2"), "d63" >= (if(1,1,0)-1))"},
#define YC oE2 gQ oY2 q2 oY2 q2 oY2 oK1"absnzlt","sub(abs(x)"dH3"if("oX2"), "d63 dH3"(if(1,1,0)-1))"},
#define SD {2 wR1 mE1,q2 mE1,q2 mE1 qN"addconstmul","5*(if("oX2")+x+y"o02
#define TD {2 wR1 dR1,q2 dR1,q2 dR1 qN"addmulconstmul","5*(if("oX2")*y+x)"},
#define UD {2 wR1 wS1,q2 wS1,q2 wS1 qN"addnegmulneg","-5 + (if(1,5,0)*x*y"o02
#define WD {2 wR1 wT1,q2 wT1,q2 wT1 qN"addnegmulpos","(if(1,-5,0)*y"qI3"if(1,5,0)*x)"},
#define YD wG w01,q2 w01,q2 w01 qN"cmpeq_add_imm",h61 hE2
#define SE {1,qJ gH1 q2 gH1 q2 gH1 oK1"cmpeq_add_reduce",d73"="dQ3
#define TE wG h81,q2 h81,q2 h81 qN"cmpeq_addadd_imm",o7 w72
#define UE wH wU1,q2 wU1,q2 wU1 qN"cmpeq_minma"oZ2" = "hF3
#define WE wH h91,q2 h91,q2 h91 qN"cmpeq_minmax"d83"= "h93
#define YE wG gI1,q2 gI1,q2 gI1 qN"cmpeq_mul_imm_neg",dT1 hE2
#define SF wG gJ1,q2 gJ1,q2 gJ1 qN"cmpeq_mul_imm_pos",wV1 hE2
#define TF wG mP,q2 mP,q2 mP qN"cmpeq_mulmul_imm_neg",mM2 w72
#define UF wG mQ,q2 mQ,q2 mQ qN"cmpeq_mulmul_imm_pos",gP3 w72
#define WF wG w11,q2 w11,q2 w11 qN"cmpge_add_imm",h61 qK2
#define YF {1,qJ gK1 q2 gK1 q2 gK1 oK1"cmpge_add_reduce",d73">="dQ3
#define SG wG hA1,q2 hA1,q2 hA1 qN"cmpge_addadd_imm",o7 o72
#define TG wH wW1,q2 wW1,q2 wW1 qN"cmpge_minma"oZ2 dO3 hF3
#define UG wH hB1,q2 hB1,q2 hB1 qN"cmpge_minmax"d83">= "h93
#define WG wG gL1,q2 gL1,q2 gL1 qN"cmpge_mul_imm_neg",dT1 qK2
#define YG wG gM1,q2 gM1,q2 gM1 qN"cmpge_mul_imm_pos",wV1 qK2
#define SH wG mR,q2 mR,q2 mR qN"cmpge_mulmul_imm_neg",mM2 o72
#define TH wG mS,q2 mS,q2 mS qN"cmpge_mulmul_imm_pos",gP3 o72
#define UH wG w21,q2 w21,q2 w21 qN"cmpgt_add_imm",h61 hF2
#define WH {1,qJ gN1 q2 gN1 q2 gN1 oK1"cmpgt_add_reduce",d73">"dQ3
#define YH wG hC1,q2 hC1,q2 hC1 qN"cmpgt_addadd_imm",o7 w52
#define SI wH wX1,q2 wX1,q2 wX1 qN"cmpgt_minma"oZ2" > "hF3
#define TI wH hD1,q2 hD1,q2 hD1 qN"cmpgt_minmax"d83"> "h93
#define UI wG gO1,q2 gO1,q2 gO1 qN"cmpgt_mul_imm_neg",dT1 hF2
#define WI wG gP1,q2 gP1,q2 gP1 qN"cmpgt_mul_imm_pos",wV1 hF2
#define YI wG mT,q2 mT,q2 mT qN"cmpgt_mulmul_imm_neg",mM2 w52
#define SJ wG mU,q2 mU,q2 mU qN"cmpgt_mulmul_imm_pos",gP3 w52
#define TJ wG w31,q2 w31,q2 w31 qN"cmple_add_imm",h61 qL2
#define UJ {1,qJ gQ1 q2 gQ1 q2 gQ1 oK1"cmple_add_reduce",d73"<="dQ3
#define WJ wG hE1,q2 hE1,q2 hE1 qN"cmple_addadd_imm",o7 w62
#define YJ wH wY1,q2 wY1,q2 wY1 qN"cmple_minma"oZ2 dN3 hF3
#define SK wH hF1,q2 hF1,q2 hF1 qN"cmple_minmax"d83"<= "h93
#define TK wG gR1,q2 gR1,q2 gR1 qN"cmple_mul_imm_neg",dT1 qL2
#define UK wG gS1,q2 gS1,q2 gS1 qN"cmple_mul_imm_pos",wV1 qL2
#define WK wG mV,q2 mV,q2 mV qN"cmple_mulmul_imm_neg",mM2 w62
#define YK wG mW,q2 mW,q2 mW qN"cmple_mulmul_imm_pos",gP3 w62
#define SL wG w41,q2 w41,q2 w41 qN"cmplt_add_imm",h61 qM2},
#define TL {1,qJ gT1 q2 gT1 q2 gT1 oK1"cmplt_add_reduce",d73"<"dQ3
#define UL wG hG1,q2 hG1,q2 hG1 qN"cmplt_addadd_imm",o7")"dH3 hY
#define WL wH wZ1,q2 wZ1,q2 wZ1 qN"cmplt_minma"oZ2 dH3 hF3
#define YL wH hH1,q2 hH1,q2 hH1 qN"cmplt_minmax"d83"< "h93
#define SM wG gU1,q2 gU1,q2 gU1 qN"cmplt_mul_imm_neg",dT1 qM2},
#define TM wG gV1,q2 gV1,q2 gV1 qN"cmplt_mul_imm_pos",wV1 qM2},
#define UM wG mX,q2 mX,q2 mX qN"cmplt_mulmul_imm_neg",mM2")"dH3 hY
#define WM wG mY,q2 mY,q2 mY qN"cmplt_mulmul_imm_pos",wJ"4)"dH3 hY
#define YM wG w51,q2 w51,q2 w51 qN"cmpne_add_imm",h61 a01},
#define SN {1,qJ gW1 q2 gW1 q2 gW1 oK1"cmpne_add_reduce",d73"!="dQ3
#define TN wG hI1,q2 hI1,q2 hI1 qN"cmpne_addadd_imm",o7 o82
#define UN wH a11,q2 a11,q2 a11 qN"cmpne_minma"oZ2 dI3 hF3
#define WN wH hJ1,q2 hJ1,q2 hJ1 qN"cmpne_minmax"d83"!= "h93
#define YN wG gX1,q2 gX1,q2 gX1 qN"cmpne_mul_imm_neg",dT1 a01},
#define SO wG gY1,q2 gY1,q2 gY1 qN"cmpne_mul_imm_pos",wV1 a01},
#define TO wG mZ,q2 mZ,q2 mZ qN"cmpne_mulmul_imm_neg",mM2 o82
#define UO wG q01,q2 q01,q2 q01 qN"cmpne_mulmul_imm_pos",gP3 o82
#define WO wG w61,q2 w61,q2 w61 qN"cmpzz_add_imm"dC" "h61 qM2 aC" "h61 qN2" "h61 hG2" "h61 qO2 h61 a01 dD h61 hE2
#define YO {1,qJ gZ1 q2 gZ1 q2 gZ1 oK1"cmpzz_add_reduce"dC" "d73"< "h1 aC" "d73"<= "h1 aE" "d73"> "h1 oV" "d73">= "h1 aD d73"!= "h1 dD d73"="dQ3
#define SP wG hK1,q2 hK1,q2 hK1 qN"cmpzz_addadd_imm"dC" "o7 hH2 aC" "o7 hI2" "o7 hJ2" "o7 wB1 o7 wC1 o7 w72
#define TP wH a21,q2 a21,q2 a21 qN"cmpzz_minmax"dC hD3"< "hH3 aC hD3"<= "hH3 aE hD3"> "hH3 oV hD3">= "hH3 g1"0010 *"hD3"!= "hH3" +  0x0020 *"hD3"= "hF3
#define UP wH hM1,q2 hM1,q2 hM1 qN"cmpzz_minmax_rev"dC hD3"< "hI3 aC hD3"<= "hI3 aE hD3"> "hI3 oV hD3">= "hI3 g1"0010 *"hD3"!= "hI3" +  0x0020 *"hD3"= "h93
#define WP wG h01,q2 h01,q2 h01 qN"cmpzz_mul_imm_neg"dC gP2 qM2 aC gP2 qN2 gP2 hG2 gP2 qO2 dT1 a01 dD dT1 hE2
#define YP wG h11,q2 h11,q2 h11 qN"cmpzz_mul_imm_pos"dC oN1 qM2 aC oN1 qN2 oN1 hG2 oN1 qO2 wV1 a01 dD wV1 hE2
#define SQ wG q11,q2 q11,q2 q11 qN"cmpzz_mulmul_imm_neg"dC h71 hH2 aC h71 hI2 h71 hJ2 h71 wB1 mM2 wC1 mM2 w72
#define TQ wG q21,q2 q21,q2 q21 qN"cmpzz_mulmul_imm_pos"dC" "gP3 hH2 aC" "gP3 hI2" "gP3 hJ2" "gP3 wB1 gP3 wC1 gP3 w72
#define UQ wH hK2,q2 hK2,q2 hK2 qN"ge_and_eq",mW2 oS1
#define WQ wH hL2,q2 hL2,q2 hL2 qN"ge_and_le",mW2 hN1},
#define YQ wH hM2,q2 hM2,q2 hM2 qN"ge_and_ne",mW2 dJ1
#define SR wH w82,q2 w82,q2 w82 qN"ge_or_eq",mX2 oS1
#define TR wH w92,q2 w92,q2 w92 qN"ge_or_le",mX2 hN1},
#define UR wH wA2,q2 wA2,q2 wA2 qN"ge_or_ne",mX2 dJ1
#define WR wH hN2,q2 hN2,q2 hN2 qN"gt_and_eq"gQ2 oS1
#define YR wH hO2,q2 hO2,q2 hO2 qN"gt_and_ge"gQ2 m7},
#define SS wH hP2,q2 hP2,q2 hP2 qN"gt_and_le"gQ2 hN1},
#define TS wH hQ2,q2 hQ2,q2 hQ2 qN"gt_and_ne"gQ2 dJ1
#define US wH wB2,q2 wB2,q2 wB2 qN"gt_or_eq"gA3 oS1
#define WS wH wC2,q2 wC2,q2 wC2 qN"gt_or_ge"gA3 m7},
#define YS wH wD2,q2 wD2,q2 wD2 qN"gt_or_le"gA3 hN1},
#define ST wH wE2,q2 wE2,q2 wE2 qN"gt_or_ne"gA3 dJ1
#define TT gL3 If10,q2 If10,q2 If10,oK1"if10",o6",1,0) + 10*"o6",0,1)    + 100*"o6">0,1,0) + 1000*"o6">0,0,1"o02
#define UT {mF dV1,q2 dV1,q2 dV1 qN1"tract_abs",o6", abs(x+2), abs(y+5))"},
#define WT {mF dW1,q2 dW1,q2 dW1 qN1"tract_add"hB2"+2, y+"gX2
#define YT {mF d71,q2 d71,q2 d71 qN1"tract_add1"hB2"+2, y"o02
#define SU {mF d81,q2 d81,q2 d81 qN1"tract_add2",o6", y, y+2"o02
#define TU {a31 qJ1 q2 qJ1 q2 qJ1"x"dU"tract_and1_l"hB2"&z, y<1"o02
#define UU {a31 q71 q2 q71 q2 q71"x"dU"tract_and1_nl"hB2"&z, z"o02
#define WU {a31 qK1 q2 qK1 q2 qK1"x"dU"tract_and2_l",o6", y<1, y&z"o02
#define YU {a31 q81 q2 q81 q2 q81"x"dU"tract_and2_nl",o6", z, y&z"o02
#define SV {mF If_extract_div,0,q2 If_extract_div qN1"tract_div"hB2"/x, y/2"o02
#define TV {mF dX1,q2 dX1,q2 dX1 qN1"tract_min",o6", min(y,2), min(y,5))"},
#define UV {mF dY1,q2 dY1,q2 dY1 qN1"tract_mul"hB2"*2, y*"gX2
#define WV {mF d91,q2 d91,q2 d91 qN1"tract_mul1"hB2"*2, y"o02
#define YV {mF dA1,q2 dA1,q2 dA1 qN1"tract_mul2",o6", y, y*2"o02
#define SW {a31 h21 q2 h21 q2 h21"x"dU"tract_or1_l",o6", y|z, y<1"o02
#define TW {a31 qL1 q2 qL1 q2 qL1"x"dU"tract_or1_nl",o6", y|z, z"o02
#define UW {a31 h31 q2 h31 q2 h31"x"dU"tract_or2_l",o6", y<1, y|z"o02
#define WW {a31 qO1 q2 qO1 q2 qO1"x"dU"tract_or2_nl",o6", z, y|z"o02
#define YW {1,3,5,gQ w71 q2 w71 q2 w71 oK1"if_join_add2","x + 10 +"hL1"<4, 3,4"o02
#define SX {1,3,5,gQ w81 q2 w81 q2 w81 oK1"if_join_mul2","x * 10 *"hL1"<4, 3,4"o02
#define TX dP3 Ifabs,q2 Ifabs,q2 Ifabs,oK1"ifabs","1"dD1"< 0,-x,"h53"   10"dD1"<=0,-x,"h53"  100"dD1"> 0,-x,"h53" 1000"dD1">=0,-x,"h53"10000"dD1"< 0,x"dE3"     100000"dD1"<=0,x"dE3"    1000000"dD1"> 0,x"dE3"10000000"dD1">=0,x,-"mR2
#define UX {4 d6 gQ wF2 q2 wF2 q2 wF2"b,d,"w12"ifmerge"dJ2"y,x,b"mZ2"y,x,d)) +  if(b,if(d,y,x),if(d,b,"mR2
#define WX {4 d6 gQ hR2 q2 hR2 q2 hR2"a,b,"w12"ifmerge2"dJ2"y,a,b"mZ2"b,a,b))"},
#define YX {4 d6 gQ qP2 q2 qP2 q2 qP2"a,b,"w12"ifmerge2b"dJ2"y,a,b"mZ2"b,b,a))"},
#define SY wH Ifnop,q2 Ifnop,q2 Ifnop qN"ifnop",o6",y,y"o02
#define TY {mX1 L_abs,q2 L_abs,q2 L_abs qN"l_abs","(x+2) & "d63 mQ1
#define UY {mX1 wG2,q2 wG2,q2 wG2 qN"l_mulabs","(x*abs(y))"mQ1
#define WY {mX1 wH2,q2 wH2,q2 wH2 qN"l_mulneg","(x*y*-5)"mQ1
#define YY {mX1 wI2,q2 wI2,q2 wI2 qN"l_notnot","(x+2) & !!x"mQ1
#define SZ wH hS2,q2 hS2,q2 hS2 qN"le_and_eq",hN1" & "oS1
#define TZ wH hT2,q2 hT2,q2 hT2 qN"le_and_ne",hN1" & "dJ1
#define UZ wH wJ2,q2 wJ2,q2 wJ2 qN"le_or_eq",hN1" | "oS1
#define WZ wH wK2,q2 wK2,q2 wK2 qN"le_or_ne",hN1" | "dJ1
#define YZ wH hU2,q2 hU2,q2 hU2 qN"lt_and_eq"hV2 oS1
#define Sa wH hW2,q2 hW2,q2 hW2 qN"lt_and_ge"hV2 m7},
#define Ta wH hX2,q2 hX2,q2 hX2 qN"lt_and_gt"hV2"(x > y"o02
#define Ua wH hY2,q2 hY2,q2 hY2 qN"lt_and_le"hV2 hN1},
#define Wa wH hZ2,q2 hZ2,q2 hZ2 qN"lt_and_ne"hV2 dJ1
#define Ya wH wL2,q2 wL2,q2 wL2 qN"lt_or_eq"gK3 oS1
#define Sb wH wM2,q2 wM2,q2 wM2 qN"lt_or_ge"gK3 m7},
#define Tb wH wN2,q2 wN2,q2 wN2 qN"lt_or_gt"mD" | (x > y"o02
#define Ub wH wO2,q2 wO2,q2 wO2 qN"lt_or_le"gK3 hN1},
#define Wb wH wP2,q2 wP2,q2 wP2 qN"lt_or_ne"gK3 dJ1
#define Yb {a31 a41 q2 a41 q2 a41 mG"mergemulabs","abs(x)*abs(y)*z"},
#define Sc {3,0,4,gQ Mixedminmax,oT1 oT1 mG"mixedminmax","max(z,min(x,max(max(z,y),x)))"h03"10*min(z,max(x,min(y,x)))"h03"100*min(max(x,y),min(y,z)) +  1000*max(min(x,y),max(y,z))"},
#define Tc wH Nand2,q2 Nand2,q2 Nand2 qN"nand2",hU3},
#define Uc w22 qQ2 q2 qQ2 q2 qQ2 mG"nand2plus",hU3" | z"},
#define Wc w22 Nand3,q2 Nand3,q2 Nand3,mG"nand3",hU3" | !z"},
#define Yc wH Nor2,q2 Nor2,q2 Nor2 qN"nor2",hV3},
#define Sd w22 d02 q2 d02 q2 d02 mG"nor2plus",hV3" & z"},
#define Td w22 Nor3,q2 Nor3,q2 Nor3,mG"nor3",hV3" & !z"},
#define Ud wH Not_eq,q2 Not_eq,q2 Not_eq qN"not_eq",o6" = "h23
#define Wd wH Not_ge,q2 Not_ge,q2 Not_ge qN"not_ge",o6 dO3 h23
#define Yd wH Not_gt,q2 Not_gt,q2 Not_gt qN"not_gt",o6" > "h23
#define Se wH Not_le,q2 Not_le,q2 Not_le qN"not_le",o6 dN3 h23
#define Te wH Not_lt,q2 Not_lt,q2 Not_lt qN"not_lt",o6 dH3 h23
#define Ue wH Not_ne,q2 Not_ne,q2 Not_ne qN"not_ne",o6 dI3 h23
#define We {mF Notnot,q2 Notnot,q2 Notnot qN"notnot","!!x + if(y, 1,0"o02
#define Ye oE2 gQ mV2 gJ2 gJ2,"x"q6"/xaddnot","!(x+if(1,4,4))"},
#define Sf oE2 gQ mH1 q2 mH1 q2 mH1"x"q6"/xaddnotnot","!!(x+if(1,4,4))"},
#define Tf {1,-w91 t1,g3 t1,g3 t1,m42"1","x+max(0, min(-2,0))"},
#define Uf {1,-w91 t2,g3 t2,g3 t2,m42"2","min(x,min(1,"mR2
#define Wf {1,-mI1 t3,g3 t3,g3 t3,m42"3","sub(  (!x & !!x) ,  (!x | !!x)  "o02
#define Yf {2,-mI1 t4,g3 t4,g3 t4,"x,y",oF"4","sub(!(x-y), !!(x-y))"},
#define Sg oE2 gR3 t6,g3 t6,g3 t6,m42"6","sub(!(x+4), !!(x+3))"},
#define Tg {1,-w91 t36,g3 t36,g3 t36,m42"36","-if(x<0, x, -x) + -if(x<5, 2, 3"o02
#define Ug {2,-mI1 t60,g3 t60,g3 t60,"x,y",oF"60","sqr(x) | sub(x,y) | value()"},
#define Wg {2,-20,20,dB1 t16,qZ t16,qZ t16,oF2"16",o6"<0, if(y<0, x+y, x-y), if(y>0, x*y, x+2*y))"},
#define Yg {2,-20,20,dB1 t17,qZ t17,qZ t17,oF2"17","sqr(x)+sub(x,y)+psqr(y)+psub(y+1,x-2)-1"},
#define Sh {2,-100,100,dB1 t19,qZ t19,qZ t19,oF2"19","(x<y)+10"oH2"<=y)+100"oH2">y)+1000"oH2">=y)+10000"oH2"=y)+100000"oH2"!=y)+  (x&y)*2+(x|y)*20+(!x)*200+(!!x)*2000+4*!((x<y)&(x<3))+40*!!(!(x>y)|(x>3))"},
#define Th {2,-100,100,dB1 t20,qZ t20,qZ t20,oF2"20","(!(x"dI3"y) & !x) + !(!(!(!y)))"},
#define Uh {1,oG2 t21,qZ t21,qZ t21,"x"dY"21","sqr(x)+value()-pvalue ( "o02
#define Wh {1,g83 dB1 t24,qZ t24,qZ t24,"x"dY"24","(min(x, min(1,"mG1" min(x, 1))/2 + min(x, 1)*3 + max(0, min(-2,0))"},
#define Yh {2,-5,5,dB1 t29,qZ t29,qZ t29,oF2"29","x-y*1"},
#define Si {4,-5,5,dB1 t34,qZ t34,qZ t34,"t,う,お,早"dY"34","お+早*う-t"},
#define Ti {3,oG2 t35,qZ t35,qZ t35,"A_very_long_variable_name_1,A_very_long_variable_name_2,Yet_a_third_very_long_variable_name"dY"35","A_very_long_variable_name_1-A_very_long_variable_name_2+  Yet_a_third_very_long_variable_name*A_very_long_variable_name_1"},
#define Ui {2,oG2 t50,qZ t50,qZ t50,oF2"50","(x<y | y<x)"d93"2"oH2"<y & y<x)"d93"4"oH2 q03" y<=x)"d93"8"oH2"<y & "dG3"   16"oH2"<y | "dG3"   32"oH2 q03" x>=y)"d93"64"oH2"<=y | x>=y)"d93"128"oH2"!=y & x=y)"d93"256"oH2"!=y & "dG3"512"oH2 q03" x=y"o02
#define Wi {2,-11,11,dB1 t58,qZ t58,qZ t58,oF2"58","(-x"dH3"3)"oM2"-1 > 5)"oM2"-3"dH3"10)"oM2"-3"dH3"y*7) +  (x*4"dH3"y*7)"oM2"6"dH3"y*-3"qI3"-x"dH3"11"qI3"5"dH3"-y"o02
#define Yi {3,-8,7,dB1 I1,0,qZ I1,w32"i1","1+2+3-4*5*6/3+10/2-9%2 + (x+y - 11*x + z/10 + x/(z+31))"},
#define Sj {3,-7,7,dB1 I2,0,qZ I2,w32"i2","if(abs(x*y)"dH3"20 | x+y > 30 & z > 5, min(x,2*y), max(y,z*2))"},
#define Tj {3,1,7,dB1 I3,0,qZ I3,w32"i3","(x+y) + 2"oH2"-z) + 3*(x*y) + 4*(y/z) + 5"oH2"%z)"h03"6"oH2"<y) + 7"oH2"<=z) + 8"oH2">2"q13" 9*(y>=3"q13" 10*(x+y!=z) +  11*(100+x) + 12*(101-y) + 13*(102"q13" 14*(103/x)"},
#define Uj {2,dM1 Add_d,qG Add_d a61"add_d","x+y"},
#define Wj {3,dM1 Addsub_d,qG Addsub_d wQ2 g0"addsub_d","x+y+x+x-z+x"},
#define Yj {2,h6 And_d,qG And_d a61"and_d","x&y"},
#define Sk {2,h6 Cmpeq_d,qG Cmpeq_d a61"cmpeq_d","x=y"},
#define Tk {2,h6 Cmpge_d,qG Cmpge_d a61"cmpge_d","x>=y"},
#define Uk {2,h6 Cmpgt_d,qG Cmpgt_d a61"cmpgt_d","x>y"},
#define Wk {2,h6 Cmple_d,qG Cmple_d a61"cmple_d","x<=y"},
#define Yk {2,h6 Cmplt_d,qG Cmplt_d a61"cmplt_d","x<y"},
#define Sl {2,h6 Cmpne_d,qG Cmpne_d a61"cmpne_d","x!=y"},
#define Tl {2,w8 Div_d,qG Div_d a61"div_d","(x-0.25)/y"},
#define Ul {3,w8 Divmul_d,qG Divmul_d wQ2 g0"divmul_d","x*y*x*x/z"oH2"-0.25"o02
#define Wl {1,-7,6,N(0.6)qM,qG Inv_d,qG Inv_d dW g0"inv_d","1/x"},
#define Yl {2,w8 Mul_d,qG Mul_d a61"mul_d","x*y"},
#define Sm {1,dM1 Neg_d,qG Neg_d dW g0"neg_d","-x"},
#define Tm {1,wY,qG Not_d,qG Not_d dW g0"not_d","!x"},
#define Um {1,wY,qG Notnot_d,qG Notnot_d dW g0"notnot_d","!!x"},
#define Wm {2,h6 Or_d,qG Or_d a61"or_d","x|y"},
#define Ym {2,dM1 Sub_d,qG Sub_d a61"sub_d","x-y"},
#define Sn {1,gF3 N(0.5)qM qB Abs_d qB Abs_d gG1"abs_d",d63},
#define Tn {3,wY qB If_d qB If_d wQ2 wS"/if_d",o6",y,z"o02
#define Un {1,-4000,4000,mA Int qB Int gG1"int","int(x)"},
#define Wn m32 Absneverneg q4 Absneverneg wU"absneverneg","abs(acos"g51
#define Yn m32 Absnot2 q4 Absnot2 wU"absnot2","!acos(x)"},
#define So {2 d5 Absnot3 q4 Absnot3 dW gR"absnot3","!(!(x&y))"},
#define To m32 Absnot4 q4 Absnot4 wU"absnot4","!(!acos"g51
#define Uo {1,1,3,N(0.1)qM q4 Acoshcosh q4 Acoshcosh wU"acoshcosh","cosh("q23 g51
#define Wo {1,N(1.7),N(3.7),N(0.28)qM q4 Acoshsinh q4 Acoshsinh wU q23 oA2,oA2"("q23 g51
#define Yo {1,-3,-3,N(0.7)qM q4 Addexp q4 Addexp wU"addexp","exp(x+4"o02
#define Sp {1,-3,-3,N(0.7)qM q4 Addexp2 q4 Addexp2 wU"addexp2","exp2(x+4"o02
#define Tp g9 Asinhcosh q4 Asinhcosh wU"asinhcosh","cosh(a"oA2 g51
#define Up oX Asinhsinh q4 Asinhsinh wU"a"oA2 oA2,oA2"(a"oA2 g51
#define Wp {2 aG N(0.11)qM q4 Atan2tan q4 Atan2tan dW gR"atan2tan","tan("aH2"(x,y))"},
#define Yp {oY Ceilneg q4 Ceilneg wU"ceilneg","ceil"g72
#define Sq {2,aP Deg q4 Deg dW gR"deg","("wR2")*y + x*("wR2 qI3"y*("wR2"))*4"},
#define Tq {1 d6 N(0.5),aW2 Degxmul q4 Degxmul wU"degxmul","acos(x)*2"},
#define Uq {1 aG wB Dupaddmulh q4 Dupaddmulh wU"dupaddmulh","(x+x)*0.5"},
#define Wq {2 aG wB Dupaddmulmul7 q4 Dupaddmulmul7 dW gR"dupaddmulmul7","y*(x+x)*7"},
#define Yq {2 aG wB Dupaddmulmulh q4 Dupaddmulmulh dW gR"dupaddmulmulh","y*(x+x)*0.5"},
#define Sr aD1 Dupxpowmul q4 Dupxpowmul wU"dupxpowmul","x*(x^3"o02
#define Tr oP1 Exp2div q4 Exp2div dW gR"exp2div","x/exp2(y"o02
#define Ur oX Exp2log2 q4 Exp2log2 wU"exp2log2","log2(exp2"g51
#define Wr oP1 Expdiv q4 Expdiv dW gR"expdiv","x/"m62"y"o02
#define Yr oX Explog q4 Explog wU"explog","log("qJ3
#define Ss oX Explog2 q4 Explog2 wU"explog2","log2("qJ3
#define Ts oX Explog10 q4 Explog10 wU"explog10","log10("qJ3
#define Us {oY Floorneg q4 Floorneg wU"floorneg","floor"g72
#define Ws {1,N(-1.5),N(1.5),hA2 q4 Int q4 Int wU"int","x+"qR2 qR2"sub(int(1.1), int(1.6"a71"1.5"a71"-1.1"a71"-1.6"a71"-1.5))"},
#define Ys {oY Intceil q4 Intceil wU"intceil","ceil"mY1
#define St {oY Intfloor q4 Intfloor wU"intfloor","floor"mY1
#define Tt {oY Intint q4 Intint wU"intint","int"mY1
#define Ut {oY Inttrunc q4 Inttrunc wU"inttrunc","trunc"mY1
#define Wt oP1 Invdiv q4 Invdiv dW gR"invdiv","y/(1/x)"},
#define Yt {1 aG 2 qM q4 Invinv q4 Invinv wU"invinv","1/(1/x)"},
#define Su {oY Negceil q4 Negceil wU"negceil","-ceil(x)"},
#define Tu {oY Negfloor q4 Negfloor wU"negfloor","-floor(x)"},
#define Uu oP1 Powdiv q4 Powdiv a51,"10optimizer_bytecode/powdiv","x/pow(x"mF1
#define Wu {1,qC1 Powhalf q4 Powhalf,dZ1"half",d12",0.5"o02
#define Yu oP1 Powinv q4 Powinv a51,"10optimizer_bytecode/powinv","1/pow(x"mF1
#define Sv {1,qC1 Powminushalf q4 Powminushalf,dZ1"minushalf",d12",-0.5"o02
#define Tv {1,1,5,wB Powminusone q4 Powminusone,dZ1"minusone",d12",-1.0"o02
#define Uv {1,qC1 Powminusthird q4 Powminusthird,dZ1"minusthird",d12",(-1.0/3.0))"},
#define Wv {1,qC1 Powthird q4 Powthird,dZ1"third",d12","dB2"/3.0))"},
#define Yv {2,aP Rad q4 Rad dW gR"rad","("gR2")*y + x*("gR2") + (x*("gR2"))*4"},
#define Sw {1,-2,2,N(0.8)qM q4 Radxmul q4 Radxmul wU"radxmul","cos"wJ gR2")*4"o02
#define Tw {1,aP Sqrlog q4 Sqrlog wU"sqrlog","log"d22
#define Uw {1,aP Sqrlog2 q4 Sqrlog2 wU"sqrlog2","log2"d22
#define Ww {1,aP Sqrlog10 q4 Sqrlog10 wU"sqrlog10","log10"d22
#define Yw {1,-2,2,N(0.8),aW2 Xmulrad q4 Xmulrad,0,q7"/xmulrad","cos"a92
#define Sx aE1 Xxfdup q4 Xxfdup,0,q7"/xxfdup","sub(sin(x),sin(x))"},
#define Tx dP3 Abscos,q2 Abscos,gD"abscos","cos(sqrt("a81"))) + sqrt("a81"))"},
#define Ux dP3 Abscosh,q2 Abscosh,gD"abscosh","cosh(sqrt("a81"))) + sqrt("a81"))"},
#define Wx {1 d6 N(0.1)qM,q2 Acoscos,q2 Acoscos,gD"acoscos","cos(acos"g51
#define Yx {1,N(1.7),N(3.7),N(0.28)qM,q2 Acoshsinh,q2 Acoshsinh,gD q23 oA2,oA2"(if(1,acosh(x),0))"},
#define Sy {2,wT2 1,hA2,q2 Addlog,q2 Addlog,0 qN"addlog","log(x)+log(y"o02
#define Ty hQ3 Addsin2cos2,q2 Addsin2cos2,gD"addsin2cos2",q42"^2 + cos(x)^2"},
#define Uy {1,N(-0.7),N(0.7),N(0.28)qM,q2 Asinhcosh,q2 Asinhcosh,gD"asinhcosh","cosh(if(1,a"oA2"(x),0))"},
#define Wy {1 d6 N(0.1)qM,q2 Asinsin,q2 Asinsin,gD"asinsin","sin(asin(x))"},
#define Yy hQ Cmpeq_pow_imm_negneg,q2 Cmpeq_pow_imm_negneg,gD a91 hS" = "gZ3
#define Sz hQ Cmpeq_pow_imm_negpos,q2 Cmpeq_pow_imm_negpos,gD a91 hT" = "h13
#define Tz {1,qJ Cmpeq_pow_imm_posneg,q2 Cmpeq_pow_imm_posneg,gD a91 d0" = "d53
#define Uz {1,qJ Cmpeq_pow_imm_pospos,q2 Cmpeq_pow_imm_pospos,gD a91 d3" = "hG3
#define Wz {1,qJ Cmpeq_pow_imm_pospos_base,q2 Cmpeq_pow_imm_pospos_base,gD a91 h33"= "wK
#define Yz wG Cmpeq_powpow_imm_base,q2 Cmpeq_powpow_imm_base,0 qN a91 hC" = "a3
#define S_ hQ Cmpge_pow_imm_negneg,q2 Cmpge_pow_imm_negneg,o71 hS dO3 gZ3
#define T_ hQ Cmpge_pow_imm_negpos,q2 Cmpge_pow_imm_negpos,o71 hT dO3 h13
#define U_ {1,qJ Cmpge_pow_imm_posneg,q2 Cmpge_pow_imm_posneg,o71 d0 dO3 d53
#define W_ {1,qJ Cmpge_pow_imm_pospos,q2 Cmpge_pow_imm_pospos,o71 d3 dO3 hG3
#define Y_ {1,qJ Cmpge_pow_imm_pospos_base,q2 Cmpge_pow_imm_pospos_base,o71 h33">= "wK
#define S01 wG Cmpge_powpow_imm_base,q2 Cmpge_powpow_imm_base,0 qN"cmpge_"hC dO3 a3
#define T01 hQ Cmpgt_pow_imm_negneg,q2 Cmpgt_pow_imm_negneg,o81 hS" > "gZ3
#define U01 hQ Cmpgt_pow_imm_negpos,q2 Cmpgt_pow_imm_negpos,o81 hT" > "h13
#define W01 {1,qJ Cmpgt_pow_imm_posneg,q2 Cmpgt_pow_imm_posneg,o81 d0" > "d53
#define Y01 {1,qJ Cmpgt_pow_imm_pospos,q2 Cmpgt_pow_imm_pospos,o81 d3" > "hG3
#define S11 {1,qJ Cmpgt_pow_imm_pospos_base,q2 Cmpgt_pow_imm_pospos_base,o81 h33"> "wK
#define T11 wG Cmpgt_powpow_imm_base,q2 Cmpgt_powpow_imm_base,0 qN"cmpgt_"hC" > "a3
#define U11 hQ Cmple_pow_imm_negneg,q2 Cmple_pow_imm_negneg,m52 hS dN3 gZ3
#define W11 hQ Cmple_pow_imm_negpos,q2 Cmple_pow_imm_negpos,m52 hT dN3 h13
#define Y11 {1,qJ Cmple_pow_imm_posneg,q2 Cmple_pow_imm_posneg,m52 d0 dN3 d53
#define S21 {1,qJ Cmple_pow_imm_pospos,q2 Cmple_pow_imm_pospos,m52 d3 dN3 hG3
#define T21 {1,qJ Cmple_pow_imm_pospos_base,q2 Cmple_pow_imm_pospos_base,m52 h33"<= "wK
#define U21 wG Cmple_powpow_imm_base,q2 Cmple_powpow_imm_base,0 qN aA1 hC dN3 a3
#define W21 hQ Cmplt_pow_imm_negneg,q2 Cmplt_pow_imm_negneg,o91 hS dH3 gZ3
#define Y21 hQ Cmplt_pow_imm_negpos,q2 Cmplt_pow_imm_negpos,o91 hT dH3 h13
#define S31 {1,qJ Cmplt_pow_imm_posneg,q2 Cmplt_pow_imm_posneg,o91 d0 dH3 d53
#define T31 {1,qJ Cmplt_pow_imm_pospos,q2 Cmplt_pow_imm_pospos,o91 d3 dH3 hG3
#define U31 {1,qJ Cmplt_pow_imm_pospos_base,q2 Cmplt_pow_imm_pospos_base,o91 h33"< "wK
#define W31 wG Cmplt_powpow_imm_base,q2 Cmplt_powpow_imm_base,0 qN"cmplt_"hC dH3 a3
#define Y31 hQ Cmpne_pow_imm_negneg,q2 Cmpne_pow_imm_negneg,oA1 hS dI3 gZ3
#define S41 hQ Cmpne_pow_imm_negpos,q2 Cmpne_pow_imm_negpos,oA1 hT dI3 h13
#define T41 {1,qJ Cmpne_pow_imm_posneg,q2 Cmpne_pow_imm_posneg,oA1 d0 dI3 d53
#define U41 {1,qJ Cmpne_pow_imm_pospos,q2 Cmpne_pow_imm_pospos,oA1 d3 dI3 hG3
#define W41 {1,qJ Cmpne_pow_imm_pospos_base,q2 Cmpne_pow_imm_pospos_base,oA1 h33"!= "wK
#define Y41 wG Cmpne_powpow_imm_base,q2 Cmpne_powpow_imm_base,0 qN"cmpne_"hC dI3 a3
#define S51 hQ Cmpzz_pow_imm_negneg,q2 Cmpzz_pow_imm_negneg,hO1"_imm_negneg"dC oU1 dH3 h43 aC oU1 dN3 h43 aE oU1" > "h43 oV oU1 dO3 h43 aD gO",-3)"dI3 h43 dD gO",-3) = "gZ3
#define T51 hQ Cmpzz_pow_imm_negpos,q2 Cmpzz_pow_imm_negpos,hO1"_imm_negpos"dC oV1 dH3 hC3 aC oV1 dN3 hC3 aE oV1" > "hC3 oV oV1 dO3 hC3 aD gO",-2)"dI3 hC3 dD gO",-2) = "h13
#define U51 {1,qJ Cmpzz_pow_imm_posneg,q2 Cmpzz_pow_imm_posneg,hO1"_imm_posneg"dC dA3"< "hW3 aC dA3"<= "hW3 aE dA3"> "hW3 oV dA3">= "hW3 aD gO",3)"dI3 hW3 dD gO",3) = "d53
#define W51 {1,qJ Cmpzz_pow_imm_pospos,q2 Cmpzz_pow_imm_pospos,hO1"_imm_pospos"dC q02 dH3"25)"aC q02" <= 25)"aE q02" > 25)"oV q02" >= 25)"aD gO",2)"dI3"25)"dD gO",2) = "hG3
#define Y51 {1,qJ Cmpzz_pow_imm_pospos_base,q2 Cmpzz_pow_imm_pospos_base,hO1"_imm_pospos_base"dC" "h63"<"dR3 aC" "h63"<="dR3 aE" "h63">"dR3 oV" "h63">="dR3 aD h63"!="dR3 dD h63"= "wK
#define S61 wG Cmpzz_powpow_imm_base,q2 Cmpzz_powpow_imm_base,0 qN"cmpzz_powpow_imm_base"dC" "qQ1 dH3 g71 aC" "qQ1 dN3 g71 aE" "qQ1" > "g71 oV" "qQ1 dO3 g71 aD qQ1 dI3 g71 dD qQ1" = "a3
#define T61 {2,q33 Expexp_a,q2 Expexp_a,0 qN q43"p_a","exp(x*2 + y*3"o02
#define U61 {3,q33 Expexp_b,q2 Expexp_b mC q43"p_b",aR" * exp(y+z"o02
#define W61 {3,q33 Expexp_c,q2 Expexp_c mC q43"p_c","exp(x + y*z"o02
#define Y61 {gX3 hF If_extract_sin,q2 If_extract_sin,0 qN1"tract_sin",o6", sin(y), "hA3
#define S71 o12 If_join_add,q2 If_join_add,0 qN"if_join_add"o92"+"aB1
#define T71 o12 If_join_and,q2 If_join_and,0 qN"if_join_and"o92"&"aB1
#define U71 o12 If_join_max,q2 If_join_max,0 qN"if_join_max","max("o6 dA","hX3")))"},
#define W71 o12 If_join_min,q2 If_join_min,0 qN"if_join_min","min("o6 dA","hX3")))"},
#define Y71 o12 If_join_mul,q2 If_join_mul,0 qN"if_join_mul"o92"*"aB1
#define S81 o12 If_join_or,q2 If_join_or,0 qN"if_join_or",o6 dA" |"hX3"))"},
#define T81 dS2 Ifabsnot,q2 Ifabsnot mC"ifabsnot","if(!(sin(x)+1.2), y,z"o02
#define U81 dS2 Ifconst,q2 Ifconst mC"ifconst","if(1, x,y) + if(0,z,y"o02
#define W81 {4 w42 Ififconst,q2 Ififconst,0,"w,"mG"ififconst","if("o6",1,y),z,w) + if(if(w,z,0),"w02
#define Y81 w22 Ifnot,q2 Ifnot mC"ifnot","if(!x, y,z"o02
#define S91 dS3 Muland2,q2 Muland2,0 qN"muland2",hY3},
#define T91 dS2 Muland2plus,q2 Muland2plus mC"muland2plus",hY3" * z"},
#define U91 dS2 Muland3,q2 Muland3 mC"muland3",hY3" * !!z"},
#define W91 dS3 Mulandlt,q2 Mulandlt,0 qN"mulandlt",wS2" (y<0"o02
#define Y91 {2,wT2 1,hA2,q2 Mulimmlog,q2 Mulimmlog,0 qN"mulimmlog","log(if(1,5,0)*x*y"o02
#define SA1 dS3 Mulnor2,q2 Mulnor2,0 qN"mulnor2",hZ3},
#define TA1 dS2 Mulnor2plus,q2 Mulnor2plus mC"mulnor2plus",hZ3" * z"},
#define UA1 dS2 Mulnor3,q2 Mulnor3 mC"mulnor3",hZ3" * !z"},
#define WA1 dP3 Negceil,q2 Negceil,gD"negceil","ceil(x*(abs(x)-abs(x)-1))"},
#define YA1 dP3 Negcos,q2 Negcos,gD"negcos","cos"wU2
#define SB1 dP3 Negcosh,q2 Negcosh,gD"negcosh","cosh"wU2
#define TB1 dP3 Negfloor,q2 Negfloor,gD"negfloor","floor(x*(abs(x)-abs(x)-1))"},
#define UB1 dP3 Negsin,q2 Negsin,gD"negsin","sin(x*"qD1
#define WB1 dP3 Negsinh,q2 Negsinh,gD"neg"oA2,oA2 wU2
#define YB1 hQ3 Posnot,q2 Posnot,gD"posnot","!(sin(x) + 1.2"o02
#define SC1 hQ3 Posnotnot,q2 Posnotnot,gD"posnotnot","!!(sin(x) + 1.2"o02
#define TC1 {1,wT2 1,hA2,q2 Powimmaddimmlog,q2 Powimmaddimmlog mJ1"immaddimmlog","pow(5, log(x)+1"o02
#define UC1 {1,wT2 2,hA2,q2 Powimmlog,q2 Powimmlog mJ1"immlog","pow(3, log(x)) + pow(5, log(x)*sin(x))"},
#define WC1 {2 wR1 Powmulimm_fnen,q2 Powmulimm_fnen dW dE1"mulimm_fnen",o01"^(-8"o02
#define YC1 {q53 Powmulimm_fnep,q2 Powmulimm_fnep dW dE1"mulimm_fnep",o01"^(4"o02
#define SD1 {1,-3,-1,hF Powmulimm_fnfn,q2 Powmulimm_fnfn mJ1"mulimm_fnfn","((-5.1)*x)^(-7.1"o02
#define TD1 {q53 Powmulimm_fnfp,q2 Powmulimm_fnfp dW dE1"mulimm_fnfp",o01"^7.1"},
#define UD1 {q53 Powmulimm_fpfp,q2 Powmulimm_fpfp dW dE1"mulimm_fpfp","(5.1*x*y)^7.1"},
#define WD1 hQ3 Sub1cos2,q2 Sub1cos2,gD"sub1cos2","1-cos(x)^2"},
#define YD1 hQ3 Sub1sin2,q2 Sub1sin2,gD"sub1sin2","1-"q42"^2"},
#define SE1 {1,N(-9.42477796076937971538793014983850865259),N(9.42477796076937971538793014983850865259),N(0.785398163397448309615660845819875721049292349)qM,q2 Trig_modulo,q2 Trig_modulo,gD"trig_modulo","cos(x+pi"qE1"2/3"qE1"5/2"qE1"6/2"qE1 dK3"  "o11")"wI1"2/3)"wI1"5/2)"wI1"6/2)"wI1 dK3"  cos(x-pi) +"dF1"2/3) +"dF1"5/2) +"dF1"6/2) +"dF1 dK3 o21")"q63"2/3)"q63"5/2)"q63"6/2)"q63"7/2"o02
#define TE1 {1 aG hA2,q2 Trunc_from_if,q2 Trunc_from_if,gD"trunc_from_if",o6">0,  "hL3 d32">=0, "hL3 d32"<0,  "hJ3 d32"<=0, "hJ3 qS2">0,  "hJ3 qS2">=0, "hJ3 qS2"<0,  "hL3" 10*"o6"<=0, floor(x),ceil"g51
#define UE1 {1,N(-0.7),N(0.7),N(0.28)qM,g3 t5,g3 t5 dW,oF"5","sub(sin(x)+csc(x),cos"g51
#define WE1 {2 aG N(.25)qM,g3 t42,g3 t42 a51,oF"42","sqrt(x*x) + 1.5*((y*y)^.25) + hypot(x"mF1
#define YE1 {1,-100,-1,N(.5)qM,g3 t51,g3 t51 dW,oF"51","log"g72
#define SF1 {1,N(.05),1,N(.01)qM,g3 t57,g3 t57 dW,oF"57","cosh(a"oA2 g51
#define TF1 {2,-2,2,N(1.2)qM,g3 t59,g3 t59 a51,oF"59","cosh(x^2) + tanh(y^2"o02
#define UF1 {1,g83 N(.25)mK1 t1,qZ t1 dV"1","x*4/2 + (1+(2+3)) + x*x+x+1+2+3*4+5*6*\n7-8*9"},
#define WF1 {1,g83 o52 t2,qZ t2 dV"2","2 * x+ sin ( x ) / .5 + 2-sin(x)*sin(x)"},
#define YF1 {3,-7,7,a02 t3,qZ t3 qT2"3","(x=y & y=x)+  1+2-3.1*4e2/.5 + x*x+y*y+z*z  + (x&x) + (y|y"o02
#define SG1 {2,-10,10,a02 t4,qZ t4 dX"4","( ((( ( x-y) -( ((y) *2) -3)) )* 4))+sin(x)*cos(y)-cos(x)*sin(y"o02
#define TG1 {2,gQ3 8,d42 t5,qZ t5,0,"__A5_x08,o__5_0AB_"dY"5","__A5_x08^o__5_0AB_"},
#define UG1 {gC3 N(.01)mK1 t7,qZ t7 dV"7","cos(x)*sin(1-x)*(1-cos(x/2)*sin(x*5))"},
#define WG1 {2,-8,8,a12 t8,qZ t8 dX"8",aH2"(x,y)+max(x"mF1
#define YG1 {3,1,15,N(.7)mK1 t9,qZ t9 qT2"9","1.5+x*y-2+4/8+z+z+z+z+x/(y*z"o02
#define SH1 {3,1,4,N(.3)mK1 t10,qZ t10 qT2"10","1+sin(cos(max(1+2+3+4+5, x+y+z)))+2"},
#define TH1 {3,1,19,N(.8)mK1 t11,qZ t11 qT2"11","-(-(-(-(-x))-x))+y*1+log(1.1^z"o02
#define UH1 {1,1,2000,a02 t12,qZ t12 dV"12","1/log(10^((3-2)/log(x)))"},
#define WH1 {2,-30,30,a02 t13,qZ t13 dX"13","x^3 * x^4 + y^3 * y^5"},
#define YH1 {1,-50,50,o52 t14,qZ t14 dV"14","x*pi + sin(2*pi) + CONST"},
#define SI1 {2,N(1.1),6,N(.07)mK1 t15,qZ t15 dX"15","x^y/log(y) + log(x)/log(y) + log(x^y"o02
#define TI1 {2,1,17,a12 t18,qZ t18 dX"18","- ( - ( - ( - 5 ) ) ) * -x^ -y^-2"},
#define UI1 {gX3 o52 t22,qZ t22 dX"22","3.5doubled + 10*x tripled - sin(y)doubled"h03"100"oH2" doubled-y tripled)doubled + 5/2doubled + 1.1^x doubled +  1.1doubled^x doubled"},
#define WI1 {1,g83 o52 t23,qZ t23 dV"23","(x/(2*acos(0)))*180"},
#define YI1 {3,1,3,a12 t25,qZ t25,0,"a,b,c"dY"25","a^b^c + a^-2 * (-b^2"qI3"-b^-c"o02
#define SJ1 {1,-100,100,gQ3 true,qZ t26_deg,qZ t26_deg dV"26_deg",qO3" cos(x*1.5) + asin(x/110) + acos(x/120"o02
#define TJ1 {2,gQ3 N(.9),N(.025)mK1 t27,qZ t27 dX"27","abs(x)+acos(x)+asin(x)+atan(x)+"aH2"(x,y)+ceil(x)+cos(x)+cosh(x)+cot(x)+csc"dA2" "d12 mF1
#define UJ1 {2,gQ3 N(.9),N(.025)mK1 t28,qZ t28 dX"28","exp(x)+floor(x)+int(x)+log(x)+log10(x)+max(x,y)+min(x,y)+sec(x)+sin(x)+sinh(x)+sqrt(x)+tan(x)+tanh(x)+ceil(y)+trunc(y"o02
#define WJ1 {2,3,10,dB1 t30,qZ t30 dX"30","x - y*1 + (x%y) + x / (y^1.1) + 2^3 + 5%3 + x^(y^0) + x^0.5"},
#define YJ1 {3,gQ3 4,N(.35)mK1 t31,qZ t31 qT2"31","x - (y*(y*(y*-1))*1) + log(x*exp"dB2")^y) - log(x^y)"h03"exp"dB2")^log(x+6) + 10^("wX2"6"dC2"y+6)*log(z+6"dC2"10)) -    exp"dB2")^("wX2"6)*y) - 5^("wX2"7"dC2"5)) + "qU2"^3 * "qU2"^2 /  "qU2"^4"},
#define SK1 {3,1,2,N(.05)mK1 t32,qZ t32 qT2"32","x"mO"+y/y-min(3,4)-x-max(4,3)+max(3,4)-min(4,3)+0+(z*1)"mO"+(x-2+2)+(x*0.5*2)+y*0     +min(min(min(4.0,x),1.0),min(x,min(min(y,4.0),z)))"mO"+max(max(max(4.0,x),1.0)"mM1"x(max(y,4.0),z)))"mO"+(abs(1)+acos"dB2")+asin(1.0)+atan"dB2")+ceil(1.1)+cos(0.0)      +cosh(0.0)+floor(1.1)+log"dB2")+sin(0.0)+sinh(0.0)+tan"dB2")      +tanh"dB2")+"aH2"(1.0,1.0))"mO"+(x-(y-z))"mO"+(x+y)"oM2"y"qL3"max(x"mM1"x(x,max(x,x))))*-1.0     +(z-z"qL3"1/sin(x/5)"q73"cos(y/5)"q73"tan(z/5"qL3"log10(cot(z/5) + csc(y/5) + sec(x/5))"mO"+log(30+x)*log(40+y"dC2"50+z)"mO"+sin(x/57.295779513082320877"qL3"asin(x/10)*57.295779513082320877     +floor(-x)"q73"ceil(x)"mO"+sqrt(5 * 0.2) +(-"wY2 wY2"x+-"oS2
#define TK1 {2,-2,2,o52 t33,qZ t33 dX"33","sin(sqrt(10-x*x+y*y))+cos(sqrt(15-x*x-y*y))+sin(x*x+y*y"o02
#define UK1 {gC3 o52 t37,qZ t37 dV"37","5 + 7.5*8 / 3 - 2^4*2 + 7%2+4 + x"},
#define WK1 {3,N(-.9),N(.9),o52 t38,qZ t38 qT2"38","a"oA2 dA2" 1.5*"q23"(y+3) + 2.5*atanh(z"o02
#define YK1 {3,N(-1.3),N(1.3),d42 t39,qZ t39 qT2"39","sin(x+cos(y*1.5))-cos(x+sin(y*1.5))+z*z*z*sin(z*z*z-x*x-y*y)-    cos(y*1.5)*sin(x+cos(y*1.5))+x*y*z+x*y*2.5+x*y*z*cos(x)+x*y*cos(x)+x*z*cos(x)+  y*z*2.5+(x*y*z*cos(x)-x*y*z-y*cos(x)-x*z*y+x*y+x*z-cos(x)*x)"},
#define SL1 {3,N(-1.3),N(1.3),N(.075)mK1 t40,qZ t40 qT2"40","(x+x+x+x+x+x+x+x+x+x+x+y"aA")*    (x+x+x+x+x+x+x+x+x+x+x+y"aA")+    2*(x+x+x+x+x+x+x+x+x+x+x+y"aA")-    x*y*(x+x+x+x+x+x+x+x+x+x+x+y"aA")+  x*(x+x+x+x+x+x+x+x+x+x+x+y"aA o02
#define TL1 {3,-2,2,d42 t41,qZ t41 qT2"41","x*3+x*y+x*z+x*sin(y*z) -    "wZ2"4"h03 qG1"))*x"h03 wZ2"y +  "wZ2"z"},
#define UL1 {1,-100,100,N(.03)mK1 t43,qZ t43 dV"43","log(x*x)+abs("m62"abs(x)+1))"},
#define WL1 {1,0,100,N(.125)mK1 t44,qZ t44 dV"44","(x^2"mL1"8)"h03"1.1"oH2"^3"mL1"7)"h03"1.2"oH2"^4"mL1"6)"h03"1.3"oH2"^5"mL1"5)"h03"1.4"oH2"^6"mL1"6)"h03"1.5"oH2"^7"mL1"4)"h03"1.6"oH2"^8"mL1"3)"h03"1.7"oH2"^9"mL1"2) +  1.8*(sqrt(abs(-sqrt(x))^3))"},
#define YL1 {gC3 N(.025)mK1 t45,qZ t45 dV"45","(x^2"mL1"7) + 1.1"oH2"^4"mL1"5) + 1.2"oH2"^6"mL1"3"o02
#define SM1 {2,N(-.9),N(.9),d42 t46,qZ t46 dX"46","abs(floor(acos(x)+4)) + 1.1*abs(floor(acos(y)+1.5)) +  ("g81 dH3"(acos(y)-10)) + 1.2*max(-4, acos(x)) + 1.3*min(9, acos(x)-9"o02
#define TM1 {2 aG o52 t47,qZ t47 dX"47","1.25*(exp(x)+"m62"-"mG1" 1.5*("m62"y)-exp(-y)) +  1.75*(("m62"-x)+exp(x))/2) + 2.0*(("m62"-x)-exp(x))/2) + 2.25*(cosh(y)+sinh(y))"},
#define UM1 {1,2,N(1e9),N(1.2e7)mK1 t48,qZ t48 dV"48",oA2"((log(x)/5+1)*5) + 1.2*cosh((log(x)/log(2)+1)*log"w9" !(x | !(x/4))"},
#define WM1 {1,-100,100,N(.05)mK1 t49,qZ t49 dV"49",aH2"(0, x) + (-4"oH2"-100))^3.3"},
#define YM1 {gC3 a02 t52,qZ t52 dV"52","x + "dB2"+2.0+3.0+4.0-5.0-6.0-7.0-8.0)/3.0"h03"4.0*(1.0+sin(2.0)+cos(4.0*5.0+6.0)/2.0) + cos(0.5)*tan(0.6+0.2) -  1.1/log(2.1)*sqrt(3.3) + 2^3"},
#define SN1 {2,0,10,N(0.5)mK1 t53,qZ t53 dX"53","(x&y) + 4*(int(x/10)|int(y/10)) + 8*((-!-!-x)+(!-!-!y)) + 16*(-------x + !!!!!!!y"o02
#define TN1 {2,-10,100,a02 t54,qZ t54 dX"54","(x<y"m72"<=y"m72">y"m72">=y)+    (x=y"m72"!=y)+(x&y"m72"|y)+    (!x)+(!!x)+    !((x<y)&(x<3))+  !!(!(x>y)|(x>3))"},
#define UN1 {2,1,100,a02 t55,qZ t55 dX"55","(x^1.2"dH3"0"qI3"y^2.5"dH3"0) + 2*(x*x<0) + 3*(y^3<0) + 4"oH2"^4<0"o02
#define WN1 {1,N(.25),100,N(.25)mK1 t56,qZ t56 dV"56","1.75e21%x"},
#define YN1 {1 aG N(0.2)mK1 t59,qZ t59 dV"59","(cos(x)"dH3"sin(x))"h03"(cos(x)-sin(x))"h03"sub(sinh(x)-cosh(x), "oA2"(x)/cosh(x)) +  sqrt(cos(x)^2+sin(x)^2"o02
#define SO1 {1,N(1e-6),4000,mA Log qB Log gG1"log"mP1
#define TO1 g9 Abscos q4 Abscos wU"abscos","cos(abs"g51
#define UO1 g9 Abscosh q4 Abscosh wU"abscosh","cosh(abs"g51
#define WO1 qK3 Abseq0 q4 Abseq0 q4 Abseq0 g5"abseq0"aM1"=0"qI3"0=abs"g51
#define YO1 {1,N(0.001),N(0.9),N(0.01)qM q4 Absevenconstpow q4 Absevenconstpow wU"absevenconstpow",d63" ^ 1506"},
#define SP1 {2,N(0.001),N(0.9),N(0.01)qM q4 Absmulevenconstpow q4 Absmulevenconstpow dW gR"absmulevenconstpow","(abs(x)*y) ^ 1506"},
#define TP1 qK3 q83 q4 q83 q4 q83 g5"absneq0"aM1"=0"qI3"0=abs"g51
#define UP1 qK3 Add q4 Add q4 Add g5"add","5+3+x"},
#define WP1 qK3 Add0 q4 Add0 q4 Add0 g5"add0","x+0+x"},
#define YP1 qK3 And q4 And q4 And g5"and","(5&3"d52"5&0)+(0&5)+(0&0"o02
#define SQ1 m32 Cmp_acos q4 Cmp_acos wU"cmp_acos","1"oL"=acos("wX"    2"oL"<acos("wX"    4"oL"<=acos("wX a22 oL">acos("wX gS2 oL">=acos("wX"  32"oL"!=acos(0.75))"},
#define TQ1 m32 Cmp_acos_outrange q4 Cmp_acos_outrange wU"cmp_acos_outrange","1"oL"=2"o8 g81"<2)"h03"4"oL"<=2) +"a22 oL">2) +"gS2 oL">=2) +  32"oL"!=2"o02
#define UQ1 aD1 q93 q4 q93 q4 q93 g5"cmp_add","1"aQ qW2 aQ qX2 aQ aH1 aQ">4)"wF aQ d41 aQ oW1
#define WQ1 m32 Cmp_asin q4 Cmp_asin wU"cmp_asin","1"oM"=a"dL3"  2"oM"<a"dL3"  4"oM"<=a"q12 a22 oM">a"q12 gS2 oM">=a"dL3"32"oM"!=asin(0.75))"},
#define YQ1 m32 Cmp_asin_outrange q4 Cmp_asin_outrange wU"cmp_asin_outrange","1"oM"=2"o8"a"q42"<2)"h03"4"oM"<=2) +"a22 oM">2) +"gS2 oM">=2) +  32"oM"!=2"o02
#define SR1 aF Cmp_atan q4 Cmp_atan wU"cmp_atan","1"qR1"=atan"o31 qR1"<atan"o41 qR1"<=atan"wM1 qR1">atan"wN1 qR1">=atan"m91 qR1"!=atan"dG1
#define TR1 aF Cmp_exp q4 Cmp_exp wU gT2"p","1"m81"=e"m82" 2"m81"<e"m82" 4"m81"<=e"m82"  8"m81">e"m82" 16"m81">=e"m82" 32"m81"!=exp"dG1
#define UR1 aF Cmp_exp2 q4 Cmp_exp2 wU gT2"p2","1"o9"=exp2"w9" 2"o9"<exp2"w9" 4"o9"<=exp2"w9"  8"o9">exp2"w9" 16"o9">=exp2"w9" 32"o9"!=exp2"dG1
#define WR1 aF Cmp_exp2_neg q4 Cmp_exp2_neg wU gT2"p2_neg","1"o9"=-4) + 2"o9"<-4) + 4"o9"<=-4) +  8"o9">-4) + 16"o9">=-4)"dJ3 o9"!=-4"o02
#define YR1 aF Cmp_exp_neg q4 Cmp_exp_neg wU gT2"p_neg","1"m81"=-4) + 2"m81"<-4) + 4"m81"<=-4"hZ1 aR">-4) + 16"m81">=-4)"dJ3 m81"!=-4"o02
#define SS1 aI Cmp_log2_nn q4 Cmp_log2_nn wU"cmp_log2_nn","1"mA1 qA3 wN aS mA1 a4 mA1 a5 mA1 aT mA1 o51
#define TS1 aI Cmp_log2_np q4 Cmp_log2_np wU"cmp_log2_np","1"mA1"=log2"o31 mA1"<log2"o41 mA1"<=log2"wM1 mA1">log2"wN1 mA1">=log2"m91 mA1"!=log2"dG1
#define US1 aF Cmp_log2_pn q4 Cmp_log2_pn wU"cmp_log2_pn","1"hW qB3 hW aS hW a4 hW a5 hW aT hW o51
#define WS1 aF Cmp_log2_pp q4 Cmp_log2_pp wU"cmp_log2_pp","1"hW"=log2"o31 hW"<log2"o41 hW"<=log2"wM1 hW">log2"wN1 hW">=log2"m91 hW"!=log2"dG1
#define YS1 aI Cmp_log10_nn q4 Cmp_log10_nn wU"cmp_log10_nn","1"dJ qB3 dJ aS dJ a4 dJ a5 dJ aT dJ o51
#define ST1 aI Cmp_log10_np q4 Cmp_log10_np wU"cmp_log10_np","1"dJ"=log10"o31 dJ"<log10"o41 dJ"<=log10"wM1 dJ">log10"wN1 dJ">=log10"m91 dJ"!=log10"dG1
#define TT1 aF Cmp_log10_pn q4 Cmp_log10_pn wU"cmp_log10_pn","1"hR qB3 hR aS hR a4 hR a5 hR aT hR o51
#define UT1 aF Cmp_log10_pp q4 Cmp_log10_pp wU"cmp_log10_pp","1"hR"=log10"a32 q22 hR"<log10"a32 h03"4"hR"<=log10"a32" +"a22 hR">log10"a32" +"gS2 hR">=log10"a32" +  32"hR"!=log10"a32},
#define WT1 aI Cmp_log_nn q4 Cmp_log_nn wU"cmp_log_nn","1"oQ1 qA3"log(x)"aS oQ1 a4 oQ1 a5 oQ1 aT oQ1 o51
#define YT1 aI Cmp_log_np q4 Cmp_log_np wU"cmp_log_np","1"oQ1"=log"o31 oQ1"<log"o41 oQ1"<=log"wM1 oQ1">log"wN1 oQ1">=log"m91 oQ1"!=log"dG1
#define SU1 aF Cmp_log_pn q4 Cmp_log_pn wU"cmp_log_pn","1"oR1 qA3"log(abs(x))"aS oR1 a4 oR1 a5 oR1 aT oR1 o51
#define TU1 aF Cmp_log_pp q4 Cmp_log_pp wU"cmp_log_pp","1"oR1"=log"o31 oR1"<log"o41 oR1"<=log"wM1 oR1">log"wN1 oR1">=log"m91 oR1"!=log"dG1
#define UU1 aD1 qV2 q4 qV2 q4 qV2 g5"cmp_mulneg","1"a42 qW2 a42 qX2 a42 aH1 a42">4)"wF a42 d41 a42 oW1
#define WU1 aD1 qY2 q4 qY2 q4 qY2 g5"cmp_mulpos","1"a52 qW2 a52 qX2 a52 aH1 a52">4)"wF a52 d41 a52 oW1
#define YU1 aD1 qC3 q4 qC3 q4 qC3 g5"cmp_neg","1"aI1"=4) + 2"aI1"<4) + 4"aI1"<=4) +  8"aI1">4) + 16"aI1 d41 aI1 oW1
#define SV1 aF1 Cmp_powx_n_n q4 Cmp_powx_n_n,dH1"_n_n","1"g7"="w6 wC g7"<"w6 wD g7"<="w6 wE g7">"w6 wF g7">="w6 dJ3 g7"!="w6},
#define TV1 aF1 Cmp_powx_n_p q4 Cmp_powx_n_p,dH1"_n_p","1"g7"="w5 wC g7"<"w5 wD g7"<="w5 wE g7">"w5 wF g7">="w5 dJ3 g7"!="w5},
#define UV1 aJ1 Cmp_powx_nn q4 Cmp_powx_nn,dH1"_nn","1"g7 gU2 g7 gV2 g7 q32 g7 gW2 g7">=-4)"dJ3 g7"!=-4"o02
#define WV1 aJ1 Cmp_powx_np q4 Cmp_powx_np,dH1"_np","1"g7 qW2 g7 qX2 g7 aH1 g7">4)"wF g7 d41 g7 oW1
#define YV1 aF1 Cmp_powx_p_n q4 Cmp_powx_p_n,dH1"_p_n","1"oT"="w6 wC oT"<"w6 wD oT"<="w6 wE oT">"w6 wF oT">="w6 dJ3 oT"!="w6},
#define SW1 aF1 Cmp_powx_p_p q4 Cmp_powx_p_p,dH1"_p_p","1"oT"="w5 wC oT"<"w5 wD oT"<="w5 wE oT">"w5 wF oT">="w5 dJ3 oT"!="w5},
#define TW1 aJ1 Cmp_powx_pn q4 Cmp_powx_pn,dH1"_pn","1"g53 gU2 g53 gV2 g53 q32 g53 gW2 h3"x)>=-4)"dJ3 h3"x)!=-4"o02
#define UW1 aJ1 Cmp_powx_pp q4 Cmp_powx_pp,dH1"_pp","1"g53 qW2 g53 qX2 g53 aH1 h3"x)>4)"wF g53 d41 g53 oW1
#define WW1 hE Cmp_powy_n_n q4 Cmp_powy_n_n,aK1"y_n_n","1"aL1"="hE3"2"aL1"<"hE3"4"aL1"<="hE3"8"aL1">"hE3"16"aL1">="o3" 32"aL1"!=(x^-6.1))"},
#define YW1 hE Cmp_powy_n_p q4 Cmp_powy_n_p,aK1"y_n_p","1"aL1"=(x"aU wC aL1"<(x"aU wD aL1"<=(x"aU wE aL1">(x"aU wF aL1">=(x"aU dJ3 aL1"!=(x"aU},
#define SX1 hE Cmp_powy_nn q4 Cmp_powy_nn,aK1"y_nn","1"aL1 gU2 aL1 gV2 aL1 q32 aL1 gW2 aL1">=-4)"dJ3 aL1"!=-4"o02
#define TX1 hE Cmp_powy_np q4 Cmp_powy_np,aK1"y_np","1"aL1 qW2 aL1 qX2 aL1 aH1 aL1">4)"wF aL1 d41 aL1 oW1
#define UX1 hE Cmp_powy_p_n q4 Cmp_powy_p_n,aK1"y_p_n","1"h5"="hE3"2"h5"<"hE3"4"h5"<="hE3"8"h5">"hE3"16"h5">="o3" 32"h5"!=(x^-6.1))"},
#define WX1 hE Cmp_powy_p_p q4 Cmp_powy_p_p,aK1"y_p_p","1"h5"=(x"aU wC h5"<(x"aU wD h5"<=(x"aU wE h5">(x"aU wF h5">=(x"aU dJ3 h5"!=(x"aU},
#define YX1 hE Cmp_powy_pn q4 Cmp_powy_pn,aK1"y_pn","1"h5 gU2 h5 gV2 h5 q32 h5 gW2 h5">=-4)"dJ3 h5"!=-4"o02
#define SY1 hE Cmp_powy_pp q4 Cmp_powy_pp,aK1"y_pp","1"h5 qW2 h5 qX2 h5 aH1 h5">4)"wF h5 d41 h5 oW1
#define TY1 aF Cmp_sinh q4 Cmp_sinh,d9 oA2,"1"qS1"="oA2 o31 qS1"<"oA2 o41 qS1"<="oA2 wM1 qS1">"oA2 wN1 qS1">="oA2 m91 qS1"!="oA2 dG1
#define UY1 aD1 qD3 q4 qD3 q4 qD3 g5"cmp_sqr","1"wO"=16) + 2"wO"<16) + 4"wO"<=16) +  8"wO">16) + 16"wO">=16)"dJ3 wO"!=16"o02
#define WY1 aD1 mN1 q4 mN1 q4 mN1 g5"cmp_sqr_neg","1"wO"=-16) + 2"wO"<-16) + 4"wO"<=-16) +  8"wO">-16) + -16"wO">=-16)"dJ3 wO"!=-16"o02
#define YY1 {1,-4,4,hA2 q4 Cmp_tanh q4 Cmp_tanh wU"cmp_tanh","1"oO"=tanh("wX"    2"oO"<tanh("wX"    4"oO"<=tanh("wX a22 oO">tanh("wX gS2 oO">=tanh("wX"  32"oO"!=tanh(0.75))"},
#define SZ1 {1,-4,4,hA2 q4 Cmp_tanh_outrange q4 Cmp_tanh_outrange wU"cmp_tanh_outrange","1"oO"=2"o8"tanh(x)<2)"h03"4"oO"<=2) +"a22 oO">2) +"gS2 oO">=2) +  32"oO"!=2"o02
#define TZ1 qK3 Cmpeq q4 Cmpeq q4 Cmpeq g5"cmpeq","(5=3"d52"4=4"o02
#define UZ1 qK3 Cmpge q4 Cmpge q4 Cmpge g5"cmpge","(5>=3"d52"4>=8"o02
#define WZ1 qK3 Cmpgt q4 Cmpgt q4 Cmpgt g5"cmpgt","(5>3"d52"4>8"o02
#define YZ1 qK3 Cmple q4 Cmple q4 Cmple g5"cmple","(5<3"d52"4<8"o02
#define Sa1 qK3 Cmplt q4 Cmplt q4 Cmplt g5"cmplt","(5<3)+x"},
#define Ta1 qK3 Cmpne q4 Cmpne q4 Cmpne g5"cmpne","(5!=3"d52"4!=4"o02
#define Ua1 qK3 Div q4 Div q4 Div g5"div","(5/4)+x"},
#define Wa1 qK3 Div1 q4 Div1 q4 Div1 g5"div1","x/1+x"},
#define Ya1 qK3 Divxx q4 Divxx q4 Divxx g5"divxx","x+x/x+x"},
#define Sb1 qK3 Eq0 q4 Eq0 q4 Eq0 g5"eq0","(x=0"qI3"0="oS2
#define Tb1 qK3 Eq1 q4 Eq1 q4 Eq1 g5"eq1","(!x=1"o02
#define Ub1 aE1 qE3 q4 qE3 q4 qE3 g5"ge0_abs"aM1 hM3 hR3 hN3 hS3
#define Wb1 m32 Ge0_neg q4 Ge0_neg wU"ge0_neg"aO1 hM3 oU hN3 hA3
#define Yb1 m32 Ge0_pos q4 Ge0_pos wU"ge0_pos","("g81 hM3 h73 hN3 hK3
#define Sc1 aE1 qF3 q4 qF3 q4 qF3 g5"ge1_abs"aM1 hO3 hR3 hP3 hS3
#define Tc1 m32 Ge1_neg q4 Ge1_neg wU"ge1_neg"aO1 hO3 oU hP3 hA3
#define Uc1 m32 Ge1_pos q4 Ge1_pos wU"ge1_pos","("g81 hO3 h73 hP3 hK3
#define Wc1 m32 Gehalf q4 Gehalf wU"gehalf","x>=0.5"},
#define Yc1 aE1 qG3 q4 qG3 q4 qG3 g5"gt0_abs"aM1 d03 hR3 d13 hS3
#define Sd1 m32 Gt0_neg q4 Gt0_neg wU"gt0_neg"aO1 d03 oU d13 hA3
#define Td1 m32 Gt0_pos q4 Gt0_pos wU"gt0_pos","("g81 d03 h73 d13 hK3
#define Ud1 aE1 qH3 q4 qH3 q4 qH3 g5"gt1_abs"aM1 d23 hR3 d33 hS3
#define Wd1 m32 Gt1_neg q4 Gt1_neg wU"gt1_neg"aO1 d23 oU d33 hA3
#define Yd1 m32 Gt1_pos q4 Gt1_pos wU"gt1_pos","("g81 d23 h73 d33 hK3
#define Se1 m32 Gtminushalf q4 Gtminushalf wU"gtminushalf","x>-0.5"},
#define Te1 {1,gS3 Immsub q4 Immsub q4 Immsub g5"immsub","x-5"},
#define Ue1 m32 Leminushalf q4 Leminushalf wU"leminushalf","x<=-0.5"},
#define We1 {1,0,3,oZ Log2exp1 q4 Log2exp1 wU"log2exp1",m62"log2"g51
#define Ye1 {1,-1,N(0.75),hA2 q4 Log2exp2 q4 Log2exp2 wU"log2exp2","exp2(log2(acos(x)))"},
#define Sf1 {1,0,3,oZ Logexp1 q4 Logexp1 wU"logexp1",m62"log"g51
#define Tf1 {1,-1,N(0.75),hA2 q4 Logexp2 q4 Logexp2 wU"logexp2",m62"log(acos(x)))"},
#define Uf1 g61 Logmul q4 Logmul wU"logmul","log("o61
#define Wf1 g61 Logmul2 q4 Logmul2 wU"logmul2","log2("o61
#define Yf1 g61 Logmul10 q4 Logmul10 wU"logmul10","log10("o61
#define Sg1 aE1 Lt0 q4 Lt0 q4 Lt0 g5"lt0","sub(abs(x)<0, x<0"o02
#define Tg1 m32 Lthalf q4 Lthalf wU"lthalf","x<0.5"},
#define Ug1 qK3 Mod q4 Mod q4 Mod g5"mod","(5%4)+x"},
#define Wg1 qK3 Mul q4 Mul q4 Mul g5"mul","(5*4)+x"},
#define Yg1 qK3 Mul1 q4 Mul1 q4 Mul1 g5"mul1","x*1+x"},
#define Sh1 qK3 Mul1b q4 Mul1b wU"mul1b",wJ"0.2)*5)+x"},
#define Th1 {2,N(0.1),10,N(0.1)qM q4 Mul_zero q4 Mul_zero dW gR"mul_zero","(x*y+1)+(sin(x)+sin(y))*log(x)*y*x*0"},
#define Uh1 qK3 Mulneg q4 Mulneg q4 Mulneg g5"mulneg","-"a92
#define Wh1 qK3 a82 q4 a82 q4 a82 g5"multodiv","x/4+x"},
#define Yh1 {2,gS3 Negadd q4 Negadd q4 Negadd,mO2"negadd","x+(-y"o02
#define Si1 g9 Negcos q4 Negcos wU"negcos","cos"g72
#define Ti1 g9 Negcosh q4 Negcosh wU"negcosh","cosh"g72
#define Ui1 qK3 Negmul q4 Negmul q4 Negmul g5"negmul","(-x)*5"},
#define Wi1 g9 Negsin q4 Negsin wU"negsin","sin(-"oS2
#define Yi1 g9 Negsinh q4 Negsinh wU"neg"oA2,oA2 g72
#define Sj1 {2,gS3 Negsub q4 Negsub q4 Negsub,mO2"negsub","x-(-y"o02
#define Tj1 g9 Negtan q4 Negtan wU"negtan","tan"g72
#define Uj1 g9 Negtanh q4 Negtanh wU"negtanh","tanh"g72
#define Wj1 qK3 Neq0 q4 Neq0 q4 Neq0 g5"neq0","(x!=0"qI3"0!="oS2
#define Yj1 qK3 Neq1 q4 Neq1 q4 Neq1 g5"neq1","(!x!=1"o02
#define Sk1 qK3 Not q4 Not q4 Not g5"not","(!(3))+x"},
#define Tk1 qK3 Or q4 Or q4 Or g5"or","(5|3"d52"5|0)+(0|5)+(0|0"o02
#define Uk1 g9 Sincos_cci q4 Sincos_cci,aK"cos_cci","cos"dA2" sec(x)"},
#define Wk1 g9 Sincos_cic q4 Sincos_cic,aK"cos_cic","sec"dA2 mO1
#define Yk1 g9 Sincos_sc q4 Sincos_sc,aK"cos_sc",qO3 mO1
#define Sl1 g9 Sincos_sci q4 Sincos_sci,aK"cos_sci",qO3" sec(x)"},
#define Tl1 g9 Sincos_sis q4 Sincos_sis,aK"cos_sis","csc"dA2" "q42},
#define Ul1 g9 Sincos_ssi q4 Sincos_ssi,aK"cos_ssi",qO3" csc(x)"},
#define Wl1 g9 Sincos_tan q4 Sincos_tan,aK"cos_tan",q42" /"mO1
#define Yl1 g9 Sincos_tit q4 Sincos_tit,aK"cos_tit","cot"dA2" tan(x)"},
#define Sm1 g9 Sincos_tti q4 Sincos_tti,aK"cos_tti","tan"dA2" cot(x)"},
#define Tm1 qK3 Sqreq0 q4 Sqreq0 q4 Sqreq0 g5"sqreq0","(x*x=0"qI3"0=x*x)"},
#define Um1 qK3 qP3 q4 qP3 q4 qP3 g5"sqrneq0","(x*x=0"qI3"0=x*x)"},
#define Wm1 {1,0,3,oZ Sqrtsqr1 q4 Sqrtsqr1 wU"sqrtsqr1","sqrt(x)^2"},
#define Ym1 {oY Sqrtsqr2 q4 Sqrtsqr2 wU"sqrtsqr2","sqrt(acos(x))^2"},
#define Sn1 qK3 Sub q4 Sub q4 Sub g5"sub","5-3+x"},
#define Tn1 qK3 Sub0 q4 Sub0 q4 Sub0 g5"sub0","x-0+x"},
#define Un1 {1 aG wB Subxx q4 Subxx q4 Subxx g5"subxx","x+(x-x)+x+(1-x+x)"},
#define Wn1 g9 Xmulsinhneg q4 Xmulsinhneg,0,q7"/xmulsinhneg","-"oA2 a92
#define Yn1 g9 Xmulsinneg q4 Xmulsinneg,0,q7"/xmulsinneg","-sin(x*"gX2
#define So1 g9 Xmultanhneg q4 Xmultanhneg,0,q7"/xmultanhneg","-tanh"a92
#define To1 g9 Xmultanneg q4 Xmultanneg,0,q7"/xmultanneg","-tan"a92
#define Uo1 {1,N(0.5),3,N(0.7)qM q4 Xsqryfsqrhypot q4 Xsqryfsqrhypot,0,q7"/xsqryfsqrhypot","sqrt(log(x)^2+"wN"^2"o02
#define Wo1 {2,N(0.5),3,N(0.7)qM q4 Xsqrysqrhypot q4 Xsqrysqrhypot a51,"10optimizer_bytecode/xsqrysqrhypot","sqrt(log(x)^2+y*y"o02
#define Yo1 {1 aL t1,q5 t1,q5 t1,"a",qE"1","(1/a"qS3
#define Sp1 {1 aL t2,q5 t2,q5 t2,"a",qE"2","5*a"},
#define Tp1 {1 aL t3,q5 t3,q5 t3,"a",qE"3","5/a"},
#define Up1 {2 aL t4,q5 t4,q5 t4,hB"4","(a*5)*b"},
#define Wp1 {2 aL t5,q5 t5,q5 t5,hB"5","(a*5)/b"},
#define Yp1 {2 aL t6,q5 t6,q5 t6,hB"6","(1/a)*b"},
#define Sq1 {2 aL t7,q5 t7,q5 t7,hB"7","(1/a)/b"},
#define Tq1 {2 aL t8,q5 t8,q5 t8,hB"8",aA2")*("aB2")*"gX2
#define Uq1 {2 aL t9,q5 t9,q5 t9,hB"9",aA2")/("aB2")*"gX2
#define Wq1 aM t10,q5 t10,q5 t10,hB"10",aB2")*(5/a"o02
#define Yq1 aM t11,q5 t11,q5 t11,hB"11",aB2")/(50/a"o02
#define Sr1 m92 t12,q5 t12,q5 t12,"a",qE"12","(-a)+5"},
#define Tr1 aM t13,q5 t13,q5 t13,hB"13","5+(a*b"o02
#define Ur1 aM t14,q5 t14,q5 t14,hB"14","5-(a*b"o02
#define Wr1 aM t15,q5 t15,q5 t15,hB"15","(a+5)+"aB2 o02
#define Yr1 aM t16,q5 t16,q5 t16,hB"16","(a+5)-abs(b"o02
#define Ss1 aM t17,q5 t17,q5 t17,hB"17","(-a)+"aB2 o02
#define Ts1 aM t18,q5 t18,q5 t18,hB"18","(-a)-abs(b"o02
#define Us1 aM t19,q5 t19,q5 t19,hB"19","b+("aA2")+"gX2
#define Ws1 aM t20,q5 t20,q5 t20,hB"20","b-("aA2")+"gX2
#define Ys1 aM t21,q5 t21,q5 t21,hB"21",aB2")+(5-a"o02
#define St1 aM t22,q5 t22,q5 t22,hB"22",aB2")-(5-a"o02
#define Tt1 aM t23,q5 t23,q5 t23,hB"23",h41"b"qQ3
#define Ut1 aM t24,q5 t24,q5 t24,hB"24",h41"5"qQ3
#define Wt1 aM t25,q5 t25,q5 t25,hB"25",h41"5"qR3
#define Yt1 aM t26,q5 t26,q5 t26,hB"26","(   abs(a)/b"qQ3
#define Su1 aM t27,q5 t27,q5 t27,hB"27","(   abs(a)/b"qR3
#define Tu1 aM t28,q5 t28,q5 t28,hB"28","((-a)/b"qS3
#define Uu1 aM t29,q5 t29,q5 t29,hB"29","(5/b"qR3
#define Wu1 m92 t30,q5 t30,q5 t30,"b",qE"30","(7/b"qS3
#define Yu1 aM t31,q5 t31,q5 t31,hB"31","b*(7/-a"o02
#define Sv1 aM t32,q5 t32,q5 t32,hB"32","(5-b)-a"},
#define Tv1 aM t33,q5 t33,q5 t33,hB"33","(5-b)+a"},
#define Uv1 aM t34,q5 t34,q5 t34,hB"34","((a+7)-b)+5"},
#define Wv1 aM t35,q5 t35,q5 t35,hB"35","((-a)-b)+5"},
#define Yv1 m92 t36,q5 t36,q5 t36,"a",qE"36","(7-abs(a))+5"},
#define Sw1 aM t37,q5 t37,q5 t37,hB"37","((7-b)+a)+5"},
#define Tw1 aM t38,q5 t38,q5 t38,hB"38","((5*b+"aA2"))<0)*1 + (("aB2"))<0)*2"},
#define Uw1 m92 t39,q5 t39,q5 t39,"a",qE"39","(a+7"qS3
#define Ww1 aM t40,q5 t40,q5 t40,hB"40","(b+(a*7))*5"},
#define Yw1 aM t41,q5 t41,q5 t41,hB"41","(b-(a*7))*5"},
#define Sx1 m92 t42,q5 t42,q5 t42,"a",qE"42","(a+7)+5"},
#define Tx1 m92 t43,q5 t43,q5 t43,"a",qE"43","(a*7"qS3
#define Ux1 gL3 qT3 q2 qT3 q2 qT3 oK1"abseq0"aM1"=if"gY2 dB3"(if"gY2")=abs"g51
#define Wx1 gL3 aC2 q2 aC2 q2 aC2 oK1"absneq0"aM1"=if"gY2 dB3"(if"gY2")=abs"g51
#define Yx1 gL3 Eq0,q2 Eq0,q2 Eq0,oK1"eq0","(x=if("qT1" (if(1,0,0)="oS2
#define Sy1 gL3 Eq1,q2 Eq1,q2 Eq1,oK1"eq1","(!x=if"gM3},
#define Ty1 dP3 aD2 q2 aD2 q2 aD2 oK1"ge0_abs"aM1 dO3 h83"  2"hP1 dN3 hB3"<= "h83"8"hP1 dO3 hS3
#define Uy1 dP3 aE2 q2 aE2 q2 aE2 oK1"ge1_abs"aM1" >= if"gM3 q22 dI1 dN3 hB3"<= if"hQ1 dB3" 8"dI1 dO3 hS3
#define Wy1 {1 d6 hA2,q2 Gehalf,q2 Gehalf,gD"gehalf","x>=if(1,0.5,0"o02
#define Yy1 dP3 aF2 q2 aF2 q2 aF2 oK1"gt0_abs"aM1" > "h83"  2"hP1 dH3 hB3"< "h83"8"hP1" > "hS3
#define Sz1 dP3 aG2 q2 aG2 q2 aG2 oK1"gt1_abs"aM1" > if"gM3 q22 dI1 dH3 hB3"< if"hQ1 dB3" 8"dI1" > "hS3
#define Tz1 {1 d6 hA2,q2 Lthalf,q2 Lthalf,gD"lthalf","x<if(1,0.5,0"o02
#define Uz1 gL3 Neq0,q2 Neq0,q2 Neq0,oK1"neq0","(x!=if("qT1" (if(1,0,0)!="oS2
#define Wz1 gL3 Neq1,q2 Neq1,q2 Neq1,oK1"neq1","(!x!=if"gM3},
#define Yz1 {1,-9,9,gR3 t7,g3 t7,g3 t7,m42"7","x>7 & x<2"},
#define S_1 {2,-9,9,gR3 t8,g3 t8 a51,oF"8",aH2"(-x,-y) + 10*"aH2"(-x,y) + 20*"aH2"(x,-y) + 30*"aH2"(x"mF1
#define T_1 {1 aP1 t9a,g3 t9a,g3 t9a,m42"9a","a:=x;a*0"},
#define U_1 {2 aP1 t9b,g3 t9b,g3 t9b,aI2"9b","sub(a,b"qU3
#define W_1 {2 aP1 t9c,g3 t9c,g3 t9c,aI2"9c","psub(a,b"qU3
#define Y_1 {2 aP1 t9d,g3 t9d,g3 t9d,aI2"9d","if(a,b*0,a*0"qU3
#define S02 {2,hD Add_cd,0 a61"add_cd","x+y"},
#define T02 {2,g33 Add_d,qG Add_d a61"add_d","x+y"},
#define U02 {3,hD Addsub_cd,0 wQ2 g0"addsub_cd","x+y+x+x-z+x"},
#define W02 {3,g33 Addsub_d,qG Addsub_d wQ2 g0"addsub_d","x+y+x+x-z+x"},
#define Y02 {2,gK And_d,qG And_d a61"and_d","x&y"},
#define S12 {2,hD Cmpeq_cd,0 a61"cmpeq_cd","x=y"},
#define T12 {2,gK Cmpeq_d,qG Cmpeq_d a61"cmpeq_d","x=y"},
#define U12 {2,gK Cmpge_d,qG Cmpge_d a61"cmpge_d","x>=y"},
#define W12 {2,gK Cmpgt_d,qG Cmpgt_d a61"cmpgt_d","x>y"},
#define Y12 {2,gK Cmple_d,qG Cmple_d a61"cmple_d","x<=y"},
#define S22 {2,gK Cmplt_d,qG Cmplt_d a61"cmplt_d","x<y"},
#define T22 {2,hD Cmpne_cd,0 a61"cmpne_cd","x!=y"},
#define U22 {2,gK Cmpne_d,qG Cmpne_d a61"cmpne_d","x!=y"},
#define W22 {2 dB Div_d,qG Div_d a61"div_d","(x-0.25)/y"},
#define Y22 {3 dB Divmul_d,qG Divmul_d wQ2 g0"divmul_d","x*y*x*x/z"oH2"-0.25"o02
#define S32 {1,N(-7.0,0.0),N(6.0,0.0),N(0.6,0.0)qM,qG Inv_d,qG Inv_d dW g0"inv_d","1/x"},
#define T32 {2,N(-7.25,+3.625),N(7.25,-3.625),N(0.5,-0.25)qM,qG Mul_cd,0 a61"mul_cd","x*y"},
#define U32 {2 dB Mul_d,qG Mul_d a61"mul_d","x*y"},
#define W32 {1,hD Neg_cd,0 dW g0"neg_cd","-x"},
#define Y32 {1,g33 Neg_d,qG Neg_d dW g0"neg_d","-x"},
#define S42 {1,N(-1.25,0.0),N(1.25,0.0)oZ1 qM,qG Not_d,qG Not_d dW g0"not_d","!x"},
#define T42 {1,N(-1.25,0.0),N(1.25,0.0)oZ1 qM,qG Notnot_d,qG Notnot_d dW g0"notnot_d","!!x"},
#define U42 {2,gK Or_d,qG Or_d a61"or_d","x|y"},
#define W42 {2,hD Sub_cd,0 a61"sub_cd","x-y"},
#define Y42 {2,g33 Sub_d,qG Sub_d a61"sub_d","x-y"},
#define S52 {1,N(-400.0,+200.0),N(400.0,-200.0),N(0.5,-0.25)qM qB Abs_cd,dQ2"abs_cd",d63},
#define T52 gX Arg,dQ2"arg"mP1
#define U52 gX Conj,dQ2"conj","conj(x)"},
#define W52 gX Imag,dQ2"imag","imag(x)"},
#define Y52 gX Log qB Log gG1"log"mP1
#define S62 {1,N(-4000.0,-0.5),N(4000.0,+0.5),N(0.3,+3.75e-05)qM qB Log_cd,dQ2"log_cd"mP1
#define T62 {2,N(-4.0,0.0),mR1 N(1.0,0.0)qM qB Max qB Max qB Max,"x,y"wS"/max","max(x"mF1
#define U62 {2,N(-4.0,0.0),mR1 N(1.0,0.0)qM qB Min qB Min qB Min,"x,y"wS"/min","min(x"mF1
#define W62 {2,N(0.01,0.0),mR1 N(0.05,0.0)qM qB Polar,wR"/polar","polar(x"mF1
#define Y62 gX Real,dQ2"real","real(x)"},
#define S72 {1,N(-100000.0,0.0),N(100000.0,0.0),N(1000.0,0.0)qM qB Sqrt_cd,dQ2"sqrt_cd","sqrt(x)"},
#define T72 {1,g6 t1,q5 t1,q5 t1,"a",qE"1","(1/a"qS3
#define U72 {1,g6 t2,q5 t2,q5 t2,"a",qE"2","5*a"},
#define W72 {1,g6 t3,q5 t3,q5 t3,"a",qE"3","5/a"},
#define Y72 {2,g6 t4,q5 t4,q5 t4,hB"4","(a*5)*b"},
#define S82 {2,g6 t5,q5 t5,q5 t5,hB"5","(a*5)/b"},
#define T82 {2,g6 t6,q5 t6,q5 t6,hB"6","(1/a)*b"},
#define U82 {2,g6 t7,q5 t7,q5 t7,hB"7","(1/a)/b"},
#define W82 {2,g6 t8,q5 t8,q5 t8,hB"8",aA2")*("aB2")*"gX2
#define Y82 {2,g6 t9,q5 t9,q5 t9,hB"9",aA2")/("aB2")*"gX2
#define S92 wA1 t10,q5 t10,q5 t10,hB"10",aB2")*(5/a"o02
#define T92 wA1 t11,q5 t11,q5 t11,hB"11",aB2")/(50/a"o02
#define U92 {1,q9 t12,q5 t12,q5 t12,"a",qE"12","(-a)+5"},
#define W92 wA1 t13,q5 t13,q5 t13,hB"13","5+(a*b"o02
#define Y92 wA1 t14,q5 t14,q5 t14,hB"14","5-(a*b"o02
#define SA2 wA1 t15,q5 t15,q5 t15,hB"15","(a+5)+"aB2 o02
#define TA2 wA1 t16,q5 t16,q5 t16,hB"16","(a+5)-abs(b"o02
#define UA2 wA1 t17,q5 t17,q5 t17,hB"17","(-a)+"aB2 o02
#define WA2 wA1 t18,q5 t18,q5 t18,hB"18","(-a)-abs(b"o02
#define YA2 wA1 t19,q5 t19,q5 t19,hB"19","b+("aA2")+"gX2
#define SB2 wA1 t20,q5 t20,q5 t20,hB"20","b-("aA2")+"gX2
#define TB2 wA1 t21,q5 t21,q5 t21,hB"21",aB2")+(5-a"o02
#define UB2 wA1 t22,q5 t22,q5 t22,hB"22",aB2")-(5-a"o02
#define WB2 wA1 t23,q5 t23,q5 t23,hB"23",h41"b"qQ3
#define YB2 wA1 t24,q5 t24,q5 t24,hB"24",h41"5"qQ3
#define SC2 wA1 t25,q5 t25,q5 t25,hB"25",h41"5"qR3
#define TC2 wA1 t26,q5 t26,q5 t26,hB"26","(   abs(a)/b"qQ3
#define UC2 wA1 t27,q5 t27,q5 t27,hB"27","(   abs(a)/b"qR3
#define WC2 wA1 t28,q5 t28,q5 t28,hB"28","((-a)/b"qS3
#define YC2 wA1 t29,q5 t29,q5 t29,hB"29","(5/b"qR3
#define SD2 {1,q9 t30,q5 t30,q5 t30,"b",qE"30","(7/b"qS3
#define TD2 wA1 t31,q5 t31,q5 t31,hB"31","b*(7/-a"o02
#define UD2 wA1 t32,q5 t32,q5 t32,hB"32","(5-b)-a"},
#define WD2 wA1 t33,q5 t33,q5 t33,hB"33","(5-b)+a"},
#define YD2 wA1 t34,q5 t34,q5 t34,hB"34","((a+7)-b)+5"},
#define SE2 wA1 t35,q5 t35,q5 t35,hB"35","((-a)-b)+5"},
#define TE2 {1,q9 t36,q5 t36,q5 t36,"a",qE"36","(7-abs(a))+5"},
#define UE2 wA1 t37,q5 t37,q5 t37,hB"37","((7-b)+a)+5"},
#define WE2 wA1 t38,q5 t38,q5 t38,hB"38","((5*b+"aA2"))<0)*1 + (("aB2"))<0)*2"},
#define YE2 {1,q9 t39,q5 t39,q5 t39,"a",qE"39","(a+7"qS3
#define SF2 wA1 t40,q5 t40,q5 t40,hB"40","(b+(a*7))*5"},
#define TF2 wA1 t41,q5 t41,q5 t41,hB"41","(b-(a*7))*5"},
#define UF2 {1,q9 t42,q5 t42,q5 t42,"a",qE"42","(a+7)+5"},
#define WF2 {1,q9 t43,q5 t43,q5 t43,"a",qE"43","(a*7"qS3
#define YF2 {1 aJ Abscos,q2 Abscos,gD"abscos","cos(sqrt("a81"))) + sqrt("a81"))"},
#define SG2 {1 aJ Abscosh,q2 Abscosh,gD"abscosh","cosh(sqrt("a81"))) + sqrt("a81"))"},
#define TG2 {1 qP1 qT3 q2 qT3 q2 qT3 oK1"abseq0"aM1"=if"gY2 dB3"(if"gY2")=abs"g51
#define UG2 {1 qP1 aC2 q2 aC2 q2 aC2 oK1"absneq0"aM1"=if"gY2 dB3"(if"gY2")=abs"g51
#define WG2 {1,N(-5.0,0.0),N(5.0,0.0),gL2 oW2 q2 oW2 q2 oW2 oK1"absnzge","sub(abs(x) >= if("oX2"), "d63" >= (if(1,1,0)-1))"},
#define YG2 {1,N(-5.0,0.0),N(5.0,0.0),gL2 oY2 q2 oY2 q2 oY2 oK1"absnzlt","sub(abs(x)"dH3"if("oX2"), "d63 dH3"(if(1,1,0)-1))"},
#define SH2 {1,N(-1.0,0.0),N(1.0,0.0),N(0.1,0.0)qM,q2 Acoscos,q2 Acoscos,gD"acoscos","cos(acos"g51
#define TH2 {1,N(1.7,0.0),N(3.7,0.0),N(0.28,0.0)qM,q2 Acoshsinh,q2 Acoshsinh,gD q23 oA2,oA2"(if(1,acosh(x),0))"},
#define UH2 {hM mE1,q2 mE1,q2 mE1 qN"addconstmul","5*(if("oX2")+x+y"o02
#define WH2 {2 oZ1,N(1.0,0.0)oZ1 qM,q2 Addlog,q2 Addlog,0 qN"addlog","log(x)+log(y"o02
#define YH2 {hM dR1,q2 dR1,q2 dR1 qN"addmulconstmul","5*(if("oX2")*y+x)"},
#define SI2 {hM wS1,q2 wS1,q2 wS1 qN"addnegmulneg","-5 + (if(1,5,0)*x*y"o02
#define TI2 {hM wT1,q2 wT1,q2 wT1 qN"addnegmulpos","(if(1,-5,0)*y"qI3"if(1,5,0)*x)"},
#define UI2 {1,h9 Addsin2cos2,q2 Addsin2cos2,gD"addsin2cos2",q42"^2 + cos(x)^2"},
#define WI2 {1,N(-0.7,0.0),N(0.7,0.0),N(0.28,0.0)qM,q2 Asinhcosh,q2 Asinhcosh,gD"asinhcosh","cosh(if(1,a"oA2"(x),0))"},
#define YI2 {1,N(-1.0,0.0),N(1.0,0.0),N(0.1,0.0)qM,q2 Asinsin,q2 Asinsin,gD"asinsin","sin(asin(x))"},
#define SJ2 oG w01,q2 w01,q2 w01 qN"cmpeq_add_imm",h61 hE2
#define TJ2 wO1 gH1 q2 gH1 q2 gH1 oK1"cmpeq_add_reduce",d73"="dQ3
#define UJ2 oG h81,q2 h81,q2 h81 qN"cmpeq_addadd_imm",o7 w72
#define WJ2 {hN wU1,q2 wU1,q2 wU1 qN"cmpeq_minma"oZ2" = "hF3
#define YJ2 {hN h91,q2 h91,q2 h91 qN"cmpeq_minmax"d83"= "h93
#define SK2 oG gI1,q2 gI1,q2 gI1 qN"cmpeq_mul_imm_neg",dT1 hE2
#define TK2 oG gJ1,q2 gJ1,q2 gJ1 qN"cmpeq_mul_imm_pos",wV1 hE2
#define UK2 oG mP,q2 mP,q2 mP qN"cmpeq_mulmul_imm_neg",mM2 w72
#define WK2 oG mQ,q2 mQ,q2 mQ qN"cmpeq_mulmul_imm_pos",gP3 w72
#define YK2 oL1 Cmpeq_pow_imm_negneg,q2 Cmpeq_pow_imm_negneg,gD a91 hS" = "gZ3
#define SL2 oL1 Cmpeq_pow_imm_negpos,q2 Cmpeq_pow_imm_negpos,gD a91 hT" = "h13
#define TL2 wO1 Cmpeq_pow_imm_posneg,q2 Cmpeq_pow_imm_posneg,gD a91 d0" = "d53
#define UL2 wO1 Cmpeq_pow_imm_pospos,q2 Cmpeq_pow_imm_pospos,gD a91 d3" = "hG3
#define WL2 wO1 Cmpeq_pow_imm_pospos_base,q2 Cmpeq_pow_imm_pospos_base,gD a91 h33"= "wK
#define YL2 oG Cmpeq_powpow_imm_base,q2 Cmpeq_powpow_imm_base,0 qN a91 hC" = "a3
#define SM2 oG w11,q2 w11,q2 w11 qN"cmpge_add_imm",h61 qK2
#define TM2 wO1 gK1 q2 gK1 q2 gK1 oK1"cmpge_add_reduce",d73">="dQ3
#define UM2 oG hA1,q2 hA1,q2 hA1 qN"cmpge_addadd_imm",o7 o72
#define WM2 {hN wW1,q2 wW1,q2 wW1 qN"cmpge_minma"oZ2 dO3 hF3
#define YM2 {hN hB1,q2 hB1,q2 hB1 qN"cmpge_minmax"d83">= "h93
#define SN2 oG gL1,q2 gL1,q2 gL1 qN"cmpge_mul_imm_neg",dT1 qK2
#define TN2 oG gM1,q2 gM1,q2 gM1 qN"cmpge_mul_imm_pos",wV1 qK2
#define UN2 oG mR,q2 mR,q2 mR qN"cmpge_mulmul_imm_neg",mM2 o72
#define WN2 oG mS,q2 mS,q2 mS qN"cmpge_mulmul_imm_pos",gP3 o72
#define YN2 oL1 Cmpge_pow_imm_negneg,q2 Cmpge_pow_imm_negneg,o71 hS dO3 gZ3
#define SO2 oL1 Cmpge_pow_imm_negpos,q2 Cmpge_pow_imm_negpos,o71 hT dO3 h13
#define TO2 wO1 Cmpge_pow_imm_posneg,q2 Cmpge_pow_imm_posneg,o71 d0 dO3 d53
#define UO2 wO1 Cmpge_pow_imm_pospos,q2 Cmpge_pow_imm_pospos,o71 d3 dO3 hG3
#define WO2 wO1 Cmpge_pow_imm_pospos_base,q2 Cmpge_pow_imm_pospos_base,o71 h33">= "wK
#define YO2 oG Cmpge_powpow_imm_base,q2 Cmpge_powpow_imm_base,0 qN"cmpge_"hC dO3 a3
#define SP2 oG w21,q2 w21,q2 w21 qN"cmpgt_add_imm",h61 hF2
#define TP2 wO1 gN1 q2 gN1 q2 gN1 oK1"cmpgt_add_reduce",d73">"dQ3
#define UP2 oG hC1,q2 hC1,q2 hC1 qN"cmpgt_addadd_imm",o7 w52
#define WP2 {hN wX1,q2 wX1,q2 wX1 qN"cmpgt_minma"oZ2" > "hF3
#define YP2 {hN hD1,q2 hD1,q2 hD1 qN"cmpgt_minmax"d83"> "h93
#define SQ2 oG gO1,q2 gO1,q2 gO1 qN"cmpgt_mul_imm_neg",dT1 hF2
#define TQ2 oG gP1,q2 gP1,q2 gP1 qN"cmpgt_mul_imm_pos",wV1 hF2
#define UQ2 oG mT,q2 mT,q2 mT qN"cmpgt_mulmul_imm_neg",mM2 w52
#define WQ2 oG mU,q2 mU,q2 mU qN"cmpgt_mulmul_imm_pos",gP3 w52
#define YQ2 oL1 Cmpgt_pow_imm_negneg,q2 Cmpgt_pow_imm_negneg,o81 hS" > "gZ3
#define SR2 oL1 Cmpgt_pow_imm_negpos,q2 Cmpgt_pow_imm_negpos,o81 hT" > "h13
#define TR2 wO1 Cmpgt_pow_imm_posneg,q2 Cmpgt_pow_imm_posneg,o81 d0" > "d53
#define UR2 wO1 Cmpgt_pow_imm_pospos,q2 Cmpgt_pow_imm_pospos,o81 d3" > "hG3
#define WR2 wO1 Cmpgt_pow_imm_pospos_base,q2 Cmpgt_pow_imm_pospos_base,o81 h33"> "wK
#define YR2 oG Cmpgt_powpow_imm_base,q2 Cmpgt_powpow_imm_base,0 qN"cmpgt_"hC" > "a3
#define SS2 oG w31,q2 w31,q2 w31 qN"cmple_add_imm",h61 qL2
#define TS2 wO1 gQ1 q2 gQ1 q2 gQ1 oK1"cmple_add_reduce",d73"<="dQ3
#define US2 oG hE1,q2 hE1,q2 hE1 qN"cmple_addadd_imm",o7 w62
#define WS2 {hN wY1,q2 wY1,q2 wY1 qN"cmple_minma"oZ2 dN3 hF3
#define YS2 {hN hF1,q2 hF1,q2 hF1 qN"cmple_minmax"d83"<= "h93
#define ST2 oG gR1,q2 gR1,q2 gR1 qN"cmple_mul_imm_neg",dT1 qL2
#define TT2 oG gS1,q2 gS1,q2 gS1 qN"cmple_mul_imm_pos",wV1 qL2
#define UT2 oG mV,q2 mV,q2 mV qN"cmple_mulmul_imm_neg",mM2 w62
#define WT2 oG mW,q2 mW,q2 mW qN"cmple_mulmul_imm_pos",gP3 w62
#define YT2 oL1 Cmple_pow_imm_negneg,q2 Cmple_pow_imm_negneg,m52 hS dN3 gZ3
#define SU2 oL1 Cmple_pow_imm_negpos,q2 Cmple_pow_imm_negpos,m52 hT dN3 h13
#define TU2 wO1 Cmple_pow_imm_posneg,q2 Cmple_pow_imm_posneg,m52 d0 dN3 d53
#define UU2 wO1 Cmple_pow_imm_pospos,q2 Cmple_pow_imm_pospos,m52 d3 dN3 hG3
#define WU2 wO1 Cmple_pow_imm_pospos_base,q2 Cmple_pow_imm_pospos_base,m52 h33"<= "wK
#define YU2 oG Cmple_powpow_imm_base,q2 Cmple_powpow_imm_base,0 qN aA1 hC dN3 a3
#define SV2 oG w41,q2 w41,q2 w41 qN"cmplt_add_imm",h61 qM2},
#define TV2 wO1 gT1 q2 gT1 q2 gT1 oK1"cmplt_add_reduce",d73"<"dQ3
#define UV2 oG hG1,q2 hG1,q2 hG1 qN"cmplt_addadd_imm",o7")"dH3 hY
#define WV2 {hN wZ1,q2 wZ1,q2 wZ1 qN"cmplt_minma"oZ2 dH3 hF3
#define YV2 {hN hH1,q2 hH1,q2 hH1 qN"cmplt_minmax"d83"< "h93
#define SW2 oG gU1,q2 gU1,q2 gU1 qN"cmplt_mul_imm_neg",dT1 qM2},
#define TW2 oG gV1,q2 gV1,q2 gV1 qN"cmplt_mul_imm_pos",wV1 qM2},
#define UW2 oG mX,q2 mX,q2 mX qN"cmplt_mulmul_imm_neg",mM2")"dH3 hY
#define WW2 oG mY,q2 mY,q2 mY qN"cmplt_mulmul_imm_pos",wJ"4)"dH3 hY
#define YW2 oL1 Cmplt_pow_imm_negneg,q2 Cmplt_pow_imm_negneg,o91 hS dH3 gZ3
#define SX2 oL1 Cmplt_pow_imm_negpos,q2 Cmplt_pow_imm_negpos,o91 hT dH3 h13
#define TX2 wO1 Cmplt_pow_imm_posneg,q2 Cmplt_pow_imm_posneg,o91 d0 dH3 d53
#define UX2 wO1 Cmplt_pow_imm_pospos,q2 Cmplt_pow_imm_pospos,o91 d3 dH3 hG3
#define WX2 wO1 Cmplt_pow_imm_pospos_base,q2 Cmplt_pow_imm_pospos_base,o91 h33"< "wK
#define YX2 oG Cmplt_powpow_imm_base,q2 Cmplt_powpow_imm_base,0 qN"cmplt_"hC dH3 a3
#define SY2 oG w51,q2 w51,q2 w51 qN"cmpne_add_imm",h61 a01},
#define TY2 wO1 gW1 q2 gW1 q2 gW1 oK1"cmpne_add_reduce",d73"!="dQ3
#define UY2 oG hI1,q2 hI1,q2 hI1 qN"cmpne_addadd_imm",o7 o82
#define WY2 {hN a11,q2 a11,q2 a11 qN"cmpne_minma"oZ2 dI3 hF3
#define YY2 {hN hJ1,q2 hJ1,q2 hJ1 qN"cmpne_minmax"d83"!= "h93
#define SZ2 oG gX1,q2 gX1,q2 gX1 qN"cmpne_mul_imm_neg",dT1 a01},
#define TZ2 oG gY1,q2 gY1,q2 gY1 qN"cmpne_mul_imm_pos",wV1 a01},
#define UZ2 oG mZ,q2 mZ,q2 mZ qN"cmpne_mulmul_imm_neg",mM2 o82
#define WZ2 oG q01,q2 q01,q2 q01 qN"cmpne_mulmul_imm_pos",gP3 o82
#define YZ2 oL1 Cmpne_pow_imm_negneg,q2 Cmpne_pow_imm_negneg,oA1 hS dI3 gZ3
#define Sa2 oL1 Cmpne_pow_imm_negpos,q2 Cmpne_pow_imm_negpos,oA1 hT dI3 h13
#define Ta2 wO1 Cmpne_pow_imm_posneg,q2 Cmpne_pow_imm_posneg,oA1 d0 dI3 d53
#define Ua2 wO1 Cmpne_pow_imm_pospos,q2 Cmpne_pow_imm_pospos,oA1 d3 dI3 hG3
#define Wa2 wO1 Cmpne_pow_imm_pospos_base,q2 Cmpne_pow_imm_pospos_base,oA1 h33"!= "wK
#define Ya2 oG Cmpne_powpow_imm_base,q2 Cmpne_powpow_imm_base,0 qN"cmpne_"hC dI3 a3
#define Sb2 oG w61,q2 w61,q2 w61 qN"cmpzz_add_imm"dC" "h61 qM2 aC" "h61 qN2" "h61 hG2" "h61 qO2 h61 a01 dD h61 hE2
#define Tb2 wO1 gZ1 q2 gZ1 q2 gZ1 oK1"cmpzz_add_reduce"dC" "d73"< "h1 aC" "d73"<= "h1 aE" "d73"> "h1 oV" "d73">= "h1 aD d73"!= "h1 dD d73"="dQ3
#define Ub2 oG hK1,q2 hK1,q2 hK1 qN"cmpzz_addadd_imm"dC" "o7 hH2 aC" "o7 hI2" "o7 hJ2" "o7 wB1 o7 wC1 o7 w72
#define Wb2 {hN a21,q2 a21,q2 a21 qN"cmpzz_minmax"dC hD3"< "hH3 aC hD3"<= "hH3 aE hD3"> "hH3 oV hD3">= "hH3 g1"0010 *"hD3"!= "hH3" +  0x0020 *"hD3"= "hF3
#define Yb2 {hN hM1,q2 hM1,q2 hM1 qN"cmpzz_minmax_rev"dC hD3"< "hI3 aC hD3"<= "hI3 aE hD3"> "hI3 oV hD3">= "hI3 g1"0010 *"hD3"!= "hI3" +  0x0020 *"hD3"= "h93
#define Sc2 oG h01,q2 h01,q2 h01 qN"cmpzz_mul_imm_neg"dC gP2 qM2 aC gP2 qN2 gP2 hG2 gP2 qO2 dT1 a01 dD dT1 hE2
#define Tc2 oG h11,q2 h11,q2 h11 qN"cmpzz_mul_imm_pos"dC oN1 qM2 aC oN1 qN2 oN1 hG2 oN1 qO2 wV1 a01 dD wV1 hE2
#define Uc2 oG q11,q2 q11,q2 q11 qN"cmpzz_mulmul_imm_neg"dC h71 hH2 aC h71 hI2 h71 hJ2 h71 wB1 mM2 wC1 mM2 w72
#define Wc2 oG q21,q2 q21,q2 q21 qN"cmpzz_mulmul_imm_pos"dC" "gP3 hH2 aC" "gP3 hI2" "gP3 hJ2" "gP3 wB1 gP3 wC1 gP3 w72
#define Yc2 oL1 Cmpzz_pow_imm_negneg,q2 Cmpzz_pow_imm_negneg,hO1"_imm_negneg"dC oU1 dH3 h43 aC oU1 dN3 h43 aE oU1" > "h43 oV oU1 dO3 h43 aD gO",-3)"dI3 h43 dD gO",-3) = "gZ3
#define Sd2 oL1 Cmpzz_pow_imm_negpos,q2 Cmpzz_pow_imm_negpos,hO1"_imm_negpos"dC oV1 dH3 hC3 aC oV1 dN3 hC3 aE oV1" > "hC3 oV oV1 dO3 hC3 aD gO",-2)"dI3 hC3 dD gO",-2) = "h13
#define Td2 wO1 Cmpzz_pow_imm_posneg,q2 Cmpzz_pow_imm_posneg,hO1"_imm_posneg"dC dA3"< "hW3 aC dA3"<= "hW3 aE dA3"> "hW3 oV dA3">= "hW3 aD gO",3)"dI3 hW3 dD gO",3) = "d53
#define Ud2 wO1 Cmpzz_pow_imm_pospos,q2 Cmpzz_pow_imm_pospos,hO1"_imm_pospos"dC q02 dH3"25)"aC q02" <= 25)"aE q02" > 25)"oV q02" >= 25)"aD gO",2)"dI3"25)"dD gO",2) = "hG3
#define Wd2 wO1 Cmpzz_pow_imm_pospos_base,q2 Cmpzz_pow_imm_pospos_base,hO1"_imm_pospos_base"dC" "h63"<"dR3 aC" "h63"<="dR3 aE" "h63">"dR3 oV" "h63">="dR3 aD h63"!="dR3 dD h63"= "wK
#define Yd2 oG Cmpzz_powpow_imm_base,q2 Cmpzz_powpow_imm_base,0 qN"cmpzz_powpow_imm_base"dC" "qQ1 dH3 g71 aC" "qQ1 dN3 g71 aE" "qQ1" > "g71 oV" "qQ1 dO3 g71 aD qQ1 dI3 g71 dD qQ1" = "a3
#define Se2 {1 qP1 Eq0,q2 Eq0,q2 Eq0,oK1"eq0","(x=if("qT1" (if(1,0,0)="oS2
#define Te2 {1 qP1 Eq1,q2 Eq1,q2 Eq1,oK1"eq1","(!x=if"gM3},
#define Ue2 {2,dS Expexp_a,q2 Expexp_a,0 qN q43"p_a","exp(x*2 + y*3"o02
#define We2 {3,dS Expexp_b,q2 Expexp_b mC q43"p_b",aR" * exp(y+z"o02
#define Ye2 {3,dS Expexp_c,q2 Expexp_c mC q43"p_c","exp(x + y*z"o02
#define Sf2 {1 aJ aD2 q2 aD2 q2 aD2 oK1"ge0_abs"aM1 dO3 h83"  2"hP1 dN3 hB3"<= "h83"8"hP1 dO3 hS3
#define Tf2 {1 aJ aE2 q2 aE2 q2 aE2 oK1"ge1_abs"aM1" >= if"gM3 q22 dI1 dN3 hB3"<= if"hQ1 dB3" 8"dI1 dO3 hS3
#define Uf2 {hN hK2,q2 hK2,q2 hK2 qN"ge_and_eq",mW2 oS1
#define Wf2 {hN hL2,q2 hL2,q2 hL2 qN"ge_and_le",mW2 hN1},
#define Yf2 {hN hM2,q2 hM2,q2 hM2 qN"ge_and_ne",mW2 dJ1
#define Sg2 {hN w82,q2 w82,q2 w82 qN"ge_or_eq",mX2 oS1
#define Tg2 {hN w92,q2 w92,q2 w92 qN"ge_or_le",mX2 hN1},
#define Ug2 {hN wA2,q2 wA2,q2 wA2 qN"ge_or_ne",mX2 dJ1
#define Wg2 {1,N(-1.0,0.0),N(1.0,0.0)oZ1 qM,q2 Gehalf,q2 Gehalf,gD"gehalf","x>=if(1,0.5,0"o02
#define Yg2 {1 aJ aF2 q2 aF2 q2 aF2 oK1"gt0_abs"aM1" > "h83"  2"hP1 dH3 hB3"< "h83"8"hP1" > "hS3
#define Sh2 {1 aJ aG2 q2 aG2 q2 aG2 oK1"gt1_abs"aM1" > if"gM3 q22 dI1 dH3 hB3"< if"hQ1 dB3" 8"dI1" > "hS3
#define Th2 {hN hN2,q2 hN2,q2 hN2 qN"gt_and_eq"gQ2 oS1
#define Uh2 {hN hO2,q2 hO2,q2 hO2 qN"gt_and_ge"gQ2 m7},
#define Wh2 {hN hP2,q2 hP2,q2 hP2 qN"gt_and_le"gQ2 hN1},
#define Yh2 {hN hQ2,q2 hQ2,q2 hQ2 qN"gt_and_ne"gQ2 dJ1
#define Si2 {hN wB2,q2 wB2,q2 wB2 qN"gt_or_eq"gA3 oS1
#define Ti2 {hN wC2,q2 wC2,q2 wC2 qN"gt_or_ge"gA3 m7},
#define Ui2 {hN wD2,q2 wD2,q2 wD2 qN"gt_or_le"gA3 hN1},
#define Wi2 {hN wE2,q2 wE2,q2 wE2 qN"gt_or_ne"gA3 dJ1
#define Yi2 {1 qP1 If10,q2 If10,q2 If10,oK1"if10",o6",1,0) + 10*"o6",0,1)    + 100*"o6">0,1,0) + 1000*"o6">0,0,1"o02
#define Sj2 {2,gE dV1,q2 dV1,q2 dV1 qN1"tract_abs",o6", abs(x+2), abs(y+5))"},
#define Tj2 {2,gE dW1,q2 dW1,q2 dW1 qN1"tract_add"hB2"+2, y+"gX2
#define Uj2 {2,gE d71,q2 d71,q2 d71 qN1"tract_add1"hB2"+2, y"o02
#define Wj2 {2,gE d81,q2 d81,q2 d81 qN1"tract_add2",o6", y, y+2"o02
#define Yj2 {oC qJ1 q2 qJ1 q2 qJ1"x"dU"tract_and1_l"hB2"&z, y<1"o02
#define Sk2 {oC q71 q2 q71 q2 q71"x"dU"tract_and1_nl"hB2"&z, z"o02
#define Tk2 {oC qK1 q2 qK1 q2 qK1"x"dU"tract_and2_l",o6", y<1, y&z"o02
#define Uk2 {oC q81 q2 q81 q2 q81"x"dU"tract_and2_nl",o6", z, y&z"o02
#define Wk2 {2,gE dX1,q2 dX1,q2 dX1 qN1"tract_min",o6", min(y,2), min(y,5))"},
#define Yk2 {2,gE dY1,q2 dY1,q2 dY1 qN1"tract_mul"hB2"*2, y*"gX2
#define Sl2 {2,gE d91,q2 d91,q2 d91 qN1"tract_mul1"hB2"*2, y"o02
#define Tl2 {2,gE dA1,q2 dA1,q2 dA1 qN1"tract_mul2",o6", y, y*2"o02
#define Ul2 {oC h21 q2 h21 q2 h21"x"dU"tract_or1_l",o6", y|z, y<1"o02
#define Wl2 {oC qL1 q2 qL1 q2 qL1"x"dU"tract_or1_nl",o6", y|z, z"o02
#define Yl2 {oC h31 q2 h31 q2 h31"x"dU"tract_or2_l",o6", y<1, y|z"o02
#define Sm2 {oC qO1 q2 qO1 q2 qO1"x"dU"tract_or2_nl",o6", z, y|z"o02
#define Tm2 {2,N(-4.0,0.0),N(4.0,0.0)gE1 q2 If_extract_sin,q2 If_extract_sin,0 qN1"tract_sin",o6", sin(y), "hA3
#define Um2 {2,gZ If_join_add,q2 If_join_add,0 qN"if_join_add"o92"+"aB1
#define Wm2 {1,g73 N(5.0,0.0),gL2 w71 q2 w71 q2 w71 oK1"if_join_add2","x + 10 +"hL1"<4, 3,4"o02
#define Ym2 {2,gZ If_join_and,q2 If_join_and,0 qN"if_join_and"o92"&"aB1
#define Sn2 {2,gZ If_join_max,q2 If_join_max,0 qN"if_join_max","max("o6 dA","hX3")))"},
#define Tn2 {2,gZ If_join_min,q2 If_join_min,0 qN"if_join_min","min("o6 dA","hX3")))"},
#define Un2 {2,gZ If_join_mul,q2 If_join_mul,0 qN"if_join_mul"o92"*"aB1
#define Wn2 {1,g73 N(5.0,0.0),gL2 w81 q2 w81 q2 w81 oK1"if_join_mul2","x * 10 *"hL1"<4, 3,4"o02
#define Yn2 {2,gZ If_join_or,q2 If_join_or,0 qN"if_join_or",o6 dA" |"hX3"))"},
#define So2 {1 aJ Ifabs,q2 Ifabs,q2 Ifabs,oK1"ifabs","1"dD1"< 0,-x,"h53"   10"dD1"<=0,-x,"h53"  100"dD1"> 0,-x,"h53" 1000"dD1">=0,-x,"h53"10000"dD1"< 0,x"dE3"     100000"dD1"<=0,x"dE3"    1000000"dD1"> 0,x"dE3"10000000"dD1">=0,x,-"mR2
#define To2 {3,h9 Ifabsnot,q2 Ifabsnot mC"ifabsnot","if(!(sin(x)+1.2), y,z"o02
#define Uo2 {3,h9 Ifconst,q2 Ifconst mC"ifconst","if(1, x,y) + if(0,z,y"o02
#define Wo2 {4 qP1 Ififconst,q2 Ififconst,0,"w,"mG"ififconst","if("o6",1,y),z,w) + if(if(w,z,0),"w02
#define Yo2 {4 aJ wF2 q2 wF2 q2 wF2"b,d,"w12"ifmerge"dJ2"y,x,b"mZ2"y,x,d)) +  if(b,if(d,y,x),if(d,b,"mR2
#define Sp2 {4 aJ hR2 q2 hR2 q2 hR2"a,b,"w12"ifmerge2"dJ2"y,a,b"mZ2"b,a,b))"},
#define Tp2 {4 aJ qP2 q2 qP2 q2 qP2"a,b,"w12"ifmerge2b"dJ2"y,a,b"mZ2"b,b,a))"},
#define Up2 {hN Ifnop,q2 Ifnop,q2 Ifnop qN"ifnop",o6",y,y"o02
#define Wp2 {3 qP1 Ifnot,q2 Ifnot mC"ifnot","if(!x, y,z"o02
#define Yp2 hO L_abs,q2 L_abs,q2 L_abs qN"l_abs","(x+2) & "d63 mQ1
#define Sq2 hO wG2,q2 wG2,q2 wG2 qN"l_mulabs","(x*abs(y))"mQ1
#define Tq2 hO wH2,q2 wH2,q2 wH2 qN"l_mulneg","(x*y*-5)"mQ1
#define Uq2 hO wI2,q2 wI2,q2 wI2 qN"l_notnot","(x+2) & !!x"mQ1
#define Wq2 {hN hS2,q2 hS2,q2 hS2 qN"le_and_eq",hN1" & "oS1
#define Yq2 {hN hT2,q2 hT2,q2 hT2 qN"le_and_ne",hN1" & "dJ1
#define Sr2 {hN wJ2,q2 wJ2,q2 wJ2 qN"le_or_eq",hN1" | "oS1
#define Tr2 {hN wK2,q2 wK2,q2 wK2 qN"le_or_ne",hN1" | "dJ1
#define Ur2 {hN hU2,q2 hU2,q2 hU2 qN"lt_and_eq"hV2 oS1
#define Wr2 {hN hW2,q2 hW2,q2 hW2 qN"lt_and_ge"hV2 m7},
#define Yr2 {hN hX2,q2 hX2,q2 hX2 qN"lt_and_gt"hV2"(x > y"o02
#define Ss2 {hN hY2,q2 hY2,q2 hY2 qN"lt_and_le"hV2 hN1},
#define Ts2 {hN hZ2,q2 hZ2,q2 hZ2 qN"lt_and_ne"hV2 dJ1
#define Us2 {hN wL2,q2 wL2,q2 wL2 qN"lt_or_eq"gK3 oS1
#define Ws2 {hN wM2,q2 wM2,q2 wM2 qN"lt_or_ge"gK3 m7},
#define Ys2 {hN wN2,q2 wN2,q2 wN2 qN"lt_or_gt"mD" | (x > y"o02
#define St2 {hN wO2,q2 wO2,q2 wO2 qN"lt_or_le"gK3 hN1},
#define Tt2 {hN wP2,q2 wP2,q2 wP2 qN"lt_or_ne"gK3 dJ1
#define Ut2 {1,N(-1.0,0.0),N(1.0,0.0)oZ1 qM,q2 Lthalf,q2 Lthalf,gD"lthalf","x<if(1,0.5,0"o02
#define Wt2 {oC a41 q2 a41 q2 a41 mG"mergemulabs","abs(x)*abs(y)*z"},
#define Yt2 {3,N(0.0,0.0),mR1 N(1.0,0.0)qM,oT1 oT1 oT1 mG"mixedminmax","max(z,min(x,max(max(z,y),x)))"h03"10*min(z,max(x,min(y,x)))"h03"100*min(max(x,y),min(y,z)) +  1000*max(min(x,y),max(y,z))"},
#define Su2 {2,h9 Muland2,q2 Muland2,0 qN"muland2",hY3},
#define Tu2 {3,h9 Muland2plus,q2 Muland2plus mC"muland2plus",hY3" * z"},
#define Uu2 {3,h9 Muland3,q2 Muland3 mC"muland3",hY3" * !!z"},
#define Wu2 {2,h9 Mulandlt,q2 Mulandlt,0 qN"mulandlt",wS2" (y<0"o02
#define Yu2 {2 oZ1,N(1.0,0.0)oZ1 qM,q2 Mulimmlog,q2 Mulimmlog,0 qN"mulimmlog","log(if(1,5,0)*x*y"o02
#define Sv2 {2,h9 Mulnor2,q2 Mulnor2,0 qN"mulnor2",hZ3},
#define Tv2 {3,h9 Mulnor2plus,q2 Mulnor2plus mC"mulnor2plus",hZ3" * z"},
#define Uv2 {3,h9 Mulnor3,q2 Mulnor3 mC"mulnor3",hZ3" * !z"},
#define Wv2 {hN Nand2,q2 Nand2,q2 Nand2 qN"nand2",hU3},
#define Yv2 {3 qP1 qQ2 q2 qQ2 q2 qQ2 mG"nand2plus",hU3" | z"},
#define Sw2 {3 qP1 Nand3,q2 Nand3,q2 Nand3,mG"nand3",hU3" | !z"},
#define Tw2 {1 aJ Negceil,q2 Negceil,gD"negceil","ceil(x*(abs(x)-abs(x)-1))"},
#define Uw2 {1 aJ Negcos,q2 Negcos,gD"negcos","cos"wU2
#define Ww2 {1 aJ Negcosh,q2 Negcosh,gD"negcosh","cosh"wU2
#define Yw2 {1 aJ Negfloor,q2 Negfloor,gD"negfloor","floor(x*(abs(x)-abs(x)-1))"},
#define Sx2 {1 aJ Negsin,q2 Negsin,gD"negsin","sin(x*"qD1
#define Tx2 {1 aJ Negsinh,q2 Negsinh,gD"neg"oA2,oA2 wU2
#define Ux2 {1 qP1 Neq0,q2 Neq0,q2 Neq0,oK1"neq0","(x!=if("qT1" (if(1,0,0)!="oS2
#define Wx2 {1 qP1 Neq1,q2 Neq1,q2 Neq1,oK1"neq1","(!x!=if"gM3},
#define Yx2 {hN Nor2,q2 Nor2,q2 Nor2 qN"nor2",hV3},
#define Sy2 {3 qP1 d02 q2 d02 q2 d02 mG"nor2plus",hV3" & z"},
#define Ty2 {3 qP1 Nor3,q2 Nor3,q2 Nor3,mG"nor3",hV3" & !z"},
#define Uy2 {hN Not_eq,q2 Not_eq,q2 Not_eq qN"not_eq",o6" = "h23
#define Wy2 {hN Not_ge,q2 Not_ge,q2 Not_ge qN"not_ge",o6 dO3 h23
#define Yy2 {hN Not_gt,q2 Not_gt,q2 Not_gt qN"not_gt",o6" > "h23
#define Sz2 {hN Not_le,q2 Not_le,q2 Not_le qN"not_le",o6 dN3 h23
#define Tz2 {hN Not_lt,q2 Not_lt,q2 Not_lt qN"not_lt",o6 dH3 h23
#define Uz2 {hN Not_ne,q2 Not_ne,q2 Not_ne qN"not_ne",o6 dI3 h23
#define Wz2 {2,gE Notnot,q2 Notnot,q2 Notnot qN"notnot","!!x + if(y, 1,0"o02
#define Yz2 {1,h9 Posnot,q2 Posnot,gD"posnot","!(sin(x) + 1.2"o02
#define S_2 {1,h9 Posnotnot,q2 Posnotnot,gD"posnotnot","!!(sin(x) + 1.2"o02
#define T_2 {1 oZ1,N(1.0,0.0)oZ1 qM,q2 Powimmaddimmlog,q2 Powimmaddimmlog mJ1"immaddimmlog","pow(5, log(x)+1"o02
#define U_2 {1 oZ1,qE2 oZ1 qM,q2 Powimmlog,q2 Powimmlog mJ1"immlog","pow(3, log(x)) + pow(5, log(x)*sin(x))"},
#define W_2 {hM Powmulimm_fnen,q2 Powmulimm_fnen dW dE1"mulimm_fnen",o01"^(-8"o02
#define Y_2 {2,dT Powmulimm_fnep,q2 Powmulimm_fnep dW dE1"mulimm_fnep",o01"^(4"o02
#define S03 {1,N(-3.0,0.0),N(-1.0,0.0)gE1 q2 Powmulimm_fnfn,q2 Powmulimm_fnfn mJ1"mulimm_fnfn","((-5.1)*x)^(-7.1"o02
#define T03 {2,dT Powmulimm_fnfp,q2 Powmulimm_fnfp dW dE1"mulimm_fnfp",o01"^7.1"},
#define U03 {2,dT Powmulimm_fpfp,q2 Powmulimm_fpfp dW dE1"mulimm_fpfp","(5.1*x*y)^7.1"},
#define W03 {1,h9 Sub1cos2,q2 Sub1cos2,gD"sub1cos2","1-cos(x)^2"},
#define Y03 {1,h9 Sub1sin2,q2 Sub1sin2,gD"sub1sin2","1-"q42"^2"},
#define S13 {1,N(-9.42477796076937971538793014983850865259,0.0),N(9.42477796076937971538793014983850865259,0.0),N(0.785398163397448309615660845819875721049292349,0.0)qM,q2 Trig_modulo,q2 Trig_modulo,gD"trig_modulo","cos(x+pi"qE1"2/3"qE1"5/2"qE1"6/2"qE1 dK3"  "o11")"wI1"2/3)"wI1"5/2)"wI1"6/2)"wI1 dK3"  cos(x-pi) +"dF1"2/3) +"dF1"5/2) +"dF1"6/2) +"dF1 dK3 o21")"q63"2/3)"q63"5/2)"q63"6/2)"q63"7/2"o02
#define T13 {1,N(-3.0,0.0),N(3.0,0.0)oZ1 qM,q2 Trunc_from_if,q2 Trunc_from_if,gD"trunc_from_if",o6">0,  "hL3 d32">=0, "hL3 d32"<0,  "hJ3 d32"<=0, "hJ3 qS2">0,  "hJ3 qS2">=0, "hJ3 qS2"<0,  "hL3" 10*"o6"<=0, floor(x),ceil"g51
#define U13 {1,N(-5.0,0.0),N(5.0,0.0),N(1.0,0.0)qM gJ2 gJ2 gJ2,"x"q6"/xaddnot","!(x+if(1,4,4))"},
#define W13 {1,N(-5.0,0.0),N(5.0,0.0),gL2 mH1 q2 mH1 q2 mH1"x"q6"/xaddnotnot","!!(x+if(1,4,4))"},
#define N(x) (x)
#define P(x) N(x##.0)
namespace
cpp_01unit_operators{using
namespace
FUNCTIONPARSERTYPES;q3
Add_cd
aJ2
Add_d
aJ2
Add_i
aJ2
Addsub_cd
qU1
Addsub_d
qU1
Addsub_i
qU1
And_d
qL
oJ1>=gD2)?fp_abs(y)>=gD2):aK2
And_i
qL
x!=gM2?y!=gM2:gF2
Cmpeq_cd
qL
x==mB1
Cmpeq_d
qL
x==mB1
Cmpeq_i
qL
x==mB1
Cmpge_d
qL
x>=mB1
Cmpge_i
qL
x>=mB1
Cmpgt_d
qL
x>mB1
Cmpgt_i
qL
x>mB1
Cmple_d
qL
x<=mB1
Cmple_i
qL
x<=mB1
Cmplt_d
qL
x<mB1
Cmplt_i
qL
x<mB1
Cmpne_cd
qL
x!=mB1
Cmpne_d
qL
x!=mB1
Cmpne_i
qL
x!=mB1
Div_d
qL(x-q0(0.25l))/mB1
Div_i
qL
x/(y+q0(3l
qP
Divmul_d
hJ
x*y*x*x/z*(x-q0(0.25l
qP
Divmul_i
hJ
x*y*x*x/(z+dI2*(x+dL1
Inv_d
qW
g42
x;}
q3
Inv_i
qW
g42
x;}
q3
Mod(qD,&z
oR2
qA
fmod(x,z);}
q3
Mod_i(qD,&z
oR2
qA
x%(z+q0(3l
qP
Mul_cd
qL
x*mB1
Mul_d
qL
x*mB1
Mul_i
qL
x*(y+dL1
Neg_cd
qW-x;}
q3
Neg_d
qW-x;}
q3
Neg_i
qW-x;}
q3
Not_d
qW
oJ1<gD2
qP
Not_i
qW
q0(x==aK2
Notnot_d
qW
oJ1>=gD2
qP
Notnot_i
qW
q0(x!=aK2
Or_d
qL
oJ1<gD2)?fp_abs(y)>=gD2):q0(1l
qP
Or_i
qL
x==gM2?y!=gM2:q0(1l);}
q3
Sub_cd
qL
x-mB1
Sub_d
qL
x-mB1
Sub_i
qL
x-y;}
}
namespace
cpp_02unit_functions{using
namespace
FUNCTIONPARSERTYPES;q3
Abs_cd
qW
std::abs(wA
Abs_d
qW
x<gM2?-x:x;}
q3
Abs_i
qW
x<gM2?-x:x;}
q3
Acos
qW
acos(wA
Acos_deg
wF1
acos(x
qP
Acosh
qW
g91-1.0
qP
Acosh_deg
wF1
g91-1.0)qP
Arg
qW
hP
wA
Asin
qW
asin(wA
Asin_deg
wF1
asin(x
qP
Asinh
qW
g91+1.0
qP
Asinh_deg
wF1
g91+1.0)qP
Atan
qW
atan(wA
Atan2
qL
atan2(x
aN2
Atan2_deg
qL
r2d(atan2(x,y
qP
Atan_deg
wF1
atan(x
qP
Atanh
qW
log((1.0+x)/(1.0-x))*0.5;}
q3
Cbrt
qW
x<0.0?-exp(log(-x)/3.0):(x>0.0?exp(log(x)/3.0):0.0);}
q3
Ceil
qW
ceil(wA
Conj
qW
fp_conj(wA
Cos
qW
cos(wA
Cos_deg
qW
cos(aQ1
Cosh
qW
cosh(wA
Cosh_deg
qW
cosh(aQ1
Exp
qW
exp(wA
Exp2
qW
exp(x*fp_const_log2<q0>(qP
Floor
qW
floor(wA
Hypot
qL
sqrt(x*x+y*y);}
q3
If_d
hJ
fp_abs(x)>=gD2)?y:z;}
q3
If_i
hJ(x!=gM2)?y:z;}
q3
Imag
qW
fp_imag(wA
Int
qW
fp_floor(x+gD2
qP
Log
qW
log(wA
Log2
qW
log(x)*1.4426950408889634073599246810018921374266;}
q3
Log10
qW
log(x)*0.43429448190325182765112891891660508229;}
q3
Log_cd
qW
std::log(wA
Max
qL
x>y?x:mB1
Min
qL
x<y?x:mB1
Polar
qL
fp_polar(x
aN2
Pow_neg
qL
pow(-x*0.25
aN2
Pow_pos
qL
pow(x
aN2
Real
qW
fp_real(wA
Sin
qW
sin(wA
Sin_deg
qW
sin(aQ1
Sinh
qW
sinh(wA
Sinh_deg
qW
sinh(aQ1
Sqrt
qW
sqrt(wA
Sqrt_cd
qW
std::sqrt(wA
Tan
qW
tan(wA
Tan_deg
qW
tan(aQ1
Tanh
qW
tanh(wA
Tanh_deg
qW
tanh(aQ1
Trunc
qW
x<0.0?ceil(x):floor(x
g43
cpp_03unit_constants{using
namespace
FUNCTIONPARSERTYPES;q3
E_d
qW
exp(x*0.0+1.0);}
q3
L2_d
qW
log(x*0.0+2.0);}
q3
L10_d
qW
log(x*0.0+10.0);}
q3
Pi_d
qW
atan2(x*0.0,-1.0
g43
cpp_10optimizer_bytecode{using
namespace
FUNCTIONPARSERTYPES;q3
Abs
qW(q0(3l)hY1
Abscos
qW
gH3
d51
Abscosh
qW
aO2
d51
Abseq0
qW
fp_equal(w0
0l
mC1
d51
Absevenconstpow
qW
fp_pow(w0
1506l
qP
Absmulevenconstpow
qL
fp_pow(fp_abs(x)*y,q0(1506l
qP
q83
qW
fp_equal(w0
0l
mC1
d51
Absneverneg
qW
fp_acos(wA
Absnot
g62
d51
Absnot2
g62
gB1
qP
Absnot3
qL
fp_not(fp_not(fp_and(x,y)qP
Absnot4
g62
fp_not(gB1)qP
wQ1
g62
fp_notNot((x*x)qP
mP2(qD;q0
b0[2]qA
userDefFuncSub<q0>((b0[0]=(fp_greaterOrEq(fp_abs(x),dM),b0[1]=(fp_greaterOrEq(w0
0l))),b0
qP
mQ2(qD;q0
b1[2]qA
userDefFuncSub<q0>((b1[0]=(fp_less(fp_abs(x),dM),b1[1]=(fp_less(w0
0l))),b1
qP
Abssqr
qW
x*x;}
q3
Absyxpow_neg
qW
fp_pow(qO-4.0),1.5);}
q3
Absyxpow_pos
qW
fp_pow(qO
4.0),1.5);}
q3
Acos
qW
acos(0.7
hY1
Acos_deg
wF1
acos(0.7)hY1
Acosh
qW
m9
1.1-1.0)hY1
Acosh_deg
wF1
m9
1.1-1.0))hY1
Acoshcosh
qW
aO2
fp_acosh(x
qP
Acoshsinh
qW
fp_sinh(fp_acosh(x
qP
Add
qW
q0(5l
gC1
3l
hY1
Add0
qW
x+q0(0l
hY1
Addexp
qW
gO3+dL1
Addexp2
qW
fp_exp2(x+dL1
And
qW
fp_and(q0(hS1+fp_and(d01,gM2)+fp_and(gM2,d01)+fp_and(gM2,aK2
Asin
qW
asin(0.7
hY1
Asin_deg
wF1
asin(0.7)hY1
Asinh
qW
m9
1.1+1.0)hY1
Asinh_deg
wF1
m9
1.1+1.0))hY1
Asinhcosh
qW
aO2
fp_asinh(x
qP
Asinhsinh
qW
fp_sinh(fp_asinh(x
qP
Atan
qW
atan(1.1
hY1
Atan2
qW
atan2(5.0,4.0
hY1
Atan2_deg
wF1
atan2(5.0,4.0)hY1
Atan2tan
qL
dD2
q82
x,y
qP
Atan_deg
wF1
atan(1.1)hY1
Atanh
qW
log((1.0+0.7)/(1.0-0.7))*0.5+x;}
q3
Cbrt
qW
exp(qX3)/3.0
hY1
Ceil
qW
ceil(1.1
hY1
Ceilneg
qW
fp_ceil(-wA
Cmp_acos(qT
hH))qU
hH))qQ
hH))qR
hH))qS
hH
qF
hH
qP
Cmp_acos_outrange(qT
gA1
qU
gA1
qQ
gA1
qR
gA1
qS
oP
2l
qF
oP
2l
qP
q93(qT(gN3
qU(gN3
qQ(gN3
qR(gN3
qS(q0(dK
qF(q0(dK
qP
Cmp_asin(qT
hK))qU
hK))qQ
hK))qR
hK))qS
hK
qF
hK
qP
Cmp_asin_outrange(qT
aP2
qU
aP2
qQ
aP2
qR
aP2
qS
qV1
q0(2l
qF
qV1
q0(2l
qP
Cmp_atan(qT
dL))qU
dL))qQ
dL))qR
dL))qS
dL
qF
dL
qP
Cmp_exp(qT
oD))qU
oD))qQ
oD))qR
oD))qS
oD
qF
oD
qP
Cmp_exp2(qT
dN))qU
dN))qQ
dN))qR
dN))qS
dN
qF
dN
qP
Cmp_exp2_neg(qT
mH
dM
qU
mH
dM
qQ
mH
dM
qR
mH
dM
qS
mH
dK1
mH
dL1
Cmp_exp_neg(qT
qW1
dM
qU
qW1
dM
qQ
qW1
dM
qR
qW1
dM
qS
qW1
dK1
qW1
dL1
Cmp_log2_nn(qT
h8
hR1
qU
h8
hR1
qQ
h8
hR1
qR
h8
hR1
qS
h8
oB1
qF
h8
oB1
qP
Cmp_log2_np(qT
h8
aR1))qU
h8
aR1))qQ
h8
aR1))qR
h8
aR1))qS
h8
aR1
qF
h8
aR1
qP
Cmp_log2_pn(qT
h8
aS1
qU
h8
aS1
qQ
h8
aS1
qR
h8
aS1
qS
h8
aT1
qF
h8
aT1
qP
Cmp_log2_pp(qT
h8
aU1
qU
h8
aU1
qQ
h8
aU1
qR
h8
aU1
qS
h8
gB
h8
gL
qF
h8
gB
h8
gL
qP
Cmp_log10_nn(qT
gU
hR1
qU
gU
hR1
qQ
gU
hR1
qR
gU
hR1
qS
gU
oB1
qF
gU
oB1
qP
Cmp_log10_np(qT
gU
aV1))qU
gU
aV1))qQ
gU
aV1))qR
gU
aV1))qS
gU
aV1
qF
gU
aV1
qP
Cmp_log10_pn(qT
gU
aS1
qU
gU
aS1
qQ
gU
aS1
qR
gU
aS1
qS
gU
aT1
qF
gU
aT1
qP
Cmp_log10_pp(qT
gU
gB
gU
gZ2
qU
gU
gB
gU
gZ2
qQ
gU
gB
gU
gZ2
qR
gU
gB
gU
gZ2
qS
gU
gB
gU
q0(1l)qF
gU
gB
gU
q0(1l)qP
Cmp_log_nn(qT
hP
hR1
qU
hP
hR1
qQ
hP
hR1
qR
hP
hR1
qS
hP
oB1
qF
hP
oB1
qP
Cmp_log_np(qT
hP
aW1
qU
hP
aW1
qQ
hP
aW1
qR
hP
aW1
qS
hP
x),hP
gL
qF
hP
x),hP
gL
qP
Cmp_log_pn(qT
hP
aS1
qU
hP
aS1
qQ
hP
aS1
qR
hP
aS1
qS
hP
aT1
qF
hP
aT1
qP
Cmp_log_pp(qT
hP
gB
hP
gL))qU
hP
gB
hP
gL))qQ
hP
gB
hP
gL))qR
hP
gB
hP
gL))qS
hP
gB
hP
gL
qF
hP
gB
hP
gL
qP
qV2(qT(x
a6
dM
qU(x
a6
dM
qQ(x
a6
dM
qR(x
a6
dM
qS(x
a6
dK1(x
a6
dL1
qY2(qT(x
a7
dM
qU(x
a7
dM
qQ(x
a7
dM
qR(x
a7
dM
qS(x
a7
dK1(x
a7
dL1
qC3(qT(-x),dM
qU(-x),dM
qQ(-x),dM
qR(-x),dM
qS(-x),dK1(-x),dL1
Cmp_powx_n_n(qT
oE))qU
oE))qQ
oE))qR
oE))qS
oE
qF
oE
qP
Cmp_powx_n_p(qT
aX1
qU
aX1
qQ
aX1
qR
aX1
qS
oB2
hI
qF
oB2
hI
qP
Cmp_powx_nn(qT
oB2),-dM
qU
oB2),-dM
qQ
oB2),-dM
qR
oB2),-dM
qS
oB2),-dK1
oB2),-dL1
Cmp_powx_np(qT
oB2),dM
qU
oB2),dM
qQ
oB2),dM
qR
oB2),dM
qS
oB2),dK1
oB2),dL1
Cmp_powx_p_n
o22
dO))qU
oC2
qQ
oC2
qR
oC2
h02
dO
qF
qI
gC
dO
qP
Cmp_powx_p_p
o22
oC1))qU
qI
gC
oC1))qQ
qI
gC
oC1))qR
qI
gC
oC1))h02
oC1
qF
qI
gC
oC1
qP
Cmp_powx_pn
o22),-dM
qU
qI
gC),-dM
qQ
qI
gC),-dM
qR
qI
gC),-dM
h02),-dK1
qI
gC),-dL1
Cmp_powx_pp
o22),dM
qU
qI
gC),dM
qQ
qI
gC),dM
qR
qI
gC),dM
h02),dK1
qI
gC),dL1
Cmp_powy_n_n
o62-hU))qU
gT3
qQ
gT3
qR
gT3
qS
qO-hU
qF
qO-hU
qP
Cmp_powy_n_p
o62-hV))qU
qO-hV))qQ
qO-hV))qR
qO-hV))qS
qO-hV
qF
qO-hV
qP
Cmp_powy_nn
o62-gG-oD2-gG-oI2-gG-oJ2-gG-oK2-gG-dK1
qO-gG-dL1
Cmp_powy_np
o62-gG
oD2-gG
oI2-gG
oJ2-gG
oK2-gG
dK1
qO-gG
dL1
Cmp_powy_p_n
o62
hU))qU
qO
hU))qQ
qO
hU))qR
qO
hU))qS
qO
hU
qF
qO
hU
qP
Cmp_powy_p_p
o62
hV))qU
qO
hV))qQ
qO
hV))qR
qO
hV))qS
qO
hV
qF
qO
hV
qP
Cmp_powy_pn
o62
gG-oD2
gG-oI2
gG-oJ2
gG-oK2
gG-dK1
qO
gG-dL1
Cmp_powy_pp
o62
gG
oD2
gG
oI2
gG
oJ2
gG
oK2
gG
dK1
qO
gG
dL1
Cmp_sinh(qT
dQ))qU
dQ))qQ
dQ))qR
dQ))qS
dQ
qF
dQ
qP
qD3(qT(qX1))qU(qX1))qQ(qX1))qR(qX1))qS(qX1
qF(qX1
qP
mN1(qT(qY1))qU(qY1))qQ(qY1))qR(qY1))+-q0(16l)*fp_greaterOrEq((qY1
qF(qY1
qP
Cmp_tanh(qT
hL))qU
hL))qQ
hL))qR
hL))qS
hL
qF
hL
qP
Cmp_tanh_outrange(qT
aQ2
qU
aQ2
qQ
aQ2
qR
aQ2
qS
qZ1
q0(2l
qF
qZ1
q0(2l
qP
Cmpeq
qW
fp_equal(q0(hS1+fp_equal(h22,dL1
Cmpge
qW
qH1
3l),d01)+x+qH1
8l),dL1
Cmpgt
qW
mS1
3l),d01)+x+mS1
8l),dL1
Cmple
qW
qH1
hS1+qH1
4l),q0(8l
qP
Cmplt
qW
mS1
hS1;}
q3
Cmpne
dO1
q0(hS1+fp_nequal(h22,dL1
Cos
qW
cos(1.1
hY1
Cos_deg
qW
cos
gE2
Cosh
qW
cosh(1.1
hY1
Cosh_deg
qW
cosh
gE2
Deg
qL
r2d(y)+r2d(x)+r2d(y)*h22;}
q3
Degxmul
wF1
gB1))*gL;}
q3
Div
qW(d01/dM+x;}
q3
Div1
qW
x/q0(1l
hY1
Divxx
qW
x+x/x+x;}
q3
qF2
qW
x*q0(14l);}
q3
Dupaddmulh
qW
x;}
q3
Dupaddmulmul7
qL
y*x*q0(14l);}
q3
Dupaddmulmulh
qL
y*x;}
q3
hC2(qD;q0
b2[2]qA
userDefFuncSub<q0>((b2[0]=(fp_min(x,x)),b2[1]=(fp_max(x,x)),b2
qP
qG2(qD;q0
b3[2]qA
userDefFuncSub<q0>((b3[0]=(x
g63
x)),b3[1]=(x+fp_max(x,x)),b3
qP
qH2(qD,&y
oR2;q0
b4[2]qA
userDefFuncSub<q0>((b4[0]=(fp_min(y,x)),b4[1]=(fp_max(y,x)),b4
qP
qI2
qW
x
hT1
Dupxpowmul
qW
qO
dL1
Eq0
qW
fp_equal(x,q0(0l
mC1
wA
Eq1
qW
fp_equal(fp_not(x),q0(1l
qP
Exp
qW
exp(1.1
hY1
Exp2
qW
exp(1.1*0.693147180559945309417232121458176568075500134
hY1
Exp2div
qL
x/fp_exp2(y);}
q3
Exp2log2
qW
h8
fp_exp2(x
qP
Exp2xpow
qW
fp_pow(fp_exp2(x),1506.0);}
q3
Expdiv
qL
x/fp_exp(y);}
q3
Explog
qW
hP
gO3
qP
Explog2
qW
x/fp_const_log2<q0>();}
q3
Explog10
qW
x/fp_const_log10<q0>();}
q3
Expxpow
qW
fp_pow
dH2
x),1506.0);}
q3
Floor
qW
floor(1.1
hY1
Floorneg
qW
fp_floor(-wA
qE3
aV
w0
0l))+qV3
fp_abs(x))qQ
w0
0l)qW3
d51
Ge0_neg
aV
w1
0l))+qV3
aY1))qQ
w1
0l)qW3
aY1
qP
Ge0_pos
aV
oP
0l))+qV3
gB1))qQ
oP
0l)qW3
gB1
qP
qF3
aV
w0
aZ1
fp_abs(x))qQ
w0
g12
d51
Ge1_neg
aV
w1
aZ1
aY1))qQ
w1
g12
aY1
qP
Ge1_pos
aV
oP
aZ1
gB1))qQ
oP
g12
gB1
qP
Gehalf
qW
hX,gD2
qP
qG3
qW
g01
w0
oD1
fp_abs(w2(w0
oE1
d51
Gt0_neg
qW
g01
w1
oD1
fp_sin(w2(w1
oE1
aY1
qP
Gt0_pos
qW
g01
oP
oD1
fp_acos(w2(oP
oE1
gB1
qP
qH3
qW
g01
w0
g22
fp_abs(w2(w0
g32
d51
Gt1_neg
qW
g01
w1
g22
fp_sin(w2(w1
g32
aY1
qP
Gt1_pos
qW
g01
oP
g22
fp_acos(w2(oP
g32
gB1
qP
Gtminushalf
qW
oI,-gD2
qP
Hypot
qW
sqrt(5.0*5.0+4.0*4.0
hY1
Immsub
qW
x-d01;}
q3
Int
qW
x+(((((hV1
1.1l
mA2
1.6l)mA2
1.5l)mA2-1.1l)mA2-1.6l)mA2-1.5l)qP
Intceil
qW
fp_ceil(oI,h12
Intfloor
qW
fp_floor(oI,h12
Intint
qW
fp_int(oI,h12
Inttrunc
qW
fp_trunc(oI,h12
Invdiv
qL
y/(g42
wA
Invinv
qW
g42(g42
wA
Invmul
qL
y*(g42
wA
Leminushalf
qW
o4,-gD2
qP
Log
qW
qX3
hY1
Log2
qW
qX3)*1.4426950408889634073599246810018921374266+x;}
q3
Log2exp1
qW
fp_exp(h8
x
qP
Log2exp2
qW
fp_exp2(h8
gB1)qP
Log10
qW
qX3)*0.43429448190325182765112891891660508229+x;}
q3
Logexp1
qW
fp_exp(hP
x
qP
Logexp2
qW
fp_exp(hP
gB1)qP
Logmul
qW
hP
m4
Logmul2
qW
h8
m4
Logmul10
qW
gU
m4
Lt0
qC2
fp_abs(x),x-x)-aX,x-wA
Lthalf
qW
aX,gD2
qP
Max
qW
q0(5l
hY1
Min
qW
q0(4l
hY1
Mod
qW
fp_mod(d01,dM+x;}
q3
Mul
qW(d01*dM+x;}
q3
Mul1
qW
x*q0(1l
hY1
Mul1b
qW((x*q0(0.2l))*d01
hY1
Mul2
qW
x+x;}
q3
Mul4
qL
y*(x*gL)*gL+(y*gL)*gL;}
q3
Mul_zero
qL(x*y+q0(1l))+(aY1)+fp_sin(y))*hP
x)*y*x*gF2
Mulminus1
qW
x*-1.0;}
q3
Mulneg
qW-(x
g52
a82
qW
x/q0(4l
hY1
Neg
qW((-((5.0)))hY1
Negabs
qW
fp_abs(-wA
Negadd
qL
x+(-y);}
q3
Negceil
qW-fp_ceil(wA
Negcos
qW
gH3-wA
Negcosh
qW
aO2-wA
Negdiv
qW(-x)/d01;}
q3
Negfloor
qW-fp_floor(wA
Negmul
qW(-x)hT1
Negneg
qW-(-(-(-(-(-(x))))qP
Negnot
g62-wA
Negsin
qW
fp_sin(-wA
Negsinh
qW
fp_sinh(-wA
Negsqr
qW
x*x;}
q3
Negsub
qL
x-(-y);}
q3
Negtan
qW
dD2-wA
Negtanh
qW
fp_tanh(-wA
Neq0
qW(w3,gM2))+(fp_nequal(gM2,x
qP
Neq1
dO1
fp_not(x),q0(1l
qP
Not
g62
q0(3l)hY1
Not_eq
qL
x!=mB1
Not_ge
qL
x<mB1
Not_gt
qL
x<=mB1
Not_le
qL
x>mB1
Not_lt
qL
x>=mB1
Not_ne
qL
x==mB1
Notnot
qW
fp_notNot(wA
hD2
g62
wA
qJ2
g62
wA
Or
qW
fp_or(q0(hS1+fp_or(d01,gM2)+fp_or(gM2,d01)+fp_or(gM2,aK2
Pow_neg
qW
pow(-0.25,4.0
hY1
Pow_pos
qW
pow(1.1,7.1
hY1
Powdiv
qL
x/qO
y);}
q3
Powhalf
qW
qO
gD2
qP
Powinv
qL
g42
qO
y);}
q3
Powminushalf
qW
qO-gD2
qP
Powminusone
qW
qO-q0(1.0l
qP
Powminusthird
qW
qO(q0(-1.0l)/q0(3.0l)qP
Powthird
qW
qO(a0/q0(3.0l)qP
Powxpow
qW
fp_pow(qO
1.7),1506.0);}
q3
Rad
qL
d2r(y)+d2r(x)+d2r(x)*h22;}
q3
Radxmul
qW
gH3
d2r(x+x+x+x
qP
Rsqrt
qW
1.0/h32
wA
Sin
qW
sin(1.1
hY1
Sin_deg
qW
sin
gE2
Sincos_cci
qW
mB
h42
gH3
wA
Sincos_cic
qW
g42
mB)+gH3
wA
Sincos_sc
qW
aY1)+gH3
wA
Sincos_sci
qW
aY1
h42
gH3
wA
Sincos_sis
qW
g42
aY1)+fp_sin(wA
Sincos_ssi
qW
aY1
h42
fp_sin(wA
Sincos_tan
qW
dD2
wA
Sincos_tit
qW
g42
dD2
x)+dD2
wA
Sincos_tti
qW
dD2
x
h42
dD2
wA
Sinh
qW
sinh(1.1
hY1
Sinh_deg
qW
sinh
gE2
mS2
qW(-x)*x;}
q3
mT2
qW
x*(-wA
Sqr_xx
qW
x*x;}
q3
oT2
qL
y*-x*x;}
q3
oU2
qL
y*x*-x;}
q3
mU2
qL
y*x*x;}
q3
Sqreq0
qW
fp_equal(x*x,q0(0l
mC1
x*wA
Sqrlog
qW
hP
x*wA
Sqrlog2
qW
h8
x*wA
Sqrlog10
qW
gU
x*wA
qP3
qW
fp_equal(x*x,q0(0l
mC1
x*wA
Sqrsqrt
qW
h32
x*wA
Sqrt
qW
sqrt(1.1
hY1
Sqrtsqr1
qW
fp_pow(h32
x),q0(2l
qP
Sqrtsqr2
qW
fp_pow(h32
gB1)),q0(2l
qP
Sqrxpow
qW
oG1,2402.0);}
q3
Sqrxpow_nonint
qW
oG1,3.5);}
q3
Sub
qW
d01-q0(3l
hY1
Sub0
qW
x-q0(0l
hY1
Subxx
qW
x+(x-x)+x+(q0(1l)-x+wA
Tan
qW
tan(1.1
hY1
Tan_deg
qW
tan
gE2
Tanh
qW
tanh(1.1
hY1
Tanh_deg
qW
tanh
gE2
Trunc
qW
1.0+x;}
q3
mV2
g62
x+dL1
Xaddnotnot
qW
d61+dL1
Xmulrad
qW
gH3
d2r(gK2
x
qP
Xmulsinhneg
qW-fp_sinh(x
g52
Xmulsinneg
qW-aY1
g52
Xmultanhneg
qW-fp_tanh(x
g52
Xmultanneg
qW-dD2
x
g52
Xsqryfsqrhypot
qW
fp_hypot(hP
x),h8
x
qP
Xsqrysqrhypot
qL
fp_hypot(hP
x)aN2
Xxdup
qW
x-x;}
q3
Xxfdup
qW
x-x;}
q3
oV2
qL
y*fp_abs(x)*fp_abs(wA
Ypowxpow
qW
fp_pow(qO
38.5),5.0
g43
cpp_11optimizer_constaddmul{using
namespace
FUNCTIONPARSERTYPES;q3
t1(mI2
g42
a)hT1
t2(qC
qA
d01*a;}
q3
t3(qC
qA
d01/a;}
q3
t4
oQ(a*d01)*b;}
q3
t5
oQ(a*d01)/b;}
q3
t6
oQ(g42
a)*b;}
q3
t7
oQ(g42
a)/b;}
q3
t8
oQ
q52)*(mI
g52
t9
oQ
q52)/(mI
g52
t10
oQ
mI*(d01/a);}
q3
t11
oQ
mI/(q0(50l)/a);}
q3
t12(mI2-a
hU1
t13
oQ
d01+(a*b);}
q3
t14
oQ
d01-(a*b);}
q3
t15
oQ(a+d01)+mI;}
q3
t16
oQ(a+d01)-mI;}
q3
t17
oQ(-a)+mI;}
q3
t18
oQ(-a)-mI;}
q3
t19
oQ
b+(q52
gC1
5l
qP
t20
oQ
b-(q52
gC1
5l
qP
t21
oQ
mI+(d01-a);}
q3
t22
oQ
mI-(d01-a);}
q3
t23
oQ
dT2
b)/a;}
q3
t24
oQ
dT2
d01)/a;}
q3
t25
oQ
dT2
d01
gU3
t26
oQ(q52)/b)/a;}
q3
t27
oQ(q52)/b
gU3
t28
oQ((-a)/b)hT1
t29
oQ(d01/b
gU3
t30(gC2*vars){gC2&b=vars[0]qA(h72/b)hT1
t31
oQ
b*(h72/-a);}
q3
t32
oQ(d01-b)-a;}
q3
t33
oQ(d01-b)+a;}
q3
t34
oQ((a+h72)-b
hU1
t35
oQ((-a)-b
hU1
t36(mI2
h72-q52)hU1
t37
oQ((h72-b)+a
hU1
t38
oQ
fp_less((d01*b+q52)),gM2)*q0(1l)dL2(mI),gM2)*gL;}
q3
t39(mI2
a+h72)hT1
t40
oQ(b+(a*h72))hT1
t41
oQ(b-(a*h72))hT1
t42(mI2
a+h72
hU1
t43(mI2
a*h72)*d01;}
}
namespace
cpp_20optimizer_optimizations{using
namespace
FUNCTIONPARSERTYPES;q3
Abscos
qW
gH3
fp_abs(x))+fp_abs(wA
Abscosh
qW
aO2
fp_abs(x))+fp_abs(wA
Abseq0
qW
fp_equal(w0
0l
mC1
d51
q83
qW
fp_equal(w0
0l
mC1
d51
mP2(qD;q0
b5[2]qA
userDefFuncSub<q0>((b5[0]=(fp_greaterOrEq(fp_abs(x),dM),b5[1]=(fp_greaterOrEq(w0
0l))),b5
qP
mQ2(qD;q0
b6[2]qA
userDefFuncSub<q0>((b6[0]=(fp_less(fp_abs(x),dM),b6[1]=(fp_less(w0
0l))),b6
qP
Acoscos
qW
gH3
gB1
qP
Acoshsinh
qW
fp_sinh(fp_acosh(x
qP
mE1
qL
d01*(h22+x+y);}
q3
Addlog
qL
hP
x)+hP
y);}
q3
dR1
qL
d01*(h22*y+wA
wS1
qL-d01+(d01*x*y);}
q3
wT1
qL-d01*y+(d01*wA
Addsin2cos2
qW
fp_pow(aY1),gL)+fp_pow(mB),q0(2l
qP
Asinhcosh
qW
aO2
fp_asinh(x
qP
Asinsin
qW
fp_sin(fp_asin(x
qP
w01
qL
fp_equal(x
dG
qP
Cmpeq_add_reduce
qW
fp_equal(mJ
qP
h81
qL
fp_equal(x+h2
wU1
qL((fp_equal(x
mK
h91
qL((fp_equal(x
mT1
gI1
qL
fp_equal(x*-dF
gJ1
qL
fp_equal(x*dF
mP
qL
fp_equal(x*-h2
mQ
qL
fp_equal(x*h2
Cmpeq_pow_imm_negneg
qW
fp_equal(d7
qP
Cmpeq_pow_imm_negpos
qW
fp_equal(o1
Cmpeq_pow_imm_posneg
qW
fp_equal(x*aW
Cmpeq_pow_imm_pospos
qW
fp_equal(x
d21
Cmpeq_pow_imm_pospos_base
qW
fp_equal(q0(dI
Cmpeq_powpow_imm_base
qL
fp_equal(dR
w11
qL
hX
dG
qP
Cmpge_add_reduce
aV
mJ
qP
hA1
qL
hX+h2
wW1
qL((hX
mK
hB1
qL((hX
mT1
gL1
qL
hX*-dF
gM1
qL
hX*dF
mR
qL
hX*-h2
mS
qL
hX*h2
Cmpge_pow_imm_negneg
aV
d7
qP
Cmpge_pow_imm_negpos
aV
o1
Cmpge_pow_imm_posneg
qW
hX*aW
Cmpge_pow_imm_pospos
qW
hX
d21
Cmpge_pow_imm_pospos_base
aV
q0(dI
Cmpge_powpow_imm_base
qL
fp_greaterOrEq(dR
w21
qL
oI
dG
qP
Cmpgt_add_reduce
qW
g01
mJ
qP
hC1
qL
oI+h2
wX1
qL((oI
mK
hD1
qL((oI
mT1
gO1
qL
oI*-dF
gP1
qL
oI*dF
mT
qL
oI*-h2
mU
qL
oI*h2
Cmpgt_pow_imm_negneg
qW
g01
d7
qP
Cmpgt_pow_imm_negpos
qW
g01
o1
Cmpgt_pow_imm_posneg
qW
oI*aW
Cmpgt_pow_imm_pospos
qW
oI
d21
Cmpgt_pow_imm_pospos_base
qW
g01
q0(dI
Cmpgt_powpow_imm_base
qL
g01
dR
w31
qL
o4
dG
qP
Cmple_add_reduce
qW
dN1
mJ
qP
hE1
qL
o4+h2
wY1
qL((o4
mK
hF1
qL((o4
mT1
gR1
qL
o4*-dF
gS1
qL
o4*dF
mV
qL
o4*-h2
mW
qL
o4*h2
Cmple_pow_imm_negneg
qW
dN1
d7
qP
Cmple_pow_imm_negpos
qW
dN1
o1
Cmple_pow_imm_posneg
qW
o4*aW
Cmple_pow_imm_pospos
qW
o4
d21
Cmple_pow_imm_pospos_base
qW
qH1
dI
Cmple_powpow_imm_base
qL
dN1
dR
w41
qL
aX
dG
qP
Cmplt_add_reduce
qC2
mJ
qP
hG1
qL
aX+h2
wZ1
qL((aX
mK
hH1
qL((aX
mT1
gU1
qL
aX*-dF
gV1
qL
aX*dF
mX
qL
aX*-h2
mY
qL
aX*h2
Cmplt_pow_imm_negneg
qC2
d7
qP
Cmplt_pow_imm_negpos
qC2
o1
Cmplt_pow_imm_posneg
qW
aX*aW
Cmplt_pow_imm_pospos
qW
aX
d21
Cmplt_pow_imm_pospos_base
qW
mS1
dI
Cmplt_powpow_imm_base
qL
fp_less(dR
w51
qL
w3
dG
qP
Cmpne_add_reduce
dO1
mJ
qP
hI1
qL
w3+h2
a11
qL((w3
mK
hJ1
qL((w3
mT1
gX1
qL
w3*-dF
gY1
qL
w3*dF
mZ
qL
w3*-h2
q01
qL
w3*h2
Cmpne_pow_imm_negneg
dO1
d7
qP
Cmpne_pow_imm_negpos
dO1
o1
Cmpne_pow_imm_posneg
qW
w3*aW
Cmpne_pow_imm_pospos
qW
w3
d21
Cmpne_pow_imm_pospos_base
dO1
q0(dI
Cmpne_powpow_imm_base
qL
fp_nequal(dR
w61
qL
q0(h7
h82
gP
h82
gS
h82
gI
h82
gW
x
dG
mB2
dG
qP
Cmpzz_add_reduce
q62
mJ)gC1
gP
mJ)gC1
gS
mJ)gC1
gI
mJ)gC1
gW
mJ))gT
mJ
qP
hK1
qL
q0(h7
x+q0
m01
gP
x+q0
m01
gS
x+q0
m01
gI
x+q0
m01
gW
x+q0
qY3+h2
a21
qL
q0(0x0001l)*((aX
mU1
0x0002l)*((o4
mU1
0x0004l)*((oI
mU1
0x0008l)*((hX
mU1
0x0010l)*((w3
mU1
0x0020l)*((fp_equal(x
mK
hM1
qL
q0(0x0001l)*((aX
mV1
0x0002l)*((o4
mV1
0x0004l)*((oI
mV1
0x0008l)*((hX
mV1
0x0010l)*((w3
mV1
0x0020l)*((fp_equal(x
mT1
h01
oX1-dH
gP
x*-dH
gS
x*-dH
gI
x*-dH
gW
x*-h22*mL2
mB2*-dF
h11
oX1
dH
gP
x*dH
gS
x*dH
gI
x*dH
gW
x*h22*mL2
mB2*dF
q11
oX1
aR2
gP
x*aR2
gS
x*aR2
gI
x*aR2
gW
x*-q0
qY3*-h2
q21
oX1
q0
m01
gP
x*q0
m01
gS
x*q0
m01
gI
x*q0
m01
gW
x*q0
qY3*h2
Cmpzz_pow_imm_negneg
q62
d7)gC1
gP
d7)gC1
gS
d7)gC1
gI
d7)gC1
gW
d7))gT
d7
qP
Cmpzz_pow_imm_negpos
q62
w4
gP
w4
gS
w4
gI
w4
gW
qO-gL),q0(0.0625l))gT
o1
Cmpzz_pow_imm_posneg
q62
x
aB
gP
x
aB
gS
x
aB
gI
x
aB
gW
x*x*x,-q0(125l
mB2*aW
Cmpzz_pow_imm_pospos
q62
x
wE1
gP
x
wE1
gS
x
wE1
gI
x
wE1
gW
x*x,q0(25l
mB2
d21
Cmpzz_pow_imm_pospos_base
q62
q0(oK+q0(gP
q0(oK+q0(gS
q0(oK+q0(gI
q0(oK+q0(gW
q0(oK
gT
q0(dI
Cmpzz_powpow_imm_base
qL
q0(h7
oR+q0(gP
oR+q0(gS
oR+q0(gI
oR+q0(gW
oR
gT
dR
Eq0
qW
fp_equal(x,q0(0l
mC1
wA
Eq1
qW
fp_equal(fp_not(x),q0(1l
qP
Expexp_a
qL
gO3*gL+y*q0(3l
qP
Expexp_b
hJ
gO3)*fp_exp(y+z);}
q3
Expexp_c
hJ
gO3+y*z);}
q3
qE3
aV
w0
0l))+qV3
fp_abs(x))qQ
w0
0l)qW3
d51
qF3
aV
w0
aZ1
fp_abs(x))qQ
w0
g12
d51
hK2
qL
x==mB1
hL2
qL
x==mB1
hM2
qL
x>mB1
w82
qL
x>=mB1
w92
qL
x
g82
wA2
qL
x
g82
Gehalf
qW
hX,gD2
qP
qG3
qW
g01
w0
oD1
fp_abs(w2(w0
oE1
d51
qH3
qW
g01
w0
g22
fp_abs(w2(w0
g32
d51
hN2
qL
x
oS
qZ3
hO2
qL
x>mB1
hP2
qL
x
oS
qZ3
hQ2
qL
x>mB1
wB2
qL
x>=mB1
wC2
qL
x>=mB1
wD2
qL
x
g82
wE2
qL
x!=mB1
If10
qW
d61
gC1
10l)*fp_not(x
gC1
100l)*oI,gM2
gC1
1000l)*o4,aK2
dV1
qL
fp_abs(o5(x+gL):(y+d01
qP
dW1
qL
y+(o5
gL:q0(5l
qP
d71
qL
o5(y+gL):mB1
d81
qL
o5
y:(y+q0(2l
qP
If_extract_and1_l(qY
oY1:qI1
qP
If_extract_and1_nl(qY
oY1:z;}
q3
If_extract_and2_l(qY
qI1)):oY1;}
q3
If_extract_and2_nl(qY
z:oY1;}
q3
If_extract_div
qL
y/(o5
x:q0(2l
qP
dX1
qL
fp_min(y,(o5
gL:d01
qP
dY1
qL
y*(o5
gL:q0(5l
qP
d91
qL
o5(y*gL):mB1
dA1
qL
o5
y:(y*q0(2l
qP
If_extract_or1_l(qY
m21:qI1
qP
If_extract_or1_nl(qY
m21:z;}
q3
If_extract_or2_l(qY
qI1)):m21;}
q3
If_extract_or2_nl(qY
z:m21;}
q3
If_extract_sin
qL
fp_sin(o5
y:wA
If_join_add
qL
aY(m41
gG3)):(fp_cos
aL2))+fp_sin
aL2)qP
If_join_add2
qW
x+(aY
q0(13l):q0(14l
qP
If_join_and
qL
aY
fp_and
qB1
fp_and
dP
If_join_max
qL
aY
fp_max
qB1
fp_max
dP
If_join_min
qL
aY
fp_min
qB1
fp_min
dP
If_join_mul
qL
aY(fp_sin(y)*gG3)):(fp_cos
aL2))*fp_sin
aL2)qP
If_join_mul2
qW
x*(aY
q0(30l):q0(40l
qP
If_join_or
qL
aY
fp_or
qB1
fp_or
dP
Ifabs
qW
q0(1l
q61
aX
m5
10l
q61
o4
m5
100l
q61
oI
m5
1000l
q61
hX
m5
10000l
q61
aX
q31
100000l
q61
o4
q31
1000000l
q61
oI
q31
10000000l
q61
hX,gM2
gJ
x:-x
qP
Ifabsnot
hJ
fp_truth(aY1
gC1
1.2l)gJ
z:mB1
Ifconst
hJ
x+y+z*gF2
Ififconst(gC2*vars){gC2&w=vars[0],&x
oR2,&y=vars[2],&z=vars[3]qA
mE
o5
q0(1l):y
gJ
z:w)+mE
fp_truth(w
gJ
z:gM2
gJ
x:y);}
q3
Ifmerge(gC2*vars){gC2&b=vars[0],&d
oR2,&oJ
x:b):mE
y
gJ
x:d))+mE
b
gJ
mE
d
gJ
y:x):mE
d
gJ
b:x
qP
Ifmerge2(qC,&b
oR2,&oJ
a:b):mE
b
gJ
a:b
qP
Ifmerge2b(qC,&b
oR2,&oJ
a:b):mE
b
gJ
b:a
qP
Ifnop
qL
x*gM2+mB1
Ifnot(qY
z:mB1
L_abs
gG2+gL,fp_and(fp_abs(x),y+gL
qP
wG2
gG2*y*fp_abs(y),y+q0(2l
qP
wH2
gG2*y*-d01,y+q0(2l
qP
wI2
gG2+gL,fp_and(d61),y+gL
qP
hS2
qL
x==mB1
hT2
qL
x<mB1
wJ2
qL
x<=mB1
wK2
qL
x
g82
hU2
qL
x
oS
qZ3
hW2
qL
x
oS
qZ3
hX2
qL
x
oS
qZ3
hY2
qL
x<mB1
hZ2
qL
x<mB1
wL2
qL
x<=mB1
wM2
qL
x
g82
wN2
qL
x!=mB1
wO2
qL
x<=mB1
wP2
qL
x!=mB1
Lthalf
qW
aX,gD2
qP
Mergemulabs
hJ
fp_abs(x)*fp_abs(y)*z;}
q3
Mixedminmax
hJ
fp_max(z,fp_min
gH2
fp_max(z,y),x))gC1
10l)*fp_min(z,fp_max(x,fp_min(y,x))gC1
100l)*fp_min(fp_max(x,y),fp_min(y,z)gC1
1000l)*fp_max(fp_min(x,y),fp_max(y,z
qP
Muland2
qL
a8;}
q3
Muland2plus
hJ
a8*z;}
q3
Muland3
hJ
a8*fp_notNot(z);}
q3
Mulandlt
qL
d61)*q0(fp_less(y,gM2
qP
Mulimmlog
qL
hP
d01*x*y);}
q3
Mulnor2
qL
qA1;}
q3
Mulnor2plus
hJ
qA1*z;}
q3
Mulnor3
hJ
qA1*aS2);}
q3
Nand2
qL
aN
qP
Nand2plus
hJ
fp_or(aN)),z);}
q3
Nand3
hJ
fp_or(aN)),aS2
qP
Negceil
qW
fp_ceil(-wA
Negcos
qW
gH3-wA
Negcosh
qW
aO2-wA
Negfloor
qW
fp_floor(-wA
Negsin
qW
fp_sin(-wA
Negsinh
qW
fp_sinh(-wA
Neq0
qW(w3,gM2))+(fp_nequal(gM2,x
qP
Neq1
dO1
fp_not(x),q0(1l
qP
Nor2
qL
a9
qP
Nor2plus
hJ
fp_and(a9)),z);}
q3
Nor3
hJ
fp_and(a9)),aS2
qP
Not_eq
qL
x!=mB1
Not_ge
qL
x<mB1
Not_gt
qL
x<=mB1
Not_le
qL
x>mB1
Not_lt
qL
x>=mB1
Not_ne
qL
x==mB1
Notnot
qL
fp_truth(x)+fp_truth(y);}
q3
Posnot
g62
aY1
gC1
1.2l
qP
Posnotnot
qW
fp_notNot(aY1
gC1
1.2l
qP
Powimmaddimmlog
qW
qI
5l),hP
x
gC1
1l
qP
Powimmlog
qW
qI
3l),hP
x))+qI
5l),hP
x)*aY1
qP
Powmulimm_fnen
qL
a1*y,(q0(-8l)qP
Powmulimm_fnep
qL
a1*y,(h12
Powmulimm_fnfn
qW
a1,(q0(-7.1l)qP
Powmulimm_fnfp
qL
a1*y,q0(7.1l
qP
Powmulimm_fpfp
qL
qI
5.1l)*x*y,q0(7.1l
qP
Sub1cos2
qW
q0(1l)-fp_pow(mB),q0(2l
qP
Sub1sin2
qW
q0(1l)-fp_pow(w1
2l
qP
Trig_modulo
qW
mB+gF)+mB+gF*q72)+mB+gF*d01
dE2+gF*q0(6l)dE2+gF*h72
dF2
a2+gF*q72
a2+gF*d01
dF2*q0(6l)dF2*h72
dE2-gF)+mB-gF*q72)+mB-gF*d01
dE2-gF*q0(6l)dE2-gF*h72
dG2
a2-gF*q72
a2-gF*d01
dG2*q0(6l)dG2*h72/q0(2l
qP
Trunc_from_if
qW
fp_trunc(x)*q0(4l
gC1
40l)*(x>gM2?fp_ceil(x):fp_floor(x
qP
mV2
g62
x+dL1
Xaddnotnot
qW
d61+dM;}
}
namespace
cpp_50regressions{using
namespace
FUNCTIONPARSERTYPES;q3
t1
qW
x+g92
0l),fp_min(q0(-2l),gM2
qP
t2
qW
fp_min(x,fp_min(q0(1l),x
qP
t3(qD;q0
b7[2]qA
userDefFuncSub<q0>((b7[0]=(fp_and(fp_not(x),d61))),b7[1]=(fp_or(fp_not(x),d61))),b7
qP
t4(qD,&y
oR2;q0
b9[2]qA
userDefFuncSub<q0>((b9[0]=(fp_not(x-y)),b9[1]=(d61-y)),b9
qP
t5(qD;q0
b11[2]qA
userDefFuncSub<q0>((b11[0]=(aY1
h42
aY1)),b11[1]=(mB)),b11
qP
t6(qD;q0
b13[2]qA
userDefFuncSub<q0>((b13[0]=(fp_not(x+dM),b13[1]=(d61+dI2),b13
qP
t7
qW
x-x;}
q3
t8
qL
q82-x,-y
gC1
10l)*q82-x,y
gC1
20l)*q82
x,-y
gC1
30l)*q82
x
aN2
t9a
qW
x*gF2
t9b
oQ(a-b)*gF2
t9c
oQ(a-b)*gF2
t9d
oQ
a*b*gF2
t36
qW-(x<gM2?x:-x)+-(x<d01?gL:q0(3l
qP
t42
qL
h32
x*x
gC1
1.5l)*(fp_pow(y*y,q0(0.25l)))+fp_hypot(x
aN2
t51
qW
hP-wA
t57
qW
aO2
fp_asinh(x
qP
t59
qL
aO2
x*x)+fp_tanh(y*y);}
q3
t60(qD,&y
oR2;q0
b14[1];q0
b15[2]qA
fp_or(fp_or(d11
b14[0]=(x),b14)),userDefFuncSub<q0>((b15[0]=(x),b15[1]=(y),b15))),userDefFuncValue<q0>((0))g43
cpp_99misc{using
namespace
FUNCTIONPARSERTYPES;q3
t1
qW
x*h22/gL+(q0(1l)+(gL+dI2)+x*x+x+(a0+g03
gC1
3.0l)*q0(4.0l
gC1
5.0l)*q0(6.0l)*q0(7.0l)-q0(8.0l)*q0(9.0l
qP
t2
qW
gL*x+aY1)/q0(.5l)+gL-aY1)aT2
wA
t3
hJ
fp_and(m31),fp_equal(y,x))+a0+g03)-q0(3.1l)*q0(4e2l)/q0(.5l)+x*x+y*y+z*z+fp_and(x,x)+fp_or(y
aN2
t4
qL(((((x-y)-(((y)*gL)-dI2))*dM
a2)*gG3)-mB)aT2
y);}
q3
t5(gC2*vars){gC2&__A5_x08=vars[0],&o__5_0AB_
oR2
qA
fp_pow(__A5_x08,o__5_0AB_);}
q3
t7
qW
mB)aT2
q0(1l)-x)*(q0(1l)-mB/gL)*aY1*d01
qP
t8
qL
q82
x,y)+(x>y?x:y);}
q3
t9
hJ
q0(1.5l)+x*y-g03
gC1
4.0l)/q0(8.0l)+z+z+z+z+x/(y*z);}
q3
t10
hJ
q0(1l)+fp_sin(gH3
g92
1l)+gL+q0(3l
gC1
4l
gC1
5l),x+y+z)))+gL;}
q3
t11
hJ(-x-x)+y+hP
qI
1.1l),z
qP
t12
qW
a0/hP
qI
10.0l),a0/hP
x)qP
t13
qL
qO
dI2*qO
dM+fp_pow(y,dI2*fp_pow(y,q0(5l
qP
t14
qW
x*gF+fp_sin(gL*gF
gC1
CONST);}
q3
t15
qL
qO
y)/hP
y)+hP
x)/hP
y)+hP
qO
y
qP
t16
qL
x<gM2?(y<gM2?x+y:x-y):(y>gM2?x*y:x+gL*y);}
q3
t17(qD,&y
oR2;q0
b18[1];q0
b19[2];q0
b20[1];q0
b21[2]qA
d11
b18[0]=(x),b18))+userDefFuncSub<q0>((b19[0]=(x),b19[1]=(y),b19))+d11
b20[0]=(y),b20))+userDefFuncSub<q0>((b21[0]=aL2)),b21[1]=(x-gL),b21))-q0(1l);}
q3
t18
qL-(-(-(-d01)))*-qO-fp_pow(y,-gL
qP
t19
qL
aX,y
gC1
10l)*o4,y
gC1
100l)*oI,y
gC1
1000l)*hX,y
gC1
10000l)*m31
gC1
100000l)*w3,y)+fp_and(x,y)*gL+fp_or(x,y)*q0(20l)aU2
x)*q0(200l)+fp_truth(x)*q0(2000l
gC1
4l)*fp_not(fp_and(aX,y),aX,dI2)gC1
40l
gW3
fp_not(oI,y)),oI,q0(3l)qP
t20
qL
fp_and(fp_not<q0>(x!=y),fp_not(x))+fp_truth(y);}
q3
t21(qD;q0
b26[1]qA
d11
b26[0]=(x),b26))+userDefFuncValue<q0>((0))-d01;}
q3
t22
qL(q0(3.5l)*gL
gC1
10l)*(x*dI2-(fp_sin(y)*gL
gC1
100l)*((x*gL)-(y*dI2)*gL+q0(5.0l)/(gL*gL)+qI
1.1l),x*gL)+qI
1.1l)*gL,x*q0(2l
qP
t23
qW(x/(gL*fp_acos(q0(0.0l))))*q0(180l);}
q3
t24
qW(fp_min(x,fp_min(q0(1l),x))g63
gZ2/gL
g63
q0(1l))*q0(3l)+g92
0l),fp_min(q0(-2l),gM2
qP
t25(qC,&b
oR2,&c=vars[2]qA
fp_pow(a,fp_pow(b,c))+fp_pow(a,-gL)*(-fp_pow(b,gL))+(-fp_pow(b,-c
qP
t26_deg
qW
fp_sin(d2r(x))+gH3
d2r(x*q0(1.5l)))+r2d(fp_asin(x/q0(110.0l)))+r2d(gB1/q0(120.0l)qP
t27
qL
fp_abs(x)+gB1)+fp_asin(x)+fp_atan(x)+q82
x,y)+fp_ceil(x)+mB)+aO2
x)+a0/dD2
x)+a0/aY1)+qO
y);}
q3
t28
qL
gO3)+fp_floor(x)+fp_int(x)+hP
x)+gU
x)+fp_max(x,y)g63
y
h42
mB
a2)+fp_sinh(x)+h32
x)+dD2
x)+fp_tanh(x)+fp_ceil(y)+fp_trunc(y);}
q3
t29
qL
x-y*q0(1l);}
q3
t30
qL
x-y*q0(1l)+fp_mod(x,y)+x/fp_pow(y,q0(gV3
qI
2l),dI2+fp_mod(d01,dI2+qO
fp_pow(y,gM2))+qO
gD2
qP
t31
hJ
x-(y*(y*(y*-gZ2*q0(1l))+hP
x*h52
y))-hP
qO
y))+h52
hP
x
gJ3)+qI
10.0l),hP
x
gJ3/hP
y
gJ3*hP
z
gJ3/hP
q0(10.0l)))-h52
hP
x
gJ3*y)-qI
5.0l),hP
x+h72)/hP
q0(5.0l)))+h62
dI2*h62
gL)/h62
dL1
t32
hJ
x+y/y-fp_min(q0(3l),dM-x-g92
4l),dI2+g92
3l),dM-fp_min(h22,q0(3l)gC1
0l)+(z*q0(1l))+(x-gL+gL)+(x*gD2)*gL)+y*gM2+fp_min(fp_min(fp_min(q0(4.0l),x),a0),fp_min(x,fp_min(fp_min(y,q0(4.0l)),z)))+fp_max(fp_max(g92
4.0l),x),a0),fp_max
gH2
fp_max(y,q0(4.0l)),z)))+(fp_abs(q0(1l))+fp_acos(a0)+fp_asin(a0)+fp_atan(a0)+fp_ceil(q0(gV3
fp_cos
wJ1
fp_cosh
wJ1
fp_floor(q0(gV3
hP
a0)+fp_sin
wJ1
fp_sinh
wJ1
dD2
a0)+fp_tanh(a0)+q82
a0,a0))+(x-(y-z))+(x+y)+(x*y)+fp_max
gH2
x,fp_max
gH2
x,x))))*-a0+(z-z
h42
aY1/dP1
gG3/dP1
dD2
z/d01)+gU
g42
dD2
z/dP1
fp_sin(y/dP1
mB/d01))+hP
q0(30l)+x)*hP
q0(40l)+y)/hP
q0(50l)+z
a2/q0(57.295779513082320877l))+fp_asin(x/q0(10l))*q0(57.295779513082320877l)+fp_floor(-x
h42
fp_ceil(x)+h32
d01*q0(0.2l))+(-x+-x+-x+-x+-x+-wA
t33
qL
fp_sin(h32
q0(10l)-x*x+y*y))+gH3
h32
q0(15l)-x*x-y*y)a2*x+y*y);}
q3
t34(gC2*vars){gC2&t=vars[0],&rvar0
oR2,&rvar1=vars[2],&rvar2=vars[3]qA
rvar1+rvar2*rvar0-t;}
q3
t35(gC2*vars){gC2&wP=vars[0],&A_very_long_variable_name_2
oR2,&Yet_a_third_very_long_variable_name=vars[2]qA
wP-A_very_long_variable_name_2+Yet_a_third_very_long_variable_name*wP;}
q3
t37
qW
q0(5l
gC1
7.5l)*q0(8l)/q0(3l)-qI
2l),dM*gL+fp_mod(h72,gL
gC1
4l
hY1
t38
hJ
fp_asinh(x
gC1
1.5l)*fp_acosh(y+q0(3l)gC1
2.5l)*fp_atanh(z);}
q3
t39
hJ
aY1+wK1)-mB+fp_sin(y*q0(1.5l)))+z*z*z
aT2
z*z*z-x*x-y*y)-wK1*aY1+wK1)+x*y*z+x*y*q0(2.5l)+x*y*z*mB)+x*y*mB)+x*z*mB)+y*z*q0(2.5l)+(x*y*z*mB)-x*y*z-y*mB)-x*z*y+x*y+x*z-mB)*wA
t40
hJ
gY*gY+gL*gY-x*y*gY+x*gY;}
q3
t41
hJ
x*q0(3l)+x*y+x*z+x
aT2
y*z)-(fp_sin(oF1
h22
gI2
x
gI2
y
gI2
z;}
q3
t43
qW
hP
x*x)+fp_abs
dH2
fp_abs(x
gC1
1l)qP
t44
qW
oG1
wQ
8l)o32
oG1*x
wQ
7l)o42
oG1*x*x
wQ
6l)gC1
1.3l)*oH1
wQ
5l)gC1
1.4l)*oH1*x
wQ
6l)gC1
1.5l
dK2,g42
dM+q0(1.6l
dK2*x
wQ
3l)gC1
1.7l
dK2*x*x,g42
gL
gC1
1.8l)*(h32
fp_pow(fp_abs(-h32
x)),dI2
qP
t45
qW
oG1
wQ
7l)o32
oG1*x*x
wQ
5l)o42
oH1*x
wQ
3l
qP
t46
qL
fp_abs(fp_floor(gB1)+dM
o32
fp_abs(fp_floor(fp_acos(y
gC1
1.5l)))dL2
gB1),(fp_acos(y)-q0(10l))o42
g92-4l),gB1)gC1
1.3l)*fp_min(q0(9l),gB1)-q0(9l
qP
t47
qL
q0(1.25l)*dH2
x)+fp_exp(-x)gC1
1.5l)*dH2
y)-fp_exp(-y)gC1
1.75l)*(dH2-x)+gO3))/gL
gC1
2.0l)*(dH2-x)-gO3))/gL
gC1
2.25l)*(aO2
y)+fp_sinh(y
qP
t48
qW
fp_sinh((hP
x)/q0(5l
gC1
1l))*d01
o42
aO2(hP
x)/hP
gL
gC1
1l))*hP
gL))aU2
fp_or
mE
x),fp_not(x/dM
qP
t49
qW
q82
gM2,x)+qI-4l)*(x-q0(100l)),q0(3.3l
qP
t50
qL
fp_or(aX,y),fp_less(y,x))+gL
wL1
aX,y),fp_less(y,x)gC1
4l)wL1
o4,y),dN1
y,x)gC1
8l)wL1
aX,gA2
16l
gW3
aX,gA2
32l)wL1
o4,y),hX,y)gC1
64l
gW3
o4,y),hX,y)gC1
128l)wL1
w3,y),m31)gC1
256l)wL1
w3,gA2
512l)wL1
o4,y),m31
qP
t52
qW
x+(a0+g03
gC1
3.0l
gC1
4.0l)-q0(5.0l)-q0(6.0l)-q0(7.0l)-q0(8.0l))/q0(3.0l
gC1
4.0l)*(a0+fp_sin(g03))+gH3
q0(4.0l)*q0(5.0l
gC1
6.0l))/g03))+gH3
gD2))*dD2
q0(0.6l
gC1
0.2l))-q0(1.1l)/hP
q0(2.1l))*h32
q0(3.3l))+qI
2l),q0(3l
qP
t53
gG2,y
gC1
4l
gW3
fp_int(x/q0(10l)),fp_int(y/q0(10l))gC1
8l)*((-dC1-x)))+(dC1-fp_not(y))))gC1
16l)*(-x
aU2
y
qP
t54
qL
aX,y)+o4,y)+oI,y)+hX,y)+m31)+w3,y)+fp_and(x,y)+fp_or(x,y)aU2
x)+fp_truth(x)aU2
fp_and(aX,y),aX,dI2))+fp_or(fp_not(oI,y)),oI,q0(3l)qP
t55
qL
fp_less(qO
q0(1.2l)),gM2)dL2
fp_pow(y,q0(2.5l)),gM2)qU
x*x,gM2
gC1
3l)*fp_less(fp_pow(y,dI2,gM2
gC1
4l)*fp_less(qO
dM,aK2
t56
qW
fp_mod(q0(1.75e21l),wA
t58
qL
fp_less(-x,dI2+oI*-q0(1l),d01)+aX*-q0(3l),q0(10l))+aX*-q0(3l),y*h72)+aX*h22,y*h72)+aX*q0(6l),y*-dI2
dL2-x,q0(11l))dL2
d01,-y);}
q3
t59
qC2
mB),aY1))+(mB)-aY1))+((fp_sinh(x)-aO2
x))-(fp_sinh(x)/aO2
x))gC1
q0(1l
qP
I1
hJ
q0(1l)+gL+q0(3l)-h22*d01*q0(6l)/q0(3l
gC1
10l)/gL-q0(9l)%gL+(x+y-q0(11l)*x+z/q0(10l)+x/(z+q0(31l)qP
I2
hJ((fp_abs(x*y)<q0(20l))||(((x+y)>q0(30l))&&(z>d01)))?fp_min(x,gL*y):fp_max(y,z*q0(2l
qP
I3
hJ(x+y)+gL*(x-z
gC1
3l)*(x*y
gC1
4l)*(y/z
gC1
5l)*fp_mod(x,z
gC1
6l)*(x<y
gC1
7l)*(x<=z
gC1
8l)*(x>gL*z
gC1
9l)*(y>=q0(3l)*z
gC1
10l)*(x+y!=z
gC1
11l)*(q0(100l)+x
gC1
12l)*(q0(101l)-y
gC1
13l)*(q0(102l)*z
gC1
14l)*(q0(103l)/x);}
}
#define Value_t double
template<>const
TestType<q0>RegressionTests<q0>::Tests[]={Uj
Wj
Yj
Sk
Tk
Uk
Wk
Yk
Sl
Tl
Ul
Wl{2,-11,11,N(0.3)qM,qG
Mod,qG
Mod
dW",z"
g0"mod"
,"x%z"
}
,Yl
Sm
Tm
Um
Wm
Ym
Sn{1
d6
mL
Acos
qB
Acos
gG1"acos"
,"acos"
aV2
gB2
Acos_deg
qB
Acos_deg
gG1"acos_deg"
,"acos"
hA
1,400,mA
Acosh
qB
Acosh
gG1
q23,q23
hA
1,400,q92
Acosh_deg
qB
Acosh_deg
gG1"acosh_deg"
,q23
aV2
mL
Asin
qB
Asin
gG1"asin"
,"a"
gY3
d6
gB2
Asin_deg
qB
Asin_deg
gG1"asin_deg"
,"a"
gY3
d6
mL
Asinh
qB
Asinh
gG1"a"
oA2,"a"
oA2
aV2
gB2
Asinh_deg
qB
Asinh_deg
gG1"asinh_deg"
,"a"
oA2
hA
gF3
mA
Atan
qB
Atan
gG1"atan"
,"atan(x)"
}
,{gX3
dQ1
Atan2
qB
Atan2
mC2"/"
aH2,aH2"(x"
mF1{gX3
N(0.05)gF1
Atan2_deg
qB
Atan2_deg
mC2"/atan2_deg"
,aH2"(x"
mF1{1,gF3
q92
Atan_deg
qB
Atan_deg
gG1"atan_deg"
,"atan"
aV2
mL
Atanh
qB
Atanh
gG1"atanh"
,"atanh"
hA-50000,50000,1000
qM
qB
Cbrt
qB
Cbrt
gG1"cbrt"
,"cbrt"
hA-10,10,hA2
qB
Ceil
qB
Ceil
gG1"ceil"
,"ceil"
hA
dW2
Cos
qB
Cos
gG1"cos"
,"cos"
hA-mM
gF1
Cos_deg
qB
Cos_deg
gG1"cos_deg"
,"cos"
hA-140,140,mA
Cosh
qB
Cosh
gG1"cosh"
,"cosh"
hA-140,140,q92
Cosh_deg
qB
Cosh_deg
gG1"cosh_deg"
,"cosh"
hA-90,90,mL
Exp
qB
Exp
gG1"exp"
,"exp"
hA-90,90,mL
Exp2
qB
Exp2
gG1"exp2"
,"exp2"
hA-10,10,hA2
qB
Floor
qB
Floor
gG1"floor"
,"floor(x)"
}
,{gX3
dQ1
Hypot
qB
Hypot
mC2"/hypot"
,"hypot(x"
mF1
Tn
Un
SO1{1,N(1e-6),4000,mA
Log2
qB
Log2
gG1"log2"
,"log2"
hA
N(1e-6),4000,mA
Log10
qB
Log10
gG1"log10"
,"log10(x)"
}
,T4
U4{2,1,20,1
qM
qB
Pow_neg
qB
Pow_neg
mC2"/pow_neg"
,"pow(-x*0.25,y"
o02{2,N(0.01),4,dQ1
Pow_pos
qB
Pow_pos
mC2"/pow_pos"
,d12
mF1{1,dW2
Sin
qB
Sin,qH"/sin"
,gY3,-mM
gF1
Sin_deg
qB
Sin_deg,qH"/sin_deg"
,gY3,gF3
mA
Sinh
qB
Sinh,qH"/sinh"
,oA2
hA
gF3
q92
Sinh_deg
qB
Sinh_deg,qH"/sinh_deg"
,oA2
hA
0,100000,1000
qM
qB
Sqrt
qB
Sqrt
gG1"sqrt"
,"sqrt"
hA
N(-1.3),N(1.3),dQ1
Tan
qB
Tan
gG1"tan"
,"tan"
hA-89,89,N(0.25)gF1
Tan_deg
qB
Tan_deg
gG1"tan_deg"
,"tan"
hA
dW2
Tanh
qB
Tanh
gG1"tanh"
,"tanh"
hA-mM
gF1
Tanh_deg
qB
Tanh_deg
gG1"tanh_deg"
,"tanh"
hA-4000,4000,mA
Trunc
qB
Trunc
gG1"trunc"
,"trunc"
hA
0,1,1
qM,hG
E_d,hG
E_d
wT"e_d"
,dC3"naturalnumber"
hX1
L2_d,hG
L2_d
wT"l2_d"
,dC3"logtwo"
hX1
L10_d,hG
L10_d
wT"l10_d"
,dC3"logten"
hX1
Pi_d,hG
Pi_d
wT"pi_d"
,dC3"pi"
}
,W4
TO1
UO1
WO1
YO1
SP1
TP1
Wn
Y4
Yn
So
To
S5
T5
U5
W5{gC3
N(0.1)qM
q4
Absyxpow_neg
q4
Absyxpow_neg
wU"absyxpow_neg"
,"(x^-4)^1.5"
}
,{gC3
N(0.1)qM
q4
Absyxpow_pos
q4
Absyxpow_pos
wU"absyxpow_pos"
,"(x^4)^1.5"
}
,qK3
Acos
q4
Acos
wU"acos"
,"acos("
dM2,aW2
Acos_deg
q4
Acos_deg
wU"acos_deg"
,"acos("
dM2
qM
q4
Acosh
q4
Acosh
wU
q23,q23"("
wL
Acosh_deg
q4
Acosh_deg
wU"acosh_deg"
,q23"("
wM
Uo
Wo
UP1
WP1
Yo
Sp
YP1
qK3
Asin
q4
Asin
wU"asin"
,"asin("
dM2,aW2
Asin_deg
q4
Asin_deg
wU"asin_deg"
,"asin("
dM2
qM
q4
Asinh
q4
Asinh
wU"a"
oA2,"a"
oA2"("
wL
Asinh_deg
q4
Asinh_deg
wU"asinh_deg"
,"a"
oA2"("
wM
Tp
Up
qK3
Atan
q4
Atan
wU"atan"
,"atan"
m8
Atan2
q4
Atan2
wU
aH2,aH2"(5,4"
gH,aW2
Atan2_deg
q4
Atan2_deg
wU"atan2_deg"
,aH2"(5,4)+x"
}
,Wp{1,0,1,1,aW2
Atan_deg
q4
Atan_deg
wU"atan_deg"
,"atan"
m8
Atanh
q4
Atanh
wU"atanh"
,"atanh("
dM2
qM
q4
Cbrt
q4
Cbrt
wU"cbrt"
,"cbrt"
m8
Ceil
q4
Ceil
wU"ceil"
,"ceil("
wM
Yp
SQ1
TQ1
UQ1
WQ1
YQ1
SR1
TR1
UR1
WR1
YR1
SS1
TS1
US1
WS1
YS1
ST1
TT1
UT1
WT1
YT1
SU1
TU1
UU1
WU1
YU1
SV1
TV1
UV1
WV1
YV1
SW1
TW1
UW1
WW1
YW1
SX1
TX1
UX1
WX1
YX1
SY1
TY1
UY1
WY1
YY1
SZ1
TZ1
UZ1
WZ1
YZ1
Sa1
Ta1
qK3
Cos
q4
Cos
wU"cos"
,"cos("
wL
Cos_deg
q4
Cos_deg
wU"cos_deg"
,"cos"
m8
Cosh
q4
Cosh
wU"cosh"
,"cosh("
wL
Cosh_deg
q4
Cosh_deg
wU"cosh_deg"
,"cosh("
wM
Sq
Tq
Ua1
Wa1
Ya1
Y5
Uq
Wq
Yq
S6
T6
U6
W6
Sr
Sb1
Tb1
qK3
Exp
q4
Exp
wU"exp"
,"exp"
m8
Exp2
q4
Exp2
wU"exp2"
,"exp2("
wM
Tr
Ur{1,aH
Exp2xpow
q4
Exp2xpow
wU"exp2xpow"
,"exp2(x)"
dN2
Wr
Yr
Ss
Ts{1,aH
Expxpow
q4
Expxpow
wU"expxpow"
,aR
dN2
qK3
Floor
q4
Floor
wU"floor"
,"floor("
wM
Us
Ub1
Wb1
Yb1
Sc1
Tc1
Uc1
Wc1
Yc1
Sd1
Td1
Ud1
Wd1
Yd1
Se1
qK3
Hypot
q4
Hypot
wU"hypot"
,"hypot(5,4)+x"
}
,Te1
Ws
Ys
St
Tt
Ut
Wt
Yt
Y6
Ue1
qK3
Log
q4
Log
wU"log"
,"log"
m8
Log2
q4
Log2
wU"log2"
,"log2("
wM
We1
Ye1
qK3
Log10
q4
Log10
wU"log10"
,"log10("
wM
Sf1
Tf1
Uf1
Wf1
Yf1
Sg1
Tg1
S7
T7
Ug1
Wg1
Yg1
Sh1
U7
W7
Th1
qK3
Mulminus1
q4
Mulminus1
wU"mulminus1"
,"x*-1"
}
,Uh1
Wh1
qK3
Neg
q4
Neg
wU"neg"
,"((-((5))))+x"
}
,Y7
Yh1
Su
Si1
Ti1
S8
Tu
Ui1
T8
U8
Wi1
Yi1
W8
Sj1
Tj1
Uj1
Wj1
Yj1
Sk1
Y8
S9
T9
U9
W9
Y9
SA
TA
UA
Tk1
qK3
Pow_neg
q4
Pow_neg,dZ1"_neg"
,"pow(-0.25,4"
gH
qM
q4
Pow_pos
q4
Pow_pos,dZ1"_pos"
,"pow(1.1, 7.1)+x"
}
,Uu
Wu
Yu
Sv
Tv
Uv
Wv{1,aH
Powxpow
q4
Powxpow,0,q7"/powxpow"
,"(x^1.7)"
dN2
Yv
Sw{1,N(0.01),10,N(0.05)qM
q4
Rsqrt
q4
Rsqrt
wU"rsqrt"
,"1/sqrt"
hA
0,1,wB
Sin
q4
Sin,aK,"sin("
wL
Sin_deg
q4
Sin_deg,aK"_deg"
,"sin("
wM
Uk1
Wk1
Yk1
Sl1
Tl1
Ul1
Wl1
Yl1
Sm1
qK3
Sinh
q4
Sinh,aK"h"
,oA2"("
wL
Sinh_deg
q4
Sinh_deg,aK"h_deg"
,oA2"("
wM
WA
YA
SB
TB
UB
WB
Tm1
Tw
Uw
Ww
Um1{gC3
N(0.1)qM
q4
Sqrsqrt
q4
Sqrsqrt
wU"sqrsqrt"
,"sqrt"
d22
qK3
Sqrt
q4
Sqrt
wU"sqrt"
,"sqrt("
wM
Wm1
Ym1{1,aH
Sqrxpow
q4
Sqrxpow
wU"sqrxpow"
,"(x^2)^2402"
}
,{gC3
N(0.1)qM
q4
Sqrxpow_nonint
q4
Sqrxpow_nonint
wU"sqrxpow_nonint"
,"(x^2)^3.5"
}
,Sn1
Tn1
Un1
qK3
Tan
q4
Tan
wU"tan"
,"tan("
wL
Tan_deg
q4
Tan_deg
wU"tan_deg"
,"tan"
m8
Tanh
q4
Tanh
wU"tanh"
,"tanh("
wL
Tanh_deg
q4
Tanh_deg
wU"tanh_deg"
,"tanh"
m8
Trunc
q4
Trunc
wU"trunc"
,"trunc("
wM
YB
SC
Yw
Wn1
Yn1
So1
To1
Uo1
Wo1
TC
Sx
UC{1,0,10,N(0.01)qM
q4
Ypowxpow
q4
Ypowxpow
wU"ypowxpow"
,"(x^38.5)^5"
}
,Yo1
Sp1
Tp1
Up1
Wp1
Yp1
Sq1
Tq1
Uq1
Wq1
Yq1
Sr1
Tr1
Ur1
Wr1
Yr1
Ss1
Ts1
Us1
Ws1
Ys1
St1
Tt1
Ut1
Wt1
Yt1
Su1
Tu1
Uu1
Wu1
Yu1
Sv1
Tv1
Uv1
Wv1
Yv1
Sw1
Tw1
Uw1
Ww1
Yw1
Sx1
Tx1
Tx
Ux
Ux1
Wx1
WC
YC
Wx
Yx
SD
Sy
TD
UD
WD
Ty
Uy
Wy
YD
SE
TE
UE
WE
YE
SF
TF
UF
Yy
Sz
Tz
Uz
Wz
Yz
WF
YF
SG
TG
UG
WG
YG
SH
TH
S_
T_
U_
W_
Y_
S01
UH
WH
YH
SI
TI
UI
WI
YI
SJ
T01
U01
W01
Y01
S11
T11
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
U11
W11
Y11
S21
T21
U21
SL
TL
UL
WL
YL
SM
TM
UM
WM
W21
Y21
S31
T31
U31
W31
YM
SN
TN
UN
WN
YN
SO
TO
UO
Y31
S41
T41
U41
W41
Y41
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
S51
T51
U51
W51
Y51
S61
Yx1
Sy1
T61
U61
W61
Ty1
Uy1
UQ
WQ
YQ
SR
TR
UR
Wy1
Yy1
Sz1
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
TV
UV
WV
YV
SW
TW
UW
WW
Y61
S71
YW
T71
U71
W71
Y71
SX
S81
TX
T81
U81
W81
UX
WX
YX
SY
Y81
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Tz1
Yb
Sc
S91
T91
U91
W91
Y91
SA1
TA1
UA1
Tc
Uc
Wc
WA1
YA1
SB1
TB1
UB1
WB1
Uz1
Wz1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
YB1
SC1
TC1
UC1
WC1
YC1
SD1
TD1
UD1
WD1
YD1
SE1
TE1
Ye
Sf
Tf
Uf
Wf
Yf
UE1
Sg
Yz1
S_1
T_1
U_1
W_1
Y_1
Tg
WE1
YE1
SF1
TF1
Ug
UF1
WF1
YF1
SG1
TG1
UG1
WG1
YG1
SH1
TH1
UH1
WH1
YH1
SI1
Wg
Yg
TI1
Sh
Th
Uh
UI1
WI1
Wh
YI1
SJ1
TJ1
UJ1
Yh
WJ1
YJ1
SK1
TK1
Si
Ti
UK1
WK1
YK1
SL1
TL1
UL1
WL1
YL1
SM1
TM1
UM1
WM1
Ui
YM1
SN1
TN1
UN1
WN1
Wi
YN1
TestType<q0>()}
;
#undef Value_t
#undef N
#undef P
#ifdef FP_SUPPORT_COMPLEX_DOUBLE_TYPE
#define N(x,y) (q0(x,y))
#define Value_t std::complex<double>
namespace
cpp_02unit_functions
mE2
Cos_cd
qW
cos
wD1
Sin_cd
qW
sin(x);}
}
template<>const
TestType<q0>RegressionTests<q0>::Tests[]={S02
T02
U02
W02
Y02
S12
T12
U12
W12
Y12
S22
T22
U22
W22
Y22
S32
T32
U32
W32
Y32
S42
T42
U42
W42
Y42
S52
T52
U52{1,N(-dD3,+200.0),N(dD3,-200.0),N(5.0,-0.025)qM
qB
Cos_cd,dQ2"cos_cd"
,"cos(x)"
}
,W52
Y52
S62
T62
U62
W62
Y62{1,N(-dD3,+200.0),N(dD3,-200.0),N(5.0,-0.025)qM
qB
Sin_cd,dR2"_cd"
,q42}
,S72
T72
U72
W72
Y72
S82
T82
U82
W82
Y82
S92
T92
U92
W92
Y92
SA2
TA2
UA2
WA2
YA2
SB2
TB2
UB2
WB2
YB2
SC2
TC2
UC2
WC2
YC2
SD2
TD2
UD2
WD2
YD2
SE2
TE2
UE2
WE2
YE2
SF2
TF2
UF2
WF2
YF2
SG2
TG2
UG2
WG2
YG2
SH2
TH2
UH2
WH2
YH2
SI2
TI2
UI2
WI2
YI2
SJ2
TJ2
UJ2
WJ2
YJ2
SK2
TK2
UK2
WK2
YK2
SL2
TL2
UL2
WL2
YL2
SM2
TM2
UM2
WM2
YM2
SN2
TN2
UN2
WN2
YN2
SO2
TO2
UO2
WO2
YO2
SP2
TP2
UP2
WP2
YP2
SQ2
TQ2
UQ2
WQ2
YQ2
SR2
TR2
UR2
WR2
YR2
SS2
TS2
US2
WS2
YS2
ST2
TT2
UT2
WT2
YT2
SU2
TU2
UU2
WU2
YU2
SV2
TV2
UV2
WV2
YV2
SW2
TW2
UW2
WW2
YW2
SX2
TX2
UX2
WX2
YX2
SY2
TY2
UY2
WY2
YY2
SZ2
TZ2
UZ2
WZ2
YZ2
Sa2
Ta2
Ua2
Wa2
Ya2
Sb2
Tb2
Ub2
Wb2
Yb2
Sc2
Tc2
Uc2
Wc2
Yc2
Sd2
Td2
Ud2
Wd2
Yd2
Se2
Te2
Ue2
We2
Ye2
Sf2
Tf2
Uf2
Wf2
Yf2
Sg2
Tg2
Ug2
Wg2
Yg2
Sh2
Th2
Uh2
Wh2
Yh2
Si2
Ti2
Ui2
Wi2
Yi2
Sj2
Tj2
Uj2
Wj2
Yj2
Sk2
Tk2
Uk2
Wk2
Yk2
Sl2
Tl2
Ul2
Wl2
Yl2
Sm2
Tm2
Um2
Wm2
Ym2
Sn2
Tn2
Un2
Wn2
Yn2
So2
To2
Uo2
Wo2
Yo2
Sp2
Tp2
Up2
Wp2
Yp2
Sq2
Tq2
Uq2
Wq2
Yq2
Sr2
Tr2
Ur2
Wr2
Yr2
Ss2
Ts2
Us2
Ws2
Ys2
St2
Tt2
Ut2
Wt2
Yt2
Su2
Tu2
Uu2
Wu2
Yu2
Sv2
Tv2
Uv2
Wv2
Yv2
Sw2
Tw2
Uw2
Ww2
Yw2
Sx2
Tx2
Ux2
Wx2
Yx2
Sy2
Ty2
Uy2
Wy2
Yy2
Sz2
Tz2
Uz2
Wz2
Yz2
S_2
T_2
U_2
W_2
Y_2
S03
T03
U03
W03
Y03
S13
T13
U13
W13
TestType<q0>()}
;
#undef Value_t
#undef N
#endif /*FP_SUPPORT_COMPLEX_DOUBLE_TYPE */
#ifdef FP_SUPPORT_COMPLEX_FLOAT_TYPE
#define N(x,y) (q0(APP(x,f),APP(y,f)))
#define Value_t std::complex<float>
namespace
cpp_02unit_functions
mE2
Cos_cf
qW
cos
wD1
Sin_cf
qW
sin(x);}
}
template<>const
TestType<q0>RegressionTests<q0>::Tests[]={S02
T02
U02
W02
Y02
S12
T12
U12
W12
Y12
S22
T22
U22
W22
Y22
S32
T32
U32
W32
Y32
S42
T42
U42
W42
Y42
S52
T52
U52{1,N(-40.0,+0.5),N(40.0,-0.5),N(0.1,-0.00125)qM
qB
Cos_cf,dQ2"cos_cf"
,"cos(x)"
}
,W52
S62
T62
U62
W62
Y62{1,N(-40.0,+0.5),N(40.0,-0.5),N(0.1,-0.00125)qM
qB
Sin_cf,dR2"_cf"
,q42}
,S72
YF2
SG2
SH2
TH2
UH2
WH2
YH2
SI2
TI2
UI2
WI2
YI2
SJ2
TJ2
UJ2
WJ2
YJ2
SK2
TK2
UK2
WK2
YK2
SL2
TL2
UL2
WL2
YL2
SM2
TM2
UM2
WM2
YM2
SN2
TN2
UN2
WN2
YN2
SO2
TO2
UO2
WO2
YO2
SP2
TP2
UP2
WP2
YP2
SQ2
TQ2
UQ2
WQ2
YQ2
SR2
TR2
UR2
WR2
YR2
SS2
TS2
US2
WS2
YS2
ST2
TT2
UT2
WT2
YT2
SU2
TU2
UU2
WU2
YU2
SV2
TV2
UV2
WV2
YV2
SW2
TW2
UW2
WW2
YW2
SX2
TX2
UX2
WX2
YX2
SY2
TY2
UY2
WY2
YY2
SZ2
TZ2
UZ2
WZ2
YZ2
Sa2
Ta2
Ua2
Wa2
Ya2
Sb2
Tb2
Ub2
Wb2
Yb2
Sc2
Tc2
Uc2
Wc2
Yc2
Sd2
Td2
Ud2
Wd2
Yd2
Se2
Te2
Ue2
We2
Ye2
Sf2
Tf2
Uf2
Wf2
Yf2
Sg2
Tg2
Ug2
Wg2
Yg2
Sh2
Th2
Uh2
Wh2
Yh2
Si2
Ti2
Ui2
Wi2
Yi2
Sj2
Tj2
Uj2
Wj2
Yj2
Sk2
Tk2
Uk2
Wk2
Yk2
Sl2
Tl2
Ul2
Wl2
Yl2
Sm2
Tm2
Um2
Wm2
Ym2
Sn2
Tn2
Un2
Wn2
Yn2
So2
To2
Uo2
Wo2
Yo2
Sp2
Tp2
Up2
Wp2
Yp2
Sq2
Tq2
Uq2
Wq2
Yq2
Sr2
Tr2
Ur2
Wr2
Yr2
Ss2
Ts2
Us2
Ws2
Ys2
St2
Tt2
Ut2
Wt2
Yt2
Su2
Tu2
Uu2
Wu2
Yu2
Sv2
Tv2
Uv2
Wv2
Yv2
Sw2
Tw2
Uw2
Ww2
Yw2
Sx2
Tx2
Ux2
Wx2
Yx2
Sy2
Ty2
Uy2
Wy2
Yy2
Sz2
Tz2
Uz2
Wz2
Yz2
S_2
T_2
U_2
W_2
Y_2
S03
T03
U03
W03
Y03
S13
T13
U13
W13
TestType<q0>()}
;
#undef Value_t
#undef N
#endif /*FP_SUPPORT_COMPLEX_FLOAT_TYPE */
#ifdef FP_SUPPORT_COMPLEX_LONG_DOUBLE_TYPE
#define N(x,y) (q0(APP(x,l),APP(y,l)))
#define Value_t std::complex<long double>
template<>const
TestType<q0>RegressionTests<q0>::Tests[]={T02
W02
Y02
T12
U12
W12
Y12
S22
U22
W22
Y22
S32
U32
Y32
S42
T42
U42
Y42
T52
U52
W52
T62
U62
W62
Y62
YF2
SG2
SH2
TH2
UH2
WH2
YH2
SI2
TI2
UI2
WI2
YI2
SJ2
TJ2
UJ2
WJ2
YJ2
SK2
TK2
UK2
WK2
YK2
SL2
TL2
UL2
WL2
YL2
SM2
TM2
UM2
WM2
YM2
SN2
TN2
UN2
WN2
YN2
SO2
TO2
UO2
WO2
YO2
SP2
TP2
UP2
WP2
YP2
SQ2
TQ2
UQ2
WQ2
YQ2
SR2
TR2
UR2
WR2
YR2
SS2
TS2
US2
WS2
YS2
ST2
TT2
UT2
WT2
YT2
SU2
TU2
UU2
WU2
YU2
SV2
TV2
UV2
WV2
YV2
SW2
TW2
UW2
WW2
YW2
SX2
TX2
UX2
WX2
YX2
SY2
TY2
UY2
WY2
YY2
SZ2
TZ2
UZ2
WZ2
YZ2
Sa2
Ta2
Ua2
Wa2
Ya2
Sb2
Tb2
Ub2
Wb2
Yb2
Sc2
Tc2
Uc2
Wc2
Yc2
Sd2
Td2
Ud2
Wd2
Yd2
Se2
Te2
Ue2
We2
Ye2
Sf2
Tf2
Uf2
Wf2
Yf2
Sg2
Tg2
Ug2
Yg2
Sh2
Th2
Uh2
Wh2
Yh2
Si2
Ti2
Ui2
Wi2
Yi2
Sj2
Tj2
Uj2
Wj2
Yj2
Sk2
Tk2
Uk2
Wk2
Yk2
Sl2
Tl2
Ul2
Wl2
Yl2
Sm2
Tm2
Um2
Wm2
Ym2
Sn2
Tn2
Un2
Wn2
Yn2
So2
To2
Uo2
Wo2
Yo2
Sp2
Tp2
Up2
Wp2
Yp2
Sq2
Tq2
Uq2
Wq2
Yq2
Sr2
Tr2
Ur2
Wr2
Yr2
Ss2
Ts2
Us2
Ws2
Ys2
St2
Tt2
Wt2
Yt2
Su2
Tu2
Uu2
Wu2
Yu2
Sv2
Tv2
Uv2
Wv2
Yv2
Sw2
Tw2
Uw2
Ww2
Yw2
Sx2
Tx2
Ux2
Wx2
Yx2
Sy2
Ty2
Uy2
Wy2
Yy2
Sz2
Tz2
Uz2
Wz2
Yz2
S_2
T_2
U_2
W_2
Y_2
S03
T03
U03
W03
Y03
S13
T13
U13
W13
TestType<q0>()}
;
#undef Value_t
#undef N
#endif /*FP_SUPPORT_COMPLEX_LONG_DOUBLE_TYPE */
#ifdef FP_SUPPORT_FLOAT_TYPE
#define N(x) (APP(x,f))
#define P(x) N(x##.0)
#define Value_t float
namespace
cpp_01unit_operators
mE2
Modf(qD,&z
oR2
qA
fmodf(x,z
g43
cpp_02unit_functions
mE2
Acosf
qW
acosf
wD1
gD3
wF1
acosf(x
mD2
Acoshf
hW1
x+dO2-1.0f
mD2
g93
wF1
fp_acosh(x
mD2
Asinf
qW
asinf
wD1
gE3
wF1
asinf(x
mD2
Asinhf
hW1
x+dO2+1.0f
mD2
gI3
wF1
fp_asinh(x
mD2
Atan2f
qL
dP2
x,y);}
q0
Atan2f_deg
qL
r2d(dP2
x,y
mD2
Atanf
qW
atanf
wD1
Atanf_deg
wF1
atanf(x
mD2
Atanhf
hW1(1.0f+x)/(1.0f-x))*0.5f;}
q0
Cbrtf
qW
fp_cbrt
wD1
Ceilf
qW
ceilf
wD1
Cosf
qW
cosf
wD1
Cosf_deg
qW
cosf(g11
Coshf
qW
coshf
wD1
Coshf_deg
qW
coshf(g11
Exp2f
qW
expf(x*fp_const_log2<q0>(mD2
Expf
qW
expf
wD1
Floorf
qW
floorf
wD1
Hypotf
qL
dO2+y*y);}
q0
Log2f
hW1
x)*1.4426950408889634073599246810018921374266f;}
q0
Log10f
qW
log10f
wD1
Logf
hW1
x);}
q0
Pow_negf
qL
powf(-x*0.25f,y);}
q0
Pow_posf
qL
powf(x,y);}
q0
Sinf
qW
sinf
wD1
Sinf_deg
qW
sinf(g11
Sinhf
qW
sinhf
wD1
Sinhf_deg
qW
sinhf(g11
Sqrtf
qW
sqrtf
wD1
Tanf
qW
tanf
wD1
Tanf_deg
qW
tanf(g11
Tanhf
qW
tanhf
wD1
Tanhf_deg
qW
tanhf(g11
Truncf
qW
fp_trunc(x
g43
cpp_03unit_constants
mE2
E_f
qW
expf(x*0.0f+1.0f);}
q0
L2_f
hW1
x*0.0f+2.0f);}
q0
L10_f
hW1
x*0.0f+10.0f);}
q0
Pi_f
qW
dP2
x*0.0f,-1.0f
g43
cpp_10optimizer_bytecode
mE2
Acosf
qW
acosf(0.7f
d1
gD3
wF1
acosf(0.7f)d1
Acoshf
h92+sqrtf(1.1f*1.1f-1.0f)d1
g93
wF1
fp_acosh(1.1f)d1
Asinf
qW
asinf(0.7f
d1
gE3
wF1
asinf(0.7f)d1
Asinhf
h92+sqrtf(1.1f*1.1f+1.0f)d1
gI3
wF1
fp_asinh(1.1f)d1
Atan2f
qW
dP2
5.0f,g13
Atan2f_deg
wF1
dP2
5.0f,4.0f)d1
Atanf
qW
atanf
m11
Atanf_deg
wF1
atanf(1.1f)d1
Atanhf
hW1(1.0f+0.7f)/(1.0f-0.7f))*0.5f+x;}
q0
Cbrtf
qW
fp_cbrt
m11
Ceilf
qW
ceilf
m11
Cosf
qW
cosf
m11
Cosf_deg
qW
cosf(g21
Coshf
qW
coshf
m11
Coshf_deg
qW
coshf(g21
Exp2f
qW
expf(1.1f*0.693147180559945309417232121458176568075500134f
d1
Expf
qW
expf
m11
Floorf
qW
floorf
m11
Hypotf
qW
sqrtf(5.0f*5.0f+4.0f*g13
Log2f
h92)*1.4426950408889634073599246810018921374266f+x;}
q0
Log10f
qW
log10f
m11
Logf
h92
d1
Pow_negf
qW
powf(-0.25f,g13
Pow_posf
qW
powf(1.1f,7.1f
d1
Sinf
qW
sinf
m11
Sinf_deg
qW
sinf(g21
Sinhf
qW
sinhf
m11
Sinhf_deg
qW
sinhf(g21
Sqrtf
qW
sqrtf
m11
Tanf
qW
tanf
m11
Tanf_deg
qW
tanf(g21
Tanhf
qW
tanhf
m11
Tanhf_deg
qW
tanhf(g21
Truncf
qW
1.0f+x;}
}
template<>const
TestType<q0>RegressionTests<q0>::Tests[]={Uj
Wj
Yj
Sk
Tk
Uk
Wk
Yk
Sl
Tl
Ul
Wl{2,-11,11,N(0.3)qM,qG
Modf,0
dW",z"
g0"modf"
,"x%z"
}
,Yl
Sm
Tm
Um
Wm
Ym
Sn{1
d6
mL
Acosf,dQ2"acosf"
,"acos"
aV2
gB2
gD3,dQ2"acosf_deg"
,"acos"
hA
1,400,mA
Acoshf,dQ2"acoshf"
,q23
hA
1,400,q92
g93,dQ2"acoshf_deg"
,q23
aV2
mL
Asinf,dQ2"asinf"
,"a"
gY3
d6
gB2
gE3,dQ2"asinf_deg"
,"a"
gY3
d6
mL
Asinhf,dQ2"asinhf"
,"a"
oA2
aV2
gB2
gI3,dQ2"asinhf_deg"
,"a"
oA2"(x)"
}
,{gX3
dQ1
Atan2f,wR"/atan2f"
,aH2"(x"
mF1{gX3
N(0.05)gF1
Atan2f_deg,wR"/atan2f_deg"
,aH2"(x"
mF1{1,gF3
mA
Atanf,dQ2"atanf"
,"atan"
hA
gF3
q92
Atanf_deg,dQ2"atanf_deg"
,"atan"
aV2
mL
Atanhf,dQ2"atanhf"
,"atanh"
hA-50000,50000,1000
qM
qB
Cbrtf,dQ2"cbrtf"
,"cbrt"
hA-10,10,hA2
qB
Ceilf,dQ2"ceilf"
,"ceil"
hA
dW2
Cosf,dQ2"cosf"
,"cos"
hA
gF3
5
gF1
Cosf_deg,dQ2"cosf_deg"
,"cos"
hA
dM3
N(0.025)qM
qB
Coshf,dQ2"coshf"
,"cosh"
hA
dM3
q92
Coshf_deg,dQ2"coshf_deg"
,"cosh"
hA-90,90,mL
Exp2f,dQ2"exp2f"
,"exp2"
hA-20,20,mL
Expf,dQ2"expf"
,"exp"
hA-10,10,hA2
qB
Floorf,dQ2"floorf"
,"floor(x)"
}
,{gX3
dQ1
Hypotf,wR"/hypotf"
,"hypot(x"
mF1
Tn
Un{1,aZ
Log2f,dQ2"log2f"
,"log2"
hA
aZ
Log10f,dQ2"log10f"
,"log10"
hA
aZ
Logf,dQ2"logf"
mP1
T4
U4{2,1,20,1
qM
qB
Pow_negf,wR"/pow_negf"
,"pow(-x*0.25,y"
o02{2,N(0.01),4,dQ1
Pow_posf,wR"/pow_posf"
,d12
mF1{1,dW2
Sinf,dR2"f"
,gY3,gF3
5
gF1
Sinf_deg,dR2"f_deg"
,gY3,dM3
mA
Sinhf,dR2"hf"
,oA2
hA
gF3
q92
Sinhf_deg,dR2"hf_deg"
,oA2
hA
0,100000,1000
qM
qB
Sqrtf,dQ2"sqrtf"
,"sqrt"
hA
N(-1.3),N(1.3),dQ1
Tanf,dQ2"tanf"
,"tan"
hA-89,89,N(0.25)gF1
Tanf_deg,dQ2"tanf_deg"
,"tan"
hA
dW2
Tanhf,dQ2"tanhf"
,"tanh"
hA-mM
gF1
Tanhf_deg,dQ2"tanhf_deg"
,"tanh"
hA
gF3
mA
Truncf,dQ2"truncf"
,"trunc"
hA
0,1,1
qM,hG
E_f,oW"e_f"
,dC3"naturalnumber"
hX1
L2_f,oW"l2_f"
,dC3"logtwo"
hX1
L10_f,oW"l10_f"
,dC3"logten"
hX1
Pi_f,oW"pi_f"
,dC3"pi"
}
,W4
TO1
UO1
YO1
SP1
Wn
Y4
Yn
So
To
S5
W5
qK3
Acosf
d2"acosf"
,"acos("
dM2,aW2
gD3
d2"acosf_deg"
,"acos(0.7)+x"
}
,Uo
qK3
Acoshf
d2"acoshf"
,q23"("
wL
g93
d2"acoshf_deg"
,q23"("
wM
Wo
Yo
Sp
qK3
Asinf
d2"asinf"
,"asin("
dM2,aW2
gE3
d2"asinf_deg"
,"asin(0.7)+x"
}
,Tp
qK3
Asinhf
d2"asinhf"
,"a"
oA2"("
wL
gI3
d2"asinhf_deg"
,"a"
oA2"("
wM
Up
qK3
Atan2f
d2"atan2f"
,aH2"(5,4"
gH,aW2
Atan2f_deg
d2"atan2f_deg"
,aH2"(5,4)+x"
}
,Wp
qK3
Atanf
d2"atanf"
,"atan("
wL
Atanf_deg
d2"atanf_deg"
,"atan"
m8
Atanhf
d2"atanhf"
,"atanh("
dM2
qM
q4
Cbrtf
d2"cbrtf"
,"cbrt"
m8
Ceilf
d2"ceilf"
,"ceil("
wM
Yp
SQ1
TQ1
UQ1
WQ1
YQ1
SR1
TR1
UR1
WR1
YR1
SS1
TS1
US1
WS1
YS1
ST1
TT1
UT1
WT1
YT1
SU1
TU1
UU1
WU1
YU1
SV1
TV1
UV1
WV1
YV1
SW1
TW1
UW1
WW1
YW1
SX1
TX1
UX1
WX1
YX1
SY1
TY1
UY1
WY1
YY1
SZ1
qK3
Cosf
d2"cosf"
,"cos("
wL
Cosf_deg
d2"cosf_deg"
,"cos"
m8
Coshf
d2"coshf"
,"cosh("
wL
Coshf_deg
d2"coshf_deg"
,"cosh("
wM
Sq
Tq
Y5
Uq
Wq
Yq
S6
T6
U6
W6
Sr
Sb1
Tb1
Tr
qK3
Exp2f
d2"exp2f"
,"exp2("
wM
Ur
Wr
qK3
Expf
d2"expf"
,m62
wM
Yr
Ss
Ts
qK3
Floorf
d2"floorf"
,"floor("
wM
Us
Ub1
Wb1
Yb1
Sc1
Tc1
Uc1
Wc1
Yc1
Sd1
Td1
Ud1
Wd1
Yd1
Se1
qK3
Hypotf
d2"hypotf"
,"hypot(5,4)+x"
}
,Ws
Ys
St
Tt
Ut
Wt
Yt
Y6
Ue1
We1
Ye1
qK3
Log2f
d2"log2f"
,"log2"
m8
Log10f
d2"log10f"
,"log10("
wM
Sf1
Tf1
qK3
Logf
d2"logf"
,"log("
wM
Uf1
Wf1
Yf1
Sg1
Tg1
S7
T7
Sh1
U7
W7
Th1
Y7
Su
Si1
Ti1
S8
Tu
T8
U8
Wi1
Yi1
W8
Tj1
Uj1
Wj1
Yj1
Y8
S9
T9
U9
W9
Y9
SA
TA
UA
qK3
Pow_negf,0,dZ1"_negf"
,"pow(-0.25,4"
gH
qM
q4
Pow_posf,0,dZ1"_posf"
,"pow(1.1, 7.1)+x"
}
,Uu
Wu
Yu
Sv
Tv
Uv
Wv
Yv
Sw
Uk1
Wk1
Yk1
Sl1
Tl1
Ul1
Wl1
Yl1
Sm1
qK3
Sinf,0,aK"f"
,"sin("
wL
Sinf_deg,0,aK"f_deg"
,"sin(1.1"
gH
qM
q4
Sinhf,0,aK"hf"
,oA2"("
wL
Sinhf_deg,0,aK"hf_deg"
,oA2"("
wM
WA
YA
SB
TB
UB
WB
Tw
Uw
Ww
qK3
Sqrtf
d2"sqrtf"
,"sqrt("
wM
Wm1
Ym1
Un1
qK3
Tanf
d2"tanf"
,"tan("
wL
Tanf_deg
d2"tanf_deg"
,"tan"
m8
Tanhf
d2"tanhf"
,"tanh("
wL
Tanhf_deg
d2"tanhf_deg"
,"tanh"
m8
Truncf
d2"truncf"
,"trunc("
wM
YB
SC
Yw
Wn1
Yn1
So1
To1
Uo1
Wo1
TC
Sx
UC
Tx
Ux
Wx
Yx
SD
Sy
TD
UD
WD
Ty
Uy
Wy
YD
SE
TE
UE
WE
YE
SF
TF
UF
Yy
Sz
Tz
Uz
Wz
Yz
WF
YF
SG
TG
UG
WG
YG
SH
TH
S_
T_
U_
W_
Y_
S01
UH
WH
YH
SI
TI
UI
WI
YI
SJ
T01
U01
W01
Y01
S11
T11
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
U11
W11
Y11
S21
T21
U21
SL
TL
UL
WL
YL
SM
TM
UM
WM
W21
Y21
S31
T31
U31
W31
YM
SN
TN
UN
WN
YN
SO
TO
UO
Y31
S41
T41
U41
W41
Y41
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
S51
T51
U51
W51
Y51
S61
Yx1
Sy1
T61
U61
W61
Ty1
Uy1
UQ
WQ
YQ
SR
TR
UR
Wy1
Yy1
Sz1
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
TV
UV
WV
YV
SW
TW
UW
WW
Y61
S71
YW
T71
U71
W71
Y71
SX
S81
TX
T81
U81
W81
UX
WX
YX
SY
Y81
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Tz1
Yb
Sc
S91
T91
U91
W91
Y91
SA1
TA1
UA1
Tc
Uc
Wc
WA1
YA1
SB1
TB1
UB1
WB1
Uz1
Wz1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
YB1
SC1
TC1
UC1
WC1
YC1
SD1
TD1
UD1
WD1
YD1
SE1
TE1
Ye
Sf
Tf
Uf
Wf
Yf
UE1
S_1
Tg
WE1
YE1
SF1
TF1
Ug
UF1
WF1
YF1
SG1
TG1
UG1
WG1
YG1
SH1
TH1
UH1
WH1
YH1
SI1
Wg
Yg
TI1
Sh
Th
Uh
WI1
Wh
YI1
SJ1
TJ1
UJ1
Yh
WJ1
SK1
Si
Ti
UK1
WL1
YL1
SM1
TM1
UM1
WM1
Ui
YM1
SN1
TN1
UN1
WN1
Wi
YN1
TestType<q0>()}
;
#undef Value_t
#undef N
#undef P
#endif /*FP_SUPPORT_FLOAT_TYPE */
#ifdef FP_SUPPORT_GMP_INT_TYPE
#define P(x) (APP(x,l))
#define Value_t GmpInt
template<>const
TestType<q0>RegressionTests<q0>::Tests[]={S
T
U
W
Y
S1
T1
U1
W1
Y1
S2
T2
U2
W2
Y2
S3
T3
U3
W3
Y3
S4
T4
U4
W4
Y4
S5
T5
U5
W5
Y5
S6
T6
U6
W6
Y6
S7
T7
U7
W7
Y7
S8
T8
U8
W8
Y8
S9
T9
U9
W9
Y9
SA
TA
UA
WA
YA
SB
TB
UB
WB
YB
SC
TC
UC
WC
YC
SD
TD
UD
WD
YD
SE
TE
UE
WE
YE
SF
TF
UF
WF
YF
SG
TG
UG
WG
YG
SH
TH
UH
WH
YH
SI
TI
UI
WI
YI
SJ
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
SL
TL
UL
WL
YL
SM
TM
UM
WM
YM
SN
TN
UN
WN
YN
SO
TO
UO
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
UQ
WQ
YQ
SR
TR
UR
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
SV
TV
UV
WV
YV
SW
TW
UW
WW
YW
SX
TX
UX
WX
YX
SY
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Yb
Sc
Tc
Uc
Wc
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
Ye
Sf
Tf
Uf
Wf
Yf
Sg
Tg
Ug
Wg
Yg
Sh
Th
Uh
Wh
Yh
Si
Ti
Ui
Wi
Yi
Sj
Tj
TestType<q0>()}
;
#undef Value_t
#undef P
#endif /*FP_SUPPORT_GMP_INT_TYPE */
#ifdef FP_SUPPORT_LONG_DOUBLE_TYPE
#define N(x) (APP(x,l))
#define P(x) N(x##.0)
#define Value_t long double
namespace
cpp_01unit_operators
mE2
Modl(qD,&z
oR2
qA
fmodl(x,z
g43
cpp_02unit_functions
mE2
Acoshl
m0
x+dU2-1.0l
mD2
Acoshl_deg
wF1
fp_acosh(x
mD2
Acosl
qW
acosl
wD1
Acosl_deg
wF1
acosl(x
mD2
Asinhl
m0
x+dU2+1.0l
mD2
Asinhl_deg
wF1
fp_asinh(x
mD2
Asinl
qW
asinl
wD1
Asinl_deg
wF1
asinl(x
mD2
Atan2l
qL
dV2
x,y);}
q0
Atan2l_deg
qL
r2d(dV2
x,y
mD2
Atanhl
m0(1.0l+x)/(1.0l-x))*0.5l;}
q0
Atanl
qW
atanl
wD1
Atanl_deg
wF1
atanl(x
mD2
Cbrtl
qW
fp_cbrt
wD1
Ceill
qW
ceill
wD1
Coshl
qW
coshl
wD1
Coshl_deg
qW
coshl(g11
Cosl
qW
cosl
wD1
Cosl_deg
qW
cosl(g11
Exp2l
qW
expl(x*fp_const_log2<q0>(mD2
Expl
qW
expl
wD1
Floorl
qW
floorl
wD1
Hypotl
qL
dU2+y*y);}
q0
Log2l
m0
x)*1.4426950408889634073599246810018921374266l;}
q0
Log10l
qW
log10l
wD1
Logl
m0
x);}
q0
Pow_negl
qL
powl(-x*0.25l,y);}
q0
Pow_posl
qL
powl(x,y);}
q0
Sinhl
qW
sinhl
wD1
Sinhl_deg
qW
sinhl(g11
Sinl
qW
sinl
wD1
Sinl_deg
qW
sinl(g11
Sqrtl
qW
sqrtl
wD1
Tanhl
qW
tanhl
wD1
Tanhl_deg
qW
tanhl(g11
Tanl
qW
tanl
wD1
Tanl_deg
qW
tanl(g11
Truncl
qW
fp_trunc(x
g43
cpp_03unit_constants
mE2
E_ld
qW
expl(x*0.0l+1.0l);}
q0
L2_ld
m0
x*0.0l+2.0l);}
q0
L10_ld
m0
x*0.0l+10.0l);}
q0
Pi_ld
qW
dV2
x*0.0l,-1.0l
g43
cpp_10optimizer_bytecode
mE2
Acoshl
m0
1.1l+sqrtl(1.1l*1.1l-1.0l)d1
Acoshl_deg
wF1
fp_acosh(1.1l)d1
Acosl
qW
acosl(0.7l
d1
Acosl_deg
wF1
acosl(0.7l)d1
Asinhl
m0
1.1l+sqrtl(1.1l*1.1l+1.0l)d1
Asinhl_deg
wF1
fp_asinh(1.1l)d1
Asinl
qW
asinl(0.7l
d1
Asinl_deg
wF1
asinl(0.7l)d1
Atan2l
qW
dV2
5.0l,g23
Atan2l_deg
wF1
dV2
5.0l,4.0l)d1
Atanhl
m0(1.0l+0.7l)/(1.0l-0.7l))*0.5l+x;}
q0
Atanl
qW
atanl
wG1
Atanl_deg
wF1
atanl(1.1l)d1
Cbrtl
qW
fp_cbrt
wG1
Ceill
qW
ceill
wG1
Coshl
qW
coshl
wG1
Coshl_deg
qW
coshl(g31
Cosl
qW
cosl
wG1
Cosl_deg
qW
cosl(g31
Exp2l
qW
expl(1.1l*0.693147180559945309417232121458176568075500134l
d1
Expl
qW
expl
wG1
Floorl
qW
floorl
wG1
Hypotl
qW
sqrtl(5.0l*5.0l+4.0l*g23
Invsincostan
qL
x/m41
x/m51
x/qA2+x*m41
x*m51
x*qA2+1.0l/m41
1.0l/m51
1.0l/qA2+1.0l*m41
1.0l*m51
1.0l*qA2;}
q0
Log2l
m0
1.1l)*1.4426950408889634073599246810018921374266l+x;}
q0
Log10l
qW
log10l
wG1
Logl
m0
1.1l
d1
Pow_negl
qW
powl(-0.25l,g23
Pow_posl
qW
powl(1.1l,7.1l
d1
Sinhl
qW
sinhl
wG1
Sinhl_deg
qW
sinhl(g31
Sinl
qW
sinl
wG1
Sinl_deg
qW
sinl(g31
Sqrtl
qW
sqrtl
wG1
Tanhl
qW
tanhl
wG1
Tanhl_deg
qW
tanhl(g31
Tanl
qW
tanl
wG1
Tanl_deg
qW
tanl(g31
Truncl
qW
1.0l+x;}
}
template<>const
TestType<q0>RegressionTests<q0>::Tests[]={Uj
Wj
Yj
Sk
Tk
Uk
Wk
Yk
Sl
Tl
Ul
Wl{2,-11,11,N(0.3)qM,qG
Modl,0
dW",z"
g0"modl"
,"x%z"
}
,Yl
Sm
Tm
Um
Wm
Ym
Sn{1,1,400,mA
Acoshl,dQ2"acoshl"
,q23
hA
1,400,q92
Acoshl_deg,dQ2"acoshl_deg"
,q23
aV2
mL
Acosl,dQ2"acosl"
,"acos"
aV2
gB2
Acosl_deg,dQ2"acosl_deg"
,"acos"
aV2
mL
Asinhl,dQ2"asinhl"
,"a"
oA2
aV2
gB2
Asinhl_deg,dQ2"asinhl_deg"
,"a"
oA2
aV2
mL
Asinl,dQ2"asinl"
,"a"
gY3
d6
gB2
Asinl_deg,dQ2"asinl_deg"
,"a"
q42}
,{gX3
dQ1
Atan2l,wR"/atan2l"
,aH2"(x"
mF1{gX3
N(0.05)gF1
Atan2l_deg,wR"/atan2l_deg"
,aH2"(x"
mF1{1
d6
mL
Atanhl,dQ2"atanhl"
,"atanh"
hA
gF3
mA
Atanl,dQ2"atanl"
,"atan"
hA
gF3
q92
Atanl_deg,dQ2"atanl_deg"
,"atan"
hA-50000,50000,1000
qM
qB
Cbrtl,dQ2"cbrtl"
,"cbrt"
hA-10,10,hA2
qB
Ceill,dQ2"ceill"
,"ceil"
hA-140,140,mA
Coshl,dQ2"coshl"
,"cosh"
hA-140,140,q92
Coshl_deg,dQ2"coshl_deg"
,"cosh"
hA
dW2
Cosl,dQ2"cosl"
,"cos"
hA-mM
gF1
Cosl_deg,dQ2"cosl_deg"
,"cos"
hA-90,90,mL
Exp2l,dQ2"exp2l"
,"exp2"
hA-90,90,mL
Expl,dQ2"expl"
,"exp"
hA-10,10,hA2
qB
Floorl,dQ2"floorl"
,"floor(x)"
}
,{gX3
dQ1
Hypotl,wR"/hypotl"
,"hypot(x"
mF1
Tn
Un{1,aZ
Log2l,dQ2"log2l"
,"log2"
hA
aZ
Log10l,dQ2"log10l"
,"log10"
hA
aZ
Logl,dQ2"logl"
mP1
T4
U4{2,1,20,1
qM
qB
Pow_negl,wR"/pow_negl"
,"pow(-x*0.25,y"
o02{2,N(0.01),4,dQ1
Pow_posl,wR"/pow_posl"
,d12
mF1{1,gF3
mA
Sinhl,dR2"hl"
,oA2
hA
gF3
q92
Sinhl_deg,dR2"hl_deg"
,oA2
hA
dW2
Sinl,dR2"l"
,gY3,-mM
gF1
Sinl_deg,dR2"l_deg"
,gY3,0,100000,1000
qM
qB
Sqrtl,dQ2"sqrtl"
,"sqrt"
hA
dW2
Tanhl,dQ2"tanhl"
,"tanh"
hA-mM
gF1
Tanhl_deg,dQ2"tanhl_deg"
,"tanh"
hA
N(-1.3),N(1.3),dQ1
Tanl,dQ2"tanl"
,"tan"
hA-89,89,N(0.25)gF1
Tanl_deg,dQ2"tanl_deg"
,"tan"
hA
gF3
mA
Truncl,dQ2"truncl"
,"trunc"
hA
0,1,1
qM,hG
E_ld,oW"e_ld"
,dC3"naturalnumber"
hX1
L2_ld,oW"l2_ld"
,dC3"logtwo"
hX1
L10_ld,oW"l10_ld"
,dC3"logten"
hX1
Pi_ld,oW"pi_ld"
,dC3"pi"
}
,W4
YO1
SP1
Wn
Y4
Yn
So
To
S5
W5
Uo
qK3
Acoshl
d2"acoshl"
,q23"("
wL
Acoshl_deg
d2"acoshl_deg"
,q23"("
wM
Wo
qK3
Acosl
d2"acosl"
,"acos("
dM2,aW2
Acosl_deg
d2"acosl_deg"
,"acos(0.7)+x"
}
,Yo
Sp
Tp
qK3
Asinhl
d2"asinhl"
,"a"
oA2"("
wL
Asinhl_deg
d2"asinhl_deg"
,"a"
oA2"("
wM
Up
qK3
Asinl
d2"asinl"
,"asin("
dM2,aW2
Asinl_deg
d2"asinl_deg"
,"asin("
dM2
qM
q4
Atan2l
d2"atan2l"
,aH2"(5,4"
gH,aW2
Atan2l_deg
d2"atan2l_deg"
,aH2"(5,4)+x"
}
,Wp
qK3
Atanhl
d2"atanhl"
,"atanh("
dM2
qM
q4
Atanl
d2"atanl"
,"atan("
wL
Atanl_deg
d2"atanl_deg"
,"atan"
m8
Cbrtl
d2"cbrtl"
,"cbrt"
m8
Ceill
d2"ceill"
,"ceil("
wM
Yp
SQ1
TQ1
UQ1
WQ1
YQ1
SR1
TR1
UR1
WR1
YR1
SS1
TS1
US1
WS1
YS1
ST1
TT1
UT1
WT1
YT1
SU1
TU1
UU1
WU1
YU1
SV1
TV1
UV1
WV1
YV1
SW1
TW1
UW1
WW1
YW1
SX1
TX1
UX1
WX1
YX1
SY1
TY1
UY1
WY1
YY1
SZ1
qK3
Coshl
d2"coshl"
,"cosh("
wL
Coshl_deg
d2"coshl_deg"
,"cosh"
m8
Cosl
d2"cosl"
,"cos("
wL
Cosl_deg
d2"cosl_deg"
,"cos("
wM
Sq
Tq
Y5
Uq
Wq
Yq
S6
T6
U6
W6
Sr
Sb1
Tb1
Tr
qK3
Exp2l
d2"exp2l"
,"exp2("
wM
Ur
Wr
qK3
Expl
d2"expl"
,m62
wM
Yr
Ss
Ts
qK3
Floorl
d2"floorl"
,"floor("
wM
Us
Ub1
Wb1
Yb1
Sc1
Tc1
Uc1
Yc1
Sd1
Td1
Ud1
Wd1
Yd1
qK3
Hypotl
d2"hypotl"
,"hypot(5,4)+x"
}
,Ws
Ys
St
Tt
Ut
Wt
Yt
Y6{2,N(-0.7),N(0.7),N(0.28)qM
q4
Invsincostan,0
dW
gR"invsincostan"
,"x/sin("
wP1"cos("
wP1"tan("
wP1"csc("
wP1"sec("
wP1"cot(y) +  1/sin(y)"
q73"cos(y)"
q73"tan(y)"
q73"csc(y)"
q73"sec(y)"
q73"cot(y"
o02
qK3
Log2l
d2"log2l"
,"log2"
m8
Log10l
d2"log10l"
,"log10"
m8
Logl
d2"logl"
,"log("
wM
Uf1
Wf1
Yf1
S7
T7
U7
W7
Y7
Su
S8
Tu
T8
U8
W8
Wj1
Yj1
Y8
S9
T9
U9
W9
Y9
SA
TA
UA
qK3
Pow_negl,0,dZ1"_negl"
,"pow(-0.25,4"
gH
qM
q4
Pow_posl,0,dZ1"_posl"
,"pow(1.1, 7.1)+x"
}
,Uu
Wu
Yu
Sv
Tv
Uv
Wv
Yv
Sw
Uk1
Wk1
Yk1
Sl1
Tl1
Ul1
Wl1
Yl1
Sm1
qK3
Sinhl,0,aK"hl"
,oA2"("
wL
Sinhl_deg,0,aK"hl_deg"
,oA2
m8
Sinl,0,aK"l"
,"sin("
wL
Sinl_deg,0,aK"l_deg"
,"sin("
wM
WA
YA
SB
TB
UB
WB
Tw
Uw
Ww
qK3
Sqrtl
d2"sqrtl"
,"sqrt("
wM
Un1
qK3
Tanhl
d2"tanhl"
,"tanh("
wL
Tanhl_deg
d2"tanhl_deg"
,"tanh"
m8
Tanl
d2"tanl"
,"tan("
wL
Tanl_deg
d2"tanl_deg"
,"tan"
m8
Truncl
d2"truncl"
,"trunc("
wM
YB
SC
Yw
Uo1
Wo1
TC
Sx
UC
Tx
Ux
Wx
Yx
SD
Sy
TD
UD
WD
Ty
Uy
Wy
YD
SE
TE
UE
WE
YE
SF
TF
UF
Yy
Sz
Tz
Uz
Wz
Yz
WF
YF
SG
TG
UG
WG
YG
SH
TH
S_
T_
U_
W_
Y_
S01
UH
WH
YH
SI
TI
UI
WI
YI
SJ
T01
U01
W01
Y01
S11
T11
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
U11
W11
Y11
S21
T21
U21
SL
TL
UL
WL
YL
SM
TM
UM
WM
W21
Y21
S31
T31
U31
W31
YM
SN
TN
UN
WN
YN
SO
TO
UO
Y31
S41
T41
U41
W41
Y41
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
S51
T51
U51
W51
Y51
S61
Yx1
Sy1
T61
U61
W61
Ty1
Uy1
UQ
WQ
YQ
SR
TR
UR
Yy1
Sz1
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
TV
UV
WV
YV
SW
TW
UW
WW
Y61
S71
YW
T71
U71
W71
Y71
SX
S81
TX
T81
U81
W81
UX
WX
YX
SY
Y81
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Yb
Sc
S91
T91
U91
W91
Y91
SA1
TA1
UA1
Tc
Uc
Wc
WA1
YA1
SB1
TB1
UB1
WB1
Uz1
Wz1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
YB1
SC1
TC1
UC1
WC1
YC1
SD1
TD1
UD1
WD1
YD1
SE1
TE1
Ye
Sf
Tf
Uf
Wf
Yf
UE1
Tg
WE1
YE1
SF1
TF1
Ug
UF1
WF1
YF1
SG1
TG1
UG1
WG1
YG1
SH1
TH1
UH1
WH1
YH1
SI1
Wg
Yg
TI1
Sh
Th
Uh
UI1
WI1
Wh
YI1
SJ1
TJ1
UJ1
Yh
WJ1
YJ1
SK1
TK1
Si
Ti
UK1
WK1
YK1
SL1
TL1
UL1
WL1
YL1
SM1
TM1
UM1
WM1
Ui
YM1
SN1
TN1
UN1
WN1
Wi
YN1
TestType<q0>()}
;
#undef Value_t
#undef N
#undef P
#endif /*FP_SUPPORT_LONG_DOUBLE_TYPE */
#ifdef FP_SUPPORT_LONG_INT_TYPE
#define P(x) (APP(x,l))
#define Value_t long
template<>const
TestType<q0>RegressionTests<q0>::Tests[]={S
T
U
W
Y
S1
T1
U1
W1
Y1
S2
T2
U2
W2
Y2
S3
T3
U3
W3
Y3
S4
T4
U4
W4
WO1
TP1
Y4
S5
T5
U5
W5
UP1
WP1
YP1
UQ1
UU1
WU1
YU1
UY1
WY1
TZ1
UZ1
WZ1
YZ1
Sa1
Ta1
Ua1
Wa1
Ya1
Y5
S6
T6
U6
W6
Sb1
Tb1
Ub1
Sc1
Yc1
Ud1
Te1
Y6
Sg1
S7
T7
Ug1
Wg1
Yg1
U7
W7
Uh1
Wh1
Y7
Yh1
S8
Ui1
T8
U8
W8
Sj1
Wj1
Yj1
Sk1
Y8
S9
T9
U9
W9
Y9
SA
TA
UA
Tk1
WA
YA
SB
TB
UB
WB
Tm1
Um1
Sn1
Tn1
Un1
YB
SC
TC
UC
Yo1
Sp1
Tp1
Up1
Wp1
Yp1
Sq1
Tq1
Uq1
Wq1
Yq1
Sr1
Tr1
Ur1
Wr1
Yr1
Ss1
Ts1
Us1
Ws1
Ys1
St1
Tt1
Ut1
Wt1
Yt1
Su1
Tu1
Uu1
Wu1
Yu1
Sv1
Tv1
Uv1
Wv1
Yv1
Sw1
Tw1
Uw1
Ww1
Yw1
Sx1
Tx1
Ux1
Wx1
WC
YC
SD
TD
UD
WD
YD
SE
TE
UE
WE
YE
SF
TF
UF
WF
YF
SG
TG
UG
WG
YG
SH
TH
UH
WH
YH
SI
TI
UI
WI
YI
SJ
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
SL
TL
UL
WL
YL
SM
TM
UM
WM
YM
SN
TN
UN
WN
YN
SO
TO
UO
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
Yx1
Sy1
Ty1
Uy1
UQ
WQ
YQ
SR
TR
UR
Yy1
Sz1
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
SV
TV
UV
WV
YV
SW
TW
UW
WW
YW
SX
TX
UX
WX
YX
SY
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Yb
Sc
Tc
Uc
Wc
Uz1
Wz1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
Ye
Sf
Tf
Uf
Wf
Yf
Sg
Yz1
T_1
U_1
W_1
Y_1
Tg
Ug
Wg
Yg
Sh
Th
Uh
Wh
Yh
Si
Ti
Ui
Wi
Yi
Sj
Tj
TestType<q0>()}
;
#undef Value_t
#undef P
#endif /*FP_SUPPORT_LONG_INT_TYPE */
#ifdef FP_SUPPORT_MPFR_FLOAT_TYPE
#define N(x) (q0(#x,0))
#define P(x) N(x)
#define Value_t MpfrFloat
static
gC2
wH1("0.5"
,0),mF2("0.25"
,0),mflit1_1("1.1"
,0),mflit0_7("0.7"
,0),mflit1_6("1.6"
,0),mflit1_5("1.5"
,0),mflitm1_1("-1.1"
,0),mflitm1_6("-1.6"
,0),mflitm1_5("-1.5"
,0),mflitm0_25("-0.25"
,0),mK2("7.1"
,0),mflit0_015625("0.015625"
,0),mflit0_0625("0.0625"
,0),mflit5_0625("5.0625"
,0),mflit1_2("1.2"
,0),mflitm5_1("-5.1"
,0),mflitm7_1("-7.1"
,0),mflit5_1("5.1"
,0),mflit_5(".5"
,0),mflit3_1("3.1"
,0),mflit4e2("4e2"
,0),mflit3_5("3.5"
,0),mflit57_295779513082320877("57.295779513082320877"
,0),mflit0_2("0.2"
,0),mflit7_5("7.5"
,0),m22("2.5"
,0),mflit1_3("1.3"
,0),mflit1_4("1.4"
,0),mflit1_7("1.7"
,0),mflit1_8("1.8"
,0),mflit1_25("1.25"
,0),mflit1_75("1.75"
,0),mflit2_25("2.25"
,0),mflit3_3("3.3"
,0),mflit0_6("0.6"
,0),mflit2_1("2.1"
,0),mflit1_75e21("1.75e21"
,0);namespace
cpp_01unit_operators
mE2
And_d
qL
oJ1>=wH1?fp_abs(y)>=wH1:q0(0
mD2
Div_d
qL(x-mF2)/y;}
q0
Divmul_d
hJ
x*y*x*x/z*(x-mF2);}
q0
Modm(qD,&z
oR2
qA
x%z;}
q0
Not_d
qW
oJ1<mJ2
Notnot_d
qW
oJ1>=mJ2
Or_d
qL
oJ1<wH1?fp_abs(y)>=wH1:m02;}
}
namespace
cpp_02unit_functions
mE2
Acoshm(qV
acosh
wD1
Acoshm_deg
oI1::acosh(x
mD2
Acosm(qV
acos
wD1
Acosm_deg
oI1::acos(x
mD2
Asinhm(qV
asinh
wD1
Asinhm_deg
oI1::asinh(x
mD2
Asinm(qV
asin
wD1
Asinm_deg
oI1::asin(x
mD2
Atan2m
qL
q0::atan2(x,y);}
q0
Atan2m_deg
qL
r2d(q0::atan2(x,y
mD2
Atanhm(qV
atanh
wD1
Atanm(qV
atan
wD1
Atanm_deg
oI1::atan(x
mD2
Cbrtm(qV
cbrt
wD1
Ceilm(qV
ceil
wD1
Coshm(qV
cosh
wD1
Coshm_deg(qV
cosh(g11
Cosm(qV
cos
wD1
Cosm_deg(qV
cos(g11
Exp2m(qV
exp2
wD1
Expm(qV
exp
wD1
Floorm(qV
floor
wD1
Hypotm
qL
q0::hypot(x,y);}
q0
If_d
hJ
fp_abs(x)>=wH1?y:z;}
q0
Int
qW
fp_floor(x+mJ2
Log2m(qV
log2
wD1
Log10m(qV
log10
wD1
Logm(qV
log
wD1
Pow_negm
qL
q0::pow(-x*mF2,y);}
q0
Pow_posm
qL
q0::pow(x,y);}
q0
Sinhm(qV
sinh
wD1
Sinhm_deg(qV
sinh(g11
Sinm(qV
sin
wD1
Sinm_deg(qV
sin(g11
Sqrtm(qV
sqrt
wD1
Tanhm(qV
tanh
wD1
Tanhm_deg(qV
tanh(g11
Tanm(qV
tan
wD1
Tanm_deg(qV
tan(g11
Truncm(qV
trunc(x
g43
cpp_03unit_constants
mE2
E_mpfr(qV
exp(x
mG2
1
mD2
L2_mpfr(qV
log(x
mG2
2
mD2
L10_mpfr(qV
log(x
mG2
10
mD2
Pi_mpfr(qV
atan2(x*q0(0),-m02;}
}
namespace
cpp_10optimizer_bytecode
mE2
Acoshm(qV
acosh(gV
Acoshm_deg
oI1::acosh(wW
Acosm(qV
acos(mW1
Acosm_deg
oI1::acos(mflit0_7)d1
Asinhm(qV
asinh(gV
Asinhm_deg
oI1::asinh(wW
Asinm(qV
asin(mW1
Asinm_deg
oI1::asin(mflit0_7)d1
Atan2m(qV
atan2(q0(aX2
d1
Atan2m_deg
oI1::atan2(q0(aX2)d1
Atanhm(qV
atanh(mW1
Atanm(qV
atan(gV
Atanm_deg
oI1::atan(wW
Cbrtm(qV
cbrt(gV
Ceilm(qV
ceil(gV
Coshm(qV
cosh(gV
Coshm_deg(qV
cosh(aY2
Cosm(qV
cos(gV
Cosm_deg(qV
cos(aY2
Exp2m(qV
exp2(gV
Expm(qV
exp(gV
Floorm(qV
floor(gV
Hypotm(qV
hypot(q0(aX2
d1
Int
qW
x+(((((fp_int(mflit1_1)qB2
mflit1_6))qB2
mflit1_5))qB2
mflitm1_1))qB2
mflitm1_6))qB2
mflitm1_5
mD2
Log2m(qV
log2(gV
Log10m(qV
log10(gV
Logm(qV
log(gV
Pow_negm(qV
pow(mflitm0_25,q0(4)d1
Pow_posm(qV
pow(mflit1_1,mK2
d1
Powhalf
qW
qO
mJ2
Powminushalf
qW
qO-mJ2
Sinhm(qV
sinh(gV
Sinhm_deg(qV
sinh(aY2
Sinm(qV
sin(gV
Sinm_deg(qV
sin(aY2
Sqrtm(qV
sqrt(gV
Tanhm(qV
tanh(gV
Tanhm_deg(qV
tanh(aY2
Tanm(qV
tan(gV
Tanm_deg(qV
tan(aY2
Truncm
qW
q0(1)+x;}
}
namespace
cpp_20optimizer_optimizations
mE2
Cmpeq_pow_imm_negneg
qW
fp_equal(mH2
Cmpeq_pow_imm_negpos
qW
fp_equal(qO
oN2
Cmpeq_pow_imm_pospos_base
qW
fp_equal(oQ2
Cmpge_pow_imm_negneg
aV
mH2
Cmpge_pow_imm_negpos
aV
qO
oN2
Cmpge_pow_imm_pospos_base
aV
oQ2
Cmpgt_pow_imm_negneg
qW
g01
mH2
Cmpgt_pow_imm_negpos
qW
g01
qO
oN2
Cmpgt_pow_imm_pospos_base
qW
g01
oQ2
Cmple_pow_imm_negneg
qW
dN1
mH2
Cmple_pow_imm_negpos
qW
dN1
qO
oN2
Cmple_pow_imm_pospos_base
qW
dN1
oQ2
Cmplt_pow_imm_negneg
qC2
mH2
Cmplt_pow_imm_negpos
qC2
qO
oN2
Cmplt_pow_imm_pospos_base
qC2
oQ2
Cmpne_pow_imm_negneg
dO1
mH2
Cmpne_pow_imm_negpos
dO1
qO
oN2
Cmpne_pow_imm_pospos_base
dO1
oQ2
Cmpzz_pow_imm_negneg
dX2
gM
aO
gM
m1
gM
m2
gM
m6
gM
mN
mH2
Cmpzz_pow_imm_negpos
dX2
qO
h0
aO
qO
h0
m1
qO
h0
m2
qO
h0
m6
qO
h0
mN
qO
oN2
Cmpzz_pow_imm_pospos_base
dX2
gN
aO
gN
m1
gN
m2
gN
m6
gN
mN
oQ2
Ifabsnot
hJ
fp_truth
q41!=q0(0)?z:y;}
q0
Posnot
qW
fp_not
q41;}
q0
Posnotnot
qW
fp_notNot
q41;}
q0
Powmulimm_fnen
wZ(q0(-8)mD2
Powmulimm_fnep
wZ(q0(4)mD2
Powmulimm_fnfn
qW
fp_pow((mflitm5_1)*x,(mflitm7_1
mD2
Powmulimm_fnfp
wZ
mK2);}
q0
Powmulimm_fpfp
qL
fp_pow(mflit5_1*x*y,mK2
g43
cpp_50regressions
mE2
t42
qL
h32
x*x)+dY2(fp_pow(y*y,mF2))+fp_hypot(x,y
g43
cpp_99misc
mE2
t2
qW
q0(2)*x+aY1)/mflit_5+q0(2)-aY1)*fp_sin
wD1
t3
hJ
fp_and(m31),fp_equal(y,x)gC1
1
gC1
2)-mflit3_1*mflit4e2/mflit_5+x*x+y*y+z*z+fp_and(x,x)+fp_or(y,y);}
q0
t9
hJ
mflit1_5+x*y-q0(2
gC1
4)/q0(8)+z+z+z+z+x/(y*z);}
q0
t11
hJ(-x-x)+y+hP
fp_pow(mflit1_1,z
mD2
t22
qL(mflit3_5*q0(2)gC1
10)*(x*q0(3))-(fp_sin(y)*q0(2)gC1
100)*((x
aZ2-(y*q0(3)))*q0(2
gC1
5)/(q0(2)aZ2+fp_pow(mflit1_1,x
aZ2+fp_pow(dZ2
q0(2),x
aZ2;}
q0
t26_deg
qW
fp_sin(d2r(x))+gH3
d2r(x*mflit1_5))+r2d(fp_asin(x/q0(110)))+r2d(gB1/q0(120)mD2
t30
qL
x-y*q0(1)+fp_mod(x,y)+x/fp_pow(y,mflit1_1)+qI
2),q0(3))+fp_mod(q0(5),q0(3))+qO
fp_pow(y,q0(0)))+qO
mJ2
t32
hJ
x+y/y-fp_min(q0(3),q0(4))-x-g92
4),q0(3))+g92
3),q0(4))-fp_min(q0(4),q0(3)gC1
0)+(z*m02+(x-q0(2
gC1
2))+(x*wH1
aZ2+y*q0(0)+fp_min(fp_min(fp_min(q0(4),x),m02,fp_min(x,fp_min(fp_min(y,q0(4)),z)))+fp_max(fp_max(g92
4),x),m02,fp_max
gH2
fp_max(y,q0(4)),z)))+(fp_abs
oO2
fp_acos
oO2
fp_asin
oO2
fp_atan
oO2
fp_ceil(mflit1_1)+gH3
m12
aO2
m12
fp_floor(mflit1_1)+hP
m02+fp_sin(m12
fp_sinh(m12
dD2
m02+fp_tanh
oO2
q82
q0(1),m02)+(x-(y-z))+(x+y)+(x*y)+fp_max
gH2
x,fp_max
gH2
x,x))))*-q0(1)+(z-z
gC1
1)/aY1/oM1
gG3/oM1
dD2
z/q0(5))+gU
q0(1)/dD2
z/oM1
fp_sin(y/oM1
mB/q0(5)))+hP
q0(30)+x)*hP
q0(40)+y)/hP
q0(50)+z
a2/mflit57_295779513082320877)+fp_asin(x/q0(10))*mflit57_295779513082320877+fp_floor(-x
gC1
1)/fp_ceil(x)+h32
q0(5)*mflit0_2)+(-x+-x+-x+-x+-x+-x);}
q0
t37
qW
q0(5)+mflit7_5*q0(8)/q0(3)-qI
2),q0(4))*q0(2)+fp_mod(q0(7),q0(2)gC1
4
d1
t38
hJ
fp_asinh(x)+dY2
fp_acosh(y+q0(3))+m22*fp_atanh(z);}
q0
t39
hJ
aY1+g41)-mB+fp_sin(y*mflit1_5))+z*z*z
aT2
z*z*z-x*x-y*y)-g41*aY1+g41)+x*y*z+x*y*m22+x*y*z*mB)+x*y*mB)+x*z*mB)+y*z*m22+(x*y*z*mB)-x*y*z-y*mB)-x*z*y+x*y+x*z-mB)*x);}
q0
t44
qW
oG1
w7
8))+dZ2
oG1*x
w7
7))m61
oG1
oP2
6))+mflit1_3*oH1
w7
5))+mflit1_4*oH1*x
w7
6))+dY2
oH1
oP2
4))+mflit1_6*oH1*x
oP2
3))+mflit1_7*oH1*x*x
oP2
2))+mflit1_8*(h32
fp_pow(fp_abs(-h32
x)),q0(3))mD2
t45
qW
oG1
w7
7))+dZ2
oG1
oP2
5))m61
oH1*x
w7
3
mD2
t46
qL
fp_abs(fp_floor(gB1
gC1
4)))+dZ2
fp_abs(fp_floor(fp_acos(y)+mflit1_5))dL2
gB1),(fp_acos(y)-q0(10)))m61
g92-4),gB1))+mflit1_3*fp_min(q0(9),gB1)-q0(9
mD2
t47
qL
mflit1_25*dH2
x)+fp_exp(-x))+dY2
dH2
y)-fp_exp(-y))+mflit1_75*(dH2-x)+gO3))/q0(2)gC1
2)*(dH2-x)-gO3))/q0(2))+mflit2_25*(aO2
y)+fp_sinh(y
mD2
t48
qW
fp_sinh((hP
x)/q0(5
gC1
1))*q0(5))m61
aO2(hP
x)/hP
q0(2)gC1
1))*hP
q0(2)))aU2
fp_or
mE
x),fp_not(x/q0(4))mD2
t49
qW
q82
q0(0),x)+qI-4)*(x-q0(100)),mflit3_3);}
q0
t52
qW
x+(q0(1
gC1
2
gC1
3
gC1
4)-q0(5)-q0(6)-q0(7)-q0(8))/q0(3
gC1
4)*(q0(1)+fp_sin(q0(2))+gH3
q0(4)*q0(5
gC1
6))/q0(2))+gH3
wH1)*dD2
mflit0_6+mflit0_2)-mflit1_1/hP
mflit2_1)*h32
mflit3_3)+qI
2),q0(3
mD2
t55
qL
fp_less(qO
mflit1_2),q0(0))dL2
fp_pow(y,m22),q0(0)gC1
2)*aX*x,q0(0)gC1
3)*fp_less(fp_pow(y,q0(3)),q0(0)gC1
4)*fp_less(qO
q0(4)),q0(0
mD2
t56
qW
fp_mod(mflit1_75e21,x);}
}
template<>const
TestType<q0>RegressionTests<q0>::Tests[]={Uj
Wj
Yj
Sk
Tk
Uk
Wk
Yk
Sl
Tl
Ul
Wl{2,-11,11,N(0.3)qM,qG
Modm,0
dW",z"
g0"modm"
,"x%z"
}
,Yl
Sm
Tm
Um
Wm
Ym
Sn{1,1,400,mA
Acoshm,dQ2"acoshm"
,q23
hA
1,400,q92
Acoshm_deg,dQ2"acoshm_deg"
,q23
aV2
mL
Acosm,dQ2"acosm"
,"acos"
aV2
gB2
Acosm_deg,dQ2"acosm_deg"
,"acos"
aV2
mL
Asinhm,dQ2"asinhm"
,"a"
oA2
aV2
gB2
Asinhm_deg,dQ2"asin"
qM3"a"
oA2
aV2
mL
Asinm,dQ2"asinm"
,"a"
gY3
d6
gB2
Asinm_deg,dQ2"asin"
qN3"a"
q42}
,{gX3
N(0.15)qM
qB
Atan2m,wR"/atan2m"
,aH2"(x"
mF1{gX3
N(0.15)gF1
Atan2m_deg,wR"/atan2m_deg"
,aH2"(x"
mF1{1
d6
mL
Atanhm,dQ2"atanhm"
,"atanh"
hA
gF3
mA
Atanm,dQ2"atanm"
,"atan"
hA
gF3
q92
Atanm_deg,dQ2"atanm_deg"
,"atan"
hA-50000,50000,1000
qM
qB
Cbrtm,dQ2"cbrtm"
,"cbrt"
hA-10,10,hA2
qB
Ceilm,dQ2"ceilm"
,"ceil"
hA-140,140,mA
Coshm,dQ2"coshm"
,"cosh"
hA-140,140,q92
Coshm_deg,dQ2"coshm_deg"
,"cosh"
hA
dW2
Cosm,dQ2"cosm"
,"cos"
hA-mM
gF1
Cosm_deg,dQ2"cosm_deg"
,"cos"
hA-90,90,N(0.02)qM
qB
Exp2m,dQ2"exp2m"
,"exp2"
hA-90,90,N(0.02)qM
qB
Expm,dQ2"expm"
,"exp"
hA-10,10,hA2
qB
Floorm,dQ2"floorm"
,"floor(x)"
}
,{gX3
dQ1
Hypotm,wR"/hypotm"
,"hypot(x"
mF1
Tn
Un{1,aZ
Log2m,dQ2"log2m"
,"log2"
hA
aZ
Log10m,dQ2"log10m"
,"log10"
hA
aZ
Logm,dQ2"logm"
mP1
T4
U4{2,1,20,1
qM
qB
Pow_negm,wR"/pow_negm"
,"pow(-x*0.25,y"
o02{2,N(0.01),4,dQ1
Pow_posm,wR"/pow_posm"
,d12
mF1{1,gF3
mA
Sinhm,dR2"hm"
,oA2
hA
gF3
q92
Sinhm_deg,dR2
qM3
oA2
hA
dW2
Sinm,dR2"m"
,gY3,-mM
gF1
Sinm_deg,dR2
qN3
gY3,0,100000,1000
qM
qB
Sqrtm,dQ2"sqrtm"
,"sqrt"
hA
dW2
Tanhm,dQ2"tanhm"
,"tanh"
hA-mM
gF1
Tanhm_deg,dQ2"tanhm_deg"
,"tanh"
hA
N(-1.3),N(1.3),dQ1
Tanm,dQ2"tanm"
,"tan"
hA-89,89,N(0.25)gF1
Tanm_deg,dQ2"tanm_deg"
,"tan"
hA
gF3
mA
Truncm,dQ2"truncm"
,"trunc"
hA
0,1,1
qM,hG
E_mpfr,oW"e_mpfr"
,dC3"naturalnumber"
hX1
L2_mpfr,oW"l2_mpfr"
,dC3"logtwo"
hX1
L10_mpfr,oW"l10_mpfr"
,dC3"logten"
hX1
Pi_mpfr,oW"pi_mpfr"
,dC3"pi"
}
,W4
Wn
Y4
Yn
So
To
S5
W5
Uo
qK3
Acoshm
d2"acoshm"
,q23"("
wL
Acoshm_deg
d2"acoshm_deg"
,q23"("
wM
Wo
qK3
Acosm
d2"acosm"
,"acos("
dM2,aW2
Acosm_deg
d2"acosm_deg"
,"acos(0.7)+x"
}
,Yo
Sp
Tp
qK3
Asinhm
d2"asinhm"
,"a"
oA2"("
wL
Asinhm_deg
d2"asin"
qM3"a"
oA2"("
wM
Up
qK3
Asinm
d2"asinm"
,"asin("
dM2,aW2
Asinm_deg
d2"asin"
qN3"asin("
dM2
qM
q4
Atan2m
d2"atan2m"
,aH2"(5,4"
gH,aW2
Atan2m_deg
d2"atan2m_deg"
,aH2"(5,4)+x"
}
,Wp
qK3
Atanhm
d2"atanhm"
,"atanh("
dM2
qM
q4
Atanm
d2"atanm"
,"atan("
wL
Atanm_deg
d2"atanm_deg"
,"atan"
m8
Cbrtm
d2"cbrtm"
,"cbrt"
m8
Ceilm
d2"ceilm"
,"ceil("
wM
Yp
qK3
Coshm
d2"coshm"
,"cosh("
wL
Coshm_deg
d2"coshm_deg"
,"cosh"
m8
Cosm
d2"cosm"
,"cos("
wL
Cosm_deg
d2"cosm_deg"
,"cos("
wM
Sq
Tq
Y5
Uq
Wq
Yq
W6
Sr
Tr
Ur
qK3
Exp2m
d2"exp2m"
,"exp2("
wM
Wr
Yr
Ss
Ts
qK3
Expm
d2"expm"
,"exp"
m8
Floorm
d2"floorm"
,"floor("
wM
Us
qK3
Hypotm
d2"hypotm"
,"hypot(5,4)+x"
}
,Ws
Ys
St
Tt
Ut
Wt
Yt
Y6
qK3
Log2m
d2"log2m"
,"log2"
m8
Log10m
d2"log10m"
,"log10"
m8
Logm
d2"logm"
,"log("
wM
S7
T7
U7
W7
Y7
Su
S8
Tu
T8
U8
W8
Y8
S9
T9
U9
W9
Y9
SA
TA
UA
qK3
Pow_negm,0,dZ1"_negm"
,"pow(-0.25,4"
gH
qM
q4
Pow_posm,0,dZ1"_posm"
,"pow(1.1, 7.1)+x"
}
,Uu
Wu
Yu
Sv
Tv
Uv
Wv
Yv
Sw
qK3
Sinhm,0,aK"hm"
,oA2"("
wL
Sinhm_deg,0,aK
qM3
oA2
m8
Sinm,0,aK"m"
,"sin("
wL
Sinm_deg,0,aK
qN3"sin("
wM
WA
YA
SB
TB
UB
WB
Tw
Uw
Ww
qK3
Sqrtm
d2"sqrtm"
,"sqrt"
m8
Tanhm
d2"tanhm"
,"tanh("
wL
Tanhm_deg
d2"tanhm_deg"
,"tanh"
m8
Tanm
d2"tanm"
,"tan("
wL
Tanm_deg
d2"tanm_deg"
,"tan"
m8
Truncm
d2"truncm"
,"trunc("
wM
Yw
TC
Sx
UC
Tx
Ux
Wx
Yx
SD
Sy
TD
UD
WD
Ty
Uy
Wy
YD
SE
TE
UE
WE
YE
SF
TF
UF
Yy
Sz
Tz
Uz
Wz
Yz
WF
YF
SG
TG
UG
WG
YG
SH
TH
S_
T_
U_
W_
Y_
S01
UH
WH
YH
SI
TI
UI
WI
YI
SJ
T01
U01
W01
Y01
S11
T11
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
U11
W11
Y11
S21
T21
U21
SL
TL
UL
WL
YL
SM
TM
UM
WM
W21
Y21
S31
T31
U31
W31
YM
SN
TN
UN
WN
YN
SO
TO
UO
Y31
S41
T41
U41
W41
Y41
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
S51
T51
U51
W51
Y51
S61
T61
U61
W61
UQ
WQ
YQ
SR
TR
UR
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
TV
UV
WV
YV
SW
TW
UW
WW
Y61
S71
YW
T71
U71
W71
Y71
SX
S81
TX
T81
U81
W81
UX
WX
YX
SY
Y81
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Yb
Sc
S91
T91
U91
W91
Y91
SA1
TA1
UA1
Tc
Uc
Wc
WA1
YA1
SB1
TB1
UB1
WB1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
YB1
SC1
TC1
UC1
WC1
YC1
SD1
TD1
UD1
WD1
YD1
SE1
TE1
Tf
Uf
Wf
Yf
UE1
Tg
WE1
YE1
SF1
TF1
Ug
UF1
WF1
YF1
SG1
TG1
UG1
WG1
YG1
SH1
TH1
UH1
WH1
YH1
SI1
Wg
Yg
TI1
Sh
Th
Uh
UI1
WI1
Wh
YI1
SJ1
TJ1
UJ1
Yh
WJ1
YJ1
SK1
TK1
Si
Ti
UK1
WK1
YK1
SL1
TL1
UL1
WL1
YL1
SM1
TM1
UM1
WM1
Ui
YM1
SN1
TN1
UN1
WN1
Wi
YN1
TestType<q0>()}
;
#undef Value_t
#undef N
#undef P
#endif /*FP_SUPPORT_MPFR_FLOAT_TYPE */
