#define w93 " " oB3
#define w83 "    "
#define w73 (fp_acos(
#define w63 -aS,oW1
#define w53 (qC sin
#define w43 *fp_sin
#define w33 (qH((
#define w23 (qH mD
#define w13 ,y);}q3
#define w03 1,-10,10,
#define oZ3 (qC sinh
#define oY3 :b):(aR
#define oX3 ,y);}q0
#define oW3 "a" gA2
#define oV3 Sqrneq0
#define oU3 Gt1_abs
#define oT3 Gt0_abs
#define oS3 Ge1_abs
#define oR3 Ge0_abs
#define oQ3 Cmp_sqr
#define oP3 Cmp_neg
#define oO3 Cmp_add
#define oN3 Absneq0
#define oM3 hJ2"  "
#define oL3 gX2"  "
#define oK3 Ifmerge
#define oJ3 gT2"  "
#define oI3 Xaddnot
#define oH3 Sqr_yxx
#define oG3 Sqr_xnx
#define oF3 Sqr_nxx
#define oE3 Absnzlt
#define oD3 Absnzge
#define oC3 q0(3))
#define oB3 " 32"
#define oA3 qG2" "
#define o93 "-125"
#define o83 "x*0+ "
#define o73 40000.0
#define o63 dA1") "
#define o53 gP1") "
#define o43 Multodiv
#define o33 ",3) "
#define o23 hF2" "
#define o13 h22" "
#define o03 hX3" "
#define dZ3 Nor2plus
#define dY3 Lt_or_ne
#define dX3 Lt_or_le
#define dW3 Lt_or_gt
#define dV3 Lt_or_ge
#define dU3 Lt_or_eq
#define dT3 Le_or_ne
#define dS3 Le_or_eq
#define dR3 hV1") "
#define dQ3 L_notnot
#define dP3 L_mulneg
#define dO3 L_mulabs
#define dN3 "(" mA1
#define dM3 Ifmerge2
#define dL3 Gt_or_ne
#define dK3 Gt_or_le
#define dJ3 Gt_or_ge
#define dI3 Gt_or_eq
#define dH3 Ge_or_ne
#define dG3 Ge_or_le
#define dF3 Ge_or_eq
#define dE3 " " mY2
#define dD3 " " gS3
#define dC3 gR2" "
#define dB3 " y," gQ2
#define dA3 gP2" "
#define d93 Xxsqrdup
#define d83 Sqr_yxnx
#define d73 Sqr_ynxx
#define d63 aS2 mQ
#define d53 " " qK3
#define d43 aO1"1 > "
#define d33 qJ2"1 < "
#define d23 aN1"0 > "
#define d13 qI2"0 < "
#define d03 "!x * !y"
#define hZ3 hG2" !!y"
#define hY3 " if" wH2
#define hX3 " +" w83
#define hW3 "!x & !y"
#define hV3 Nand2plus
#define hU3 "!x | !y"
#define hT3 Lt_and_ne
#define hS3 Lt_and_le
#define hR3 Lt_and_gt
#define hQ3 Lt_and_ge
#define hP3 Lt_and_eq
#define hO3 Le_and_ne
#define hN3 Le_and_eq
#define hM3 Ifmerge2b
#define hL3 Gt_and_ne
#define hK3 Gt_and_le
#define hJ3 Gt_and_ge
#define hI3 Gt_and_eq
#define hH3 Ge_and_ne
#define hG3 Ge_and_le
#define hF3 Ge_and_eq
#define hE3 Notnotnot
#define hD3 Dupminmax
#define hC3 "if" d42
#define hB3 {2 m7 1,hH
#define hA3 "if" d52
#define h93 wI1"1 >= "
#define h83 aM1"1 <= "
#define h73 wH1"0 >= "
#define h63 aL1"0 <= "
#define h53 wV"   "
#define h43 dX"   "
#define h33 Cmp_mulpos
#define h23 Cmp_mulneg
#define h13 Xaddnotnot
#define h03 Notnotnot2
#define gZ3 Dupxmuladd
#define gY3 Dupminmax3
#define gX3 Dupminmax2
#define gW3 Dupaddmul7
#define gV3 "abs" qV1
#define gU3 "abs" hO1
#define gT3 "0.0625"
#define gS3 "y,y,x)"
#define gR3 "y,x,y)"
#define gQ3 Cmp_sqr_neg
#define gP3 "floor" d21
#define gO3 "25" mQ
#define gN3 Mixedminmax
#define gM3 Mergemulabs
#define gL3 Addconstmul
#define gK3 "acos" qV1
#define gJ3 "ceil" q51
#define gI3 If_join_mul2
#define gH3 If_join_add2
#define gG3 gG1" "
#define gF3 Cmpzz_minmax
#define gE3 Cmpne_minmax
#define gD3 Cmplt_minmax
#define gC3 Cmple_minmax
#define gB3 Cmpgt_minmax
#define gA3 Cmpge_minmax
#define g93 Cmpeq_minmax
#define g83 Addnegmulpos
#define g73 Addnegmulneg
#define g63 Absnotnotnot
#define g53 -2,2,1,qM
#define g43 Cmpzz_add_imm
#define g33 Cmpne_add_imm
#define g23 Cmplt_add_imm
#define g13 Cmple_add_imm
#define g03 Cmpgt_add_imm
#define qZ3 Cmpge_add_imm
#define qY3 Cmpeq_add_imm
#define qX3 "sin(x))"},
#define qW3 If_extract_mul
#define qV3 If_extract_min
#define qU3 If_extract_add
#define qT3 If_extract_abs
#define qS3 Addmulconstmul
#define qR3 gU3" "
#define qQ3 "acos" wC o4
#define qP3 If_extract_mul2
#define qO3 If_extract_mul1
#define qN3 If_extract_add2
#define qM3 If_extract_add1
#define qL3 o93 mQ
#define qK3 "(5.0625 "
#define qJ3 gS2 w83 w83
#define qI3 If_extract_or2_l
#define qH3 If_extract_or1_l
#define qG3 Cmpzz_minmax_rev
#define qF3 Cmpzz_addadd_imm
#define qE3 Cmpzz_add_reduce
#define qD3 Cmpne_minmax_rev
#define qC3 Cmpne_addadd_imm
#define qB3 Cmpne_add_reduce
#define qA3 Cmplt_minmax_rev
#define q93 Cmplt_addadd_imm
#define q83 Cmplt_add_reduce
#define q73 Cmple_minmax_rev
#define q63 Cmple_addadd_imm
#define q53 Cmple_add_reduce
#define q43 Cmpgt_minmax_rev
#define q33 Cmpgt_addadd_imm
#define q23 Cmpgt_add_reduce
#define q13 Cmpge_minmax_rev
#define q03 Cmpge_addadd_imm
#define mZ2 Cmpge_add_reduce
#define mY2 gS3},
#define mX2 Cmpeq_minmax_rev
#define mW2 Cmpeq_addadd_imm
#define mV2 Cmpeq_add_reduce
#define mU2 If_extract_or2_nl
#define mT2 If_extract_or1_nl
#define mS2 If_extract_and2_l
#define mR2 If_extract_and1_l
#define mQ2 Cmpzz_mul_imm_pos
#define mP2 Cmpzz_mul_imm_neg
#define mO2 Cmpne_mul_imm_pos
#define mN2 Cmpne_mul_imm_neg
#define mM2 Cmplt_mul_imm_pos
#define mL2 Cmplt_mul_imm_neg
#define mK2 Cmple_mul_imm_pos
#define mJ2 Cmple_mul_imm_neg
#define mI2 Cmpgt_mul_imm_pos
#define mH2 Cmpgt_mul_imm_neg
#define mG2 Cmpge_mul_imm_pos
#define mF2 Cmpge_mul_imm_neg
#define mE2 Cmpeq_mul_imm_pos
#define mD2 Cmpeq_mul_imm_neg
#define mC2 d4"5.0625 "
#define mB2 "y, 0,1" mQ
#define mA2 If_extract_and2_nl
#define m92 If_extract_and1_nl
#define m82 Cmpzz_mulmul_imm_pos
#define m72 Cmpzz_mulmul_imm_neg
#define m62 Cmpne_mulmul_imm_pos
#define m52 Cmpne_mulmul_imm_neg
#define m42 Cmplt_mulmul_imm_pos
#define m32 Cmplt_mulmul_imm_neg
#define m22 Cmple_mulmul_imm_pos
#define m12 Cmple_mulmul_imm_neg
#define m02 Cmpgt_mulmul_imm_pos
#define aZ2 Cmpgt_mulmul_imm_neg
#define aY2 Cmpge_mulmul_imm_pos
#define aX2 Cmpge_mulmul_imm_neg
#define aW2 Cmpeq_mulmul_imm_pos
#define aV2 Cmpeq_mulmul_imm_neg
#define aU2 gT3 mQ
#define aT2 cpp_03unit_constants::
#define aS2 "-0.015625"
#define aR2 cpp_02unit_functions::
#define aQ2 h7 LNG_ONLY
#define aP2 cpp_99misc::
#define aO2 cpp_50regressions::
#define aN2 cpp_01unit_operators::
#define aM2 cpp_10optimizer_bytecode::
#define aL2 cpp_11optimizer_constaddmul::
#define aK2 DBL_ONLY
#define aJ2 cpp_20optimizer_optimizations::
#define aI2 fp_exp(
#define aH2 gW oA1
#define aG2 N(.1),
#define aF2 +fp_min(x,
#define aE2 +fp_sin(
#define aD2 {1 o61
#define aC2 Asinhf_deg
#define aB2 },{1,0,dE
#define aA2 Asinf_deg
#define a92 Acosf_deg
#define a82 -6,6,1 qL
#define a72 " " qF1
#define a62 fp_ceil(
#define a52 "a",qE
#define a42 Acoshf_deg
#define a32 fp_and(aO,
#define a22 fp_max wT1
#define a12 (qH wH 0l);}q3
#define a02 qB mD1
#define wZ2 1000,1000,
#define wY2 h0"x)"
#define wX2 N(3.0,0.0),
#define wW2 ")) + (if"
#define wV2 ;}}namespace
#define wU2 TestType<q0>
#define wT2 4.0l dQ
#define wS2 4.0f dQ
#define wR2 "(" a81
#define wQ2 4000,w2
#define wP2 q0(2l)
#define wO2 wP2:
#define wN2 dK gN x
#define wM2 mU);}q3
#define wL2 mflit7_1
#define wK2 q0(1.1l))+
#define wJ2 N(2.0,0.0),
#define wI2 (qJ q0(
#define wH2 "(x" dW
#define wG2 ")/a"},
#define wF2 ")*0"},
#define wE2 ")*" gH2
#define wD2 ")*a"},
#define wC2 a51" +"
#define wB2 "(1,0,1"
#define wA2 ") + ("
#define w92 N(.5)h5
#define w82 qB,oT
#define w72 "sqrt("
#define w62 " + 1/"
#define w52 N(.2)h5
#define w42 "expex"
#define w32 {2 m7 hP
#define w22 -2,2,hP
#define w12 "acosh"
#define w02 "*z) +"
#define oZ2 "<=y &"
#define oY2 aY" | "
#define oX2 aY" & "
#define oW2 "x))"},
#define oV2 "x,y,z"
#define oU2 fp_not(
#define oT2 (qH q0
#define oS2 *q0(0 oH
#define oR2 (qJ exp(
#define oQ2 (qJ sqrtf
#define oP2 qJ logf(
#define oO2 (dK gX x
#define oN2 (dK gI x
#define oM2 (dK gS x
#define oL2 q0(6l))
#define oK2 mflit0_25
#define oJ2 {using namespace FUNCTIONPARSERTYPES;q0
#define oI2 ));}q0
#define oH2 ))gT x
#define oG2 oJ gG)
#define oF2 g2 dU
#define oE2 g2-dU
#define oD2 h9 gG
#define oC2 oF gG)
#define oB2 (qJ qL1
#define oA2 0l)oH dG 0l
#define o92 0l dL 0l
#define o82 (oU2 x
#define o72 N(-6.0,0.0),wN
#define o62 q0(0l)
#define o52 "(" wU
#define o42 oQ" "
#define o32 oP" "
#define o22 ")+(x"
#define o12 "exp" qV1
#define o02 "exp("
#define dZ2 " " dV
#define dY2 " != "
#define dX2 " <= "
#define dW2 " >= "
#define dV2 "m_deg",
#define dU2 mflit2_5
#define dT2 *q0(2))
#define dS2 d2r(dD
#define dR2 5),q0(4)
#define dQ2 qJ w11
#define dP2 (1.1l dQ
#define dO2 qJ expl(
#define dN2 "(" w6
#define dM2 "hm_deg",
#define dL2 true q4
#define dK2 q0(dN))
#define dJ2 q0(3l))
#define dI2 qH a0*y,
#define dH2 oU2 z
#define dG2 log(1.1)
#define dF2 qV qP-g2
#define dE2 gB-gG qV
#define dD2 gB-gG qU
#define dC2 gB-gG qT
#define dB2 gB-gG qS
#define dA2 gB-gG qX
#define d92 wD 0l))
#define d82 (qH x>=w41
#define d72 fp_cosh(
#define d62 qJ-x;}q3
#define d52 "(" gP1
#define d42 "(" dA1
#define d32 q0(0l qQ
#define d22 qH x+w41
#define d12 "+" hK1
#define d02 "a,b",oL
#define hZ2 "atan2"
#define hY2 "abs(b"
#define hX2 "abs(a"
#define hW2 o8"-5)"
#define hV2 o8"5)"
#define hU2 "=-2) +" h81
#define hT2 "=-2" oC
#define hS2 oX w93
#define hR2 oX h71
#define hQ2 oX h91
#define hP2 oX w83"4"
#define hO2 oX h81
#define hN2 q91"))*"
#define hM2 N(.15)h5
#define hL2 "x+-x+-"
#define hK2 N(.1)h5
#define hJ2 "7/2) +"
#define hI2 q01 1,q7
#define hH2 {1 m7 hP
#define hG2 "!!x *"
#define hF2 ",-2)"
#define hE2 ")" d6 gM
#define hD2 ")" hJ1
#define hC2 ")" hI1
#define hB2 ")" hH1
#define hA2 ")" hG1
#define h92 q0(1l)
#define h82 ,hR gG)
#define h72 qJ fp_pow(
#define h62 (qJ fp_sin(
#define h52 qJ oU2
#define h42 (0l);}q3
#define h32 (qJ h92/
#define h22 ",-3)"
#define h12 "180/pi"
#define h02 qB dP1
#define gZ2 qB",y,z"
#define gY2 10,10,h4
#define gX2 "x!=y) +"
#define gW2 )oH 1.2l)*
#define gV2 "x" dP1
#define gU2 {3,0,hN
#define gT2 ",-" wD1
#define gS2 "," wD1
#define gR2 "x" hU1
#define gQ2 "x" wA1
#define gP2 "x",o0
#define gO2 "1,4,0"
#define gN2 m7 1 qL
#define gM2 N(0.5)qL
#define gL2 (fp_cos o5
#define gK2 (fp_sin(y),qN1
#define gJ2 (qH hT1
#define gI2 (1.1f dQ
#define gH2 "5"},
#define gG2 (q0(0))+
#define gF2 gL;}q0
#define gE2 gY;}q0
#define gD2 gK;}q0
#define gC2 *d7 qQ
#define gB2 h9 x),
#define gA2 "sinh"
#define g92 ",if("
#define g82 +fp_less(
#define g72 fp_sqrt(
#define g62 aI2-x)
#define g52 *fp_pow(a4
#define g42 (qJ r2d(
#define g32 q0(0.5l
#define g22 (hE(wL1/mJ)
#define g12 x+x+x+x+
#define g02 aI2 x)
#define qZ2 mflit1_1*
#define qY2 mflit1_5*
#define qX2 atan2l(
#define qW2 sqrtl(x*x
#define qV2 atan2f(
#define qU2 sqrtf(x*x
#define qT2 "^1506"},
#define qS2 q0 wS1
#define qR2 fp_tan(
#define qQ2 x oH 1l)/
#define qP2 qP-hZ))
#define qO2 -gD),dU
#define qN2 ,"1" oI1
#define qM2 ,gU gG)
#define qL2 "(x*" mJ1
#define qK2 "(x) +"
#define qJ2 " > 1" oC
#define qI2 " > 0" oC
#define qH2 ")+x+("
#define qG2 "xp" oX
#define qF2 "(log(x+"
#define qE2 "   if(x"
#define qD2 "(x^2" mQ
#define qC2 "pow(x"
#define qB2 ,-5,5,
#define qA2 fp_pow gW1
#define q92 1 qB2 1,
#define q82 a3" | "
#define q72 a3" & "
#define q62 " " gA1
#define q52 " < 6" mQ
#define q42 " > 6" mQ
#define q32 " = 6" mQ
#define q22 qJ fp_nequal(
#define q12 fp_equal(
#define q02 5)oH 1)/
#define mZ1 fp_and(x
#define mY1 )oH gX x
#define mX1 )oH gI x
#define mW1 )oH gS x
#define mV1 )oH gN x
#define mU1 q0(16l
#define mT1 qU qK gD
#define mS1 q0(7l)
#define mR1 ),fp_abs(
#define mQ1 h92))
#define mP1 *-d7 qQ
#define mO1 q0(5l)
#define mN1 wP2 qQ
#define mM1 qR dO1
#define mL1 {1,q2
#define mK1 {2,q6
#define mJ1 "5" mQ
#define mI1 "cmp_ex"
#define mH1 ")/log("
#define mG1 "(1.0"
#define mF1 dM" " gM
#define mE1 "pi/180"
#define mD1 ",y,z",oT
#define mC1 "x" mD1
#define mB1 " + (x*"
#define mA1 "y+2" mQ
#define m91 "x" dI
#define m81 hM1" | "
#define m71 qJ aI2
#define m61 (mB qK gD
#define m51 )g52*
#define m41 (oM,q0(4l)qQ
#define m31 hM1" & "
#define m21 wL"4)"
#define m11 gJ1")"
#define m01 "abs(x)"
#define aZ1 y),w9,y)oH
#define aY1 fp_max(q0(
#define aX1 fp_min(q0(
#define aW1 )/gG+mH-gF
#define aV1 wH 1l);}q3
#define aU1 +fp_or(q0(
#define aT1 fp_and(q0(
#define aS1 " < 6)" a9
#define aR1 ,qG"/sin"
#define aQ1 "log(x)"},
#define aP1 {1,0,hN
#define aO1 " < 1" hC1
#define aN1 " < 0" hC1
#define aM1 " >= 1" oC
#define aL1 " >= 0" oC
#define aK1 "(x*z+17)"
#define aJ1 2 q01 2 qL
#define aI1 "sub(sub("
#define aH1 10,10,1,hH
#define aG1 " > 6)" aB
#define aF1 " != 6)" d6
#define aE1 " != 6" mQ
#define aD1 " <= 6" mQ
#define aC1 " >= 6" mQ
#define aB1 -fp_int(
#define aA1 mflit0_5
#define a91 qR2 y)
#define a81 "0.7" gH
#define a71 fp_atan2(
#define a61 qJ q0(h8
#define a51 "sin(x)"
#define a41 "(-x)"},
#define a31 ") +" oB3
#define a21 "(1)) +"
#define a11 {3 m7 hP
#define a01 "(x>4" mQ
#define wZ1 "*(x"
#define wY1 q0(1))+
#define wX1 mflit0_7 dQ
#define wW1 4,4,N(0.05)
#define wV1 g72 q0(
#define wU1 fp_cos(y w71
#define wT1 (x,fp_max(
#define wS1 (1.0l))
#define wR1 qJ fp_less(
#define wQ1 (2l)/dJ2+
#define wP1 dB y:x oH
#define wO1 dB x:y oH
#define wN1 dB y:mS
#define wM1 ))+mflit1_2*
#define wL1 (h92
#define wK1 N(4.0,0.0),
#define wJ1 " cos(x)"},
#define wI1 " <= 1" hC1
#define wH1 " <= 0" hC1
#define wG1 ",max(x,ma"
#define wF1 "   10*" o0
#define wE1 qB q8"/pow"
#define wD1 "x)) +"
#define wC1 " >= 6)" aC
#define wB1 " <= 6)" aA
#define wA1 ",y" mQ
#define w91 "dupminmax"
#define w81 ,fp_sin(
#define w71 *q0(1.5l))
#define w61 dY2 g31 d6
#define w51 {2,q2
#define w41 y;}q3
#define w31 {1,-oA
#define w21 q0(fp_abs(x)
#define w11 r2d(q0::
#define w01 fp_cos(y)+
#define oZ1 ,"(sin(x)"
#define oY1 fp_sin(y)+
#define oX1 -400,400,
#define oW1 true qI
#define oV1 (q0(0.0l))+
#define oU1 1 m7 N(0.01)
#define oT1 5l)oH 1l)/
#define oS1 )*fp_and(dY,y),
#define oR1 =vars[1],&
#define oQ1 =vars[0],&
#define oP1 fp_or(y,z)
#define oO1 "(acos(x)"
#define oN1 ,"(" m01
#define oM1 fp_abs(a
#define oL1 0l))qT q0(0l
#define oK1 0l))qX q0(0l
#define oJ1 d2r(x qQ
#define oI1 h1")"
#define oH1 oO"pow"
#define oG1 "<-4) " m0
#define oF1 "=-4) " aZ
#define oE1 "*((-x)"
#define oD1 ,N(0.25)
#define oC1 1 oD1,
#define oB1 gG1 dW"))"},
#define oA1 "cmpeq_"
#define o91 ")), int("
#define o81 4l),y+q0(6l oH2
#define o71 qH q0(h8 x*
#define o61 ,-1,hN
#define o51 3 o61
#define o41 wL"4*y)"
#define o31 2 q01 2,q7
#define o21 q5"/"
#define o11 (oP2 1.1f
#define o01 40,40,3,qM
#define dZ1 "y) + x/"
#define dY1 qK-gD hD)
#define dX1 hR x),-gG
#define dW1 gU x),-gG
#define dV1 -q0(2l qQ
#define dU1 gB2-gG
#define dT1 "sin(" wU
#define dS1 N(0.5,0.0),
#define dR1 N(-1.0,0.0)qN
#define dQ1 q01 N(0.41)qL
#define dP1 ",y",oT
#define dO1 "if_ex"
#define dN1 N(1.0,0.0),q7
#define dM1 fp_and(y,z)
#define dL1 "(cbrt(x^6"
#define dK1 ">-4) +" wR
#define dJ1 "<=-4) " m1
#define dI1 "!=4" mQ
#define dH1 qB g3"/"
#define dG1 2,-4,4,1,q7
#define dF1 "(x != y" mQ
#define dE1 "(x = y" mQ
#define dD1 gJ1"*y)"
#define dC1 N(1e-6),400,w2
#define dB1 h21 z+q0(17l),
#define dA1 "1,1,1"
#define d91 "1.1^x*4.1" mQ
#define d81 "<4) " m0
#define d71 "=4) " aZ
#define d61 {1,-4,4,1 qL
#define d51 {1,-36,36,1 qL
#define d41 {w03 1 qL
#define d31 "!=-2" mQ
#define d21 "(x),ceil(x))+"
#define d11 "((-5.1)*x*y)"
#define d01 gW"cmpne_"
#define hZ1 gW"cmplt_"
#define hY1 gW"cmple_"
#define hX1 gW"cmpgt_"
#define hW1 gW"cmpge_"
#define hV1 "(x <= y"
#define hU1 "_rev",o0
#define hT1 aO,dU gO
#define hS1 *x,q0(25l)oH
#define hR1 fp_lessOrEq(
#define hQ1 "+ sin(x+pi*"
#define hP1 +x;}q3
#define hO1 wC"*(" m01
#define hN1 oO"powx"
#define hM1 ,"(x > y)"
#define hL1 "(2))"},
#define hK1 " cos(x-pi*"
#define hJ1 g1"0010 " a8
#define hI1 g1"0008 " a8
#define hH1 g1"0004 " a8
#define hG1 g1"0002 " a8
#define hF1 0,4,N(0.1)qL
#define hE1 z+y+z+y+z+y+
#define hD1 oU2-oU2
#define hC1 ") " aN
#define hB1 "*(" oU
#define hA1 "*(" wQ
#define h91 w83"8"
#define h81 w83"2"
#define h71 w83"16"
#define h61 "*(" wP
#define h51 "*(" aK
#define h41 "*(" aJ
#define h31 ")^(1/"
#define h21 fp_pow(x*
#define h11 fp_notNot(x
#define h01 /q0(3l)hD))
#define gZ1 fp_abs(x qQ
#define gY1 g0 o1"+y+z"
#define gX1 ,N(0.25,0.0),
#define gW1 (aI2 qS2,
#define gV1 "x" q8"/"
#define gU1 0x0001)*fp_less(
#define gT1 )/gG aE2 x
#define gS1 oH 5l);}q3
#define gR1 mO1,dJ2+x
#define gQ1 ")) " aN"if("
#define gP1 "1,0,0"
#define gO1 ">4) +" wR
#define gN1 "<=4) " m1
#define gM1 o7"(" qW1
#define gL1 o7"(x)"
#define gK1 ",y" q8"/pow"
#define gJ1 wL"-4"
#define gI1 ") + sin(x-pi*"
#define gH1 " + cos(x+pi*"
#define gG1 " if(x"
#define gF1 ")" dW2 g31 aC" "
#define gE1 ") > " g31 aB" "
#define gD1 )*(mO1+(
#define gC1 ")" dX2 g31 aA" "
#define gB1 ") < " g31 a9" "
#define gA1 o3"+y)"
#define g91 {2,-460,100,8,qM
#define g81 "((1/   abs(b))*"
#define g71 N(0.1),oW1
#define g61 " " o41
#define g51 " " dD1
#define g41 userDefFuncSqr<q0>((
#define g31 "(y+6))"
#define g21 hA-1,1,N(0.01)
#define g11 *x,q0(25l qQ
#define g01 log(x+sqrt(x*x
#define qZ1 3,N(0.0,0.0)qN
#define qY1 "pow(-4,y))"
#define qX1 qB q71
#define qW1 "abs(x))"
#define qV1 "(x))"},
#define qU1 -6,6,N(0.5),qM
#define qT1 "*(5+" o0
#define qS1 fp_cos(y*mflit1_5)
#define qR1 d2r(1.1l)dQ
#define qQ1 d2r(1.1f)dQ
#define qP1 "1.1" gH qL
#define qO1 ,o62)gO x:-x
#define qN1 fp_cos(y)):
#define qM1 "x,y",g6
#define qL1 fp_greater(
#define qK1 g02,
#define qJ1 hM x+y+x+x-z hP1
#define qI1 "*(sinh(x)"
#define qH1 "*(atan(x)"
#define qG1 "(x*if(1,-1,0))"},
#define qF1 "(pow(2,x)"
#define qE1 fp_less(y,q0(1l
#define qD1 ),fp_acos(
#define qC1 hR1 q0(
#define qB1 ))aB1 q0(
#define qA1 q0(4l qQ
#define q91 "(sin(x)+cos(y"
#define q81 -10,10,N(0.8)qL
#define q71 ",y" q8"/"
#define q61 gW"cmpzz_pow"
#define q51 "(x),floor(x))+"
#define q41 fp_sin(x)+mflit1_2)
#define q31 fp_abs(x)>=aA1
#define q21 oU2 x)*oU2 y)
#define q11 fp_tanh(x),gG
#define q01 ,-3,3,
#define mZ {1 q01 N(0.1)qL
#define mY x*x),mU1))
#define mX fp_asin(x),gG
#define mW fp_acos(x),gG
#define mV "pow(1.5,x))"
#define mU *q0(5l
#define mT {2,0,hN
#define mS x);}q3
#define mR N(-5.0,0.0),N(5.0,0.0),wJ2 q7
#define mQ ")"},
#define mP ")) +" h81"*(if("
#define mO w83" "
#define mN +q0(0x0020)*q12
#define mM (d2r(x oI2
#define mL dB x:y);}q3
#define mK ((x*q0(gA
#define mJ fp_abs(b)
#define mI -2,2,1,q7
#define mH fp_cos(x
#define mG fp_exp2(x),-dU
#define mF (fp_sin(x)+fp_cos(y))*
#define mE {1,-15,15,2,qA
#define mD q12 x
#define mC qJ fp_greaterOrEq(
#define mB qJ qW
#define mA (qJ q12
#define m9 1,dR1
#define m8 (x);}q0
#define m7 ,-1,1,
#define m6 m7 2,qA
#define m5 gZ2 q8"/"
#define m4 ,o62)gO-x:x)oH
#define m3 log(1.1+sqrt(1.1*
#define m2 ">=4" a31
#define m1 "+   8"
#define m0 "+   4"
#define aZ "+   2"
#define aY "(x >= y)"
#define aX +q0(0x0010)*fp_nequal(
#define aW qK 1.1l),x)*q0(4.1l qQ
#define aV +q0(0x0008)*fp_greaterOrEq(
#define aU +q0(0x0004)*qL1
#define aT qJ logl(
#define aS 40000,40000,5
#define aR fp_truth(
#define aQ ,qG"/"
#define aP *x*x,-q0(125l
#define aO fp_less(x
#define aN "+  8*("
#define aM ">=-2) +" w93
#define aL "<-2)" hX3"4"
#define aK "exp2(x)"
#define aJ "exp(x)"
#define aI "*((1-x+x+5)"
#define aH -1,1,gM2
#define aG oV2 q8"/"
#define aF +q0(0x0002)*hR1
#define aE fp_or o82),oU2 y
#define aD N(-1.25),N(1.25)oD1
#define aC g1"0010 *"
#define aB g1"0008 *"
#define aA g1"0004 *"
#define a9 g1"0002 *"
#define a8 "* " gM
#define a7 fp_and o82),oU2 y
#define a6 h11)*fp_notNot(y)
#define a5 ">-2) +" h71
#define a4 x*x*x*x
#define a3 ,"(x < y)"
#define a2 "<=-2) +" h91
#define a1 qY1},
#define a0 fp_pow((q0(-5.1l))*x
#define wZ qH fp_pow((mflitm5_1)*x*y,
#define wY N(-7.25),N(7.25),N(0.5),qM
#define wX qP-gG,q0(0.0625l)
#define wW LNG_ONLY(0)q5"/x"
#define wV "^6.1)) +"
#define wU "0.75)) +"
#define wT A_very_long_variable_name_1
#define wS "*((x*x)"
#define wR "   16"
#define wQ "log2(" qW1
#define wP "log2(x)"
#define wO mV},
#define wN N(6.0,0.0),dS1 qM
#define wM qB",y",g6
#define wL "((x*"
#define wK "x" g3"/"
#define wJ N(-.1),aG2 N(0.01)qL
#define wI qB,"03unit_constants/"
#define wH x*o62+y*q0(0l oH
#define wG qK 2l),x),qK-4l),y)
#define wF x)oH 4l)*fp_less(
#define wE fp_sin(x),q0(
#define wD fp_abs(x),q0(
#define wC "(x))" hX3"4"
#define wB ,"02unit_functions"
#define wA qB",y" wB
#define w9 fp_nequal(x
#define w8 ,false qI
#define w7 ,0,1,1 qL
#define w6 "1.1)+x"},
#define w5 h7 wI
#define w4 "1.1" gH,dL2
#define w3 LNG_ONLY(0)q5"/pow"
#define w2 N(0.1)w8
#define w1 ,hT dS1 q7
#define w0 const q0*vars){const q0&
#define oZ "sin(x))" hX3"4*(sin(x)"
#define oY h0"(x/3))"
#define oX "(2)) +"
#define oW {1,N(0.5),3,gM2
#define oV {1 q01 gM2
#define oU "log10(x)"
#define oT "99misc/"
#define oS 5.0625l),qK 1.5l),x)
#define oR qK1 aI2 gG)
#define oQ "(1.061^(x/3)))"
#define oP "((-1.061)^x))"
#define oO qZ"cmp_"
#define oN fp_acos(x),q0(
#define oM qL1 x
#define oL "50regressions/"
#define oK qP-gG,q0(0.0625l qQ
#define oJ fp_sinh(x),fp_sinh(
#define oI *x,q0(1)/q0(
#define oH )+q0(
#define oG qK-gD),qK-1.061l),x
#define oF fp_exp2(x),fp_exp2(
#define oE fp_atan(x),fp_atan(
#define oD 3,dR1
#define oC ") +" h81"*("
#define oB 1 gN2
#define oA 1,1 oD1 qL
#define o9 "*(tanh(x)"
#define o8 "*((x/2*x*"
#define o7 "*(log"
#define o6 "*(a" a51
#define o5 (y+h92)w81 y+h92 qQ
#define o4 "*(acos(x)"
#define o3 "((x+4"
#define o2 N(-2.0,0.0),wJ2 dS1 q7
#define o1 "+y+z+y+z+y+z"
#define o0 "if(x"
#define dZ aR x)gO
#define dY hR1 x
#define dX "(x^-6.1)) +"
#define dW "<4, cos(y),sin(y+1"
#define dV "((((x*5/2)+x*x-2))"
#define dU q0(4l))
#define dT x*x*x,h92/q0(
#define dS 2,N(-3.0,0.0),wX2 dN1
#define dR N(-7.25,0.0),N(7.25,0.0),dS1 qM
#define dQ )+x;}q0
#define dP qK 2l),x),qK-4l),y qQ
#define dO /dJ2,qK-1.061l),x
#define dN 1l)-x+x+mO1),q0(4l
#define dM ,"0x0001 *"
#define dL )oH 2l)*qC1
#define dK 4l),y+q0(6l)oH
#define dJ "*(log10(" qW1
#define dI ",y,z" q8"/" dO1
#define dH 5.0625l),qK 1.5l),x qQ
#define dG 8l)*fp_greaterOrEq(q0(
#define dF "<4, sin(y),cos(y+1))"
#define dE 1,1,false,aT2
#define dD mflit1_1)dQ
#define dC {1 qB2 2,q7
#define dB ,y)!=o62)?
#define dA /wP2*x*-mO1),q0(4l
#define d9 /wP2*x mU)),q0(4l
#define d8 +q0(4l)+y,q0(6l
#define d7 q0(4l)*y,q0(6l
#define d6 " +  0x0020 * "
#define d5 qP-dJ2,-q0(0.015625l
#define d4 "pow_imm_pospos_base","("
#define d3 "pow_imm_pospos",gM",2)"
#define d2 "pow_imm_posneg",gM",3)"
#define d1 fp_greaterOrEq(x
#define d0 g2 qP q0(6.1l)))
#define hZ g2 qP-q0(6.1l)
#define hY "pow_imm_negpos",gM hF2
#define hX g31},
#define hW {1,-6,6,1,q7
#define hV "pow_imm_negneg",gM h22
#define hU 2,N(-4.0,0.0),wK1 dN1
#define hT N(-1.0,0.0),N(1.0,0.0),
#define hS 2,N(-3.0,0.0),wX2 wJ2 q7
#define hR fp_log(
#define hQ LNG_ONLY(0)q5"/sin"
#define hP N(0.5),q7
#define hO fp_tanh(x),fp_tanh(q0(0.75l)
#define hN 1,1,q7
#define hM (qD,&y oR1 z=vars[2];return
#define hL fp_asin(x),fp_asin(q0(0.75l)
#define hK fp_acos(x qD1 q0(0.75l)
#define hJ {oC1 3 oD1 qL
#define hI 2,N(0.0,0.0)qN
#define hH false,aO2
#define hG x=vars[2],&y=vars[3];return(dZ(aR y)gO
#define hF "powpow_imm_base",qF1
#define hE const q9
#define hD ),qK 1.061l),x/q0(3l)
#define hC "a,b",qE
#define hB q0(4l),y+q0(6l qQ
#define hA "(x)"},{1,
#define h9 fp_log2(
#define h8 0x0001l)*fp_less(
#define h7 aK2(0)
#define h6 {2,N(-1.75),N(1.75)oD1,qM
#define h5 ,false,aP2
#define h4 1 h5
#define h3 wX2 N(5.0,0.0),dS1 q7
#define h2 "*((x^5.1)"
#define h1 "*((x^-5.1"
#define h0 "*((2.051^"
#define gZ wL"5/2)+abs(x)))"
#define gY -q0(2)),mflit0_0625)
#define gX 0x0010l)*fp_nequal(
#define gW qB q8"/"
#define gV mflit1_1 dQ
#define gU fp_log10(
#define gT +q0(0x0020l)*q12
#define gS 0x0004l)*qL1
#define gR {1,N(1e-6,0.0),N(4000.0,0.0),N(0.1,0.0)w8
#define gQ N(-6.0,-3.0),N(6.0,+3.0),N(0.5,+0.25),qM
#define gP *(g12 g12 x+x+x+y+hE1 hE1 z+y+z+y+z)
#define gO !=o62?
#define gN 0x0002l)*hR1
#define gM "(pow(x"
#define gL mflit5_0625,fp_pow(mflit1_5,x))
#define gK qP-oC3,-mflit0_015625)
#define gJ N(-1.75,0.0),N(1.75,0.0)gX1 qM
#define gI 0x0008l)*fp_greaterOrEq(
#define gH ")+x"},{1,0,1,1
#define gG wP2)
#define gF fp_const_pi<q0>()
#define gE 2,N(-2.0,0.0),wJ2 dN1
#define gD 2.051l),x
#define gC {1,N(-0.7),N(0.7),N(0.28)qL
#define gB fp_abs(x)),
#define gA 5l)/gG+x*x-gG,((x mU)/gG+fp_abs(x)
#define g9 hT wJ2 qA
#define g8 {2,-6,6,1,q7
#define g7 (w0 a=vars[0];return
#define g6 "01unit_operators/"
#define g5 {2,-15,15,2,qA
#define g4 "*(((-2.051)^x)"
#define g3 ",y","10optimizer_bytecode"
#define g2 q0(5.1l)),
#define g1 hX3"0x"
#define g0 "y+z" o1"+y+z"
#define qZ LNG_ONLY(0)o21
#define qY qD,&y oR1 z=vars[2];return dZ
#define qX +wP2*fp_less(
#define qW h92*q12
#define qV +q0(32l)*fp_nequal(
#define qU +mU1)*fp_greaterOrEq(
#define qT +q0(8l)*qL1
#define qS +q0(4l)*hR1
#define qR "x" q71
#define qQ ));}q3
#define qP fp_pow(x,
#define qO qB wB
#define qN ,N(1.0,0.0),dN1
#define qM false,aN2
#define qL ,false q4
#define qK fp_pow(q0(
#define qJ qD;return
#define qI ,aR2
#define qH qD,&y=vars[1];return
#define qG aQ2(0)q5
#define qF ,h7 qO
#define qE "11optimizer_constaddmul/"
#define qD const q0 q1
#define qC qJ q0::
#define qB LNG_ONLY(0)"x"
#define qA false,aL2
#define q9 q0*vars){const q0&a oQ1 b=vars[1];return
#define q8 ,"20optimizer_optimizations"
#define q7 false,aJ2
#define q6 N(-15.0,0.0),N(15.0,0.0),wJ2 qA
#define q5 "x","10optimizer_bytecode"
#define q4 ,aM2
#define q3 template<typename q0>static q0
#define q2 N(-6.0,0.0),N(6.0,0.0),dN1
#define q1 *vars){const q0&x=vars[0]
#define q0 Value_t
#ifdef FP_TEST_WANT_DOUBLE_TYPE
#define DBL_ONLY(p) p,
#else
#define DBL_ONLY(p)
#endif
#ifdef FP_TEST_WANT_LONG_INT_TYPE
#define LNG_ONLY(p) p,
#else
#define LNG_ONLY(p)
#endif
#define APP(x,y) x##y
#define S {2,-o01 Add_i,aQ2(aN2 Add_i)qM1"add_i","x+y"},
#define T {3,-o01 Addsub_i,aQ2(aN2 Addsub_i)oV2,g6"addsub_i","x+y+x+x-z+x"},
#define U {2,g53 And_i,aQ2(aN2 And_i)qM1"and_i","x&y"},
#define W {2,g53 Cmpeq_i,aQ2(aN2 Cmpeq_i)qM1"cmpeq_i","x=y"},
#define Y {2,g53 Cmpge_i,aQ2(aN2 Cmpge_i)qM1"cmpge_i","x>=y"},
#define S1 {2,g53 Cmpgt_i,aQ2(aN2 Cmpgt_i)qM1"cmpgt_i","x>y"},
#define T1 {2,g53 Cmple_i,aQ2(aN2 Cmple_i)qM1"cmple_i","x<=y"},
#define U1 {2,g53 Cmplt_i,aQ2(aN2 Cmplt_i)qM1"cmplt_i","x<y"},
#define W1 {2,g53 Cmpne_i,aQ2(aN2 Cmpne_i)qM1"cmpne_i","x!=y"},
#define Y1 g91 Div_i,aQ2(aN2 Div_i)qM1"div_i","x/(y+3" mQ
#define S2 {3,-46,40,2,qM Divmul_i,aQ2(aN2 Divmul_i)oV2,g6"divmul_i","x*y*x*x/(z+3)*(x+4" mQ
#define T2 {1,-41,40,3,qM Inv_i,aQ2(aN2 Inv_i)"x",g6"inv_i","1/x"},
#define U2 g91 Mod_i,aQ2(aN2 Mod_i)"x,z",g6"mod_i","x%(z+3" mQ
#define W2 g91 Mul_i,aQ2(aN2 Mul_i)qM1"mul_i","x*(y+4" mQ
#define Y2 {1,-o01 Neg_i,aQ2(aN2 Neg_i)"x",g6"neg_i","-x"},
#define S3 {1,g53 Not_i,aQ2(aN2 Not_i)"x",g6"not_i","!x"},
#define T3 {1,g53 Notnot_i,aQ2(aN2 Notnot_i)"x",g6"notnot_i","!!x"},
#define U3 {2,g53 Or_i,aQ2(aN2 Or_i)qM1"or_i","x|y"},
#define W3 {2,-o01 Sub_i,aQ2(aN2 Sub_i)qM1"sub_i","x-y"},
#define Y3 {1,-40000,40000,1 w8 Abs_i,aQ2(aR2 Abs_i)"x" wB"/abs_i",m01},
#define S4 {3,-2,2,1 w8 If_i,aQ2(aR2 If_i)oV2 wB"/if_i",o0",y,z" mQ
#define T4 {2,-4,4,1 w8 Max,aK2(aR2 Max)LNG_ONLY(aR2 Max)"x,y" wB"/max","max(x" wA1
#define U4 {2,-4,4,1 w8 Min,aK2(aR2 Min)LNG_ONLY(aR2 Min)"x,y" wB"/min","min(x" wA1
#define W4 {1 w7 Abs,aK2(aM2 Abs)LNG_ONLY(aM2 Abs)o21"abs","(abs(-3))+x"},
#define Y4 {oB Absnot,aK2(aM2 Absnot)LNG_ONLY(aM2 Absnot)o21"absnot","!(abs" qV1
#define S5 {oB g63,aK2(aM2 g63)LNG_ONLY(aM2 g63)o21"absnotnotnot","!(!!((x*x)))"},
#define T5 {1 qB2 1 qL oD3,aK2(aM2 oD3)LNG_ONLY(aM2 oD3)o21"absnzge","sub(" m01" >= 4, abs(x) >= 0" mQ
#define U5 {1 qB2 1 qL oE3,aK2(aM2 oE3)LNG_ONLY(aM2 oE3)o21"absnzlt","sub(" m01" < 4, abs(x) < 0" mQ
#define W5 {oB Abssqr,aK2(aM2 Abssqr)LNG_ONLY(aM2 Abssqr)o21"abssqr","abs(x)*" m01},
#define Y5 {1 q01 1 qL gW3,aK2(aM2 gW3)LNG_ONLY(aM2 gW3)o21"dupaddmul7","(x+x)*7"},
#define S6 d41 hD3,aK2(aM2 hD3)LNG_ONLY(aM2 hD3)o21 w91,"sub(min(x,x), max(x," oW2
#define T6 d41 gX3,aK2(aM2 gX3)LNG_ONLY(aM2 gX3)o21 w91"2","sub(x+min(x,x), x+max(x," oW2
#define U6 {2,-2,2,1 qL gY3,aK2(aM2 gY3)LNG_ONLY(aM2 gY3)wK w91"3","sub(min(min(y,x),x), max(max(y,x)," oW2
#define W6 d41 gZ3,aK2(aM2 gZ3)LNG_ONLY(aM2 gZ3)o21"dupxmuladd","x+(x*4" mQ
#define Y6 {aJ1 Invmul,aK2(aM2 Invmul)LNG_ONLY(aM2 Invmul)wK"invmul","y*(1/x)"},
#define S7 {1 w7 Max,aK2(aM2 Max)LNG_ONLY(aM2 Max)o21"max","max(5,4)+x"},
#define T7 {1 w7 Min,aK2(aM2 Min)LNG_ONLY(aM2 Min)o21"min","min(4,5)+x"},
#define U7 {1 w7 Mul2,aK2(aM2 Mul2)LNG_ONLY(aM2 Mul2)o21"mul2","x*2"},
#define W7 {2 q01 1 qL Mul4,aK2(aM2 Mul4)LNG_ONLY(aM2 Mul4)wK"mul4","y*(x*2)*2 + (y*2)*2"},
#define Y7 {oB Negabs,aK2(aM2 Negabs)LNG_ONLY(aM2 Negabs)o21"negabs","abs" a41
#define S8 {oB Negdiv,aK2(aM2 Negdiv)LNG_ONLY(aM2 Negdiv)o21"negdiv","(-x)/" gH2
#define T8 {1 q01 2 qL Negneg,aK2(aM2 Negneg)LNG_ONLY(aM2 Negneg)o21"negneg","-(-(-(-(-(-(x))))))"},
#define U8 {oB Negnot,aK2(aM2 Negnot)LNG_ONLY(aM2 Negnot)o21"negnot","!" a41
#define W8 {oB Negsqr,aK2(aM2 Negsqr)LNG_ONLY(aM2 Negsqr)o21"negsqr","(-x)*(-x)"},
#define Y8 {2 w7 Not_eq,aK2(aM2 Not_eq)LNG_ONLY(aM2 Not_eq)wK"not_eq","!" dE1
#define S9 {2 w7 Not_ge,aK2(aM2 Not_ge)LNG_ONLY(aM2 Not_ge)wK"not_ge","!" aY},
#define T9 {2 w7 Not_gt,aK2(aM2 Not_gt)LNG_ONLY(aM2 Not_gt)wK"not_gt","!(x > y" mQ
#define U9 {2 w7 Not_le,aK2(aM2 Not_le)LNG_ONLY(aM2 Not_le)wK"not_le","!" hV1 mQ
#define W9 {2 w7 Not_lt,aK2(aM2 Not_lt)LNG_ONLY(aM2 Not_lt)wK"not_lt","!(x < y" mQ
#define Y9 {2 w7 Not_ne,aK2(aM2 Not_ne)LNG_ONLY(aM2 Not_ne)wK"not_ne","!" dF1
#define SA {oB Notnot,aK2(aM2 Notnot)LNG_ONLY(aM2 Notnot)o21"notnot","!!(x)"},
#define TA {oB hE3,aK2(aM2 hE3)LNG_ONLY(aM2 hE3)o21"notnotnot","!!!(x)"},
#define UA {oB h03,aK2(aM2 h03)LNG_ONLY(aM2 h03)o21"notnotnot2","!x&!x"},
#define WA {oB oF3,aK2(aM2 oF3)LNG_ONLY(aM2 oF3)o21"sqr_nxx","(-x)*x"},
#define YA {oB oG3,aK2(aM2 oG3)LNG_ONLY(aM2 oG3)o21"sqr_xnx","x*(-x)"},
#define SB {oB Sqr_xx,aK2(aM2 Sqr_xx)LNG_ONLY(aM2 Sqr_xx)o21"sqr_xx","x*x"},
#define TB {2 gN2 d73,aK2(aM2 d73)LNG_ONLY(aM2 d73)wK"sqr_ynxx","y*-x*x"},
#define UB {2 gN2 d83,aK2(aM2 d83)LNG_ONLY(aM2 d83)wK"sqr_yxnx","y*x*-x"},
#define WB {2 gN2 oH3,aK2(aM2 oH3)LNG_ONLY(aM2 oH3)wK"sqr_yxx","y*x*x"},
#define YB {1 qB2 1 qL oI3,aK2(aM2 oI3)LNG_ONLY(aM2 oI3)q5"/xaddnot","!(x+4" mQ
#define SC {1 qB2 1 qL h13,aK2(aM2 h13)LNG_ONLY(aM2 h13)q5"/xaddnotnot","!!(x+4" mQ
#define TC {oB Xxdup,aK2(aM2 Xxdup)LNG_ONLY(aM2 Xxdup)q5"/xxdup","sub(x,x)"},
#define UC {2 gN2 d93,aK2(aM2 d93)LNG_ONLY(aM2 d93)"x" g3"/xxsqrdup","y*abs(x)*" m01},
#define WC {q92 q7 oD3,aK2(aJ2 oD3)LNG_ONLY(aJ2 oD3)gV1"absnzge","sub(" m01" >= if(" gO2"), abs(x)" dW2"(if(1,1,0)-1))"},
#define YC {q92 q7 oE3,aK2(aJ2 oE3)LNG_ONLY(aJ2 oE3)gV1"absnzlt","sub(" m01" < if(" gO2"), abs(x) < (if(1,1,0)-1))"},
#define SD {o31 gL3,aK2(aJ2 gL3)LNG_ONLY(aJ2 gL3)qR"addconstmul","5*(if(" gO2")+x+y" mQ
#define TD {o31 qS3,aK2(aJ2 qS3)LNG_ONLY(aJ2 qS3)qR"addmulconstmul","5*(if(" gO2")*y+x)"},
#define UD {o31 g73,aK2(aJ2 g73)LNG_ONLY(aJ2 g73)qR"addnegmulneg","-5 + (if(1,5,0)*x*y" mQ
#define WD {o31 g83,aK2(aJ2 g83)LNG_ONLY(aJ2 g83)qR"addnegmulpos","(if(1,-5,0)*y" wA2"if(1,5,0)*x)"},
#define YD g8 qY3,aK2(aJ2 qY3)LNG_ONLY(aJ2 qY3)qR"cmpeq_add_imm",gA1 q32
#define SE hW mV2,aK2(aJ2 mV2)LNG_ONLY(aJ2 mV2)gV1"cmpeq_add_reduce",dV" = " gZ},
#define TE g8 mW2,aK2(aJ2 mW2)LNG_ONLY(aJ2 mW2)qR"cmpeq_addadd_imm",o3") = " hX
#define UE mT g93,aK2(aJ2 g93)LNG_ONLY(aJ2 g93)qR"cmpeq_minma" dA3"=" dB3
#define WE mT mX2,aK2(aJ2 mX2)LNG_ONLY(aJ2 mX2)qR"cmpeq_minma" dC3"=" dE3
#define YE g8 mD2,aK2(aJ2 mD2)LNG_ONLY(aJ2 mD2)qR"cmpeq_mul_imm_neg",dD1 q32
#define SF g8 mE2,aK2(aJ2 mE2)LNG_ONLY(aJ2 mE2)qR"cmpeq_mul_imm_pos",o41 q32
#define TF g8 aV2,aK2(aJ2 aV2)LNG_ONLY(aJ2 aV2)qR"cmpeq_mulmul_imm_neg",m11" = " hX
#define UF g8 aW2,aK2(aJ2 aW2)LNG_ONLY(aJ2 aW2)qR"cmpeq_mulmul_imm_pos",m21" = " hX
#define WF g8 qZ3,aK2(aJ2 qZ3)LNG_ONLY(aJ2 qZ3)qR"cmpge_add_imm",gA1 aC1
#define YF hW mZ2,aK2(aJ2 mZ2)LNG_ONLY(aJ2 mZ2)gV1"cmpge_add_reduce",dV dW2 gZ},
#define SG g8 q03,aK2(aJ2 q03)LNG_ONLY(aJ2 q03)qR"cmpge_addadd_imm",o3")" dW2 hX
#define TG mT gA3,aK2(aJ2 gA3)LNG_ONLY(aJ2 gA3)qR"cmpge_minma" dA3">=" dB3
#define UG mT q13,aK2(aJ2 q13)LNG_ONLY(aJ2 q13)qR"cmpge_minma" dC3">=" dE3
#define WG g8 mF2,aK2(aJ2 mF2)LNG_ONLY(aJ2 mF2)qR"cmpge_mul_imm_neg",dD1 aC1
#define YG g8 mG2,aK2(aJ2 mG2)LNG_ONLY(aJ2 mG2)qR"cmpge_mul_imm_pos",o41 aC1
#define SH g8 aX2,aK2(aJ2 aX2)LNG_ONLY(aJ2 aX2)qR"cmpge_mulmul_imm_neg",m11 dW2 hX
#define TH g8 aY2,aK2(aJ2 aY2)LNG_ONLY(aJ2 aY2)qR"cmpge_mulmul_imm_pos",m21 dW2 hX
#define UH g8 g03,aK2(aJ2 g03)LNG_ONLY(aJ2 g03)qR"cmpgt_add_imm",gA1 q42
#define WH hW q23,aK2(aJ2 q23)LNG_ONLY(aJ2 q23)gV1"cmpgt_add_reduce",dV" > " gZ},
#define YH g8 q33,aK2(aJ2 q33)LNG_ONLY(aJ2 q33)qR"cmpgt_addadd_imm",o3") > " hX
#define SI mT gB3,aK2(aJ2 gB3)LNG_ONLY(aJ2 gB3)qR"cmpgt_minma" dA3">" dB3
#define TI mT q43,aK2(aJ2 q43)LNG_ONLY(aJ2 q43)qR"cmpgt_minma" dC3">" dE3
#define UI g8 mH2,aK2(aJ2 mH2)LNG_ONLY(aJ2 mH2)qR"cmpgt_mul_imm_neg",dD1 q42
#define WI g8 mI2,aK2(aJ2 mI2)LNG_ONLY(aJ2 mI2)qR"cmpgt_mul_imm_pos",o41 q42
#define YI g8 aZ2,aK2(aJ2 aZ2)LNG_ONLY(aJ2 aZ2)qR"cmpgt_mulmul_imm_neg",m11" > " hX
#define SJ g8 m02,aK2(aJ2 m02)LNG_ONLY(aJ2 m02)qR"cmpgt_mulmul_imm_pos",m21" > " hX
#define TJ g8 g13,aK2(aJ2 g13)LNG_ONLY(aJ2 g13)qR"cmple_add_imm",gA1 aD1
#define UJ hW q53,aK2(aJ2 q53)LNG_ONLY(aJ2 q53)gV1"cmple_add_reduce",dV dX2 gZ},
#define WJ g8 q63,aK2(aJ2 q63)LNG_ONLY(aJ2 q63)qR"cmple_addadd_imm",o3")" dX2 hX
#define YJ mT gC3,aK2(aJ2 gC3)LNG_ONLY(aJ2 gC3)qR"cmple_minma" dA3"<=" dB3
#define SK mT q73,aK2(aJ2 q73)LNG_ONLY(aJ2 q73)qR"cmple_minma" dC3"<=" dE3
#define TK g8 mJ2,aK2(aJ2 mJ2)LNG_ONLY(aJ2 mJ2)qR"cmple_mul_imm_neg",dD1 aD1
#define UK g8 mK2,aK2(aJ2 mK2)LNG_ONLY(aJ2 mK2)qR"cmple_mul_imm_pos",o41 aD1
#define WK g8 m12,aK2(aJ2 m12)LNG_ONLY(aJ2 m12)qR"cmple_mulmul_imm_neg",m11 dX2 hX
#define YK g8 m22,aK2(aJ2 m22)LNG_ONLY(aJ2 m22)qR"cmple_mulmul_imm_pos",m21 dX2 hX
#define SL g8 g23,aK2(aJ2 g23)LNG_ONLY(aJ2 g23)qR"cmplt_add_imm",gA1 q52
#define TL hW q83,aK2(aJ2 q83)LNG_ONLY(aJ2 q83)gV1"cmplt_add_reduce",dV" < " gZ},
#define UL g8 q93,aK2(aJ2 q93)LNG_ONLY(aJ2 q93)qR"cmplt_addadd_imm",o3") < " hX
#define WL mT gD3,aK2(aJ2 gD3)LNG_ONLY(aJ2 gD3)qR"cmplt_minma" dA3"<" dB3
#define YL mT qA3,aK2(aJ2 qA3)LNG_ONLY(aJ2 qA3)qR"cmplt_minma" dC3"<" dE3
#define SM g8 mL2,aK2(aJ2 mL2)LNG_ONLY(aJ2 mL2)qR"cmplt_mul_imm_neg",dD1 q52
#define TM g8 mM2,aK2(aJ2 mM2)LNG_ONLY(aJ2 mM2)qR"cmplt_mul_imm_pos",o41 q52
#define UM g8 m32,aK2(aJ2 m32)LNG_ONLY(aJ2 m32)qR"cmplt_mulmul_imm_neg",m11" < " hX
#define WM g8 m42,aK2(aJ2 m42)LNG_ONLY(aJ2 m42)qR"cmplt_mulmul_imm_pos",m21" < " hX
#define YM g8 g33,aK2(aJ2 g33)LNG_ONLY(aJ2 g33)qR"cmpne_add_imm",gA1 aE1
#define SN hW qB3,aK2(aJ2 qB3)LNG_ONLY(aJ2 qB3)gV1"cmpne_add_reduce",dV dY2 gZ},
#define TN g8 qC3,aK2(aJ2 qC3)LNG_ONLY(aJ2 qC3)qR"cmpne_addadd_imm",o3")" dY2 hX
#define UN mT gE3,aK2(aJ2 gE3)LNG_ONLY(aJ2 gE3)qR"cmpne_minma" dA3"!=" dB3
#define WN mT qD3,aK2(aJ2 qD3)LNG_ONLY(aJ2 qD3)qR"cmpne_minma" dC3"!=" dE3
#define YN g8 mN2,aK2(aJ2 mN2)LNG_ONLY(aJ2 mN2)qR"cmpne_mul_imm_neg",dD1 aE1
#define SO g8 mO2,aK2(aJ2 mO2)LNG_ONLY(aJ2 mO2)qR"cmpne_mul_imm_pos",o41 aE1
#define TO g8 m52,aK2(aJ2 m52)LNG_ONLY(aJ2 m52)qR"cmpne_mulmul_imm_neg",m11 dY2 hX
#define UO g8 m62,aK2(aJ2 m62)LNG_ONLY(aJ2 m62)qR"cmpne_mulmul_imm_pos",m21 dY2 hX
#define WO g8 g43,aK2(aJ2 g43)LNG_ONLY(aJ2 g43)qR"cmpzz_add_imm" dM q62 aS1 q62 wB1 q62 aG1 q62 wC1 q62 aF1 gA1 q32
#define YO hW qE3,aK2(aJ2 qE3)LNG_ONLY(aJ2 qE3)gV1"cmpzz_add_reduce" dM dZ2" < " gZ a9 dZ2 dX2 gZ aA dZ2" > " gZ aB dZ2 dW2 gZ aC dZ2 dY2 gZ d6 dV" = " gZ},
#define SP g8 qF3,aK2(aJ2 qF3)LNG_ONLY(aJ2 qF3)qR"cmpzz_addadd_imm" dM" " o3 gB1 o3 gC1 o3 gE1 o3 gF1 o3")" w61 o3") = " hX
#define TP mT gF3,aK2(aJ2 gF3)LNG_ONLY(aJ2 gF3)qR"cmpzz_minmax" dM gG3"< " gR3 a9 gG3"<= " gR3 aA gG3"> " gR3 aB gG3">= " gR3 aC gG3"!= " gR3" +  0x0020 *" gG3"=" dB3
#define UP mT qG3,aK2(aJ2 qG3)LNG_ONLY(aJ2 qG3)qR"cmpzz_minmax_rev" dM gG3"<" dD3 a9 gG3"<=" dD3 aA gG3">" dD3 aB gG3">=" dD3 aC gG3"!=" dD3" +  0x0020 *" gG3"=" dE3
#define WP g8 mP2,aK2(aJ2 mP2)LNG_ONLY(aJ2 mP2)qR"cmpzz_mul_imm_neg" dM g51 aS1 g51 wB1 g51 aG1 g51 wC1 g51 aF1 dD1 q32
#define YP g8 mQ2,aK2(aJ2 mQ2)LNG_ONLY(aJ2 mQ2)qR"cmpzz_mul_imm_pos" dM g61 aS1 g61 wB1 g61 aG1 g61 wC1 g61 aF1 o41 q32
#define SQ g8 m72,aK2(aJ2 m72)LNG_ONLY(aJ2 m72)qR"cmpzz_mulmul_imm_neg" dM" " gJ1 gB1 gJ1 gC1 gJ1 gE1 gJ1 gF1 m11 w61 m11" = " hX
#define TQ g8 m82,aK2(aJ2 m82)LNG_ONLY(aJ2 m82)qR"cmpzz_mulmul_imm_pos" dM" " wL"4" gB1 wL"4" gC1 wL"4" gE1 wL"4" gF1 m21 w61 m21" = " hX
#define UQ mT hF3,aK2(aJ2 hF3)LNG_ONLY(aJ2 hF3)qR"ge_and_eq",oX2 dE1
#define WQ mT hG3,aK2(aJ2 hG3)LNG_ONLY(aJ2 hG3)qR"ge_and_le",oX2 hV1 mQ
#define YQ mT hH3,aK2(aJ2 hH3)LNG_ONLY(aJ2 hH3)qR"ge_and_ne",oX2 dF1
#define SR mT dF3,aK2(aJ2 dF3)LNG_ONLY(aJ2 dF3)qR"ge_or_eq",oY2 dE1
#define TR mT dG3,aK2(aJ2 dG3)LNG_ONLY(aJ2 dG3)qR"ge_or_le",oY2 hV1 mQ
#define UR mT dH3,aK2(aJ2 dH3)LNG_ONLY(aJ2 dH3)qR"ge_or_ne",oY2 dF1
#define WR mT hI3,aK2(aJ2 hI3)LNG_ONLY(aJ2 hI3)qR"gt_and_eq" m31 dE1
#define YR mT hJ3,aK2(aJ2 hJ3)LNG_ONLY(aJ2 hJ3)qR"gt_and_ge" m31 aY},
#define SS mT hK3,aK2(aJ2 hK3)LNG_ONLY(aJ2 hK3)qR"gt_and_le" m31 hV1 mQ
#define TS mT hL3,aK2(aJ2 hL3)LNG_ONLY(aJ2 hL3)qR"gt_and_ne" m31 dF1
#define US mT dI3,aK2(aJ2 dI3)LNG_ONLY(aJ2 dI3)qR"gt_or_eq" m81 dE1
#define WS mT dJ3,aK2(aJ2 dJ3)LNG_ONLY(aJ2 dJ3)qR"gt_or_ge" m81 aY},
#define YS mT dK3,aK2(aJ2 dK3)LNG_ONLY(aJ2 dK3)qR"gt_or_le" m81 hV1 mQ
#define ST mT dL3,aK2(aJ2 dL3)LNG_ONLY(aJ2 dL3)qR"gt_or_ne" m81 dF1
#define TT aP1 If10,aK2(aJ2 If10)LNG_ONLY(aJ2 If10)gV1"if10",o0",1,0) + 10*" o0",0,1)" w83"+ 100*" o0">0,1,0) + 1000*" o0">0,0,1" mQ
#define UT {2,mI qT3,aK2(aJ2 qT3)LNG_ONLY(aJ2 qT3)mM1"tract_abs",o0", abs(x+2), abs(y+5))"},
#define WT {2,mI qU3,aK2(aJ2 qU3)LNG_ONLY(aJ2 qU3)mM1"tract_add",o0", y+2, y+" mJ1
#define YT {2,mI qM3,aK2(aJ2 qM3)LNG_ONLY(aJ2 qM3)mM1"tract_add1",o0", y+2, y" mQ
#define SU {2,mI qN3,aK2(aJ2 qN3)LNG_ONLY(aJ2 qN3)mM1"tract_add2",o0", y, y+2" mQ
#define TU {o51 mR2,aK2(aJ2 mR2)LNG_ONLY(aJ2 mR2)m91"tract_and1_l",o0", y&z, y<1" mQ
#define UU {o51 m92,aK2(aJ2 m92)LNG_ONLY(aJ2 m92)m91"tract_and1_nl",o0", y&z, z" mQ
#define WU {o51 mS2,aK2(aJ2 mS2)LNG_ONLY(aJ2 mS2)m91"tract_and2_l",o0", y<1, y&z" mQ
#define YU {o51 mA2,aK2(aJ2 mA2)LNG_ONLY(aJ2 mA2)m91"tract_and2_nl",o0", z, y&z" mQ
#define SV {2,mI If_extract_div,aQ2(aJ2 If_extract_div)mM1"tract_div",o0", y/x, y/2" mQ
#define TV {2,mI qV3,aK2(aJ2 qV3)LNG_ONLY(aJ2 qV3)mM1"tract_min",o0", min(y,2), min(y,5))"},
#define UV {2,mI qW3,aK2(aJ2 qW3)LNG_ONLY(aJ2 qW3)mM1"tract_mul",o0", y*2, y*" mJ1
#define WV {2,mI qO3,aK2(aJ2 qO3)LNG_ONLY(aJ2 qO3)mM1"tract_mul1",o0", y*2, y" mQ
#define YV {2,mI qP3,aK2(aJ2 qP3)LNG_ONLY(aJ2 qP3)mM1"tract_mul2",o0", y, y*2" mQ
#define SW {o51 qH3,aK2(aJ2 qH3)LNG_ONLY(aJ2 qH3)m91"tract_or1_l",o0", y|z, y<1" mQ
#define TW {o51 mT2,aK2(aJ2 mT2)LNG_ONLY(aJ2 mT2)m91"tract_or1_nl",o0", y|z, z" mQ
#define UW {o51 qI3,aK2(aJ2 qI3)LNG_ONLY(aJ2 qI3)m91"tract_or2_l",o0", y<1, y|z" mQ
#define WW {o51 mU2,aK2(aJ2 mU2)LNG_ONLY(aJ2 mU2)m91"tract_or2_nl",o0", z, y|z" mQ
#define YW {1,3,5,1,q7 gH3,aK2(aJ2 gH3)LNG_ONLY(aJ2 gH3)gV1"if_join_add2","x + 10 +" gG1"<4, 3,4" mQ
#define SX {1,3,5,1,q7 gI3,aK2(aJ2 gI3)LNG_ONLY(aJ2 gI3)gV1"if_join_mul2","x * 10 *" gG1"<4, 3,4" mQ
#define TX aD2 Ifabs,aK2(aJ2 Ifabs)LNG_ONLY(aJ2 Ifabs)gV1"ifabs","1" qT1"< 0,-x" qJ3"   10" qT1"<=0,-x" qJ3"  100" qT1"> 0,-x" qJ3" 1000" qT1">=0,-x" qJ3"10000" qT1"< 0,x" oJ3 w83" 100000" qT1"<=0,x" oJ3 w83"1000000" qT1"> 0,x" oJ3"10000000" qT1">=0,x,-" oW2
#define UX {4 o61 oK3,aK2(aJ2 oK3)LNG_ONLY(aJ2 oK3)"b,d," qR"ifmerge",o0 g92"y,x,b)" g92"y,x,d)) +  if(b,if(d,y,x)" g92"d,b," oW2
#define WX {4 o61 dM3,aK2(aJ2 dM3)LNG_ONLY(aJ2 dM3)"a,b," qR"ifmerge2",o0 g92"y,a,b)" g92"b,a,b))"},
#define YX {4 o61 hM3,aK2(aJ2 hM3)LNG_ONLY(aJ2 hM3)"a,b," qR"ifmerge2b",o0 g92"y,a,b)" g92"b,b,a))"},
#define SY mT Ifnop,aK2(aJ2 Ifnop)LNG_ONLY(aJ2 Ifnop)qR"ifnop",o0",y,y" mQ
#define TY {dG1 L_abs,aK2(aJ2 L_abs)LNG_ONLY(aJ2 L_abs)qR"l_abs","(x+2) & abs(x) & " dN3
#define UY {dG1 dO3,aK2(aJ2 dO3)LNG_ONLY(aJ2 dO3)qR"l_mulabs","(x*abs(y)) & " dN3
#define WY {dG1 dP3,aK2(aJ2 dP3)LNG_ONLY(aJ2 dP3)qR"l_mulneg","(x*y*-5) & " dN3
#define YY {dG1 dQ3,aK2(aJ2 dQ3)LNG_ONLY(aJ2 dQ3)qR"l_notnot","(x+2) & !!x & " dN3
#define SZ mT hN3,aK2(aJ2 hN3)LNG_ONLY(aJ2 hN3)qR"le_and_eq",dR3"& " dE1
#define TZ mT hO3,aK2(aJ2 hO3)LNG_ONLY(aJ2 hO3)qR"le_and_ne",dR3"& " dF1
#define UZ mT dS3,aK2(aJ2 dS3)LNG_ONLY(aJ2 dS3)qR"le_or_eq",dR3"| " dE1
#define WZ mT dT3,aK2(aJ2 dT3)LNG_ONLY(aJ2 dT3)qR"le_or_ne",dR3"| " dF1
#define YZ mT hP3,aK2(aJ2 hP3)LNG_ONLY(aJ2 hP3)qR"lt_and_eq" q72 dE1
#define Sa mT hQ3,aK2(aJ2 hQ3)LNG_ONLY(aJ2 hQ3)qR"lt_and_ge" q72 aY},
#define Ta mT hR3,aK2(aJ2 hR3)LNG_ONLY(aJ2 hR3)qR"lt_and_gt" q72"(x > y" mQ
#define Ua mT hS3,aK2(aJ2 hS3)LNG_ONLY(aJ2 hS3)qR"lt_and_le" q72 hV1 mQ
#define Wa mT hT3,aK2(aJ2 hT3)LNG_ONLY(aJ2 hT3)qR"lt_and_ne" q72 dF1
#define Ya mT dU3,aK2(aJ2 dU3)LNG_ONLY(aJ2 dU3)qR"lt_or_eq" q82 dE1
#define Sb mT dV3,aK2(aJ2 dV3)LNG_ONLY(aJ2 dV3)qR"lt_or_ge" q82 aY},
#define Tb mT dW3,aK2(aJ2 dW3)LNG_ONLY(aJ2 dW3)qR"lt_or_gt" q82"(x > y" mQ
#define Ub mT dX3,aK2(aJ2 dX3)LNG_ONLY(aJ2 dX3)qR"lt_or_le" q82 hV1 mQ
#define Wb mT dY3,aK2(aJ2 dY3)LNG_ONLY(aJ2 dY3)qR"lt_or_ne" q82 dF1
#define Yb {o51 gM3,aK2(aJ2 gM3)LNG_ONLY(aJ2 gM3)aG"mergemulabs","abs(x)*abs(y)*z"},
#define Sc {3,0,4,1,q7 gN3,aK2(aJ2 gN3)LNG_ONLY(aJ2 gN3)aG"mixedminmax","max(z,min(x,max(max(z,y),x)))" hX3"10*min(z,max(x,min(y,x)))" hX3"100*min(max(x,y),min(y,z)) +  1000*max(min(x,y),max(y,z))"},
#define Tc mT Nand2,aK2(aJ2 Nand2)LNG_ONLY(aJ2 Nand2)qR"nand2",hU3},
#define Uc gU2 hV3,aK2(aJ2 hV3)LNG_ONLY(aJ2 hV3)aG"nand2plus",hU3" | z"},
#define Wc gU2 Nand3,aK2(aJ2 Nand3)LNG_ONLY(aJ2 Nand3)aG"nand3",hU3" | !z"},
#define Yc mT Nor2,aK2(aJ2 Nor2)LNG_ONLY(aJ2 Nor2)qR"nor2",hW3},
#define Sd gU2 dZ3,aK2(aJ2 dZ3)LNG_ONLY(aJ2 dZ3)aG"nor2plus",hW3" & z"},
#define Td gU2 Nor3,aK2(aJ2 Nor3)LNG_ONLY(aJ2 Nor3)aG"nor3",hW3" & !z"},
#define Ud mT Not_eq,aK2(aJ2 Not_eq)LNG_ONLY(aJ2 Not_eq)qR"not_eq",o0" = " mB2
#define Wd mT Not_ge,aK2(aJ2 Not_ge)LNG_ONLY(aJ2 Not_ge)qR"not_ge",o0" >= " mB2
#define Yd mT Not_gt,aK2(aJ2 Not_gt)LNG_ONLY(aJ2 Not_gt)qR"not_gt",o0" > " mB2
#define Se mT Not_le,aK2(aJ2 Not_le)LNG_ONLY(aJ2 Not_le)qR"not_le",o0" <= " mB2
#define Te mT Not_lt,aK2(aJ2 Not_lt)LNG_ONLY(aJ2 Not_lt)qR"not_lt",o0" < " mB2
#define Ue mT Not_ne,aK2(aJ2 Not_ne)LNG_ONLY(aJ2 Not_ne)qR"not_ne",o0" != " mB2
#define We {2,mI Notnot,aK2(aJ2 Notnot)LNG_ONLY(aJ2 Notnot)qR"notnot","!!x + if(y, 1,0" mQ
#define Ye {q92 q7 oI3,aK2(aJ2 oI3)LNG_ONLY(aJ2 oI3)"x" q8"/xaddnot","!(x+if(1,4,4))"},
#define Sf {q92 q7 h13,aK2(aJ2 h13)LNG_ONLY(aJ2 h13)"x" q8"/xaddnotnot","!!(x+if(1,4,4))"},
#define Tf {1,-aH1 t1,aK2(aO2 t1)LNG_ONLY(aO2 t1)"x",oL"1","x+max(0, min(-2,0))"},
#define Uf {1,-aH1 t2,aK2(aO2 t2)LNG_ONLY(aO2 t2)"x",oL"2","min(x,min(1," oW2
#define Wf {1,-2,2,1,hH t3,aK2(aO2 t3)LNG_ONLY(aO2 t3)"x",oL"3","sub(  (!x & !!x) ,  (!x | !!x)  " mQ
#define Yf {2,-2,2,1,hH t4,aK2(aO2 t4)LNG_ONLY(aO2 t4)"x,y",oL"4","sub(!(x-y), !!(x-y))"},
#define Sg {q92 hH t6,aK2(aO2 t6)LNG_ONLY(aO2 t6)"x",oL"6","sub(!(x+4), !!(x+3))"},
#define Tg {1,-aH1 t36,aK2(aO2 t36)LNG_ONLY(aO2 t36)"x",oL"36","-if(x<0, x, -x) + -if(x<5, 2, 3" mQ
#define Ug {2,-2,2,1,hH t60,aK2(aO2 t60)LNG_ONLY(aO2 t60)"x,y",oL"60","sqr(x) | sub(x,y) | value()"},
#define Wg {2,-20,20,h4 t16,aK2(aP2 t16)LNG_ONLY(aP2 t16)gV2"16",o0"<0, if(y<0, x+y, x-y), if(y>0, x*y, x+2*y))"},
#define Yg {2,-20,20,h4 t17,aK2(aP2 t17)LNG_ONLY(aP2 t17)gV2"17","sqr(x)+sub(x,y)+psqr(y)+psub(y+1,x-2)-1"},
#define Sh {2,-100,100,h4 t19,aK2(aP2 t19)LNG_ONLY(aP2 t19)gV2"19","(x<y)+10" wZ1"<=y)+100" wZ1">y)+1000" wZ1">=y)+10000" wZ1"=y)+100000" wZ1"!=y)+  (x&y)*2+(x|y)*20+(!x)*200+(!!x)*2000+4*!((x<y)&(x<3))+40*!!(!(x>y)|(x>3))"},
#define Th {2,-100,100,h4 t20,aK2(aP2 t20)LNG_ONLY(aP2 t20)gV2"20","(!(x != y) & !x) + !(!(!(!y)))"},
#define Uh {1,-gY2 t21,aK2(aP2 t21)LNG_ONLY(aP2 t21)"x",oT"21","sqr(x)+value()-pvalue ( " mQ
#define Wh {1,-wZ2 h4 t24,aK2(aP2 t24)LNG_ONLY(aP2 t24)"x",oT"24","(min(x, min(1," wD1" min(x, 1))/2 + min(x, 1)*3 + max(0, min(-2,0))"},
#define Yh {2 qB2 h4 t29,aK2(aP2 t29)LNG_ONLY(aP2 t29)gV2"29","x-y*1"},
#define Si {4 qB2 h4 t34,aK2(aP2 t34)LNG_ONLY(aP2 t34)"t,う,お,早",oT"34","お+早*う-t"},
#define Ti {3,-gY2 t35,aK2(aP2 t35)LNG_ONLY(aP2 t35)"A_very_long_variable_name_1,A_very_long_variable_name_2,Yet_a_third_very_long_variable_name",oT"35","A_very_long_variable_name_1-A_very_long_variable_name_2+  Yet_a_third_very_long_variable_name*A_very_long_variable_name_1"},
#define Ui {2,-gY2 t50,aK2(aP2 t50)LNG_ONLY(aP2 t50)gV2"50","(x<y | y<x)" o03"2" wZ1"<y & y<x)" o03"4" wZ1 oZ2" y<=x)" o03"8" wZ1"<y & " oL3"   16" wZ1"<y | " oL3" " w93 wZ1 oZ2" x>=y)" o03"64" wZ1"<=y | x>=y)" o03"128" wZ1"!=y & x=y)" o03"256" wZ1"!=y & " oL3"512" wZ1 oZ2" x=y" mQ
#define Wi {2,-11,11,h4 t58,aK2(aP2 t58)LNG_ONLY(aP2 t58)gV2"58","(-x < 3)" mB1"-1 > 5)" mB1"-3 < 10)" mB1"-3 < y*7) +  (x*4 < y*7)" mB1"6 < y*-3" wA2"-x < 11" wA2"5 < -y" mQ
#define Yi {3,-8,7,h4 I1,aQ2(aP2 I1)mC1"i1","1+2+3-4*5*6/3+10/2-9%2 + (x+y - 11*x + z/10 + x/(z+31))"},
#define Sj {3,-7,7,h4 I2,aQ2(aP2 I2)mC1"i2","if(abs(x*y) < 20 | x+y > 30 & z > 5, min(x,2*y), max(y,z*2))"},
#define Tj {3,1,7,h4 I3,aQ2(aP2 I3)mC1"i3","(x+y) + 2" wZ1"-z) + 3*(x*y) + 4*(y/z) + 5" wZ1"%z)" hX3"6" wZ1"<y) + 7" wZ1"<=z) + 8" wZ1">2" w02" 9*(y>=3" w02" 10*(x+y!=z) +  11*(100+x) + 12*(101-y) + 13*(102" w02" 14*(103/x)"},
#define Uj {2,qU1 Add_d,aK2(aN2 Add_d)wM"add_d","x+y"},
#define Wj {3,qU1 Addsub_d,aK2(aN2 Addsub_d)gZ2,g6"addsub_d","x+y+x+x-z+x"},
#define Yj h6 And_d,aK2(aN2 And_d)wM"and_d","x&y"},
#define Sk h6 Cmpeq_d,aK2(aN2 Cmpeq_d)wM"cmpeq_d","x=y"},
#define Tk h6 Cmpge_d,aK2(aN2 Cmpge_d)wM"cmpge_d","x>=y"},
#define Uk h6 Cmpgt_d,aK2(aN2 Cmpgt_d)wM"cmpgt_d","x>y"},
#define Wk h6 Cmple_d,aK2(aN2 Cmple_d)wM"cmple_d","x<=y"},
#define Yk h6 Cmplt_d,aK2(aN2 Cmplt_d)wM"cmplt_d","x<y"},
#define Sl h6 Cmpne_d,aK2(aN2 Cmpne_d)wM"cmpne_d","x!=y"},
#define Tl {2,wY Div_d,aK2(aN2 Div_d)wM"div_d","(x-0.25)/y"},
#define Ul {3,wY Divmul_d,aK2(aN2 Divmul_d)gZ2,g6"divmul_d","x*y*x*x/z" wZ1"-0.25" mQ
#define Wl {1,-7,6,N(0.6),qM Inv_d,aK2(aN2 Inv_d)qB,g6"inv_d","1/x"},
#define Yl {2,wY Mul_d,aK2(aN2 Mul_d)wM"mul_d","x*y"},
#define Sm {1,qU1 Neg_d,aK2(aN2 Neg_d)qB,g6"neg_d","-x"},
#define Tm {1,aD,qM Not_d,aK2(aN2 Not_d)qB,g6"not_d","!x"},
#define Um {1,aD,qM Notnot_d,aK2(aN2 Notnot_d)qB,g6"notnot_d","!!x"},
#define Wm h6 Or_d,aK2(aN2 Or_d)wM"or_d","x|y"},
#define Ym {2,qU1 Sub_d,aK2(aN2 Sub_d)wM"sub_d","x-y"},
#define Sn {1,oX1 N(0.5)w8 Abs_d,aK2(aR2 Abs_d)qO"/abs_d",m01},
#define Tn {3,aD w8 If_d,aK2(aR2 If_d)gZ2 wB"/if_d",o0",y,z" mQ
#define Un {1,-4000,wQ2 Int,aK2(aR2 Int)qO"/int","int(x)"},
#define Wn w31 Absneverneg,aK2(aM2 Absneverneg)qZ"absneverneg","abs(acos" qV1
#define Yn w31 Absnot2,aK2(aM2 Absnot2)qZ"absnot2","!acos(x)"},
#define So {2,-oA Absnot3,aK2(aM2 Absnot3)dH1"absnot3","!(!(x&y))"},
#define To w31 Absnot4,aK2(aM2 Absnot4)qZ"absnot4","!(!acos" qV1
#define Uo {1,1,3,N(0.1)qL Acoshcosh,aK2(aM2 Acoshcosh)qZ"acoshcosh","cosh(" w12 qV1
#define Wo {1,N(1.7),N(3.7),N(0.28)qL Acoshsinh,aK2(aM2 Acoshsinh)qZ w12 gA2,gA2"(" w12 qV1
#define Yo {1,-3,-3,N(0.7)qL Addexp,aK2(aM2 Addexp)qZ"addexp","exp(x+4" mQ
#define Sp {1,-3,-3,N(0.7)qL Addexp2,aK2(aM2 Addexp2)qZ"addexp2","exp2(x+4" mQ
#define Tp gC Asinhcosh,aK2(aM2 Asinhcosh)qZ"asinhcosh","cosh(a" gA2 qV1
#define Up mZ Asinhsinh,aK2(aM2 Asinhsinh)qZ oW3 gA2,gA2"(a" gA2 qV1
#define Wp {2 q01 N(0.11)qL Atan2tan,aK2(aM2 Atan2tan)dH1"atan2tan","tan(" hZ2"(x,y))"},
#define Yp {1,aH Ceilneg,aK2(aM2 Ceilneg)qZ"ceilneg","ceil" a41
#define Sq {2,q81 Deg,aK2(aM2 Deg)dH1"deg","(" h12")*y + x*(" h12 wA2"y*(" h12"))*4"},
#define Tq {1 m7 N(0.5),dL2 Degxmul,aK2(aM2 Degxmul)qZ"degxmul","acos(x)*2"},
#define Uq {1 q01 1 qL Dupaddmulh,aK2(aM2 Dupaddmulh)qZ"dupaddmulh","(x+x)*0.5"},
#define Wq {2 q01 1 qL Dupaddmulmul7,aK2(aM2 Dupaddmulmul7)dH1"dupaddmulmul7","y*(x+x)*7"},
#define Yq {2 q01 1 qL Dupaddmulmulh,aK2(aM2 Dupaddmulmulh)dH1"dupaddmulmulh","y*(x+x)*0.5"},
#define Sr d41 Dupxpowmul,aK2(aM2 Dupxpowmul)qZ"dupxpowmul","x*(x^3" mQ
#define Tr {aJ1 Exp2div,aK2(aM2 Exp2div)dH1"exp2div","x/exp2(y" mQ
#define Ur mZ Exp2log2,aK2(aM2 Exp2log2)qZ"exp2log2","log2(exp2" qV1
#define Wr {aJ1 Expdiv,aK2(aM2 Expdiv)dH1"expdiv","x/" o02"y" mQ
#define Yr mZ Explog,aK2(aM2 Explog)qZ"explog","log(" o12
#define Ss mZ Explog2,aK2(aM2 Explog2)qZ"explog2","log2(" o12
#define Ts mZ Explog10,aK2(aM2 Explog10)qZ"explog10","log10(" o12
#define Us {1,aH Floorneg,aK2(aM2 Floorneg)qZ"floorneg","floor" a41
#define Ws {1,N(-1.5),N(1.5)oD1 qL Int,aK2(aM2 Int)qZ"int","x+" aI1 aI1"sub(int(1.1), int(1.6" o91"1.5" o91"-1.1" o91"-1.6" o91"-1.5))"},
#define Ys {1,aH Intceil,aK2(aM2 Intceil)qZ"intceil","ceil" a01
#define St {1,aH Intfloor,aK2(aM2 Intfloor)qZ"intfloor","floor" a01
#define Tt {1,aH Intint,aK2(aM2 Intint)qZ"intint","int" a01
#define Ut {1,aH Inttrunc,aK2(aM2 Inttrunc)qZ"inttrunc","trunc" a01
#define Wt {aJ1 Invdiv,aK2(aM2 Invdiv)dH1"invdiv","y/(1/x)"},
#define Yt {1 q01 2 qL Invinv,aK2(aM2 Invinv)qZ"invinv","1/(1/x)"},
#define Su {1,aH Negceil,aK2(aM2 Negceil)qZ"negceil","-ceil(x)"},
#define Tu {1,aH Negfloor,aK2(aM2 Negfloor)qZ"negfloor","-floor(x)"},
#define Uu {aJ1 Powdiv,aK2(aM2 Powdiv)qB g3"/powdiv","x/pow(x" wA1
#define Wu {1,hF1 Powhalf,aK2(aM2 Powhalf)w3"half",qC2",0.5" mQ
#define Yu {aJ1 Powinv,aK2(aM2 Powinv)qB g3"/powinv","1/pow(x" wA1
#define Sv {1,hF1 Powminushalf,aK2(aM2 Powminushalf)w3"minushalf",qC2",-0.5" mQ
#define Tv {1,1,5,1 qL Powminusone,aK2(aM2 Powminusone)w3"minusone",qC2",-1.0" mQ
#define Uv {1,hF1 Powminusthird,aK2(aM2 Powminusthird)w3"minusthird",qC2",(-1.0/3.0))"},
#define Wv {1,hF1 Powthird,aK2(aM2 Powthird)w3"third",qC2"," mG1"/3.0))"},
#define Yv {2,q81 Rad,aK2(aM2 Rad)dH1"rad","(" mE1")*y + x*(" mE1") + (x*(" mE1"))*4"},
#define Sw {1,-2,2,N(0.8)qL Radxmul,aK2(aM2 Radxmul)qZ"radxmul","cos" wL mE1")*4" mQ
#define Tw {1,q81 Sqrlog,aK2(aM2 Sqrlog)qZ"sqrlog","log" qD2
#define Uw {1,q81 Sqrlog2,aK2(aM2 Sqrlog2)qZ"sqrlog2","log2" qD2
#define Ww {1,q81 Sqrlog10,aK2(aM2 Sqrlog10)qZ"sqrlog10","log10" qD2
#define Yw {1,-2,2,N(0.8),dL2 Xmulrad,aK2(aM2 Xmulrad)wW"mulrad","cos" qL2
#define Sx {oB Xxfdup,aK2(aM2 Xxfdup)LNG_ONLY(0)q5"/xxfdup","sub(sin(x),sin(x))"},
#define Tx aD2 Abscos,aK2(aJ2 Abscos)gW"abscos","cos(sqrt" dL1"))) + sqrt" dL1"))"},
#define Ux aD2 Abscosh,aK2(aJ2 Abscosh)gW"abscosh","cosh(sqrt" dL1"))) + sqrt" dL1"))"},
#define Wx {1 m7 N(0.1),q7 Acoscos,aK2(aJ2 Acoscos)gW"acoscos","cos(acos" qV1
#define Yx {1,N(1.7),N(3.7),N(0.28),q7 Acoshsinh,aK2(aJ2 Acoshsinh)gW w12 gA2,gA2"(if(1,acosh(x),0))"},
#define Sy {2 oD1,oC1 q7 Addlog,aK2(aJ2 Addlog)qX1"addlog","log(x)+log(y" mQ
#define Ty hH2 Addsin2cos2,aK2(aJ2 Addsin2cos2)gW"addsin2cos2",a51"^2 + cos(x)^2"},
#define Uy {1,N(-0.7),N(0.7),N(0.28),q7 Asinhcosh,aK2(aJ2 Asinhcosh)gW"asinhcosh","cosh(if(1,a" gA2"(x),0))"},
#define Wy {1 m7 N(0.1),q7 Asinsin,aK2(aJ2 Asinsin)gW"asinsin","sin(asin(x))"},
#define Yy dC Cmpeq_pow_imm_negneg,aK2(aJ2 Cmpeq_pow_imm_negneg)aH2 hV" = " d63
#define Sz dC Cmpeq_pow_imm_negpos,aK2(aJ2 Cmpeq_pow_imm_negpos)aH2 hY" = " aU2
#define Tz hW Cmpeq_pow_imm_posneg,aK2(aJ2 Cmpeq_pow_imm_posneg)aH2 d2" = " qL3
#define Uz hW Cmpeq_pow_imm_pospos,aK2(aJ2 Cmpeq_pow_imm_pospos)aH2 d3" = " gO3
#define Wz hW Cmpeq_pow_imm_pospos_base,aK2(aJ2 Cmpeq_pow_imm_pospos_base)aH2 mC2"= " wO
#define Yz g8 Cmpeq_powpow_imm_base,aK2(aJ2 Cmpeq_powpow_imm_base)qX1 oA1 hF" = " a1
#define S_ dC Cmpge_pow_imm_negneg,aK2(aJ2 Cmpge_pow_imm_negneg)hW1 hV" >= " d63
#define T_ dC Cmpge_pow_imm_negpos,aK2(aJ2 Cmpge_pow_imm_negpos)hW1 hY" >= " aU2
#define U_ hW Cmpge_pow_imm_posneg,aK2(aJ2 Cmpge_pow_imm_posneg)hW1 d2" >= " qL3
#define W_ hW Cmpge_pow_imm_pospos,aK2(aJ2 Cmpge_pow_imm_pospos)hW1 d3" >= " gO3
#define Y_ hW Cmpge_pow_imm_pospos_base,aK2(aJ2 Cmpge_pow_imm_pospos_base)hW1 mC2">= " wO
#define S01 g8 Cmpge_powpow_imm_base,aK2(aJ2 Cmpge_powpow_imm_base)qX1"cmpge_" hF dW2 a1
#define T01 dC Cmpgt_pow_imm_negneg,aK2(aJ2 Cmpgt_pow_imm_negneg)hX1 hV" > " d63
#define U01 dC Cmpgt_pow_imm_negpos,aK2(aJ2 Cmpgt_pow_imm_negpos)hX1 hY" > " aU2
#define W01 hW Cmpgt_pow_imm_posneg,aK2(aJ2 Cmpgt_pow_imm_posneg)hX1 d2" > " qL3
#define Y01 hW Cmpgt_pow_imm_pospos,aK2(aJ2 Cmpgt_pow_imm_pospos)hX1 d3" > " gO3
#define S11 hW Cmpgt_pow_imm_pospos_base,aK2(aJ2 Cmpgt_pow_imm_pospos_base)hX1 mC2"> " wO
#define T11 g8 Cmpgt_powpow_imm_base,aK2(aJ2 Cmpgt_powpow_imm_base)qX1"cmpgt_" hF" > " a1
#define U11 dC Cmple_pow_imm_negneg,aK2(aJ2 Cmple_pow_imm_negneg)hY1 hV" <= " d63
#define W11 dC Cmple_pow_imm_negpos,aK2(aJ2 Cmple_pow_imm_negpos)hY1 hY" <= " aU2
#define Y11 hW Cmple_pow_imm_posneg,aK2(aJ2 Cmple_pow_imm_posneg)hY1 d2" <= " qL3
#define S21 hW Cmple_pow_imm_pospos,aK2(aJ2 Cmple_pow_imm_pospos)hY1 d3" <= " gO3
#define T21 hW Cmple_pow_imm_pospos_base,aK2(aJ2 Cmple_pow_imm_pospos_base)hY1 mC2"<= " wO
#define U21 g8 Cmple_powpow_imm_base,aK2(aJ2 Cmple_powpow_imm_base)qX1"cmple_" hF dX2 a1
#define W21 dC Cmplt_pow_imm_negneg,aK2(aJ2 Cmplt_pow_imm_negneg)hZ1 hV" < " d63
#define Y21 dC Cmplt_pow_imm_negpos,aK2(aJ2 Cmplt_pow_imm_negpos)hZ1 hY" < " aU2
#define S31 hW Cmplt_pow_imm_posneg,aK2(aJ2 Cmplt_pow_imm_posneg)hZ1 d2" < " qL3
#define T31 hW Cmplt_pow_imm_pospos,aK2(aJ2 Cmplt_pow_imm_pospos)hZ1 d3" < " gO3
#define U31 hW Cmplt_pow_imm_pospos_base,aK2(aJ2 Cmplt_pow_imm_pospos_base)hZ1 mC2"< " wO
#define W31 g8 Cmplt_powpow_imm_base,aK2(aJ2 Cmplt_powpow_imm_base)qX1"cmplt_" hF" < " a1
#define Y31 dC Cmpne_pow_imm_negneg,aK2(aJ2 Cmpne_pow_imm_negneg)d01 hV" != " d63
#define S41 dC Cmpne_pow_imm_negpos,aK2(aJ2 Cmpne_pow_imm_negpos)d01 hY" != " aU2
#define T41 hW Cmpne_pow_imm_posneg,aK2(aJ2 Cmpne_pow_imm_posneg)d01 d2" != " qL3
#define U41 hW Cmpne_pow_imm_pospos,aK2(aJ2 Cmpne_pow_imm_pospos)d01 d3" != " gO3
#define W41 hW Cmpne_pow_imm_pospos_base,aK2(aJ2 Cmpne_pow_imm_pospos_base)d01 mC2"!= " wO
#define Y41 g8 Cmpne_powpow_imm_base,aK2(aJ2 Cmpne_powpow_imm_base)qX1"cmpne_" hF dY2 a1
#define S51 dC Cmpzz_pow_imm_negneg,aK2(aJ2 Cmpzz_pow_imm_negneg)q61"_imm_negneg" mF1 o13"< " aS2 hA2 o13"<= " aS2 hB2 o13"> " aS2 hC2 o13">= " aS2 hD2 o13"!= " aS2 hE2 o13"= " d63
#define T51 dC Cmpzz_pow_imm_negpos,aK2(aJ2 Cmpzz_pow_imm_negpos)q61"_imm_negpos" mF1 o23"< " gT3 hA2 o23"<= " gT3 hB2 o23"> " gT3 hC2 o23">= " gT3 hD2 o23"!= " gT3 hE2 o23"= " aU2
#define U51 hW Cmpzz_pow_imm_posneg,aK2(aJ2 Cmpzz_pow_imm_posneg)q61"_imm_posneg" mF1 o33"< " o93 hA2 o33"<= " o93 hB2 o33"> " o93 hC2 o33">= " o93 hD2 o33"!= " o93 hE2 o33"= " qL3
#define W51 hW Cmpzz_pow_imm_pospos,aK2(aJ2 Cmpzz_pow_imm_pospos)q61"_imm_pospos" mF1",2) < 25" hA2",2) <= 25" hB2",2) > 25" hC2",2) >= 25" hD2",2) != 25" hE2",2) = " gO3
#define Y51 hW Cmpzz_pow_imm_pospos_base,aK2(aJ2 Cmpzz_pow_imm_pospos_base)q61"_imm_pospos_base" dM d53"< " mV a9 d53"<= " mV aA d53"> " mV aB d53">= " mV aC d53"!= " mV d6 qK3"= " wO
#define S61 g8 Cmpzz_powpow_imm_base,aK2(aJ2 Cmpzz_powpow_imm_base)qX1"cmpzz_powpow_imm_base" dM a72" < " qY1 a9 a72 dX2 qY1 aA a72" > " qY1 aB a72 dW2 qY1 aC a72 dY2 qY1 d6 qF1" = " a1
#define T61 {2,w22 Expexp_a,aK2(aJ2 Expexp_a)qX1 w42"p_a","exp(x*2 + y*3" mQ
#define U61 {3,w22 Expexp_b,aK2(aJ2 Expexp_b)m5 w42"p_b",aJ" * exp(y+z" mQ
#define W61 {3,w22 Expexp_c,aK2(aJ2 Expexp_c)m5 w42"p_c","exp(x + y*z" mQ
#define Y61 {2,-4,4,hP If_extract_sin,aK2(aJ2 If_extract_sin)qX1 dO1"tract_sin",o0", sin(y), " qX3
#define S71 {2,3,5,hP If_join_add,aK2(aJ2 If_join_add)qX1"if_join_add",o0 dF" +" oB1
#define T71 {2,3,5,hP If_join_and,aK2(aJ2 If_join_and)qX1"if_join_and",o0 dF" &" oB1
#define U71 {2,3,5,hP If_join_max,aK2(aJ2 If_join_max)qX1"if_join_max","max(" o0 dF"," hY3")))"},
#define W71 {2,3,5,hP If_join_min,aK2(aJ2 If_join_min)qX1"if_join_min","min(" o0 dF"," hY3")))"},
#define Y71 {2,3,5,hP If_join_mul,aK2(aJ2 If_join_mul)qX1"if_join_mul",o0 dF" *" oB1
#define S81 {2,3,5,hP If_join_or,aK2(aJ2 If_join_or)qX1"if_join_or",o0 dF" |" hY3"))"},
#define T81 a11 Ifabsnot,aK2(aJ2 Ifabsnot)m5"ifabsnot","if(!(sin(x)+1.2), y,z" mQ
#define U81 a11 Ifconst,aK2(aJ2 Ifconst)m5"ifconst","if(1, x,y) + if(0,z,y" mQ
#define W81 {4,0,hN Ififconst,aK2(aJ2 Ififconst)LNG_ONLY(0)"w," aG"ififconst","if(" o0",1,y),z,w) + if(if(w,z,0)," gQ2
#define Y81 gU2 Ifnot,aK2(aJ2 Ifnot)m5"ifnot","if(!x, y,z" mQ
#define S91 w32 Muland2,aK2(aJ2 Muland2)qX1"muland2",hZ3},
#define T91 a11 Muland2plus,aK2(aJ2 Muland2plus)m5"muland2plus",hZ3" * z"},
#define U91 a11 Muland3,aK2(aJ2 Muland3)m5"muland3",hZ3" * !!z"},
#define W91 w32 Mulandlt,aK2(aJ2 Mulandlt)qX1"mulandlt",hG2" (y<0" mQ
#define Y91 {2 oD1,oC1 q7 Mulimmlog,aK2(aJ2 Mulimmlog)qX1"mulimmlog","log(if(1,5,0)*x*y" mQ
#define SA1 w32 Mulnor2,aK2(aJ2 Mulnor2)qX1"mulnor2",d03},
#define TA1 a11 Mulnor2plus,aK2(aJ2 Mulnor2plus)m5"mulnor2plus",d03" * z"},
#define UA1 a11 Mulnor3,aK2(aJ2 Mulnor3)m5"mulnor3",d03" * !z"},
#define WA1 aD2 Negceil,aK2(aJ2 Negceil)gW"negceil","ceil(x*(" m01"-abs(x)-1))"},
#define YA1 aD2 Negcos,aK2(aJ2 Negcos)gW"negcos","cos" qG1
#define SB1 aD2 Negcosh,aK2(aJ2 Negcosh)gW"negcosh","cosh" qG1
#define TB1 aD2 Negfloor,aK2(aJ2 Negfloor)gW"negfloor","floor(x*(" m01"-abs(x)-1))"},
#define UB1 aD2 Negsin,aK2(aJ2 Negsin)gW"negsin","sin(x*if(1,-1,0))"},
#define WB1 aD2 Negsinh,aK2(aJ2 Negsinh)gW"neg" gA2,gA2 qG1
#define YB1 hH2 Posnot,aK2(aJ2 Posnot)gW"posnot","!(sin(x) + 1.2" mQ
#define SC1 hH2 Posnotnot,aK2(aJ2 Posnotnot)gW"posnotnot","!!(sin(x) + 1.2" mQ
#define TC1 {oC1 oC1 q7 Powimmaddimmlog,aK2(aJ2 Powimmaddimmlog)wE1"immaddimmlog","pow(5, log(x)+1" mQ
#define UC1 {oC1 2 oD1,q7 Powimmlog,aK2(aJ2 Powimmlog)wE1"immlog","pow(3, log(x)) + pow(5, log(x)*sin(x))"},
#define WC1 {o31 Powmulimm_fnen,aK2(aJ2 Powmulimm_fnen)qB gK1"mulimm_fnen",d11"^(-8" mQ
#define YC1 {2 hI2 Powmulimm_fnep,aK2(aJ2 Powmulimm_fnep)qB gK1"mulimm_fnep",d11"^(4" mQ
#define SD1 {1,-3,-1,hP Powmulimm_fnfn,aK2(aJ2 Powmulimm_fnfn)wE1"mulimm_fnfn","((-5.1)*x)^(-7.1" mQ
#define TD1 {2 hI2 Powmulimm_fnfp,aK2(aJ2 Powmulimm_fnfp)qB gK1"mulimm_fnfp",d11"^7.1"},
#define UD1 {2 hI2 Powmulimm_fpfp,aK2(aJ2 Powmulimm_fpfp)qB gK1"mulimm_fpfp","(5.1*x*y)^7.1"},
#define WD1 hH2 Sub1cos2,aK2(aJ2 Sub1cos2)gW"sub1cos2","1-cos(x)^2"},
#define YD1 hH2 Sub1sin2,aK2(aJ2 Sub1sin2)gW"sub1sin2","1-" a51"^2"},
#define SE1 {1,N(-9.42477796076937971538793014983850865259),N(9.42477796076937971538793014983850865259),N(0.785398163397448309615660845819875721049292349),q7 Trig_modulo,aK2(aJ2 Trig_modulo)gW"trig_modulo","cos(x+pi)" gH1"2/3)" gH1"5/2)" gH1"6/2)" gH1 oM3"  sin(x+pi) " hQ1"2/3) " hQ1"5/2) " hQ1"6/2) " hQ1 oM3"  cos(x-pi) " d12"2/3) " d12"5/2) " d12"6/2) " d12 oM3"sin(x-pi" gI1"2/3" gI1"5/2" gI1"6/2" gI1"7/2" mQ
#define TE1 {1 q01 N(0.25),q7 Trunc_from_if,aK2(aJ2 Trunc_from_if)gW"trunc_from_if",o0">0,  " gP3 qE2">=0, " gP3 qE2"<0,  " gJ3 qE2"<=0, " gJ3 wF1">0,  " gJ3 wF1">=0, " gJ3 wF1"<0,  " gP3" 10*" o0"<=0, floor(x),ceil" qV1
#define UE1 {1,N(-0.7),N(0.7),N(0.28),hH t5,aK2(aO2 t5)qB,oL"5","sub(sin(x)+csc(x),cos" qV1
#define WE1 {2 q01 N(.25),hH t42,aK2(aO2 t42)qB",y",oL"42","sqrt(x*x) + 1.5*((y*y)^.25) + hypot(x" wA1
#define YE1 {1,-100,-1,N(.5),hH t51,aK2(aO2 t51)qB,oL"51","log" a41
#define SF1 {1,N(.05),1,N(.01),hH t57,aK2(aO2 t57)qB,oL"57","cosh(a" gA2 qV1
#define TF1 {2,-2,2,N(1.2),hH t59,aK2(aO2 t59)qB",y",oL"59","cosh(x^2) + tanh(y^2" mQ
#define UF1 {1,-wZ2 N(.25)h5 t1,aK2(aP2 t1)w82"1","x*4/2 + (1+(2+3)) + x*x+x+1+2+3*4+5*6*\n7-8*9"},
#define WF1 {1,-wZ2 hK2 t2,aK2(aP2 t2)w82"2","2 * x+ sin ( x ) / .5 + 2-sin(x)*sin(x)"},
#define YF1 {3,-7,7,w92 t3,aK2(aP2 t3)a02"3","(x=y & y=x)+  1+2-3.1*4e2/.5 + x*x+y*y+z*z  + (x&x) + (y|y" mQ
#define SG1 {2,-10,10,w92 t4,aK2(aP2 t4)h02"4","( ((( ( x-y) -( ((y) *2) -3)) )* 4))+sin(x)*cos(y)-cos(x)*sin(y" mQ
#define TG1 {2,aG2 8,hM2 t5,aK2(aP2 t5)LNG_ONLY(0)"__A5_x08,o__5_0AB_",oT"5","__A5_x08^o__5_0AB_"},
#define UG1 {w03 N(.01)h5 t7,aK2(aP2 t7)w82"7","cos(x)*sin(1-x)*(1-cos(x/2)*sin(x*5))"},
#define WG1 {2,-8,8,w52 t8,aK2(aP2 t8)h02"8",hZ2"(x,y)+max(x" wA1
#define YG1 {3,1,15,N(.7)h5 t9,aK2(aP2 t9)a02"9","1.5+x*y-2+4/8+z+z+z+z+x/(y*z" mQ
#define SH1 {3,1,4,N(.3)h5 t10,aK2(aP2 t10)a02"10","1+sin(cos(max(1+2+3+4+5, x+y+z)))+2"},
#define TH1 {3,1,19,N(.8)h5 t11,aK2(aP2 t11)a02"11","-(-(-(-(-x))-x))+y*1+log(1.1^z" mQ
#define UH1 {1,1,2000,w92 t12,aK2(aP2 t12)w82"12","1/log(10^((3-2)/log(x)))"},
#define WH1 {2,-30,30,w92 t13,aK2(aP2 t13)h02"13","x^3 * x^4 + y^3 * y^5"},
#define YH1 {1,-50,50,hK2 t14,aK2(aP2 t14)w82"14","x*pi + sin(2*pi) + CONST"},
#define SI1 {2,N(1.1),6,N(.07)h5 t15,aK2(aP2 t15)h02"15","x^y/log(y) + log(x)/log(y) + log(x^y" mQ
#define TI1 {2,1,17,w52 t18,aK2(aP2 t18)h02"18","- ( - ( - ( - 5 ) ) ) * -x^ -y^-2"},
#define UI1 {2,-4,4,hK2 t22,aK2(aP2 t22)h02"22","3.5doubled + 10*x tripled - sin(y)doubled" hX3"100" wZ1" doubled-y tripled)doubled + 5/2doubled + 1.1^x doubled +  1.1doubled^x doubled"},
#define WI1 {1,-wZ2 hK2 t23,aK2(aP2 t23)w82"23","(x/(2*acos(0)))*180"},
#define YI1 {3,1,3,w52 t25,aK2(aP2 t25)LNG_ONLY(0)"a,b,c",oT"25","a^b^c + a^-2 * (-b^2" wA2"-b^-c" mQ
#define SJ1 {1,-100,100,aG2 true,aP2 t26_deg,aK2(aP2 t26_deg)w82"26_deg",wC2" cos(x*1.5) + asin(x/110) + acos(x/120" mQ
#define TJ1 {2,aG2 N(.9),N(.025)h5 t27,aK2(aP2 t27)h02"27","abs(x)+acos(x)+asin(x)+atan(x)+" hZ2"(x,y)+ceil(x)+cos(x)+cosh(x)+cot(x)+csc" qK2" " qC2 wA1
#define UJ1 {2,aG2 N(.9),N(.025)h5 t28,aK2(aP2 t28)h02"28","exp(x)+floor(x)+int(x)+log(x)+log10(x)+max(x,y)+min(x,y)+sec(x)+sin(x)+sinh(x)+sqrt(x)+tan(x)+tanh(x)+ceil(y)+trunc(y" mQ
#define WJ1 {2,3,10,h4 t30,aK2(aP2 t30)h02"30","x - y*1 + (x%y) + x / (y^1.1) + 2^3 + 5%3 + x^(y^0) + x^0.5"},
#define YJ1 {3,aG2 4,N(.35)h5 t31,aK2(aP2 t31)a02"31","x - (y*(y*(y*-1))*1) + log(x*exp" mG1")^y) - log(x^y)" hX3"exp" mG1")^log(x+6) + 10^" qF2"6" mH1"y+6)*log(z+6" mH1"10)) -" w83"exp" mG1")^" qF2"6)*y) - 5^" qF2"7" mH1"5)) + " aK1"^3 * " aK1"^2 /  " aK1"^4"},
#define SK1 {3,1,2,N(.05)h5 t32,aK2(aP2 t32)a02"32","x" mO"+y/y-min(3,4)-x-max(4,3)+max(3,4)-min(4,3)+0+(z*1)" mO"+(x-2+2)+(x*0.5*2)+y*0" w83" +min(min(min(4.0,x),1.0),min(x,min(min(y,4.0),z)))" mO"+max(max(max(4.0,x),1.0)" wG1"x(max(y,4.0),z)))" mO"+(abs(1)+acos" mG1")+asin(1.0)+atan" mG1")+ceil(1.1)+cos(0.0)" w83"  +cosh(0.0)+floor(1.1)+log" mG1")+sin(0.0)+sinh(0.0)+tan" mG1")" w83"  +tanh" mG1")+" hZ2"(1.0,1.0))" mO"+(x-(y-z))" mO"+(x+y)" mB1"y)" mO"+max(x" wG1"x(x,max(x,x))))*-1.0" w83" +(z-z)" mO"+1/sin(x/5)" w62"cos(y/5)" w62"tan(z/5)" mO"+log10(cot(z/5) + csc(y/5) + sec(x/5))" mO"+log(30+x)*log(40+y" mH1"50+z)" mO"+sin(x/57.295779513082320877)" mO"+asin(x/10)*57.295779513082320877" w83" +floor(-x)" w62"ceil(x)" mO"+" w72"5 * 0.2) +(-" hL2 hL2"x+-x)"},
#define TK1 {2,-2,2,hK2 t33,aK2(aP2 t33)h02"33","sin(" w72"10-x*x+y*y))+cos(" w72"15-x*x-y*y))+sin(x*x+y*y" mQ
#define UK1 {w03 hK2 t37,aK2(aP2 t37)w82"37","5 + 7.5*8 / 3 - 2^4*2 + 7%2+4 + x"},
#define WK1 {3,N(-.9),N(.9),hK2 t38,aK2(aP2 t38)a02"38",oW3 qK2" 1.5*" w12"(y+3) + 2.5*atanh(z" mQ
#define YK1 {3,N(-1.3),N(1.3),hM2 t39,aK2(aP2 t39)a02"39","sin(x+cos(y*1.5))-cos(x+sin(y*1.5))+z*z*z*sin(z*z*z-x*x-y*y)-" w83"cos(y*1.5)*sin(x+cos(y*1.5))+x*y*z+x*y*2.5+x*y*z*cos(x)+x*y*cos(x)+x*z*cos(x)+  y*z*2.5+(x*y*z*cos(x)-x*y*z-y*cos(x)-x*z*y+x*y+x*z-cos(x)*x)"},
#define SL1 {3,N(-1.3),N(1.3),N(.075)h5 t40,aK2(aP2 t40)a02"40","(x+x+x+x+x+x+x+x+x+x+x+" gY1")*" w83"(x+x+x+x+x+x+x+x+x+x+x+" gY1")+" h81"*(x+x+x+x+x+x+x+x+x+x+x+" gY1")-" w83"x*y*(x+x+x+x+x+x+x+x+x+x+x+" gY1")+  x*(x+x+x+x+x+x+x+x+x+x+x+" gY1 mQ
#define TL1 {3,-2,2,hM2 t41,aK2(aP2 t41)a02"41","x*3+x*y+x*z+x*sin(y*z) -" w83 hN2"4" hX3 q91"))*x" hX3 hN2"y +  " hN2"z"},
#define UL1 {1,-100,100,N(.03)h5 t43,aK2(aP2 t43)w82"43","log(x*x)+abs(" o02"abs(x)+1))"},
#define WL1 {1,0,100,N(.125)h5 t44,aK2(aP2 t44)w82"44","(x^2" h31"8)" hX3"1.1" wZ1"^3" h31"7)" hX3"1.2" wZ1"^4" h31"6)" hX3"1.3" wZ1"^5" h31"5)" hX3"1.4" wZ1"^6" h31"6)" hX3"1.5" wZ1"^7" h31"4)" hX3"1.6" wZ1"^8" h31"3)" hX3"1.7" wZ1"^9" h31"2) +  1.8*(" w72"abs(-sqrt(x))^3))"},
#define YL1 {w03 N(.025)h5 t45,aK2(aP2 t45)w82"45","(x^2" h31"7) + 1.1" wZ1"^4" h31"5) + 1.2" wZ1"^6" h31"3" mQ
#define SM1 {2,N(-.9),N(.9),hM2 t46,aK2(aP2 t46)h02"46","abs(floor(acos(x)+4)) + 1.1*abs(floor(acos(y)+1.5)) +  " oO1" < (acos(y)-10)) + 1.2*max(-4, acos(x)) + 1.3*min(9, acos(x)-9" mQ
#define TM1 {2 q01 hK2 t47,aK2(aP2 t47)h02"47","1.25*(exp(x)+" o02"-" wD1" 1.5*(" o02"y)-exp(-y)) +  1.75*((" o02"-x)+exp(x))/2) + 2.0*((" o02"-x)-exp(x))/2) + 2.25*(cosh(y)+sinh(y))"},
#define UM1 {1,2,N(1e9),N(1.2e7)h5 t48,aK2(aP2 t48)w82"48",gA2"((log(x)/5+1)*5) + 1.2*cosh((log(x)/log(2)+1)*log" oX" !(x | !(x/4))"},
#define WM1 {1,-100,100,N(.05)h5 t49,aK2(aP2 t49)w82"49",hZ2"(0, x) + (-4" wZ1"-100))^3.3"},
#define YM1 {w03 w92 t52,aK2(aP2 t52)w82"52","x + " mG1"+2.0+3.0+4.0-5.0-6.0-7.0-8.0)/3.0" hX3"4.0*(1.0+sin(2.0)+cos(4.0*5.0+6.0)/2.0) + cos(0.5)*tan(0.6+0.2) -  1.1/log(2.1)*" w72"3.3) + 2^3"},
#define SN1 {2,0,10,N(0.5)h5 t53,aK2(aP2 t53)h02"53","(x&y) + 4*(int(x/10)|int(y/10)) + 8*((-!-!-x)+(!-!-!y)) + 16*(-------x + !!!!!!!y" mQ
#define TN1 {2,-10,100,w92 t54,aK2(aP2 t54)h02"54","(x<y" o22"<=y" o22">y" o22">=y)+" w83"(x=y" o22"!=y)+(x&y" o22"|y)+" w83"(!x)+(!!x)+" w83"!((x<y)&(x<3))+  !!(!(x>y)|(x>3))"},
#define UN1 {2,1,100,w92 t55,aK2(aP2 t55)h02"55","(x^1.2 < 0" wA2"y^2.5 < 0) + 2*(x*x<0) + 3*(y^3<0) + 4" wZ1"^4<0" mQ
#define WN1 {1,N(.25),100,N(.25)h5 t56,aK2(aP2 t56)w82"56","1.75e21%x"},
#define YN1 {1 q01 N(0.2)h5 t59,aK2(aP2 t59)w82"59","(cos(x) < sin(x))" hX3"(cos(x)-sin(x))" hX3"sub(sinh(x)-cosh(x), " gA2"(x)/cosh(x)) +  sqrt(cos(x)^2+sin(x)^2" mQ
#define SO1 {1,N(1e-6),wQ2 Log,aK2(aR2 Log)qO"/log",aQ1
#define TO1 gC Abscos,aK2(aM2 Abscos)qZ"abscos","cos(abs" qV1
#define UO1 gC Abscosh,aK2(aM2 Abscosh)qZ"abscosh","cosh(abs" qV1
#define WO1 {1 w7 Abseq0,aK2(aM2 Abseq0)LNG_ONLY(aM2 Abseq0)o21"abseq0" oN1"=0" wA2"0=abs" qV1
#define YO1 {1,N(0.001),N(0.9),N(0.01)qL Absevenconstpow,aK2(aM2 Absevenconstpow)qZ"absevenconstpow",m01" ^ 1506"},
#define SP1 {2,N(0.001),N(0.9),N(0.01)qL Absmulevenconstpow,aK2(aM2 Absmulevenconstpow)dH1"absmulevenconstpow","(abs(x)*y) ^ 1506"},
#define TP1 {1 w7 oN3,aK2(aM2 oN3)LNG_ONLY(aM2 oN3)o21"absneq0" oN1"=0" wA2"0=abs" qV1
#define UP1 {1 w7 Add,aK2(aM2 Add)LNG_ONLY(aM2 Add)o21"add","5+3+x"},
#define WP1 {1 w7 Add0,aK2(aM2 Add0)LNG_ONLY(aM2 Add0)o21"add0","x+0+x"},
#define YP1 {1 w7 And,aK2(aM2 And)LNG_ONLY(aM2 And)o21"and","(5&3" qH2"5&0)+(0&5)+(0&0" mQ
#define SQ1 w31 Cmp_acos,aK2(aM2 Cmp_acos)qZ"cmp_acos","1" o4"=acos" o52 h81 o4"<acos" o52 w83"4" o4"<=acos" o52 h91 o4">acos" o52 h71 o4">=acos" o52 w93 o4"!=acos(0.75))"},
#define TQ1 w31 Cmp_acos_outrange,aK2(aM2 Cmp_acos_outrange)qZ"cmp_acos_outrange","1" o4"=2) +" h81 o4"<2)" hX3"4" o4"<=2) +" h91 o4">2) +" h71 o4">=2) +" w93 o4"!=2" mQ
#define UQ1 d41 oO3,aK2(aM2 oO3)LNG_ONLY(aM2 oO3)o21"cmp_add","1" aI d71 aI d81 aI gN1 aI gO1 aI m2 aI dI1
#define WQ1 w31 Cmp_asin,aK2(aM2 Cmp_asin)qZ"cmp_asin","1" o6"=a" dT1 h81 o6"<a" dT1 w83"4" o6"<=a" dT1 h91 o6">a" dT1 h71 o6">=a" dT1 w93 o6"!=asin(0.75))"},
#define YQ1 w31 Cmp_asin_outrange,aK2(aM2 Cmp_asin_outrange)qZ"cmp_asin_outrange","1" o6"=2) +" h81 o6"<2)" hX3"4" o6"<=2) +" h91 o6">2) +" h71 o6">=2) +" w93 o6"!=2" mQ
#define SR1 oV Cmp_atan,aK2(aM2 Cmp_atan)qZ"cmp_atan","1" qH1"=atan" hO2 qH1"<atan" hP2 qH1"<=atan" hQ2 qH1">atan" hR2 qH1">=atan" hS2 qH1"!=atan" hL1
#define TR1 oV Cmp_exp,aK2(aM2 Cmp_exp)qZ mI1"p","1" h41"=e" oA3"2" h41"<e" oA3"4" h41"<=e" oA3" 8" h41">e" oA3"16" h41">=e" oA3"32" h41"!=exp" hL1
#define UR1 oV Cmp_exp2,aK2(aM2 Cmp_exp2)qZ mI1"p2","1" h51"=exp2" oX" 2" h51"<exp2" oX" 4" h51"<=exp2" oX"  8" h51">exp2" oX" 16" h51">=exp2" oX oB3 h51"!=exp2" hL1
#define WR1 oV Cmp_exp2_neg,aK2(aM2 Cmp_exp2_neg)qZ mI1"p2_neg","1" h51"=-4) + 2" h51"<-4) + 4" h51"<=-4" hC1 aK">-4) + 16" h51">=-4" a31 h51"!=-4" mQ
#define YR1 oV Cmp_exp_neg,aK2(aM2 Cmp_exp_neg)qZ mI1"p_neg","1" h41"=-4) + 2" h41"<-4) + 4" h41"<=-4" hC1 aJ">-4) + 16" h41">=-4" a31 h41"!=-4" mQ
#define SS1 oW Cmp_log2_nn,aK2(aM2 Cmp_log2_nn)qZ"cmp_log2_nn","1" h61 hT2 wP aL h61 a2 h61 a5 h61 aM h61 d31
#define TS1 oW Cmp_log2_np,aK2(aM2 Cmp_log2_np)qZ"cmp_log2_np","1" h61"=log2" hO2 h61"<log2" hP2 h61"<=log2" hQ2 h61">log2" hR2 h61">=log2" hS2 h61"!=log2" hL1
#define US1 oV Cmp_log2_pn,aK2(aM2 Cmp_log2_pn)qZ"cmp_log2_pn","1" hA1 hT2 wQ aL hA1 a2 hA1 a5 hA1 aM hA1 d31
#define WS1 oV Cmp_log2_pp,aK2(aM2 Cmp_log2_pp)qZ"cmp_log2_pp","1" hA1"=log2" hO2 hA1"<log2" hP2 hA1"<=log2" hQ2 hA1">log2" hR2 hA1">=log2" hS2 hA1"!=log2" hL1
#define YS1 oW Cmp_log10_nn,aK2(aM2 Cmp_log10_nn)qZ"cmp_log10_nn","1" hB1 hT2 oU aL hB1 a2 hB1 a5 hB1 aM hB1 d31
#define ST1 oW Cmp_log10_np,aK2(aM2 Cmp_log10_np)qZ"cmp_log10_np","1" hB1"=log10" hO2 hB1"<log10" hP2 hB1"<=log10" hQ2 hB1">log10" hR2 hB1">=log10" hS2 hB1"!=log10" hL1
#define TT1 oV Cmp_log10_pn,aK2(aM2 Cmp_log10_pn)qZ"cmp_log10_pn","1" dJ hU2 dJ aL dJ a2 dJ a5 dJ aM dJ d31
#define UT1 oV Cmp_log10_pp,aK2(aM2 Cmp_log10_pp)qZ"cmp_log10_pp","1" dJ"=log10" a21 h81 dJ"<log10" a21 w83"4" dJ"<=log10" a21 h91 dJ">log10" a21 h71 dJ">=log10" a21 w93 dJ"!=log10(1))"},
#define WT1 oW Cmp_log_nn,aK2(aM2 Cmp_log_nn)qZ"cmp_log_nn","1" gL1 hU2 gL1 aL gL1 a2 gL1 a5 gL1 aM gL1 d31
#define YT1 oW Cmp_log_np,aK2(aM2 Cmp_log_np)qZ"cmp_log_np","1" gL1"=log" hO2 gL1"<log" hP2 gL1"<=log" hQ2 gL1">log" hR2 gL1">=log" hS2 gL1"!=log" hL1
#define SU1 oV Cmp_log_pn,aK2(aM2 Cmp_log_pn)qZ"cmp_log_pn","1" gM1 hU2 gM1 aL gM1 a2 gM1 a5 gM1 aM gM1 d31
#define TU1 oV Cmp_log_pp,aK2(aM2 Cmp_log_pp)qZ"cmp_log_pp","1" gM1"=log" hO2 gM1"<log" hP2 gM1"<=log" hQ2 gM1">log" hR2 gM1">=log" hS2 gM1"!=log" hL1
#define UU1 d41 h23,aK2(aM2 h23)LNG_ONLY(aM2 h23)o21"cmp_mulneg","1" hV2 d71 hV2 d81 hV2 gN1 hV2 gO1 hV2 m2 hV2 dI1
#define WU1 d41 h33,aK2(aM2 h33)LNG_ONLY(aM2 h33)o21"cmp_mulpos","1" hW2 d71 hW2 d81 hW2 gN1 hW2 gO1 hW2 m2 hW2 dI1
#define YU1 d41 oP3,aK2(aM2 oP3)LNG_ONLY(aM2 oP3)o21"cmp_neg","1" oE1"=4) + 2" oE1"<4) + 4" oE1"<=4) +  8" oE1">4) + 16" oE1 m2 oE1 dI1
#define SV1 d51 Cmp_powx_n_n,aK2(aM2 Cmp_powx_n_n)hN1"_n_n","1" g4"=" o32 aZ g4"<" o32 m0 g4"<=" o32 m1 g4">" o32"+" wR g4">=" o32"+" oB3 g4"!=" oP},
#define TV1 d51 Cmp_powx_n_p,aK2(aM2 Cmp_powx_n_p)hN1"_n_p","1" g4"=" o42 aZ g4"<" o42 m0 g4"<=" o42 m1 g4">" o42"+" wR g4">=" o42"+" oB3 g4"!=" oQ},
#define UV1 d61 Cmp_powx_nn,aK2(aM2 Cmp_powx_nn)hN1"_nn","1" g4 oF1 g4 oG1 g4 dJ1 g4 dK1 g4">=-4" a31 g4"!=-4" mQ
#define WV1 d61 Cmp_powx_np,aK2(aM2 Cmp_powx_np)hN1"_np","1" g4 d71 g4 d81 g4 gN1 g4 gO1 g4 m2 g4 dI1
#define YV1 d51 Cmp_powx_p_n,aK2(aM2 Cmp_powx_p_n)hN1"_p_n","1" oY"=" o32 aZ oY"<" o32 m0 oY"<=" o32 m1 oY">" o32"+" wR oY">=" o32"+" oB3 oY"!=" oP},
#define SW1 d51 Cmp_powx_p_p,aK2(aM2 Cmp_powx_p_p)hN1"_p_p","1" oY"=" o42 aZ oY"<" o42 m0 oY"<=" o42 m1 oY">" o42"+" wR oY">=" o42"+" oB3 oY"!=" oQ},
#define TW1 d61 Cmp_powx_pn,aK2(aM2 Cmp_powx_pn)hN1"_pn","1" wY2 oF1 wY2 oG1 wY2 dJ1 wY2 dK1 h0"x)>=-4" a31 h0"x)!=-4" mQ
#define UW1 d61 Cmp_powx_pp,aK2(aM2 Cmp_powx_pp)hN1"_pp","1" wY2 d71 wY2 d81 wY2 gN1 wY2 gO1 wY2 m2 wY2 dI1
#define WW1 hJ Cmp_powy_n_n,aK2(aM2 Cmp_powy_n_n)oH1"y_n_n" qN2"=" h43"2" oI1"<" h43"4" oI1"<=" h43"8" oI1">" dX wR oI1">=" dX oB3 oI1"!=(x^-6.1))"},
#define YW1 hJ Cmp_powy_n_p,aK2(aM2 Cmp_powy_n_p)oH1"y_n_p" qN2"=(x" h53"2" oI1"<(x" h53"4" oI1"<=(x" h53"8" oI1">(x" wV wR oI1">=(x" wV oB3 oI1"!=(x^6.1))"},
#define SX1 hJ Cmp_powy_nn,aK2(aM2 Cmp_powy_nn)oH1"y_nn" qN2 oF1 oI1 oG1 oI1 dJ1 oI1 dK1 oI1">=-4" a31 oI1"!=-4" mQ
#define TX1 hJ Cmp_powy_np,aK2(aM2 Cmp_powy_np)oH1"y_np" qN2 d71 oI1 d81 oI1 gN1 oI1 gO1 oI1 m2 oI1 dI1
#define UX1 hJ Cmp_powy_p_n,aK2(aM2 Cmp_powy_p_n)oH1"y_p_n","1" h2"=" h43"2" h2"<" h43"4" h2"<=" h43"8" h2">" dX wR h2">=" dX oB3 h2"!=(x^-6.1))"},
#define WX1 hJ Cmp_powy_p_p,aK2(aM2 Cmp_powy_p_p)oH1"y_p_p","1" h2"=(x" h53"2" h2"<(x" h53"4" h2"<=(x" h53"8" h2">(x" wV wR h2">=(x" wV oB3 h2"!=(x^6.1))"},
#define YX1 hJ Cmp_powy_pn,aK2(aM2 Cmp_powy_pn)oH1"y_pn","1" h2 oF1 h2 oG1 h2 dJ1 h2 dK1 h2">=-4" a31 h2"!=-4" mQ
#define SY1 hJ Cmp_powy_pp,aK2(aM2 Cmp_powy_pp)oH1"y_pp","1" h2 d71 h2 d81 h2 gN1 h2 gO1 h2 m2 h2 dI1
#define TY1 oV Cmp_sinh,aK2(aM2 Cmp_sinh)oO gA2,"1" qI1"=" gA2 hO2 qI1"<" gA2 hP2 qI1"<=" gA2 hQ2 qI1">" gA2 hR2 qI1">=" gA2 hS2 qI1"!=" gA2 hL1
#define UY1 d41 oQ3,aK2(aM2 oQ3)LNG_ONLY(aM2 oQ3)o21"cmp_sqr","1" wS"=16) + 2" wS"<16) + 4" wS"<=16) +  8" wS">16) + 16" wS">=16" a31 wS"!=16" mQ
#define WY1 d41 gQ3,aK2(aM2 gQ3)LNG_ONLY(aM2 gQ3)o21"cmp_sqr_neg","1" wS"=-16) + 2" wS"<-16) + 4" wS"<=-16) +  8" wS">-16) + -16" wS">=-16" a31 wS"!=-16" mQ
#define YY1 {1,-4,4 oD1 qL Cmp_tanh,aK2(aM2 Cmp_tanh)qZ"cmp_tanh","1" o9"=tanh" o52 h81 o9"<tanh" o52 w83"4" o9"<=tanh" o52 h91 o9">tanh" o52 h71 o9">=tanh" o52 w93 o9"!=tanh(0.75))"},
#define SZ1 {1,-4,4 oD1 qL Cmp_tanh_outrange,aK2(aM2 Cmp_tanh_outrange)qZ"cmp_tanh_outrange","1" o9"=2) +" h81 o9"<2)" hX3"4" o9"<=2) +" h91 o9">2) +" h71 o9">=2) +" w93 o9"!=2" mQ
#define TZ1 {1 w7 Cmpeq,aK2(aM2 Cmpeq)LNG_ONLY(aM2 Cmpeq)o21"cmpeq","(5=3" qH2"4=4" mQ
#define UZ1 {1 w7 Cmpge,aK2(aM2 Cmpge)LNG_ONLY(aM2 Cmpge)o21"cmpge","(5>=3" qH2"4>=8" mQ
#define WZ1 {1 w7 Cmpgt,aK2(aM2 Cmpgt)LNG_ONLY(aM2 Cmpgt)o21"cmpgt","(5>3" qH2"4>8" mQ
#define YZ1 {1 w7 Cmple,aK2(aM2 Cmple)LNG_ONLY(aM2 Cmple)o21"cmple","(5<3" qH2"4<8" mQ
#define Sa1 {1 w7 Cmplt,aK2(aM2 Cmplt)LNG_ONLY(aM2 Cmplt)o21"cmplt","(5<3)+x"},
#define Ta1 {1 w7 Cmpne,aK2(aM2 Cmpne)LNG_ONLY(aM2 Cmpne)o21"cmpne","(5!=3" qH2"4!=4" mQ
#define Ua1 {1 w7 Div,aK2(aM2 Div)LNG_ONLY(aM2 Div)o21"div","(5/4)+x"},
#define Wa1 {1 w7 Div1,aK2(aM2 Div1)LNG_ONLY(aM2 Div1)o21"div1","x/1+x"},
#define Ya1 {1 w7 Divxx,aK2(aM2 Divxx)LNG_ONLY(aM2 Divxx)o21"divxx","x+x/x+x"},
#define Sb1 {1 w7 Eq0,aK2(aM2 Eq0)LNG_ONLY(aM2 Eq0)o21"eq0","(x=0" wA2"0=x)"},
#define Tb1 {1 w7 Eq1,aK2(aM2 Eq1)LNG_ONLY(aM2 Eq1)o21"eq1","(!x=1" mQ
#define Ub1 {oB oR3,aK2(aM2 oR3)LNG_ONLY(aM2 oR3)o21"ge0_abs" oN1 h63 gU3 h73 gV3
#define Wb1 w31 Ge0_neg,aK2(aM2 Ge0_neg)qZ"ge0_neg" oZ1 h63 oZ h73 qX3
#define Yb1 w31 Ge0_pos,aK2(aM2 Ge0_pos)qZ"ge0_pos",oO1 h63 qQ3 h73 gK3
#define Sc1 {oB oS3,aK2(aM2 oS3)LNG_ONLY(aM2 oS3)o21"ge1_abs" oN1 h83 gU3 h93 gV3
#define Tc1 w31 Ge1_neg,aK2(aM2 Ge1_neg)qZ"ge1_neg" oZ1 h83 oZ h93 qX3
#define Uc1 w31 Ge1_pos,aK2(aM2 Ge1_pos)qZ"ge1_pos",oO1 h83 qQ3 h93 gK3
#define Wc1 w31 Gehalf,aK2(aM2 Gehalf)qZ"gehalf","x>=0.5"},
#define Yc1 {oB oT3,aK2(aM2 oT3)LNG_ONLY(aM2 oT3)o21"gt0_abs" oN1 d13 gU3 d23 gV3
#define Sd1 w31 Gt0_neg,aK2(aM2 Gt0_neg)qZ"gt0_neg" oZ1 d13 oZ d23 qX3
#define Td1 w31 Gt0_pos,aK2(aM2 Gt0_pos)qZ"gt0_pos",oO1 d13 qQ3 d23 gK3
#define Ud1 {oB oU3,aK2(aM2 oU3)LNG_ONLY(aM2 oU3)o21"gt1_abs" oN1 d33 gU3 d43 gV3
#define Wd1 w31 Gt1_neg,aK2(aM2 Gt1_neg)qZ"gt1_neg" oZ1 d33 oZ d43 qX3
#define Yd1 w31 Gt1_pos,aK2(aM2 Gt1_pos)qZ"gt1_pos",oO1 d33 qQ3 d43 gK3
#define Se1 w31 Gtminushalf,aK2(aM2 Gtminushalf)qZ"gtminushalf","x>-0.5"},
#define Te1 {1,a82 Immsub,aK2(aM2 Immsub)LNG_ONLY(aM2 Immsub)o21"immsub","x-5"},
#define Ue1 w31 Leminushalf,aK2(aM2 Leminushalf)qZ"leminushalf","x<=-0.5"},
#define We1 {1,0,3,gM2 Log2exp1,aK2(aM2 Log2exp1)qZ"log2exp1",o02"log2" qV1
#define Ye1 {1,-1,N(0.75)oD1 qL Log2exp2,aK2(aM2 Log2exp2)qZ"log2exp2","exp2(log2(acos(x)))"},
#define Sf1 {1,0,3,gM2 Logexp1,aK2(aM2 Logexp1)qZ"logexp1",o02"log" qV1
#define Tf1 {1,-1,N(0.75)oD1 qL Logexp2,aK2(aM2 Logexp2)qZ"logexp2",o02"log(acos(x)))"},
#define Uf1 {1 dQ1 Logmul,aK2(aM2 Logmul)qZ"logmul","log(" d91
#define Wf1 {1 dQ1 Logmul2,aK2(aM2 Logmul2)qZ"logmul2","log2(" d91
#define Yf1 {1 dQ1 Logmul10,aK2(aM2 Logmul10)qZ"logmul10","log10(" d91
#define Sg1 {oB Lt0,aK2(aM2 Lt0)LNG_ONLY(aM2 Lt0)o21"lt0","sub(" m01"<0, x<0" mQ
#define Tg1 w31 Lthalf,aK2(aM2 Lthalf)qZ"lthalf","x<0.5"},
#define Ug1 {1 w7 Mod,aK2(aM2 Mod)LNG_ONLY(aM2 Mod)o21"mod","(5%4)+x"},
#define Wg1 {1 w7 Mul,aK2(aM2 Mul)LNG_ONLY(aM2 Mul)o21"mul","(5*4)+x"},
#define Yg1 {1 w7 Mul1,aK2(aM2 Mul1)LNG_ONLY(aM2 Mul1)o21"mul1","x*1+x"},
#define Sh1 {1 w7 Mul1b,aK2(aM2 Mul1b)qZ"mul1b",wL"0.2)*5)+x"},
#define Th1 {2,N(0.1),10,N(0.1)qL Mul_zero,aK2(aM2 Mul_zero)dH1"mul_zero","(x*y+1)+(sin(x)+sin(y))*log(x)*y*x*0"},
#define Uh1 {1 w7 Mulneg,aK2(aM2 Mulneg)LNG_ONLY(aM2 Mulneg)o21"mulneg","-" qL2
#define Wh1 {1 w7 o43,aK2(aM2 o43)LNG_ONLY(aM2 o43)o21"multodiv","x/4+x"},
#define Yh1 {2,a82 Negadd,aK2(aM2 Negadd)LNG_ONLY(aM2 Negadd)wK"negadd","x+(-y" mQ
#define Si1 gC Negcos,aK2(aM2 Negcos)qZ"negcos","cos" a41
#define Ti1 gC Negcosh,aK2(aM2 Negcosh)qZ"negcosh","cosh" a41
#define Ui1 {1 w7 Negmul,aK2(aM2 Negmul)LNG_ONLY(aM2 Negmul)o21"negmul","(-x)*" gH2
#define Wi1 gC Negsin,aK2(aM2 Negsin)qZ"negsin","sin(-x)"},
#define Yi1 gC Negsinh,aK2(aM2 Negsinh)qZ"neg" gA2,gA2 a41
#define Sj1 {2,a82 Negsub,aK2(aM2 Negsub)LNG_ONLY(aM2 Negsub)wK"negsub","x-(-y" mQ
#define Tj1 gC Negtan,aK2(aM2 Negtan)qZ"negtan","tan" a41
#define Uj1 gC Negtanh,aK2(aM2 Negtanh)qZ"negtanh","tanh" a41
#define Wj1 {1 w7 Neq0,aK2(aM2 Neq0)LNG_ONLY(aM2 Neq0)o21"neq0","(x!=0" wA2"0!=x)"},
#define Yj1 {1 w7 Neq1,aK2(aM2 Neq1)LNG_ONLY(aM2 Neq1)o21"neq1","(!x!=1" mQ
#define Sk1 {1 w7 Not,aK2(aM2 Not)LNG_ONLY(aM2 Not)o21"not","(!(3))+x"},
#define Tk1 {1 w7 Or,aK2(aM2 Or)LNG_ONLY(aM2 Or)o21"or","(5|3" qH2"5|0)+(0|5)+(0|0" mQ
#define Uk1 gC Sincos_cci,aK2(aM2 Sincos_cci)hQ"cos_cci","cos" qK2" sec(x)"},
#define Wk1 gC Sincos_cic,aK2(aM2 Sincos_cic)hQ"cos_cic","sec" qK2 wJ1
#define Yk1 gC Sincos_sc,aK2(aM2 Sincos_sc)hQ"cos_sc",wC2 wJ1
#define Sl1 gC Sincos_sci,aK2(aM2 Sincos_sci)hQ"cos_sci",wC2" sec(x)"},
#define Tl1 gC Sincos_sis,aK2(aM2 Sincos_sis)hQ"cos_sis","csc" qK2" " a51},
#define Ul1 gC Sincos_ssi,aK2(aM2 Sincos_ssi)hQ"cos_ssi",wC2" csc(x)"},
#define Wl1 gC Sincos_tan,aK2(aM2 Sincos_tan)hQ"cos_tan",a51" /" wJ1
#define Yl1 gC Sincos_tit,aK2(aM2 Sincos_tit)hQ"cos_tit","cot" qK2" tan(x)"},
#define Sm1 gC Sincos_tti,aK2(aM2 Sincos_tti)hQ"cos_tti","tan" qK2" cot(x)"},
#define Tm1 {1 w7 Sqreq0,aK2(aM2 Sqreq0)LNG_ONLY(aM2 Sqreq0)o21"sqreq0","(x*x=0" wA2"0=x*x)"},
#define Um1 {1 w7 oV3,aK2(aM2 oV3)LNG_ONLY(aM2 oV3)o21"sqrneq0","(x*x=0" wA2"0=x*x)"},
#define Wm1 {1,0,3,gM2 Sqrtsqr1,aK2(aM2 Sqrtsqr1)qZ"sqrtsqr1","sqrt(x)^2"},
#define Ym1 {1,aH Sqrtsqr2,aK2(aM2 Sqrtsqr2)qZ"sqrtsqr2",w72"acos(x))^2"},
#define Sn1 {1 w7 Sub,aK2(aM2 Sub)LNG_ONLY(aM2 Sub)o21"sub","5-3+x"},
#define Tn1 {1 w7 Sub0,aK2(aM2 Sub0)LNG_ONLY(aM2 Sub0)o21"sub0","x-0+x"},
#define Un1 {1 q01 1 qL Subxx,aK2(aM2 Subxx)LNG_ONLY(aM2 Subxx)o21"subxx","x+(x-x)+x+(1-x+x)"},
#define Wn1 gC Xmulsinhneg,aK2(aM2 Xmulsinhneg)wW"mulsinhneg","-" gA2 qL2
#define Yn1 gC Xmulsinneg,aK2(aM2 Xmulsinneg)wW"mulsinneg","-sin(x*" mJ1
#define So1 gC Xmultanhneg,aK2(aM2 Xmultanhneg)wW"multanhneg","-tanh" qL2
#define To1 gC Xmultanneg,aK2(aM2 Xmultanneg)wW"multanneg","-tan" qL2
#define Uo1 {1,N(0.5),3,N(0.7)qL Xsqryfsqrhypot,aK2(aM2 Xsqryfsqrhypot)wW"sqryfsqrhypot",w72"log(x)^2+" wP"^2" mQ
#define Wo1 {2,N(0.5),3,N(0.7)qL Xsqrysqrhypot,aK2(aM2 Xsqrysqrhypot)qB g3"/xsqrysqrhypot",w72"log(x)^2+y*y" mQ
#define Yo1 {1 m6 t1,aK2(aL2 t1)LNG_ONLY(aL2 t1)a52"1","(1/a" wE2
#define Sp1 {1 m6 t2,aK2(aL2 t2)LNG_ONLY(aL2 t2)a52"2","5*a"},
#define Tp1 {1 m6 t3,aK2(aL2 t3)LNG_ONLY(aL2 t3)a52"3","5/a"},
#define Up1 {2 m6 t4,aK2(aL2 t4)LNG_ONLY(aL2 t4)hC"4","(a*5)*b"},
#define Wp1 {2 m6 t5,aK2(aL2 t5)LNG_ONLY(aL2 t5)hC"5","(a*5)/b"},
#define Yp1 {2 m6 t6,aK2(aL2 t6)LNG_ONLY(aL2 t6)hC"6","(1/a)*b"},
#define Sq1 {2 m6 t7,aK2(aL2 t7)LNG_ONLY(aL2 t7)hC"7","(1/a)/b"},
#define Tq1 {2 m6 t8,aK2(aL2 t8)LNG_ONLY(aL2 t8)hC"8",hX2")*(" hY2")*" mJ1
#define Uq1 {2 m6 t9,aK2(aL2 t9)LNG_ONLY(aL2 t9)hC"9",hX2")/(" hY2")*" mJ1
#define Wq1 g5 t10,aK2(aL2 t10)LNG_ONLY(aL2 t10)hC"10",hY2")*(5/a" mQ
#define Yq1 g5 t11,aK2(aL2 t11)LNG_ONLY(aL2 t11)hC"11",hY2")/(50/a" mQ
#define Sr1 mE t12,aK2(aL2 t12)LNG_ONLY(aL2 t12)a52"12","(-a)+" gH2
#define Tr1 g5 t13,aK2(aL2 t13)LNG_ONLY(aL2 t13)hC"13","5+(a*b" mQ
#define Ur1 g5 t14,aK2(aL2 t14)LNG_ONLY(aL2 t14)hC"14","5-(a*b" mQ
#define Wr1 g5 t15,aK2(aL2 t15)LNG_ONLY(aL2 t15)hC"15","(a+5)+" hY2 mQ
#define Yr1 g5 t16,aK2(aL2 t16)LNG_ONLY(aL2 t16)hC"16","(a+5)-abs(b" mQ
#define Ss1 g5 t17,aK2(aL2 t17)LNG_ONLY(aL2 t17)hC"17","(-a)+" hY2 mQ
#define Ts1 g5 t18,aK2(aL2 t18)LNG_ONLY(aL2 t18)hC"18","(-a)-abs(b" mQ
#define Us1 g5 t19,aK2(aL2 t19)LNG_ONLY(aL2 t19)hC"19","b+(" hX2")+" mJ1
#define Ws1 g5 t20,aK2(aL2 t20)LNG_ONLY(aL2 t20)hC"20","b-(" hX2")+" mJ1
#define Ys1 g5 t21,aK2(aL2 t21)LNG_ONLY(aL2 t21)hC"21",hY2")+(5-a" mQ
#define St1 g5 t22,aK2(aL2 t22)LNG_ONLY(aL2 t22)hC"22",hY2")-(5-a" mQ
#define Tt1 g5 t23,aK2(aL2 t23)LNG_ONLY(aL2 t23)hC"23",g81"b" wG2
#define Ut1 g5 t24,aK2(aL2 t24)LNG_ONLY(aL2 t24)hC"24",g81"5" wG2
#define Wt1 g5 t25,aK2(aL2 t25)LNG_ONLY(aL2 t25)hC"25",g81"5" wD2
#define Yt1 g5 t26,aK2(aL2 t26)LNG_ONLY(aL2 t26)hC"26","(   abs(a)/b" wG2
#define Su1 g5 t27,aK2(aL2 t27)LNG_ONLY(aL2 t27)hC"27","(   abs(a)/b" wD2
#define Tu1 g5 t28,aK2(aL2 t28)LNG_ONLY(aL2 t28)hC"28","((-a)/b" wE2
#define Uu1 g5 t29,aK2(aL2 t29)LNG_ONLY(aL2 t29)hC"29","(5/b" wD2
#define Wu1 mE t30,aK2(aL2 t30)LNG_ONLY(aL2 t30)"b",qE"30","(7/b" wE2
#define Yu1 g5 t31,aK2(aL2 t31)LNG_ONLY(aL2 t31)hC"31","b*(7/-a" mQ
#define Sv1 g5 t32,aK2(aL2 t32)LNG_ONLY(aL2 t32)hC"32","(5-b)-a"},
#define Tv1 g5 t33,aK2(aL2 t33)LNG_ONLY(aL2 t33)hC"33","(5-b)+a"},
#define Uv1 g5 t34,aK2(aL2 t34)LNG_ONLY(aL2 t34)hC"34","((a+7)-b)+" gH2
#define Wv1 g5 t35,aK2(aL2 t35)LNG_ONLY(aL2 t35)hC"35","((-a)-b)+" gH2
#define Yv1 mE t36,aK2(aL2 t36)LNG_ONLY(aL2 t36)a52"36","(7-abs(a))+" gH2
#define Sw1 g5 t37,aK2(aL2 t37)LNG_ONLY(aL2 t37)hC"37","((7-b)+a)+" gH2
#define Tw1 g5 t38,aK2(aL2 t38)LNG_ONLY(aL2 t38)hC"38","((5*b+" hX2"))<0)*1 + ((" hY2"))<0)*2"},
#define Uw1 mE t39,aK2(aL2 t39)LNG_ONLY(aL2 t39)a52"39","(a+7" wE2
#define Ww1 g5 t40,aK2(aL2 t40)LNG_ONLY(aL2 t40)hC"40","(b+(a*7))*" gH2
#define Yw1 g5 t41,aK2(aL2 t41)LNG_ONLY(aL2 t41)hC"41","(b-(a*7))*" gH2
#define Sx1 mE t42,aK2(aL2 t42)LNG_ONLY(aL2 t42)a52"42","(a+7)+" gH2
#define Tx1 mE t43,aK2(aL2 t43)LNG_ONLY(aL2 t43)a52"43","(a*7" wE2
#define Ux1 aP1 Abseq0,aK2(aJ2 Abseq0)LNG_ONLY(aJ2 Abseq0)gV1"abseq0" oN1"=if" wB2 wW2 wB2")=abs" qV1
#define Wx1 aP1 oN3,aK2(aJ2 oN3)LNG_ONLY(aJ2 oN3)gV1"absneq0" oN1"=if" wB2 wW2 wB2")=abs" qV1
#define Yx1 aP1 Eq0,aK2(aJ2 Eq0)LNG_ONLY(aJ2 Eq0)gV1"eq0","(x=if" d52 wW2 d52")=x)"},
#define Sy1 aP1 Eq1,aK2(aJ2 Eq1)LNG_ONLY(aJ2 Eq1)gV1"eq1","(!x=if" d42"))"},
#define Ty1 aD2 oR3,aK2(aJ2 oR3)LNG_ONLY(aJ2 oR3)gV1"ge0_abs" oN1" >= " hA3 mP o53"<= " qR3"<= " hA3 gQ1 o53">= " gV3
#define Uy1 aD2 oS3,aK2(aJ2 oS3)LNG_ONLY(aJ2 oS3)gV1"ge1_abs" oN1" >= " hC3 mP o63"<= " qR3"<= " hC3 gQ1 o63">= " gV3
#define Wy1 {1 m7 N(0.25),q7 Gehalf,aK2(aJ2 Gehalf)gW"gehalf","x>=if(1,0.5,0" mQ
#define Yy1 aD2 oT3,aK2(aJ2 oT3)LNG_ONLY(aJ2 oT3)gV1"gt0_abs" oN1" > " hA3 mP o53"< " qR3"< " hA3 gQ1 o53"> " gV3
#define Sz1 aD2 oU3,aK2(aJ2 oU3)LNG_ONLY(aJ2 oU3)gV1"gt1_abs" oN1" > " hC3 mP o63"< " qR3"< " hC3 gQ1 o63"> " gV3
#define Tz1 {1 m7 N(0.25),q7 Lthalf,aK2(aJ2 Lthalf)gW"lthalf","x<if(1,0.5,0" mQ
#define Uz1 aP1 Neq0,aK2(aJ2 Neq0)LNG_ONLY(aJ2 Neq0)gV1"neq0","(x!=if" d52 wW2 d52")!=x)"},
#define Wz1 aP1 Neq1,aK2(aJ2 Neq1)LNG_ONLY(aJ2 Neq1)gV1"neq1","(!x!=if" d42"))"},
#define Yz1 {1,-9,9,1,hH t7,aK2(aO2 t7)LNG_ONLY(aO2 t7)"x",oL"7","x>7 & x<2"},
#define S_1 {2,-9,9,1,hH t8,aK2(aO2 t8)qB",y",oL"8",hZ2"(-x,-y) + 10*" hZ2"(-x,y) + 20*" hZ2"(x,-y) + 30*" hZ2"(x" wA1
#define T_1 {1 m7 1,hH t9a,aK2(aO2 t9a)LNG_ONLY(aO2 t9a)"x",oL"9a","a:=x;a*0"},
#define U_1 hB3 t9b,aK2(aO2 t9b)LNG_ONLY(aO2 t9b)d02"9b","sub(a,b" wF2
#define W_1 hB3 t9c,aK2(aO2 t9c)LNG_ONLY(aO2 t9c)d02"9c","psub(a,b" wF2
#define Y_1 hB3 t9d,aK2(aO2 t9d)LNG_ONLY(aO2 t9d)d02"9d","if(a,b*0,a*0" wF2
#define S02 {2,gQ Add_cd,h7 wM"add_cd","x+y"},
#define T02 {2,o72 Add_d,aK2(aN2 Add_d)wM"add_d","x+y"},
#define U02 {3,gQ Addsub_cd,h7 gZ2,g6"addsub_cd","x+y+x+x-z+x"},
#define W02 {3,o72 Addsub_d,aK2(aN2 Addsub_d)gZ2,g6"addsub_d","x+y+x+x-z+x"},
#define Y02 {2,gJ And_d,aK2(aN2 And_d)wM"and_d","x&y"},
#define S12 {2,gQ Cmpeq_cd,h7 wM"cmpeq_cd","x=y"},
#define T12 {2,gJ Cmpeq_d,aK2(aN2 Cmpeq_d)wM"cmpeq_d","x=y"},
#define U12 {2,gJ Cmpge_d,aK2(aN2 Cmpge_d)wM"cmpge_d","x>=y"},
#define W12 {2,gJ Cmpgt_d,aK2(aN2 Cmpgt_d)wM"cmpgt_d","x>y"},
#define Y12 {2,gJ Cmple_d,aK2(aN2 Cmple_d)wM"cmple_d","x<=y"},
#define S22 {2,gJ Cmplt_d,aK2(aN2 Cmplt_d)wM"cmplt_d","x<y"},
#define T22 {2,gQ Cmpne_cd,h7 wM"cmpne_cd","x!=y"},
#define U22 {2,gJ Cmpne_d,aK2(aN2 Cmpne_d)wM"cmpne_d","x!=y"},
#define W22 {2,dR Div_d,aK2(aN2 Div_d)wM"div_d","(x-0.25)/y"},
#define Y22 {3,dR Divmul_d,aK2(aN2 Divmul_d)gZ2,g6"divmul_d","x*y*x*x/z" wZ1"-0.25" mQ
#define S32 {1,N(-7.0,0.0),N(6.0,0.0),N(0.6,0.0),qM Inv_d,aK2(aN2 Inv_d)qB,g6"inv_d","1/x"},
#define T32 {2,N(-7.25,+3.625),N(7.25,-3.625),N(0.5,-0.25),qM Mul_cd,h7 wM"mul_cd","x*y"},
#define U32 {2,dR Mul_d,aK2(aN2 Mul_d)wM"mul_d","x*y"},
#define W32 {1,gQ Neg_cd,h7 qB,g6"neg_cd","-x"},
#define Y32 {1,o72 Neg_d,aK2(aN2 Neg_d)qB,g6"neg_d","-x"},
#define S42 {1,N(-1.25,0.0),N(1.25,0.0)gX1 qM Not_d,aK2(aN2 Not_d)qB,g6"not_d","!x"},
#define T42 {1,N(-1.25,0.0),N(1.25,0.0)gX1 qM Notnot_d,aK2(aN2 Notnot_d)qB,g6"notnot_d","!!x"},
#define U42 {2,gJ Or_d,aK2(aN2 Or_d)wM"or_d","x|y"},
#define W42 {2,gQ Sub_cd,h7 wM"sub_cd","x-y"},
#define Y42 {2,o72 Sub_d,aK2(aN2 Sub_d)wM"sub_d","x-y"},
#define S52 {1,N(-400.0,+200.0),N(400.0,-200.0),N(0.5,-0.25)w8 Abs_cd qF"/abs_cd",m01},
#define T52 gR Arg qF"/arg",aQ1
#define U52 gR Conj qF"/conj","conj(x)"},
#define W52 gR Imag qF"/imag","imag(x)"},
#define Y52 gR Log,aK2(aR2 Log)qO"/log",aQ1
#define S62 {1,N(-4000.0,-0.5),N(4000.0,+0.5),N(0.3,+3.75e-05)w8 Log_cd qF"/log_cd",aQ1
#define T62 {2,N(-4.0,0.0),wK1 N(1.0,0.0)w8 Max,aK2(aR2 Max)LNG_ONLY(aR2 Max)"x,y" wB"/max","max(x" wA1
#define U62 {2,N(-4.0,0.0),wK1 N(1.0,0.0)w8 Min,aK2(aR2 Min)LNG_ONLY(aR2 Min)"x,y" wB"/min","min(x" wA1
#define W62 {2,N(0.01,0.0),wK1 N(0.05,0.0)w8 Polar,h7 wA"/polar","polar(x" wA1
#define Y62 gR Real qF"/real","real(x)"},
#define S72 {1,N(-100000.0,0.0),N(100000.0,0.0),N(1000.0,0.0)w8 Sqrt_cd qF"/sqrt_cd","sqrt(x)"},
#define T72 {1,g9 t1,aK2(aL2 t1)LNG_ONLY(aL2 t1)a52"1","(1/a" wE2
#define U72 {1,g9 t2,aK2(aL2 t2)LNG_ONLY(aL2 t2)a52"2","5*a"},
#define W72 {1,g9 t3,aK2(aL2 t3)LNG_ONLY(aL2 t3)a52"3","5/a"},
#define Y72 {2,g9 t4,aK2(aL2 t4)LNG_ONLY(aL2 t4)hC"4","(a*5)*b"},
#define S82 {2,g9 t5,aK2(aL2 t5)LNG_ONLY(aL2 t5)hC"5","(a*5)/b"},
#define T82 {2,g9 t6,aK2(aL2 t6)LNG_ONLY(aL2 t6)hC"6","(1/a)*b"},
#define U82 {2,g9 t7,aK2(aL2 t7)LNG_ONLY(aL2 t7)hC"7","(1/a)/b"},
#define W82 {2,g9 t8,aK2(aL2 t8)LNG_ONLY(aL2 t8)hC"8",hX2")*(" hY2")*" mJ1
#define Y82 {2,g9 t9,aK2(aL2 t9)LNG_ONLY(aL2 t9)hC"9",hX2")/(" hY2")*" mJ1
#define S92 mK1 t10,aK2(aL2 t10)LNG_ONLY(aL2 t10)hC"10",hY2")*(5/a" mQ
#define T92 mK1 t11,aK2(aL2 t11)LNG_ONLY(aL2 t11)hC"11",hY2")/(50/a" mQ
#define U92 {1,q6 t12,aK2(aL2 t12)LNG_ONLY(aL2 t12)a52"12","(-a)+" gH2
#define W92 mK1 t13,aK2(aL2 t13)LNG_ONLY(aL2 t13)hC"13","5+(a*b" mQ
#define Y92 mK1 t14,aK2(aL2 t14)LNG_ONLY(aL2 t14)hC"14","5-(a*b" mQ
#define SA2 mK1 t15,aK2(aL2 t15)LNG_ONLY(aL2 t15)hC"15","(a+5)+" hY2 mQ
#define TA2 mK1 t16,aK2(aL2 t16)LNG_ONLY(aL2 t16)hC"16","(a+5)-abs(b" mQ
#define UA2 mK1 t17,aK2(aL2 t17)LNG_ONLY(aL2 t17)hC"17","(-a)+" hY2 mQ
#define WA2 mK1 t18,aK2(aL2 t18)LNG_ONLY(aL2 t18)hC"18","(-a)-abs(b" mQ
#define YA2 mK1 t19,aK2(aL2 t19)LNG_ONLY(aL2 t19)hC"19","b+(" hX2")+" mJ1
#define SB2 mK1 t20,aK2(aL2 t20)LNG_ONLY(aL2 t20)hC"20","b-(" hX2")+" mJ1
#define TB2 mK1 t21,aK2(aL2 t21)LNG_ONLY(aL2 t21)hC"21",hY2")+(5-a" mQ
#define UB2 mK1 t22,aK2(aL2 t22)LNG_ONLY(aL2 t22)hC"22",hY2")-(5-a" mQ
#define WB2 mK1 t23,aK2(aL2 t23)LNG_ONLY(aL2 t23)hC"23",g81"b" wG2
#define YB2 mK1 t24,aK2(aL2 t24)LNG_ONLY(aL2 t24)hC"24",g81"5" wG2
#define SC2 mK1 t25,aK2(aL2 t25)LNG_ONLY(aL2 t25)hC"25",g81"5" wD2
#define TC2 mK1 t26,aK2(aL2 t26)LNG_ONLY(aL2 t26)hC"26","(   abs(a)/b" wG2
#define UC2 mK1 t27,aK2(aL2 t27)LNG_ONLY(aL2 t27)hC"27","(   abs(a)/b" wD2
#define WC2 mK1 t28,aK2(aL2 t28)LNG_ONLY(aL2 t28)hC"28","((-a)/b" wE2
#define YC2 mK1 t29,aK2(aL2 t29)LNG_ONLY(aL2 t29)hC"29","(5/b" wD2
#define SD2 {1,q6 t30,aK2(aL2 t30)LNG_ONLY(aL2 t30)"b",qE"30","(7/b" wE2
#define TD2 mK1 t31,aK2(aL2 t31)LNG_ONLY(aL2 t31)hC"31","b*(7/-a" mQ
#define UD2 mK1 t32,aK2(aL2 t32)LNG_ONLY(aL2 t32)hC"32","(5-b)-a"},
#define WD2 mK1 t33,aK2(aL2 t33)LNG_ONLY(aL2 t33)hC"33","(5-b)+a"},
#define YD2 mK1 t34,aK2(aL2 t34)LNG_ONLY(aL2 t34)hC"34","((a+7)-b)+" gH2
#define SE2 mK1 t35,aK2(aL2 t35)LNG_ONLY(aL2 t35)hC"35","((-a)-b)+" gH2
#define TE2 {1,q6 t36,aK2(aL2 t36)LNG_ONLY(aL2 t36)a52"36","(7-abs(a))+" gH2
#define UE2 mK1 t37,aK2(aL2 t37)LNG_ONLY(aL2 t37)hC"37","((7-b)+a)+" gH2
#define WE2 mK1 t38,aK2(aL2 t38)LNG_ONLY(aL2 t38)hC"38","((5*b+" hX2"))<0)*1 + ((" hY2"))<0)*2"},
#define YE2 {1,q6 t39,aK2(aL2 t39)LNG_ONLY(aL2 t39)a52"39","(a+7" wE2
#define SF2 mK1 t40,aK2(aL2 t40)LNG_ONLY(aL2 t40)hC"40","(b+(a*7))*" gH2
#define TF2 mK1 t41,aK2(aL2 t41)LNG_ONLY(aL2 t41)hC"41","(b-(a*7))*" gH2
#define UF2 {1,q6 t42,aK2(aL2 t42)LNG_ONLY(aL2 t42)a52"42","(a+7)+" gH2
#define WF2 {1,q6 t43,aK2(aL2 t43)LNG_ONLY(aL2 t43)a52"43","(a*7" wE2
#define YF2 {m9 Abscos,aK2(aJ2 Abscos)gW"abscos","cos(sqrt" dL1"))) + sqrt" dL1"))"},
#define SG2 {m9 Abscosh,aK2(aJ2 Abscosh)gW"abscosh","cosh(sqrt" dL1"))) + sqrt" dL1"))"},
#define TG2 {1,N(0.0,0.0)qN Abseq0,aK2(aJ2 Abseq0)LNG_ONLY(aJ2 Abseq0)gV1"abseq0" oN1"=if" wB2 wW2 wB2")=abs" qV1
#define UG2 {1,N(0.0,0.0)qN oN3,aK2(aJ2 oN3)LNG_ONLY(aJ2 oN3)gV1"absneq0" oN1"=if" wB2 wW2 wB2")=abs" qV1
#define WG2 {1,N(-5.0,0.0),N(5.0,0.0),dN1 oD3,aK2(aJ2 oD3)LNG_ONLY(aJ2 oD3)gV1"absnzge","sub(" m01" >= if(" gO2"), abs(x)" dW2"(if(1,1,0)-1))"},
#define YG2 {1,N(-5.0,0.0),N(5.0,0.0),dN1 oE3,aK2(aJ2 oE3)LNG_ONLY(aJ2 oE3)gV1"absnzlt","sub(" m01" < if(" gO2"), abs(x) < (if(1,1,0)-1))"},
#define SH2 {1,hT N(0.1,0.0),q7 Acoscos,aK2(aJ2 Acoscos)gW"acoscos","cos(acos" qV1
#define TH2 {1,N(1.7,0.0),N(3.7,0.0),N(0.28,0.0),q7 Acoshsinh,aK2(aJ2 Acoshsinh)gW w12 gA2,gA2"(if(1,acosh(x),0))"},
#define UH2 {hS gL3,aK2(aJ2 gL3)LNG_ONLY(aJ2 gL3)qR"addconstmul","5*(if(" gO2")+x+y" mQ
#define WH2 {2 gX1 N(1.0,0.0)gX1 q7 Addlog,aK2(aJ2 Addlog)qX1"addlog","log(x)+log(y" mQ
#define YH2 {hS qS3,aK2(aJ2 qS3)LNG_ONLY(aJ2 qS3)qR"addmulconstmul","5*(if(" gO2")*y+x)"},
#define SI2 {hS g73,aK2(aJ2 g73)LNG_ONLY(aJ2 g73)qR"addnegmulneg","-5 + (if(1,5,0)*x*y" mQ
#define TI2 {hS g83,aK2(aJ2 g83)LNG_ONLY(aJ2 g83)qR"addnegmulpos","(if(1,-5,0)*y" wA2"if(1,5,0)*x)"},
#define UI2 {1 w1 Addsin2cos2,aK2(aJ2 Addsin2cos2)gW"addsin2cos2",a51"^2 + cos(x)^2"},
#define WI2 {1,N(-0.7,0.0),N(0.7,0.0),N(0.28,0.0),q7 Asinhcosh,aK2(aJ2 Asinhcosh)gW"asinhcosh","cosh(if(1,a" gA2"(x),0))"},
#define YI2 {1,hT N(0.1,0.0),q7 Asinsin,aK2(aJ2 Asinsin)gW"asinsin","sin(asin(x))"},
#define SJ2 w51 qY3,aK2(aJ2 qY3)LNG_ONLY(aJ2 qY3)qR"cmpeq_add_imm",gA1 q32
#define TJ2 mL1 mV2,aK2(aJ2 mV2)LNG_ONLY(aJ2 mV2)gV1"cmpeq_add_reduce",dV" = " gZ},
#define UJ2 w51 mW2,aK2(aJ2 mW2)LNG_ONLY(aJ2 mW2)qR"cmpeq_addadd_imm",o3") = " hX
#define WJ2 {hI g93,aK2(aJ2 g93)LNG_ONLY(aJ2 g93)qR"cmpeq_minma" dA3"=" dB3
#define YJ2 {hI mX2,aK2(aJ2 mX2)LNG_ONLY(aJ2 mX2)qR"cmpeq_minma" dC3"=" dE3
#define SK2 w51 mD2,aK2(aJ2 mD2)LNG_ONLY(aJ2 mD2)qR"cmpeq_mul_imm_neg",dD1 q32
#define TK2 w51 mE2,aK2(aJ2 mE2)LNG_ONLY(aJ2 mE2)qR"cmpeq_mul_imm_pos",o41 q32
#define UK2 w51 aV2,aK2(aJ2 aV2)LNG_ONLY(aJ2 aV2)qR"cmpeq_mulmul_imm_neg",m11" = " hX
#define WK2 w51 aW2,aK2(aJ2 aW2)LNG_ONLY(aJ2 aW2)qR"cmpeq_mulmul_imm_pos",m21" = " hX
#define YK2 {1,mR Cmpeq_pow_imm_negneg,aK2(aJ2 Cmpeq_pow_imm_negneg)aH2 hV" = " d63
#define SL2 {1,mR Cmpeq_pow_imm_negpos,aK2(aJ2 Cmpeq_pow_imm_negpos)aH2 hY" = " aU2
#define TL2 mL1 Cmpeq_pow_imm_posneg,aK2(aJ2 Cmpeq_pow_imm_posneg)aH2 d2" = " qL3
#define UL2 mL1 Cmpeq_pow_imm_pospos,aK2(aJ2 Cmpeq_pow_imm_pospos)aH2 d3" = " gO3
#define WL2 mL1 Cmpeq_pow_imm_pospos_base,aK2(aJ2 Cmpeq_pow_imm_pospos_base)aH2 mC2"= " wO
#define YL2 w51 Cmpeq_powpow_imm_base,aK2(aJ2 Cmpeq_powpow_imm_base)qX1 oA1 hF" = " a1
#define SM2 w51 qZ3,aK2(aJ2 qZ3)LNG_ONLY(aJ2 qZ3)qR"cmpge_add_imm",gA1 aC1
#define TM2 mL1 mZ2,aK2(aJ2 mZ2)LNG_ONLY(aJ2 mZ2)gV1"cmpge_add_reduce",dV dW2 gZ},
#define UM2 w51 q03,aK2(aJ2 q03)LNG_ONLY(aJ2 q03)qR"cmpge_addadd_imm",o3")" dW2 hX
#define WM2 {hI gA3,aK2(aJ2 gA3)LNG_ONLY(aJ2 gA3)qR"cmpge_minma" dA3">=" dB3
#define YM2 {hI q13,aK2(aJ2 q13)LNG_ONLY(aJ2 q13)qR"cmpge_minma" dC3">=" dE3
#define SN2 w51 mF2,aK2(aJ2 mF2)LNG_ONLY(aJ2 mF2)qR"cmpge_mul_imm_neg",dD1 aC1
#define TN2 w51 mG2,aK2(aJ2 mG2)LNG_ONLY(aJ2 mG2)qR"cmpge_mul_imm_pos",o41 aC1
#define UN2 w51 aX2,aK2(aJ2 aX2)LNG_ONLY(aJ2 aX2)qR"cmpge_mulmul_imm_neg",m11 dW2 hX
#define WN2 w51 aY2,aK2(aJ2 aY2)LNG_ONLY(aJ2 aY2)qR"cmpge_mulmul_imm_pos",m21 dW2 hX
#define YN2 {1,mR Cmpge_pow_imm_negneg,aK2(aJ2 Cmpge_pow_imm_negneg)hW1 hV" >= " d63
#define SO2 {1,mR Cmpge_pow_imm_negpos,aK2(aJ2 Cmpge_pow_imm_negpos)hW1 hY" >= " aU2
#define TO2 mL1 Cmpge_pow_imm_posneg,aK2(aJ2 Cmpge_pow_imm_posneg)hW1 d2" >= " qL3
#define UO2 mL1 Cmpge_pow_imm_pospos,aK2(aJ2 Cmpge_pow_imm_pospos)hW1 d3" >= " gO3
#define WO2 mL1 Cmpge_pow_imm_pospos_base,aK2(aJ2 Cmpge_pow_imm_pospos_base)hW1 mC2">= " wO
#define YO2 w51 Cmpge_powpow_imm_base,aK2(aJ2 Cmpge_powpow_imm_base)qX1"cmpge_" hF dW2 a1
#define SP2 w51 g03,aK2(aJ2 g03)LNG_ONLY(aJ2 g03)qR"cmpgt_add_imm",gA1 q42
#define TP2 mL1 q23,aK2(aJ2 q23)LNG_ONLY(aJ2 q23)gV1"cmpgt_add_reduce",dV" > " gZ},
#define UP2 w51 q33,aK2(aJ2 q33)LNG_ONLY(aJ2 q33)qR"cmpgt_addadd_imm",o3") > " hX
#define WP2 {hI gB3,aK2(aJ2 gB3)LNG_ONLY(aJ2 gB3)qR"cmpgt_minma" dA3">" dB3
#define YP2 {hI q43,aK2(aJ2 q43)LNG_ONLY(aJ2 q43)qR"cmpgt_minma" dC3">" dE3
#define SQ2 w51 mH2,aK2(aJ2 mH2)LNG_ONLY(aJ2 mH2)qR"cmpgt_mul_imm_neg",dD1 q42
#define TQ2 w51 mI2,aK2(aJ2 mI2)LNG_ONLY(aJ2 mI2)qR"cmpgt_mul_imm_pos",o41 q42
#define UQ2 w51 aZ2,aK2(aJ2 aZ2)LNG_ONLY(aJ2 aZ2)qR"cmpgt_mulmul_imm_neg",m11" > " hX
#define WQ2 w51 m02,aK2(aJ2 m02)LNG_ONLY(aJ2 m02)qR"cmpgt_mulmul_imm_pos",m21" > " hX
#define YQ2 {1,mR Cmpgt_pow_imm_negneg,aK2(aJ2 Cmpgt_pow_imm_negneg)hX1 hV" > " d63
#define SR2 {1,mR Cmpgt_pow_imm_negpos,aK2(aJ2 Cmpgt_pow_imm_negpos)hX1 hY" > " aU2
#define TR2 mL1 Cmpgt_pow_imm_posneg,aK2(aJ2 Cmpgt_pow_imm_posneg)hX1 d2" > " qL3
#define UR2 mL1 Cmpgt_pow_imm_pospos,aK2(aJ2 Cmpgt_pow_imm_pospos)hX1 d3" > " gO3
#define WR2 mL1 Cmpgt_pow_imm_pospos_base,aK2(aJ2 Cmpgt_pow_imm_pospos_base)hX1 mC2"> " wO
#define YR2 w51 Cmpgt_powpow_imm_base,aK2(aJ2 Cmpgt_powpow_imm_base)qX1"cmpgt_" hF" > " a1
#define SS2 w51 g13,aK2(aJ2 g13)LNG_ONLY(aJ2 g13)qR"cmple_add_imm",gA1 aD1
#define TS2 mL1 q53,aK2(aJ2 q53)LNG_ONLY(aJ2 q53)gV1"cmple_add_reduce",dV dX2 gZ},
#define US2 w51 q63,aK2(aJ2 q63)LNG_ONLY(aJ2 q63)qR"cmple_addadd_imm",o3")" dX2 hX
#define WS2 {hI gC3,aK2(aJ2 gC3)LNG_ONLY(aJ2 gC3)qR"cmple_minma" dA3"<=" dB3
#define YS2 {hI q73,aK2(aJ2 q73)LNG_ONLY(aJ2 q73)qR"cmple_minma" dC3"<=" dE3
#define ST2 w51 mJ2,aK2(aJ2 mJ2)LNG_ONLY(aJ2 mJ2)qR"cmple_mul_imm_neg",dD1 aD1
#define TT2 w51 mK2,aK2(aJ2 mK2)LNG_ONLY(aJ2 mK2)qR"cmple_mul_imm_pos",o41 aD1
#define UT2 w51 m12,aK2(aJ2 m12)LNG_ONLY(aJ2 m12)qR"cmple_mulmul_imm_neg",m11 dX2 hX
#define WT2 w51 m22,aK2(aJ2 m22)LNG_ONLY(aJ2 m22)qR"cmple_mulmul_imm_pos",m21 dX2 hX
#define YT2 {1,mR Cmple_pow_imm_negneg,aK2(aJ2 Cmple_pow_imm_negneg)hY1 hV" <= " d63
#define SU2 {1,mR Cmple_pow_imm_negpos,aK2(aJ2 Cmple_pow_imm_negpos)hY1 hY" <= " aU2
#define TU2 mL1 Cmple_pow_imm_posneg,aK2(aJ2 Cmple_pow_imm_posneg)hY1 d2" <= " qL3
#define UU2 mL1 Cmple_pow_imm_pospos,aK2(aJ2 Cmple_pow_imm_pospos)hY1 d3" <= " gO3
#define WU2 mL1 Cmple_pow_imm_pospos_base,aK2(aJ2 Cmple_pow_imm_pospos_base)hY1 mC2"<= " wO
#define YU2 w51 Cmple_powpow_imm_base,aK2(aJ2 Cmple_powpow_imm_base)qX1"cmple_" hF dX2 a1
#define SV2 w51 g23,aK2(aJ2 g23)LNG_ONLY(aJ2 g23)qR"cmplt_add_imm",gA1 q52
#define TV2 mL1 q83,aK2(aJ2 q83)LNG_ONLY(aJ2 q83)gV1"cmplt_add_reduce",dV" < " gZ},
#define UV2 w51 q93,aK2(aJ2 q93)LNG_ONLY(aJ2 q93)qR"cmplt_addadd_imm",o3") < " hX
#define WV2 {hI gD3,aK2(aJ2 gD3)LNG_ONLY(aJ2 gD3)qR"cmplt_minma" dA3"<" dB3
#define YV2 {hI qA3,aK2(aJ2 qA3)LNG_ONLY(aJ2 qA3)qR"cmplt_minma" dC3"<" dE3
#define SW2 w51 mL2,aK2(aJ2 mL2)LNG_ONLY(aJ2 mL2)qR"cmplt_mul_imm_neg",dD1 q52
#define TW2 w51 mM2,aK2(aJ2 mM2)LNG_ONLY(aJ2 mM2)qR"cmplt_mul_imm_pos",o41 q52
#define UW2 w51 m32,aK2(aJ2 m32)LNG_ONLY(aJ2 m32)qR"cmplt_mulmul_imm_neg",m11" < " hX
#define WW2 w51 m42,aK2(aJ2 m42)LNG_ONLY(aJ2 m42)qR"cmplt_mulmul_imm_pos",m21" < " hX
#define YW2 {1,mR Cmplt_pow_imm_negneg,aK2(aJ2 Cmplt_pow_imm_negneg)hZ1 hV" < " d63
#define SX2 {1,mR Cmplt_pow_imm_negpos,aK2(aJ2 Cmplt_pow_imm_negpos)hZ1 hY" < " aU2
#define TX2 mL1 Cmplt_pow_imm_posneg,aK2(aJ2 Cmplt_pow_imm_posneg)hZ1 d2" < " qL3
#define UX2 mL1 Cmplt_pow_imm_pospos,aK2(aJ2 Cmplt_pow_imm_pospos)hZ1 d3" < " gO3
#define WX2 mL1 Cmplt_pow_imm_pospos_base,aK2(aJ2 Cmplt_pow_imm_pospos_base)hZ1 mC2"< " wO
#define YX2 w51 Cmplt_powpow_imm_base,aK2(aJ2 Cmplt_powpow_imm_base)qX1"cmplt_" hF" < " a1
#define SY2 w51 g33,aK2(aJ2 g33)LNG_ONLY(aJ2 g33)qR"cmpne_add_imm",gA1 aE1
#define TY2 mL1 qB3,aK2(aJ2 qB3)LNG_ONLY(aJ2 qB3)gV1"cmpne_add_reduce",dV dY2 gZ},
#define UY2 w51 qC3,aK2(aJ2 qC3)LNG_ONLY(aJ2 qC3)qR"cmpne_addadd_imm",o3")" dY2 hX
#define WY2 {hI gE3,aK2(aJ2 gE3)LNG_ONLY(aJ2 gE3)qR"cmpne_minma" dA3"!=" dB3
#define YY2 {hI qD3,aK2(aJ2 qD3)LNG_ONLY(aJ2 qD3)qR"cmpne_minma" dC3"!=" dE3
#define SZ2 w51 mN2,aK2(aJ2 mN2)LNG_ONLY(aJ2 mN2)qR"cmpne_mul_imm_neg",dD1 aE1
#define TZ2 w51 mO2,aK2(aJ2 mO2)LNG_ONLY(aJ2 mO2)qR"cmpne_mul_imm_pos",o41 aE1
#define UZ2 w51 m52,aK2(aJ2 m52)LNG_ONLY(aJ2 m52)qR"cmpne_mulmul_imm_neg",m11 dY2 hX
#define WZ2 w51 m62,aK2(aJ2 m62)LNG_ONLY(aJ2 m62)qR"cmpne_mulmul_imm_pos",m21 dY2 hX
#define YZ2 {1,mR Cmpne_pow_imm_negneg,aK2(aJ2 Cmpne_pow_imm_negneg)d01 hV" != " d63
#define Sa2 {1,mR Cmpne_pow_imm_negpos,aK2(aJ2 Cmpne_pow_imm_negpos)d01 hY" != " aU2
#define Ta2 mL1 Cmpne_pow_imm_posneg,aK2(aJ2 Cmpne_pow_imm_posneg)d01 d2" != " qL3
#define Ua2 mL1 Cmpne_pow_imm_pospos,aK2(aJ2 Cmpne_pow_imm_pospos)d01 d3" != " gO3
#define Wa2 mL1 Cmpne_pow_imm_pospos_base,aK2(aJ2 Cmpne_pow_imm_pospos_base)d01 mC2"!= " wO
#define Ya2 w51 Cmpne_powpow_imm_base,aK2(aJ2 Cmpne_powpow_imm_base)qX1"cmpne_" hF dY2 a1
#define Sb2 w51 g43,aK2(aJ2 g43)LNG_ONLY(aJ2 g43)qR"cmpzz_add_imm" dM q62 aS1 q62 wB1 q62 aG1 q62 wC1 q62 aF1 gA1 q32
#define Tb2 mL1 qE3,aK2(aJ2 qE3)LNG_ONLY(aJ2 qE3)gV1"cmpzz_add_reduce" dM dZ2" < " gZ a9 dZ2 dX2 gZ aA dZ2" > " gZ aB dZ2 dW2 gZ aC dZ2 dY2 gZ d6 dV" = " gZ},
#define Ub2 w51 qF3,aK2(aJ2 qF3)LNG_ONLY(aJ2 qF3)qR"cmpzz_addadd_imm" dM" " o3 gB1 o3 gC1 o3 gE1 o3 gF1 o3")" w61 o3") = " hX
#define Wb2 {hI gF3,aK2(aJ2 gF3)LNG_ONLY(aJ2 gF3)qR"cmpzz_minmax" dM gG3"< " gR3 a9 gG3"<= " gR3 aA gG3"> " gR3 aB gG3">= " gR3 aC gG3"!= " gR3" +  0x0020 *" gG3"=" dB3
#define Yb2 {hI qG3,aK2(aJ2 qG3)LNG_ONLY(aJ2 qG3)qR"cmpzz_minmax_rev" dM gG3"<" dD3 a9 gG3"<=" dD3 aA gG3">" dD3 aB gG3">=" dD3 aC gG3"!=" dD3" +  0x0020 *" gG3"=" dE3
#define Sc2 w51 mP2,aK2(aJ2 mP2)LNG_ONLY(aJ2 mP2)qR"cmpzz_mul_imm_neg" dM g51 aS1 g51 wB1 g51 aG1 g51 wC1 g51 aF1 dD1 q32
#define Tc2 w51 mQ2,aK2(aJ2 mQ2)LNG_ONLY(aJ2 mQ2)qR"cmpzz_mul_imm_pos" dM g61 aS1 g61 wB1 g61 aG1 g61 wC1 g61 aF1 o41 q32
#define Uc2 w51 m72,aK2(aJ2 m72)LNG_ONLY(aJ2 m72)qR"cmpzz_mulmul_imm_neg" dM" " gJ1 gB1 gJ1 gC1 gJ1 gE1 gJ1 gF1 m11 w61 m11" = " hX
#define Wc2 w51 m82,aK2(aJ2 m82)LNG_ONLY(aJ2 m82)qR"cmpzz_mulmul_imm_pos" dM" " wL"4" gB1 wL"4" gC1 wL"4" gE1 wL"4" gF1 m21 w61 m21" = " hX
#define Yc2 {1,mR Cmpzz_pow_imm_negneg,aK2(aJ2 Cmpzz_pow_imm_negneg)q61"_imm_negneg" mF1 o13"< " aS2 hA2 o13"<= " aS2 hB2 o13"> " aS2 hC2 o13">= " aS2 hD2 o13"!= " aS2 hE2 o13"= " d63
#define Sd2 {1,mR Cmpzz_pow_imm_negpos,aK2(aJ2 Cmpzz_pow_imm_negpos)q61"_imm_negpos" mF1 o23"< " gT3 hA2 o23"<= " gT3 hB2 o23"> " gT3 hC2 o23">= " gT3 hD2 o23"!= " gT3 hE2 o23"= " aU2
#define Td2 mL1 Cmpzz_pow_imm_posneg,aK2(aJ2 Cmpzz_pow_imm_posneg)q61"_imm_posneg" mF1 o33"< " o93 hA2 o33"<= " o93 hB2 o33"> " o93 hC2 o33">= " o93 hD2 o33"!= " o93 hE2 o33"= " qL3
#define Ud2 mL1 Cmpzz_pow_imm_pospos,aK2(aJ2 Cmpzz_pow_imm_pospos)q61"_imm_pospos" mF1",2) < 25" hA2",2) <= 25" hB2",2) > 25" hC2",2) >= 25" hD2",2) != 25" hE2",2) = " gO3
#define Wd2 mL1 Cmpzz_pow_imm_pospos_base,aK2(aJ2 Cmpzz_pow_imm_pospos_base)q61"_imm_pospos_base" dM d53"< " mV a9 d53"<= " mV aA d53"> " mV aB d53">= " mV aC d53"!= " mV d6 qK3"= " wO
#define Yd2 w51 Cmpzz_powpow_imm_base,aK2(aJ2 Cmpzz_powpow_imm_base)qX1"cmpzz_powpow_imm_base" dM a72" < " qY1 a9 a72 dX2 qY1 aA a72" > " qY1 aB a72 dW2 qY1 aC a72 dY2 qY1 d6 qF1" = " a1
#define Se2 {1,N(0.0,0.0)qN Eq0,aK2(aJ2 Eq0)LNG_ONLY(aJ2 Eq0)gV1"eq0","(x=if" d52 wW2 d52")=x)"},
#define Te2 {1,N(0.0,0.0)qN Eq1,aK2(aJ2 Eq1)LNG_ONLY(aJ2 Eq1)gV1"eq1","(!x=if" d42"))"},
#define Ue2 {2,o2 Expexp_a,aK2(aJ2 Expexp_a)qX1 w42"p_a","exp(x*2 + y*3" mQ
#define We2 {3,o2 Expexp_b,aK2(aJ2 Expexp_b)m5 w42"p_b",aJ" * exp(y+z" mQ
#define Ye2 {3,o2 Expexp_c,aK2(aJ2 Expexp_c)m5 w42"p_c","exp(x + y*z" mQ
#define Sf2 {m9 oR3,aK2(aJ2 oR3)LNG_ONLY(aJ2 oR3)gV1"ge0_abs" oN1" >= " hA3 mP o53"<= " qR3"<= " hA3 gQ1 o53">= " gV3
#define Tf2 {m9 oS3,aK2(aJ2 oS3)LNG_ONLY(aJ2 oS3)gV1"ge1_abs" oN1" >= " hC3 mP o63"<= " qR3"<= " hC3 gQ1 o63">= " gV3
#define Uf2 {hI hF3,aK2(aJ2 hF3)LNG_ONLY(aJ2 hF3)qR"ge_and_eq",oX2 dE1
#define Wf2 {hI hG3,aK2(aJ2 hG3)LNG_ONLY(aJ2 hG3)qR"ge_and_le",oX2 hV1 mQ
#define Yf2 {hI hH3,aK2(aJ2 hH3)LNG_ONLY(aJ2 hH3)qR"ge_and_ne",oX2 dF1
#define Sg2 {hI dF3,aK2(aJ2 dF3)LNG_ONLY(aJ2 dF3)qR"ge_or_eq",oY2 dE1
#define Tg2 {hI dG3,aK2(aJ2 dG3)LNG_ONLY(aJ2 dG3)qR"ge_or_le",oY2 hV1 mQ
#define Ug2 {hI dH3,aK2(aJ2 dH3)LNG_ONLY(aJ2 dH3)qR"ge_or_ne",oY2 dF1
#define Wg2 {1,hT N(0.25,0.0),q7 Gehalf,aK2(aJ2 Gehalf)gW"gehalf","x>=if(1,0.5,0" mQ
#define Yg2 {m9 oT3,aK2(aJ2 oT3)LNG_ONLY(aJ2 oT3)gV1"gt0_abs" oN1" > " hA3 mP o53"< " qR3"< " hA3 gQ1 o53"> " gV3
#define Sh2 {m9 oU3,aK2(aJ2 oU3)LNG_ONLY(aJ2 oU3)gV1"gt1_abs" oN1" > " hC3 mP o63"< " qR3"< " hC3 gQ1 o63"> " gV3
#define Th2 {hI hI3,aK2(aJ2 hI3)LNG_ONLY(aJ2 hI3)qR"gt_and_eq" m31 dE1
#define Uh2 {hI hJ3,aK2(aJ2 hJ3)LNG_ONLY(aJ2 hJ3)qR"gt_and_ge" m31 aY},
#define Wh2 {hI hK3,aK2(aJ2 hK3)LNG_ONLY(aJ2 hK3)qR"gt_and_le" m31 hV1 mQ
#define Yh2 {hI hL3,aK2(aJ2 hL3)LNG_ONLY(aJ2 hL3)qR"gt_and_ne" m31 dF1
#define Si2 {hI dI3,aK2(aJ2 dI3)LNG_ONLY(aJ2 dI3)qR"gt_or_eq" m81 dE1
#define Ti2 {hI dJ3,aK2(aJ2 dJ3)LNG_ONLY(aJ2 dJ3)qR"gt_or_ge" m81 aY},
#define Ui2 {hI dK3,aK2(aJ2 dK3)LNG_ONLY(aJ2 dK3)qR"gt_or_le" m81 hV1 mQ
#define Wi2 {hI dL3,aK2(aJ2 dL3)LNG_ONLY(aJ2 dL3)qR"gt_or_ne" m81 dF1
#define Yi2 {1,N(0.0,0.0)qN If10,aK2(aJ2 If10)LNG_ONLY(aJ2 If10)gV1"if10",o0",1,0) + 10*" o0",0,1)" w83"+ 100*" o0">0,1,0) + 1000*" o0">0,0,1" mQ
#define Sj2 {gE qT3,aK2(aJ2 qT3)LNG_ONLY(aJ2 qT3)mM1"tract_abs",o0", abs(x+2), abs(y+5))"},
#define Tj2 {gE qU3,aK2(aJ2 qU3)LNG_ONLY(aJ2 qU3)mM1"tract_add",o0", y+2, y+" mJ1
#define Uj2 {gE qM3,aK2(aJ2 qM3)LNG_ONLY(aJ2 qM3)mM1"tract_add1",o0", y+2, y" mQ
#define Wj2 {gE qN3,aK2(aJ2 qN3)LNG_ONLY(aJ2 qN3)mM1"tract_add2",o0", y, y+2" mQ
#define Yj2 {oD mR2,aK2(aJ2 mR2)LNG_ONLY(aJ2 mR2)m91"tract_and1_l",o0", y&z, y<1" mQ
#define Sk2 {oD m92,aK2(aJ2 m92)LNG_ONLY(aJ2 m92)m91"tract_and1_nl",o0", y&z, z" mQ
#define Tk2 {oD mS2,aK2(aJ2 mS2)LNG_ONLY(aJ2 mS2)m91"tract_and2_l",o0", y<1, y&z" mQ
#define Uk2 {oD mA2,aK2(aJ2 mA2)LNG_ONLY(aJ2 mA2)m91"tract_and2_nl",o0", z, y&z" mQ
#define Wk2 {gE qV3,aK2(aJ2 qV3)LNG_ONLY(aJ2 qV3)mM1"tract_min",o0", min(y,2), min(y,5))"},
#define Yk2 {gE qW3,aK2(aJ2 qW3)LNG_ONLY(aJ2 qW3)mM1"tract_mul",o0", y*2, y*" mJ1
#define Sl2 {gE qO3,aK2(aJ2 qO3)LNG_ONLY(aJ2 qO3)mM1"tract_mul1",o0", y*2, y" mQ
#define Tl2 {gE qP3,aK2(aJ2 qP3)LNG_ONLY(aJ2 qP3)mM1"tract_mul2",o0", y, y*2" mQ
#define Ul2 {oD qH3,aK2(aJ2 qH3)LNG_ONLY(aJ2 qH3)m91"tract_or1_l",o0", y|z, y<1" mQ
#define Wl2 {oD mT2,aK2(aJ2 mT2)LNG_ONLY(aJ2 mT2)m91"tract_or1_nl",o0", y|z, z" mQ
#define Yl2 {oD qI3,aK2(aJ2 qI3)LNG_ONLY(aJ2 qI3)m91"tract_or2_l",o0", y<1, y|z" mQ
#define Sm2 {oD mU2,aK2(aJ2 mU2)LNG_ONLY(aJ2 mU2)m91"tract_or2_nl",o0", z, y|z" mQ
#define Tm2 {2,N(-4.0,0.0),wK1 dS1 q7 If_extract_sin,aK2(aJ2 If_extract_sin)qX1 dO1"tract_sin",o0", sin(y), " qX3
#define Um2 {2,h3 If_join_add,aK2(aJ2 If_join_add)qX1"if_join_add",o0 dF" +" oB1
#define Wm2 {1,wX2 N(5.0,0.0),dN1 gH3,aK2(aJ2 gH3)LNG_ONLY(aJ2 gH3)gV1"if_join_add2","x + 10 +" gG1"<4, 3,4" mQ
#define Ym2 {2,h3 If_join_and,aK2(aJ2 If_join_and)qX1"if_join_and",o0 dF" &" oB1
#define Sn2 {2,h3 If_join_max,aK2(aJ2 If_join_max)qX1"if_join_max","max(" o0 dF"," hY3")))"},
#define Tn2 {2,h3 If_join_min,aK2(aJ2 If_join_min)qX1"if_join_min","min(" o0 dF"," hY3")))"},
#define Un2 {2,h3 If_join_mul,aK2(aJ2 If_join_mul)qX1"if_join_mul",o0 dF" *" oB1
#define Wn2 {1,wX2 N(5.0,0.0),dN1 gI3,aK2(aJ2 gI3)LNG_ONLY(aJ2 gI3)gV1"if_join_mul2","x * 10 *" gG1"<4, 3,4" mQ
#define Yn2 {2,h3 If_join_or,aK2(aJ2 If_join_or)qX1"if_join_or",o0 dF" |" hY3"))"},
#define So2 {m9 Ifabs,aK2(aJ2 Ifabs)LNG_ONLY(aJ2 Ifabs)gV1"ifabs","1" qT1"< 0,-x" qJ3"   10" qT1"<=0,-x" qJ3"  100" qT1"> 0,-x" qJ3" 1000" qT1">=0,-x" qJ3"10000" qT1"< 0,x" oJ3 w83" 100000" qT1"<=0,x" oJ3 w83"1000000" qT1"> 0,x" oJ3"10000000" qT1">=0,x,-" oW2
#define To2 {3 w1 Ifabsnot,aK2(aJ2 Ifabsnot)m5"ifabsnot","if(!(sin(x)+1.2), y,z" mQ
#define Uo2 {3 w1 Ifconst,aK2(aJ2 Ifconst)m5"ifconst","if(1, x,y) + if(0,z,y" mQ
#define Wo2 {4,N(0.0,0.0)qN Ififconst,aK2(aJ2 Ififconst)LNG_ONLY(0)"w," aG"ififconst","if(" o0",1,y),z,w) + if(if(w,z,0)," gQ2
#define Yo2 {4,dR1 oK3,aK2(aJ2 oK3)LNG_ONLY(aJ2 oK3)"b,d," qR"ifmerge",o0 g92"y,x,b)" g92"y,x,d)) +  if(b,if(d,y,x)" g92"d,b," oW2
#define Sp2 {4,dR1 dM3,aK2(aJ2 dM3)LNG_ONLY(aJ2 dM3)"a,b," qR"ifmerge2",o0 g92"y,a,b)" g92"b,a,b))"},
#define Tp2 {4,dR1 hM3,aK2(aJ2 hM3)LNG_ONLY(aJ2 hM3)"a,b," qR"ifmerge2b",o0 g92"y,a,b)" g92"b,b,a))"},
#define Up2 {hI Ifnop,aK2(aJ2 Ifnop)LNG_ONLY(aJ2 Ifnop)qR"ifnop",o0",y,y" mQ
#define Wp2 {qZ1 Ifnot,aK2(aJ2 Ifnot)m5"ifnot","if(!x, y,z" mQ
#define Yp2 {hU L_abs,aK2(aJ2 L_abs)LNG_ONLY(aJ2 L_abs)qR"l_abs","(x+2) & abs(x) & " dN3
#define Sq2 {hU dO3,aK2(aJ2 dO3)LNG_ONLY(aJ2 dO3)qR"l_mulabs","(x*abs(y)) & " dN3
#define Tq2 {hU dP3,aK2(aJ2 dP3)LNG_ONLY(aJ2 dP3)qR"l_mulneg","(x*y*-5) & " dN3
#define Uq2 {hU dQ3,aK2(aJ2 dQ3)LNG_ONLY(aJ2 dQ3)qR"l_notnot","(x+2) & !!x & " dN3
#define Wq2 {hI hN3,aK2(aJ2 hN3)LNG_ONLY(aJ2 hN3)qR"le_and_eq",dR3"& " dE1
#define Yq2 {hI hO3,aK2(aJ2 hO3)LNG_ONLY(aJ2 hO3)qR"le_and_ne",dR3"& " dF1
#define Sr2 {hI dS3,aK2(aJ2 dS3)LNG_ONLY(aJ2 dS3)qR"le_or_eq",dR3"| " dE1
#define Tr2 {hI dT3,aK2(aJ2 dT3)LNG_ONLY(aJ2 dT3)qR"le_or_ne",dR3"| " dF1
#define Ur2 {hI hP3,aK2(aJ2 hP3)LNG_ONLY(aJ2 hP3)qR"lt_and_eq" q72 dE1
#define Wr2 {hI hQ3,aK2(aJ2 hQ3)LNG_ONLY(aJ2 hQ3)qR"lt_and_ge" q72 aY},
#define Yr2 {hI hR3,aK2(aJ2 hR3)LNG_ONLY(aJ2 hR3)qR"lt_and_gt" q72"(x > y" mQ
#define Ss2 {hI hS3,aK2(aJ2 hS3)LNG_ONLY(aJ2 hS3)qR"lt_and_le" q72 hV1 mQ
#define Ts2 {hI hT3,aK2(aJ2 hT3)LNG_ONLY(aJ2 hT3)qR"lt_and_ne" q72 dF1
#define Us2 {hI dU3,aK2(aJ2 dU3)LNG_ONLY(aJ2 dU3)qR"lt_or_eq" q82 dE1
#define Ws2 {hI dV3,aK2(aJ2 dV3)LNG_ONLY(aJ2 dV3)qR"lt_or_ge" q82 aY},
#define Ys2 {hI dW3,aK2(aJ2 dW3)LNG_ONLY(aJ2 dW3)qR"lt_or_gt" q82"(x > y" mQ
#define St2 {hI dX3,aK2(aJ2 dX3)LNG_ONLY(aJ2 dX3)qR"lt_or_le" q82 hV1 mQ
#define Tt2 {hI dY3,aK2(aJ2 dY3)LNG_ONLY(aJ2 dY3)qR"lt_or_ne" q82 dF1
#define Ut2 {1,hT N(0.25,0.0),q7 Lthalf,aK2(aJ2 Lthalf)gW"lthalf","x<if(1,0.5,0" mQ
#define Wt2 {oD gM3,aK2(aJ2 gM3)LNG_ONLY(aJ2 gM3)aG"mergemulabs","abs(x)*abs(y)*z"},
#define Yt2 {3,N(0.0,0.0),wK1 dN1 gN3,aK2(aJ2 gN3)LNG_ONLY(aJ2 gN3)aG"mixedminmax","max(z,min(x,max(max(z,y),x)))" hX3"10*min(z,max(x,min(y,x)))" hX3"100*min(max(x,y),min(y,z)) +  1000*max(min(x,y),max(y,z))"},
#define Su2 {2 w1 Muland2,aK2(aJ2 Muland2)qX1"muland2",hZ3},
#define Tu2 {3 w1 Muland2plus,aK2(aJ2 Muland2plus)m5"muland2plus",hZ3" * z"},
#define Uu2 {3 w1 Muland3,aK2(aJ2 Muland3)m5"muland3",hZ3" * !!z"},
#define Wu2 {2 w1 Mulandlt,aK2(aJ2 Mulandlt)qX1"mulandlt",hG2" (y<0" mQ
#define Yu2 {2 gX1 N(1.0,0.0)gX1 q7 Mulimmlog,aK2(aJ2 Mulimmlog)qX1"mulimmlog","log(if(1,5,0)*x*y" mQ
#define Sv2 {2 w1 Mulnor2,aK2(aJ2 Mulnor2)qX1"mulnor2",d03},
#define Tv2 {3 w1 Mulnor2plus,aK2(aJ2 Mulnor2plus)m5"mulnor2plus",d03" * z"},
#define Uv2 {3 w1 Mulnor3,aK2(aJ2 Mulnor3)m5"mulnor3",d03" * !z"},
#define Wv2 {hI Nand2,aK2(aJ2 Nand2)LNG_ONLY(aJ2 Nand2)qR"nand2",hU3},
#define Yv2 {qZ1 hV3,aK2(aJ2 hV3)LNG_ONLY(aJ2 hV3)aG"nand2plus",hU3" | z"},
#define Sw2 {qZ1 Nand3,aK2(aJ2 Nand3)LNG_ONLY(aJ2 Nand3)aG"nand3",hU3" | !z"},
#define Tw2 {m9 Negceil,aK2(aJ2 Negceil)gW"negceil","ceil(x*(" m01"-abs(x)-1))"},
#define Uw2 {m9 Negcos,aK2(aJ2 Negcos)gW"negcos","cos" qG1
#define Ww2 {m9 Negcosh,aK2(aJ2 Negcosh)gW"negcosh","cosh" qG1
#define Yw2 {m9 Negfloor,aK2(aJ2 Negfloor)gW"negfloor","floor(x*(" m01"-abs(x)-1))"},
#define Sx2 {m9 Negsin,aK2(aJ2 Negsin)gW"negsin","sin(x*if(1,-1,0))"},
#define Tx2 {m9 Negsinh,aK2(aJ2 Negsinh)gW"neg" gA2,gA2 qG1
#define Ux2 {1,N(0.0,0.0)qN Neq0,aK2(aJ2 Neq0)LNG_ONLY(aJ2 Neq0)gV1"neq0","(x!=if" d52 wW2 d52")!=x)"},
#define Wx2 {1,N(0.0,0.0)qN Neq1,aK2(aJ2 Neq1)LNG_ONLY(aJ2 Neq1)gV1"neq1","(!x!=if" d42"))"},
#define Yx2 {hI Nor2,aK2(aJ2 Nor2)LNG_ONLY(aJ2 Nor2)qR"nor2",hW3},
#define Sy2 {qZ1 dZ3,aK2(aJ2 dZ3)LNG_ONLY(aJ2 dZ3)aG"nor2plus",hW3" & z"},
#define Ty2 {qZ1 Nor3,aK2(aJ2 Nor3)LNG_ONLY(aJ2 Nor3)aG"nor3",hW3" & !z"},
#define Uy2 {hI Not_eq,aK2(aJ2 Not_eq)LNG_ONLY(aJ2 Not_eq)qR"not_eq",o0" = " mB2
#define Wy2 {hI Not_ge,aK2(aJ2 Not_ge)LNG_ONLY(aJ2 Not_ge)qR"not_ge",o0" >= " mB2
#define Yy2 {hI Not_gt,aK2(aJ2 Not_gt)LNG_ONLY(aJ2 Not_gt)qR"not_gt",o0" > " mB2
#define Sz2 {hI Not_le,aK2(aJ2 Not_le)LNG_ONLY(aJ2 Not_le)qR"not_le",o0" <= " mB2
#define Tz2 {hI Not_lt,aK2(aJ2 Not_lt)LNG_ONLY(aJ2 Not_lt)qR"not_lt",o0" < " mB2
#define Uz2 {hI Not_ne,aK2(aJ2 Not_ne)LNG_ONLY(aJ2 Not_ne)qR"not_ne",o0" != " mB2
#define Wz2 {gE Notnot,aK2(aJ2 Notnot)LNG_ONLY(aJ2 Notnot)qR"notnot","!!x + if(y, 1,0" mQ
#define Yz2 {1 w1 Posnot,aK2(aJ2 Posnot)gW"posnot","!(sin(x) + 1.2" mQ
#define S_2 {1 w1 Posnotnot,aK2(aJ2 Posnotnot)gW"posnotnot","!!(sin(x) + 1.2" mQ
#define T_2 {1 gX1 N(1.0,0.0)gX1 q7 Powimmaddimmlog,aK2(aJ2 Powimmaddimmlog)wE1"immaddimmlog","pow(5, log(x)+1" mQ
#define U_2 {1 gX1 N(2.0,0.0)gX1 q7 Powimmlog,aK2(aJ2 Powimmlog)wE1"immlog","pow(3, log(x)) + pow(5, log(x)*sin(x))"},
#define W_2 {hS Powmulimm_fnen,aK2(aJ2 Powmulimm_fnen)qB gK1"mulimm_fnen",d11"^(-8" mQ
#define Y_2 {dS Powmulimm_fnep,aK2(aJ2 Powmulimm_fnep)qB gK1"mulimm_fnep",d11"^(4" mQ
#define S03 {1,N(-3.0,0.0),N(-1.0,0.0),dS1 q7 Powmulimm_fnfn,aK2(aJ2 Powmulimm_fnfn)wE1"mulimm_fnfn","((-5.1)*x)^(-7.1" mQ
#define T03 {dS Powmulimm_fnfp,aK2(aJ2 Powmulimm_fnfp)qB gK1"mulimm_fnfp",d11"^7.1"},
#define U03 {dS Powmulimm_fpfp,aK2(aJ2 Powmulimm_fpfp)qB gK1"mulimm_fpfp","(5.1*x*y)^7.1"},
#define W03 {1 w1 Sub1cos2,aK2(aJ2 Sub1cos2)gW"sub1cos2","1-cos(x)^2"},
#define Y03 {1 w1 Sub1sin2,aK2(aJ2 Sub1sin2)gW"sub1sin2","1-" a51"^2"},
#define S13 {1,N(-9.42477796076937971538793014983850865259,0.0),N(9.42477796076937971538793014983850865259,0.0),N(0.785398163397448309615660845819875721049292349,0.0),q7 Trig_modulo,aK2(aJ2 Trig_modulo)gW"trig_modulo","cos(x+pi)" gH1"2/3)" gH1"5/2)" gH1"6/2)" gH1 oM3"  sin(x+pi) " hQ1"2/3) " hQ1"5/2) " hQ1"6/2) " hQ1 oM3"  cos(x-pi) " d12"2/3) " d12"5/2) " d12"6/2) " d12 oM3"sin(x-pi" gI1"2/3" gI1"5/2" gI1"6/2" gI1"7/2" mQ
#define T13 {1,N(-3.0,0.0),N(3.0,0.0)gX1 q7 Trunc_from_if,aK2(aJ2 Trunc_from_if)gW"trunc_from_if",o0">0,  " gP3 qE2">=0, " gP3 qE2"<0,  " gJ3 qE2"<=0, " gJ3 wF1">0,  " gJ3 wF1">=0, " gJ3 wF1"<0,  " gP3" 10*" o0"<=0, floor(x),ceil" qV1
#define U13 {1,N(-5.0,0.0),N(5.0,0.0),dN1 oI3,aK2(aJ2 oI3)LNG_ONLY(aJ2 oI3)"x" q8"/xaddnot","!(x+if(1,4,4))"},
#define W13 {1,N(-5.0,0.0),N(5.0,0.0),dN1 h13,aK2(aJ2 h13)LNG_ONLY(aJ2 h13)"x" q8"/xaddnotnot","!!(x+if(1,4,4))"},
#define N(x) (x)
#define P(x) N(x##.0)
namespace
cpp_01unit_operators{using
namespace
FUNCTIONPARSERTYPES;q3
Add_cd(d22
Add_d(d22
Add_i(d22
Addsub_cd
qJ1
Addsub_d
qJ1
Addsub_i
qJ1
And_d(qH
w21>=g32)?fp_abs(y)>=g32):d32
And_i(qH
x
gO
y!=o62:q0
h42
Cmpeq_cd(qH
x==w41
Cmpeq_d(qH
x==w41
Cmpeq_i(qH
x==w41
Cmpge_d
d82
Cmpge_i
d82
Cmpgt_d(qH
x>w41
Cmpgt_i(qH
x>w41
Cmple_d(qH
x<=w41
Cmple_i(qH
x<=w41
Cmplt_d(qH
x<w41
Cmplt_i(qH
x<w41
Cmpne_cd(qH
x!=w41
Cmpne_d(qH
x!=w41
Cmpne_i(qH
x!=w41
Div_d(qH(x-q0(0.25l))/w41
Div_i(qH
x/(y+q0(3l
qQ
Divmul_d
hM
x*y*x*x/z*(x-q0(0.25l
qQ
Divmul_i
hM
x*y*x*x/(z+dJ2*(x+qA1
Inv_d
h32
x;}
q3
Inv_i
h32
x;}
q3
Mod(qD,&z=vars[1];return
fmod(x,z);}
q3
Mod_i(qD,&z=vars[1];return
x%(z+q0(3l
qQ
Mul_cd(qH
x*w41
Mul_d(qH
x*w41
Mul_i(qH
x*(y+qA1
Neg_cd(d62
Neg_d(d62
Neg_i(d62
Not_d(qJ
w21<g32
qQ
Not_i
wI2
x==d32
Notnot_d(qJ
w21>=g32
qQ
Notnot_i
wI2
x!=d32
Or_d(qH
w21<g32)?fp_abs(y)>=g32):q0(1l
qQ
Or_i(qH
x==o62?y!=o62:h92;}
q3
Sub_cd(qH
x-w41
Sub_d(qH
x-w41
Sub_i(qH
x-y
wV2
cpp_02unit_functions{using
namespace
FUNCTIONPARSERTYPES;q3
Abs_cd(qJ
std::abs(mS
Abs_d(qJ
x<o62?-x:x;}
q3
Abs_i(qJ
x<o62?-x:x;}
q3
Acos(qJ
acos(mS
Acos_deg
g42
acos(x
qQ
Acosh(qJ
g01-1.0
qQ
Acosh_deg
g42
g01-1.0)qQ
Arg(qJ
hR
mS
Asin(qJ
asin(mS
Asin_deg
g42
asin(x
qQ
Asinh(qJ
g01+1.0
qQ
Asinh_deg
g42
g01+1.0)qQ
Atan(qJ
atan(mS
Atan2(qH
atan2(x
w13
Atan2_deg(qH
r2d(atan2(x,y
qQ
Atan_deg
g42
atan(x
qQ
Atanh(qJ
log((1.0+x)/(1.0-x))*0.5;}
q3
Cbrt(qJ
x<0.0?-exp(log(-x)/3.0):(x>0.0?exp(log(x)/3.0):0.0);}
q3
Ceil(qJ
ceil(mS
Conj(qJ
fp_conj(mS
Cos(qJ
cos(mS
Cos_deg(qJ
cos(oJ1
Cosh(qJ
cosh(mS
Cosh_deg(qJ
cosh(oJ1
Exp
oR2
mS
Exp2
oR2
x*fp_const_log2<q0>(qQ
Floor(qJ
floor(mS
Hypot(qH
sqrt(x*x+y*y);}
q3
If_d
hM
fp_abs(x)>=g32)?y:z;}
q3
If_i
hM(x!=o62)?y:z;}
q3
Imag(qJ
fp_imag(mS
Int(qJ
fp_floor(x+g32
qQ
Log(qJ
log(mS
Log2(qJ
log(x)*1.4426950408889634073599246810018921374266;}
q3
Log10(qJ
log(x)*0.43429448190325182765112891891660508229;}
q3
Log_cd(qJ
std::log(mS
Max(qH
x>y?x:w41
Min(qH
x<y?x:w41
Polar(qH
fp_polar(x
w13
Pow_neg(qH
pow(-x*0.25
w13
Pow_pos(qH
pow(x
w13
Real(qJ
fp_real(mS
Sin(qJ
sin(mS
Sin_deg(qJ
sin(oJ1
Sinh(qJ
sinh(mS
Sinh_deg(qJ
sinh(oJ1
Sqrt(qJ
sqrt(mS
Sqrt_cd(qJ
std::sqrt(mS
Tan(qJ
tan(mS
Tan_deg(qJ
tan(oJ1
Tanh(qJ
tanh(mS
Tanh_deg(qJ
tanh(oJ1
Trunc(qJ
x<0.0?ceil(x):floor(x)wV2
cpp_03unit_constants{using
namespace
FUNCTIONPARSERTYPES;q3
E_d
oR2
x*0.0+1.0);}
q3
L2_d(qJ
log(x*0.0+2.0);}
q3
L10_d(qJ
log(x*0.0+10.0);}
q3
Pi_d(qJ
atan2(x*0.0,-1.0)wV2
cpp_10optimizer_bytecode{using
namespace
FUNCTIONPARSERTYPES;q3
Abs(qJ(dJ2
hP1
Abscos(qJ
fp_cos(gZ1
Abscosh(qJ
d72
gZ1
Abseq0
mA
d92+q12
o62,gZ1
Absevenconstpow(h72
wD
1506l
qQ
Absmulevenconstpow(qH
fp_pow(fp_abs(x)*y,q0(1506l
qQ
oN3
mA
d92+q12
o62,gZ1
Absneverneg(qJ
fp_acos(mS
Absnot(h52
gZ1
Absnot2(h52
fp_acos(x
qQ
Absnot3(qH
oU2
oU2
mZ1,y)qQ
Absnot4(h52
oU2
fp_acos(x)qQ
g63(h52
fp_notNot((x*x)qQ
oD3(qD;q0
b0[2];return
userDefFuncSub<q0>((b0[0]=(fp_greaterOrEq(fp_abs(x),dU),b0[1]=(fp_greaterOrEq(d92),b0
qQ
oE3(qD;q0
b1[2];return
userDefFuncSub<q0>((b1[0]=(fp_less(fp_abs(x),dU),b1[1]=(fp_less(d92),b1
qQ
Abssqr(qJ
x*x;}
q3
Absyxpow_neg(h72
qP-4.0),1.5);}
q3
Absyxpow_pos(h72
qP
4.0),1.5);}
q3
Acos(qJ
acos(0.7)hP1
Acos_deg
g42
acos(0.7))hP1
Acosh(qJ
m3
1.1-1.0))hP1
Acosh_deg
g42
m3
1.1-1.0)))hP1
Acoshcosh(qJ
d72
fp_acosh(x
qQ
Acoshsinh(qJ
fp_sinh(fp_acosh(x
qQ
Add
wI2
5l
oH
3l)hP1
Add0(qJ
x+o62
hP1
Addexp(m71
x+qA1
Addexp2(qJ
fp_exp2(x+qA1
And(qJ
fp_and(gR1+aT1
5l),o62)+aT1
0l),mO1)+aT1
0l),d32
Asin(qJ
asin(0.7)hP1
Asin_deg
g42
asin(0.7))hP1
Asinh(qJ
m3
1.1+1.0))hP1
Asinh_deg
g42
m3
1.1+1.0)))hP1
Asinhcosh(qJ
d72
fp_asinh(x
qQ
Asinhsinh(qJ
fp_sinh(fp_asinh(x
qQ
Atan(qJ
atan(1.1)hP1
Atan2(qJ
atan2(5.0,4.0)hP1
Atan2_deg
g42
atan2(5.0,4.0))hP1
Atan2tan(qH
qR2
a71
x,y
qQ
Atan_deg
g42
atan(1.1))hP1
Atanh(qJ
log((1.0+0.7)/(1.0-0.7))*0.5+x;}
q3
Cbrt
oR2
dG2/3.0)hP1
Ceil(qJ
ceil(1.1)hP1
Ceilneg(qJ
a62-mS
Cmp_acos(mB
hK))qX
hK))qS
hK))qT
hK))qU
hK))qV
hK
qQ
Cmp_acos_outrange(mB
mW
qX
mW
qS
mW
qT
mW
qU
mW
qV
oN
2l
qQ
oO3(mB(dK2
qX(dK2
qS(dK2
qT(dK2
qU(dK2
qV(q0(dN
qQ
Cmp_asin(mB
hL))qX
hL))qS
hL))qT
hL))qU
hL))qV
hL
qQ
Cmp_asin_outrange(mB
mX
qX
mX
qS
mX
qT
mX
qU
mX
qV
fp_asin(x),q0(2l
qQ
Cmp_atan(mB
oE
gG)qX
oE
gG)qS
oE
gG)qT
oE
gG)qU
oE
gG)qV
oE
mN1
Cmp_exp(mB
oR
qX
oR
qS
oR
qT
oR
qU
oR
qV
qK1
aI2
mN1
Cmp_exp2(mB
oC2
qX
oC2
qS
oC2
qT
oC2
qU
oC2
qV
oF
mN1
Cmp_exp2_neg(mB
mG
qX
mG
qS
mG
qT
mG
qU
mG
qV
fp_exp2(x),-qA1
Cmp_exp_neg(mB
qK1-dU
qX
qK1-dU
qS
qK1-dU
qT
qK1-dU
qU
qK1-dU
qV
qK1-qA1
Cmp_log2_nn(mB
dU1
qX
dU1
qS
dU1
qT
dU1
qU
dU1
qV
gB2
dV1
Cmp_log2_np(mB
gB2
oD2)qX
gB2
oD2)qS
gB2
oD2)qT
gB2
oD2)qU
gB2
oD2)qV
gB2
h9
mN1
Cmp_log2_pn(mB
h9
dA2
h9
dB2
h9
dC2
h9
dD2
h9
dE2
h9
gB
dV1
Cmp_log2_pp(mB
h9
gB
oD2)qX
h9
gB
oD2)qS
h9
gB
oD2)qT
h9
gB
oD2)qU
h9
gB
oD2)qV
h9
gB
h9
mN1
Cmp_log10_nn(mB
dW1
qX
dW1
qS
dW1
qT
dW1
qU
dW1
qV
gU
x),dV1
Cmp_log10_np(mB
gU
x)qM2
qX
gU
x)qM2
qS
gU
x)qM2
qT
gU
x)qM2
qU
gU
x)qM2
qV
gU
x),gU
mN1
Cmp_log10_pn(mB
gU
dA2
gU
dB2
gU
dC2
gU
dD2
gU
dE2
gU
gB
dV1
Cmp_log10_pp(mB
gU
gB
gU
mQ1
qX
gU
gB
gU
mQ1
qS
gU
gB
gU
mQ1
qT
gU
gB
gU
mQ1
qU
gU
gB
gU
mQ1
qV
gU
gB
gU
h92
qQ
Cmp_log_nn(mB
dX1
qX
dX1
qS
dX1
qT
dX1
qU
dX1
qV
hR
x),dV1
Cmp_log_np(mB
hR
x)h82
qX
hR
x)h82
qS
hR
x)h82
qT
hR
x)h82
qU
hR
x)h82
qV
hR
x),hR
mN1
Cmp_log_pn(mB
hR
dA2
hR
dB2
hR
dC2
hR
dD2
hR
dE2
hR
gB
dV1
Cmp_log_pp(mB
hR
gB
hR
gG)qX
hR
gB
hR
gG)qS
hR
gB
hR
gG)qT
hR
gB
hR
gG)qU
hR
gB
hR
gG)qV
hR
gB
hR
mN1
h23(mB(x
d9))qX(x
d9))qS(x
d9))qT(x
d9))qU(x
d9))qV(x
d9
qQ
h33(mB(x
dA))qX(x
dA))qS(x
dA))qT(x
dA))qU(x
dA))qV(x
dA
qQ
oP3(mB(-x),dU
qX(-x),dU
qS(-x),dU
qT(-x),dU
qU(-x),dU
qV(-x),qA1
Cmp_powx_n_n(mB
oG))qX
oG))qS
oG))qT
oG))qU
oG))qV
oG
qQ
Cmp_powx_n_p(mB
dY1)qX
dY1)qS
dY1)qT
dY1)qU
dY1)qV
qK-gD
hD
qQ
Cmp_powx_nn(mB
qK-gD),-dU
qX
qK-gD),-dU
qS
qK-gD),-dU
qT
qK-gD),-dU
qU
qK-gD),-dU
qV
qK-gD),-qA1
Cmp_powx_np(mB
qK
qO2
qX
qK
qO2
qS
qK
qO2
qT
qK
qO2
qU
qK
qO2
qV
qK-gD),qA1
Cmp_powx_p_n
m61
dO))qX
qK
gD
dO))qS
qK
gD
dO))qT
qK
gD
dO))mT1
dO))qV
qK
gD
dO
qQ
Cmp_powx_p_p
m61
h01
qX
qK
gD
h01
qS
qK
gD
h01
qT
qK
gD
h01
mT1
h01
qV
qK
gD/q0(3l)hD
qQ
Cmp_powx_pn
m61),-dU
qX
qK
gD),-dU
qS
qK
gD),-dU
qT
qK
gD),-dU
mT1),-dU
qV
qK
gD),-qA1
Cmp_powx_pp
m61),dU
qX
qK
gD),dU
qS
qK
gD),dU
qT
qK
gD),dU
mT1),dU
qV
qK
gD),qA1
Cmp_powy_n_n(mB
qP2
qX
qP2
qS
qP2
qT
qP2
qU
qP2
qV
qP-hZ
qQ
Cmp_powy_n_p(mB
qP-d0
qX
qP-d0
qS
qP-d0
qT
qP-d0
qU
qP-d0
dF2
qP
q0(6.1l)qQ
Cmp_powy_nn(mB
qP-oE2
qX
qP-oE2
qS
qP-oE2
qT
qP-oE2
qU
qP-oE2
dF2-qA1
Cmp_powy_np(mB
qP-oF2
qX
qP-oF2
qS
qP-oF2
qT
qP-oF2
qU
qP-oF2
dF2
qA1
Cmp_powy_p_n(mB
qP
hZ))qX
qP
hZ))qS
qP
hZ))qT
qP
hZ))qU
qP
hZ))qV
qP
hZ
qQ
Cmp_powy_p_p(mB
qP
d0
qX
qP
d0
qS
qP
d0
qT
qP
d0
qU
qP
d0
qV
qP
g2
qP
q0(6.1l)qQ
Cmp_powy_pn(mB
qP
oE2
qX
qP
oE2
qS
qP
oE2
qT
qP
oE2
qU
qP
oE2
qV
qP
g2-qA1
Cmp_powy_pp(mB
qP
oF2
qX
qP
oF2
qS
qP
oF2
qT
qP
oF2
qU
qP
oF2
qV
qP
g2
qA1
Cmp_sinh(mB
oG2
qX
oG2
qS
oG2
qT
oG2
qU
oG2
qV
oJ
mN1
oQ3(mB(mY
qX(mY
qS(mY
qT(mY
qU(mY
qV(x*x),mU1
qQ
gQ3(mB(x*x),-mU1))qX(x*x),-mU1))qS(x*x),-mU1))qT(x*x),-mU1))+-mU1)*fp_greaterOrEq((x*x),-mU1))qV(x*x),-mU1
qQ
Cmp_tanh(mB
hO))qX
hO))qS
hO))qT
hO))qU
hO))qV
hO
qQ
Cmp_tanh_outrange(mB
q11
qX
q11
qS
q11
qT
q11
qU
q11
qV
fp_tanh(x),q0(2l
qQ
Cmpeq
mA
gR1+q12
q0(4l),qA1
Cmpge(qJ
qC1
3l),mO1)+x+qC1
8l),qA1
Cmpgt(wR1
q0(3l),mO1)+x
g82
q0(8l),qA1
Cmple(qJ
qC1
5l),dJ2+x+qC1
4l),q0(8l
qQ
Cmplt(wR1
gR1;}
q3
Cmpne(q22
gR1+fp_nequal(q0(4l),qA1
Cos(qJ
cos(1.1)hP1
Cos_deg(qJ
cos(d2r(1.1))hP1
Cosh(qJ
cosh(1.1)hP1
Cosh_deg(qJ
cosh(d2r(1.1))hP1
Deg(qH
r2d(y)+r2d(x)+r2d(y)*q0(4l);}
q3
Degxmul
g42
fp_acos(x))*wP2;}
q3
Div(qJ(mO1/dU
hP1
Div1(qJ
x/h92
hP1
Divxx(qJ
x+x/x
hP1
gW3(qJ
x*q0(14l);}
q3
Dupaddmulh(qJ
x;}
q3
Dupaddmulmul7(qH
y*x*q0(14l);}
q3
Dupaddmulmulh(qH
y*x;}
q3
hD3(qD;q0
b2[2];return
userDefFuncSub<q0>((b2[0]=(fp_min(x,x)),b2[1]=(fp_max(x,x)),b2
qQ
gX3(qD;q0
b3[2];return
userDefFuncSub<q0>((b3[0]=(x
aF2
x)),b3[1]=(x+fp_max(x,x)),b3
qQ
gY3(qD,&y=vars[1];q0
b4[2];return
userDefFuncSub<q0>((b4[0]=(fp_min(y,x)),b4[1]=(fp_max(y,x)),b4
qQ
gZ3(qJ
x
wM2
Dupxpowmul(qJ
qP
qA1
Eq0
mA
x,o62)+q12
o62,mS
Eq1
mA
oU2
x),q0(1l
qQ
Exp
oR2
1.1)hP1
Exp2
oR2
1.1*0.693147180559945309417232121458176568075500134)hP1
Exp2div(qH
x/fp_exp2(y);}
q3
Exp2log2(qJ
h9
fp_exp2(x
qQ
Exp2xpow(h72
fp_exp2(x),1506.0);}
q3
Expdiv(qH
x/aI2
y);}
q3
Explog(qJ
hR
aI2
x
qQ
Explog2(qJ
x/fp_const_log2<q0>();}
q3
Explog10(qJ
x/fp_const_log10<q0>();}
q3
Expxpow(h72
qK1
1506.0);}
q3
Floor(qJ
floor(1.1)hP1
Floorneg(qJ
fp_floor(-mS
oR3(mC
wD
o92
mR1
x))qS
wD
oA2),gZ1
Ge0_neg(mC
wE
o92)w81
x))qS
wE
oA2)w81
x
qQ
Ge0_pos(mC
oN
o92
qD1
x))qS
oN
oA2
qD1
x
qQ
oS3(mC
wD
1l
dL
1l
mR1
x))qS
wD
1l)oH
dG
1l),gZ1
Ge1_neg(mC
wE
1l
dL
1l)w81
x))qS
wE
1l)oH
dG
1l)w81
x
qQ
Ge1_pos(mC
oN
1l
dL
1l
qD1
x))qS
oN
1l)oH
dG
1l
qD1
x
qQ
Gehalf(qJ
d1,g32
qQ
oT3
oB2
wD
oK1
mR1
wF
wD
oL1),gZ1
Gt0_neg
oB2
wE
oK1)w81
wF
wE
oL1)w81
x
qQ
Gt0_pos
oB2
oN
oK1
qD1
wF
oN
oL1
qD1
x
qQ
oU3
oB2
wD
1l))qX
q0(1l
mR1
wF
wD
1l))qT
h92,gZ1
Gt1_neg
oB2
wE
1l))qX
h92
w81
wF
wE
1l))qT
h92
w81
x
qQ
Gt1_pos
oB2
oN
1l))qX
q0(1l
qD1
wF
oN
1l))qT
q0(1l
qD1
x
qQ
Gtminushalf(qJ
oM,-g32
qQ
Hypot(qJ
sqrt(5.0*5.0+4.0*4.0)hP1
Immsub(qJ
x-mO1;}
q3
Int(qJ
x+(((((fp_int(q0(1.1l
qB1
1.6l)qB1
1.5l)qB1-1.1l)qB1-1.6l)qB1-1.5l)qQ
Intceil(qJ
fp_ceil
m41
Intfloor(qJ
fp_floor
m41
Intint(qJ
fp_int
m41
Inttrunc(qJ
fp_trunc
m41
Invdiv(qH
y/wL1/mS
Invinv
h32
wL1/mS
Invmul(qH
y*wL1/mS
Leminushalf(qJ
dY,-g32
qQ
Log(qJ
dG2
hP1
Log2(qJ
dG2*1.4426950408889634073599246810018921374266+x;}
q3
Log2exp1(m71
h9
x
qQ
Log2exp2(qJ
fp_exp2(h9
fp_acos(x)qQ
Log10(qJ
dG2*0.43429448190325182765112891891660508229+x;}
q3
Logexp1(m71
hR
x
qQ
Logexp2(m71
hR
fp_acos(x)qQ
Logmul(qJ
hR
aW
Logmul2(qJ
h9
aW
Logmul10(qJ
gU
aW
Lt0(wR1
fp_abs(x),x-x)-aO,x-mS
Lthalf(qJ
aO,g32
qQ
Max(qJ
mO1
hP1
Min
wI2
4l)hP1
Mod(qJ
fp_mod(mO1,dU
hP1
Mul(qJ(mO1*dU
hP1
Mul1(qJ
x*h92
hP1
Mul1b(qJ((x*q0(0.2l))mU))hP1
Mul2(qJ
x
hP1
Mul4(qH
y*(x*gG*wP2+(y*gG*wP2;}
q3
Mul_zero(qH(x*y+h92)+(fp_sin(x)aE2
y))*hR
x)*y*x*q0
h42
Mulminus1(qJ
x*-1.0;}
q3
Mulneg(qJ-(x
mU
qQ
o43(qJ
x/q0(4l)hP1
Neg(qJ((-((5.0))))hP1
Negabs(qJ
fp_abs(-mS
Negadd(qH
x+(-y);}
q3
Negceil(qJ-a62
mS
Negcos(qJ
fp_cos(-mS
Negcosh(qJ
d72-mS
Negdiv(qJ(-x)/mO1;}
q3
Negfloor(qJ-fp_floor(mS
Negmul(qJ(-x)wM2
Negneg(qJ-(-(-(-(-(-(x))))qQ
Negnot(h52-mS
Negsin
h62-mS
Negsinh(qJ
fp_sinh(-mS
Negsqr(qJ
x*x;}
q3
Negsub(qH
x-(-y);}
q3
Negtan(qJ
qR2-mS
Negtanh(qJ
fp_tanh(-mS
Neq0(qJ(w9,o62))+(fp_nequal(o62,x
qQ
Neq1(q22
oU2
x),q0(1l
qQ
Not(h52
dJ2
hP1
Not_eq(qH
x!=w41
Not_ge(qH
x<w41
Not_gt(qH
x<=w41
Not_le(qH
x>w41
Not_lt
d82
Not_ne(qH
x==w41
Notnot(qJ
fp_notNot(mS
hE3(h52
mS
h03(h52
mS
Or(qJ
fp_or(gR1
aU1
5l),o62)aU1
0l),mO1)aU1
0l),d32
Pow_neg(qJ
pow(-0.25,4.0)hP1
Pow_pos(qJ
pow(1.1,7.1)hP1
Powdiv(qH
x/qP
y);}
q3
Powhalf(qJ
qP
g32
qQ
Powinv(qH
h92/qP
y);}
q3
Powminushalf(qJ
qP-g32
qQ
Powminusone(qJ
qP-q0(1.0l
qQ
Powminusthird(qJ
qP(q0(-1.0l)/q0(3.0l)qQ
Powthird(qJ
qP(q0(1.0l)/q0(3.0l)qQ
Powxpow(h72
qP
1.7),1506.0);}
q3
Rad(qH
d2r(y)+d2r(x)+d2r(x)*q0(4l);}
q3
Radxmul(qJ
fp_cos(d2r(x+x+x+x
qQ
Rsqrt(qJ
1.0/g72
mS
Sin(qJ
sin(1.1)hP1
Sin_deg(qJ
sin(d2r(1.1))hP1
Sincos_cci(qJ
mH
oH
1l)/mH);}
q3
Sincos_cic
h32
mH)+mH);}
q3
Sincos_sc
h62
x)+mH);}
q3
Sincos_sci
h62
qQ2
mH);}
q3
Sincos_sis
h32
fp_sin(x)aE2
mS
Sincos_ssi
h62
qQ2
fp_sin(mS
Sincos_tan(qJ
qR2
mS
Sincos_tit
h32
qR2
x)+qR2
mS
Sincos_tti(qJ
qR2
qQ2
qR2
mS
Sinh(qJ
sinh(1.1)hP1
Sinh_deg(qJ
sinh(d2r(1.1))hP1
oF3(qJ(-x)*x;}
q3
oG3(qJ
x*(-mS
Sqr_xx(qJ
x*x;}
q3
d73(qH
y*-x*x;}
q3
d83(qH
y*x*-x;}
q3
oH3(qH
y*x*x;}
q3
Sqreq0
mA
x*x,o62)+q12
o62,x*mS
Sqrlog(qJ
hR
x*mS
Sqrlog2(qJ
h9
x*mS
Sqrlog10(qJ
gU
x*mS
oV3
mA
x*x,o62)+q12
o62,x*mS
Sqrsqrt(qJ
g72
x*mS
Sqrt(qJ
sqrt(1.1)hP1
Sqrtsqr1(h72
g72
x),q0(2l
qQ
Sqrtsqr2(h72
g72
fp_acos(x)),q0(2l
qQ
Sqrxpow(qJ
h21
x,2402.0);}
q3
Sqrxpow_nonint(qJ
h21
x,3.5);}
q3
Sub(qJ
mO1-q0(3l)hP1
Sub0(qJ
x-o62
hP1
Subxx(qJ
x+(x-x)+x+wL1-x+mS
Tan(qJ
tan(1.1)hP1
Tan_deg(qJ
tan(d2r(1.1))hP1
Tanh(qJ
tanh(1.1)hP1
Tanh_deg(qJ
tanh(d2r(1.1))hP1
Trunc(qJ
1.0+x;}
q3
oI3(h52
x+qA1
h13(qJ
h11+qA1
Xmulrad(qJ
fp_cos(d2r(g12
x
qQ
Xmulsinhneg(qJ-fp_sinh(x
mU
qQ
Xmulsinneg(qJ-fp_sin(x
mU
qQ
Xmultanhneg(qJ-fp_tanh(x
mU
qQ
Xmultanneg(qJ-qR2
x
mU
qQ
Xsqryfsqrhypot(qJ
fp_hypot(hR
x),h9
x
qQ
Xsqrysqrhypot(qH
fp_hypot(hR
x)w13
Xxdup(qJ
x-x;}
q3
Xxfdup(qJ
x-x;}
q3
d93(qH
y*fp_abs(x)*fp_abs(mS
Ypowxpow(h72
qP
38.5),5.0)wV2
cpp_11optimizer_constaddmul{using
namespace
FUNCTIONPARSERTYPES;q3
t1
g7
wL1/a)wM2
t2
g7
mO1*a;}
q3
t3
g7
mO1/a;}
q3
t4(hE(a
mU))*b;}
q3
t5(hE(a
mU))/b;}
q3
t6(hE
wL1/a)*b;}
q3
t7(hE
wL1/a)/b;}
q3
t8(hE
oM1)*(mJ
mU
qQ
t9(hE
oM1)/(mJ
mU
qQ
t10(hE
mJ*(mO1/a);}
q3
t11(hE
mJ/(q0(50l)/a);}
q3
t12
g7(-a
gS1
t13(hE
mO1+(a*b);}
q3
t14(hE
mO1-(a*b);}
q3
t15(hE(a+mO1)+mJ;}
q3
t16(hE(a+mO1)-mJ;}
q3
t17(hE(-a)+mJ;}
q3
t18(hE(-a)-mJ;}
q3
t19(hE
b+(oM1
oH
5l
qQ
t20(hE
b-(oM1
oH
5l
qQ
t21(hE
mJ+(mO1-a);}
q3
t22(hE
mJ-(mO1-a);}
q3
t23
g22*b)/a;}
q3
t24
g22
mU))/a;}
q3
t25
g22
mU))*a;}
q3
t26(hE(oM1)/b)/a;}
q3
t27(hE(oM1)/b)*a;}
q3
t28(hE((-a)/b)wM2
t29(hE(mO1/b)*a;}
q3
t30(w0
b=vars[0];return(mS1/b)wM2
t31(hE
b*(mS1/-a);}
q3
t32(hE(mO1-b)-a;}
q3
t33(hE(mO1-b)+a;}
q3
t34(hE((a+mS1)-b
gS1
t35(hE((-a)-b
gS1
t36
g7(mS1-oM1)gS1
t37(hE((mS1-b)+a
gS1
t38(hE
fp_less((mO1*b+oM1)),o62)*h92
g82(mJ),o62)*wP2;}
q3
t39
g7(a+mS1)wM2
t40(hE(b+(a*mS1))wM2
t41(hE(b-(a*mS1))wM2
t42
g7(a+mS1
gS1
t43
g7(a*mS1)mU)wV2
cpp_20optimizer_optimizations{using
namespace
FUNCTIONPARSERTYPES;q3
Abscos(qJ
fp_cos(fp_abs(x))+fp_abs(mS
Abscosh(qJ
d72
fp_abs(x))+fp_abs(mS
Abseq0
mA
d92+q12
o62,gZ1
oN3
mA
d92+q12
o62,gZ1
oD3(qD;q0
b5[2];return
userDefFuncSub<q0>((b5[0]=(fp_greaterOrEq(fp_abs(x),dU),b5[1]=(fp_greaterOrEq(d92),b5
qQ
oE3(qD;q0
b6[2];return
userDefFuncSub<q0>((b6[0]=(fp_less(fp_abs(x),dU),b6[1]=(fp_less(d92),b6
qQ
Acoscos(qJ
fp_cos
w73
x
qQ
Acoshsinh(qJ
fp_sinh(fp_acosh(x
qQ
gL3(qH
mO1*(q0(4l)+x+y);}
q3
Addlog(qH
hR
x)+hR
y);}
q3
qS3(qH
mO1*(q0(4l)*y+mS
g73(qH-mO1+(mO1*x*y);}
q3
g83(qH-mO1*y+(mO1*mS
Addsin2cos2(h72
fp_sin(x),gG+fp_pow(mH),q0(2l
qQ
Asinhcosh(qJ
d72
fp_asinh(x
qQ
Asinsin
h62
fp_asin(x
qQ
qY3
w23
d8
qQ
mV2
mA
mK
qQ
mW2
w23+hB
g93
w33
mD
mL
mX2
w33
mD
wN1
mD2
w23
mP1
mE2
w23
gC2
aV2
w23*-hB
aW2
w23*hB
Cmpeq_pow_imm_negneg
mA
d5
qQ
Cmpeq_pow_imm_negpos
mA
oK
Cmpeq_pow_imm_posneg
mA
x
aP
qQ
Cmpeq_pow_imm_pospos
mA
x
g11
Cmpeq_pow_imm_pospos_base
mA
q0(dH
Cmpeq_powpow_imm_base(qH
q12
dP
qZ3(qH
d1
d8
qQ
mZ2(mC
mK
qQ
q03(qH
d1+hB
gA3
w33
d1
mL
q13
w33
d1
wN1
mF2(qH
d1
mP1
mG2(qH
d1
gC2
aX2(qH
d1*-hB
aY2(qH
d1*hB
Cmpge_pow_imm_negneg(mC
d5
qQ
Cmpge_pow_imm_negpos(mC
oK
Cmpge_pow_imm_posneg(qJ
d1
aP
qQ
Cmpge_pow_imm_pospos(qJ
d1
g11
Cmpge_pow_imm_pospos_base(mC
q0(dH
Cmpge_powpow_imm_base(qH
fp_greaterOrEq(dP
g03(qH
oM
d8
qQ
q23
oB2
mK
qQ
q33(qH
oM+hB
gB3
w33
oM
mL
q43
w33
oM
wN1
mH2(qH
oM
mP1
mI2(qH
oM
gC2
aZ2(qH
oM*-hB
m02(qH
oM*hB
Cmpgt_pow_imm_negneg
oB2
d5
qQ
Cmpgt_pow_imm_negpos
oB2
oK
Cmpgt_pow_imm_posneg(qJ
oM
aP
qQ
Cmpgt_pow_imm_pospos(qJ
oM
g11
Cmpgt_pow_imm_pospos_base
oB2
q0(dH
Cmpgt_powpow_imm_base(qH
qL1
dP
g13(qH
dY
d8
qQ
q53(qJ
hR1
mK
qQ
q63(qH
dY+hB
gC3
w33
dY
mL
q73
w33
dY
wN1
mJ2(qH
dY
mP1
mK2(qH
dY
gC2
m12(qH
dY*-hB
m22(qH
dY*hB
Cmple_pow_imm_negneg(qJ
hR1
d5
qQ
Cmple_pow_imm_negpos(qJ
hR1
oK
Cmple_pow_imm_posneg(qJ
dY
aP
qQ
Cmple_pow_imm_pospos(qJ
dY
g11
Cmple_pow_imm_pospos_base(qJ
qC1
dH
Cmple_powpow_imm_base(qH
hR1
dP
g23(qH
aO
d8
qQ
q83(wR1
mK
qQ
q93(qH
aO+hB
gD3
w33
aO
mL
qA3
w33
aO
wN1
mL2(qH
aO
mP1
mM2(qH
aO
gC2
m32(qH
aO*-hB
m42(qH
aO*hB
Cmplt_pow_imm_negneg(wR1
d5
qQ
Cmplt_pow_imm_negpos(wR1
oK
Cmplt_pow_imm_posneg(qJ
aO
aP
qQ
Cmplt_pow_imm_pospos(qJ
aO
g11
Cmplt_pow_imm_pospos_base(wR1
q0(dH
Cmplt_powpow_imm_base(qH
fp_less(dP
g33(qH
w9
d8
qQ
qB3(q22
mK
qQ
qC3(qH
w9+hB
gE3
w33
w9
mL
qD3
w33
w9
wN1
mN2(qH
w9
mP1
mO2(qH
w9
gC2
m52(qH
w9*-hB
m62(qH
w9*hB
Cmpne_pow_imm_negneg(q22
d5
qQ
Cmpne_pow_imm_negpos(q22
oK
Cmpne_pow_imm_posneg(qJ
w9
aP
qQ
Cmpne_pow_imm_pospos(qJ
w9
g11
Cmpne_pow_imm_pospos_base(q22
q0(dH
Cmpne_powpow_imm_base(qH
fp_nequal(dP
g43
oT2(h8
x
d8
mV1
d8
mW1
d8
mX1
d8
mY1
d8
oH2
d8
qQ
qE3(a61
mK)oH
gN
mK)oH
gS
mK)oH
gI
mK)oH
gX
mK))gT
mK
qQ
qF3
oT2(h8
x+q0(wN2+q0
oM2+q0
oN2+q0
oO2+q0(o81+hB
gF3
oT2(0x0001l)*((aO
wO1
0x0002l)*((dY
wO1
0x0004l)*((oM
wO1
0x0008l)*((d1
wO1
0x0010l)*((w9
wO1
0x0020l)*((mD
mL
qG3
oT2(0x0001l)*((aO
wP1
0x0002l)*((dY
wP1
0x0004l)*((oM
wP1
0x0008l)*((d1
wP1
0x0010l)*((w9
wP1
0x0020l)*((mD
wN1
mP2(o71-d7
mV1*-d7
mW1*-d7
mX1*-d7
mY1*-d7
oH2
mP1
mQ2(o71
d7
mV1*d7
mW1*d7
mX1*d7
mY1*d7
oH2
gC2
m72(o71-q0(wN2*-q0
oM2*-q0
oN2*-q0
oO2*-q0(o81*-hB
m82(o71
q0(wN2*q0
oM2*q0
oN2*q0
oO2*q0(o81*hB
Cmpzz_pow_imm_negneg(a61
d5)oH
gN
d5)oH
gS
d5)oH
gI
d5)oH
gX
d5))gT
d5
qQ
Cmpzz_pow_imm_negpos(a61
wX
oH
gN
wX
oH
gS
wX
oH
gI
wX
oH
gX
wX)gT
oK
Cmpzz_pow_imm_posneg(a61
x
aP
mV1
aP
mW1
aP
mX1
aP
mY1
aP
oH2
aP
qQ
Cmpzz_pow_imm_pospos(a61
x
hS1
gN
x
hS1
gS
x
hS1
gI
x
hS1
gX
x*x,q0(25l
oH2
g11
Cmpzz_pow_imm_pospos_base(a61
q0(oS
oH
gN
q0(oS
oH
gS
q0(oS
oH
gI
q0(oS
oH
gX
q0(oS)gT
q0(dH
Cmpzz_powpow_imm_base
oT2(h8
wG
oH
gN
wG
oH
gS
wG
oH
gI
wG
oH
gX
wG)gT
dP
Eq0
mA
x,o62)+q12
o62,mS
Eq1
mA
oU2
x),q0(1l
qQ
Expexp_a(qH
aI2
x*wP2+y*q0(3l
qQ
Expexp_b
hM
g02*aI2
y+z);}
q3
Expexp_c
hM
aI2
x+y*z);}
q3
oR3(mC
wD
o92
mR1
x))qS
wD
oA2),gZ1
oS3(mC
wD
1l
dL
1l
mR1
x))qS
wD
1l)oH
dG
1l),gZ1
hF3(qH
x==w41
hG3(qH
x==w41
hH3(qH
x>w41
dF3
d82
dG3(qH
aV1
dH3(qH
aV1
Gehalf(qJ
d1,g32
qQ
oT3
oB2
wD
oK1
mR1
wF
wD
oL1),gZ1
oU3
oB2
wD
1l))qX
q0(1l
mR1
wF
wD
1l))qT
h92,gZ1
hI3
a12
hJ3(qH
x>w41
hK3
a12
hL3(qH
x>w41
dI3
d82
dJ3
d82
dK3(qH
aV1
dL3(qH
x!=w41
If10(qJ
h11
oH
10l)*oU2
x
oH
100l)*oM,o62
oH
1000l)*dY,d32
qT3(qH
fp_abs(dZ(x+gG:(y+mO1
qQ
qU3(qH
y+(dZ
wO2
q0(5l
qQ
qM3(qH
dZ(y+gG:w41
qN3(qH
dZ
y:(y+q0(2l
qQ
mR2(qY
dM1:qE1
qQ
m92(qY
dM1:z;}
q3
mS2(qY
qE1)):dM1;}
q3
mA2(qY
z:dM1;}
q3
If_extract_div(qH
y/(dZ
x:q0(2l
qQ
qV3(qH
fp_min(y,(dZ
wO2
mO1
qQ
qW3(qH
y*(dZ
wO2
q0(5l
qQ
qO3(qH
dZ(y*gG:w41
qP3(qH
dZ
y:(y*q0(2l
qQ
qH3(qY
oP1:qE1
qQ
mT2(qY
oP1:z;}
q3
qI3(qY
qE1)):oP1;}
q3
mU2(qY
z:oP1;}
q3
If_extract_sin(qH
fp_sin(dZ
y:mS
If_join_add
gJ2(oY1
qN1(fp_cos(y+h92)aE2
y+h92
qQ
gH3(qJ
x+(hT1
q0(13l):q0(14l
qQ
If_join_and
gJ2
fp_and
gK2
fp_and
gL2
If_join_max
gJ2
fp_max
gK2
fp_max
gL2
If_join_min
gJ2
fp_min
gK2
fp_min
gL2
If_join_mul
gJ2(fp_sin(y)*qN1(fp_cos(y+h92)w43(y+h92
qQ
gI3(qJ
x*(hT1
q0(30l):q0(40l
qQ
If_join_or
gJ2
fp_or
gK2
fp_or
gL2
Ifabs
wI2
1l
gD1
aO
m4
10l
gD1
dY
m4
100l
gD1
oM
m4
1000l
gD1
d1
m4
10000l
gD1
aO
qO1)oH
100000l
gD1
dY
qO1)oH
1000000l
gD1
oM
qO1)oH
10000000l
gD1
d1
qO1
qQ
Ifabsnot
hM
aR
fp_sin(x
oH
1.2l))gO
z:w41
Ifconst
hM
x+y+z*q0
h42
Ififconst(w0
w
oQ1
x
oR1
y=vars[2],&z=vars[3];return(aR
dZ
h92:y)gO
z:w)+(aR
aR
w)gO
z:o62)gO
x:y);}
q3
oK3(w0
b
oQ1
d
oR1
hG
x
oY3
y)gO
x:d))+(aR
b)gO(aR
d)gO
y:x):(aR
d)gO
b:x
qQ
dM3(w0
a
oQ1
b
oR1
hG
a
oY3
b)gO
a:b
qQ
hM3(w0
a
oQ1
b
oR1
hG
a
oY3
b)gO
b:a
qQ
Ifnop(qH
x*o62+w41
Ifnot(qY
z:w41
L_abs(qH
mZ1+wP2,fp_and(fp_abs(x),y+mN1
dO3(qH
mZ1*y*fp_abs(y),y+q0(2l
qQ
dP3(qH
mZ1*y*-mO1,y+q0(2l
qQ
dQ3(qH
mZ1+wP2,fp_and(h11),y+mN1
hN3(qH
x==w41
hO3(qH
x<w41
dS3(qH
x<=w41
dT3(qH
aV1
hP3
a12
hQ3
a12
hR3
a12
hS3(qH
x<w41
hT3(qH
x<w41
dU3(qH
x<=w41
dV3(qH
aV1
dW3(qH
x!=w41
dX3(qH
x<=w41
dY3(qH
x!=w41
Lthalf(qJ
aO,g32
qQ
gM3
hM
fp_abs(x)*fp_abs(y)*z;}
q3
gN3
hM
fp_max(z,fp_min
wT1
fp_max(z,y),x))oH
10l)*fp_min(z,fp_max(x,fp_min(y,x))oH
100l)*fp_min(fp_max(x,y),fp_min(y,z)oH
1000l)*fp_max(fp_min(x,y),fp_max(y,z
qQ
Muland2(qH
a6;}
q3
Muland2plus
hM
a6*z;}
q3
Muland3
hM
a6*fp_notNot(z);}
q3
Mulandlt(qH
h11)*q0(fp_less(y,o62
qQ
Mulimmlog(qH
hR
mO1*x*y);}
q3
Mulnor2(qH
q21;}
q3
Mulnor2plus
hM
q21*z;}
q3
Mulnor3
hM
q21*dH2);}
q3
Nand2(qH
aE
qQ
hV3
hM
fp_or(aE)),z);}
q3
Nand3
hM
fp_or(aE)),dH2
qQ
Negceil(qJ
a62-mS
Negcos(qJ
fp_cos(-mS
Negcosh(qJ
d72-mS
Negfloor(qJ
fp_floor(-mS
Negsin
h62-mS
Negsinh(qJ
fp_sinh(-mS
Neq0(qJ(w9,o62))+(fp_nequal(o62,x
qQ
Neq1(q22
oU2
x),q0(1l
qQ
Nor2(qH
a7
qQ
dZ3
hM
fp_and(a7)),z);}
q3
Nor3
hM
fp_and(a7)),dH2
qQ
Not_eq(qH
x!=w41
Not_ge(qH
x<w41
Not_gt(qH
x<=w41
Not_le(qH
x>w41
Not_lt
d82
Not_ne(qH
x==w41
Notnot(qH
aR
x)+aR
y);}
q3
Posnot(h52
fp_sin(x
oH
1.2l
qQ
Posnotnot(qJ
fp_notNot(fp_sin(x
oH
1.2l
qQ
Powimmaddimmlog(qJ
qK
5l),hR
x
oH
1l
qQ
Powimmlog(qJ
qK
3l),hR
x))+qK
5l),hR
x)w43(x
qQ
Powmulimm_fnen(dI2(q0(-8l)qQ
Powmulimm_fnep(dI2(q0(4l)qQ
Powmulimm_fnfn(qJ
a0,(q0(-7.1l)qQ
Powmulimm_fnfp(dI2
q0(7.1l
qQ
Powmulimm_fpfp(qH
qK
5.1l)*x*y,q0(7.1l
qQ
Sub1cos2(qJ
h92-fp_pow(mH),q0(2l
qQ
Sub1sin2(qJ
h92-fp_pow(wE
2l
qQ
Trig_modulo(qJ
mH+gF)+mH+gF*q0
wQ1
mH+gF
mU)/gG+mH+gF*q0(6l)/gG+mH+gF*q0(7l
gT1+gF)aE2
x+gF*q0
wQ1
fp_sin(x+gF
mU
gT1+gF*q0(6l
gT1+gF*q0(7l
aW1)+mH-gF*q0
wQ1
mH-gF
mU
aW1*q0(6l
aW1*q0(7l
gT1-gF)aE2
x-gF*q0
wQ1
fp_sin(x-gF
mU
gT1-gF*q0(6l
gT1-gF*mS1/q0(2l
qQ
Trunc_from_if(qJ
fp_trunc(x)*q0(4l
oH
40l)*(x>o62?a62
x):fp_floor(x
qQ
oI3(h52
x+qA1
h13(qJ
h11+dU
wV2
cpp_50regressions{using
namespace
FUNCTIONPARSERTYPES;q3
t1(qJ
x+aY1
0l),aX1-2l),o62
qQ
t2(qJ
fp_min(x,fp_min
wL1,x
qQ
t3(qD;q0
b7[2];return
userDefFuncSub<q0>((b7[0]=(fp_and
o82),h11))),b7[1]=(fp_or
o82),h11))),b7
qQ
t4(qD,&y=vars[1];q0
b9[2];return
userDefFuncSub<q0>((b9[0]=o82-y)),b9[1]=(h11-y)),b9
qQ
t5(qD;q0
b11[2];return
userDefFuncSub<q0>((b11[0]=(fp_sin(qQ2
fp_sin(x)),b11[1]=(mH)),b11
qQ
t6(qD;q0
b13[2];return
userDefFuncSub<q0>((b13[0]=o82+dU),b13[1]=(h11+dJ2),b13
qQ
t7(qJ
x-x;}
q3
t8(qH
a71-x,-y
oH
10l)*a71-x,y
oH
20l)*a71
x,-y
oH
30l)*a71
x
w13
t9a(qJ
x*q0
h42
t9b(hE(a-b)*q0
h42
t9c(hE(a-b)*q0
h42
t9d(hE
a*b*q0
h42
t36(qJ-(x<o62?x:-x)+-(x<mO1?wO2
q0(3l
qQ
t42(qH
g72
x*x
oH
1.5l)*(fp_pow(y*y,q0(0.25l)))+fp_hypot(x
w13
t51(qJ
hR-mS
t57(qJ
d72
fp_asinh(x
qQ
t59(qH
d72
x*x)+fp_tanh(y*y);}
q3
t60(qD,&y=vars[1];q0
b14[1];q0
b15[2];return
fp_or(fp_or(g41
b14[0]=(x),b14)),userDefFuncSub<q0>((b15[0]=(x),b15[1]=(y),b15))),userDefFuncValue<q0>((0)))wV2
cpp_99misc{using
namespace
FUNCTIONPARSERTYPES;q3
t1(qJ
x*q0(4l)/wP2+wL1+(q0(2l
oH
3l)))+x*x+x+(q0(1.0l
oH
2.0l
oH
3.0l)*q0(4.0l
oH
5.0l)*q0(6.0l)*q0(7.0l)-q0(8.0l)*q0(9.0l
qQ
t2
wI2
2l)*x
aE2
x)/q0(.5l
oH
2l)-fp_sin(x)w43(mS
t3
hM
fp_and(mD,y),q12
y,x)oH
1.0l
oH
2.0l)-q0(3.1l)*q0(4e2l)/q0(.5l)+x*x+y*y+z*z+mZ1,x)+fp_or(y
w13
t4
w33(((x-y)-(((y)*gG-dJ2))*dU)aE2
x)*fp_cos(y)-mH)w43(y);}
q3
t5(w0
__A5_x08
oQ1
o__5_0AB_=vars[1];return
fp_pow(__A5_x08,o__5_0AB_);}
q3
t7(qJ
mH)w43
wL1-x)*wL1-mH/gG
w43(x
mU)qQ
t8(qH
a71
x,y)+(x>y?x:y);}
q3
t9
hM
q0(1.5l)+x*y-q0(2.0l
oH
4.0l)/q0(8.0l)+z+z+z+z+x/(y*z);}
q3
t10
hM
h92
aE2
fp_cos(aY1
1l
oH
2l
oH
3l
oH
4l
oH
5l),x+y+z))oH
2l);}
q3
t11
hM(-x-x)+y+hR
qK
1.1l),z
qQ
t12
wI2
1.0l)/hR
qK
10.0l),q0(1.0l)/hR
x)qQ
t13(qH
qP
dJ2*qP
dU+fp_pow(y,dJ2*fp_pow(y,q0(5l
qQ
t14(qJ
x*gF
aE2
wP2*gF
oH
CONST);}
q3
t15(qH
qP
y)/hR
y)+hR
x)/hR
y)+hR
qP
y
qQ
t16(qH
x<o62?(y<o62?x+y:x-y):(y>o62?x*y:x+wP2*y);}
q3
t17(qD,&y=vars[1];q0
b18[1];q0
b19[2];q0
b20[1];q0
b21[2];return
g41
b18[0]=(x),b18))+userDefFuncSub<q0>((b19[0]=(x),b19[1]=(y),b19))+g41
b20[0]=(y),b20))+userDefFuncSub<q0>((b21[0]=(y+h92),b21[1]=(x-gG,b21))-h92;}
q3
t18(qH-(-(-(-mO1)))*-qP-fp_pow(y,-mN1
t19(qH
aO,y
oH
10l)*dY,y
oH
100l)*oM,y
oH
1000l)*d1,y
oH
10000l)*mD,y
oH
100000l)*w9,y)+mZ1,y)*wP2+fp_or(x,y)*q0(20l)+oU2
x)*q0(200l)+aR
x)*q0(2000l
oH
4l)*oU2
a32
y),aO,dJ2)oH
40l)*fp_or(oU2
oM,y)),oM,q0(3l)qQ
t20(qH
fp_and(fp_not<q0>(x!=y),oU2
x))+aR
y);}
q3
t21(qD;q0
b26[1];return
g41
b26[0]=(x),b26))+userDefFuncValue<q0>((0))-mO1;}
q3
t22(qH(q0(3.5l)*gG+q0(10l)*(x*dJ2-(fp_sin(y)*gG+q0(100l)*((x*gG-(y*dJ2)*q0(2l
oH
5.0l)/(wP2*gG+qK
1.1l),x*gG+qK
1.1l)*wP2,x*q0(2l
qQ
t23(qJ(x/(wP2*fp_acos(q0(0.0l))))*q0(180l);}
q3
t24(qJ(fp_min(x,fp_min
wL1,x))aF2
mQ1/wP2
aF2
h92)*q0(3l)+aY1
0l),aX1-2l),o62
qQ
t25(w0
a
oQ1
b
oR1
c=vars[2];return
fp_pow(a,fp_pow(b,c))+fp_pow(a,-gG*(-fp_pow(b,gG)+(-fp_pow(b,-c
qQ
t26_deg
h62
d2r(x))+fp_cos(d2r(x
w71)+r2d(fp_asin(x/q0(110.0l)))+r2d
w73
x/q0(120.0l)qQ
t27(qH
fp_abs(x)+fp_acos(x)+fp_asin(x)+fp_atan(x)+a71
x,y)+a62
x)+mH)+d72
x
oH
1.0l)/qR2
x
oH
1.0l)/fp_sin(x)+qP
y);}
q3
t28(qH
g02+fp_floor(x)+fp_int(x)+hR
x)+gU
x)+fp_max(x,y)aF2
y
oH
1l)/mH)aE2
x)+fp_sinh(x)+g72
x)+qR2
x)+fp_tanh(x)+a62
y)+fp_trunc(y);}
q3
t29(qH
x-y*h92;}
q3
t30(qH
x-y*h92+fp_mod(x,y)+x/fp_pow(y,wK2
qK
2l),dJ2+fp_mod(mO1,dJ2+qP
fp_pow(y,o62))+qP
g32
qQ
t31
hM
x-(y*(y*(y*-mQ1*h92)+hR
x*qA2
y))-hR
qP
y))+qA2
hR
x+oL2)+qK
10.0l),hR
x+oL2/hR
y+oL2*hR
z+oL2/hR
q0(10.0l)))-qA2
hR
x+oL2*y)-qK
5.0l),hR
x+mS1)/hR
q0(5.0l)))+dB1
dJ2*dB1
gG/dB1
qA1
t32
hM
x+y/y-aX1
3l),dU-x-aY1
4l),dJ2+aY1
3l),dU-aX1
4l),q0(3l)oH
0l)+(z*h92)+(x-wP2+gG+(x*g32)*gG+y*o62+fp_min(fp_min(aX1
4.0l),x),qS2,fp_min(x,fp_min(fp_min(y,q0(4.0l)),z)))+fp_max(fp_max(aY1
4.0l),x),qS2,a22
fp_max(y,q0(4.0l)),z)))+(fp_abs
wL1)+fp_acos(qS2+fp_asin(qS2+fp_atan(qS2+a62
wK2
fp_cos
oV1
fp_cosh
oV1
fp_floor(wK2
hR
qS2+fp_sin
oV1
fp_sinh
oV1
qR2
qS2+fp_tanh(qS2+a71
q0(1.0l),qS2)+(x-(y-z))+(x+y)+(x*y)+a22
x,a22
x,x))))*-q0(1.0l)+(z-z
oH
1l)/fp_sin(x/q0(oT1
fp_cos(y/q0(oT1
qR2
z/mO1)+gU
h92/qR2
z/q0(oT1
fp_sin(y/q0(oT1
mH/mO1))+hR
q0(30l)+x)*hR
q0(40l)+y)/hR
q0(50l)+z)aE2
x/q0(57.295779513082320877l))+fp_asin(x/q0(10l))*q0(57.295779513082320877l)+fp_floor(-qQ2
a62
x)+wV1
5l)*q0(0.2l))+(-x+-x+-x+-x+-x+-mS
t33(qH
fp_sin(wV1
10l)-x*x+y*y))+fp_cos(wV1
15l)-x*x-y*y))aE2
x*x+y*y);}
q3
t34(w0
t
oQ1
rvar0
oR1
rvar1=vars[2],&rvar2=vars[3];return
rvar1+rvar2*rvar0-t;}
q3
t35(w0
wT
oQ1
A_very_long_variable_name_2
oR1
Yet_a_third_very_long_variable_name=vars[2];return
wT-A_very_long_variable_name_2+Yet_a_third_very_long_variable_name*wT;}
q3
t37
wI2
5l
oH
7.5l)*q0(8l)/q0(3l)-qK
2l),dU*wP2+fp_mod(mS1,gG+q0(4l)hP1
t38
hM
fp_asinh(x
oH
1.5l)*fp_acosh(y+q0(3l)oH
2.5l)*fp_atanh(z);}
q3
t39
hM
fp_sin(x+wU1)-mH
aE2
y
w71)+z*z*z
w43(z*z*z-x*x-y*y)-wU1
w43(x+wU1)+x*y*z+x*y*q0(2.5l)+x*y*z*mH)+x*y*mH)+x*z*mH)+y*z*q0(2.5l)+(x*y*z*mH)-x*y*z-y*mH)-x*z*y+x*y+x*z-mH)*mS
t40
hM(g12
g12
x+x+x+y+hE1
hE1
z+y+z+y+z)gP+wP2
gP-x*y
gP+x
gP;}
q3
t41
hM
x*q0(3l)+x*y+x*z+x
w43(y*z)-mF
q0(4l)+mF
x+mF
y+mF
z;}
q3
t43(qJ
hR
x*x)+fp_abs(aI2
fp_abs(x
oH
1l)qQ
t44(qJ
h21
x,h92/q0(8l)oH
1.1l)*fp_pow(dT
7l
gW2
h21
dT
6l)oH
1.3l)*h21
x*dT
5l)oH
1.4l)*h21
x*x*dT
6l)oH
1.5l
m51
dT
4l)oH
1.6l
m51
x*dT
3l)oH
1.7l
m51
a4*x,h92/gG+q0(1.8l)*(g72
fp_pow(fp_abs(-g72
x)),dJ2
qQ
t45(qJ
h21
x,h92/mS1
oH
1.1l)*h21
dT
5l
gW2
h21
x*x*dT
3l
qQ
t46(qH
fp_abs(fp_floor
w73
x)+dU
oH
1.1l)*fp_abs(fp_floor
w73
y
oH
1.5l)))g82
fp_acos(x),w73
y)-q0(10l)gW2
aY1-4l
qD1
x)oH
1.3l)*aX1
9l
qD1
x)-q0(9l
qQ
t47
oT2(1.25l)*(g02+g62
oH
1.5l)*(aI2
y)-aI2-y)oH
1.75l)*((g62+g02)/gG+q0(2.0l)*((g62-g02)/gG+q0(2.25l)*(d72
y)+fp_sinh(y
qQ
t48(qJ
fp_sinh((hR
x)/q0(5l
oH
1l))mU
gW2
d72(hR
x)/hR
gG+h92)*hR
gG)+oU2
fp_or(aR
x),oU2
x/dU
qQ
t49(qJ
a71
o62,x)+qK-4l)*(x-q0(100l)),q0(3.3l
qQ
t50(qH
fp_or(aO,y),fp_less(y,x)oH
2l)*a32
y),fp_less(y,x)oH
4l
oS1
hR1
y,x)oH
8l)*a32
aZ1
16l)*fp_or(aO,aZ1
32l
oS1
d1,y)oH
64l)*fp_or(dY,y),d1,y)oH
128l)*fp_and(w9,y),mD,y)oH
256l)*fp_and(w9,aZ1
512l
oS1
mD,y
qQ
t52(qJ
x+(q0(1.0l
oH
2.0l
oH
3.0l
oH
4.0l)-q0(5.0l)-q0(6.0l)-q0(7.0l)-q0(8.0l))/q0(3.0l
oH
4.0l)*(q0(1.0l)aE2
q0(2.0l))+fp_cos(q0(4.0l)*q0(5.0l
oH
6.0l))/q0(2.0l))+fp_cos(g32))*qR2
q0(0.6l
oH
0.2l))-q0(1.1l)/hR
q0(2.1l))*wV1
3.3l))+qK
2l),q0(3l
qQ
t53(qH
mZ1,y
oH
4l)*fp_or(fp_int(x/q0(10l)),fp_int(y/q0(10l))oH
8l)*((-hD1-x)))+(hD1-oU2
y))))oH
16l)*(-x+oU2
y
qQ
t54(qH
aO,y)+dY,y)+oM,y)+d1,y)+mD,y)+w9,y)+mZ1,y)+fp_or(x,y)+oU2
x)+aR
x)+oU2
a32
y),aO,dJ2))+fp_or(oU2
oM,y)),oM,q0(3l)qQ
t55(qH
fp_less(qP
q0(1.2l)),o62)g82
fp_pow(y,q0(2.5l)),o62)qX
x*x,o62
oH
3l)*fp_less(fp_pow(y,dJ2,o62
oH
4l)*fp_less(qP
dU,d32
t56(qJ
fp_mod(q0(1.75e21l),mS
t58(qH
fp_less(-x,dJ2+oM*-h92,mO1)+aO*-q0(3l),q0(10l))+aO*-q0(3l),y*mS1)+aO*q0(4l),y*mS1)+aO*q0(6l),y*-dJ2
g82-x,q0(11l))g82
mO1,-y);}
q3
t59(wR1
mH)w81
x))+(mH)-fp_sin(x))+((fp_sinh(x)-d72
x))-(fp_sinh(x)/d72
x))oH
q0(1l
qQ
I1
hM
q0(1l
oH
2l
oH
3l)-q0(4l)mU)*q0(6l)/q0(3l
oH
10l)/wP2-q0(9l)%wP2+(x+y-q0(11l)*x+z/q0(10l)+x/(z+q0(31l)qQ
I2
hM((fp_abs(x*y)<q0(20l))||(((x+y)>q0(30l))&&(z>mO1)))?fp_min(x,wP2*y):fp_max(y,z*q0(2l
qQ
I3
hM(x+y
oH
2l)*(x-z
oH
3l)*(x*y
oH
4l)*(y/z
oH
5l)*fp_mod(x,z
oH
6l)*(x<y
oH
7l)*(x<=z
oH
8l)*(x>wP2*z
oH
9l)*(y>=q0(3l)*z
oH
10l)*(x+y!=z
oH
11l)*(q0(100l)+x
oH
12l)*(q0(101l)-y
oH
13l)*(q0(102l)*z
oH
14l)*(q0(103l)/x);}
}
#define Value_t double
#undef Value_t
#undef N
#undef P
#ifdef FP_TEST_WANT_COMPLEX_DOUBLE_TYPE
#define N(x,y) (q0(x,y))
#define Value_t std::complex<double>
namespace
cpp_02unit_functions
oJ2
Cos_cd(qJ
cos
m8
Sin_cd(qJ
sin(x);}
}
template<>const
wU2
RegressionTests<q0>::Tests[]={S02
T02
U02
W02
Y02
S12
T12
U12
W12
Y12
S22
T22
U22
W22
Y22
S32
T32
U32
W32
Y32
S42
T42
U42
W42
Y42
S52
T52
U52{1,N(-o73,+200.0),N(o73,-200.0),N(5.0,-0.025)w8
Cos_cd
qF"/cos_cd"
,"cos(x)"
}
,W52
Y52
S62
T62
U62
W62
Y62{1,N(-o73,+200.0),N(o73,-200.0),N(5.0,-0.025)w8
Sin_cd
qF"/sin_cd"
,a51}
,S72
T72
U72
W72
Y72
S82
T82
U82
W82
Y82
S92
T92
U92
W92
Y92
SA2
TA2
UA2
WA2
YA2
SB2
TB2
UB2
WB2
YB2
SC2
TC2
UC2
WC2
YC2
SD2
TD2
UD2
WD2
YD2
SE2
TE2
UE2
WE2
YE2
SF2
TF2
UF2
WF2
YF2
SG2
TG2
UG2
WG2
YG2
SH2
TH2
UH2
WH2
YH2
SI2
TI2
UI2
WI2
YI2
SJ2
TJ2
UJ2
WJ2
YJ2
SK2
TK2
UK2
WK2
YK2
SL2
TL2
UL2
WL2
YL2
SM2
TM2
UM2
WM2
YM2
SN2
TN2
UN2
WN2
YN2
SO2
TO2
UO2
WO2
YO2
SP2
TP2
UP2
WP2
YP2
SQ2
TQ2
UQ2
WQ2
YQ2
SR2
TR2
UR2
WR2
YR2
SS2
TS2
US2
WS2
YS2
ST2
TT2
UT2
WT2
YT2
SU2
TU2
UU2
WU2
YU2
SV2
TV2
UV2
WV2
YV2
SW2
TW2
UW2
WW2
YW2
SX2
TX2
UX2
WX2
YX2
SY2
TY2
UY2
WY2
YY2
SZ2
TZ2
UZ2
WZ2
YZ2
Sa2
Ta2
Ua2
Wa2
Ya2
Sb2
Tb2
Ub2
Wb2
Yb2
Sc2
Tc2
Uc2
Wc2
Yc2
Sd2
Td2
Ud2
Wd2
Yd2
Se2
Te2
Ue2
We2
Ye2
Sf2
Tf2
Uf2
Wf2
Yf2
Sg2
Tg2
Ug2
Wg2
Yg2
Sh2
Th2
Uh2
Wh2
Yh2
Si2
Ti2
Ui2
Wi2
Yi2
Sj2
Tj2
Uj2
Wj2
Yj2
Sk2
Tk2
Uk2
Wk2
Yk2
Sl2
Tl2
Ul2
Wl2
Yl2
Sm2
Tm2
Um2
Wm2
Ym2
Sn2
Tn2
Un2
Wn2
Yn2
So2
To2
Uo2
Wo2
Yo2
Sp2
Tp2
Up2
Wp2
Yp2
Sq2
Tq2
Uq2
Wq2
Yq2
Sr2
Tr2
Ur2
Wr2
Yr2
Ss2
Ts2
Us2
Ws2
Ys2
St2
Tt2
Ut2
Wt2
Yt2
Su2
Tu2
Uu2
Wu2
Yu2
Sv2
Tv2
Uv2
Wv2
Yv2
Sw2
Tw2
Uw2
Ww2
Yw2
Sx2
Tx2
Ux2
Wx2
Yx2
Sy2
Ty2
Uy2
Wy2
Yy2
Sz2
Tz2
Uz2
Wz2
Yz2
S_2
T_2
U_2
W_2
Y_2
S03
T03
U03
W03
Y03
S13
T13
U13
W13
wU2()}
;
#undef Value_t
#undef N
#endif /*FP_TEST_WANT_COMPLEX_DOUBLE_TYPE */
#ifdef FP_TEST_WANT_COMPLEX_FLOAT_TYPE
#define N(x,y) (q0(APP(x,f),APP(y,f)))
#define Value_t std::complex<float>
namespace
cpp_02unit_functions
oJ2
Cos_cf(qJ
cos
m8
Sin_cf(qJ
sin(x);}
}
template<>const
wU2
RegressionTests<q0>::Tests[]={S02
T02
U02
W02
Y02
S12
T12
U12
W12
Y12
S22
T22
U22
W22
Y22
S32
T32
U32
W32
Y32
S42
T42
U42
W42
Y42
S52
T52
U52{1,N(-40.0,+0.5),N(40.0,-0.5),N(0.1,-0.00125)w8
Cos_cf
qF"/cos_cf"
,"cos(x)"
}
,W52
S62
T62
U62
W62
Y62{1,N(-40.0,+0.5),N(40.0,-0.5),N(0.1,-0.00125)w8
Sin_cf
qF"/sin_cf"
,a51}
,S72
YF2
SG2
SH2
TH2
UH2
WH2
YH2
SI2
TI2
UI2
WI2
YI2
SJ2
TJ2
UJ2
WJ2
YJ2
SK2
TK2
UK2
WK2
YK2
SL2
TL2
UL2
WL2
YL2
SM2
TM2
UM2
WM2
YM2
SN2
TN2
UN2
WN2
YN2
SO2
TO2
UO2
WO2
YO2
SP2
TP2
UP2
WP2
YP2
SQ2
TQ2
UQ2
WQ2
YQ2
SR2
TR2
UR2
WR2
YR2
SS2
TS2
US2
WS2
YS2
ST2
TT2
UT2
WT2
YT2
SU2
TU2
UU2
WU2
YU2
SV2
TV2
UV2
WV2
YV2
SW2
TW2
UW2
WW2
YW2
SX2
TX2
UX2
WX2
YX2
SY2
TY2
UY2
WY2
YY2
SZ2
TZ2
UZ2
WZ2
YZ2
Sa2
Ta2
Ua2
Wa2
Ya2
Sb2
Tb2
Ub2
Wb2
Yb2
Sc2
Tc2
Uc2
Wc2
Yc2
Sd2
Td2
Ud2
Wd2
Yd2
Se2
Te2
Ue2
We2
Ye2
Sf2
Tf2
Uf2
Wf2
Yf2
Sg2
Tg2
Ug2
Wg2
Yg2
Sh2
Th2
Uh2
Wh2
Yh2
Si2
Ti2
Ui2
Wi2
Yi2
Sj2
Tj2
Uj2
Wj2
Yj2
Sk2
Tk2
Uk2
Wk2
Yk2
Sl2
Tl2
Ul2
Wl2
Yl2
Sm2
Tm2
Um2
Wm2
Ym2
Sn2
Tn2
Un2
Wn2
Yn2
So2
To2
Uo2
Wo2
Yo2
Sp2
Tp2
Up2
Wp2
Yp2
Sq2
Tq2
Uq2
Wq2
Yq2
Sr2
Tr2
Ur2
Wr2
Yr2
Ss2
Ts2
Us2
Ws2
Ys2
St2
Tt2
Ut2
Wt2
Yt2
Su2
Tu2
Uu2
Wu2
Yu2
Sv2
Tv2
Uv2
Wv2
Yv2
Sw2
Tw2
Uw2
Ww2
Yw2
Sx2
Tx2
Ux2
Wx2
Yx2
Sy2
Ty2
Uy2
Wy2
Yy2
Sz2
Tz2
Uz2
Wz2
Yz2
S_2
T_2
U_2
W_2
Y_2
S03
T03
U03
W03
Y03
S13
T13
U13
W13
wU2()}
;
#undef Value_t
#undef N
#endif /*FP_TEST_WANT_COMPLEX_FLOAT_TYPE */
#ifdef FP_TEST_WANT_COMPLEX_LONG_DOUBLE_TYPE
#define N(x,y) (q0(APP(x,l),APP(y,l)))
#define Value_t std::complex<long double>
template<>const
wU2
RegressionTests<q0>::Tests[]={T02
W02
Y02
T12
U12
W12
Y12
S22
U22
W22
Y22
S32
U32
Y32
S42
T42
U42
Y42
T52
U52
W52
T62
U62
W62
Y62
YF2
SG2
SH2
TH2
UH2
WH2
YH2
SI2
TI2
UI2
WI2
YI2
SJ2
TJ2
UJ2
WJ2
YJ2
SK2
TK2
UK2
WK2
YK2
SL2
TL2
UL2
WL2
YL2
SM2
TM2
UM2
WM2
YM2
SN2
TN2
UN2
WN2
YN2
SO2
TO2
UO2
WO2
YO2
SP2
TP2
UP2
WP2
YP2
SQ2
TQ2
UQ2
WQ2
YQ2
SR2
TR2
UR2
WR2
YR2
SS2
TS2
US2
WS2
YS2
ST2
TT2
UT2
WT2
YT2
SU2
TU2
UU2
WU2
YU2
SV2
TV2
UV2
WV2
YV2
SW2
TW2
UW2
WW2
YW2
SX2
TX2
UX2
WX2
YX2
SY2
TY2
UY2
WY2
YY2
SZ2
TZ2
UZ2
WZ2
YZ2
Sa2
Ta2
Ua2
Wa2
Ya2
Sb2
Tb2
Ub2
Wb2
Yb2
Sc2
Tc2
Uc2
Wc2
Yc2
Sd2
Td2
Ud2
Wd2
Yd2
Se2
Te2
Ue2
We2
Ye2
Sf2
Tf2
Uf2
Wf2
Yf2
Sg2
Tg2
Ug2
Yg2
Sh2
Th2
Uh2
Wh2
Yh2
Si2
Ti2
Ui2
Wi2
Yi2
Sj2
Tj2
Uj2
Wj2
Yj2
Sk2
Tk2
Uk2
Wk2
Yk2
Sl2
Tl2
Ul2
Wl2
Yl2
Sm2
Tm2
Um2
Wm2
Ym2
Sn2
Tn2
Un2
Wn2
Yn2
So2
To2
Uo2
Wo2
Yo2
Sp2
Tp2
Up2
Wp2
Yp2
Sq2
Tq2
Uq2
Wq2
Yq2
Sr2
Tr2
Ur2
Wr2
Yr2
Ss2
Ts2
Us2
Ws2
Ys2
St2
Tt2
Wt2
Yt2
Su2
Tu2
Uu2
Wu2
Yu2
Sv2
Tv2
Uv2
Wv2
Yv2
Sw2
Tw2
Uw2
Ww2
Yw2
Sx2
Tx2
Ux2
Wx2
Yx2
Sy2
Ty2
Uy2
Wy2
Yy2
Sz2
Tz2
Uz2
Wz2
Yz2
S_2
T_2
U_2
W_2
Y_2
S03
T03
U03
W03
Y03
S13
T13
U13
W13
wU2()}
;
#undef Value_t
#undef N
#endif /*FP_TEST_WANT_COMPLEX_LONG_DOUBLE_TYPE */
#ifdef FP_TEST_WANT_DOUBLE_TYPE
#define N(x) (x)
#define P(x) N(x##.0)
#define Value_t double
template<>const
wU2
RegressionTests<q0>::Tests[]={Uj
Wj
Yj
Sk
Tk
Uk
Wk
Yk
Sl
Tl
Ul
Wl{2,-11,11,N(0.3),qM
Mod,aK2(aN2
Mod)qB",z"
,g6"mod"
,"x%z"
}
,Yl
Sm
Tm
Um
Wm
Ym
Sn{oU1
w8
Acos,aK2(aR2
Acos)qO"/acos"
,"acos"
g21,oW1
Acos_deg,aK2(aR2
Acos_deg)qO"/acos_deg"
,"acos"
hA
1,400,w2
Acosh,aK2(aR2
Acosh)qO"/"
w12,w12
hA
1,400,g71
Acosh_deg,aK2(aR2
Acosh_deg)qO"/acosh_deg"
,w12
g21
w8
Asin,aK2(aR2
Asin)qO"/asin"
,"a"
a51}
,{oU1,oW1
Asin_deg,aK2(aR2
Asin_deg)qO"/asin_deg"
,"a"
a51}
,{oU1
w8
Asinh,aK2(aR2
Asinh)qO"/a"
gA2,oW3
g21,oW1
Asinh_deg,aK2(aR2
Asinh_deg)qO"/asinh_deg"
,oW3
hA
oX1
w2
Atan,aK2(aR2
Atan)qO"/atan"
,"atan(x)"
}
,{2,-wW1
w8
Atan2,aK2(aR2
Atan2)wA"/"
hZ2,hZ2"(x"
wA1{2,-wW1,oW1
Atan2_deg,aK2(aR2
Atan2_deg)wA"/atan2_deg"
,hZ2"(x"
wA1{1,oX1
g71
Atan_deg,aK2(aR2
Atan_deg)qO"/atan_deg"
,"atan"
g21
w8
Atanh,aK2(aR2
Atanh)qO"/atanh"
,"atanh"
hA-50000,50000,1000
w8
Cbrt,aK2(aR2
Cbrt)qO"/cbrt"
,"cbrt"
hA-10,10
oD1
w8
Ceil,aK2(aR2
Ceil)qO"/ceil"
,"ceil"
hA-aS
w8
Cos,aK2(aR2
Cos)qO"/cos"
,"cos"
hA
w63
Cos_deg,aK2(aR2
Cos_deg)qO"/cos_deg"
,"cos"
hA-140,140,w2
Cosh,aK2(aR2
Cosh)qO"/cosh"
,"cosh"
hA-140,140,g71
Cosh_deg,aK2(aR2
Cosh_deg)qO"/cosh_deg"
,"cosh"
hA-90,90,N(0.01)w8
Exp,aK2(aR2
Exp)qO"/exp"
,"exp"
hA-90,90,N(0.01)w8
Exp2,aK2(aR2
Exp2)qO"/exp2"
,"exp2"
hA-10,10
oD1
w8
Floor,aK2(aR2
Floor)qO"/floor"
,"floor(x)"
}
,{2,-wW1
w8
Hypot,aK2(aR2
Hypot)wA"/hypot"
,"hypot(x"
wA1
Tn
Un
SO1{1,N(1e-6),wQ2
Log2,aK2(aR2
Log2)qO"/log2"
,"log2"
hA
N(1e-6),wQ2
Log10,aK2(aR2
Log10)qO"/log10"
,oU}
,T4
U4{2,1,20,1
w8
Pow_neg,aK2(aR2
Pow_neg)wA"/pow_neg"
,"pow(-x*0.25,y"
mQ{2,N(0.01),4,N(0.05)w8
Pow_pos,aK2(aR2
Pow_pos)wA"/pow_pos"
,qC2
wA1{1,-aS
w8
Sin,aK2(aR2
Sin)qO"/sin"
,a51}
,{1,w63
Sin_deg,aK2(aR2
Sin_deg)qO"/sin_deg"
,a51}
,{1,oX1
w2
Sinh,aK2(aR2
Sinh)qO"/sinh"
,gA2
hA
oX1
g71
Sinh_deg,aK2(aR2
Sinh_deg)qO"/sinh_deg"
,gA2
hA
0,100000,1000
w8
Sqrt,aK2(aR2
Sqrt)qO"/sqrt"
,"sqrt"
hA
N(-1.3),N(1.3),N(0.05)w8
Tan,aK2(aR2
Tan)qO"/tan"
,"tan"
hA-89,89
oD1,oW1
Tan_deg,aK2(aR2
Tan_deg)qO"/tan_deg"
,"tan"
hA-aS
w8
Tanh,aK2(aR2
Tanh)qO"/tanh"
,"tanh"
hA
w63
Tanh_deg,aK2(aR2
Tanh_deg)qO"/tanh_deg"
,"tanh"
hA-4000,wQ2
Trunc,aK2(aR2
Trunc)qO"/trunc"
,"trunc"
hA
0,dE
E_d,aK2(aT2
E_d)wI"e_d"
,o83"naturalnumber"
aB2
L2_d,aK2(aT2
L2_d)wI"l2_d"
,o83"logtwo"
aB2
L10_d,aK2(aT2
L10_d)wI"l10_d"
,o83"logten"
aB2
Pi_d,aK2(aT2
Pi_d)wI"pi_d"
,o83"pi"
}
,W4
TO1
UO1
WO1
YO1
SP1
TP1
Wn
Y4
Yn
So
To
S5
T5
U5
W5{w03
N(0.1)qL
Absyxpow_neg,aK2(aM2
Absyxpow_neg)qZ"absyxpow_neg"
,"(x^-4)^1.5"
}
,{w03
N(0.1)qL
Absyxpow_pos,aK2(aM2
Absyxpow_pos)qZ"absyxpow_pos"
,"(x^4)^1.5"
}
,{1
w7
Acos,aK2(aM2
Acos)qZ"acos"
,"acos"
wR2,dL2
Acos_deg,aK2(aM2
Acos_deg)qZ"acos_deg"
,"acos"
wR2
qL
Acosh,aK2(aM2
Acosh)qZ
w12,w12"("
w4
Acosh_deg,aK2(aM2
Acosh_deg)qZ"acosh_deg"
,w12
dN2
Uo
Wo
UP1
WP1
Yo
Sp
YP1{1
w7
Asin,aK2(aM2
Asin)qZ"asin"
,"asin("
a81,dL2
Asin_deg,aK2(aM2
Asin_deg)qZ"asin_deg"
,"asin("
a81
qL
Asinh,aK2(aM2
Asinh)qZ
oW3,oW3"("
w4
Asinh_deg,aK2(aM2
Asinh_deg)qZ"asinh_deg"
,oW3
dN2
Tp
Up{1
w7
Atan,aK2(aM2
Atan)qZ"atan"
,"atan("
qP1
Atan2,aK2(aM2
Atan2)qZ
hZ2,hZ2"(5,4"
gH,dL2
Atan2_deg,aK2(aM2
Atan2_deg)qZ"atan2_deg"
,hZ2"(5,4)+x"
}
,Wp{1,0,1,1,dL2
Atan_deg,aK2(aM2
Atan_deg)qZ"atan_deg"
,"atan("
qP1
Atanh,aK2(aM2
Atanh)qZ"atanh"
,"atanh"
wR2
qL
Cbrt,aK2(aM2
Cbrt)qZ"cbrt"
,"cbrt("
qP1
Ceil,aK2(aM2
Ceil)qZ"ceil"
,"ceil"
dN2
Yp
SQ1
TQ1
UQ1
WQ1
YQ1
SR1
TR1
UR1
WR1
YR1
SS1
TS1
US1
WS1
YS1
ST1
TT1
UT1
WT1
YT1
SU1
TU1
UU1
WU1
YU1
SV1
TV1
UV1
WV1
YV1
SW1
TW1
UW1
WW1
YW1
SX1
TX1
UX1
WX1
YX1
SY1
TY1
UY1
WY1
YY1
SZ1
TZ1
UZ1
WZ1
YZ1
Sa1
Ta1{1
w7
Cos,aK2(aM2
Cos)qZ"cos"
,"cos("
w4
Cos_deg,aK2(aM2
Cos_deg)qZ"cos_deg"
,"cos("
qP1
Cosh,aK2(aM2
Cosh)qZ"cosh"
,"cosh("
w4
Cosh_deg,aK2(aM2
Cosh_deg)qZ"cosh_deg"
,"cosh"
dN2
Sq
Tq
Ua1
Wa1
Ya1
Y5
Uq
Wq
Yq
S6
T6
U6
W6
Sr
Sb1
Tb1{1
w7
Exp,aK2(aM2
Exp)qZ"exp"
,o02
qP1
Exp2,aK2(aM2
Exp2)qZ"exp2"
,"exp2"
dN2
Tr
Ur{1,wJ
Exp2xpow,aK2(aM2
Exp2xpow)qZ"exp2xpow"
,aK
qT2
Wr
Yr
Ss
Ts{1,wJ
Expxpow,aK2(aM2
Expxpow)qZ"expxpow"
,aJ
qT2{1
w7
Floor,aK2(aM2
Floor)qZ"floor"
,"floor"
dN2
Us
Ub1
Wb1
Yb1
Sc1
Tc1
Uc1
Wc1
Yc1
Sd1
Td1
Ud1
Wd1
Yd1
Se1{1
w7
Hypot,aK2(aM2
Hypot)qZ"hypot"
,"hypot(5,4)+x"
}
,Te1
Ws
Ys
St
Tt
Ut
Wt
Yt
Y6
Ue1{1
w7
Log,aK2(aM2
Log)qZ"log"
,"log("
qP1
Log2,aK2(aM2
Log2)qZ"log2"
,"log2"
dN2
We1
Ye1{1
w7
Log10,aK2(aM2
Log10)qZ"log10"
,"log10"
dN2
Sf1
Tf1
Uf1
Wf1
Yf1
Sg1
Tg1
S7
T7
Ug1
Wg1
Yg1
Sh1
U7
W7
Th1{1
w7
Mulminus1,aK2(aM2
Mulminus1)qZ"mulminus1"
,"x*-1"
}
,Uh1
Wh1{1
w7
Neg,aK2(aM2
Neg)qZ"neg"
,"((-((5))))+x"
}
,Y7
Yh1
Su
Si1
Ti1
S8
Tu
Ui1
T8
U8
Wi1
Yi1
W8
Sj1
Tj1
Uj1
Wj1
Yj1
Sk1
Y8
S9
T9
U9
W9
Y9
SA
TA
UA
Tk1{1
w7
Pow_neg,aK2(aM2
Pow_neg)w3"_neg"
,"pow(-0.25,4"
gH
qL
Pow_pos,aK2(aM2
Pow_pos)w3"_pos"
,"pow(1.1, 7.1)+x"
}
,Uu
Wu
Yu
Sv
Tv
Uv
Wv{1,wJ
Powxpow,aK2(aM2
Powxpow)LNG_ONLY(0)q5"/powxpow"
,"(x^1.7)"
qT2
Yv
Sw{1,N(0.01),10,N(0.05)qL
Rsqrt,aK2(aM2
Rsqrt)qZ"rsqrt"
,"1/sqrt"
hA
0,1,1
qL
Sin,aK2(aM2
Sin)hQ,"sin("
w4
Sin_deg,aK2(aM2
Sin_deg)hQ"_deg"
,"sin("
w6
Uk1
Wk1
Yk1
Sl1
Tl1
Ul1
Wl1
Yl1
Sm1{1
w7
Sinh,aK2(aM2
Sinh)hQ"h"
,gA2"("
w4
Sinh_deg,aK2(aM2
Sinh_deg)hQ"h_deg"
,gA2
dN2
WA
YA
SB
TB
UB
WB
Tm1
Tw
Uw
Ww
Um1{w03
N(0.1)qL
Sqrsqrt,aK2(aM2
Sqrsqrt)qZ"sqrsqrt"
,"sqrt"
qD2{1
w7
Sqrt,aK2(aM2
Sqrt)qZ"sqrt"
,"sqrt"
dN2
Wm1
Ym1{1,wJ
Sqrxpow,aK2(aM2
Sqrxpow)qZ"sqrxpow"
,"(x^2)^2402"
}
,{w03
N(0.1)qL
Sqrxpow_nonint,aK2(aM2
Sqrxpow_nonint)qZ"sqrxpow_nonint"
,"(x^2)^3.5"
}
,Sn1
Tn1
Un1{1
w7
Tan,aK2(aM2
Tan)qZ"tan"
,"tan("
w4
Tan_deg,aK2(aM2
Tan_deg)qZ"tan_deg"
,"tan("
qP1
Tanh,aK2(aM2
Tanh)qZ"tanh"
,"tanh("
w4
Tanh_deg,aK2(aM2
Tanh_deg)qZ"tanh_deg"
,"tanh("
qP1
Trunc,aK2(aM2
Trunc)qZ"trunc"
,"trunc"
dN2
YB
SC
Yw
Wn1
Yn1
So1
To1
Uo1
Wo1
TC
Sx
UC{1,0,10,N(0.01)qL
Ypowxpow,aK2(aM2
Ypowxpow)qZ"ypowxpow"
,"(x^38.5)^5"
}
,Yo1
Sp1
Tp1
Up1
Wp1
Yp1
Sq1
Tq1
Uq1
Wq1
Yq1
Sr1
Tr1
Ur1
Wr1
Yr1
Ss1
Ts1
Us1
Ws1
Ys1
St1
Tt1
Ut1
Wt1
Yt1
Su1
Tu1
Uu1
Wu1
Yu1
Sv1
Tv1
Uv1
Wv1
Yv1
Sw1
Tw1
Uw1
Ww1
Yw1
Sx1
Tx1
Tx
Ux
Ux1
Wx1
WC
YC
Wx
Yx
SD
Sy
TD
UD
WD
Ty
Uy
Wy
YD
SE
TE
UE
WE
YE
SF
TF
UF
Yy
Sz
Tz
Uz
Wz
Yz
WF
YF
SG
TG
UG
WG
YG
SH
TH
S_
T_
U_
W_
Y_
S01
UH
WH
YH
SI
TI
UI
WI
YI
SJ
T01
U01
W01
Y01
S11
T11
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
U11
W11
Y11
S21
T21
U21
SL
TL
UL
WL
YL
SM
TM
UM
WM
W21
Y21
S31
T31
U31
W31
YM
SN
TN
UN
WN
YN
SO
TO
UO
Y31
S41
T41
U41
W41
Y41
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
S51
T51
U51
W51
Y51
S61
Yx1
Sy1
T61
U61
W61
Ty1
Uy1
UQ
WQ
YQ
SR
TR
UR
Wy1
Yy1
Sz1
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
TV
UV
WV
YV
SW
TW
UW
WW
Y61
S71
YW
T71
U71
W71
Y71
SX
S81
TX
T81
U81
W81
UX
WX
YX
SY
Y81
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Tz1
Yb
Sc
S91
T91
U91
W91
Y91
SA1
TA1
UA1
Tc
Uc
Wc
WA1
YA1
SB1
TB1
UB1
WB1
Uz1
Wz1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
YB1
SC1
TC1
UC1
WC1
YC1
SD1
TD1
UD1
WD1
YD1
SE1
TE1
Ye
Sf
Tf
Uf
Wf
Yf
UE1
Sg
Yz1
S_1
T_1
U_1
W_1
Y_1
Tg
WE1
YE1
SF1
TF1
Ug
UF1
WF1
YF1
SG1
TG1
UG1
WG1
YG1
SH1
TH1
UH1
WH1
YH1
SI1
Wg
Yg
TI1
Sh
Th
Uh
UI1
WI1
Wh
YI1
SJ1
TJ1
UJ1
Yh
WJ1
YJ1
SK1
TK1
Si
Ti
UK1
WK1
YK1
SL1
TL1
UL1
WL1
YL1
SM1
TM1
UM1
WM1
Ui
YM1
SN1
TN1
UN1
WN1
Wi
YN1
wU2()}
;
#undef Value_t
#undef N
#undef P
#endif /*FP_TEST_WANT_DOUBLE_TYPE */
#ifdef FP_TEST_WANT_FLOAT_TYPE
#define N(x) (APP(x,f))
#define P(x) N(x##.0)
#define Value_t float
namespace
cpp_01unit_operators
oJ2
Modf(qD,&z=vars[1];return
fmodf(x,z)wV2
cpp_02unit_functions
oJ2
Acosf(qJ
acosf
m8
a92
g42
acosf(x
oI2
Acoshf(oP2
x+qU2-1.0f
oI2
a42
g42
fp_acosh(x
oI2
Asinf(qJ
asinf
m8
aA2
g42
asinf(x
oI2
Asinhf(oP2
x+qU2+1.0f
oI2
aC2
g42
fp_asinh(x
oI2
Atan2f(qH
qV2
x
oX3
Atan2f_deg(qH
r2d(qV2
x,y
oI2
Atanf(qJ
atanf
m8
Atanf_deg
g42
atanf(x
oI2
Atanhf(oP2(1.0f+x)/(1.0f-x))*0.5f;}
q0
Cbrtf(qJ
fp_cbrt
m8
Ceilf(qJ
ceilf
m8
Cosf(qJ
cosf
m8
Cosf_deg(qJ
cosf
mM
Coshf(qJ
coshf
m8
Coshf_deg(qJ
coshf
mM
Exp2f(qJ
expf(x*fp_const_log2<q0>(oI2
Expf(qJ
expf
m8
Floorf(qJ
floorf
m8
Hypotf(qH
qU2+y*y);}
q0
Log2f(oP2
x)*1.4426950408889634073599246810018921374266f;}
q0
Log10f(qJ
log10f
m8
Logf(qJ
logf
m8
Pow_negf(qH
powf(-x*0.25f
oX3
Pow_posf(qH
powf(x
oX3
Sinf(qJ
sinf
m8
Sinf_deg(qJ
sinf
mM
Sinhf(qJ
sinhf
m8
Sinhf_deg(qJ
sinhf
mM
Sqrtf
oQ2
m8
Tanf(qJ
tanf
m8
Tanf_deg(qJ
tanf
mM
Tanhf(qJ
tanhf
m8
Tanhf_deg(qJ
tanhf
mM
Truncf(qJ
fp_trunc(x)wV2
cpp_03unit_constants
oJ2
E_f(qJ
expf(x*0.0f+1.0f);}
q0
L2_f(oP2
x*0.0f+2.0f);}
q0
L10_f(oP2
x*0.0f+10.0f);}
q0
Pi_f(qJ
qV2
x*0.0f,-1.0f)wV2
cpp_10optimizer_bytecode
oJ2
Acosf(qJ
acosf(0.7f
dQ
a92
g42
acosf(0.7f)dQ
Acoshf
o11+sqrtf(1.1f*1.1f-1.0f)dQ
a42
g42
fp_acosh(1.1f)dQ
Asinf(qJ
asinf(0.7f
dQ
aA2
g42
asinf(0.7f)dQ
Asinhf
o11+sqrtf(1.1f*1.1f+1.0f)dQ
aC2
g42
fp_asinh(1.1f)dQ
Atan2f(qJ
qV2
5.0f,wS2
Atan2f_deg
g42
qV2
5.0f,4.0f)dQ
Atanf(qJ
atanf
gI2
Atanf_deg
g42
atanf(1.1f)dQ
Atanhf(oP2(1.0f+0.7f)/(1.0f-0.7f))*0.5f+x;}
q0
Cbrtf(qJ
fp_cbrt
gI2
Ceilf(qJ
ceilf
gI2
Cosf(qJ
cosf
gI2
Cosf_deg(qJ
cosf(qQ1
Coshf(qJ
coshf
gI2
Coshf_deg(qJ
coshf(qQ1
Exp2f(qJ
expf(1.1f*0.693147180559945309417232121458176568075500134f
dQ
Expf(qJ
expf
gI2
Floorf(qJ
floorf
gI2
Hypotf
oQ2(5.0f*5.0f+4.0f*wS2
Log2f
o11)*1.4426950408889634073599246810018921374266f+x;}
q0
Log10f(qJ
log10f
gI2
Logf
o11
dQ
Pow_negf(qJ
powf(-0.25f,wS2
Pow_posf(qJ
powf(1.1f,7.1f
dQ
Sinf(qJ
sinf
gI2
Sinf_deg(qJ
sinf(qQ1
Sinhf(qJ
sinhf
gI2
Sinhf_deg(qJ
sinhf(qQ1
Sqrtf
oQ2
gI2
Tanf(qJ
tanf
gI2
Tanf_deg(qJ
tanf(qQ1
Tanhf(qJ
tanhf
gI2
Tanhf_deg(qJ
tanhf(qQ1
Truncf(qJ
1.0f+x;}
}
template<>const
wU2
RegressionTests<q0>::Tests[]={Uj
Wj
Yj
Sk
Tk
Uk
Wk
Yk
Sl
Tl
Ul
Wl{2,-11,11,N(0.3),qM
Modf,h7
qB",z"
,g6"modf"
,"x%z"
}
,Yl
Sm
Tm
Um
Wm
Ym
Sn{oU1
w8
Acosf
qF"/acosf"
,"acos"
g21,oW1
a92
qF"/acosf_deg"
,"acos"
hA
1,400,w2
Acoshf
qF"/acoshf"
,w12
hA
1,400,g71
a42
qF"/acoshf_deg"
,w12
g21
w8
Asinf
qF"/asinf"
,"a"
a51}
,{oU1,oW1
aA2
qF"/asinf_deg"
,"a"
a51}
,{oU1
w8
Asinhf
qF"/asinhf"
,oW3
g21,oW1
aC2
qF"/asinhf_deg"
,oW3"(x)"
}
,{2,-wW1
w8
Atan2f,h7
wA"/atan2f"
,hZ2"(x"
wA1{2,-wW1,oW1
Atan2f_deg,h7
wA"/atan2f_deg"
,hZ2"(x"
wA1{1,oX1
w2
Atanf
qF"/atanf"
,"atan"
hA
oX1
g71
Atanf_deg
qF"/atanf_deg"
,"atan"
g21
w8
Atanhf
qF"/atanhf"
,"atanh"
hA-50000,50000,1000
w8
Cbrtf
qF"/cbrtf"
,"cbrt"
hA-10,10
oD1
w8
Ceilf
qF"/ceilf"
,"ceil"
hA-aS
w8
Cosf
qF"/cosf"
,"cos"
hA
oX1
5,oW1
Cosf_deg
qF"/cosf_deg"
,"cos"
hA-40,40,N(0.025)w8
Coshf
qF"/coshf"
,"cosh"
hA-40,40,g71
Coshf_deg
qF"/coshf_deg"
,"cosh"
hA-90,90,N(0.01)w8
Exp2f
qF"/exp2f"
,"exp2"
hA-20,20,N(0.01)w8
Expf
qF"/expf"
,"exp"
hA-10,10
oD1
w8
Floorf
qF"/floorf"
,"floor(x)"
}
,{2,-wW1
w8
Hypotf,h7
wA"/hypotf"
,"hypot(x"
wA1
Tn
Un{1,dC1
Log2f
qF"/log2f"
,"log2"
hA
dC1
Log10f
qF"/log10f"
,"log10"
hA
dC1
Logf
qF"/logf"
,aQ1
T4
U4{2,1,20,1
w8
Pow_negf,h7
wA"/pow_negf"
,"pow(-x*0.25,y"
mQ{2,N(0.01),4,N(0.05)w8
Pow_posf,h7
wA"/pow_posf"
,qC2
wA1{1,-aS
w8
Sinf
qF"/sinf"
,a51}
,{1,oX1
5,oW1
Sinf_deg
qF"/sinf_deg"
,a51}
,{1,-40,40,w2
Sinhf
qF"/sinhf"
,gA2
hA
oX1
g71
Sinhf_deg
qF"/sinhf_deg"
,gA2
hA
0,100000,1000
w8
Sqrtf
qF"/sqrtf"
,"sqrt"
hA
N(-1.3),N(1.3),N(0.05)w8
Tanf
qF"/tanf"
,"tan"
hA-89,89
oD1,oW1
Tanf_deg
qF"/tanf_deg"
,"tan"
hA-aS
w8
Tanhf
qF"/tanhf"
,"tanh"
hA
w63
Tanhf_deg
qF"/tanhf_deg"
,"tanh"
hA
oX1
w2
Truncf
qF"/truncf"
,"trunc"
hA
0,dE
E_f,w5"e_f"
,o83"naturalnumber"
aB2
L2_f,w5"l2_f"
,o83"logtwo"
aB2
L10_f,w5"l10_f"
,o83"logten"
aB2
Pi_f,w5"pi_f"
,o83"pi"
}
,W4
TO1
UO1
YO1
SP1
Wn
Y4
Yn
So
To
S5
W5{1
w7
Acosf
aQ"acosf"
,"acos"
wR2,dL2
a92
aQ"acosf_deg"
,"acos(0.7)+x"
}
,Uo{1
w7
Acoshf
aQ"acoshf"
,w12"("
w4
a42
aQ"acoshf_deg"
,w12
dN2
Wo
Yo
Sp{1
w7
Asinf
aQ"asinf"
,"asin("
a81,dL2
aA2
aQ"asinf_deg"
,"asin(0.7)+x"
}
,Tp{1
w7
Asinhf
aQ"asinhf"
,oW3"("
w4
aC2
aQ"asinhf_deg"
,oW3
dN2
Up{1
w7
Atan2f
aQ"atan2f"
,hZ2"(5,4"
gH,dL2
Atan2f_deg
aQ"atan2f_deg"
,hZ2"(5,4)+x"
}
,Wp{1
w7
Atanf
aQ"atanf"
,"atan("
w4
Atanf_deg
aQ"atanf_deg"
,"atan("
qP1
Atanhf
aQ"atanhf"
,"atanh"
wR2
qL
Cbrtf
aQ"cbrtf"
,"cbrt("
qP1
Ceilf
aQ"ceilf"
,"ceil"
dN2
Yp
SQ1
TQ1
UQ1
WQ1
YQ1
SR1
TR1
UR1
WR1
YR1
SS1
TS1
US1
WS1
YS1
ST1
TT1
UT1
WT1
YT1
SU1
TU1
UU1
WU1
YU1
SV1
TV1
UV1
WV1
YV1
SW1
TW1
UW1
WW1
YW1
SX1
TX1
UX1
WX1
YX1
SY1
TY1
UY1
WY1
YY1
SZ1{1
w7
Cosf
aQ"cosf"
,"cos("
w4
Cosf_deg
aQ"cosf_deg"
,"cos("
qP1
Coshf
aQ"coshf"
,"cosh("
w4
Coshf_deg
aQ"coshf_deg"
,"cosh"
dN2
Sq
Tq
Y5
Uq
Wq
Yq
S6
T6
U6
W6
Sr
Sb1
Tb1
Tr{1
w7
Exp2f
aQ"exp2f"
,"exp2"
dN2
Ur
Wr{1
w7
Expf
aQ"expf"
,"exp"
dN2
Yr
Ss
Ts{1
w7
Floorf
aQ"floorf"
,"floor"
dN2
Us
Ub1
Wb1
Yb1
Sc1
Tc1
Uc1
Wc1
Yc1
Sd1
Td1
Ud1
Wd1
Yd1
Se1{1
w7
Hypotf
aQ"hypotf"
,"hypot(5,4)+x"
}
,Ws
Ys
St
Tt
Ut
Wt
Yt
Y6
Ue1
We1
Ye1{1
w7
Log2f
aQ"log2f"
,"log2("
qP1
Log10f
aQ"log10f"
,"log10"
dN2
Sf1
Tf1{1
w7
Logf
aQ"logf"
,"log"
dN2
Uf1
Wf1
Yf1
Sg1
Tg1
S7
T7
Sh1
U7
W7
Th1
Y7
Su
Si1
Ti1
S8
Tu
T8
U8
Wi1
Yi1
W8
Tj1
Uj1
Wj1
Yj1
Y8
S9
T9
U9
W9
Y9
SA
TA
UA{1
w7
Pow_negf,qG"/pow_negf"
,"pow(-0.25,4"
gH
qL
Pow_posf,qG"/pow_posf"
,"pow(1.1, 7.1)+x"
}
,Uu
Wu
Yu
Sv
Tv
Uv
Wv
Yv
Sw
Uk1
Wk1
Yk1
Sl1
Tl1
Ul1
Wl1
Yl1
Sm1{1
w7
Sinf
aR1"f"
,"sin("
w4
Sinf_deg
aR1"f_deg"
,"sin("
qP1
Sinhf
aR1"hf"
,gA2"("
w4
Sinhf_deg
aR1"hf_deg"
,gA2
dN2
WA
YA
SB
TB
UB
WB
Tw
Uw
Ww{1
w7
Sqrtf
aQ"sqrtf"
,"sqrt"
dN2
Wm1
Ym1
Un1{1
w7
Tanf
aQ"tanf"
,"tan("
w4
Tanf_deg
aQ"tanf_deg"
,"tan("
qP1
Tanhf
aQ"tanhf"
,"tanh("
w4
Tanhf_deg
aQ"tanhf_deg"
,"tanh("
qP1
Truncf
aQ"truncf"
,"trunc"
dN2
YB
SC
Yw
Wn1
Yn1
So1
To1
Uo1
Wo1
TC
Sx
UC
Tx
Ux
Wx
Yx
SD
Sy
TD
UD
WD
Ty
Uy
Wy
YD
SE
TE
UE
WE
YE
SF
TF
UF
Yy
Sz
Tz
Uz
Wz
Yz
WF
YF
SG
TG
UG
WG
YG
SH
TH
S_
T_
U_
W_
Y_
S01
UH
WH
YH
SI
TI
UI
WI
YI
SJ
T01
U01
W01
Y01
S11
T11
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
U11
W11
Y11
S21
T21
U21
SL
TL
UL
WL
YL
SM
TM
UM
WM
W21
Y21
S31
T31
U31
W31
YM
SN
TN
UN
WN
YN
SO
TO
UO
Y31
S41
T41
U41
W41
Y41
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
S51
T51
U51
W51
Y51
S61
Yx1
Sy1
T61
U61
W61
Ty1
Uy1
UQ
WQ
YQ
SR
TR
UR
Wy1
Yy1
Sz1
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
TV
UV
WV
YV
SW
TW
UW
WW
Y61
S71
YW
T71
U71
W71
Y71
SX
S81
TX
T81
U81
W81
UX
WX
YX
SY
Y81
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Tz1
Yb
Sc
S91
T91
U91
W91
Y91
SA1
TA1
UA1
Tc
Uc
Wc
WA1
YA1
SB1
TB1
UB1
WB1
Uz1
Wz1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
YB1
SC1
TC1
UC1
WC1
YC1
SD1
TD1
UD1
WD1
YD1
SE1
TE1
Ye
Sf
Tf
Uf
Wf
Yf
UE1
S_1
Tg
WE1
YE1
SF1
TF1
Ug
UF1
WF1
YF1
SG1
TG1
UG1
WG1
YG1
SH1
TH1
UH1
WH1
YH1
SI1
Wg
Yg
TI1
Sh
Th
Uh
WI1
Wh
YI1
SJ1
TJ1
UJ1
Yh
WJ1
SK1
Si
Ti
UK1
WL1
YL1
SM1
TM1
UM1
WM1
Ui
YM1
SN1
TN1
UN1
WN1
Wi
YN1
wU2()}
;
#undef Value_t
#undef N
#undef P
#endif /*FP_TEST_WANT_FLOAT_TYPE */
#ifdef FP_TEST_WANT_GMP_INT_TYPE
#define P(x) (APP(x,l))
#define Value_t GmpInt
template<>const
wU2
RegressionTests<q0>::Tests[]={S
T
U
W
Y
S1
T1
U1
W1
Y1
S2
T2
U2
W2
Y2
S3
T3
U3
W3
Y3
S4
T4
U4
W4
Y4
S5
T5
U5
W5
Y5
S6
T6
U6
W6
Y6
S7
T7
U7
W7
Y7
S8
T8
U8
W8
Y8
S9
T9
U9
W9
Y9
SA
TA
UA
WA
YA
SB
TB
UB
WB
YB
SC
TC
UC
WC
YC
SD
TD
UD
WD
YD
SE
TE
UE
WE
YE
SF
TF
UF
WF
YF
SG
TG
UG
WG
YG
SH
TH
UH
WH
YH
SI
TI
UI
WI
YI
SJ
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
SL
TL
UL
WL
YL
SM
TM
UM
WM
YM
SN
TN
UN
WN
YN
SO
TO
UO
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
UQ
WQ
YQ
SR
TR
UR
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
SV
TV
UV
WV
YV
SW
TW
UW
WW
YW
SX
TX
UX
WX
YX
SY
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Yb
Sc
Tc
Uc
Wc
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
Ye
Sf
Tf
Uf
Wf
Yf
Sg
Tg
Ug
Wg
Yg
Sh
Th
Uh
Wh
Yh
Si
Ti
Ui
Wi
Yi
Sj
Tj
wU2()}
;
#undef Value_t
#undef P
#endif /*FP_TEST_WANT_GMP_INT_TYPE */
#ifdef FP_TEST_WANT_LONG_DOUBLE_TYPE
#define N(x) (APP(x,l))
#define P(x) N(x##.0)
#define Value_t long double
namespace
cpp_01unit_operators
oJ2
Modl(qD,&z=vars[1];return
fmodl(x,z)wV2
cpp_02unit_functions
oJ2
Acoshl(aT
x+qW2-1.0l
oI2
Acoshl_deg
g42
fp_acosh(x
oI2
Acosl(qJ
acosl
m8
Acosl_deg
g42
acosl(x
oI2
Asinhl(aT
x+qW2+1.0l
oI2
Asinhl_deg
g42
fp_asinh(x
oI2
Asinl(qJ
asinl
m8
Asinl_deg
g42
asinl(x
oI2
Atan2l(qH
qX2
x
oX3
Atan2l_deg(qH
r2d(qX2
x,y
oI2
Atanhl(aT(1.0l+x)/(1.0l-x))*0.5l;}
q0
Atanl(qJ
atanl
m8
Atanl_deg
g42
atanl(x
oI2
Cbrtl(qJ
fp_cbrt
m8
Ceill(qJ
ceill
m8
Coshl(qJ
coshl
m8
Coshl_deg(qJ
coshl
mM
Cosl(qJ
cosl
m8
Cosl_deg(qJ
cosl
mM
Exp2l(dO2
x*fp_const_log2<q0>(oI2
Expl(qJ
expl
m8
Floorl(qJ
floorl
m8
Hypotl(qH
qW2+y*y);}
q0
Log2l(aT
x)*1.4426950408889634073599246810018921374266l;}
q0
Log10l(qJ
log10l
m8
Logl(aT
x);}
q0
Pow_negl(qH
powl(-x*0.25l
oX3
Pow_posl(qH
powl(x
oX3
Sinhl(qJ
sinhl
m8
Sinhl_deg(qJ
sinhl
mM
Sinl(qJ
sinl
m8
Sinl_deg(qJ
sinl
mM
Sqrtl(qJ
sqrtl
m8
Tanhl(qJ
tanhl
m8
Tanhl_deg(qJ
tanhl
mM
Tanl(qJ
tanl
m8
Tanl_deg(qJ
tanl
mM
Truncl(qJ
fp_trunc(x)wV2
cpp_03unit_constants
oJ2
E_ld(dO2
x*0.0l+1.0l);}
q0
L2_ld(aT
x*0.0l+2.0l);}
q0
L10_ld(aT
x*0.0l+10.0l);}
q0
Pi_ld(qJ
qX2
x*0.0l,-1.0l)wV2
cpp_10optimizer_bytecode
oJ2
Acoshl(aT
1.1l+sqrtl(1.1l*1.1l-1.0l)dQ
Acoshl_deg
g42
fp_acosh(1.1l)dQ
Acosl(qJ
acosl(0.7l
dQ
Acosl_deg
g42
acosl(0.7l)dQ
Asinhl(aT
1.1l+sqrtl(1.1l*1.1l+1.0l)dQ
Asinhl_deg
g42
fp_asinh(1.1l)dQ
Asinl(qJ
asinl(0.7l
dQ
Asinl_deg
g42
asinl(0.7l)dQ
Atan2l(qJ
qX2
5.0l,wT2
Atan2l_deg
g42
qX2
5.0l,4.0l)dQ
Atanhl(aT(1.0l+0.7l)/(1.0l-0.7l))*0.5l+x;}
q0
Atanl(qJ
atanl
dP2
Atanl_deg
g42
atanl(1.1l)dQ
Cbrtl(qJ
fp_cbrt
dP2
Ceill(qJ
ceill
dP2
Coshl(qJ
coshl
dP2
Coshl_deg(qJ
coshl(qR1
Cosl(qJ
cosl
dP2
Cosl_deg(qJ
cosl(qR1
Exp2l(dO2
1.1l*0.693147180559945309417232121458176568075500134l
dQ
Expl(dO2
1.1l
dQ
Floorl(qJ
floorl
dP2
Hypotl(qJ
sqrtl(5.0l*5.0l+4.0l*wT2
Invsincostan(qH
x/oY1
x/w01
x/a91+x*oY1
x*w01
x*a91+1.0l/oY1
1.0l/w01
1.0l/a91+1.0l*oY1
1.0l*w01
1.0l*a91;}
q0
Log2l(aT
1.1l)*1.4426950408889634073599246810018921374266l+x;}
q0
Log10l(qJ
log10l
dP2
Logl(aT
1.1l
dQ
Pow_negl(qJ
powl(-0.25l,wT2
Pow_posl(qJ
powl(1.1l,7.1l
dQ
Sinhl(qJ
sinhl
dP2
Sinhl_deg(qJ
sinhl(qR1
Sinl(qJ
sinl
dP2
Sinl_deg(qJ
sinl(qR1
Sqrtl(qJ
sqrtl
dP2
Tanhl(qJ
tanhl
dP2
Tanhl_deg(qJ
tanhl(qR1
Tanl(qJ
tanl
dP2
Tanl_deg(qJ
tanl(qR1
Truncl(qJ
1.0l+x;}
}
template<>const
wU2
RegressionTests<q0>::Tests[]={Uj
Wj
Yj
Sk
Tk
Uk
Wk
Yk
Sl
Tl
Ul
Wl{2,-11,11,N(0.3),qM
Modl,h7
qB",z"
,g6"modl"
,"x%z"
}
,Yl
Sm
Tm
Um
Wm
Ym
Sn{1,1,400,w2
Acoshl
qF"/acoshl"
,w12
hA
1,400,g71
Acoshl_deg
qF"/acoshl_deg"
,w12
g21
w8
Acosl
qF"/acosl"
,"acos"
g21,oW1
Acosl_deg
qF"/acosl_deg"
,"acos"
g21
w8
Asinhl
qF"/asinhl"
,oW3
g21,oW1
Asinhl_deg
qF"/asinhl_deg"
,oW3
g21
w8
Asinl
qF"/asinl"
,"a"
a51}
,{oU1,oW1
Asinl_deg
qF"/asinl_deg"
,"a"
a51}
,{2,-wW1
w8
Atan2l,h7
wA"/atan2l"
,hZ2"(x"
wA1{2,-wW1,oW1
Atan2l_deg,h7
wA"/atan2l_deg"
,hZ2"(x"
wA1{oU1
w8
Atanhl
qF"/atanhl"
,"atanh"
hA
oX1
w2
Atanl
qF"/atanl"
,"atan"
hA
oX1
g71
Atanl_deg
qF"/atanl_deg"
,"atan"
hA-50000,50000,1000
w8
Cbrtl
qF"/cbrtl"
,"cbrt"
hA-10,10
oD1
w8
Ceill
qF"/ceill"
,"ceil"
hA-140,140,w2
Coshl
qF"/coshl"
,"cosh"
hA-140,140,g71
Coshl_deg
qF"/coshl_deg"
,"cosh"
hA-aS
w8
Cosl
qF"/cosl"
,"cos"
hA
w63
Cosl_deg
qF"/cosl_deg"
,"cos"
hA-90,90,N(0.01)w8
Exp2l
qF"/exp2l"
,"exp2"
hA-90,90,N(0.01)w8
Expl
qF"/expl"
,"exp"
hA-10,10
oD1
w8
Floorl
qF"/floorl"
,"floor(x)"
}
,{2,-wW1
w8
Hypotl,h7
wA"/hypotl"
,"hypot(x"
wA1
Tn
Un{1,dC1
Log2l
qF"/log2l"
,"log2"
hA
dC1
Log10l
qF"/log10l"
,"log10"
hA
dC1
Logl
qF"/logl"
,aQ1
T4
U4{2,1,20,1
w8
Pow_negl,h7
wA"/pow_negl"
,"pow(-x*0.25,y"
mQ{2,N(0.01),4,N(0.05)w8
Pow_posl,h7
wA"/pow_posl"
,qC2
wA1{1,oX1
w2
Sinhl
qF"/sinhl"
,gA2
hA
oX1
g71
Sinhl_deg
qF"/sinhl_deg"
,gA2
hA-aS
w8
Sinl
qF"/sinl"
,a51}
,{1,w63
Sinl_deg
qF"/sinl_deg"
,a51}
,{1,0,100000,1000
w8
Sqrtl
qF"/sqrtl"
,"sqrt"
hA-aS
w8
Tanhl
qF"/tanhl"
,"tanh"
hA
w63
Tanhl_deg
qF"/tanhl_deg"
,"tanh"
hA
N(-1.3),N(1.3),N(0.05)w8
Tanl
qF"/tanl"
,"tan"
hA-89,89
oD1,oW1
Tanl_deg
qF"/tanl_deg"
,"tan"
hA
oX1
w2
Truncl
qF"/truncl"
,"trunc"
hA
0,dE
E_ld,w5"e_ld"
,o83"naturalnumber"
aB2
L2_ld,w5"l2_ld"
,o83"logtwo"
aB2
L10_ld,w5"l10_ld"
,o83"logten"
aB2
Pi_ld,w5"pi_ld"
,o83"pi"
}
,W4
YO1
SP1
Wn
Y4
Yn
So
To
S5
W5
Uo{1
w7
Acoshl
aQ"acoshl"
,w12"("
w4
Acoshl_deg
aQ"acoshl_deg"
,w12
dN2
Wo{1
w7
Acosl
aQ"acosl"
,"acos"
wR2,dL2
Acosl_deg
aQ"acosl_deg"
,"acos(0.7)+x"
}
,Yo
Sp
Tp{1
w7
Asinhl
aQ"asinhl"
,oW3"("
w4
Asinhl_deg
aQ"asinhl_deg"
,oW3
dN2
Up{1
w7
Asinl
aQ"asinl"
,"asin("
a81,dL2
Asinl_deg
aQ"asinl_deg"
,"asin("
a81
qL
Atan2l
aQ"atan2l"
,hZ2"(5,4"
gH,dL2
Atan2l_deg
aQ"atan2l_deg"
,hZ2"(5,4)+x"
}
,Wp{1
w7
Atanhl
aQ"atanhl"
,"atanh"
wR2
qL
Atanl
aQ"atanl"
,"atan("
w4
Atanl_deg
aQ"atanl_deg"
,"atan("
qP1
Cbrtl
aQ"cbrtl"
,"cbrt("
qP1
Ceill
aQ"ceill"
,"ceil"
dN2
Yp
SQ1
TQ1
UQ1
WQ1
YQ1
SR1
TR1
UR1
WR1
YR1
SS1
TS1
US1
WS1
YS1
ST1
TT1
UT1
WT1
YT1
SU1
TU1
UU1
WU1
YU1
SV1
TV1
UV1
WV1
YV1
SW1
TW1
UW1
WW1
YW1
SX1
TX1
UX1
WX1
YX1
SY1
TY1
UY1
WY1
YY1
SZ1{1
w7
Coshl
aQ"coshl"
,"cosh("
w4
Coshl_deg
aQ"coshl_deg"
,"cosh("
qP1
Cosl
aQ"cosl"
,"cos("
w4
Cosl_deg
aQ"cosl_deg"
,"cos"
dN2
Sq
Tq
Y5
Uq
Wq
Yq
S6
T6
U6
W6
Sr
Sb1
Tb1
Tr{1
w7
Exp2l
aQ"exp2l"
,"exp2"
dN2
Ur
Wr{1
w7
Expl
aQ"expl"
,"exp"
dN2
Yr
Ss
Ts{1
w7
Floorl
aQ"floorl"
,"floor"
dN2
Us
Ub1
Wb1
Yb1
Sc1
Tc1
Uc1
Yc1
Sd1
Td1
Ud1
Wd1
Yd1{1
w7
Hypotl
aQ"hypotl"
,"hypot(5,4)+x"
}
,Ws
Ys
St
Tt
Ut
Wt
Yt
Y6{2,N(-0.7),N(0.7),N(0.28)qL
Invsincostan,h7
dH1"invsincostan"
,"x/sin("
dZ1"cos("
dZ1"tan("
dZ1"csc("
dZ1"sec("
dZ1"cot(y) +  1/sin(y)"
w62"cos(y)"
w62"tan(y)"
w62"csc(y)"
w62"sec(y)"
w62"cot(y"
mQ{1
w7
Log2l
aQ"log2l"
,"log2("
qP1
Log10l
aQ"log10l"
,"log10("
qP1
Logl
aQ"logl"
,"log"
dN2
Uf1
Wf1
Yf1
S7
T7
U7
W7
Y7
Su
S8
Tu
T8
U8
W8
Wj1
Yj1
Y8
S9
T9
U9
W9
Y9
SA
TA
UA{1
w7
Pow_negl,qG"/pow_negl"
,"pow(-0.25,4"
gH
qL
Pow_posl,qG"/pow_posl"
,"pow(1.1, 7.1)+x"
}
,Uu
Wu
Yu
Sv
Tv
Uv
Wv
Yv
Sw
Uk1
Wk1
Yk1
Sl1
Tl1
Ul1
Wl1
Yl1
Sm1{1
w7
Sinhl
aR1"hl"
,gA2"("
w4
Sinhl_deg
aR1"hl_deg"
,gA2"("
qP1
Sinl
aR1"l"
,"sin("
w4
Sinl_deg
aR1"l_deg"
,"sin("
w6
WA
YA
SB
TB
UB
WB
Tw
Uw
Ww{1
w7
Sqrtl
aQ"sqrtl"
,"sqrt"
dN2
Un1{1
w7
Tanhl
aQ"tanhl"
,"tanh("
w4
Tanhl_deg
aQ"tanhl_deg"
,"tanh("
qP1
Tanl
aQ"tanl"
,"tan("
w4
Tanl_deg
aQ"tanl_deg"
,"tan("
qP1
Truncl
aQ"truncl"
,"trunc"
dN2
YB
SC
Yw
Uo1
Wo1
TC
Sx
UC
Tx
Ux
Wx
Yx
SD
Sy
TD
UD
WD
Ty
Uy
Wy
YD
SE
TE
UE
WE
YE
SF
TF
UF
Yy
Sz
Tz
Uz
Wz
Yz
WF
YF
SG
TG
UG
WG
YG
SH
TH
S_
T_
U_
W_
Y_
S01
UH
WH
YH
SI
TI
UI
WI
YI
SJ
T01
U01
W01
Y01
S11
T11
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
U11
W11
Y11
S21
T21
U21
SL
TL
UL
WL
YL
SM
TM
UM
WM
W21
Y21
S31
T31
U31
W31
YM
SN
TN
UN
WN
YN
SO
TO
UO
Y31
S41
T41
U41
W41
Y41
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
S51
T51
U51
W51
Y51
S61
Yx1
Sy1
T61
U61
W61
Ty1
Uy1
UQ
WQ
YQ
SR
TR
UR
Yy1
Sz1
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
TV
UV
WV
YV
SW
TW
UW
WW
Y61
S71
YW
T71
U71
W71
Y71
SX
S81
TX
T81
U81
W81
UX
WX
YX
SY
Y81
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Yb
Sc
S91
T91
U91
W91
Y91
SA1
TA1
UA1
Tc
Uc
Wc
WA1
YA1
SB1
TB1
UB1
WB1
Uz1
Wz1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
YB1
SC1
TC1
UC1
WC1
YC1
SD1
TD1
UD1
WD1
YD1
SE1
TE1
Ye
Sf
Tf
Uf
Wf
Yf
UE1
Tg
WE1
YE1
SF1
TF1
Ug
UF1
WF1
YF1
SG1
TG1
UG1
WG1
YG1
SH1
TH1
UH1
WH1
YH1
SI1
Wg
Yg
TI1
Sh
Th
Uh
UI1
WI1
Wh
YI1
SJ1
TJ1
UJ1
Yh
WJ1
YJ1
SK1
TK1
Si
Ti
UK1
WK1
YK1
SL1
TL1
UL1
WL1
YL1
SM1
TM1
UM1
WM1
Ui
YM1
SN1
TN1
UN1
WN1
Wi
YN1
wU2()}
;
#undef Value_t
#undef N
#undef P
#endif /*FP_TEST_WANT_LONG_DOUBLE_TYPE */
#ifdef FP_TEST_WANT_LONG_INT_TYPE
#define P(x) (APP(x,l))
#define Value_t long
template<>const
wU2
RegressionTests<q0>::Tests[]={S
T
U
W
Y
S1
T1
U1
W1
Y1
S2
T2
U2
W2
Y2
S3
T3
U3
W3
Y3
S4
T4
U4
W4
WO1
TP1
Y4
S5
T5
U5
W5
UP1
WP1
YP1
UQ1
UU1
WU1
YU1
UY1
WY1
TZ1
UZ1
WZ1
YZ1
Sa1
Ta1
Ua1
Wa1
Ya1
Y5
S6
T6
U6
W6
Sb1
Tb1
Ub1
Sc1
Yc1
Ud1
Te1
Y6
Sg1
S7
T7
Ug1
Wg1
Yg1
U7
W7
Uh1
Wh1
Y7
Yh1
S8
Ui1
T8
U8
W8
Sj1
Wj1
Yj1
Sk1
Y8
S9
T9
U9
W9
Y9
SA
TA
UA
Tk1
WA
YA
SB
TB
UB
WB
Tm1
Um1
Sn1
Tn1
Un1
YB
SC
TC
UC
Yo1
Sp1
Tp1
Up1
Wp1
Yp1
Sq1
Tq1
Uq1
Wq1
Yq1
Sr1
Tr1
Ur1
Wr1
Yr1
Ss1
Ts1
Us1
Ws1
Ys1
St1
Tt1
Ut1
Wt1
Yt1
Su1
Tu1
Uu1
Wu1
Yu1
Sv1
Tv1
Uv1
Wv1
Yv1
Sw1
Tw1
Uw1
Ww1
Yw1
Sx1
Tx1
Ux1
Wx1
WC
YC
SD
TD
UD
WD
YD
SE
TE
UE
WE
YE
SF
TF
UF
WF
YF
SG
TG
UG
WG
YG
SH
TH
UH
WH
YH
SI
TI
UI
WI
YI
SJ
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
SL
TL
UL
WL
YL
SM
TM
UM
WM
YM
SN
TN
UN
WN
YN
SO
TO
UO
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
Yx1
Sy1
Ty1
Uy1
UQ
WQ
YQ
SR
TR
UR
Yy1
Sz1
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
SV
TV
UV
WV
YV
SW
TW
UW
WW
YW
SX
TX
UX
WX
YX
SY
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Yb
Sc
Tc
Uc
Wc
Uz1
Wz1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
Ye
Sf
Tf
Uf
Wf
Yf
Sg
Yz1
T_1
U_1
W_1
Y_1
Tg
Ug
Wg
Yg
Sh
Th
Uh
Wh
Yh
Si
Ti
Ui
Wi
Yi
Sj
Tj
wU2()}
;
#undef Value_t
#undef P
#endif /*FP_TEST_WANT_LONG_INT_TYPE */
#ifdef FP_TEST_WANT_MPFR_FLOAT_TYPE
#define N(x) (q0(#x,0))
#define P(x) N(x)
#define Value_t MpfrFloat
static
const
q0
aA1("0.5"
,0),oK2("0.25"
,0),mflit1_1("1.1"
,0),mflit0_7("0.7"
,0),mflit1_6("1.6"
,0),mflit1_5("1.5"
,0),mflitm1_1("-1.1"
,0),mflitm1_6("-1.6"
,0),mflitm1_5("-1.5"
,0),mflitm0_25("-0.25"
,0),wL2("7.1"
,0),mflit0_015625("0.015625"
,0),mflit0_0625(gT3,0),mflit5_0625("5.0625"
,0),mflit1_2("1.2"
,0),mflitm5_1("-5.1"
,0),mflitm7_1("-7.1"
,0),mflit5_1("5.1"
,0),mflit_5(".5"
,0),mflit3_1("3.1"
,0),mflit4e2("4e2"
,0),mflit3_5("3.5"
,0),mflit57_295779513082320877("57.295779513082320877"
,0),mflit0_2("0.2"
,0),mflit7_5("7.5"
,0),dU2("2.5"
,0),mflit1_3("1.3"
,0),mflit1_4("1.4"
,0),mflit1_7("1.7"
,0),mflit1_8("1.8"
,0),mflit1_25("1.25"
,0),mflit1_75("1.75"
,0),mflit2_25("2.25"
,0),mflit3_3("3.3"
,0),mflit0_6("0.6"
,0),mflit2_1("2.1"
,0),mflit1_75e21("1.75e21"
,0);namespace
cpp_01unit_operators
oJ2
And_d
oT2(q31?fp_abs(y)>=aA1:q0(0
oI2
Div_d(qH(x-oK2)/y;}
q0
Divmul_d
hM
x*y*x*x/z*(x-oK2);}
q0
Modm(qD,&z=vars[1];return
x%z;}
q0
Not_d(qJ
w21<aA1);}
q0
Notnot_d
wI2
q31);}
q0
Or_d(qH
w21<aA1?fp_abs(y)>=aA1:q0(1))wV2
cpp_02unit_functions
oJ2
Acoshm(qC
acosh
m8
Acoshm_deg(dQ2
acosh(x
oI2
Acosm(qC
acos
m8
Acosm_deg(dQ2
acos(x
oI2
Asinhm(qC
asinh
m8
Asinhm_deg(dQ2
asinh(x
oI2
Asinm(qC
asin
m8
Asinm_deg(dQ2
asin(x
oI2
Atan2m
oT2::atan2(x
oX3
Atan2m_deg(qH
w11
atan2(x,y
oI2
Atanhm(qC
atanh
m8
Atanm(qC
atan
m8
Atanm_deg(dQ2
atan(x
oI2
Cbrtm(qC
cbrt
m8
Ceilm(qC
ceil
m8
Coshm(qC
cosh
m8
Coshm_deg(qC
cosh
mM
Cosm(qC
cos
m8
Cosm_deg(qC
cos
mM
Exp2m(qC
exp2
m8
Expm(qC
exp
m8
Floorm(qC
floor
m8
Hypotm
oT2::hypot(x
oX3
If_d
hM
q31?y:z;}
q0
Int(qJ
fp_floor(x+aA1);}
q0
Log2m(qC
log2
m8
Log10m(qC
log10
m8
Logm(qC
log
m8
Pow_negm
oT2::pow(-x*oK2
oX3
Pow_posm
oT2::pow(x
oX3
Sinhm
oZ3
m8
Sinhm_deg
oZ3
mM
Sinm
w53
m8
Sinm_deg
w53
mM
Sqrtm(qC
sqrt
m8
Tanhm(qC
tanh
m8
Tanhm_deg(qC
tanh
mM
Tanm(qC
tan
m8
Tanm_deg(qC
tan
mM
Truncm(qC
trunc(x)wV2
cpp_03unit_constants
oJ2
E_mpfr(qC
exp(x
oS2
1
oI2
L2_mpfr(qC
log(x
oS2
2
oI2
L10_mpfr(qC
log(x
oS2
10
oI2
Pi_mpfr(qC
atan2(x*q0(0),-q0(1))wV2
cpp_10optimizer_bytecode
oJ2
Acoshm(qC
acosh(gV
Acoshm_deg(dQ2
acosh(dD
Acosm(qC
acos(wX1
Acosm_deg(dQ2
acos(mflit0_7)dQ
Asinhm(qC
asinh(gV
Asinhm_deg(dQ2
asinh(dD
Asinm(qC
asin(wX1
Asinm_deg(dQ2
asin(mflit0_7)dQ
Atan2m(qC
atan2(q0(dR2
dQ
Atan2m_deg(dQ2
atan2(q0(dR2)dQ
Atanhm(qC
atanh(wX1
Atanm(qC
atan(gV
Atanm_deg(dQ2
atan(dD
Cbrtm(qC
cbrt(gV
Ceilm(qC
ceil(gV
Coshm(qC
cosh(gV
Coshm_deg(qC
cosh(dS2
Cosm(qC
cos(gV
Cosm_deg(qC
cos(dS2
Exp2m(qC
exp2(gV
Expm(qC
exp(gV
Floorm(qC
floor(gV
Hypotm(qC
hypot(q0(dR2
dQ
Int(qJ
x+(((((fp_int(mflit1_1)aB1
mflit1_6))aB1
mflit1_5))aB1
mflitm1_1))aB1
mflitm1_6))aB1
mflitm1_5
oI2
Log2m(qC
log2(gV
Log10m(qC
log10(gV
Logm(qC
log(gV
Pow_negm(qC
pow(mflitm0_25,q0(4)dQ
Pow_posm(qC
pow(mflit1_1,wL2
dQ
Powhalf(qJ
qP
aA1);}
q0
Powminushalf(qJ
qP-aA1);}
q0
Sinhm
oZ3(gV
Sinhm_deg
oZ3(dS2
Sinm
w53(gV
Sinm_deg
w53(dS2
Sqrtm(qC
sqrt(gV
Tanhm(qC
tanh(gV
Tanhm_deg(qC
tanh(dS2
Tanm(qC
tan(gV
Tanm_deg(qC
tan(dS2
Truncm
wI2
1)+x
wV2
cpp_20optimizer_optimizations
oJ2
Cmpeq_pow_imm_negneg
mA
gD2
Cmpeq_pow_imm_negpos
mA
qP
gE2
Cmpeq_pow_imm_pospos_base
mA
gF2
Cmpge_pow_imm_negneg(mC
gD2
Cmpge_pow_imm_negpos(mC
qP
gE2
Cmpge_pow_imm_pospos_base(mC
gF2
Cmpgt_pow_imm_negneg
oB2
gD2
Cmpgt_pow_imm_negpos
oB2
qP
gE2
Cmpgt_pow_imm_pospos_base
oB2
gF2
Cmple_pow_imm_negneg(qJ
hR1
gD2
Cmple_pow_imm_negpos(qJ
hR1
qP
gE2
Cmple_pow_imm_pospos_base(qJ
hR1
gF2
Cmplt_pow_imm_negneg(wR1
gD2
Cmplt_pow_imm_negpos(wR1
qP
gE2
Cmplt_pow_imm_pospos_base(wR1
gF2
Cmpne_pow_imm_negneg(q22
gD2
Cmpne_pow_imm_negpos(q22
qP
gE2
Cmpne_pow_imm_pospos_base(q22
gF2
Cmpzz_pow_imm_negneg
wI2
gU1
gK
aF
gK
aU
gK
aV
gK
aX
gK
mN
gD2
Cmpzz_pow_imm_negpos
wI2
gU1
qP
gY
aF
qP
gY
aU
qP
gY
aV
qP
gY
aX
qP
gY
mN
qP
gE2
Cmpzz_pow_imm_pospos_base
wI2
gU1
gL
aF
gL
aU
gL
aV
gL
aX
gL
mN
gF2
Ifabsnot
hM
aR
q41!=q0(0)?z:y;}
q0
Posnot(h52
q41;}
q0
Posnotnot(qJ
fp_notNot(q41;}
q0
Powmulimm_fnen(wZ(q0(-8)oI2
Powmulimm_fnep(wZ(q0(4)oI2
Powmulimm_fnfn(h72(mflitm5_1)*x,(mflitm7_1
oI2
Powmulimm_fnfp(wZ
wL2);}
q0
Powmulimm_fpfp(qH
fp_pow(mflit5_1*x*y,wL2)wV2
cpp_50regressions
oJ2
t42(qH
g72
x*x)+qY2(fp_pow(y*y,oK2))+fp_hypot(x,y)wV2
cpp_99misc
oJ2
t2
wI2
2)*x
aE2
x)/mflit_5+q0(2)-fp_sin(x)w43
m8
t3
hM
fp_and(mD,y),q12
y,x)oH
1
oH
2)-mflit3_1*mflit4e2/mflit_5+x*x+y*y+z*z+mZ1,x)+fp_or(y
oX3
t9
hM
mflit1_5+x*y-q0(2
oH
4)/q0(8)+z+z+z+z+x/(y*z);}
q0
t11
hM(-x-x)+y+hR
fp_pow(mflit1_1,z
oI2
t22(qH(mflit3_5*q0(2)oH
10)*(x*oC3-(fp_sin(y)*q0(2)oH
100)*((x
dT2-(y*oC3)*q0(2
oH
5)/(q0(2)dT2+fp_pow(mflit1_1,x
dT2+fp_pow(qZ2
q0(2),x
dT2;}
q0
t26_deg
h62
d2r(x))+fp_cos(d2r(x*mflit1_5))+r2d(fp_asin(x/q0(110)))+r2d
w73
x/q0(120)oI2
t30(qH
x-y*q0(1)+fp_mod(x,y)+x/fp_pow(y,mflit1_1)+qK
2),oC3+fp_mod(q0(5),oC3+qP
fp_pow(y,q0(0)))+qP
aA1);}
q0
t32
hM
x+y/y-aX1
3),q0(4))-x-aY1
4),oC3+aY1
3),q0(4))-aX1
4),q0(3)oH
0)+(z*wY1(x-q0(2
oH
2))+(x*aA1
dT2+y*q0(0)+fp_min(fp_min(aX1
4),x),q0(1)),fp_min(x,fp_min(fp_min(y,q0(4)),z)))+fp_max(fp_max(aY1
4),x),q0(1)),a22
fp_max(y,q0(4)),z)))+(fp_abs(wY1
fp_acos(wY1
fp_asin(wY1
fp_atan(wY1
a62
mflit1_1)+fp_cos
gG2
fp_cosh
gG2
fp_floor(mflit1_1)+hR
wY1
fp_sin
gG2
fp_sinh
gG2
qR2
wY1
fp_tanh(wY1
a71
q0(1),q0(1)))+(x-(y-z))+(x+y)+(x*y)+a22
x,a22
x,x))))*-q0(1)+(z-z
oH
1)/fp_sin(x/q0(q02
fp_cos(y/q0(q02
qR2
z/q0(5))+gU
q0(1)/qR2
z/q0(q02
fp_sin(y/q0(q02
mH/q0(5)))+hR
q0(30)+x)*hR
q0(40)+y)/hR
q0(50)+z)aE2
x/mflit57_295779513082320877)+fp_asin(x/q0(10))*mflit57_295779513082320877+fp_floor(-x
oH
1)/a62
x)+wV1
5)*mflit0_2)+(-x+-x+-x+-x+-x+-x);}
q0
t37
wI2
5)+mflit7_5*q0(8)/q0(3)-qK
2),q0(4))*q0(2)+fp_mod(q0(7),q0(2)oH
4
dQ
t38
hM
fp_asinh(x)+qY2
fp_acosh(y+oC3+dU2*fp_atanh(z);}
q0
t39
hM
fp_sin(x+qS1)-mH
aE2
y*mflit1_5))+z*z*z
w43(z*z*z-x*x-y*y)-qS1
w43(x+qS1)+x*y*z+x*y*dU2+x*y*z*mH)+x*y*mH)+x*z*mH)+y*z*dU2+(x*y*z*mH)-x*y*z-y*mH)-x*z*y+x*y+x*z-mH)*x);}
q0
t44(h72
x
oI
8))+qZ2
h21
x
oI
7
wM1
h21
x*x
oI
6))+mflit1_3
g52
oI
5))+mflit1_4
g52*x
oI
6))+qY2
fp_pow(a4*x*x
oI
4))+mflit1_6
g52*x*x*x
oI
3))+mflit1_7
g52*a4
oI
2))+mflit1_8*(g72
fp_pow(fp_abs(-g72
x)),oC3
oI2
t45(h72
x
oI
7))+qZ2
h21
x*x
oI
5
wM1
fp_pow(a4*x
oI
3
oI2
t46(qH
fp_abs(fp_floor
w73
x
oH
4)))+qZ2
fp_abs(fp_floor
w73
y)+mflit1_5))g82
fp_acos(x),w73
y)-q0(10)wM1
aY1-4
qD1
x))+mflit1_3*aX1
9
qD1
x)-q0(9
oI2
t47(qH
mflit1_25*(g02+g62)+qY2(aI2
y)-aI2-y))+mflit1_75*((g62+g02)/q0(2)oH
2)*((g62-g02)/q0(2))+mflit2_25*(d72
y)+fp_sinh(y
oI2
t48(qJ
fp_sinh((hR
x)/q0(5
oH
1))*q0(5
wM1
d72(hR
x)/hR
q0(2)oH
1))*hR
q0(2)))+oU2
fp_or(aR
x),oU2
x/q0(4))oI2
t49(qJ
a71
q0(0),x)+qK-4)*(x-q0(100)),mflit3_3);}
q0
t52(qJ
x+(q0(1
oH
2
oH
3
oH
4)-q0(5)-q0(6)-q0(7)-q0(8))/q0(3
oH
4)*(q0(1)aE2
q0(2))+fp_cos(q0(4)*q0(5
oH
6))/q0(2))+fp_cos(aA1)*qR2
mflit0_6+mflit0_2)-mflit1_1/hR
mflit2_1)*g72
mflit3_3)+qK
2),q0(3
oI2
t55(qH
fp_less(qP
mflit1_2),q0(0))g82
fp_pow(y,dU2),q0(0)oH
2)*aO*x,q0(0)oH
3)*fp_less(fp_pow(y,oC3,q0(0)oH
4)*fp_less(qP
q0(4)),q0(0
oI2
t56(qJ
fp_mod(mflit1_75e21,x);}
}
template<>const
wU2
RegressionTests<q0>::Tests[]={Uj
Wj
Yj
Sk
Tk
Uk
Wk
Yk
Sl
Tl
Ul
Wl{2,-11,11,N(0.3),qM
Modm,h7
qB",z"
,g6"modm"
,"x%z"
}
,Yl
Sm
Tm
Um
Wm
Ym
Sn{1,1,400,w2
Acoshm
qF"/acoshm"
,w12
hA
1,400,g71
Acoshm_deg
qF"/acoshm_deg"
,w12
g21
w8
Acosm
qF"/acosm"
,"acos"
g21,oW1
Acosm_deg
qF"/acosm_deg"
,"acos"
g21
w8
Asinhm
qF"/asinhm"
,oW3
g21,oW1
Asinhm_deg
qF"/asin"
dM2
oW3
g21
w8
Asinm
qF"/asinm"
,"a"
a51}
,{oU1,oW1
Asinm_deg
qF"/asin"
dV2"a"
a51}
,{2,-4,4,N(0.15)w8
Atan2m,h7
wA"/atan2m"
,hZ2"(x"
wA1{2,-4,4,N(0.15),oW1
Atan2m_deg,h7
wA"/atan2m_deg"
,hZ2"(x"
wA1{oU1
w8
Atanhm
qF"/atanhm"
,"atanh"
hA
oX1
w2
Atanm
qF"/atanm"
,"atan"
hA
oX1
g71
Atanm_deg
qF"/atanm_deg"
,"atan"
hA-50000,50000,1000
w8
Cbrtm
qF"/cbrtm"
,"cbrt"
hA-10,10
oD1
w8
Ceilm
qF"/ceilm"
,"ceil"
hA-140,140,w2
Coshm
qF"/coshm"
,"cosh"
hA-140,140,g71
Coshm_deg
qF"/coshm_deg"
,"cosh"
hA-aS
w8
Cosm
qF"/cosm"
,"cos"
hA
w63
Cosm_deg
qF"/cosm_deg"
,"cos"
hA-90,90,N(0.02)w8
Exp2m
qF"/exp2m"
,"exp2"
hA-90,90,N(0.02)w8
Expm
qF"/expm"
,"exp"
hA-10,10
oD1
w8
Floorm
qF"/floorm"
,"floor(x)"
}
,{2,-wW1
w8
Hypotm,h7
wA"/hypotm"
,"hypot(x"
wA1
Tn
Un{1,dC1
Log2m
qF"/log2m"
,"log2"
hA
dC1
Log10m
qF"/log10m"
,"log10"
hA
dC1
Logm
qF"/logm"
,aQ1
T4
U4{2,1,20,1
w8
Pow_negm,h7
wA"/pow_negm"
,"pow(-x*0.25,y"
mQ{2,N(0.01),4,N(0.05)w8
Pow_posm,h7
wA"/pow_posm"
,qC2
wA1{1,oX1
w2
Sinhm
qF"/sinhm"
,gA2
hA
oX1
g71
Sinhm_deg
qF"/sin"
dM2
gA2
hA-aS
w8
Sinm
qF"/sinm"
,a51}
,{1,w63
Sinm_deg
qF"/sin"
dV2
a51}
,{1,0,100000,1000
w8
Sqrtm
qF"/sqrtm"
,"sqrt"
hA-aS
w8
Tanhm
qF"/tanhm"
,"tanh"
hA
w63
Tanhm_deg
qF"/tanhm_deg"
,"tanh"
hA
N(-1.3),N(1.3),N(0.05)w8
Tanm
qF"/tanm"
,"tan"
hA-89,89
oD1,oW1
Tanm_deg
qF"/tanm_deg"
,"tan"
hA
oX1
w2
Truncm
qF"/truncm"
,"trunc"
hA
0,dE
E_mpfr,w5"e_mpfr"
,o83"naturalnumber"
aB2
L2_mpfr,w5"l2_mpfr"
,o83"logtwo"
aB2
L10_mpfr,w5"l10_mpfr"
,o83"logten"
aB2
Pi_mpfr,w5"pi_mpfr"
,o83"pi"
}
,W4
Wn
Y4
Yn
So
To
S5
W5
Uo{1
w7
Acoshm
aQ"acoshm"
,w12"("
w4
Acoshm_deg
aQ"acoshm_deg"
,w12
dN2
Wo{1
w7
Acosm
aQ"acosm"
,"acos"
wR2,dL2
Acosm_deg
aQ"acosm_deg"
,"acos(0.7)+x"
}
,Yo
Sp
Tp{1
w7
Asinhm
aQ"asinhm"
,oW3"("
w4
Asinhm_deg
aQ"asin"
dM2
oW3
dN2
Up{1
w7
Asinm
aQ"asinm"
,"asin("
a81,dL2
Asinm_deg
aQ"asin"
dV2"asin("
a81
qL
Atan2m
aQ"atan2m"
,hZ2"(5,4"
gH,dL2
Atan2m_deg
aQ"atan2m_deg"
,hZ2"(5,4)+x"
}
,Wp{1
w7
Atanhm
aQ"atanhm"
,"atanh"
wR2
qL
Atanm
aQ"atanm"
,"atan("
w4
Atanm_deg
aQ"atanm_deg"
,"atan("
qP1
Cbrtm
aQ"cbrtm"
,"cbrt("
qP1
Ceilm
aQ"ceilm"
,"ceil"
dN2
Yp{1
w7
Coshm
aQ"coshm"
,"cosh("
w4
Coshm_deg
aQ"coshm_deg"
,"cosh("
qP1
Cosm
aQ"cosm"
,"cos("
w4
Cosm_deg
aQ"cosm_deg"
,"cos"
dN2
Sq
Tq
Y5
Uq
Wq
Yq
W6
Sr
Tr
Ur{1
w7
Exp2m
aQ"exp2m"
,"exp2"
dN2
Wr
Yr
Ss
Ts{1
w7
Expm
aQ"expm"
,o02
qP1
Floorm
aQ"floorm"
,"floor"
dN2
Us{1
w7
Hypotm
aQ"hypotm"
,"hypot(5,4)+x"
}
,Ws
Ys
St
Tt
Ut
Wt
Yt
Y6{1
w7
Log2m
aQ"log2m"
,"log2("
qP1
Log10m
aQ"log10m"
,"log10("
qP1
Logm
aQ"logm"
,"log"
dN2
S7
T7
U7
W7
Y7
Su
S8
Tu
T8
U8
W8
Y8
S9
T9
U9
W9
Y9
SA
TA
UA{1
w7
Pow_negm,qG"/pow_negm"
,"pow(-0.25,4"
gH
qL
Pow_posm,qG"/pow_posm"
,"pow(1.1, 7.1)+x"
}
,Uu
Wu
Yu
Sv
Tv
Uv
Wv
Yv
Sw{1
w7
Sinhm
aR1"hm"
,gA2"("
w4
Sinhm_deg
aR1
dM2
gA2"("
qP1
Sinm
aR1"m"
,"sin("
w4
Sinm_deg
aR1
dV2"sin("
w6
WA
YA
SB
TB
UB
WB
Tw
Uw
Ww{1
w7
Sqrtm
aQ"sqrtm"
,w72
qP1
Tanhm
aQ"tanhm"
,"tanh("
w4
Tanhm_deg
aQ"tanhm_deg"
,"tanh("
qP1
Tanm
aQ"tanm"
,"tan("
w4
Tanm_deg
aQ"tanm_deg"
,"tan("
qP1
Truncm
aQ"truncm"
,"trunc"
dN2
Yw
TC
Sx
UC
Tx
Ux
Wx
Yx
SD
Sy
TD
UD
WD
Ty
Uy
Wy
YD
SE
TE
UE
WE
YE
SF
TF
UF
Yy
Sz
Tz
Uz
Wz
Yz
WF
YF
SG
TG
UG
WG
YG
SH
TH
S_
T_
U_
W_
Y_
S01
UH
WH
YH
SI
TI
UI
WI
YI
SJ
T01
U01
W01
Y01
S11
T11
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
U11
W11
Y11
S21
T21
U21
SL
TL
UL
WL
YL
SM
TM
UM
WM
W21
Y21
S31
T31
U31
W31
YM
SN
TN
UN
WN
YN
SO
TO
UO
Y31
S41
T41
U41
W41
Y41
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
S51
T51
U51
W51
Y51
S61
T61
U61
W61
UQ
WQ
YQ
SR
TR
UR
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
TV
UV
WV
YV
SW
TW
UW
WW
Y61
S71
YW
T71
U71
W71
Y71
SX
S81
TX
T81
U81
W81
UX
WX
YX
SY
Y81
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Yb
Sc
S91
T91
U91
W91
Y91
SA1
TA1
UA1
Tc
Uc
Wc
WA1
YA1
SB1
TB1
UB1
WB1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
YB1
SC1
TC1
UC1
WC1
YC1
SD1
TD1
UD1
WD1
YD1
SE1
TE1
Tf
Uf
Wf
Yf
UE1
Tg
WE1
YE1
SF1
TF1
Ug
UF1
WF1
YF1
SG1
TG1
UG1
WG1
YG1
SH1
TH1
UH1
WH1
YH1
SI1
Wg
Yg
TI1
Sh
Th
Uh
UI1
WI1
Wh
YI1
SJ1
TJ1
UJ1
Yh
WJ1
YJ1
SK1
TK1
Si
Ti
UK1
WK1
YK1
SL1
TL1
UL1
WL1
YL1
SM1
TM1
UM1
WM1
Ui
YM1
SN1
TN1
UN1
WN1
Wi
YN1
wU2()}
;
#undef Value_t
#undef N
#undef P
#endif /*FP_TEST_WANT_MPFR_FLOAT_TYPE */
