// $Id: mesh_ucd_support.C,v 1.11 2004-01-03 15:37:43 benkirk Exp $

// The libMesh Finite Element Library.
// Copyright (C) 2002-2004  Benjamin S. Kirk, John W. Peterson
  
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
  
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
  
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA



// C++ includes
#include <iomanip>
#include <fstream>


// Local includes
#include "mesh_base.h"
#include "elem.h"
#include "face_quad4.h"
#include "face_tri3.h"
#include "cell_tet4.h"
#include "cell_hex8.h"
#include "cell_prism6.h"

void MeshBase::read_ucd(const std::string& name)
{
  std::ifstream in (name.c_str());

  this->read_ucd (in);

  return;
}




void MeshBase::read_ucd (std::istream &in)
{
  /**
   * Clear any existing mesh data
   */
  this->clear();
  
  // Check input buffer
  assert (in.good());

  // UCD doesn't work in 1D
  assert (_dim != 1);

  skip_comment_lines (in, '#');

  unsigned int nNodes=0, nElem=0, dummy=0;

  in >> nNodes   // Read the number of nodes from the stream
     >> nElem    // Read the number of elements from the stream
     >> dummy
     >> dummy
     >> dummy;


  // Read the nodal coordinates. Note that UCD format always
  // stores (x,y,z), and in 2D z=0. We don't need to store this,
  // however.  So, we read in x,y,z for each node and make a point
  // in the proper way based on what dimension we're in
  {
    unsigned int vn=0;
    Real x=0., y=0., z=0.;

    // Reserve space in the nNodes vector to avoid unnecessary
    // allocations
    _nodes.resize (nNodes);
    
    
    for (unsigned int i=0; i<nNodes; i++)
      {
	in >> vn  // Point number
	   >> x   // x-coordinate value
	   >> y   // y-coordinate value
	   >> z;  // z-coordinate value

	// Build the node
	this->node_ptr(i) = Node::build(x,y,z,i);
      }
  }


  
  // Read the elements from the stream. Notice that the UCD node-numbering
  // scheme is 1-based, and we just created a 0-based scheme above
  // (which is of course what we want). So, when we read in the nodal
  // connectivity for each element we need to take 1 off the value of
  // each node so that we get the right thing.
  {
    unsigned int material_id=0, node=0;
    std::string type;
    
    // Reserve space in the appropriate vector to avoid unnecessary
    // allocations
    _elements.resize (nElem);
    

    
    for (unsigned int i=0; i<nElem; i++)
      {
	in >> dummy        // Cell number, means nothing to us
	   >> material_id  // doesn't mean anything at present, might later
	   >> type;        // string describing cell type:
	                   // either tri, quad, tet, or hex for the
	                   // obvious cases


	                   // Now read the connectivity.
	if (type == "quad")
	  _elements[i] = new Quad4;
	else if (type == "tri")
	  _elements[i] = new Tri3;
	else if (type == "hex")
	  _elements[i] = new Hex8;
	else if (type == "tet")
	  _elements[i] = new Tet4;
	else if (type == "prism")
	  _elements[i] = new Prism6;
	else
	  error();
	
	
	for (unsigned int n=0; n<this->elem(i)->n_nodes(); n++)
	  {
	    in >> node; // read the current node
	    node -= 1;  // UCD is 1-based, so subtract

	    assert (node < n_nodes());
	    
	    this->elem(i)->set_node(n) =
	      this->node_ptr(node); // assign the node
	  }
      }
  }  
}




void MeshBase::write_ucd(const std::string& name)
{
  std::ofstream out (name.c_str());

  this->write_ucd (out);

  return;
}




void MeshBase::write_ucd (std::ostream &out)
{
  assert (out);
  
  // UCD doesn't work in 1D
  assert (_dim != 1);
  
  // Write header to stream
  {
    out << "# This file was generated by:" << std::endl
	<< "#" << std::endl
	<< "# $Id: mesh_ucd_support.C,v 1.11 2004-01-03 15:37:43 benkirk Exp $" << std::endl
	<< "#" << std::endl
	<< "# For a description of the UCD format see the AVS Developer's guide."
	<< std::endl
	<< "#" << std::endl;
  }

  
  // Write the mesh info
  out << this->n_nodes() << " "
      << this->n_elem() << " "
      << " 0 0 0"  << std::endl;

  // Write the coordinates
  for (unsigned int n=0; n<this->n_nodes(); n++)
    {
      out << (n+1) << "\t";
      this->point(n).write_unformatted(out);
    }

  // Write the elements
  for (unsigned int e=0; e<this->n_elem(); e++)
    {
      out << (e+1) << " 0 " << this->elem(e)->type() << "\t"; 
      this->elem(e)->write_ucd_connectivity(out);
    }  
}

