#define d03 " "gR3
#define hZ3 -40,40,
#define hY3 *fp_or(
#define hX3 )/a;}q3
#define hW3 w8" "
#define hV3 40000.0
#define hU3 "if(x"dQ
#define hT3 "-125)"
#define hS3 o91") "
#define hR3 wF1"1 > "
#define hQ3 a22"1 < "
#define hP3 wE1"0 > "
#define hO3 a12"0 < "
#define hN3 " "h43 g32
#define hM3 "!x * !y"
#define hL3 "!x & !y"
#define hK3 "!x | !y"
#define hJ3 " <= "
#define hI3 "if("oM1
#define hH3 "if("qT1
#define hG3 "abs"g91
#define hF3 "abs"dR1
#define hE3 "y,x,y)"
#define hD3 +x+x+x+x
#define hC3 " != "
#define hB3 " >= "
#define hA3 oL1"1"hB3
#define h93 dG2"1"hJ3
#define h83 oK1"0"hB3
#define h73 dF2"0"hJ3
#define h63 "floor"wS2
#define h53 "acos"g91
#define h43 "ceil"qH1
#define h33 "0.0625)"
#define h23 "25"g31
#define h13 "y,"oT2
#define h03 dT"   "
#define gZ3 (d2r(1.1))dT1
#define gY3 hF3" "
#define gX3 "acos"oV o0
#define gW3 "sin(x))"},
#define gV3 mL1 gM3 gM3" "
#define gU3 "-0.015625)"
#define gT3 "-125"g31
#define gS3 " +"gM3
#define gR3 "(5.0625 "
#define gQ3 d2"5.0625 "
#define gP3 "y, 0,1"g31
#define gO3 "y,y,x)"
#define gN3 "0.0625"g31
#define gM3 "    "
#define gL3 "-0.015625"g31
#define gK3 q0(0 wX
#define gJ3 q0(10l)
#define gI3 qX1 gX)
#define gH3 1 qN q4
#define gG3 "x,y,z"
#define gF3 1 qN,g1
#define gE3 q0(3))
#define gD3 oC,oM
#define gC3 " "qQ1
#define gB3 mflit7_1
#define gA3 qA2},{1
#define g93 qC qA(
#define g83 N(.1),
#define g73 fp_exp2(
#define g63 gL;}q0
#define g53 +gO qU
#define g43 Asinf_deg
#define g33 (x,fp_min(
#define g23 Acosf_deg
#define g13 q0(3l)
#define g03 0]=(x),
#define qZ3 &y oI2;q0
#define qY3 -6,6,1 qN
#define qX3 1,-10,10,
#define qW3 q4 Negneg
#define qV3 Asinhf_deg
#define qU3 Acoshf_deg
#define qT3 ;}}namespace
#define qS3 ));}q0
#define qR3 " + 32"
#define qQ3 qN qL
#define qP3 oC dA2
#define qO3 N(3.0,0.0),
#define qN3 N(-6.0,0.0),wI
#define qM3 using namespace FUNCTIONPARSERTYPES;q0
#define qL3 *q0(2
#define qK3 4.0l hW
#define qJ3 4.0f hW
#define qI3 qT expf
#define qH3 q0(2.0l
#define qG3 0l);}q3
#define qF3 d92 mP2
#define qE3 qO q0(hA
#define qD3 +fp_or(
#define qC3 oF 1l),
#define qB3 g01 gX)
#define qA3 ")*0"},
#define q93 Abseq0,
#define q83 ")*5"},
#define q73 ")*a"},
#define q63 ")/a"},
#define q53 Sqrneq0
#define q43 qA2" +"
#define q33 ") + ("
#define q23 Gt1_abs
#define q13 Gt0_abs
#define q03 Ge1_abs
#define mZ2 Ge0_abs
#define mY2 Cmp_sqr
#define mX2 Cmp_neg
#define mW2 Cmp_add
#define mV2 Absneq0
#define mU2 ")"wK1
#define mT2 " + 1/"
#define mS2 N(.5)qN
#define mR2 "acosh"
#define mQ2 "*z) +"
#define mP2 "<=y &"
#define mO2 4 d4 gR
#define mN2 ",-"mL1
#define mM2 m6" | "
#define mL2 m6" & "
#define mK2 Sqr_yxx
#define mJ2 Sqr_xnx
#define mI2 Sqr_nxx
#define mH2 "x))"},
#define mG2 Absnzlt
#define mF2 Absnzge
#define mE2 "abs(b"
#define mD2 "abs(a"
#define mC2 N(.2)qQ3
#define mB2 fp_sin(
#define mA2 fp_pow(
#define m92 ))+gP
#define m82 "x",oE
#define m72 ,0,1,gR
#define m62 {1 m72
#define m52 {1,-g0
#define m42 ")+(x"
#define m32 "exp"g91
#define m22 m8" | "
#define m12 "exp("
#define m02 " "h61
#define aZ2 hC3
#define aY2 ,"x*"
#define aX2 aY2"0+"
#define aW2 mflit2_5
#define aV2 d2r(wO
#define aU2 "y) +"
#define aT2 w11"ex"
#define aS2 oC",y"wN
#define aR2 aZ qN qB
#define aQ2 {1 d4 gR
#define aP2 hD-1,1,
#define aO2 qB1 dZ
#define aN2 fp_not(z
#define aM2 aI2 hQ
#define aL2 qI oA hQ hV1
#define aK2 qI oA-hQ
#define aJ2 o9 qI hQ hV1
#define aI2 o9 qI-
#define aH2 q0(4l qF
#define aG2 q0(4l))
#define aF2 q0(4l qM
#define aE2 ,hP gX
#define aD2 fp_cosh(
#define aC2 qO x+mD1
#define aB2 "a,b",oE
#define aA2 "atan2"
#define a92 q23,
#define a82 q13,
#define a72 q03,
#define a62 mZ2,
#define a52 mV2,
#define a42 "(x*"h62
#define a32 Multodiv
#define a22 " > 1"oU
#define a12 " > 0"oU
#define a02 o3"-5)"
#define wZ2 o3"5)"
#define wY2 q4 Negadd
#define wX2 "(1))"
#define wW2 gM3"8"
#define wV2 qI1"))*"
#define wU2 "x+-x+-"
#define wT2 "log(x+"
#define wS2 "(x)"aP1
#define wR2 " + "oF1"*"
#define wQ2 "7/2) +"
#define wP2 "(x*"qF1
#define wO2 N(0.25),
#define wN2 "!!x *"
#define wM2 "180/pi"
#define wL2 "sinh"
#define wK2 oC",y,z"
#define wJ2 "x!=y) +"
#define wI2 "x"oG1
#define wH2 Xaddnot,
#define wG2 Lt_or_ne
#define wF2 Lt_or_le
#define wE2 Lt_or_gt
#define wD2 Lt_or_ge
#define wC2 Lt_or_eq
#define wB2 Le_or_ne
#define wA2 Le_or_eq
#define w92 L_notnot
#define w82 L_mulneg
#define w72 L_mulabs
#define w62 Ifmerge,
#define w52 Gt_or_ne
#define w42 Gt_or_le
#define w32 Gt_or_ge
#define w22 Gt_or_eq
#define w12 Ge_or_ne
#define w02 Ge_or_le
#define oZ2 Ge_or_eq
#define oY2 o91 g31
#define oX2 wG"4)"
#define oW2 a51")"
#define oV2 "x"o31
#define oU2 "x,y"q6"/"
#define oT2 "x"mI1
#define oS2 "x",dX
#define oR2 mG2,
#define oQ2 "1,4,0"
#define oP2 mF2,
#define oO2 Xxsqrdup
#define oN2 Sqr_yxnx
#define oM2 Sqr_ynxx
#define oL2 "x"gW
#define oK2 (fp_not(x
#define oJ2 N(2.0,0.0)
#define oI2 =vars[1]
#define oH2 g41"*("
#define oG2 gY;}q0
#define oF2 q0(0l)
#define oE2 h8;}q0
#define oD2 ))gI x
#define oC2 ",if("
#define oB2 " + (x*"
#define oA2 -400,400,
#define o92 mflit1_5)
#define o82 mflit1_5*
#define o72 mflit0_25
#define o62 atan2l(
#define o52 sqrtl(x*x
#define o42 atan2f(
#define o32 sqrtf(x*x
#define o22 "^1506"},
#define o12 +fp_less(
#define o02 qB1 x*x*x
#define dZ2 x+q0(6l))
#define dY2 /gX a2-gF
#define dX2 (1.1)dT1
#define dW2 q0(1))
#define dV2 (q0(5),q0(4)
#define dU2 /gX a2+gF
#define dT2 q0(0l qU
#define dS2 dY1 q0::
#define dR2 )+q0(
#define dQ2 /gX)+mE
#define dP2 gO m92 x
#define dO2 ))+oF 0l),
#define dN2 q0(7l))
#define dM2 fp_tan(
#define dL2 g01 q0(2l
#define dK2 qX1 q0(2l
#define dJ2 qW1 q0(2l
#define dI2 "(x) +"
#define dH2 q4 Immsub
#define dG2 hB3"1"oU
#define dF2 hB3"0"oU
#define dE2 ")+x+("
#define dD2 "   if(x"
#define dC2 "(x^2"g31
#define dB2 "pow(x"
#define dA2 ",y,z",oM
#define d92 "*(x"
#define d82 10,10,dU1
#define d72 Nor2plus,
#define d62 Lt_and_ne
#define d52 Lt_and_le
#define d42 Lt_and_gt
#define d32 Lt_and_ge
#define d22 m8" & "
#define d12 Lt_and_eq
#define d02 Le_and_ne
#define hZ2 Le_and_eq
#define hY2 (qG3
#define hX2 Ifmerge2,
#define hW2 Gt_and_ne
#define hV2 Gt_and_le
#define hU2 Gt_and_ge
#define hT2 Gt_and_eq
#define hS2 Ge_and_ne
#define hR2 Ge_and_le
#define hQ2 Ge_and_eq
#define hP2 hB3"6"a7
#define hO2 " > 6)"oS
#define hN2 ")/log("
#define hM2 (fp_exp(
#define hL2 " < 6)"a6
#define hK2 " < 6"g31
#define hJ2 " > 6"g31
#define hI2 " = 6"g31
#define hH2 Notnotnot
#define hG2 Dupminmax
#define hF2 N(0.25)qN
#define hE2 0,qH"/sin"
#define hD2 ,0 wY
#define hC2 hY1 1.1f
#define hB2 +(m91)+aY))*
#define hA2 fp_and(x
#define h92 ((dI1/mL)*
#define h82 q0(5l qU
#define h72 fp_sqrt(
#define h62 "5"g31
#define h52 ">-4)"w9
#define h42 gM3"16"
#define h32 "(1.0"
#define h22 "pi/180"
#define h12 hS1" | "
#define h02 hS1" & "
#define gZ2 "(-x)"},
#define gY2 "abs(x)"
#define gX2 +mflit1_1*
#define gW2 q0(0.5l)
#define gV2 const q0
#define gU2 mflit1_1)+
#define gT2 y),oY,y wX
#define gS2 x,fp_max(
#define gR2 fp_max(q0(
#define gQ2 fp_min(q0(
#define gP2 +fp_min(x,
#define gO2 1l qM dI1,
#define gN2 qS oF2,
#define gM2 qM oF2,
#define gL2 wX dB 1l),
#define gK2 wX dB 0l),
#define gJ2 gC hP gX
#define gI2 gC h1 dI1
#define gH2 gC hC gX
#define gG2 gC-q0(2l
#define gF2 gC-gX)
#define gE2 "log(x)"},
#define gD2 Cmp_mulpos
#define gC2 ">4)"w9
#define gB2 Cmp_mulneg
#define gA2 "(x*z+17)"
#define g92 N(.1)qQ3
#define g82 ,true qB
#define g72 mA2 dZ
#define g62 mA2 x*x*x
#define g52 qT mA2
#define g42 qT fp_not(
#define g32 "   10*"dX
#define g22 "sub(sub("
#define g12 Nand2plus,
#define g02 Ifmerge2b,
#define qZ2 hC3"6)"dV
#define qY2 hJ3"6)"a8
#define qX2 hC3"6"g31
#define qW2 hJ3"6"g31
#define qV2 hB3"6"g31
#define qU2 wG"-4)"
#define qT2 Notnotnot2
#define qS2 Dupxmuladd
#define qR2 Dupminmax3
#define qQ2 Dupminmax2
#define qP2 Dupaddmul7
#define qO2 "z+y+z+y+"
#define qN2 "(1.1"h0
#define qM2 x oK 1l);}q3
#define qL2 ))+qB2 oF2,
#define qK2 q0(fp_abs(x)
#define qJ2 wV1),q0(4l
#define qI2 -fp_int(
#define qH2 dM2 y)
#define qG2 fp_atan2(
#define qF2 d7 x:y dR2
#define qE2 d7 y:aU
#define qD2 qT q0(hA
#define qC2 ,q0(4l qU
#define qB2 fp_equal(
#define qA2 "sin(x)"
#define q92 "acos(x)"
#define q82 ") + 32"
#define q72 "<-4) "aM
#define q62 "=-4) "aL
#define q52 "sin("wQ
#define q42 "(x>4"g31
#define q32 (q0(0.0l))+
#define q22 fp_pow hM2 mF),
#define q12 2,-4,4,gR
#define q02 g81"*y)"
#define mZ1 qV1"*y)"
#define mY1 N(0.5)qN
#define mX1 mflit0_7 hW
#define mW1 wX gG x
#define mV1 wX gZ x
#define mU1 gG2 qM
#define mT1 N(4.0,0.0),
#define mS1 " cos(x)"},
#define mR1 Cmp_sqr_neg
#define mQ1 N(.15)qQ3
#define mP1 ",max(x,ma"
#define mO1 oC q6"/pow"
#define mN1 2,2,gF3
#define mM1 Xaddnotnot,
#define mL1 "x)) +"
#define mK1 qT fp_nequal(
#define mJ1 ,"("gY2
#define mI1 ",y"g31
#define mH1 Addconstmul
#define mG1 "dupminmax"
#define mF1 N(1.0,0.0),
#define mE1 q0(5 wX 1)/
#define mD1 y;}q3
#define mC1 "*("wJ
#define mB1 *fp_and(
#define mA1 (oG,q0(4l)qU
#define m91 mB2 x
#define m81 (mB2 y),aY)):
#define m71 mB2 y)+
#define m61 ")+x"},{1 gS
#define m51 qB2 x,y
#define m41 aY*q0(1.5l))
#define m31 fp_or(y,z)
#define m21 x),h1 gX
#define m11 x),hC gX
#define m01 d2r(x qU
#define aZ1 ,"(sin(x)"
#define aY1 h5")"
#define aX1 h4"x)"
#define aW1 "<=-4) "aN
#define aV1 "*((-x)"
#define aU1 "<4) "aM
#define aT1 "=4) "aL
#define aS1 "*("aJ
#define aR1 hW3" 32"
#define aQ1 "*("aI
#define aP1 ",ceil(x))+"
#define aO1 hK1 dQ"))"},
#define aN1 "cmpeq_"
#define aM1 "cbrt(x^6"
#define aL1 ")), int("
#define aK1 Mixedminmax,
#define aJ1 Mergemulabs,
#define aI1 3 d4 gR
#define aH1 Cmpzz_minmax
#define aG1 ")"aZ2 hL1 dV
#define aF1 ")"hB3 hL1 o41
#define aE1 ") > "hL1 oS
#define aD1 ")"hJ3 hL1 a8
#define aC1 ") < "hL1 a6
#define aB1 Cmpne_minmax
#define aA1 Cmplt_minmax
#define a91 Cmple_minmax
#define a81 Cmpgt_minmax
#define a71 Cmpge_minmax
#define a61 wG"4*y)"
#define a51 wG"-4*y"
#define a41 Cmpeq_minmax
#define a31 Addnegmulpos
#define a21 Addnegmulneg
#define a11 2 oJ 2 qN,q2
#define a01 d4 gH3
#define wZ1 Absnotnotnot
#define wY1 qE3 x*
#define wX1 ))+mflit1_2*
#define wW1 q0(5l wX 1l)/
#define wV1 q0(5l)
#define wU1 userDefFuncSqr<q0>((
#define wT1 (1.1f hW
#define wS1 aU2" x/"
#define wR1 ((x*q0(gA
#define wQ1 fp_abs(a)
#define wP1 {1,q8
#define wO1 w8 h42
#define wN1 w8 wW2
#define wM1 w8 gM3"4"
#define wL1 w8 gM3"2"
#define wK1 gS3"2"
#define wJ1 ,d8"pow"
#define wI1 0l)gB x:-x wX
#define wH1 x),-gX)
#define wG1 {2 d4 gF3
#define wF1 " < 1"oH2
#define wE1 " < 0"oH2
#define wD1 10,10,gF3
#define wC1 If_join_mul2,
#define wB1 If_join_add2,
#define wA1 Cmpzz_add_imm
#define w91 Cmpne_add_imm
#define w81 Cmplt_add_imm
#define w71 Cmple_add_imm
#define w61 Cmpgt_add_imm
#define w51 Cmpge_add_imm
#define w41 Cmpeq_add_imm
#define w31 q4 Xaddnotnot
#define w21 0,q7"/pow"
#define w11 ,0 gT
#define w01 w11"cmp_ex"
#define oZ1 w11"asin"
#define oY1 fp_and(y,z)
#define oX1 " + "oE1"*"
#define oW1 x*x,q0(25l
#define oV1 {2,q9
#define oU1 "!=4"g31
#define oT1 "(x"hC3"y"g31
#define oS1 "(x = y"g31
#define oR1 " & (y+2"g31
#define oQ1 "x"q6"/"
#define oP1 d7 y:x dR2
#define oO1 q0(25l qU
#define oN1 gQ"cmpgt_"
#define oM1 "1,1,1))"
#define oL1 hJ3"1"oH2
#define oK1 hJ3"0"oH2
#define oJ1 "<=4) "aN
#define oI1 -10,10,gH3
#define oH1 "!=-2"g31
#define oG1 ",y",oM
#define oF1 "sin(x-pi"
#define oE1 "sin(x+pi"
#define oD1 "((-5.1)*x*y)"
#define oC1 " "gJ",2)"
#define oB1 " "gJ",3)"
#define oA1 gQ"cmplt_"
#define o91 "(x"hJ3"y"
#define o81 If_extract_mul
#define o71 If_extract_min
#define o61 If_extract_add
#define o51 If_extract_abs
#define o41 qY"0010 *"
#define o31 "_rev",dX
#define o21 Addmulconstmul
#define o11 fp_lessOrEq(
#define o01 ,4,N(0.05)qN qB
#define dZ1 (1.1l hW
#define dY1 qT r2d(
#define dX1 ,gQ"cmpne_"
#define dW1 ,gQ"cmple_"
#define dV1 ,gQ"cmpge_"
#define dU1 1 qQ3
#define dT1 +x;}q3
#define dS1 "*(if(1,1,1)"
#define dR1 oV"*("gY2
#define dQ1 ,d8"powx"
#define dP1 "(2))"},
#define dO1 {2 oJ 2 qN q4
#define dN1 ",y"q6"/pow"
#define dM1 "*(5+"dX
#define dL1 mA2 mflit1_1
#define dK1 N(0.01)g82
#define dJ1 fp_not(-fp_not(
#define dI1 q0(1l)
#define dH1 {1,N(-5.0,0.0),N(5.0,0.0),oJ2 qN,q2
#define dG1 ") + cos(x-pi*"
#define dF1 "(1.1^x*4.1"g31
#define dE1 {1 oJ N(0.41)qN q4
#define dD1 ")^(1/"
#define dC1 If_extract_mul2
#define dB1 If_extract_mul1
#define dA1 If_extract_add2
#define d91 If_extract_add1
#define d81 fp_notNot(x
#define d71 gE1 y,q0(6l
#define d61 fp_abs(x qU
#define d51 " "gJ",-2)"
#define d41 " "gJ",-3)"
#define d31 },{1,0,1,1 qN,hJ
#define d21 wV1;}q3
#define d11 (0x0001)*fp_less(
#define d01 fp_abs(x)>=mflit0_5
#define hZ1 (x);}q0
#define hY1 qT logf(
#define hX1 fp_int(q0(
#define hW1 (wV1,g13)+x
#define hV1 /g13
#define hU1 "*(if(1,0,0)"
#define hT1 qI gD),q0(4l
#define hS1 ,"(x > y)"
#define hR1 qI gD),-q0(4l
#define hQ1 o2"(abs(x))"
#define hP1 o2"(x)"
#define hO1 Cmpzz_minmax_rev
#define hN1 N(-.1),g83 N(0.01)qN q4
#define hM1 "("dN{1 gS
#define hL1 "(y+6))"
#define hK1 " if(x"
#define hJ1 Cmpzz_addadd_imm
#define hI1 Cmpne_minmax_rev
#define hH1 Cmpne_addadd_imm
#define hG1 Cmplt_minmax_rev
#define hF1 Cmplt_addadd_imm
#define hE1 Cmple_minmax_rev
#define hD1 Cmple_addadd_imm
#define hC1 Cmpgt_minmax_rev
#define hB1 Cmpgt_addadd_imm
#define hA1 Cmpge_minmax_rev
#define h91 Cmpge_addadd_imm
#define h81 Cmpeq_minmax_rev
#define h71 Cmpeq_addadd_imm
#define h61 dY"+y)"
#define h51 -460,100,8 qN,qG
#define h41 40,40,3 qN,qG
#define h31 "((1/   abs(b))*"
#define h21 If_extract_or2_l,
#define h11 If_extract_or1_l,
#define h01 Cmpzz_mul_imm_pos
#define gZ1 Cmpzz_mul_imm_neg
#define gY1 Cmpzz_add_reduce,
#define gX1 Cmpne_mul_imm_pos
#define gW1 Cmpne_mul_imm_neg
#define gV1 Cmpne_add_reduce,
#define gU1 Cmplt_mul_imm_pos
#define gT1 Cmplt_mul_imm_neg
#define gS1 Cmplt_add_reduce,
#define gR1 Cmple_mul_imm_pos
#define gQ1 Cmple_mul_imm_neg
#define gP1 Cmple_add_reduce,
#define gO1 Cmpgt_mul_imm_pos
#define gN1 Cmpgt_mul_imm_neg
#define gM1 Cmpgt_add_reduce,
#define gL1 Cmpge_mul_imm_pos
#define gK1 Cmpge_mul_imm_neg
#define gJ1 Cmpge_add_reduce,
#define gI1 Cmpeq_mul_imm_pos
#define gH1 Cmpeq_mul_imm_neg
#define gG1 Cmpeq_add_reduce,
#define gF1 N(0.1)g82
#define gE1 +q0(4l)+
#define gD1 fp_acos(x
#define gC1 log(x+sqrt(x*x
#define gB1 3,N(0.0,0.0)qV
#define gA1 "pow(-4,y))"
#define g91 "(x))"},
#define g81 " "wG"4"
#define g71 d2r(1.1l)hW
#define g61 d2r(1.1f)hW
#define g51 d2r(x qS3
#define g41 ") +  8"
#define g31 ")"},
#define g21 d7 x:y);}q3
#define g11 fp_greater(
#define g01 fp_tanh(x),
#define qZ1 x*x),-q0(16l
#define qY1 x*x),q0(16l
#define qX1 fp_asin(x),
#define qW1 gD1),
#define qV1 " "wG"-4"
#define qU1 hB x+y+x+x-z dT1
#define qT1 "1,0,0)) +"
#define qS1 "*(sinh(x)"
#define qR1 "*(atan(x)"
#define qQ1 "(pow(2,x)"
#define qP1 If_extract_or2_nl,
#define qO1 If_extract_or1_nl,
#define qN1 If_extract_and2_l,
#define qM1 If_extract_and1_l,
#define qL1 fp_less(y,q0(1l
#define qK1 o11 q0(
#define qJ1 {1,-4,4,gH3
#define qI1 "(sin(x)+cos(y"
#define qH1 "(x),floor(x))+"
#define qG1 ") + cos(x+pi*"
#define qF1 "if(1,-1,0))"},
#define qE1 6,6,mY1,qG
#define qD1 N(1.0,0.0)qN,q2
#define qC1 m91)+mflit1_2)
#define qB1 )*mA2
#define qA1 fp_not(x)*fp_not(y)
#define q91 ,oF2 gB-x:x wX
#define q81 *x*x,-q0(125l
#define q71 gQ"cmpzz_pow"
#define q61 "pow(1.5,x))"
#define q51 If_extract_and2_nl,
#define q41 If_extract_and1_nl,
#define q31 Cmpzz_mulmul_imm_pos
#define q21 Cmpzz_mulmul_imm_neg
#define q11 Cmpne_mulmul_imm_pos
#define q01 Cmpne_mulmul_imm_neg
#define mZ Cmplt_mulmul_imm_pos
#define mY Cmplt_mulmul_imm_neg
#define mX Cmple_mulmul_imm_pos
#define mW Cmple_mulmul_imm_neg
#define mV Cmpgt_mulmul_imm_pos
#define mU Cmpgt_mulmul_imm_neg
#define mT Cmpge_mulmul_imm_pos
#define mS Cmpge_mulmul_imm_neg
#define mR Cmpeq_mulmul_imm_pos
#define mQ Cmpeq_mulmul_imm_neg
#define mP qW1 q0(0l
#define mO gM3" "
#define mN +q0(0x0020)*qB2
#define mM N(0.01)qN qB
#define mL fp_abs(b)
#define mK x),-q0(2l
#define mJ qK"if_ex"
#define mI ,N(-1.0,0.0)qV
#define mH gG3 q6"/"
#define mG 2,-2,2,gR
#define mF q0(1.0l)
#define mE fp_cos(x
#define mD N(0.1)qN qB
#define mC log(1.1+sqrt(1.1*
#define mB {1,-36,36,gH3
#define mA {1,0,4,N(0.1)qN q4
#define m9 )*(wV1+(
#define m8 ,"(x < y)"
#define m7 ">=4"q82
#define m6 "(x"hB3"y)"
#define m5 +q0(0x0010)*fp_nequal(
#define m4 qI 1.1l),x)*q0(4.1l qU
#define m3 +q0(0x0008)*fp_greaterOrEq(
#define m2 +q0(0x0004)*g11
#define m1 qT logl(
#define m0 N(1e-6),400,mD
#define aZ 40000,40000,5
#define aY fp_cos(y
#define aX x*x,-q0(125l qU
#define aW 0,q7"/sin"
#define aV aT,q0(4l)gB
#define aU x);}q3
#define aT fp_less(x
#define aS q0(4l)*d5
#define aR g4 q0(4l
#define aQ g4-q0(4l
#define aP "^6.1))"
#define aO ">=-2) +  32"
#define aN "+   8"
#define aM "+   4"
#define aL "+   2"
#define aK "<-2)"gS3"4"
#define aJ "exp2(x)"
#define aI "exp(x)"
#define aH "*((1-x+x+5)"
#define aG -10,10,N(0.8)qN q4
#define aF "x,y",g9
#define aE +q0(0x0002)*o11
#define aD fp_or oK2),fp_not(y
#define aC (fp_truth(
#define aB -2,2,1 qN,qG
#define aA {2,-g0
#define a9 d4 2 qN,q5
#define a8 qY"0004 *"
#define a7 ")"o41
#define a6 qY"0002 *"
#define a5 qX"+y+"qO2"z"
#define a4 oC,"03unit_constants/"
#define a3 fp_and oK2),fp_not(y
#define a2 )+m91
#define a1 d81)*fp_notNot(y)
#define a0 ">-2) +"h42
#define wZ "<=-2) +"wW2
#define wY ,qH"/"
#define wX )dR2
#define wW gA1},
#define wV mA2(q0(-5.1l))*x
#define wU {1 oJ N(0.1)qN q4
#define wT qO mA2(mflitm5_1)*x*y,
#define wS N(-1.25),N(1.25),hF2
#define wR qW-gX),q0(0.0625l
#define wQ "0.75)) +"
#define wP wK2 q6"/"
#define wO mflit1_1)hW
#define wN ,"02unit_functions"
#define wM 0 aS2
#define wL A_very_long_variable_name_1
#define wK "*((x*x)"
#define wJ "log2(x)"
#define wI N(6.0,0.0),N(0.5,0.0)qN,qG
#define wH q61},
#define wG "((x*"
#define wF {2 m72
#define wE {2,qJ
#define wD 1 a01
#define wC dI1),mB2 y+dI1 qU
#define wB qI 2l),x),qI-4l),y
#define wA qT fp_greaterOrEq(
#define w9 " +   16"
#define w8 "(2)) +"
#define w7 N(-7.25),N(7.25),mY1,qG
#define w6 ,q0(1)/q0(
#define w5 d4 mY1 q4
#define w4 fp_exp(x),-q0(4l
#define w3 "((-1.061)^x))"
#define w2 "(1.061^(x/3)))"
#define w1 ,dI1/q0(
#define w0 5.0625l),qI 1.5l),x
#define oZ 4l)*y,q0(6l
#define oY fp_nequal(x
#define oX m91),q0(
#define oW fp_abs(x),q0(
#define oV "(x))"gS3"4"
#define oU mU2"*("
#define oT g73 x),-q0(4l
#define oS qY"0008 *"
#define oR "sin(x))"gS3"4*(sin(x)"
#define oQ h4"(x/3))"
#define oP {2,q8
#define oO {2,3,5,mY1,q2
#define oN ,"0x0001 *"
#define oM "99misc/"
#define oL x=vars[2],&y=vars[3]qA(dW aC y gB
#define oK *oF2+y*q0(0l dR2
#define oJ ,-3,3,
#define oI 1 oJ mY1 q4
#define oH N(0.5),3,mY1 q4
#define oG g11 x
#define oF gX*qK1
#define oE "50regressions/"
#define oD 0 w11
#define oC ,0,"x"
#define oB 0 a4
#define oA gD hV1),qI
#define o9 qI-gD),
#define o8 /gX*x*-qJ2
#define o7 /gX*x*qJ2
#define o6 fp_exp(x),fp_exp(gX
#define o5 3 mI
#define o4 "*(tanh(x)"
#define o3 "*((x/2*x*"
#define o2 "*(log"
#define o1 "*(a"qA2
#define o0 "*("q92
#define dZ x*x*x*x*x
#define dY "((x+4"
#define dX "if(x"
#define dW fp_truth(x gB
#define dV " +  0x0020 * "
#define dU o11 x
#define dT "(x^-6.1)) +"
#define dS wR qU
#define dR (x wX 4l)*fp_less(
#define dQ "<4, cos(y),sin(y+1"
#define dP "((((x*5/2)+x*x-2))"
#define dO ",y,z"q6"/if_ex"
#define dN "1.1)+x"},
#define dM qW-g13),-q0(0.015625l
#define dL N(-3.0,0.0),qO3 qD1
#define dK wB qU
#define dJ fp_sinh(x),fp_sinh(gX
#define dI g73 x),g73 gX
#define dH fp_atan(x),fp_atan(gX
#define dG 1l)-x+x+qJ2
#define dF "*(log10(x)"
#define dE N(-7.25,0.0),N(7.25,0.0),N(0.5,0.0)qN,qG
#define dD w0 qU
#define dC (x hD3 hD3+x+x g3+y+z+y+z+y+z+y+z)
#define dB 8l)*fp_greaterOrEq(q0(
#define dA "<4, sin(y),cos(y+1))"
#define d9 "*(log2(abs(x))"
#define d8 0 gT"cmp_"
#define d7 ,y)!=oF2)?
#define d6 dM qU
#define d5 y,q0(6l qU
#define d4 ,-1,1,
#define d3 d4 hF2 q4
#define d2 "pow_imm_pospos_base","("
#define d1 "pow_imm_pospos",gJ",2)"
#define d0 "pow_imm_posneg",gJ",3)"
#define hZ hL1},
#define hY fp_greaterOrEq(x
#define hX -1,1,mY1,q2
#define hW )+x;}q0
#define hV g4 qW q0(6.1l)
#define hU g4 qW-q0(6.1l)
#define hT "pow_imm_negpos",gJ",-2)"
#define hS "pow_imm_negneg",gJ",-3)"
#define hR "*(log10(abs(x))"
#define hQ 1.061l),x
#define hP fp_log(
#define hO 2,N(0.0,0.0)qV
#define hN 2,N(-3.0,0.0),qO3 oJ2 qN,q2
#define hM g01 fp_tanh(q0(0.75l)
#define hL qX1 fp_asin(q0(0.75l)
#define hK qW1 fp_acos(q0(0.75l)
#define hJ cpp_03unit_constants::
#define hI {2,N(-4.0,0.0),mT1 qD1
#define hH "powpow_imm_base",qQ1
#define hG {1,-5,5,2 qN,q2
#define hF "a,b",qE
#define hE {1,wO2 3,hF2 q4
#define hD "(x)"},{1,
#define hC fp_log2(
#define hB (qD,&y oI2,&z=vars[2]qA
#define hA 0x0001l)*fp_less(
#define h9 N(-1.75),N(1.75),hF2,qG
#define h8 qW-q0(2)),mflit0_0625)
#define h7 N(1e-6,0.0),N(4000.0,0.0),N(0.1,0.0)qN qB
#define h6 "*((x^5.1)"
#define h5 "*((x^-5.1"
#define h4 "*((2.051^"
#define h3 wG"5/2)+abs(x)))"
#define h2 qO3 N(5.0,0.0),N(0.5,0.0)qN,q2
#define h1 fp_log10(
#define h0 ")+x"},{1,0,1,1,true q4
#define gZ 0x0004l)*g11
#define gY mflit5_0625,mA2 mflit1_5,x))
#define gX q0(2l)
#define gW ",y","10optimizer_bytecode/"
#define gV (mflit1_1 hW
#define gU ,N(-1.0,0.0),mF1 N(0.5,0.0)qN,q2
#define gT ,q7"/"
#define gS ,0,1,gH3
#define gR 1 qN,q2
#define gQ 0,oQ1
#define gP q0(0x0020l)*qB2
#define gO q0(4l),y+q0(6l
#define gN qT q0::
#define gM N(-6.0,-3.0),N(6.0,+3.0),N(0.5,+0.25)qN,qG
#define gL -gE3,-mflit0_015625)
#define gK wX 0x0002l)*o11
#define gJ "(pow(x"
#define gI +q0(0x0010l)*fp_nequal(
#define gH N(-1.75,0.0),N(1.75,0.0),N(0.25,0.0)qN,qG
#define gG 0x0008l)*fp_greaterOrEq(
#define gF fp_const_pi<q0>()
#define gE N(-2.0,0.0),oJ2,qD1
#define gD 2.051l),x
#define gC fp_abs(x)),
#define gB )!=oF2?
#define gA 5l)/gX)+x*x-gX),((x*wV1/gX)+fp_abs(x)
#define g9 "01unit_operators/"
#define g8 "*(((-2.051)^x)"
#define g7 N(-1.0,0.0),mF1 oJ2 qN,q5
#define g6 {1,N(-0.7),N(0.7),N(0.28)qN q4
#define g5 (qC,&b oI2 qA
#define g4 q0(5.1l)),
#define g3 +y+z+y+z+y+z+y+z+y+z
#define g2 oC",y",g9
#define g1 cpp_50regressions::
#define g0 15,15,2 qN,q5
#define qZ qD,&y oI2,&z=vars[2]qA dW
#define qY gS3"0x"
#define qX "+"qO2 qO2"z+y+z"
#define qW mA2 x,
#define qV ,mF1 qD1
#define qU ));}q3
#define qT (qD qA
#define qS +q0(8l)*g11
#define qR +q0(4l)*o11
#define qQ +q0(16l)*fp_greaterOrEq(
#define qP qD qA dI1*qB2
#define qO (qD,&y oI2 qA
#define qN ,false
#define qM ))+gX*fp_less(
#define qL ,cpp_99misc::
#define qK ,oU2
#define qJ -6,6,gR
#define qI mA2 q0(
#define qH 0,"x"wN
#define qG cpp_01unit_operators::
#define qF wX 32l)*fp_nequal(
#define qE "11optimizer_constaddmul/"
#define qD gV2 q1
#define qC gV2*vars){gV2&a=vars[0]
#define qB ,cpp_02unit_functions::
#define qA ;return
#define q9 N(-15.0,0.0),N(15.0,0.0),oJ2 qN,q5
#define q8 N(-6.0,0.0),N(6.0,0.0),qD1
#define q7 "x","10optimizer_bytecode"
#define q6 ,"20optimizer_optimizations"
#define q5 cpp_11optimizer_constaddmul::
#define q4 ,cpp_10optimizer_bytecode::
#define q3 template<typename q0>static q0
#define q2 cpp_20optimizer_optimizations::
#define q1 *vars){gV2&x=vars[0]
#define q0 Value_t
#define APP(x,y) x##y
#define S {2,-h41 Add_i,0,qG Add_i,aF"add_i","x+y"},
#define T {3,-h41 Addsub_i,0,qG Addsub_i,gG3,g9"addsub_i","x+y+x+x-z+x"},
#define U {2,aB And_i,0,qG And_i,aF"and_i","x&y"},
#define W {2,aB Cmpeq_i,0,qG Cmpeq_i,aF"cmpeq_i","x=y"},
#define Y {2,aB Cmpge_i,0,qG Cmpge_i,aF"cmpge_i","x>=y"},
#define S1 {2,aB Cmpgt_i,0,qG Cmpgt_i,aF"cmpgt_i","x>y"},
#define T1 {2,aB Cmple_i,0,qG Cmple_i,aF"cmple_i","x<=y"},
#define U1 {2,aB Cmplt_i,0,qG Cmplt_i,aF"cmplt_i","x<y"},
#define W1 {2,aB Cmpne_i,0,qG Cmpne_i,aF"cmpne_i","x!=y"},
#define Y1 {2,h51 Div_i,0,qG Div_i,aF"div_i","x/(y+3"g31
#define S2 {3,-46,40,2 qN,qG Divmul_i,0,qG Divmul_i,gG3,g9"divmul_i"aY2"y*x*x/(z+3)*(x+4"g31
#define T2 {1,-41,40,3 qN,qG Inv_i,0,qG Inv_i,"x",g9"inv_i","1/x"},
#define U2 {2,h51 Mod_i,0,qG Mod_i,"x,z",g9"mod_i","x%(z+3"g31
#define W2 {2,h51 Mul_i,0,qG Mul_i,aF"mul_i","x*(y+4"g31
#define Y2 {1,-h41 Neg_i,0,qG Neg_i,"x",g9"neg_i","-x"},
#define S3 {1,aB Not_i,0,qG Not_i,"x",g9"not_i","!x"},
#define T3 {1,aB Notnot_i,0,qG Notnot_i,"x",g9"notnot_i","!!x"},
#define U3 {2,aB Or_i,0,qG Or_i,aF"or_i","x|y"},
#define W3 {2,-h41 Sub_i,0,qG Sub_i,aF"sub_i","x-y"},
#define Y3 {1,-40000,40000,1 qN qB Abs_i,0 qB Abs_i,"x"wN"/abs_i",gY2},
#define S4 {3,-2,2,1 qN qB If_i,0 qB If_i,gG3 wN"/if_i",dX",y,z"g31
#define T4 {2,-4,4,1 qN qB Max qB Max qB Max,"x,y"wN"/max","max(x"mI1
#define U4 {2,-4,4,1 qN qB Min qB Min qB Min,"x,y"wN"/min","min(x"mI1
#define W4 {1 gS Abs q4 Abs q4 Abs gT"abs","(abs(-3))+x"},
#define Y4 {wD Absnot q4 Absnot q4 Absnot gT"absnot","!(abs"g91
#define S5 {wD wZ1 q4 wZ1 q4 wZ1 gT"absnotnotnot","!(!!((x*x)))"},
#define T5 {1,-5,5,gH3 mF2 q4 mF2 q4 mF2 gT"absnzge","sub("gY2 hB3"4, abs(x)"hB3"0"g31
#define U5 {1,-5,5,gH3 mG2 q4 mG2 q4 mG2 gT"absnzlt","sub("gY2" < 4, abs(x) < 0"g31
#define W5 {wD Abssqr q4 Abssqr q4 Abssqr gT"abssqr","abs(x)*"gY2},
#define Y5 {1 oJ gH3 qP2 q4 qP2 q4 qP2 gT"dupaddmul7","(x+x)*7"},
#define S6 {1,oI1 hG2 q4 hG2 q4 hG2 gT mG1,"sub(min(x,x), max(x,"mH2
#define T6 {1,oI1 qQ2 q4 qQ2 q4 qQ2 gT mG1"2","sub(x+min(x,x), x+max(x,"mH2
#define U6 {2,-2,2,gH3 qR2 q4 qR2 q4 qR2,oL2 mG1"3","sub(min(min(y,x),x), max(max(y,x),"mH2
#define W6 {1,oI1 qS2 q4 qS2 q4 qS2 gT"dupxmuladd","x+(x*4"g31
#define Y6 dO1 Invmul q4 Invmul q4 Invmul,oL2"invmul","y*(1/x)"},
#define S7 {1 gS Max q4 Max q4 Max gT"max","max(5,4)+x"},
#define T7 {1 gS Min q4 Min q4 Min gT"min","min(4,5)+x"},
#define U7 {1 gS Mul2 q4 Mul2 q4 Mul2 gT"mul2"aY2"2"},
#define W7 {2 oJ gH3 Mul4 q4 Mul4 q4 Mul4,oL2"mul4","y*(x*2)*2 + (y*2)*2"},
#define Y7 {wD Negabs q4 Negabs q4 Negabs gT"negabs","abs"gZ2
#define S8 {wD Negdiv q4 Negdiv q4 Negdiv gT"negdiv","(-x)/5"},
#define T8 {1 oJ 2 qN qW3 qW3 qW3 gT"negneg","-(-(-(-(-(-(x))))))"},
#define U8 {wD Negnot q4 Negnot q4 Negnot gT"negnot","!"gZ2
#define W8 {wD Negsqr q4 Negsqr q4 Negsqr gT"negsqr","(-x)*(-x)"},
#define Y8 {2 gS Not_eq q4 Not_eq q4 Not_eq,oL2"not_eq","!"oS1
#define S9 {2 gS Not_ge q4 Not_ge q4 Not_ge,oL2"not_ge","!"m6},
#define T9 {2 gS Not_gt q4 Not_gt q4 Not_gt,oL2"not_gt","!(x > y"g31
#define U9 {2 gS Not_le q4 Not_le q4 Not_le,oL2"not_le","!"oY2
#define W9 {2 gS Not_lt q4 Not_lt q4 Not_lt,oL2"not_lt","!(x < y"g31
#define Y9 {2 gS Not_ne q4 Not_ne q4 Not_ne,oL2"not_ne","!"oT1
#define SA {wD Notnot q4 Notnot q4 Notnot gT"notnot","!!(x)"},
#define TA {wD hH2 q4 hH2 q4 hH2 gT"notnotnot","!!!(x)"},
#define UA {wD qT2 q4 qT2 q4 qT2 gT"notnotnot2","!x&!x"},
#define WA {wD mI2 q4 mI2 q4 mI2 gT"sqr_nxx","(-x)*x"},
#define YA {wD mJ2 q4 mJ2 q4 mJ2 gT"sqr_xnx","x*(-x)"},
#define SB {wD Sqr_xx q4 Sqr_xx q4 Sqr_xx gT"sqr_xx","x*x"},
#define TB {2 a01 oM2 q4 oM2 q4 oM2,oL2"sqr_ynxx","y*-x*x"},
#define UB {2 a01 oN2 q4 oN2 q4 oN2,oL2"sqr_yxnx","y*x*-x"},
#define WB {2 a01 mK2 q4 mK2 q4 mK2,oL2"sqr_yxx","y*x*x"},
#define YB {1,-5,5,gH3 Xaddnot q4 Xaddnot q4 wH2 q7"/xaddnot","!(x+4"g31
#define SC {1,-5,5,1 qN w31 w31 w31,q7"/xaddnotnot","!!(x+4"g31
#define TC {wD Xxdup q4 Xxdup q4 Xxdup,q7"/xxdup","sub(x,x)"},
#define UC {2 a01 oO2 q4 oO2 q4 oO2,"x,y","10optimizer_bytecode/xxsqrdup","y*abs(x)*"gY2},
#define WC {1,-5,5,gR oP2 q2 oP2 q2 oP2 oQ1"absnzge","sub("gY2 hB3"if("oQ2"), abs(x)"hB3"(if(1,1,0)-1))"},
#define YC {1,-5,5,gR oR2 q2 oR2 q2 oR2 oQ1"absnzlt","sub("gY2" < if("oQ2"), abs(x) < (if(1,1,0)-1))"},
#define SD {a11 mH1,q2 mH1,q2 mH1 qK"addconstmul","5*(if("oQ2")+x+y"g31
#define TD {a11 o21,q2 o21,q2 o21 qK"addmulconstmul","5*(if("oQ2")*y+x)"},
#define UD {a11 a21,q2 a21,q2 a21 qK"addnegmulneg","-5 + (if(1,5,0)*x*y"g31
#define WD {a11 a31,q2 a31,q2 a31 qK"addnegmulpos","(if(1,-5,0)*"aU2" (if(1,5,0)*x)"},
#define YD wE w41,q2 w41,q2 w41 qK"cmpeq_add_imm",h61 hI2
#define SE {1,qJ gG1 q2 gG1 q2 gG1 oQ1"cmpeq_add_reduce",dP" = "h3},
#define TE wE h71,q2 h71,q2 h71 qK"cmpeq_addadd_imm",dY") = "hZ
#define UE wF a41,q2 a41,q2 a41 qK"cmpeq_minma"oS2" = "h13
#define WE wF h81,q2 h81,q2 h81 qK"cmpeq_minma"oV2" = "gO3},
#define YE wE gH1,q2 gH1,q2 gH1 qK"cmpeq_mul_imm_neg",oW2 hI2
#define SF wE gI1,q2 gI1,q2 gI1 qK"cmpeq_mul_imm_pos",a61 hI2
#define TF wE mQ,q2 mQ,q2 mQ qK"cmpeq_mulmul_imm_neg",qU2" = "hZ
#define UF wE mR,q2 mR,q2 mR qK"cmpeq_mulmul_imm_pos",oX2" = "hZ
#define WF wE w51,q2 w51,q2 w51 qK"cmpge_add_imm",h61 qV2
#define YF {1,qJ gJ1 q2 gJ1 q2 gJ1 oQ1"cmpge_add_reduce",dP hB3 h3},
#define SG wE h91,q2 h91,q2 h91 qK"cmpge_addadd_imm",dY")"hB3 hZ
#define TG wF a71,q2 a71,q2 a71 qK"cmpge_minma"oS2 hB3 h13
#define UG wF hA1,q2 hA1,q2 hA1 qK"cmpge_minma"oV2 hB3 gO3},
#define WG wE gK1,q2 gK1,q2 gK1 qK"cmpge_mul_imm_neg",oW2 qV2
#define YG wE gL1,q2 gL1,q2 gL1 qK"cmpge_mul_imm_pos",a61 qV2
#define SH wE mS,q2 mS,q2 mS qK"cmpge_mulmul_imm_neg",qU2 hB3 hZ
#define TH wE mT,q2 mT,q2 mT qK"cmpge_mulmul_imm_pos",oX2 hB3 hZ
#define UH wE w61,q2 w61,q2 w61 qK"cmpgt_add_imm",h61 hJ2
#define WH {1,qJ gM1 q2 gM1 q2 gM1 oQ1"cmpgt_add_reduce",dP" > "h3},
#define YH wE hB1,q2 hB1,q2 hB1 qK"cmpgt_addadd_imm",dY") > "hZ
#define SI wF a81,q2 a81,q2 a81 qK"cmpgt_minma"oS2" > "h13
#define TI wF hC1,q2 hC1,q2 hC1 qK"cmpgt_minma"oV2" > "gO3},
#define UI wE gN1,q2 gN1,q2 gN1 qK"cmpgt_mul_imm_neg",oW2 hJ2
#define WI wE gO1,q2 gO1,q2 gO1 qK"cmpgt_mul_imm_pos",a61 hJ2
#define YI wE mU,q2 mU,q2 mU qK"cmpgt_mulmul_imm_neg",qU2" > "hZ
#define SJ wE mV,q2 mV,q2 mV qK"cmpgt_mulmul_imm_pos",oX2" > "hZ
#define TJ wE w71,q2 w71,q2 w71 qK"cmple_add_imm",h61 qW2
#define UJ {1,qJ gP1 q2 gP1 q2 gP1 oQ1"cmple_add_reduce",dP hJ3 h3},
#define WJ wE hD1,q2 hD1,q2 hD1 qK"cmple_addadd_imm",dY")"hJ3 hZ
#define YJ wF a91,q2 a91,q2 a91 qK"cmple_minma"oS2 hJ3 h13
#define SK wF hE1,q2 hE1,q2 hE1 qK"cmple_minma"oV2 hJ3 gO3},
#define TK wE gQ1,q2 gQ1,q2 gQ1 qK"cmple_mul_imm_neg",oW2 qW2
#define UK wE gR1,q2 gR1,q2 gR1 qK"cmple_mul_imm_pos",a61 qW2
#define WK wE mW,q2 mW,q2 mW qK"cmple_mulmul_imm_neg",qU2 hJ3 hZ
#define YK wE mX,q2 mX,q2 mX qK"cmple_mulmul_imm_pos",oX2 hJ3 hZ
#define SL wE w81,q2 w81,q2 w81 qK"cmplt_add_imm",h61 hK2
#define TL {1,qJ gS1 q2 gS1 q2 gS1 oQ1"cmplt_add_reduce",dP" < "h3},
#define UL wE hF1,q2 hF1,q2 hF1 qK"cmplt_addadd_imm",dY") < "hZ
#define WL wF aA1,q2 aA1,q2 aA1 qK"cmplt_minma"oS2" < "h13
#define YL wF hG1,q2 hG1,q2 hG1 qK"cmplt_minma"oV2" < "gO3},
#define SM wE gT1,q2 gT1,q2 gT1 qK"cmplt_mul_imm_neg",oW2 hK2
#define TM wE gU1,q2 gU1,q2 gU1 qK"cmplt_mul_imm_pos",a61 hK2
#define UM wE mY,q2 mY,q2 mY qK"cmplt_mulmul_imm_neg",qU2" < "hZ
#define WM wE mZ,q2 mZ,q2 mZ qK"cmplt_mulmul_imm_pos",oX2" < "hZ
#define YM wE w91,q2 w91,q2 w91 qK"cmpne_add_imm",h61 qX2
#define SN {1,qJ gV1 q2 gV1 q2 gV1 oQ1"cmpne_add_reduce",dP aZ2 h3},
#define TN wE hH1,q2 hH1,q2 hH1 qK"cmpne_addadd_imm",dY")"aZ2 hZ
#define UN wF aB1,q2 aB1,q2 aB1 qK"cmpne_minma"oS2 hC3 h13
#define WN wF hI1,q2 hI1,q2 hI1 qK"cmpne_minma"oV2 hC3 gO3},
#define YN wE gW1,q2 gW1,q2 gW1 qK"cmpne_mul_imm_neg",oW2 qX2
#define SO wE gX1,q2 gX1,q2 gX1 qK"cmpne_mul_imm_pos",a61 qX2
#define TO wE q01,q2 q01,q2 q01 qK"cmpne_mulmul_imm_neg",qU2 aZ2 hZ
#define UO wE q11,q2 q11,q2 q11 qK"cmpne_mulmul_imm_pos",oX2 aZ2 hZ
#define WO wE wA1,q2 wA1,q2 wA1 qK"cmpzz_add_imm"oN m02 hL2 m02 qY2 m02 hO2 m02 hP2 m02 qZ2 h61 hI2
#define YO {1,qJ gY1 q2 gY1 q2 gY1 oQ1"cmpzz_add_reduce"oN" "dP" < "h3 a6" "dP hJ3 h3 a8" "dP" > "h3 oS" "dP hB3 h3 o41" "dP aZ2 h3 dV dP" = "h3},
#define SP wE hJ1,q2 hJ1,q2 hJ1 qK"cmpzz_addadd_imm"oN" "dY aC1" "dY aD1" "dY aE1" "dY aF1" "dY aG1 dY") = "hZ
#define TP wF aH1,q2 aH1,q2 aH1 qK"cmpzz_minmax"oN hK1" < "hE3 a6 hK1 hJ3 hE3 a8 hK1" > "hE3 oS hK1 hB3"y,x,y"a7 hK1 hC3 hE3" +  0x0020 *"hK1" = "h13
#define UP wF hO1,q2 hO1,q2 hO1 qK"cmpzz_minmax_rev"oN hK1" < "gO3 a6 hK1 hJ3 gO3 a8 hK1" > "gO3 oS hK1 hB3 gO3 o41 hK1 hC3 gO3" +  0x0020 *"hK1" = "gO3},
#define WP wE gZ1,q2 gZ1,q2 gZ1 qK"cmpzz_mul_imm_neg"oN mZ1 hL2 mZ1 qY2 mZ1 hO2 mZ1 hP2 mZ1 qZ2 oW2 hI2
#define YP wE h01,q2 h01,q2 h01 qK"cmpzz_mul_imm_pos"oN q02 hL2 q02 qY2 q02 hO2 q02 hP2 q02 qZ2 a61 hI2
#define SQ wE q21,q2 q21,q2 q21 qK"cmpzz_mulmul_imm_neg"oN qV1 aC1 qV1 aD1 qV1 aE1 qV1 aF1 qV1 aG1 qU2" = "hZ
#define TQ wE q31,q2 q31,q2 q31 qK"cmpzz_mulmul_imm_pos"oN g81 aC1 g81 aD1 g81 aE1 g81 aF1 g81 aG1 oX2" = "hZ
#define UQ wF hQ2,q2 hQ2,q2 hQ2 qK"ge_and_eq",mL2 oS1
#define WQ wF hR2,q2 hR2,q2 hR2 qK"ge_and_le",mL2 oY2
#define YQ wF hS2,q2 hS2,q2 hS2 qK"ge_and_ne",mL2 oT1
#define SR wF oZ2,q2 oZ2,q2 oZ2 qK"ge_or_eq",mM2 oS1
#define TR wF w02,q2 w02,q2 w02 qK"ge_or_le",mM2 oY2
#define UR wF w12,q2 w12,q2 w12 qK"ge_or_ne",mM2 oT1
#define WR wF hT2,q2 hT2,q2 hT2 qK"gt_and_eq"h02 oS1
#define YR wF hU2,q2 hU2,q2 hU2 qK"gt_and_ge"h02 m6},
#define SS wF hV2,q2 hV2,q2 hV2 qK"gt_and_le"h02 oY2
#define TS wF hW2,q2 hW2,q2 hW2 qK"gt_and_ne"h02 oT1
#define US wF w22,q2 w22,q2 w22 qK"gt_or_eq"h12 oS1
#define WS wF w32,q2 w32,q2 w32 qK"gt_or_ge"h12 m6},
#define YS wF w42,q2 w42,q2 w42 qK"gt_or_le"h12 oY2
#define ST wF w52,q2 w52,q2 w52 qK"gt_or_ne"h12 oT1
#define TT m62 If10,q2 If10,q2 If10,oQ1"if10",dX",1,0) + 10*"dX",0,1)"gM3"+ 100*"dX">0,1,0) + 1000*"dX">0,0,1"g31
#define UT {mG o51,q2 o51,q2 o51 mJ"tract_abs",dX", abs(x+2), abs(y+5))"},
#define WT {mG o61,q2 o61,q2 o61 mJ"tract_add",dX", y+2, y+"h62
#define YT {mG d91,q2 d91,q2 d91 mJ"tract_add1",dX", y+2, y"g31
#define SU {mG dA1,q2 dA1,q2 dA1 mJ"tract_add2",dX", y, y+2"g31
#define TU {aI1 qM1 q2 qM1 q2 qM1"x"dO"tract_and1_l",dX", y&z, y<1"g31
#define UU {aI1 q41 q2 q41 q2 q41"x"dO"tract_and1_nl",dX", y&z, z"g31
#define WU {aI1 qN1 q2 qN1 q2 qN1"x"dO"tract_and2_l",dX", y<1, y&z"g31
#define YU {aI1 q51 q2 q51 q2 q51"x"dO"tract_and2_nl",dX", z, y&z"g31
#define SV {mG If_extract_div,0,q2 If_extract_div mJ"tract_div",dX", y/x, y/2"g31
#define TV {mG o71,q2 o71,q2 o71 mJ"tract_min",dX", min(y,2), min(y,5))"},
#define UV {mG o81,q2 o81,q2 o81 mJ"tract_mul",dX", y*2, y*"h62
#define WV {mG dB1,q2 dB1,q2 dB1 mJ"tract_mul1",dX", y*2, y"g31
#define YV {mG dC1,q2 dC1,q2 dC1 mJ"tract_mul2",dX", y, y*2"g31
#define SW {aI1 h11 q2 h11 q2 h11"x"dO"tract_or1_l",dX", y|z, y<1"g31
#define TW {aI1 qO1 q2 qO1 q2 qO1"x"dO"tract_or1_nl",dX", y|z, z"g31
#define UW {aI1 h21 q2 h21 q2 h21"x"dO"tract_or2_l",dX", y<1, y|z"g31
#define WW {aI1 qP1 q2 qP1 q2 qP1"x"dO"tract_or2_nl",dX", z, y|z"g31
#define YW {1,3,5,gR wB1 q2 wB1 q2 wB1 oQ1"if_join_add2","x + 10 +"hK1"<4, 3,4"g31
#define SX {1,3,5,gR wC1 q2 wC1 q2 wC1 oQ1"if_join_mul2","x * 10 *"hK1"<4, 3,4"g31
#define TX aQ2 Ifabs,q2 Ifabs,q2 Ifabs,oQ1"ifabs","1"dM1"< 0,-x,"gV3"  10"dM1"<=0,-x,"gV3" 100"dM1"> 0,-x,"gV3"1000"dM1">=0,-x,"mL1 gM3 gM3"10000"dM1"< 0,x"mN2 gM3"   100000"dM1"<=0,x"mN2 gM3"  1000000"dM1"> 0,x"mN2"  10000000"dM1">=0,x,-"mH2
#define UX {mO2 w62 q2 w62 q2 w62"b,d,"oU2"ifmerge",dX oC2"y,x,b)"oC2"y,x,d)) +  if(b,if(d,y,x)"oC2"d,b,"mH2
#define WX {mO2 hX2 q2 hX2 q2 hX2"a,b,"oU2"ifmerge2",dX oC2"y,a,b)"oC2"b,a,b))"},
#define YX {mO2 g02 q2 g02 q2 g02"a,b,"oU2"ifmerge2b",dX oC2"y,a,b)"oC2"b,b,a))"},
#define SY wF Ifnop,q2 Ifnop,q2 Ifnop qK"ifnop",dX",y,y"g31
#define TY {q12 L_abs,q2 L_abs,q2 L_abs qK"l_abs","(x+2) & abs(x)"oR1
#define UY {q12 w72,q2 w72,q2 w72 qK"l_mulabs","(x*abs(y))"oR1
#define WY {q12 w82,q2 w82,q2 w82 qK"l_mulneg","(x*y*-5)"oR1
#define YY {q12 w92,q2 w92,q2 w92 qK"l_notnot","(x+2) & !!x"oR1
#define SZ wF hZ2,q2 hZ2,q2 hZ2 qK"le_and_eq",hS3"& "oS1
#define TZ wF d02,q2 d02,q2 d02 qK"le_and_ne",hS3"& "oT1
#define UZ wF wA2,q2 wA2,q2 wA2 qK"le_or_eq",hS3"| "oS1
#define WZ wF wB2,q2 wB2,q2 wB2 qK"le_or_ne",hS3"| "oT1
#define YZ wF d12,q2 d12,q2 d12 qK"lt_and_eq"d22 oS1
#define Sa wF d32,q2 d32,q2 d32 qK"lt_and_ge"d22 m6},
#define Ta wF d42,q2 d42,q2 d42 qK"lt_and_gt"d22"(x > y"g31
#define Ua wF d52,q2 d52,q2 d52 qK"lt_and_le"d22 oY2
#define Wa wF d62,q2 d62,q2 d62 qK"lt_and_ne"d22 oT1
#define Ya wF wC2,q2 wC2,q2 wC2 qK"lt_or_eq"m22 oS1
#define Sb wF wD2,q2 wD2,q2 wD2 qK"lt_or_ge"m22 m6},
#define Tb wF wE2,q2 wE2,q2 wE2 qK"lt_or_gt"m22"(x > y"g31
#define Ub wF wF2,q2 wF2,q2 wF2 qK"lt_or_le"m22 oY2
#define Wb wF wG2,q2 wG2,q2 wG2 qK"lt_or_ne"m22 oT1
#define Yb {aI1 aJ1 q2 aJ1 q2 aJ1 mH"mergemulabs","abs(x)*abs(y)*z"},
#define Sc {3,0,4,gR aK1 q2 aK1 q2 aK1 mH"mixedminmax","max(z,min(x,max(max(z,y),x)))"gS3"10*min(z,max(x,min(y,x)))"gS3"100*min(max(x,y),min(y,z)) +  1000*max(min(x,y),max(y,z))"},
#define Tc wF Nand2,q2 Nand2,q2 Nand2 qK"nand2",hK3},
#define Uc {3 m72 g12 q2 g12 q2 g12 mH"nand2plus",hK3" | z"},
#define Wc {3 m72 Nand3,q2 Nand3,q2 Nand3,mH"nand3",hK3" | !z"},
#define Yc wF Nor2,q2 Nor2,q2 Nor2 qK"nor2",hL3},
#define Sd {3 m72 d72 q2 d72 q2 d72 mH"nor2plus",hL3" & z"},
#define Td {3 m72 Nor3,q2 Nor3,q2 Nor3,mH"nor3",hL3" & !z"},
#define Ud wF Not_eq,q2 Not_eq,q2 Not_eq qK"not_eq",dX" = "gP3
#define Wd wF Not_ge,q2 Not_ge,q2 Not_ge qK"not_ge",dX hB3 gP3
#define Yd wF Not_gt,q2 Not_gt,q2 Not_gt qK"not_gt",dX" > "gP3
#define Se wF Not_le,q2 Not_le,q2 Not_le qK"not_le",dX hJ3 gP3
#define Te wF Not_lt,q2 Not_lt,q2 Not_lt qK"not_lt",dX" < "gP3
#define Ue wF Not_ne,q2 Not_ne,q2 Not_ne qK"not_ne",dX hC3 gP3
#define We {mG Notnot,q2 Notnot,q2 Notnot qK"notnot","!!x + if(y, 1,0"g31
#define Ye {1,-5,5,gR wH2 q2 wH2 q2 wH2"x"q6"/xaddnot","!(x+if(1,4,4))"},
#define Sf {1,-5,5,gR mM1 q2 mM1 q2 mM1"x"q6"/xaddnotnot","!!(x+if(1,4,4))"},
#define Tf {1,-wD1 t1,g1 t1,g1 t1,m82"1","x+max(0, min(-2,0))"},
#define Uf {1,-wD1 t2,g1 t2,g1 t2,m82"2","min(x,min(1,"mH2
#define Wf {1,-mN1 t3,g1 t3,g1 t3,m82"3","sub(  (!x & !!x) ,  (!x | !!x)  "g31
#define Yf {2,-mN1 t4,g1 t4,g1 t4,"x,y",oE"4","sub(!(x-y), !!(x-y))"},
#define Sg {1,-5,5,gF3 t6,g1 t6,g1 t6,m82"6","sub(!(x+4), !!(x+3))"},
#define Tg {1,-wD1 t36,g1 t36,g1 t36,m82"36","-if(x<0, x, -x) + -if(x<5, 2, 3"g31
#define Ug {2,-mN1 t60,g1 t60,g1 t60,"x,y",oE"60","sqr(x) | sub(x,y) | value()"},
#define Wg {2,-20,20,dU1 t16 qL t16 qL t16,wI2"16",dX"<0, if(y<0, x+y, x-y), if(y>0, x*y, x+2*y))"},
#define Yg {2,-20,20,dU1 t17 qL t17 qL t17,wI2"17","sqr(x)+sub(x,y)+psqr(y)+psub(y+1,x-2)-1"},
#define Sh {2,-100,100,dU1 t19 qL t19 qL t19,wI2"19","(x<y)+10"d92"<=y)+100"d92">y)+1000"d92">=y)+10000"d92"=y)+100000"d92"!=y)+  (x&y)*2+(x|y)*20+(!x)*200+(!!x)*2000+4*!((x<y)&(x<3))+40*!!(!(x>y)|(x>3))"},
#define Th {2,-100,100,dU1 t20 qL t20 qL t20,wI2"20","(!(x"hC3"y) & !x) + !(!(!(!y)))"},
#define Uh {1,-d82 t21 qL t21 qL t21,"x",oM"21","sqr(x)+value()-pvalue ( "g31
#define Wh {1,-1000,1000,dU1 t24 qL t24 qL t24,"x",oM"24","(min(x, min(1,"mL1" min(x, 1))/2 + min(x, 1)*3 + max(0, min(-2,0))"},
#define Yh {2,-5,5,dU1 t29 qL t29 qL t29,wI2"29","x-y*1"},
#define Si {4,-5,5,dU1 t34 qL t34 qL t34,"t,う,お,早",oM"34","お+早*う-t"},
#define Ti {3,-d82 t35 qL t35 qL t35,"A_very_long_variable_name_1,A_very_long_variable_name_2,Yet_a_third_very_long_variable_name",oM"35","A_very_long_variable_name_1-A_very_long_variable_name_2+  Yet_a_third_very_long_variable_name*A_very_long_variable_name_1"},
#define Ui {2,-d82 t50 qL t50 qL t50,wI2"50","(x<y | y<x)"gS3" 2"d92"<y & y<x)"gS3" 4"qF3" y<=x)"gS3" 8"d92"<y & "wJ2 gM3" 16"d92"<y | "wJ2 gM3" 32"qF3" x>=y)"gS3" 64"d92"<=y | x>=y)"gS3" 128"d92"!=y & x=y)"gS3" 256"d92"!=y & "wJ2"  512"qF3" x=y"g31
#define Wi {2,-11,11,dU1 t58 qL t58 qL t58,wI2"58","(-x < 3)"oB2"-1 > 5)"oB2"-3 < 10)"oB2"-3 < y*7) +  (x*4 < y*7)"oB2"6 < y*-3"q33"-x < 11"q33"5 < -y"g31
#define Yi {3,-8,7,dU1 I1,0 qL I1,"x"dA2"i1","1+2+3-4*5*6/3+10/2-9%2 + (x+y - 11*x + z/10 + x/(z+31))"},
#define Sj {3,-7,7,dU1 I2,0 qL I2,"x"dA2"i2","if(abs(x*y) < 20 | x+y > 30 & z > 5, min(x,2*y), max(y,z*2))"},
#define Tj {3,1,7,dU1 I3,0 qL I3,"x"dA2"i3","(x+"aU2" 2"d92"-z) + 3*(x*"aU2" 4*(y/z) + 5"d92"%z)"gS3"6"d92"<y) + 7"d92"<=z) + 8"d92">2"mQ2" 9*(y>=3"mQ2" 10*(x+y!=z) +  11*(100+x) + 12*(101-y) + 13*(102"mQ2" 14*(103/x)"},
#define Uj {2,-qE1 Add_d,qG Add_d g2"add_d","x+y"},
#define Wj {3,-qE1 Addsub_d,qG Addsub_d wK2,g9"addsub_d","x+y+x+x-z+x"},
#define Yj {2,h9 And_d,qG And_d g2"and_d","x&y"},
#define Sk {2,h9 Cmpeq_d,qG Cmpeq_d g2"cmpeq_d","x=y"},
#define Tk {2,h9 Cmpge_d,qG Cmpge_d g2"cmpge_d","x>=y"},
#define Uk {2,h9 Cmpgt_d,qG Cmpgt_d g2"cmpgt_d","x>y"},
#define Wk {2,h9 Cmple_d,qG Cmple_d g2"cmple_d","x<=y"},
#define Yk {2,h9 Cmplt_d,qG Cmplt_d g2"cmplt_d","x<y"},
#define Sl {2,h9 Cmpne_d,qG Cmpne_d g2"cmpne_d","x!=y"},
#define Tl {2,w7 Div_d,qG Div_d g2"div_d","(x-0.25)/y"},
#define Ul {3,w7 Divmul_d,qG Divmul_d wK2,g9"divmul_d"aY2"y*x*x/z"d92"-0.25"g31
#define Wl {1,-7,6,N(0.6)qN,qG Inv_d,qG Inv_d oC,g9"inv_d","1/x"},
#define Yl {2,w7 Mul_d,qG Mul_d g2"mul_d"aY2"y"},
#define Sm {1,-qE1 Neg_d,qG Neg_d oC,g9"neg_d","-x"},
#define Tm {1,wS,qG Not_d,qG Not_d oC,g9"not_d","!x"},
#define Um {1,wS,qG Notnot_d,qG Notnot_d oC,g9"notnot_d","!!x"},
#define Wm {2,h9 Or_d,qG Or_d g2"or_d","x|y"},
#define Ym {2,-qE1 Sub_d,qG Sub_d g2"sub_d","x-y"},
#define Sn {1,oA2 mY1 qB Abs_d qB Abs_d wY"abs_d",gY2},
#define Tn {3,wS qB If_d qB If_d wK2 wN"/if_d",dX",y,z"g31
#define Un {1,-4000,4000,mD Int qB Int wY"int","int(x)"},
#define Wn {1 d3 Absneverneg q4 Absneverneg w11"absneverneg","abs(acos"g91
#define Yn {1 d3 Absnot2 q4 Absnot2 w11"absnot2","!acos(x)"},
#define So {2 d3 Absnot3 q4 Absnot3 oC gW"absnot3","!(!(x&y))"},
#define To {1 d3 Absnot4 q4 Absnot4 w11"absnot4","!(!acos"g91
#define Uo {1,1,3,N(0.1)qN q4 Acoshcosh q4 Acoshcosh w11"acoshcosh","cosh("mR2 g91
#define Wo {1,N(1.7),N(3.7),N(0.28)qN q4 Acoshsinh q4 Acoshsinh w11 mR2 wL2,wL2"("mR2 g91
#define Yo {1,-3,-3,N(0.7)qN q4 Addexp q4 Addexp w11"addexp","exp(x+4"g31
#define Sp {1,-3,-3,N(0.7)qN q4 Addexp2 q4 Addexp2 w11"addexp2","exp2(x+4"g31
#define Tp g6 Asinhcosh q4 Asinhcosh oZ1"hcosh","cosh(a"wL2 g91
#define Up wU Asinhsinh q4 Asinhsinh oZ1"h"wL2,wL2"(a"wL2 g91
#define Wp {2 oJ N(0.11)qN q4 Atan2tan q4 Atan2tan oC gW"atan2tan","tan("aA2"(x,y))"},
#define Yp {1 w5 Ceilneg q4 Ceilneg w11"ceilneg","ceil"gZ2
#define Sq {2,aG Deg q4 Deg oC gW"deg","("wM2")*y + x*("wM2 q33"y*("wM2"))*4"},
#define Tq {1 d4 N(0.5),true q4 Degxmul q4 Degxmul w11"degxmul","acos(x)*2"},
#define Uq {1 oJ gH3 Dupaddmulh q4 Dupaddmulh w11"dupaddmulh","(x+x)*0.5"},
#define Wq {2 oJ gH3 Dupaddmulmul7 q4 Dupaddmulmul7 oC gW"dupaddmulmul7","y*(x+x)*7"},
#define Yq {2 oJ gH3 Dupaddmulmulh q4 Dupaddmulmulh oC gW"dupaddmulmulh","y*(x+x)*0.5"},
#define Sr {1,oI1 Dupxpowmul q4 Dupxpowmul w11"dupxpowmul","x*(x^3"g31
#define Tr dO1 Exp2div q4 Exp2div oC gW"exp2div","x/exp2(y"g31
#define Ur wU Exp2log2 q4 Exp2log2 aT2"p2log2","log2(exp2"g91
#define Wr dO1 Expdiv q4 Expdiv oC gW"expdiv","x/"m12"y"g31
#define Yr wU Explog q4 Explog aT2"plog","log("m32
#define Ss wU Explog2 q4 Explog2 aT2"plog2","log2("m32
#define Ts wU Explog10 q4 Explog10 aT2"plog10","log10("m32
#define Us {1 w5 Floorneg q4 Floorneg w11"floorneg","floor"gZ2
#define Ws {1,N(-1.5),N(1.5),hF2 q4 Int q4 Int w11"int","x+"g22 g22"sub(int(1.1), int(1.6"aL1"1.5"aL1"-1.1"aL1"-1.6"aL1"-1.5))"},
#define Ys {1 w5 Intceil q4 Intceil w11"intceil","ceil"q42
#define St {1 w5 Intfloor q4 Intfloor w11"intfloor","floor"q42
#define Tt {1 w5 Intint q4 Intint w11"intint","int"q42
#define Ut {1 w5 Inttrunc q4 Inttrunc w11"inttrunc","trunc"q42
#define Wt dO1 Invdiv q4 Invdiv oC gW"invdiv","y/(1/x)"},
#define Yt {1 oJ 2 qN q4 Invinv q4 Invinv w11"invinv","1/(1/x)"},
#define Su {1 w5 Negceil q4 Negceil w11"negceil","-ceil(x)"},
#define Tu {1 w5 Negfloor q4 Negfloor w11"negfloor","-floor(x)"},
#define Uu dO1 Powdiv q4 Powdiv oC",y","10optimizer_bytecode/powdiv","x/pow(x"mI1
#define Wu mA Powhalf q4 Powhalf,w21"half",dB2",0.5"g31
#define Yu dO1 Powinv q4 Powinv oC",y","10optimizer_bytecode/powinv","1/pow(x"mI1
#define Sv mA Powminushalf q4 Powminushalf,w21"minushalf",dB2",-0.5"g31
#define Tv {1,1,5,gH3 Powminusone q4 Powminusone,w21"minusone",dB2",-1.0"g31
#define Uv mA Powminusthird q4 Powminusthird,w21"minusthird",dB2",(-1.0/3.0))"},
#define Wv mA Powthird q4 Powthird,w21"third",dB2","h32"/3.0))"},
#define Yv {2,aG Rad q4 Rad oC gW"rad","("h22")*y + x*("h22") + (x*("h22"))*4"},
#define Sw {1,-2,2,N(0.8)qN q4 Radxmul q4 Radxmul w11"radxmul","cos"wG h22")*4"g31
#define Tw {1,aG Sqrlog q4 Sqrlog w11"sqrlog","log"dC2
#define Uw {1,aG Sqrlog2 q4 Sqrlog2 w11"sqrlog2","log2"dC2
#define Ww {1,aG Sqrlog10 q4 Sqrlog10 w11"sqrlog10","log10"dC2
#define Yw {1,-2,2,N(0.8),true q4 Xmulrad q4 Xmulrad,0,q7"/xmulrad","cos"a42
#define Sx {wD Xxfdup q4 Xxfdup,0,q7"/xxfdup","sub(sin(x),sin(x))"},
#define Tx aQ2 Abscos,q2 Abscos,gQ"abscos","cos(sqrt("aM1"))) + sqrt("aM1"))"},
#define Ux aQ2 Abscosh,q2 Abscosh,gQ"abscosh","cosh(sqrt("aM1"))) + sqrt("aM1"))"},
#define Wx {1 d4 N(0.1)qN,q2 Acoscos,q2 Acoscos,gQ"acoscos","cos(acos"g91
#define Yx {1,N(1.7),N(3.7),N(0.28)qN,q2 Acoshsinh,q2 Acoshsinh,gQ mR2 wL2,wL2"(if(1,acosh(x),0))"},
#define Sy {2,wO2 1,hF2,q2 Addlog,q2 Addlog,0 qK"addlog","log(x)+log(y"g31
#define Ty {1,hX Addsin2cos2,q2 Addsin2cos2,gQ"addsin2cos2",qA2"^2 + cos(x)^2"},
#define Uy {1,N(-0.7),N(0.7),N(0.28)qN,q2 Asinhcosh,q2 Asinhcosh,gQ"asinhcosh","cosh(if(1,a"wL2"(x),0))"},
#define Wy {1 d4 N(0.1)qN,q2 Asinsin,q2 Asinsin,gQ"asinsin","sin(asin(x))"},
#define Yy hG Cmpeq_pow_imm_negneg,q2 Cmpeq_pow_imm_negneg,gQ aN1 hS" = "gL3
#define Sz hG Cmpeq_pow_imm_negpos,q2 Cmpeq_pow_imm_negpos,gQ aN1 hT" = "gN3
#define Tz {1,qJ Cmpeq_pow_imm_posneg,q2 Cmpeq_pow_imm_posneg,gQ aN1 d0" = "gT3
#define Uz {1,qJ Cmpeq_pow_imm_pospos,q2 Cmpeq_pow_imm_pospos,gQ aN1 d1" = "h23
#define Wz {1,qJ Cmpeq_pow_imm_pospos_base,q2 Cmpeq_pow_imm_pospos_base,gQ aN1 gQ3"= "wH
#define Yz wE Cmpeq_powpow_imm_base,q2 Cmpeq_powpow_imm_base,0 qK aN1 hH" = "wW
#define S_ hG Cmpge_pow_imm_negneg,q2 Cmpge_pow_imm_negneg dV1 hS hB3 gL3
#define T_ hG Cmpge_pow_imm_negpos,q2 Cmpge_pow_imm_negpos dV1 hT hB3 gN3
#define U_ {1,qJ Cmpge_pow_imm_posneg,q2 Cmpge_pow_imm_posneg dV1 d0 hB3 gT3
#define W_ {1,qJ Cmpge_pow_imm_pospos,q2 Cmpge_pow_imm_pospos dV1 d1 hB3 h23
#define Y_ {1,qJ Cmpge_pow_imm_pospos_base,q2 Cmpge_pow_imm_pospos_base dV1 gQ3">= "wH
#define S01 wE Cmpge_powpow_imm_base,q2 Cmpge_powpow_imm_base,0 qK"cmpge_"hH hB3 wW
#define T01 hG Cmpgt_pow_imm_negneg,q2 Cmpgt_pow_imm_negneg,oN1 hS" > "gL3
#define U01 hG Cmpgt_pow_imm_negpos,q2 Cmpgt_pow_imm_negpos,oN1 hT" > "gN3
#define W01 {1,qJ Cmpgt_pow_imm_posneg,q2 Cmpgt_pow_imm_posneg,oN1 d0" > "gT3
#define Y01 {1,qJ Cmpgt_pow_imm_pospos,q2 Cmpgt_pow_imm_pospos,oN1 d1" > "h23
#define S11 {1,qJ Cmpgt_pow_imm_pospos_base,q2 Cmpgt_pow_imm_pospos_base,oN1 gQ3"> "wH
#define T11 wE Cmpgt_powpow_imm_base,q2 Cmpgt_powpow_imm_base,0 qK"cmpgt_"hH" > "wW
#define U11 hG Cmple_pow_imm_negneg,q2 Cmple_pow_imm_negneg dW1 hS hJ3 gL3
#define W11 hG Cmple_pow_imm_negpos,q2 Cmple_pow_imm_negpos dW1 hT hJ3 gN3
#define Y11 {1,qJ Cmple_pow_imm_posneg,q2 Cmple_pow_imm_posneg dW1 d0 hJ3 gT3
#define S21 {1,qJ Cmple_pow_imm_pospos,q2 Cmple_pow_imm_pospos dW1 d1 hJ3 h23
#define T21 {1,qJ Cmple_pow_imm_pospos_base,q2 Cmple_pow_imm_pospos_base dW1 gQ3"<= "wH
#define U21 wE Cmple_powpow_imm_base,q2 Cmple_powpow_imm_base,0 qK"cmple_"hH hJ3 wW
#define W21 hG Cmplt_pow_imm_negneg,q2 Cmplt_pow_imm_negneg,oA1 hS" < "gL3
#define Y21 hG Cmplt_pow_imm_negpos,q2 Cmplt_pow_imm_negpos,oA1 hT" < "gN3
#define S31 {1,qJ Cmplt_pow_imm_posneg,q2 Cmplt_pow_imm_posneg,oA1 d0" < "gT3
#define T31 {1,qJ Cmplt_pow_imm_pospos,q2 Cmplt_pow_imm_pospos,oA1 d1" < "h23
#define U31 {1,qJ Cmplt_pow_imm_pospos_base,q2 Cmplt_pow_imm_pospos_base,oA1 gQ3"< "wH
#define W31 wE Cmplt_powpow_imm_base,q2 Cmplt_powpow_imm_base,0 qK"cmplt_"hH" < "wW
#define Y31 hG Cmpne_pow_imm_negneg,q2 Cmpne_pow_imm_negneg dX1 hS hC3 gL3
#define S41 hG Cmpne_pow_imm_negpos,q2 Cmpne_pow_imm_negpos dX1 hT hC3 gN3
#define T41 {1,qJ Cmpne_pow_imm_posneg,q2 Cmpne_pow_imm_posneg dX1 d0 hC3 gT3
#define U41 {1,qJ Cmpne_pow_imm_pospos,q2 Cmpne_pow_imm_pospos dX1 d1 hC3 h23
#define W41 {1,qJ Cmpne_pow_imm_pospos_base,q2 Cmpne_pow_imm_pospos_base dX1 gQ3"!= "wH
#define Y41 wE Cmpne_powpow_imm_base,q2 Cmpne_powpow_imm_base,0 qK"cmpne_"hH aZ2 wW
#define S51 hG Cmpzz_pow_imm_negneg,q2 Cmpzz_pow_imm_negneg,q71"_imm_negneg"oN d41" < "gU3 a6 d41 hJ3 gU3 a8 d41" > "gU3 oS d41 hB3"-0.015625"a7 d41 hC3 gU3 dV gJ",-3) = "gL3
#define T51 hG Cmpzz_pow_imm_negpos,q2 Cmpzz_pow_imm_negpos,q71"_imm_negpos"oN d51" < "h33 a6 d51 hJ3 h33 a8 d51" > "h33 oS d51 hB3"0.0625"a7 d51 hC3 h33 dV gJ",-2) = "gN3
#define U51 {1,qJ Cmpzz_pow_imm_posneg,q2 Cmpzz_pow_imm_posneg,q71"_imm_posneg"oN oB1" < "hT3 a6 oB1 hJ3 hT3 a8 oB1" > "hT3 oS oB1 hB3"-125"a7 oB1 hC3 hT3 dV gJ",3) = "gT3
#define W51 {1,qJ Cmpzz_pow_imm_pospos,q2 Cmpzz_pow_imm_pospos,q71"_imm_pospos"oN oC1" < 25)"a6 oC1 hJ3"25)"a8 oC1" > 25)"oS oC1 hB3"25"a7 oC1 hC3"25)"dV gJ",2) = "h23
#define Y51 {1,qJ Cmpzz_pow_imm_pospos_base,q2 Cmpzz_pow_imm_pospos_base,q71"_imm_pospos_base"oN d03"< "q61 a6 d03"<= "q61 a8 d03"> "q61 oS d03">= "q61 o41 d03"!= "q61 dV gR3"= "wH
#define S61 wE Cmpzz_powpow_imm_base,q2 Cmpzz_powpow_imm_base,0 qK"cmpzz_powpow_imm_base"oN gC3" < "gA1 a6 gC3 hJ3 gA1 a8 gC3" > "gA1 oS gC3 hB3 gA1 o41 gC3 aZ2 gA1 dV qQ1" = "wW
#define T61 {2,-4,4,mY1,q2 If_extract_sin,q2 If_extract_sin,0 mJ"tract_sin",dX", sin(y), "gW3
#define U61 oO If_join_add,q2 If_join_add,0 qK"if_join_add",dX dA" +"aO1
#define W61 oO If_join_and,q2 If_join_and,0 qK"if_join_and",dX dA" &"aO1
#define Y61 oO If_join_max,q2 If_join_max,0 qK"if_join_max","max("dX dA", "hU3")))"},
#define S71 oO If_join_min,q2 If_join_min,0 qK"if_join_min","min("dX dA", "hU3")))"},
#define T71 oO If_join_mul,q2 If_join_mul,0 qK"if_join_mul",dX dA" *"aO1
#define U71 oO If_join_or,q2 If_join_or,0 qK"if_join_or",dX dA" | "hU3"))"},
#define W71 {3,hX Ifabsnot,q2 Ifabsnot wP"ifabsnot","if(!(sin(x)+1.2), y,z"g31
#define Y71 {3,hX Ifconst,q2 Ifconst wP"ifconst","if(1, x,y) + if(0,z,y"g31
#define S81 {4 m72 Ififconst,q2 Ififconst,0,"w,"mH"ififconst","if("dX",1,y),z,w) + if(if(w,z,0),"oT2
#define T81 {3 m72 Ifnot,q2 Ifnot wP"ifnot","if(!x, y,z"g31
#define U81 {2,hX Muland2,q2 Muland2,0 qK"muland2",wN2" !!y"},
#define W81 {3,hX Muland2plus,q2 Muland2plus wP"muland2plus",wN2" !!y * z"},
#define Y81 {3,hX Muland3,q2 Muland3 wP"muland3",wN2" !!y * !!z"},
#define S91 {2,hX Mulandlt,q2 Mulandlt,0 qK"mulandlt",wN2" (y<0"g31
#define T91 {2,wO2 1,hF2,q2 Mulimmlog,q2 Mulimmlog,0 qK"mulimmlog","log(if(1,5,0)*x*y"g31
#define U91 {2,hX Mulnor2,q2 Mulnor2,0 qK"mulnor2",hM3},
#define W91 {3,hX Mulnor2plus,q2 Mulnor2plus wP"mulnor2plus",hM3" * z"},
#define Y91 {3,hX Mulnor3,q2 Mulnor3 wP"mulnor3",hM3" * !z"},
#define SA1 aQ2 Negceil,q2 Negceil,gQ"negceil","ceil(x*("gY2"-abs(x)-1))"},
#define TA1 aQ2 Negcos,q2 Negcos,gQ"negcos","cos"wP2
#define UA1 aQ2 Negcosh,q2 Negcosh,gQ"negcosh","cosh"wP2
#define WA1 aQ2 Negfloor,q2 Negfloor,gQ"negfloor","floor(x*("gY2"-abs(x)-1))"},
#define YA1 aQ2 Negsin,q2 Negsin,gQ"negsin","sin(x*"qF1
#define SB1 aQ2 Negsinh,q2 Negsinh,gQ"neg"wL2,wL2 wP2
#define TB1 {1,hX Posnot,q2 Posnot,gQ"posnot","!(sin(x) + 1.2"g31
#define UB1 {1,hX Posnotnot,q2 Posnotnot,gQ"posnotnot","!!(sin(x) + 1.2"g31
#define WB1 {1,wO2 1,hF2,q2 Powimmaddimmlog,q2 Powimmaddimmlog mO1"immaddimmlog","pow(5, log(x)+1"g31
#define YB1 {1,wO2 2,hF2,q2 Powimmlog,q2 Powimmlog mO1"immlog","pow(3, log(x)) + pow(5, log(x)*sin(x))"},
#define SC1 {a11 Powmulimm_fnen,q2 Powmulimm_fnen oC dN1"mulimm_fnen",oD1"^(-8"g31
#define TC1 {2 oJ gR Powmulimm_fnep,q2 Powmulimm_fnep oC dN1"mulimm_fnep",oD1"^(4"g31
#define UC1 {1,-3,-1,mY1,q2 Powmulimm_fnfn,q2 Powmulimm_fnfn mO1"mulimm_fnfn","((-5.1)*x)^(-7.1"g31
#define WC1 {2 oJ gR Powmulimm_fnfp,q2 Powmulimm_fnfp oC dN1"mulimm_fnfp",oD1"^7.1"},
#define YC1 {2 oJ gR Powmulimm_fpfp,q2 Powmulimm_fpfp oC dN1"mulimm_fpfp","(5.1*x*y)^7.1"},
#define SD1 {1,hX Sub1cos2,q2 Sub1cos2,gQ"sub1cos2","1-cos(x)^2"},
#define TD1 {1,hX Sub1sin2,q2 Sub1sin2,gQ"sub1sin2","1-"qA2"^2"},
#define UD1 {1,N(-9.42477796076937971538793014983850865259),N(9.42477796076937971538793014983850865259),N(0.785398163397448309615660845819875721049292349)qN,q2 Trig_modulo,q2 Trig_modulo,gQ"trig_modulo","cos(x+pi"qG1"2/3"qG1"5/2"qG1"6/2"qG1 wQ2 gM3 oE1")"oX1"2/3)"oX1"5/2)"oX1"6/2)"oX1 wQ2 gM3"cos(x-pi"dG1"2/3"dG1"5/2"dG1"6/2"dG1 wQ2"  "oF1")"wR2"2/3)"wR2"5/2)"wR2"6/2)"wR2"7/2"g31
#define WD1 {1 oJ hF2,q2 Trunc_from_if,q2 Trunc_from_if,gQ"trunc_from_if",dX">0,  "h63 dD2">=0, "h63 dD2"<0,  "h43 dD2"<=0,"hN3">0, "hN3">=0,"hN3"<0,  "h63" 10*"dX"<=0, floor(x),ceil"g91
#define YD1 {1,N(-0.7),N(0.7),N(0.28)qN,g1 t5,g1 t5 oC,oE"5","sub(sin(x)+csc(x),cos"g91
#define SE1 {2 oJ N(.25)qN,g1 t42,g1 t42 oC",y",oE"42","sqrt(x*x) + 1.5*((y*y)^.25) + hypot(x"mI1
#define TE1 {1,-100,-1,mS2,g1 t51,g1 t51 oC,oE"51","log"gZ2
#define UE1 {1,N(.05),1,N(.01)qN,g1 t57,g1 t57 oC,oE"57","cosh(a"wL2 g91
#define WE1 {2,-2,2,N(1.2)qN,g1 t59,g1 t59 oC",y",oE"59","cosh(x^2) + tanh(y^2"g31
#define YE1 {1,-1000,1000,N(.25)qQ3 t1 qL t1 gD3"1"aY2"4/2 + (1+(2+3)) + x*x+x+1+2+3*4+5*6*\n7-8*9"},
#define SF1 {1,-1000,1000,g92 t2 qL t2 gD3"2","2 * x+ sin ( x ) / .5 + 2-sin(x)*sin(x)"},
#define TF1 {3,-7,7,mS2 qL t3 qL t3 qP3"3","(x=y & y=x)+  1+2-3.1*4e2/.5 + x*x+y*y+z*z  + (x&x) + (y|y"g31
#define UF1 {2,-10,10,mS2 qL t4 qL t4 oC oG1"4","( ((( ( x-y) -( ((y) *2) -3)) )* 4))+sin(x)*cos(y)-cos(x)*sin(y"g31
#define WF1 {2,g83 8,mQ1 t5 qL t5,0,"__A5_x08,o__5_0AB_",oM"5","__A5_x08^o__5_0AB_"},
#define YF1 {2,g83 10,2 qQ3 t6 qL t6 oC oG1"6",dX">0&y>0,x*y+eval(x-1,y-1),0)+1"},
#define SG1 {qX3 N(.01)qQ3 t7 qL t7 gD3"7","cos(x)*sin(1-x)*(1-cos(x/2)*sin(x*5))"},
#define TG1 {2,-8,8,mC2 t8 qL t8 oC oG1"8",aA2"(x,y)+max(x"mI1
#define UG1 {3,1,15,N(.7)qQ3 t9 qL t9 qP3"9","1.5+x*y-2+4/8+z+z+z+z+x/(y*z"g31
#define WG1 {3,1,4,N(.3)qQ3 t10 qL t10 qP3"10","1+sin(cos(max(1+2+3+4+5, x+y+z)))+2"},
#define YG1 {3,1,19,N(.8)qQ3 t11 qL t11 qP3"11","-(-(-(-(-x))-x))+y*1+log(1.1^z"g31
#define SH1 {1,1,2000,mS2 qL t12 qL t12 gD3"12","1/log(10^((3-2)/log(x)))"},
#define TH1 {2,-30,30,mS2 qL t13 qL t13 oC oG1"13","x^3 * x^4 + y^3 * y^5"},
#define UH1 {1,-50,50,g92 t14 qL t14 gD3"14"aY2"pi + sin(2*pi) + CONST"},
#define WH1 {2,N(1.1),6,N(.07)qQ3 t15 qL t15 oC oG1"15","x^y/log("aU2" log(x)/log("aU2" log(x^y"g31
#define YH1 {2,1,17,mC2 t18 qL t18 oC oG1"18","- ( - ( - ( - 5 ) ) ) * -x^ -y^-2"},
#define SI1 {2,-4,4,g92 t22 qL t22 oC oG1"22","3.5doubled + 10*x tripled - sin(y)doubled"gS3"100"d92" doubled-y tripled)doubled + 5/2doubled + 1.1^x doubled +  1.1doubled^x doubled"},
#define TI1 {1,-1000,1000,g92 t23 qL t23 gD3"23","(x/(2*acos(0)))*180"},
#define UI1 {3,1,3,mC2 t25 qL t25,0,"a,b,c",oM"25","a^b^c + a^-2 * (-b^2"q33"-b^-c"g31
#define WI1 {1,-100,100,g83 true qL t26_deg qL t26_deg gD3"26_deg",q43" cos(x*1.5) + asin(x/110) + acos(x/120"g31
#define YI1 {2,g83 N(.9),N(.025)qQ3 t27 qL t27 oC oG1"27","abs(x)+acos(x)+asin(x)+atan(x)+"aA2"(x,y)+ceil(x)+cos(x)+cosh(x)+cot(x)+csc"dI2" "dB2 mI1
#define SJ1 {2,g83 N(.9),N(.025)qQ3 t28 qL t28 oC oG1"28","exp(x)+floor(x)+int(x)+log(x)+log10(x)+max(x,y)+min(x,y)+sec(x)+sin(x)+sinh(x)+sqrt(x)+tan(x)+tanh(x)+ceil(y)+trunc(y"g31
#define TJ1 {2,3,10,dU1 t30 qL t30 oC oG1"30","x - y*1 + (x%y) + x / (y^1.1) + 2^3 + 5%3 + x^(y^0) + x^0.5"},
#define UJ1 {3,g83 4,N(.35)qQ3 t31 qL t31 qP3"31","x - (y*(y*(y*-1))*1) + log(x*exp"h32")^y) - log(x^y)"gS3"exp"h32")^log(x+6) + 10^("wT2"6"hN2"y+6)*log(z+6"hN2"10)) -"gM3"exp"h32")^("wT2"6)*y) - 5^("wT2"7"hN2"5)) + "gA2"^3 * "gA2"^2 /  "gA2"^4"},
#define WJ1 {3,1,2,N(.05)qQ3 t32 qL t32 qP3"32","x"mO"+y/y-min(3,4)-x-max(4,3)+max(3,4)-min(4,3)+0+(z*1)"mO"+(x-2+2)+(x*0.5*2)+y*0"gM3" +min(min(min(4.0,x),1.0),min(x,min(min(y,4.0),z)))"mO"+max(max(max(4.0,x),1.0)"mP1"x(max(y,4.0),z)))"mO"+(abs(1)+acos"h32")+asin(1.0)+atan"h32")+ceil(1.1)+cos(0.0)"gM3"  +cosh(0.0)+floor(1.1)+log"h32")+sin(0.0)+sinh(0.0)+tan"h32")"gM3"  +tanh"h32")+"aA2"(1.0,1.0))"mO"+(x-(y-z))"mO"+(x+y)"oB2"y)"mO"+max(x"mP1"x(x,max(x,x))))*-1.0"gM3" +(z-z)"mO"+1/sin(x/5)"mT2"cos(y/5)"mT2"tan(z/5)"mO"+log10(cot(z/5) + csc(y/5) + sec(x/5))"mO"+log(30+x)*log(40+y"hN2"50+z)"mO"+sin(x/57.295779513082320877)"mO"+asin(x/10)*57.295779513082320877"gM3" +floor(-x)"mT2"ceil(x)"mO"+sqrt(5 * 0.2) +(-"wU2 wU2"x+-x)"},
#define YJ1 {2,-2,2,g92 t33 qL t33 oC oG1"33","sin(sqrt(10-x*x+y*y))+cos(sqrt(15-x*x-y*y))+sin(x*x+y*y"g31
#define SK1 {qX3 g92 t37 qL t37 gD3"37","5 + 7.5*8 / 3 - 2^4*2 + 7%2+4 + x"},
#define TK1 {3,N(-.9),N(.9),g92 t38 qL t38 qP3"38","a"wL2 dI2" 1.5*"mR2"(y+3) + 2.5*atanh(z"g31
#define UK1 {3,N(-1.3),N(1.3),mQ1 t39 qL t39 qP3"39","sin(x+cos(y*1.5))-cos(x+sin(y*1.5))+z*z*z*sin(z*z*z-x*x-y*y)-"gM3"cos(y*1.5)*sin(x+cos(y*1.5))+x*y*z+x*y*2.5+x*y*z*cos(x)+x*y*cos(x)+x*z*cos(x)+  y*z*2.5+(x*y*z*cos(x)-x*y*z-y*cos(x)-x*z*y+x*y+x*z-cos(x)*x)"},
#define WK1 {3,N(-1.3),N(1.3),N(.075)qQ3 t40 qL t40 qP3"40","(x+x+x+x+x+x+x+x+x+x+x+y"a5")*"gM3"(x+x+x+x+x+x+x+x+x+x+x+y"a5")+"gM3"2*(x+x+x+x+x+x+x+x+x+x+x+y"a5")-"gM3"x*y*(x+x+x+x+x+x+x+x+x+x+x+y"a5")+  x*(x+x+x+x+x+x+x+x+x+x+x+y"a5 g31
#define YK1 {3,-2,2,mQ1 t41 qL t41 qP3"41"aY2"3+x*y+x*z+x*sin(y*z) -"gM3 wV2"4"gS3 qI1"))*x"gS3 wV2"y +  "wV2"z"},
#define SL1 {1,-100,100,N(.03)qQ3 t43 qL t43 gD3"43","log(x*x)+abs("m12"abs(x)+1))"},
#define TL1 {1,0,100,N(.125)qQ3 t44 qL t44 gD3"44","(x^2"dD1"8)"gS3"1.1"d92"^3"dD1"7)"gS3"1.2"d92"^4"dD1"6)"gS3"1.3"d92"^5"dD1"5)"gS3"1.4"d92"^6"dD1"6)"gS3"1.5"d92"^7"dD1"4)"gS3"1.6"d92"^8"dD1"3)"gS3"1.7"d92"^9"dD1"2) +  1.8*(sqrt(abs(-sqrt(x))^3))"},
#define UL1 {qX3 N(.025)qQ3 t45 qL t45 gD3"45","(x^2"dD1"7) + 1.1"d92"^4"dD1"5) + 1.2"d92"^6"dD1"3"g31
#define WL1 {2,N(-.9),N(.9),mQ1 t46 qL t46 oC oG1"46","abs(floor(acos(x)+4)) + 1.1*abs(floor(acos(y)+1.5)) +  ("q92" < (acos(y)-10)) + 1.2*max(-4, acos(x)) + 1.3*min(9, acos(x)-9"g31
#define YL1 {2 oJ g92 t47 qL t47 oC oG1"47","1.25*(exp(x)+"m12"-"mL1" 1.5*("m12"y)-exp(-y)) +  1.75*(("m12"-x)+exp(x))/2) + 2.0*(("m12"-x)-exp(x))/2) + 2.25*(cosh(y)+sinh(y))"},
#define SM1 {1,2,N(1e9),N(1.2e7)qQ3 t48 qL t48 gD3"48",wL2"((log(x)/5+1)*5) + 1.2*cosh((log(x)/log(2)+1)*log"hW3"!(x | !(x/4))"},
#define TM1 {1,-100,100,N(.05)qQ3 t49 qL t49 gD3"49",aA2"(0, x) + (-4"d92"-100))^3.3"},
#define UM1 {qX3 mS2 qL t52 qL t52 gD3"52","x + "h32"+2.0+3.0+4.0-5.0-6.0-7.0-8.0)/3.0"gS3"4.0*(1.0+sin(2.0)+cos(4.0*5.0+6.0)/2.0) + cos(0.5)*tan(0.6+0.2) -  1.1/log(2.1)*sqrt(3.3) + 2^3"},
#define WM1 {2,0,10,mY1 qL t53 qL t53 oC oG1"53","(x&"aU2" 4*(int(x/10)|int(y/10)) + 8*((-!-!-x)+(!-!-!y)) + 16*(-------x + !!!!!!!y"g31
#define YM1 {2,-10,100,mS2 qL t54 qL t54 oC oG1"54","(x<y"m42"<=y"m42">y"m42">=y)+"gM3"(x=y"m42"!=y)+(x&y"m42"|y)+"gM3"(!x)+(!!x)+"gM3"!((x<y)&(x<3))+  !!(!(x>y)|(x>3))"},
#define SN1 {2,1,100,mS2 qL t55 qL t55 oC oG1"55","(x^1.2 < 0"q33"y^2.5 < 0) + 2*(x*x<0) + 3*(y^3<0) + 4"d92"^4<0"g31
#define TN1 {1,N(.25),100,N(.25)qQ3 t56 qL t56 gD3"56","1.75e21%x"},
#define UN1 {1 oJ N(0.2)qQ3 t59 qL t59 gD3"59","(cos(x) < sin(x))"gS3"(cos(x)-sin(x))"gS3"sub(sinh(x)-cosh(x), "wL2"(x)/cosh(x)) +  sqrt(cos(x)^2+sin(x)^2"g31
#define WN1 {1,N(1e-6),4000,mD Log qB Log wY"log",gE2
#define YN1 g6 Abscos q4 Abscos w11"abscos","cos(abs"g91
#define SO1 g6 Abscosh q4 Abscosh w11"abscosh","cosh(abs"g91
#define TO1 {1 gS Abseq0 q4 Abseq0 q4 Abseq0 gT"abseq0"mJ1"=0"q33"0=abs"g91
#define UO1 {1,N(0.001),N(0.9),N(0.01)qN q4 Absevenconstpow q4 Absevenconstpow w11"absevenconstpow",gY2" ^ 1506"},
#define WO1 {2,N(0.001),N(0.9),N(0.01)qN q4 Absmulevenconstpow q4 Absmulevenconstpow oC gW"absmulevenconstpow","(abs(x)*y) ^ 1506"},
#define YO1 {1 gS mV2 q4 mV2 q4 mV2 gT"absneq0"mJ1"=0"q33"0=abs"g91
#define SP1 {1 gS Add q4 Add q4 Add gT"add","5+3+x"},
#define TP1 {1 gS Add0 q4 Add0 q4 Add0 gT"add0","x+0+x"},
#define UP1 {1 gS And q4 And q4 And gT"and","(5&3"dE2"5&0)+(0&5)+(0&0"g31
#define WP1 {1 d3 Cmp_acos q4 Cmp_acos w11"cmp_acos","1"o0"=acos("wQ gM3"2"o0"<acos("wQ gM3"4"o0"<=acos("wQ wW2 o0">acos("wQ h42 o0">=acos("wQ"  32"o0"!=acos(0.75))"},
#define YP1 {1 d3 Cmp_acos_outrange q4 Cmp_acos_outrange w11"cmp_acos_outrange","1"o0"=2"mU2 o0"<2)"gS3"4"o0"<=2) +"wW2 o0">2) +"h42 o0">=2) +  32"o0"!=2"g31
#define SQ1 {1,oI1 mW2 q4 mW2 q4 mW2 gT"cmp_add","1"aH aT1 aH aU1 aH oJ1 aH gC2 aH m7 aH oU1
#define TQ1 {1 d3 Cmp_asin q4 Cmp_asin w11"cmp_asin","1"o1"=a"q52 gM3"2"o1"<a"q52 gM3"4"o1"<=a"q52 wW2 o1">a"q52 h42 o1">=a"q52"  32"o1"!=asin(0.75))"},
#define UQ1 {1 d3 Cmp_asin_outrange q4 Cmp_asin_outrange w11"cmp_asin_outrange","1"o1"=2"mU2 o1"<2)"gS3"4"o1"<=2) +"wW2 o1">2) +"h42 o1">=2) +  32"o1"!=2"g31
#define WQ1 {oI Cmp_atan q4 Cmp_atan w11"cmp_atan","1"qR1"=atan"wL1 qR1"<atan"wM1 qR1"<=atan"wN1 qR1">atan"wO1 qR1">=atan"aR1 qR1"!=atan"dP1
#define YQ1 {oI Cmp_exp q4 Cmp_exp w01"p","1"aQ1"=exp"hW3"2"aQ1"<exp"hW3"4"aQ1"<=exp"hW3" 8"aQ1">exp"hW3"16"aQ1">=exp"hW3"32"aQ1"!=exp"dP1
#define SR1 {oI Cmp_exp2 q4 Cmp_exp2 w01"p2","1"aS1"=exp2"hW3"2"aS1"<exp2"hW3"4"aS1"<=exp2"hW3" 8"aS1">exp2"hW3"16"aS1">=exp2"hW3"32"aS1"!=exp2"dP1
#define TR1 {oI Cmp_exp2_neg q4 Cmp_exp2_neg w01"p2_neg","1"aS1"=-4) + 2"aS1"<-4) + 4"aS1"<=-4"g41 aS1">-4) + 16"aS1">=-4"q82 aS1"!=-4"g31
#define UR1 {oI Cmp_exp_neg q4 Cmp_exp_neg w01"p_neg","1"aQ1"=-4) + 2"aQ1"<-4) + 4"aQ1"<=-4"g41 aQ1">-4) + 16"aQ1">=-4"q82 aQ1"!=-4"g31
#define WR1 {1,oH Cmp_log2_nn q4 Cmp_log2_nn w11"cmp_log2_nn","1"mC1"=-2"oU wJ aK mC1 wZ mC1 a0 mC1 aO mC1 oH1
#define YR1 {1,oH Cmp_log2_np q4 Cmp_log2_np w11"cmp_log2_np","1"mC1"=log2"wL1 mC1"<log2"wM1 mC1"<=log2"wN1 mC1">log2"wO1 mC1">=log2"aR1 mC1"!=log2"dP1
#define SS1 {oI Cmp_log2_pn q4 Cmp_log2_pn w11"cmp_log2_pn","1"d9"=-2"mU2 d9 aK d9 wZ d9 a0 d9 aO d9 oH1
#define TS1 {oI Cmp_log2_pp q4 Cmp_log2_pp w11"cmp_log2_pp","1"d9"=log2"wL1 d9"<log2"wM1 d9"<=log2"wN1 d9">log2"wO1 d9">=log2"aR1 d9"!=log2"dP1
#define US1 {1,oH Cmp_log10_nn q4 Cmp_log10_nn w11"cmp_log10_nn","1"dF"=-2"mU2 dF aK dF wZ dF a0 dF aO dF oH1
#define WS1 {1,oH Cmp_log10_np q4 Cmp_log10_np w11"cmp_log10_np","1"dF"=log10"wL1 dF"<log10"wM1 dF"<=log10"wN1 dF">log10"wO1 dF">=log10"aR1 dF"!=log10"dP1
#define YS1 {oI Cmp_log10_pn q4 Cmp_log10_pn w11"cmp_log10_pn","1"hR"=-2"mU2 hR aK hR wZ hR a0 hR aO hR oH1
#define ST1 {oI Cmp_log10_pp q4 Cmp_log10_pp w11"cmp_log10_pp","1"hR"=log10"wX2 wK1 hR"<log10"wX2 gS3"4"hR"<=log10"wX2" +"wW2 hR">log10"wX2" +"h42 hR">=log10"wX2" +  32"hR"!=log10"wX2},
#define TT1 {1,oH Cmp_log_nn q4 Cmp_log_nn w11"cmp_log_nn","1"hP1"=-2"mU2 hP1 aK hP1 wZ hP1 a0 hP1 aO hP1 oH1
#define UT1 {1,oH Cmp_log_np q4 Cmp_log_np w11"cmp_log_np","1"hP1"=log"wL1 hP1"<log"wM1 hP1"<=log"wN1 hP1">log"wO1 hP1">=log"aR1 hP1"!=log"dP1
#define WT1 {oI Cmp_log_pn q4 Cmp_log_pn w11"cmp_log_pn","1"hQ1"=-2"mU2 hQ1 aK hQ1 wZ hQ1 a0 hQ1 aO hQ1 oH1
#define YT1 {oI Cmp_log_pp q4 Cmp_log_pp w11"cmp_log_pp","1"hQ1"=log"wL1 hQ1"<log"wM1 hQ1"<=log"wN1 hQ1">log"wO1 hQ1">=log"aR1 hQ1"!=log"dP1
#define SU1 {1,oI1 gB2 q4 gB2 q4 gB2 gT"cmp_mulneg","1"wZ2 aT1 wZ2 aU1 wZ2 oJ1 wZ2 gC2 wZ2 m7 wZ2 oU1
#define TU1 {1,oI1 gD2 q4 gD2 q4 gD2 gT"cmp_mulpos","1"a02 aT1 a02 aU1 a02 oJ1 a02 gC2 a02 m7 a02 oU1
#define UU1 {1,oI1 mX2 q4 mX2 q4 mX2 gT"cmp_neg","1"aV1"=4) + 2"aV1"<4) + 4"aV1"<=4"g41 aV1">4) + 16"aV1 m7 aV1 oU1
#define WU1 mB Cmp_powx_n_n q4 Cmp_powx_n_n dQ1"_n_n","1"g8"="w3" "aL g8"<"w3" "aM g8"<="w3" "aN g8">"w3 w9 g8">="w3 qR3 g8"!="w3},
#define YU1 mB Cmp_powx_n_p q4 Cmp_powx_n_p dQ1"_n_p","1"g8"="w2" "aL g8"<"w2" "aM g8"<="w2" "aN g8">"w2 w9 g8">="w2 qR3 g8"!="w2},
#define SV1 qJ1 Cmp_powx_nn q4 Cmp_powx_nn dQ1"_nn","1"g8 q62 g8 q72 g8 aW1 g8 h52 g8">=-4"q82 g8"!=-4"g31
#define TV1 qJ1 Cmp_powx_np q4 Cmp_powx_np dQ1"_np","1"g8 aT1 g8 aU1 g8 oJ1 g8 gC2 g8 m7 g8 oU1
#define UV1 mB Cmp_powx_p_n q4 Cmp_powx_p_n dQ1"_p_n","1"oQ"="w3" "aL oQ"<"w3" "aM oQ"<="w3" "aN oQ">"w3 w9 oQ">="w3 qR3 oQ"!="w3},
#define WV1 mB Cmp_powx_p_p q4 Cmp_powx_p_p dQ1"_p_p","1"oQ"="w2" "aL oQ"<"w2" "aM oQ"<="w2" "aN oQ">"w2 w9 oQ">="w2 qR3 oQ"!="w2},
#define YV1 qJ1 Cmp_powx_pn q4 Cmp_powx_pn dQ1"_pn","1"aX1 q62 aX1 q72 aX1 aW1 aX1 h52 aX1">=-4"q82 aX1"!=-4"g31
#define SW1 qJ1 Cmp_powx_pp q4 Cmp_powx_pp dQ1"_pp","1"aX1 aT1 aX1 aU1 aX1 oJ1 aX1 gC2 aX1 m7 aX1 oU1
#define TW1 hE Cmp_powy_n_n q4 Cmp_powy_n_n wJ1"y_n_n","1"aY1"="h03"2"aY1"<"h03"4"aY1"<="h03"8"aY1">"h03"16"aY1">="dT" 32"aY1"!=(x^-6.1))"},
#define UW1 hE Cmp_powy_n_p q4 Cmp_powy_n_p wJ1"y_n_p","1"aY1"=(x"aP" "aL aY1"<(x"aP" "aM aY1"<=(x"aP" "aN aY1">(x"aP w9 aY1">=(x"aP qR3 aY1"!=(x"aP},
#define WW1 hE Cmp_powy_nn q4 Cmp_powy_nn wJ1"y_nn","1"aY1 q62 aY1 q72 aY1 aW1 aY1 h52 aY1">=-4"q82 aY1"!=-4"g31
#define YW1 hE Cmp_powy_np q4 Cmp_powy_np wJ1"y_np","1"aY1 aT1 aY1 aU1 aY1 oJ1 aY1 gC2 aY1 m7 aY1 oU1
#define SX1 hE Cmp_powy_p_n q4 Cmp_powy_p_n wJ1"y_p_n","1"h6"="h03"2"h6"<"h03"4"h6"<="h03"8"h6">"h03"16"h6">="dT" 32"h6"!=(x^-6.1))"},
#define TX1 hE Cmp_powy_p_p q4 Cmp_powy_p_p wJ1"y_p_p","1"h6"=(x"aP" "aL h6"<(x"aP" "aM h6"<=(x"aP" "aN h6">(x"aP w9 h6">=(x"aP qR3 h6"!=(x"aP},
#define UX1 hE Cmp_powy_pn q4 Cmp_powy_pn wJ1"y_pn","1"h6 q62 h6 q72 h6 aW1 h6 h52 h6">=-4"q82 h6"!=-4"g31
#define WX1 hE Cmp_powy_pp q4 Cmp_powy_pp wJ1"y_pp","1"h6 aT1 h6 aU1 h6 oJ1 h6 gC2 h6 m7 h6 oU1
#define YX1 {oI Cmp_sinh q4 Cmp_sinh,d8 wL2,"1"qS1"="wL2 wL1 qS1"<"wL2 wM1 qS1"<="wL2 wN1 qS1">"wL2 wO1 qS1">="wL2 aR1 qS1"!="wL2 dP1
#define SY1 {1,oI1 mY2 q4 mY2 q4 mY2 gT"cmp_sqr","1"wK"=16) + 2"wK"<16) + 4"wK"<=16"g41 wK">16) + 16"wK">=16"q82 wK"!=16"g31
#define TY1 {1,oI1 mR1 q4 mR1 q4 mR1 gT"cmp_sqr_neg","1"wK"=-16) + 2"wK"<-16) + 4"wK"<=-16"g41 wK">-16) + -16"wK">=-16"q82 wK"!=-16"g31
#define UY1 {1,-4,4,hF2 q4 Cmp_tanh q4 Cmp_tanh w11"cmp_tanh","1"o4"=tanh("wQ gM3"2"o4"<tanh("wQ gM3"4"o4"<=tanh("wQ wW2 o4">tanh("wQ h42 o4">=tanh("wQ"  32"o4"!=tanh(0.75))"},
#define WY1 {1,-4,4,hF2 q4 Cmp_tanh_outrange q4 Cmp_tanh_outrange w11"cmp_tanh_outrange","1"o4"=2"mU2 o4"<2)"gS3"4"o4"<=2) +"wW2 o4">2) +"h42 o4">=2) +  32"o4"!=2"g31
#define YY1 {1 gS Cmpeq q4 Cmpeq q4 Cmpeq gT"cmpeq","(5=3"dE2"4=4"g31
#define SZ1 {1 gS Cmpge q4 Cmpge q4 Cmpge gT"cmpge","(5>=3"dE2"4>=8"g31
#define TZ1 {1 gS Cmpgt q4 Cmpgt q4 Cmpgt gT"cmpgt","(5>3"dE2"4>8"g31
#define UZ1 {1 gS Cmple q4 Cmple q4 Cmple gT"cmple","(5<3"dE2"4<8"g31
#define WZ1 {1 gS Cmplt q4 Cmplt q4 Cmplt gT"cmplt","(5<3)+x"},
#define YZ1 {1 gS Cmpne q4 Cmpne q4 Cmpne gT"cmpne","(5!=3"dE2"4!=4"g31
#define Sa1 {1 gS Div q4 Div q4 Div gT"div","(5/4)+x"},
#define Ta1 {1 gS Div1 q4 Div1 q4 Div1 gT"div1","x/1+x"},
#define Ua1 {1 gS Divxx q4 Divxx q4 Divxx gT"divxx","x+x/x+x"},
#define Wa1 {1 gS Eq0 q4 Eq0 q4 Eq0 gT"eq0","(x=0"q33"0=x)"},
#define Ya1 {1 gS Eq1 q4 Eq1 q4 Eq1 gT"eq1","(!x=1"g31
#define Sb1 {wD mZ2 q4 mZ2 q4 mZ2 gT"ge0_abs"mJ1 h73 hF3 h83 hG3
#define Tb1 {1 d3 Ge0_neg q4 Ge0_neg w11"ge0_neg"aZ1 h73 oR h83 gW3
#define Ub1 {1 d3 Ge0_pos q4 Ge0_pos w11"ge0_pos","("q92 h73 gX3 h83 h53
#define Wb1 {wD q03 q4 q03 q4 q03 gT"ge1_abs"mJ1 h93 hF3 hA3 hG3
#define Yb1 {1 d3 Ge1_neg q4 Ge1_neg w11"ge1_neg"aZ1 h93 oR hA3 gW3
#define Sc1 {1 d3 Ge1_pos q4 Ge1_pos w11"ge1_pos","("q92 h93 gX3 hA3 h53
#define Tc1 {1 d3 Gehalf q4 Gehalf w11"gehalf","x>=0.5"},
#define Uc1 {wD q13 q4 q13 q4 q13 gT"gt0_abs"mJ1 hO3 hF3 hP3 hG3
#define Wc1 {1 d3 Gt0_neg q4 Gt0_neg w11"gt0_neg"aZ1 hO3 oR hP3 gW3
#define Yc1 {1 d3 Gt0_pos q4 Gt0_pos w11"gt0_pos","("q92 hO3 gX3 hP3 h53
#define Sd1 {wD q23 q4 q23 q4 q23 gT"gt1_abs"mJ1 hQ3 hF3 hR3 hG3
#define Td1 {1 d3 Gt1_neg q4 Gt1_neg w11"gt1_neg"aZ1 hQ3 oR hR3 gW3
#define Ud1 {1 d3 Gt1_pos q4 Gt1_pos w11"gt1_pos","("q92 hQ3 gX3 hR3 h53
#define Wd1 {1 d3 Gtminushalf q4 Gtminushalf w11"gtminushalf","x>-0.5"},
#define Yd1 {1,qY3 dH2 dH2 dH2 gT"immsub","x-5"},
#define Se1 {1 d3 Leminushalf q4 Leminushalf w11"leminushalf","x<=-0.5"},
#define Te1 {1,0,3,mY1 q4 Log2exp1 q4 Log2exp1 w11"log2exp1",m12"log2"g91
#define Ue1 {1,-1,N(0.75),hF2 q4 Log2exp2 q4 Log2exp2 w11"log2exp2","exp2(log2(acos(x)))"},
#define We1 {1,0,3,mY1 q4 Logexp1 q4 Logexp1 w11"logexp1",m12"log"g91
#define Ye1 {1,-1,N(0.75),hF2 q4 Logexp2 q4 Logexp2 w11"logexp2",m12"log(acos(x)))"},
#define Sf1 dE1 Logmul q4 Logmul w11"logmul","log"dF1
#define Tf1 dE1 Logmul2 q4 Logmul2 w11"logmul2","log2"dF1
#define Uf1 dE1 Logmul10 q4 Logmul10 w11"logmul10","log10"dF1
#define Wf1 {wD Lt0 q4 Lt0 q4 Lt0 gT"lt0","sub("gY2"<0, x<0"g31
#define Yf1 {1 d3 Lthalf q4 Lthalf w11"lthalf","x<0.5"},
#define Sg1 {1 gS Mod q4 Mod q4 Mod gT"mod","(5%4)+x"},
#define Tg1 {1 gS Mul q4 Mul q4 Mul gT"mul","(5*4)+x"},
#define Ug1 {1 gS Mul1 q4 Mul1 q4 Mul1 gT"mul1"aY2"1+x"},
#define Wg1 {1 gS Mul1b q4 Mul1b w11"mul1b",wG"0.2)*5)+x"},
#define Yg1 {2,N(0.1),10,N(0.1)qN q4 Mul_zero q4 Mul_zero oC gW"mul_zero","(x*y+1)+(sin(x)+sin(y))*log(x)*y*x*0"},
#define Sh1 {1 gS Mulneg q4 Mulneg q4 Mulneg gT"mulneg","-"a42
#define Th1 {1 gS a32 q4 a32 q4 a32 gT"multodiv","x/4+x"},
#define Uh1 {2,qY3 wY2 wY2 wY2,oL2"negadd","x+(-y"g31
#define Wh1 g6 Negcos q4 Negcos w11"negcos","cos"gZ2
#define Yh1 g6 Negcosh q4 Negcosh w11"negcosh","cosh"gZ2
#define Si1 {1 gS Negmul q4 Negmul q4 Negmul gT"negmul","(-x)*5"},
#define Ti1 g6 Negsin q4 Negsin w11"negsin","sin(-x)"},
#define Ui1 g6 Negsinh q4 Negsinh w11"neg"wL2,wL2 gZ2
#define Wi1 {2,qY3 q4 Negsub q4 Negsub q4 Negsub,oL2"negsub","x-(-y"g31
#define Yi1 g6 Negtan q4 Negtan w11"negtan","tan"gZ2
#define Sj1 g6 Negtanh q4 Negtanh w11"negtanh","tanh"gZ2
#define Tj1 {1 gS Neq0 q4 Neq0 q4 Neq0 gT"neq0","(x!=0"q33"0!=x)"},
#define Uj1 {1 gS Neq1 q4 Neq1 q4 Neq1 gT"neq1","(!x!=1"g31
#define Wj1 {1 gS Not q4 Not q4 Not gT"not","(!(3))+x"},
#define Yj1 {1 gS Or q4 Or q4 Or gT"or","(5|3"dE2"5|0)+(0|5)+(0|0"g31
#define Sk1 g6 Sincos_cci q4 Sincos_cci,aW"cos_cci","cos"dI2" sec(x)"},
#define Tk1 g6 Sincos_cic q4 Sincos_cic,aW"cos_cic","sec"dI2 mS1
#define Uk1 g6 Sincos_sc q4 Sincos_sc,aW"cos_sc",q43 mS1
#define Wk1 g6 Sincos_sci q4 Sincos_sci,aW"cos_sci",q43" sec(x)"},
#define Yk1 g6 Sincos_sis q4 Sincos_sis,aW"cos_sis","csc"dI2" "qA2},
#define Sl1 g6 Sincos_ssi q4 Sincos_ssi,aW"cos_ssi",q43" csc(x)"},
#define Tl1 g6 Sincos_tan q4 Sincos_tan,aW"cos_tan",qA2" /"mS1
#define Ul1 g6 Sincos_tit q4 Sincos_tit,aW"cos_tit","cot"dI2" tan(x)"},
#define Wl1 g6 Sincos_tti q4 Sincos_tti,aW"cos_tti","tan"dI2" cot(x)"},
#define Yl1 {1 gS Sqreq0 q4 Sqreq0 q4 Sqreq0 gT"sqreq0","(x*x=0"q33"0=x*x)"},
#define Sm1 {1 gS q53 q4 q53 q4 q53 gT"sqrneq0","(x*x=0"q33"0=x*x)"},
#define Tm1 {1,0,3,mY1 q4 Sqrtsqr1 q4 Sqrtsqr1 w11"sqrtsqr1","sqrt(x)^2"},
#define Um1 {1 w5 Sqrtsqr2 q4 Sqrtsqr2 w11"sqrtsqr2","sqrt(acos(x))^2"},
#define Wm1 {1 gS Sub q4 Sub q4 Sub gT"sub","5-3+x"},
#define Ym1 {1 gS Sub0 q4 Sub0 q4 Sub0 gT"sub0","x-0+x"},
#define Sn1 {1 oJ gH3 Subxx q4 Subxx q4 Subxx gT"subxx","x+(x-x)+x+(1-x+x)"},
#define Tn1 g6 Xmulsinhneg q4 Xmulsinhneg,0,q7"/xmulsinhneg","-"wL2 a42
#define Un1 g6 Xmulsinneg q4 Xmulsinneg,0,q7"/xmulsinneg","-sin(x*"h62
#define Wn1 g6 Xmultanhneg q4 Xmultanhneg,0,q7"/xmultanhneg","-tanh"a42
#define Yn1 g6 Xmultanneg q4 Xmultanneg,0,q7"/xmultanneg","-tan"a42
#define So1 {1,N(0.5),3,N(0.7)qN q4 Xsqryfsqrhypot q4 Xsqryfsqrhypot,0,q7"/xsqryfsqrhypot","sqrt(log(x)^2+"wJ"^2"g31
#define To1 {2,N(0.5),3,N(0.7)qN q4 Xsqrysqrhypot q4 Xsqrysqrhypot oC",y","10optimizer_bytecode/xsqrysqrhypot","sqrt(log(x)^2+y*y"g31
#define Uo1 {1 a9 t1,q5 t1,q5 t1,"a",qE"1","(1/a"q83
#define Wo1 {1 a9 t2,q5 t2,q5 t2,"a",qE"2","5*a"},
#define Yo1 {1 a9 t3,q5 t3,q5 t3,"a",qE"3","5/a"},
#define Sp1 {2 a9 t4,q5 t4,q5 t4,hF"4","(a*5)*b"},
#define Tp1 {2 a9 t5,q5 t5,q5 t5,hF"5","(a*5)/b"},
#define Up1 {2 a9 t6,q5 t6,q5 t6,hF"6","(1/a)*b"},
#define Wp1 {2 a9 t7,q5 t7,q5 t7,hF"7","(1/a)/b"},
#define Yp1 {2 a9 t8,q5 t8,q5 t8,hF"8",mD2")*("mE2")*"h62
#define Sq1 {2 a9 t9,q5 t9,q5 t9,hF"9",mD2")/("mE2")*"h62
#define Tq1 aA t10,q5 t10,q5 t10,hF"10",mE2")*(5/a"g31
#define Uq1 aA t11,q5 t11,q5 t11,hF"11",mE2")/(50/a"g31
#define Wq1 m52 t12,q5 t12,q5 t12,"a",qE"12","(-a)+5"},
#define Yq1 aA t13,q5 t13,q5 t13,hF"13","5+(a*b"g31
#define Sr1 aA t14,q5 t14,q5 t14,hF"14","5-(a*b"g31
#define Tr1 aA t15,q5 t15,q5 t15,hF"15","(a+5)+"mE2 g31
#define Ur1 aA t16,q5 t16,q5 t16,hF"16","(a+5)-abs(b"g31
#define Wr1 aA t17,q5 t17,q5 t17,hF"17","(-a)+"mE2 g31
#define Yr1 aA t18,q5 t18,q5 t18,hF"18","(-a)-abs(b"g31
#define Ss1 aA t19,q5 t19,q5 t19,hF"19","b+("mD2")+"h62
#define Ts1 aA t20,q5 t20,q5 t20,hF"20","b-("mD2")+"h62
#define Us1 aA t21,q5 t21,q5 t21,hF"21",mE2")+(5-a"g31
#define Ws1 aA t22,q5 t22,q5 t22,hF"22",mE2")-(5-a"g31
#define Ys1 aA t23,q5 t23,q5 t23,hF"23",h31"b"q63
#define St1 aA t24,q5 t24,q5 t24,hF"24",h31"5"q63
#define Tt1 aA t25,q5 t25,q5 t25,hF"25",h31"5"q73
#define Ut1 aA t26,q5 t26,q5 t26,hF"26","(   abs(a)/b"q63
#define Wt1 aA t27,q5 t27,q5 t27,hF"27","(   abs(a)/b"q73
#define Yt1 aA t28,q5 t28,q5 t28,hF"28","((-a)/b"q83
#define Su1 aA t29,q5 t29,q5 t29,hF"29","(5/b"q73
#define Tu1 m52 t30,q5 t30,q5 t30,"b",qE"30","(7/b"q83
#define Uu1 aA t31,q5 t31,q5 t31,hF"31","b*(7/-a"g31
#define Wu1 aA t32,q5 t32,q5 t32,hF"32","(5-b)-a"},
#define Yu1 aA t33,q5 t33,q5 t33,hF"33","(5-b)+a"},
#define Sv1 aA t34,q5 t34,q5 t34,hF"34","((a+7)-b)+5"},
#define Tv1 aA t35,q5 t35,q5 t35,hF"35","((-a)-b)+5"},
#define Uv1 m52 t36,q5 t36,q5 t36,"a",qE"36","(7-abs(a))+5"},
#define Wv1 aA t37,q5 t37,q5 t37,hF"37","((7-b)+a)+5"},
#define Yv1 aA t38,q5 t38,q5 t38,hF"38","((5*b+"mD2"))<0)*1 + (("mE2"))<0)*2"},
#define Sw1 m52 t39,q5 t39,q5 t39,"a",qE"39","(a+7"q83
#define Tw1 aA t40,q5 t40,q5 t40,hF"40","(b+(a*7))*5"},
#define Uw1 aA t41,q5 t41,q5 t41,hF"41","(b-(a*7))*5"},
#define Ww1 m52 t42,q5 t42,q5 t42,"a",qE"42","(a+7)+5"},
#define Yw1 m52 t43,q5 t43,q5 t43,"a",qE"43","(a*7"q83
#define Sx1 m62 q93 q2 q93 q2 q93 oQ1"abseq0"mJ1"=if(1,0,1)) + (if(1,0,1)=abs"g91
#define Tx1 m62 a52 q2 a52 q2 a52 oQ1"absneq0"mJ1"=if(1,0,1)) + (if(1,0,1)=abs"g91
#define Ux1 m62 Eq0,q2 Eq0,q2 Eq0,oQ1"eq0","(x=if("qT1" (if(1,0,0)=x)"},
#define Wx1 m62 Eq1,q2 Eq1,q2 Eq1,oQ1"eq1","(!x=if("oM1},
#define Yx1 aQ2 a62 q2 a62 q2 a62 oQ1"ge0_abs"mJ1 hB3 hH3 gM3"2"hU1 hJ3 gY3"<= "hH3"  8"hU1 hB3 hG3
#define Sy1 aQ2 a72 q2 a72 q2 a72 oQ1"ge1_abs"mJ1 hB3 hI3 wK1 dS1 hJ3 gY3"<= "hI3" +  8"dS1 hB3 hG3
#define Ty1 {1 d4 hF2,q2 Gehalf,q2 Gehalf,gQ"gehalf","x>=if(1,0.5,0"g31
#define Uy1 aQ2 a82 q2 a82 q2 a82 oQ1"gt0_abs"mJ1" > "hH3 gM3"2"hU1" < "gY3"< "hH3"  8"hU1" > "hG3
#define Wy1 aQ2 a92 q2 a92 q2 a92 oQ1"gt1_abs"mJ1" > "hI3 wK1 dS1" < "gY3"< "hI3" +  8"dS1" > "hG3
#define Yy1 {1 d4 hF2,q2 Lthalf,q2 Lthalf,gQ"lthalf","x<if(1,0.5,0"g31
#define Sz1 m62 Neq0,q2 Neq0,q2 Neq0,oQ1"neq0","(x!=if("qT1" (if(1,0,0)!=x)"},
#define Tz1 m62 Neq1,q2 Neq1,q2 Neq1,oQ1"neq1","(!x!=if("oM1},
#define Uz1 {1,-9,9,gF3 t7,g1 t7,g1 t7,m82"7","x>7 & x<2"},
#define Wz1 {2,-9,9,gF3 t8,g1 t8 oC",y",oE"8",aA2"(-x,-y) + 10*"aA2"(-x,y) + 20*"aA2"(x,-y) + 30*"aA2"(x"mI1
#define Yz1 {1 d4 gF3 t9a,g1 t9a,g1 t9a,m82"9a","a:=x;a*0"},
#define S_1 wG1 t9b,g1 t9b,g1 t9b,aB2"9b","sub(a,b"qA3
#define T_1 wG1 t9c,g1 t9c,g1 t9c,aB2"9c","psub(a,b"qA3
#define U_1 wG1 t9d,g1 t9d,g1 t9d,aB2"9d","if(a,b*0,a*0"qA3
#define W_1 {2,gM Add_cd,0 g2"add_cd","x+y"},
#define Y_1 {2,qN3 Add_d,qG Add_d g2"add_d","x+y"},
#define S02 {3,gM Addsub_cd,0 wK2,g9"addsub_cd","x+y+x+x-z+x"},
#define T02 {3,qN3 Addsub_d,qG Addsub_d wK2,g9"addsub_d","x+y+x+x-z+x"},
#define U02 {2,gH And_d,qG And_d g2"and_d","x&y"},
#define W02 {2,gM Cmpeq_cd,0 g2"cmpeq_cd","x=y"},
#define Y02 {2,gH Cmpeq_d,qG Cmpeq_d g2"cmpeq_d","x=y"},
#define S12 {2,gH Cmpge_d,qG Cmpge_d g2"cmpge_d","x>=y"},
#define T12 {2,gH Cmpgt_d,qG Cmpgt_d g2"cmpgt_d","x>y"},
#define U12 {2,gH Cmple_d,qG Cmple_d g2"cmple_d","x<=y"},
#define W12 {2,gH Cmplt_d,qG Cmplt_d g2"cmplt_d","x<y"},
#define Y12 {2,gM Cmpne_cd,0 g2"cmpne_cd","x!=y"},
#define S22 {2,gH Cmpne_d,qG Cmpne_d g2"cmpne_d","x!=y"},
#define T22 {2,dE Div_d,qG Div_d g2"div_d","(x-0.25)/y"},
#define U22 {3,dE Divmul_d,qG Divmul_d wK2,g9"divmul_d"aY2"y*x*x/z"d92"-0.25"g31
#define W22 {1,N(-7.0,0.0),N(6.0,0.0),N(0.6,0.0)qN,qG Inv_d,qG Inv_d oC,g9"inv_d","1/x"},
#define Y22 {2,N(-7.25,+3.625),N(7.25,-3.625),N(0.5,-0.25)qN,qG Mul_cd,0 g2"mul_cd"aY2"y"},
#define S32 {2,dE Mul_d,qG Mul_d g2"mul_d"aY2"y"},
#define T32 {1,gM Neg_cd,0 oC,g9"neg_cd","-x"},
#define U32 {1,qN3 Neg_d,qG Neg_d oC,g9"neg_d","-x"},
#define W32 {1,N(-1.25,0.0),N(1.25,0.0),N(0.25,0.0)qN,qG Not_d,qG Not_d oC,g9"not_d","!x"},
#define Y32 {1,N(-1.25,0.0),N(1.25,0.0),N(0.25,0.0)qN,qG Notnot_d,qG Notnot_d oC,g9"notnot_d","!!x"},
#define S42 {2,gH Or_d,qG Or_d g2"or_d","x|y"},
#define T42 {2,gM Sub_cd,0 g2"sub_cd","x-y"},
#define U42 {2,qN3 Sub_d,qG Sub_d g2"sub_d","x-y"},
#define W42 {1,N(-400.0,+200.0),N(400.0,-200.0),N(0.5,-0.25)qN qB Abs_cd hD2"abs_cd",gY2},
#define Y42 {1,h7 Arg hD2"arg",gE2
#define S52 {1,h7 Conj hD2"conj","conj(x)"},
#define T52 {1,h7 Imag hD2"imag","imag(x)"},
#define U52 {1,h7 Log qB Log wY"log",gE2
#define W52 {1,N(-4000.0,-0.5),N(4000.0,+0.5),N(0.3,+3.75e-05)qN qB Log_cd hD2"log_cd",gE2
#define Y52 {2,N(-4.0,0.0),mT1 N(1.0,0.0)qN qB Max qB Max qB Max,"x,y"wN"/max","max(x"mI1
#define S62 {2,N(-4.0,0.0),mT1 N(1.0,0.0)qN qB Min qB Min qB Min,"x,y"wN"/min","min(x"mI1
#define T62 {2,N(0.01,0.0),mT1 N(0.05,0.0)qN qB Polar,wM"/polar","polar(x"mI1
#define U62 {1,h7 Real hD2"real","real(x)"},
#define W62 {1,N(-100000.0,0.0),N(100000.0,0.0),N(1000.0,0.0)qN qB Sqrt_cd hD2"sqrt_cd","sqrt(x)"},
#define Y62 {1,g7 t1,q5 t1,q5 t1,"a",qE"1","(1/a"q83
#define S72 {1,g7 t2,q5 t2,q5 t2,"a",qE"2","5*a"},
#define T72 {1,g7 t3,q5 t3,q5 t3,"a",qE"3","5/a"},
#define U72 {2,g7 t4,q5 t4,q5 t4,hF"4","(a*5)*b"},
#define W72 {2,g7 t5,q5 t5,q5 t5,hF"5","(a*5)/b"},
#define Y72 {2,g7 t6,q5 t6,q5 t6,hF"6","(1/a)*b"},
#define S82 {2,g7 t7,q5 t7,q5 t7,hF"7","(1/a)/b"},
#define T82 {2,g7 t8,q5 t8,q5 t8,hF"8",mD2")*("mE2")*"h62
#define U82 {2,g7 t9,q5 t9,q5 t9,hF"9",mD2")/("mE2")*"h62
#define W82 oV1 t10,q5 t10,q5 t10,hF"10",mE2")*(5/a"g31
#define Y82 oV1 t11,q5 t11,q5 t11,hF"11",mE2")/(50/a"g31
#define S92 {1,q9 t12,q5 t12,q5 t12,"a",qE"12","(-a)+5"},
#define T92 oV1 t13,q5 t13,q5 t13,hF"13","5+(a*b"g31
#define U92 oV1 t14,q5 t14,q5 t14,hF"14","5-(a*b"g31
#define W92 oV1 t15,q5 t15,q5 t15,hF"15","(a+5)+"mE2 g31
#define Y92 oV1 t16,q5 t16,q5 t16,hF"16","(a+5)-abs(b"g31
#define SA2 oV1 t17,q5 t17,q5 t17,hF"17","(-a)+"mE2 g31
#define TA2 oV1 t18,q5 t18,q5 t18,hF"18","(-a)-abs(b"g31
#define UA2 oV1 t19,q5 t19,q5 t19,hF"19","b+("mD2")+"h62
#define WA2 oV1 t20,q5 t20,q5 t20,hF"20","b-("mD2")+"h62
#define YA2 oV1 t21,q5 t21,q5 t21,hF"21",mE2")+(5-a"g31
#define SB2 oV1 t22,q5 t22,q5 t22,hF"22",mE2")-(5-a"g31
#define TB2 oV1 t23,q5 t23,q5 t23,hF"23",h31"b"q63
#define UB2 oV1 t24,q5 t24,q5 t24,hF"24",h31"5"q63
#define WB2 oV1 t25,q5 t25,q5 t25,hF"25",h31"5"q73
#define YB2 oV1 t26,q5 t26,q5 t26,hF"26","(   abs(a)/b"q63
#define SC2 oV1 t27,q5 t27,q5 t27,hF"27","(   abs(a)/b"q73
#define TC2 oV1 t28,q5 t28,q5 t28,hF"28","((-a)/b"q83
#define UC2 oV1 t29,q5 t29,q5 t29,hF"29","(5/b"q73
#define WC2 {1,q9 t30,q5 t30,q5 t30,"b",qE"30","(7/b"q83
#define YC2 oV1 t31,q5 t31,q5 t31,hF"31","b*(7/-a"g31
#define SD2 oV1 t32,q5 t32,q5 t32,hF"32","(5-b)-a"},
#define TD2 oV1 t33,q5 t33,q5 t33,hF"33","(5-b)+a"},
#define UD2 oV1 t34,q5 t34,q5 t34,hF"34","((a+7)-b)+5"},
#define WD2 oV1 t35,q5 t35,q5 t35,hF"35","((-a)-b)+5"},
#define YD2 {1,q9 t36,q5 t36,q5 t36,"a",qE"36","(7-abs(a))+5"},
#define SE2 oV1 t37,q5 t37,q5 t37,hF"37","((7-b)+a)+5"},
#define TE2 oV1 t38,q5 t38,q5 t38,hF"38","((5*b+"mD2"))<0)*1 + (("mE2"))<0)*2"},
#define UE2 {1,q9 t39,q5 t39,q5 t39,"a",qE"39","(a+7"q83
#define WE2 oV1 t40,q5 t40,q5 t40,hF"40","(b+(a*7))*5"},
#define YE2 oV1 t41,q5 t41,q5 t41,hF"41","(b-(a*7))*5"},
#define SF2 {1,q9 t42,q5 t42,q5 t42,"a",qE"42","(a+7)+5"},
#define TF2 {1,q9 t43,q5 t43,q5 t43,"a",qE"43","(a*7"q83
#define UF2 {1 mI Abscos,q2 Abscos,gQ"abscos","cos(sqrt("aM1"))) + sqrt("aM1"))"},
#define WF2 {1 mI Abscosh,q2 Abscosh,gQ"abscosh","cosh(sqrt("aM1"))) + sqrt("aM1"))"},
#define YF2 {1,N(0.0,0.0)qV q93 q2 q93 q2 q93 oQ1"abseq0"mJ1"=if(1,0,1)) + (if(1,0,1)=abs"g91
#define SG2 {1,N(0.0,0.0)qV a52 q2 a52 q2 a52 oQ1"absneq0"mJ1"=if(1,0,1)) + (if(1,0,1)=abs"g91
#define TG2 {1,N(-5.0,0.0),N(5.0,0.0),qD1 oP2 q2 oP2 q2 oP2 oQ1"absnzge","sub("gY2 hB3"if("oQ2"), abs(x)"hB3"(if(1,1,0)-1))"},
#define UG2 {1,N(-5.0,0.0),N(5.0,0.0),qD1 oR2 q2 oR2 q2 oR2 oQ1"absnzlt","sub("gY2" < if("oQ2"), abs(x) < (if(1,1,0)-1))"},
#define WG2 {1,N(-1.0,0.0),mF1 N(0.1,0.0)qN,q2 Acoscos,q2 Acoscos,gQ"acoscos","cos(acos"g91
#define YG2 {1,N(1.7,0.0),N(3.7,0.0),N(0.28,0.0)qN,q2 Acoshsinh,q2 Acoshsinh,gQ mR2 wL2,wL2"(if(1,acosh(x),0))"},
#define SH2 {hN mH1,q2 mH1,q2 mH1 qK"addconstmul","5*(if("oQ2")+x+y"g31
#define TH2 {2,N(0.25,0.0),mF1 N(0.25,0.0)qN,q2 Addlog,q2 Addlog,0 qK"addlog","log(x)+log(y"g31
#define UH2 {hN o21,q2 o21,q2 o21 qK"addmulconstmul","5*(if("oQ2")*y+x)"},
#define WH2 {hN a21,q2 a21,q2 a21 qK"addnegmulneg","-5 + (if(1,5,0)*x*y"g31
#define YH2 {hN a31,q2 a31,q2 a31 qK"addnegmulpos","(if(1,-5,0)*"aU2" (if(1,5,0)*x)"},
#define SI2 {1 gU Addsin2cos2,q2 Addsin2cos2,gQ"addsin2cos2",qA2"^2 + cos(x)^2"},
#define TI2 {1,N(-0.7,0.0),N(0.7,0.0),N(0.28,0.0)qN,q2 Asinhcosh,q2 Asinhcosh,gQ"asinhcosh","cosh(if(1,a"wL2"(x),0))"},
#define UI2 {1,N(-1.0,0.0),mF1 N(0.1,0.0)qN,q2 Asinsin,q2 Asinsin,gQ"asinsin","sin(asin(x))"},
#define WI2 oP w41,q2 w41,q2 w41 qK"cmpeq_add_imm",h61 hI2
#define YI2 wP1 gG1 q2 gG1 q2 gG1 oQ1"cmpeq_add_reduce",dP" = "h3},
#define SJ2 oP h71,q2 h71,q2 h71 qK"cmpeq_addadd_imm",dY") = "hZ
#define TJ2 {hO a41,q2 a41,q2 a41 qK"cmpeq_minma"oS2" = "h13
#define UJ2 {hO h81,q2 h81,q2 h81 qK"cmpeq_minma"oV2" = "gO3},
#define WJ2 oP gH1,q2 gH1,q2 gH1 qK"cmpeq_mul_imm_neg",oW2 hI2
#define YJ2 oP gI1,q2 gI1,q2 gI1 qK"cmpeq_mul_imm_pos",a61 hI2
#define SK2 oP mQ,q2 mQ,q2 mQ qK"cmpeq_mulmul_imm_neg",qU2" = "hZ
#define TK2 oP mR,q2 mR,q2 mR qK"cmpeq_mulmul_imm_pos",oX2" = "hZ
#define UK2 dH1 Cmpeq_pow_imm_negneg,q2 Cmpeq_pow_imm_negneg,gQ aN1 hS" = "gL3
#define WK2 dH1 Cmpeq_pow_imm_negpos,q2 Cmpeq_pow_imm_negpos,gQ aN1 hT" = "gN3
#define YK2 wP1 Cmpeq_pow_imm_posneg,q2 Cmpeq_pow_imm_posneg,gQ aN1 d0" = "gT3
#define SL2 wP1 Cmpeq_pow_imm_pospos,q2 Cmpeq_pow_imm_pospos,gQ aN1 d1" = "h23
#define TL2 wP1 Cmpeq_pow_imm_pospos_base,q2 Cmpeq_pow_imm_pospos_base,gQ aN1 gQ3"= "wH
#define UL2 oP Cmpeq_powpow_imm_base,q2 Cmpeq_powpow_imm_base,0 qK aN1 hH" = "wW
#define WL2 oP w51,q2 w51,q2 w51 qK"cmpge_add_imm",h61 qV2
#define YL2 wP1 gJ1 q2 gJ1 q2 gJ1 oQ1"cmpge_add_reduce",dP hB3 h3},
#define SM2 oP h91,q2 h91,q2 h91 qK"cmpge_addadd_imm",dY")"hB3 hZ
#define TM2 {hO a71,q2 a71,q2 a71 qK"cmpge_minma"oS2 hB3 h13
#define UM2 {hO hA1,q2 hA1,q2 hA1 qK"cmpge_minma"oV2 hB3 gO3},
#define WM2 oP gK1,q2 gK1,q2 gK1 qK"cmpge_mul_imm_neg",oW2 qV2
#define YM2 oP gL1,q2 gL1,q2 gL1 qK"cmpge_mul_imm_pos",a61 qV2
#define SN2 oP mS,q2 mS,q2 mS qK"cmpge_mulmul_imm_neg",qU2 hB3 hZ
#define TN2 oP mT,q2 mT,q2 mT qK"cmpge_mulmul_imm_pos",oX2 hB3 hZ
#define UN2 dH1 Cmpge_pow_imm_negneg,q2 Cmpge_pow_imm_negneg dV1 hS hB3 gL3
#define WN2 dH1 Cmpge_pow_imm_negpos,q2 Cmpge_pow_imm_negpos dV1 hT hB3 gN3
#define YN2 wP1 Cmpge_pow_imm_posneg,q2 Cmpge_pow_imm_posneg dV1 d0 hB3 gT3
#define SO2 wP1 Cmpge_pow_imm_pospos,q2 Cmpge_pow_imm_pospos dV1 d1 hB3 h23
#define TO2 wP1 Cmpge_pow_imm_pospos_base,q2 Cmpge_pow_imm_pospos_base dV1 gQ3">= "wH
#define UO2 oP Cmpge_powpow_imm_base,q2 Cmpge_powpow_imm_base,0 qK"cmpge_"hH hB3 wW
#define WO2 oP w61,q2 w61,q2 w61 qK"cmpgt_add_imm",h61 hJ2
#define YO2 wP1 gM1 q2 gM1 q2 gM1 oQ1"cmpgt_add_reduce",dP" > "h3},
#define SP2 oP hB1,q2 hB1,q2 hB1 qK"cmpgt_addadd_imm",dY") > "hZ
#define TP2 {hO a81,q2 a81,q2 a81 qK"cmpgt_minma"oS2" > "h13
#define UP2 {hO hC1,q2 hC1,q2 hC1 qK"cmpgt_minma"oV2" > "gO3},
#define WP2 oP gN1,q2 gN1,q2 gN1 qK"cmpgt_mul_imm_neg",oW2 hJ2
#define YP2 oP gO1,q2 gO1,q2 gO1 qK"cmpgt_mul_imm_pos",a61 hJ2
#define SQ2 oP mU,q2 mU,q2 mU qK"cmpgt_mulmul_imm_neg",qU2" > "hZ
#define TQ2 oP mV,q2 mV,q2 mV qK"cmpgt_mulmul_imm_pos",oX2" > "hZ
#define UQ2 dH1 Cmpgt_pow_imm_negneg,q2 Cmpgt_pow_imm_negneg,oN1 hS" > "gL3
#define WQ2 dH1 Cmpgt_pow_imm_negpos,q2 Cmpgt_pow_imm_negpos,oN1 hT" > "gN3
#define YQ2 wP1 Cmpgt_pow_imm_posneg,q2 Cmpgt_pow_imm_posneg,oN1 d0" > "gT3
#define SR2 wP1 Cmpgt_pow_imm_pospos,q2 Cmpgt_pow_imm_pospos,oN1 d1" > "h23
#define TR2 wP1 Cmpgt_pow_imm_pospos_base,q2 Cmpgt_pow_imm_pospos_base,oN1 gQ3"> "wH
#define UR2 oP Cmpgt_powpow_imm_base,q2 Cmpgt_powpow_imm_base,0 qK"cmpgt_"hH" > "wW
#define WR2 oP w71,q2 w71,q2 w71 qK"cmple_add_imm",h61 qW2
#define YR2 wP1 gP1 q2 gP1 q2 gP1 oQ1"cmple_add_reduce",dP hJ3 h3},
#define SS2 oP hD1,q2 hD1,q2 hD1 qK"cmple_addadd_imm",dY")"hJ3 hZ
#define TS2 {hO a91,q2 a91,q2 a91 qK"cmple_minma"oS2 hJ3 h13
#define US2 {hO hE1,q2 hE1,q2 hE1 qK"cmple_minma"oV2 hJ3 gO3},
#define WS2 oP gQ1,q2 gQ1,q2 gQ1 qK"cmple_mul_imm_neg",oW2 qW2
#define YS2 oP gR1,q2 gR1,q2 gR1 qK"cmple_mul_imm_pos",a61 qW2
#define ST2 oP mW,q2 mW,q2 mW qK"cmple_mulmul_imm_neg",qU2 hJ3 hZ
#define TT2 oP mX,q2 mX,q2 mX qK"cmple_mulmul_imm_pos",oX2 hJ3 hZ
#define UT2 dH1 Cmple_pow_imm_negneg,q2 Cmple_pow_imm_negneg dW1 hS hJ3 gL3
#define WT2 dH1 Cmple_pow_imm_negpos,q2 Cmple_pow_imm_negpos dW1 hT hJ3 gN3
#define YT2 wP1 Cmple_pow_imm_posneg,q2 Cmple_pow_imm_posneg dW1 d0 hJ3 gT3
#define SU2 wP1 Cmple_pow_imm_pospos,q2 Cmple_pow_imm_pospos dW1 d1 hJ3 h23
#define TU2 wP1 Cmple_pow_imm_pospos_base,q2 Cmple_pow_imm_pospos_base dW1 gQ3"<= "wH
#define UU2 oP Cmple_powpow_imm_base,q2 Cmple_powpow_imm_base,0 qK"cmple_"hH hJ3 wW
#define WU2 oP w81,q2 w81,q2 w81 qK"cmplt_add_imm",h61 hK2
#define YU2 wP1 gS1 q2 gS1 q2 gS1 oQ1"cmplt_add_reduce",dP" < "h3},
#define SV2 oP hF1,q2 hF1,q2 hF1 qK"cmplt_addadd_imm",dY") < "hZ
#define TV2 {hO aA1,q2 aA1,q2 aA1 qK"cmplt_minma"oS2" < "h13
#define UV2 {hO hG1,q2 hG1,q2 hG1 qK"cmplt_minma"oV2" < "gO3},
#define WV2 oP gT1,q2 gT1,q2 gT1 qK"cmplt_mul_imm_neg",oW2 hK2
#define YV2 oP gU1,q2 gU1,q2 gU1 qK"cmplt_mul_imm_pos",a61 hK2
#define SW2 oP mY,q2 mY,q2 mY qK"cmplt_mulmul_imm_neg",qU2" < "hZ
#define TW2 oP mZ,q2 mZ,q2 mZ qK"cmplt_mulmul_imm_pos",oX2" < "hZ
#define UW2 dH1 Cmplt_pow_imm_negneg,q2 Cmplt_pow_imm_negneg,oA1 hS" < "gL3
#define WW2 dH1 Cmplt_pow_imm_negpos,q2 Cmplt_pow_imm_negpos,oA1 hT" < "gN3
#define YW2 wP1 Cmplt_pow_imm_posneg,q2 Cmplt_pow_imm_posneg,oA1 d0" < "gT3
#define SX2 wP1 Cmplt_pow_imm_pospos,q2 Cmplt_pow_imm_pospos,oA1 d1" < "h23
#define TX2 wP1 Cmplt_pow_imm_pospos_base,q2 Cmplt_pow_imm_pospos_base,oA1 gQ3"< "wH
#define UX2 oP Cmplt_powpow_imm_base,q2 Cmplt_powpow_imm_base,0 qK"cmplt_"hH" < "wW
#define WX2 oP w91,q2 w91,q2 w91 qK"cmpne_add_imm",h61 qX2
#define YX2 wP1 gV1 q2 gV1 q2 gV1 oQ1"cmpne_add_reduce",dP aZ2 h3},
#define SY2 oP hH1,q2 hH1,q2 hH1 qK"cmpne_addadd_imm",dY")"aZ2 hZ
#define TY2 {hO aB1,q2 aB1,q2 aB1 qK"cmpne_minma"oS2 hC3 h13
#define UY2 {hO hI1,q2 hI1,q2 hI1 qK"cmpne_minma"oV2 hC3 gO3},
#define WY2 oP gW1,q2 gW1,q2 gW1 qK"cmpne_mul_imm_neg",oW2 qX2
#define YY2 oP gX1,q2 gX1,q2 gX1 qK"cmpne_mul_imm_pos",a61 qX2
#define SZ2 oP q01,q2 q01,q2 q01 qK"cmpne_mulmul_imm_neg",qU2 aZ2 hZ
#define TZ2 oP q11,q2 q11,q2 q11 qK"cmpne_mulmul_imm_pos",oX2 aZ2 hZ
#define UZ2 dH1 Cmpne_pow_imm_negneg,q2 Cmpne_pow_imm_negneg dX1 hS hC3 gL3
#define WZ2 dH1 Cmpne_pow_imm_negpos,q2 Cmpne_pow_imm_negpos dX1 hT hC3 gN3
#define YZ2 wP1 Cmpne_pow_imm_posneg,q2 Cmpne_pow_imm_posneg dX1 d0 hC3 gT3
#define Sa2 wP1 Cmpne_pow_imm_pospos,q2 Cmpne_pow_imm_pospos dX1 d1 hC3 h23
#define Ta2 wP1 Cmpne_pow_imm_pospos_base,q2 Cmpne_pow_imm_pospos_base dX1 gQ3"!= "wH
#define Ua2 oP Cmpne_powpow_imm_base,q2 Cmpne_powpow_imm_base,0 qK"cmpne_"hH aZ2 wW
#define Wa2 oP wA1,q2 wA1,q2 wA1 qK"cmpzz_add_imm"oN m02 hL2 m02 qY2 m02 hO2 m02 hP2 m02 qZ2 h61 hI2
#define Ya2 wP1 gY1 q2 gY1 q2 gY1 oQ1"cmpzz_add_reduce"oN" "dP" < "h3 a6" "dP hJ3 h3 a8" "dP" > "h3 oS" "dP hB3 h3 o41" "dP aZ2 h3 dV dP" = "h3},
#define Sb2 oP hJ1,q2 hJ1,q2 hJ1 qK"cmpzz_addadd_imm"oN" "dY aC1" "dY aD1" "dY aE1" "dY aF1" "dY aG1 dY") = "hZ
#define Tb2 {hO aH1,q2 aH1,q2 aH1 qK"cmpzz_minmax"oN hK1" < "hE3 a6 hK1 hJ3 hE3 a8 hK1" > "hE3 oS hK1 hB3"y,x,y"a7 hK1 hC3 hE3" +  0x0020 *"hK1" = "h13
#define Ub2 {hO hO1,q2 hO1,q2 hO1 qK"cmpzz_minmax_rev"oN hK1" < "gO3 a6 hK1 hJ3 gO3 a8 hK1" > "gO3 oS hK1 hB3 gO3 o41 hK1 hC3 gO3" +  0x0020 *"hK1" = "gO3},
#define Wb2 oP gZ1,q2 gZ1,q2 gZ1 qK"cmpzz_mul_imm_neg"oN mZ1 hL2 mZ1 qY2 mZ1 hO2 mZ1 hP2 mZ1 qZ2 oW2 hI2
#define Yb2 oP h01,q2 h01,q2 h01 qK"cmpzz_mul_imm_pos"oN q02 hL2 q02 qY2 q02 hO2 q02 hP2 q02 qZ2 a61 hI2
#define Sc2 oP q21,q2 q21,q2 q21 qK"cmpzz_mulmul_imm_neg"oN qV1 aC1 qV1 aD1 qV1 aE1 qV1 aF1 qV1 aG1 qU2" = "hZ
#define Tc2 oP q31,q2 q31,q2 q31 qK"cmpzz_mulmul_imm_pos"oN g81 aC1 g81 aD1 g81 aE1 g81 aF1 g81 aG1 oX2" = "hZ
#define Uc2 dH1 Cmpzz_pow_imm_negneg,q2 Cmpzz_pow_imm_negneg,q71"_imm_negneg"oN d41" < "gU3 a6 d41 hJ3 gU3 a8 d41" > "gU3 oS d41 hB3"-0.015625"a7 d41 hC3 gU3 dV gJ",-3) = "gL3
#define Wc2 dH1 Cmpzz_pow_imm_negpos,q2 Cmpzz_pow_imm_negpos,q71"_imm_negpos"oN d51" < "h33 a6 d51 hJ3 h33 a8 d51" > "h33 oS d51 hB3"0.0625"a7 d51 hC3 h33 dV gJ",-2) = "gN3
#define Yc2 wP1 Cmpzz_pow_imm_posneg,q2 Cmpzz_pow_imm_posneg,q71"_imm_posneg"oN oB1" < "hT3 a6 oB1 hJ3 hT3 a8 oB1" > "hT3 oS oB1 hB3"-125"a7 oB1 hC3 hT3 dV gJ",3) = "gT3
#define Sd2 wP1 Cmpzz_pow_imm_pospos,q2 Cmpzz_pow_imm_pospos,q71"_imm_pospos"oN oC1" < 25)"a6 oC1 hJ3"25)"a8 oC1" > 25)"oS oC1 hB3"25"a7 oC1 hC3"25)"dV gJ",2) = "h23
#define Td2 wP1 Cmpzz_pow_imm_pospos_base,q2 Cmpzz_pow_imm_pospos_base,q71"_imm_pospos_base"oN d03"< "q61 a6 d03"<= "q61 a8 d03"> "q61 oS d03">= "q61 o41 d03"!= "q61 dV gR3"= "wH
#define Ud2 oP Cmpzz_powpow_imm_base,q2 Cmpzz_powpow_imm_base,0 qK"cmpzz_powpow_imm_base"oN gC3" < "gA1 a6 gC3 hJ3 gA1 a8 gC3" > "gA1 oS gC3 hB3 gA1 o41 gC3 aZ2 gA1 dV qQ1" = "wW
#define Wd2 {1,N(0.0,0.0)qV Eq0,q2 Eq0,q2 Eq0,oQ1"eq0","(x=if("qT1" (if(1,0,0)=x)"},
#define Yd2 {1,N(0.0,0.0)qV Eq1,q2 Eq1,q2 Eq1,oQ1"eq1","(!x=if("oM1},
#define Se2 {1 mI a62 q2 a62 q2 a62 oQ1"ge0_abs"mJ1 hB3 hH3 gM3"2"hU1 hJ3 gY3"<= "hH3"  8"hU1 hB3 hG3
#define Te2 {1 mI a72 q2 a72 q2 a72 oQ1"ge1_abs"mJ1 hB3 hI3 wK1 dS1 hJ3 gY3"<= "hI3" +  8"dS1 hB3 hG3
#define Ue2 {hO hQ2,q2 hQ2,q2 hQ2 qK"ge_and_eq",mL2 oS1
#define We2 {hO hR2,q2 hR2,q2 hR2 qK"ge_and_le",mL2 oY2
#define Ye2 {hO hS2,q2 hS2,q2 hS2 qK"ge_and_ne",mL2 oT1
#define Sf2 {hO oZ2,q2 oZ2,q2 oZ2 qK"ge_or_eq",mM2 oS1
#define Tf2 {hO w02,q2 w02,q2 w02 qK"ge_or_le",mM2 oY2
#define Uf2 {hO w12,q2 w12,q2 w12 qK"ge_or_ne",mM2 oT1
#define Wf2 {1,N(-1.0,0.0),mF1 N(0.25,0.0)qN,q2 Gehalf,q2 Gehalf,gQ"gehalf","x>=if(1,0.5,0"g31
#define Yf2 {1 mI a82 q2 a82 q2 a82 oQ1"gt0_abs"mJ1" > "hH3 gM3"2"hU1" < "gY3"< "hH3"  8"hU1" > "hG3
#define Sg2 {1 mI a92 q2 a92 q2 a92 oQ1"gt1_abs"mJ1" > "hI3 wK1 dS1" < "gY3"< "hI3" +  8"dS1" > "hG3
#define Tg2 {hO hT2,q2 hT2,q2 hT2 qK"gt_and_eq"h02 oS1
#define Ug2 {hO hU2,q2 hU2,q2 hU2 qK"gt_and_ge"h02 m6},
#define Wg2 {hO hV2,q2 hV2,q2 hV2 qK"gt_and_le"h02 oY2
#define Yg2 {hO hW2,q2 hW2,q2 hW2 qK"gt_and_ne"h02 oT1
#define Sh2 {hO w22,q2 w22,q2 w22 qK"gt_or_eq"h12 oS1
#define Th2 {hO w32,q2 w32,q2 w32 qK"gt_or_ge"h12 m6},
#define Uh2 {hO w42,q2 w42,q2 w42 qK"gt_or_le"h12 oY2
#define Wh2 {hO w52,q2 w52,q2 w52 qK"gt_or_ne"h12 oT1
#define Yh2 {1,N(0.0,0.0)qV If10,q2 If10,q2 If10,oQ1"if10",dX",1,0) + 10*"dX",0,1)"gM3"+ 100*"dX">0,1,0) + 1000*"dX">0,0,1"g31
#define Si2 {2,gE o51,q2 o51,q2 o51 mJ"tract_abs",dX", abs(x+2), abs(y+5))"},
#define Ti2 {2,gE o61,q2 o61,q2 o61 mJ"tract_add",dX", y+2, y+"h62
#define Ui2 {2,gE d91,q2 d91,q2 d91 mJ"tract_add1",dX", y+2, y"g31
#define Wi2 {2,gE dA1,q2 dA1,q2 dA1 mJ"tract_add2",dX", y, y+2"g31
#define Yi2 {o5 qM1 q2 qM1 q2 qM1"x"dO"tract_and1_l",dX", y&z, y<1"g31
#define Sj2 {o5 q41 q2 q41 q2 q41"x"dO"tract_and1_nl",dX", y&z, z"g31
#define Tj2 {o5 qN1 q2 qN1 q2 qN1"x"dO"tract_and2_l",dX", y<1, y&z"g31
#define Uj2 {o5 q51 q2 q51 q2 q51"x"dO"tract_and2_nl",dX", z, y&z"g31
#define Wj2 {2,gE o71,q2 o71,q2 o71 mJ"tract_min",dX", min(y,2), min(y,5))"},
#define Yj2 {2,gE o81,q2 o81,q2 o81 mJ"tract_mul",dX", y*2, y*"h62
#define Sk2 {2,gE dB1,q2 dB1,q2 dB1 mJ"tract_mul1",dX", y*2, y"g31
#define Tk2 {2,gE dC1,q2 dC1,q2 dC1 mJ"tract_mul2",dX", y, y*2"g31
#define Uk2 {o5 h11 q2 h11 q2 h11"x"dO"tract_or1_l",dX", y|z, y<1"g31
#define Wk2 {o5 qO1 q2 qO1 q2 qO1"x"dO"tract_or1_nl",dX", y|z, z"g31
#define Yk2 {o5 h21 q2 h21 q2 h21"x"dO"tract_or2_l",dX", y<1, y|z"g31
#define Sl2 {o5 qP1 q2 qP1 q2 qP1"x"dO"tract_or2_nl",dX", z, y|z"g31
#define Tl2 {2,N(-4.0,0.0),mT1 N(0.5,0.0)qN,q2 If_extract_sin,q2 If_extract_sin,0 mJ"tract_sin",dX", sin(y), "gW3
#define Ul2 {2,h2 If_join_add,q2 If_join_add,0 qK"if_join_add",dX dA" +"aO1
#define Wl2 {1,qO3 N(5.0,0.0),qD1 wB1 q2 wB1 q2 wB1 oQ1"if_join_add2","x + 10 +"hK1"<4, 3,4"g31
#define Yl2 {2,h2 If_join_and,q2 If_join_and,0 qK"if_join_and",dX dA" &"aO1
#define Sm2 {2,h2 If_join_max,q2 If_join_max,0 qK"if_join_max","max("dX dA", "hU3")))"},
#define Tm2 {2,h2 If_join_min,q2 If_join_min,0 qK"if_join_min","min("dX dA", "hU3")))"},
#define Um2 {2,h2 If_join_mul,q2 If_join_mul,0 qK"if_join_mul",dX dA" *"aO1
#define Wm2 {1,qO3 N(5.0,0.0),qD1 wC1 q2 wC1 q2 wC1 oQ1"if_join_mul2","x * 10 *"hK1"<4, 3,4"g31
#define Ym2 {2,h2 If_join_or,q2 If_join_or,0 qK"if_join_or",dX dA" | "hU3"))"},
#define Sn2 {1 mI Ifabs,q2 Ifabs,q2 Ifabs,oQ1"ifabs","1"dM1"< 0,-x,"gV3"  10"dM1"<=0,-x,"gV3" 100"dM1"> 0,-x,"gV3"1000"dM1">=0,-x,"mL1 gM3 gM3"10000"dM1"< 0,x"mN2 gM3"   100000"dM1"<=0,x"mN2 gM3"  1000000"dM1"> 0,x"mN2"  10000000"dM1">=0,x,-"mH2
#define Tn2 {3 gU Ifabsnot,q2 Ifabsnot wP"ifabsnot","if(!(sin(x)+1.2), y,z"g31
#define Un2 {3 gU Ifconst,q2 Ifconst wP"ifconst","if(1, x,y) + if(0,z,y"g31
#define Wn2 {4,N(0.0,0.0)qV Ififconst,q2 Ififconst,0,"w,"mH"ififconst","if("dX",1,y),z,w) + if(if(w,z,0),"oT2
#define Yn2 {4 mI w62 q2 w62 q2 w62"b,d,"oU2"ifmerge",dX oC2"y,x,b)"oC2"y,x,d)) +  if(b,if(d,y,x)"oC2"d,b,"mH2
#define So2 {4 mI hX2 q2 hX2 q2 hX2"a,b,"oU2"ifmerge2",dX oC2"y,a,b)"oC2"b,a,b))"},
#define To2 {4 mI g02 q2 g02 q2 g02"a,b,"oU2"ifmerge2b",dX oC2"y,a,b)"oC2"b,b,a))"},
#define Uo2 {hO Ifnop,q2 Ifnop,q2 Ifnop qK"ifnop",dX",y,y"g31
#define Wo2 {gB1 Ifnot,q2 Ifnot wP"ifnot","if(!x, y,z"g31
#define Yo2 hI L_abs,q2 L_abs,q2 L_abs qK"l_abs","(x+2) & abs(x)"oR1
#define Sp2 hI w72,q2 w72,q2 w72 qK"l_mulabs","(x*abs(y))"oR1
#define Tp2 hI w82,q2 w82,q2 w82 qK"l_mulneg","(x*y*-5)"oR1
#define Up2 hI w92,q2 w92,q2 w92 qK"l_notnot","(x+2) & !!x"oR1
#define Wp2 {hO hZ2,q2 hZ2,q2 hZ2 qK"le_and_eq",hS3"& "oS1
#define Yp2 {hO d02,q2 d02,q2 d02 qK"le_and_ne",hS3"& "oT1
#define Sq2 {hO wA2,q2 wA2,q2 wA2 qK"le_or_eq",hS3"| "oS1
#define Tq2 {hO wB2,q2 wB2,q2 wB2 qK"le_or_ne",hS3"| "oT1
#define Uq2 {hO d12,q2 d12,q2 d12 qK"lt_and_eq"d22 oS1
#define Wq2 {hO d32,q2 d32,q2 d32 qK"lt_and_ge"d22 m6},
#define Yq2 {hO d42,q2 d42,q2 d42 qK"lt_and_gt"d22"(x > y"g31
#define Sr2 {hO d52,q2 d52,q2 d52 qK"lt_and_le"d22 oY2
#define Tr2 {hO d62,q2 d62,q2 d62 qK"lt_and_ne"d22 oT1
#define Ur2 {hO wC2,q2 wC2,q2 wC2 qK"lt_or_eq"m22 oS1
#define Wr2 {hO wD2,q2 wD2,q2 wD2 qK"lt_or_ge"m22 m6},
#define Yr2 {hO wE2,q2 wE2,q2 wE2 qK"lt_or_gt"m22"(x > y"g31
#define Ss2 {hO wF2,q2 wF2,q2 wF2 qK"lt_or_le"m22 oY2
#define Ts2 {hO wG2,q2 wG2,q2 wG2 qK"lt_or_ne"m22 oT1
#define Us2 {1,N(-1.0,0.0),mF1 N(0.25,0.0)qN,q2 Lthalf,q2 Lthalf,gQ"lthalf","x<if(1,0.5,0"g31
#define Ws2 {o5 aJ1 q2 aJ1 q2 aJ1 mH"mergemulabs","abs(x)*abs(y)*z"},
#define Ys2 {3,N(0.0,0.0),mT1 qD1 aK1 q2 aK1 q2 aK1 mH"mixedminmax","max(z,min(x,max(max(z,y),x)))"gS3"10*min(z,max(x,min(y,x)))"gS3"100*min(max(x,y),min(y,z)) +  1000*max(min(x,y),max(y,z))"},
#define St2 {2 gU Muland2,q2 Muland2,0 qK"muland2",wN2" !!y"},
#define Tt2 {3 gU Muland2plus,q2 Muland2plus wP"muland2plus",wN2" !!y * z"},
#define Ut2 {3 gU Muland3,q2 Muland3 wP"muland3",wN2" !!y * !!z"},
#define Wt2 {2 gU Mulandlt,q2 Mulandlt,0 qK"mulandlt",wN2" (y<0"g31
#define Yt2 {2,N(0.25,0.0),mF1 N(0.25,0.0)qN,q2 Mulimmlog,q2 Mulimmlog,0 qK"mulimmlog","log(if(1,5,0)*x*y"g31
#define Su2 {2 gU Mulnor2,q2 Mulnor2,0 qK"mulnor2",hM3},
#define Tu2 {3 gU Mulnor2plus,q2 Mulnor2plus wP"mulnor2plus",hM3" * z"},
#define Uu2 {3 gU Mulnor3,q2 Mulnor3 wP"mulnor3",hM3" * !z"},
#define Wu2 {hO Nand2,q2 Nand2,q2 Nand2 qK"nand2",hK3},
#define Yu2 {gB1 g12 q2 g12 q2 g12 mH"nand2plus",hK3" | z"},
#define Sv2 {gB1 Nand3,q2 Nand3,q2 Nand3,mH"nand3",hK3" | !z"},
#define Tv2 {1 mI Negceil,q2 Negceil,gQ"negceil","ceil(x*("gY2"-abs(x)-1))"},
#define Uv2 {1 mI Negcos,q2 Negcos,gQ"negcos","cos"wP2
#define Wv2 {1 mI Negcosh,q2 Negcosh,gQ"negcosh","cosh"wP2
#define Yv2 {1 mI Negfloor,q2 Negfloor,gQ"negfloor","floor(x*("gY2"-abs(x)-1))"},
#define Sw2 {1 mI Negsin,q2 Negsin,gQ"negsin","sin(x*"qF1
#define Tw2 {1 mI Negsinh,q2 Negsinh,gQ"neg"wL2,wL2 wP2
#define Uw2 {1,N(0.0,0.0)qV Neq0,q2 Neq0,q2 Neq0,oQ1"neq0","(x!=if("qT1" (if(1,0,0)!=x)"},
#define Ww2 {1,N(0.0,0.0)qV Neq1,q2 Neq1,q2 Neq1,oQ1"neq1","(!x!=if("oM1},
#define Yw2 {hO Nor2,q2 Nor2,q2 Nor2 qK"nor2",hL3},
#define Sx2 {gB1 d72 q2 d72 q2 d72 mH"nor2plus",hL3" & z"},
#define Tx2 {gB1 Nor3,q2 Nor3,q2 Nor3,mH"nor3",hL3" & !z"},
#define Ux2 {hO Not_eq,q2 Not_eq,q2 Not_eq qK"not_eq",dX" = "gP3
#define Wx2 {hO Not_ge,q2 Not_ge,q2 Not_ge qK"not_ge",dX hB3 gP3
#define Yx2 {hO Not_gt,q2 Not_gt,q2 Not_gt qK"not_gt",dX" > "gP3
#define Sy2 {hO Not_le,q2 Not_le,q2 Not_le qK"not_le",dX hJ3 gP3
#define Ty2 {hO Not_lt,q2 Not_lt,q2 Not_lt qK"not_lt",dX" < "gP3
#define Uy2 {hO Not_ne,q2 Not_ne,q2 Not_ne qK"not_ne",dX hC3 gP3
#define Wy2 {2,gE Notnot,q2 Notnot,q2 Notnot qK"notnot","!!x + if(y, 1,0"g31
#define Yy2 {1 gU Posnot,q2 Posnot,gQ"posnot","!(sin(x) + 1.2"g31
#define Sz2 {1 gU Posnotnot,q2 Posnotnot,gQ"posnotnot","!!(sin(x) + 1.2"g31
#define Tz2 {1,N(0.25,0.0),mF1 N(0.25,0.0)qN,q2 Powimmaddimmlog,q2 Powimmaddimmlog mO1"immaddimmlog","pow(5, log(x)+1"g31
#define Uz2 {1,N(0.25,0.0),oJ2,N(0.25,0.0)qN,q2 Powimmlog,q2 Powimmlog mO1"immlog","pow(3, log(x)) + pow(5, log(x)*sin(x))"},
#define Wz2 {hN Powmulimm_fnen,q2 Powmulimm_fnen oC dN1"mulimm_fnen",oD1"^(-8"g31
#define Yz2 {2,dL Powmulimm_fnep,q2 Powmulimm_fnep oC dN1"mulimm_fnep",oD1"^(4"g31
#define S_2 {1,N(-3.0,0.0),N(-1.0,0.0),N(0.5,0.0)qN,q2 Powmulimm_fnfn,q2 Powmulimm_fnfn mO1"mulimm_fnfn","((-5.1)*x)^(-7.1"g31
#define T_2 {2,dL Powmulimm_fnfp,q2 Powmulimm_fnfp oC dN1"mulimm_fnfp",oD1"^7.1"},
#define U_2 {2,dL Powmulimm_fpfp,q2 Powmulimm_fpfp oC dN1"mulimm_fpfp","(5.1*x*y)^7.1"},
#define W_2 {1 gU Sub1cos2,q2 Sub1cos2,gQ"sub1cos2","1-cos(x)^2"},
#define Y_2 {1 gU Sub1sin2,q2 Sub1sin2,gQ"sub1sin2","1-"qA2"^2"},
#define S03 {1,N(-9.42477796076937971538793014983850865259,0.0),N(9.42477796076937971538793014983850865259,0.0),N(0.785398163397448309615660845819875721049292349,0.0)qN,q2 Trig_modulo,q2 Trig_modulo,gQ"trig_modulo","cos(x+pi"qG1"2/3"qG1"5/2"qG1"6/2"qG1 wQ2 gM3 oE1")"oX1"2/3)"oX1"5/2)"oX1"6/2)"oX1 wQ2 gM3"cos(x-pi"dG1"2/3"dG1"5/2"dG1"6/2"dG1 wQ2"  "oF1")"wR2"2/3)"wR2"5/2)"wR2"6/2)"wR2"7/2"g31
#define T03 {1,N(-3.0,0.0),qO3 N(0.25,0.0)qN,q2 Trunc_from_if,q2 Trunc_from_if,gQ"trunc_from_if",dX">0,  "h63 dD2">=0, "h63 dD2"<0,  "h43 dD2"<=0,"hN3">0, "hN3">=0,"hN3"<0,  "h63" 10*"dX"<=0, floor(x),ceil"g91
#define U03 {1,N(-5.0,0.0),N(5.0,0.0),qD1 wH2 q2 wH2 q2 wH2"x"q6"/xaddnot","!(x+if(1,4,4))"},
#define W03 {1,N(-5.0,0.0),N(5.0,0.0),qD1 mM1 q2 mM1 q2 mM1"x"q6"/xaddnotnot","!!(x+if(1,4,4))"},
#define N(x) (x)
#define P(x) N(x##.0)
namespace
cpp_01unit_operators{using
namespace
FUNCTIONPARSERTYPES;q3
Add_cd
aC2
Add_d
aC2
Add_i
aC2
Addsub_cd
qU1
Addsub_d
qU1
Addsub_i
qU1
And_d
qO
qK2>=gW2?fp_abs(y)>=gW2:dT2
And_i
qO
x!=oF2?y!=oF2:q0
hY2
Cmpeq_cd
qO
x==mD1
Cmpeq_d
qO
x==mD1
Cmpeq_i
qO
x==mD1
Cmpge_d
qO
x>=mD1
Cmpge_i
qO
x>=mD1
Cmpgt_d
qO
x>mD1
Cmpgt_i
qO
x>mD1
Cmple_d
qO
x<=mD1
Cmple_i
qO
x<=mD1
Cmplt_d
qO
x<mD1
Cmplt_i
qO
x<mD1
Cmpne_cd
qO
x!=mD1
Cmpne_d
qO
x!=mD1
Cmpne_i
qO
x!=mD1
Div_d
qO(x-q0(0.25l))/mD1
Div_i
qO
x/(y+q0(3l
qU
Divmul_d
hB
x*y*x*x/z*(x-q0(0.25l
qU
Divmul_i
hB
x*y*x*x/(z+g13)*(x+q0(4l
qU
Inv_d
qT
dI1/x;}
q3
Inv_i
qT
dI1/x;}
q3
Mod(qD,&z
oI2
qA
fmod(x,z);}
q3
Mod_i(qD,&z
oI2
qA
x%(z+q0(3l
qU
Mul_cd
qO
x*mD1
Mul_d
qO
x*mD1
Mul_i
qO
x*(y+q0(4l
qU
Neg_cd
qT-x;}
q3
Neg_d
qT-x;}
q3
Neg_i
qT-x;}
q3
Not_d
qT
qK2<q0(0.5l
qU
Not_i
qT
q0(x==dT2
Notnot_d
qT
qK2>=q0(0.5l
qU
Notnot_i
qT
q0(x!=dT2
Or_d
qO
qK2<gW2?fp_abs(y)>=gW2:q0(1l
qU
Or_i
qO
x==oF2?y!=oF2:dI1;}
q3
Sub_cd
qO
x-mD1
Sub_d
qO
x-mD1
Sub_i
qO
x-y
qT3
cpp_02unit_functions{using
namespace
FUNCTIONPARSERTYPES;q3
Abs_cd
qT
std::abs(aU
Abs_d
qT
x<oF2?-x:x;}
q3
Abs_i
qT
x<oF2?-x:x;}
q3
Acos
qT
acos(aU
Acos_deg
dY1
acos(x
qU
Acosh
qT
gC1-1.0
qU
Acosh_deg
dY1
gC1-1.0)qU
Arg
qT
hP
aU
Asin
qT
asin(aU
Asin_deg
dY1
asin(x
qU
Asinh
qT
gC1+1.0
qU
Asinh_deg
dY1
gC1+1.0)qU
Atan
qT
atan(aU
Atan2
qO
atan2(x,y);}
q3
Atan2_deg
qO
r2d(atan2(x,y
qU
Atan_deg
dY1
atan(x
qU
Atanh
qT
log((1.0+x)/(1.0-x))*0.5;}
q3
Cbrt
qT
x<0.0?-exp(log(-x)/3.0):(x>0.0?exp(log(x)/3.0):0.0);}
q3
Ceil
qT
ceil(aU
Conj
qT
fp_conj(aU
Cos
qT
cos(aU
Cos_deg
qT
cos(m01
Cosh
qT
cosh(aU
Cosh_deg
qT
cosh(m01
Exp
qT
exp(aU
Exp2
qT
exp(x*fp_const_log2<q0>(qU
Floor
qT
floor(aU
Hypot
qO
sqrt(x*x+y*y);}
q3
If_d
hB
fp_abs(x)>=gW2?y:z;}
q3
If_i
hB(x!=oF2)?y:z;}
q3
Imag
qT
fp_imag(aU
Int
qT
fp_floor(x+q0(0.5l
qU
Log
qT
log(aU
Log2
qT
log(x)*1.4426950408889634073599246810018921374266;}
q3
Log10
qT
log(x)*0.43429448190325182765112891891660508229;}
q3
Log_cd
qT
std::log(aU
Max
qO
x>y?x:mD1
Min
qO
x<y?x:mD1
Polar
qO
fp_polar(x,y);}
q3
Pow_neg
qO
pow(-x*0.25,y);}
q3
Pow_pos
qO
pow(x,y);}
q3
Real
qT
fp_real(aU
Sin
qT
sin(aU
Sin_deg
qT
sin(m01
Sinh
qT
sinh(aU
Sinh_deg
qT
sinh(m01
Sqrt
qT
sqrt(aU
Sqrt_cd
qT
std::sqrt(aU
Tan
qT
tan(aU
Tan_deg
qT
tan(m01
Tanh
qT
tanh(aU
Tanh_deg
qT
tanh(m01
Trunc
qT
x<0.0?ceil(x):floor(x)qT3
cpp_03unit_constants{using
namespace
FUNCTIONPARSERTYPES;q3
E_d
qT
exp(x*0.0+1.0);}
q3
L2_d
qT
log(x*0.0+2.0);}
q3
L10_d
qT
log(x*0.0+10.0);}
q3
Pi_d
qT
atan2(x*0.0,-1.0)qT3
cpp_10optimizer_bytecode{using
namespace
FUNCTIONPARSERTYPES;q3
Abs
qT(g13)dT1
Abscos
qT
fp_cos(d61
Abscosh
qT
aD2
d61
Abseq0
qT
qB2
oW
0l
qL2
d61
Absevenconstpow
g52
oW
1506l
qU
Absmulevenconstpow
qO
mA2
fp_abs(x)*y,q0(1506l
qU
mV2
qT
qB2
oW
0l
qL2
d61
Absneverneg
qT
fp_acos(aU
Absnot
g42
d61
Absnot2
g42
gD1
qU
Absnot3
qO
fp_not(fp_not(hA2,y)qU
Absnot4
g42
fp_not(gD1)qU
wZ1
g42
fp_notNot((x*x)qU
mF2(qD;q0
b0[2]qA
userDefFuncSub<q0>((b0[0]=(fp_greaterOrEq(oW
4l))),b0[1]=(fp_greaterOrEq(oW
0l))),b0
qU
mG2(qD;q0
b1[2]qA
userDefFuncSub<q0>((b1[0]=(fp_less(oW
4l))),b1[1]=(fp_less(oW
0l))),b1
qU
Abssqr
qT
x*x;}
q3
Absyxpow_neg
g52
qW-4.0),1.5);}
q3
Absyxpow_pos
g52
qW
4.0),1.5);}
q3
Acos
qT
acos(0.7)dT1
Acos_deg
dY1
acos(0.7))dT1
Acosh
qT
mC
1.1-1.0))dT1
Acosh_deg
dY1
mC
1.1-1.0)))dT1
Acoshcosh
qT
aD2
fp_acosh(x
qU
Acoshsinh
qT
fp_sinh(fp_acosh(x
qU
Add
qT
wV1+g13
dT1
Add0
qT
x+oF2
dT1
Addexp
qT
fp_exp(x+q0(4l
qU
Addexp2
qT
g73
x+q0(4l
qU
And
qT
fp_and
hW1+fp_and(wV1,oF2)+fp_and(oF2,wV1)+fp_and(oF2,dT2
Asin
qT
asin(0.7)dT1
Asin_deg
dY1
asin(0.7))dT1
Asinh
qT
mC
1.1+1.0))dT1
Asinh_deg
dY1
mC
1.1+1.0)))dT1
Asinhcosh
qT
aD2
fp_asinh(x
qU
Asinhsinh
qT
fp_sinh(fp_asinh(x
qU
Atan
qT
atan
dX2
Atan2
qT
atan2(5.0,4.0)dT1
Atan2_deg
dY1
atan2(5.0,4.0))dT1
Atan2tan
qO
dM2
qG2
x,y
qU
Atan_deg
dY1
atan(1.1))dT1
Atanh
qT
log((1.0+0.7)/(1.0-0.7))*0.5+x;}
q3
Cbrt
qT
exp(log(1.1)/3.0)dT1
Ceil
qT
ceil
dX2
Ceilneg
qT
fp_ceil(-aU
Cmp_acos(qP
hK
qM
hK))qR
hK))qS
hK))qQ
hK
qF
hK
qU
Cmp_acos_outrange(qP
dJ2
qM
qW1
gX)qR
qW1
gX)qS
qW1
gX)qQ
dJ2
qF
dJ2
qU
mW2(qP(q0(dG
qM(q0(dG))qR(q0(dG))qS(q0(dG))qQ(q0(dG
qF(q0(dG
qU
Cmp_asin(qP
hL
qM
hL))qR
hL))qS
hL))qQ
hL
qF
hL
qU
Cmp_asin_outrange(qP
dK2
qM
gI3
qR
gI3
qS
gI3
qQ
dK2
qF
dK2
qU
Cmp_atan(qP
dH
qM
dH))qR
dH))qS
dH))qQ
dH
qF
dH
qU
Cmp_exp(qP
o6
qM
o6))qR
o6))qS
o6))qQ
o6
qF
o6
qU
Cmp_exp2(qP
dI
qM
dI))qR
dI))qS
dI))qQ
dI
qF
dI
qU
Cmp_exp2_neg(qP
oT
qM
oT))qR
oT))qS
oT))qQ
oT
qF
oT
qU
Cmp_exp_neg(qP
w4
qM
w4))qR
w4))qS
w4))qQ
w4
qF
w4
qU
Cmp_log2_nn(qP
hC
mK
qM
hC
wH1
qR
hC
wH1
qS
hC
wH1
qQ
hC
mK
qF
hC
mK
qU
Cmp_log2_np(qP
hC
m11
qM
hC
m11))qR
hC
m11))qS
hC
m11))qQ
hC
m11
qF
hC
m11
qU
Cmp_log2_pn(qP
hC
mU1
hC
gF2
qR
hC
gF2
qS
hC
gF2
qQ
hC
gG2
qF
hC
gG2
qU
Cmp_log2_pp(qP
hC
gH2
qM
hC
gH2))qR
hC
gH2))qS
hC
gH2))qQ
hC
gH2
qF
hC
gH2
qU
Cmp_log10_nn(qP
h1
mK
qM
h1
wH1
qR
h1
wH1
qS
h1
wH1
qQ
h1
mK
qF
h1
mK
qU
Cmp_log10_np(qP
h1
m21
qM
h1
m21))qR
h1
m21))qS
h1
m21))qQ
h1
m21
qF
h1
m21
qU
Cmp_log10_pn(qP
h1
mU1
h1
gF2
qR
h1
gF2
qS
h1
gF2
qQ
h1
gG2
qF
h1
gG2
qU
Cmp_log10_pp(qP
h1
gI2
qM
h1
gI2))qR
h1
gI2))qS
h1
gI2))qQ
h1
gI2
qF
h1
gI2
qU
Cmp_log_nn(qP
hP
mK
qM
hP
wH1
qR
hP
wH1
qS
hP
wH1
qQ
hP
mK
qF
hP
mK
qU
Cmp_log_np(qP
hP
x)aE2
qM
hP
x)aE2))qR
hP
x)aE2))qS
hP
x)aE2))qQ
hP
x)aE2
qF
hP
x)aE2
qU
Cmp_log_pn(qP
hP
mU1
hP
gF2
qR
hP
gF2
qS
hP
gF2
qQ
hP
gG2
qF
hP
gG2
qU
Cmp_log_pp(qP
hP
gJ2
qM
hP
gJ2))qR
hP
gJ2))qS
hP
gJ2))qQ
hP
gJ2
qF
hP
gJ2
qU
gB2(qP(x
o7
qM(x
o7))qR(x
o7))qS(x
o7))qQ(x
o7
qF(x
o7
qU
gD2(qP(x
o8
qM(x
o8))qR(x
o8))qS(x
o8))qQ(x
o8
qF(x
o8
qU
mX2(qP(-x),aF2(-x),aG2
qR(-x),aG2
qS(-x),aG2
qQ(-x),aH2(-x)qC2
Cmp_powx_n_n(qP
aM2
qM
aM2))qR
aM2))qS
aM2))qQ
aM2
qF
aM2
qU
Cmp_powx_n_p(qP
aJ2
qM
aJ2))qR
aJ2))qS
aJ2))qQ
aJ2
qF
aJ2
qU
Cmp_powx_nn(qP
o9-aF2
o9-aG2
qR
o9-aG2
qS
o9-aG2
qQ
o9-aH2
o9-q0(4l
qU
Cmp_powx_np(qP
o9
aF2
o9
aG2
qR
o9
aG2
qS
o9
aG2
qQ
o9
aH2
o9
q0(4l
qU
Cmp_powx_p_n(qP
aK2
qM
aK2))qR
aK2))qS
aK2))qQ
aK2
qF
aK2
qU
Cmp_powx_p_p(qP
aL2
qM
aL2))qR
aL2))qS
aL2))qQ
aL2
qF
aL2
qU
Cmp_powx_pn(qP
hR1
qM
hR1))qR
hR1))qS
hR1))qQ
hR1
qF
hR1
qU
Cmp_powx_pp(qP
hT1
qM
hT1))qR
hT1))qS
hT1))qQ
hT1
qF
hT1
qU
Cmp_powy_n_n(qP
qW-hU
qM
qW-hU))qR
qW-hU))qS
qW-hU))qQ
qW-hU
qF
qW-hU
qU
Cmp_powy_n_p(qP
qW-hV
qM
qW-hV))qR
qW-hV))qS
qW-hV))qQ
qW-hV
qF
qW-hV
qU
Cmp_powy_nn(qP
qW-aQ
qM
qW-aQ))qR
qW-aQ))qS
qW-aQ))qQ
qW-aQ
qF
qW-aQ
qU
Cmp_powy_np(qP
qW-aR
qM
qW-aR))qR
qW-aR))qS
qW-aR))qQ
qW-aR
qF
qW-aR
qU
Cmp_powy_p_n(qP
qW
hU
qM
qW
hU))qR
qW
hU))qS
qW
hU))qQ
qW
hU
qF
qW
hU
qU
Cmp_powy_p_p(qP
qW
hV
qM
qW
hV))qR
qW
hV))qS
qW
hV))qQ
qW
hV
qF
qW
hV
qU
Cmp_powy_pn(qP
qW
aQ
qM
qW
aQ))qR
qW
aQ))qS
qW
aQ))qQ
qW
aQ
qF
qW
aQ
qU
Cmp_powy_pp(qP
qW
aR
qM
qW
aR))qR
qW
aR))qS
qW
aR))qQ
qW
aR
qF
qW
aR
qU
Cmp_sinh(qP
dJ
qM
dJ))qR
dJ))qS
dJ))qQ
dJ
qF
dJ
qU
mY2(qP(qY1
qM(qY1))qR(qY1))qS(qY1))qQ(qY1
qF(qY1
qU
mR1(qP(qZ1
qM(qZ1))qR(qZ1))qS(qZ1))+-q0(16l)*fp_greaterOrEq((qZ1
qF(qZ1
qU
Cmp_tanh(qP
hM
qM
hM))qR
hM))qS
hM))qQ
hM
qF
hM
qU
Cmp_tanh_outrange(qP
dL2
qM
qB3
qR
qB3
qS
qB3
qQ
dL2
qF
dL2
qU
Cmpeq
qT
fp_equal
hW1+qB2
q0(4l)qC2
Cmpge
qT
qK1
3l),wV1)+x+qK1
8l)qC2
Cmpgt
qT
fp_less(g13,wV1)+x
o12
q0(8l)qC2
Cmple
qT
qK1
5l),g13)+x+qK1
4l),q0(8l
qU
Cmplt
qT
fp_less
hW1;}
q3
Cmpne
qT
fp_nequal
hW1+fp_nequal(q0(4l)qC2
Cos
qT
cos
dX2
Cos_deg
qT
cos
gZ3
Cosh
qT
cosh
dX2
Cosh_deg
qT
cosh
gZ3
Deg
qO
r2d(y)+r2d(x)+r2d(y)*q0(4l);}
q3
Degxmul
dY1
gD1))*gX;}
q3
Div
qT(wV1/aG2
dT1
Div1
qT
x/dI1
dT1
Divxx
qT
x+x/x
dT1
qP2
qT
x*q0(14l);}
q3
Dupaddmulh
qT
x;}
q3
Dupaddmulmul7
qO
y*x*q0(14l);}
q3
Dupaddmulmulh
qO
y*x;}
q3
hG2(qD;q0
b2[2]qA
userDefFuncSub<q0>((b2[0]=(fp_min(x,x)),b2[1]=(fp_max(x,x)),b2
qU
qQ2(qD;q0
b3[2]qA
userDefFuncSub<q0>((b3[0]=(x
gP2
x)),b3[1]=(x+fp_max(x,x)),b3
qU
qR2(qD,qZ3
b4[2]qA
userDefFuncSub<q0>((b4[0]=(fp_min(y,x)),b4[1]=(fp_max(y,x)),b4
qU
qS2
qT
x*d21
Dupxpowmul
qT
qW
q0(4l
qU
Eq0
qT
qB2
x,q0(0l
qL2
aU
Eq1
qT
qB2
fp_not(x),q0(1l
qU
Exp
qT
exp
dX2
Exp2
qT
exp(1.1*0.693147180559945309417232121458176568075500134)dT1
Exp2div
qO
x/g73
y);}
q3
Exp2log2
qT
hC
g73
x
qU
Exp2xpow
g52
g73
x),1506.0);}
q3
Expdiv
qO
x/fp_exp(y);}
q3
Explog
qT
hP
fp_exp(x
qU
Explog2
qT
x/fp_const_log2<q0>();}
q3
Explog10
qT
x/fp_const_log10<q0>();}
q3
Expxpow
g52
fp_exp(x),1506.0);}
q3
Floor
qT
floor
dX2
Floorneg
qT
fp_floor(-aU
mZ2
wA
oW
0l
dO2
fp_abs(x))qR
oW
0l
gK2
d61
Ge0_neg
wA
oX
0l
dO2
m91))qR
oX
0l
gK2
m91
qU
Ge0_pos
wA
mP
dO2
gD1))qR
mP
gK2
gD1
qU
q03
wA
oW
1l))+qC3
fp_abs(x))qR
oW
1l
gL2
d61
Ge1_neg
wA
oX
1l))+qC3
m91))qR
oX
1l
gL2
m91
qU
Ge1_pos
wA
qW1
dI1)+qC3
gD1))qR
qW1
q0(1l
gL2
gD1
qU
Gehalf
qT
hY,q0(0.5l
qU
q13
qT
g11
oW
0l
gM2
fp_abs
dR
oW
0l))gN2
d61
Gt0_neg
qT
g11
oX
0l
gM2
fp_sin
dR
oX
0l))gN2
m91
qU
Gt0_pos
qT
g11
mP
gM2
fp_acos
dR
mP))gN2
gD1
qU
q23
qT
g11
oW
gO2
fp_abs
dR
oW
1l))qS
dI1,d61
Gt1_neg
qT
g11
oX
gO2
fp_sin
dR
oX
1l))qS
dI1,m91
qU
Gt1_pos
qT
g11
qW1
q0(gO2
fp_acos
dR
qW1
dI1)qS
dI1,gD1
qU
Gtminushalf
qT
oG,-q0(0.5l
qU
Hypot
qT
sqrt(5.0*5.0+4.0*4.0)dT1
Immsub
qT
x-d21
Int
qT
x+(((((hX1
1.1l))-hX1
1.6l)))-hX1
1.5l)))-hX1-1.1l)))-hX1-1.6l)))-hX1-1.5l)qU
Intceil
qT
fp_ceil
mA1
Intfloor
qT
fp_floor
mA1
Intint
qT
fp_int
mA1
Inttrunc
qT
fp_trunc
mA1
Invdiv
qO
y/(dI1/aU
Invinv
qT
dI1/(dI1/aU
Invmul
qO
y*(dI1/aU
Leminushalf
qT
dU,-q0(0.5l
qU
Log
qT
log
dX2
Log2
qT
log(1.1)*1.4426950408889634073599246810018921374266+x;}
q3
Log2exp1
qT
fp_exp(hC
x
qU
Log2exp2
qT
g73
hC
gD1)qU
Log10
qT
log(1.1)*0.43429448190325182765112891891660508229+x;}
q3
Logexp1
qT
fp_exp(hP
x
qU
Logexp2
qT
fp_exp(hP
gD1)qU
Logmul
qT
hP
m4
Logmul2
qT
hC
m4
Logmul10
qT
h1
m4
Lt0
qT
fp_less(fp_abs(x),x-x)-aT,x-aU
Lthalf
qT
aT,q0(0.5l
qU
Max
qT
wV1
dT1
Min
qT
q0(4l)dT1
Mod
qT
fp_mod(wV1,aG2
dT1
Mul
qT(wV1*aG2
dT1
Mul1
qT
x*dI1
dT1
Mul1b
qT((x*q0(0.2l))*wV1)dT1
Mul2
qT
x
dT1
Mul4
qO
y*(x*gX)*gX+(y*gX)*gX;}
q3
Mul_zero
qO(x*y+dI1)+(m91)+mB2
y))*hP
x)*y*x*q0
hY2
Mulminus1
qT
x*-1.0;}
q3
Mulneg
qT-(x*h82
a32
qT
x/q0(4l)dT1
Neg
qT((-((5.0))))dT1
Negabs
qT
fp_abs(-aU
Negadd
qO
x+(-y);}
q3
Negceil
qT-fp_ceil(aU
Negcos
qT
fp_cos(-aU
Negcosh
qT
aD2-aU
Negdiv
qT(-x)/d21
Negfloor
qT-fp_floor(aU
Negmul
qT(-x)*d21
Negneg
qT-(-(-(-(-(-(x))))qU
Negnot
g42-aU
Negsin
qT
mB2-aU
Negsinh
qT
fp_sinh(-aU
Negsqr
qT
x*x;}
q3
Negsub
qO
x-(-y);}
q3
Negtan
qT
dM2-aU
Negtanh
qT
fp_tanh(-aU
Neq0
qT(oY,oF2))+(fp_nequal(oF2,x
qU
Neq1
mK1
fp_not(x),q0(1l
qU
Not
g42
g13)dT1
Not_eq
qO
x!=mD1
Not_ge
qO
x<mD1
Not_gt
qO
x<=mD1
Not_le
qO
x>mD1
Not_lt
qO
x>=mD1
Not_ne
qO
x==mD1
Notnot
qT
fp_notNot(aU
hH2
g42
aU
qT2
g42
aU
Or
qT
fp_or
hW1
qD3
wV1,oF2)qD3
oF2,wV1)qD3
oF2,dT2
Pow_neg
qT
pow(-0.25,4.0)dT1
Pow_pos
qT
pow(1.1,7.1)dT1
Powdiv
qO
x/qW
y);}
q3
Powhalf
qT
qW
q0(0.5l
qU
Powinv
qO
dI1/qW
y);}
q3
Powminushalf
qT
qW-q0(0.5l
qU
Powminusone
qT
qW-q0(1.0l
qU
Powminusthird
qT
qW(q0(-1.0l)/q0(3.0l)qU
Powthird
qT
qW(mF/q0(3.0l)qU
Powxpow
g52
qW
1.7),1506.0);}
q3
Rad
qO
d2r(y)+d2r(x)+d2r(x)*q0(4l);}
q3
Radxmul
qT
fp_cos(d2r(x+x+x+x
qU
Rsqrt
qT
1.0/h72
aU
Sin
qT
sin
dX2
Sin_deg
qT
sin
gZ3
Sincos_cci
qT
mE)+dI1/fp_cos(aU
Sincos_cic
qT
dI1/mE)+fp_cos(aU
Sincos_sc
qT
m91)+fp_cos(aU
Sincos_sci
qT
m91)+dI1/fp_cos(aU
Sincos_sis
qT
dI1/m91
a2);}
q3
Sincos_ssi
qT
m91)+dI1/mB2
aU
Sincos_tan
qT
dM2
aU
Sincos_tit
qT
dI1/dM2
x)+dM2
aU
Sincos_tti
qT
dM2
x)+dI1/dM2
aU
Sinh
qT
sinh
dX2
Sinh_deg
qT
sinh
gZ3
mI2
qT(-x)*x;}
q3
mJ2
qT
x*(-aU
Sqr_xx
qT
x*x;}
q3
oM2
qO
y*-x*x;}
q3
oN2
qO
y*x*-x;}
q3
mK2
qO
y*x*x;}
q3
Sqreq0
qT
qB2
x*x,q0(0l
qL2
x*aU
Sqrlog
qT
hP
x*aU
Sqrlog2
qT
hC
x*aU
Sqrlog10
qT
h1
x*aU
q53
qT
qB2
x*x,q0(0l
qL2
x*aU
Sqrsqrt
qT
h72
x*aU
Sqrt
qT
sqrt
dX2
Sqrtsqr1
g52
h72
x),q0(2l
qU
Sqrtsqr2
g52
h72
gD1)),q0(2l
qU
Sqrxpow
g52
x*x,2402.0);}
q3
Sqrxpow_nonint
g52
x*x,3.5);}
q3
Sub
qT
wV1-g13
dT1
Sub0
qT
x-oF2
dT1
Subxx
qT
x+(x-x)+x+(dI1-x+aU
Tan
qT
tan
dX2
Tan_deg
qT
tan
gZ3
Tanh
qT
tanh
dX2
Tanh_deg
qT
tanh
gZ3
Trunc
qT
1.0+x;}
q3
Xaddnot
g42
x+q0(4l
qU
Xaddnotnot
qT
d81+q0(4l
qU
Xmulrad
qT
fp_cos(d2r(x
hD3
qU
Xmulsinhneg
qT-fp_sinh(x*h82
Xmulsinneg
qT-m91*h82
Xmultanhneg
qT-fp_tanh(x*h82
Xmultanneg
qT-dM2
x*h82
Xsqryfsqrhypot
qT
fp_hypot(hP
x),hC
x
qU
Xsqrysqrhypot
qO
fp_hypot(hP
x),y);}
q3
Xxdup
qT
x-x;}
q3
Xxfdup
qT
x-x;}
q3
oO2
qO
y*fp_abs(x)*fp_abs(aU
Ypowxpow
g52
qW
38.5),5.0)qT3
cpp_11optimizer_constaddmul{using
namespace
FUNCTIONPARSERTYPES;q3
t1(g93
dI1/a)*d21
t2(qC
qA
wV1*a;}
q3
t3(qC
qA
wV1/a;}
q3
t4
g5(a*wV1)*b;}
q3
t5
g5(a*wV1)/b;}
q3
t6
g5(dI1/a)*b;}
q3
t7
g5(dI1/a)/b;}
q3
t8
g5
wQ1*(mL*h82
t9
g5
wQ1/(mL*h82
t10
g5
mL*(wV1/a);}
q3
t11
g5
mL/(q0(50l)/a);}
q3
t12(g93-a)+d21
t13
g5
wV1+(a*b);}
q3
t14
g5
wV1-(a*b);}
q3
t15
g5(a+wV1)+mL;}
q3
t16
g5(a+wV1)-mL;}
q3
t17
g5(-a)+mL;}
q3
t18
g5(-a)-mL;}
q3
t19
g5
b+(wQ1+h82
t20
g5
b-(wQ1+h82
t21
g5
mL+(wV1-a);}
q3
t22
g5
mL-(wV1-a);}
q3
t23
g5
h92
b
hX3
t24
g5
h92
wV1
hX3
t25
g5
h92
wV1)*a;}
q3
t26
g5(wQ1/b
hX3
t27
g5(wQ1/b)*a;}
q3
t28
g5((-a)/b)*d21
t29
g5(wV1/b)*a;}
q3
t30(gV2*vars){gV2&b=vars[0]qA(q0(7l)/b)*d21
t31
g5
b*(q0(7l)/-a);}
q3
t32
g5(wV1-b)-a;}
q3
t33
g5(wV1-b)+a;}
q3
t34
g5((a+dN2-b)+d21
t35
g5((-a)-b)+d21
t36(g93
q0(7l)-fp_abs(a
wX
5l);}
q3
t37
g5((q0(7l)-b)+a)+d21
t38
g5
fp_less((wV1*b+wQ1),oF2)*dI1
o12(mL),oF2)*gX;}
q3
t39(g93
a+dN2*d21
t40
g5(b+(a*dN2)*d21
t41
g5(b-(a*dN2)*d21
t42(g93
a+q0(7l
wX
5l);}
q3
t43(g93
a*dN2*wV1
qT3
cpp_20optimizer_optimizations{using
namespace
FUNCTIONPARSERTYPES;q3
Abscos
qT
fp_cos(fp_abs(x))+fp_abs(aU
Abscosh
qT
aD2
fp_abs(x))+fp_abs(aU
Abseq0
qT
qB2
oW
0l
qL2
d61
mV2
qT
qB2
oW
0l
qL2
d61
mF2(qD;q0
b5[2]qA
userDefFuncSub<q0>((b5[0]=(fp_greaterOrEq(oW
4l))),b5[1]=(fp_greaterOrEq(oW
0l))),b5
qU
mG2(qD;q0
b6[2]qA
userDefFuncSub<q0>((b6[0]=(fp_less(oW
4l))),b6[1]=(fp_less(oW
0l))),b6
qU
Acoscos
qT
fp_cos(gD1
qU
Acoshsinh
qT
fp_sinh(fp_acosh(x
qU
mH1
qO
wV1*(q0(4l)+x+y);}
q3
Addlog
qO
hP
x)+hP
y);}
q3
o21
qO
wV1*(q0(4l)*y+aU
a21
qO-wV1+(wV1*x*y);}
q3
a31
qO-wV1*y+(wV1*aU
Addsin2cos2
g52
m91),gX)+mA2
mE),q0(2l
qU
Asinhcosh
qT
aD2
fp_asinh(x
qU
Asinsin
qT
mB2
fp_asin(x
qU
w41
qO
qB2
x
gE1
d5
Cmpeq_add_reduce
qT
qB2
wR1
qU
h71
qO
qB2
x
g53
a41
qO((qB2
x
g21
h81
qO((qB2
x
qE2
gH1
qO
qB2
x*-aS
gI1
qO
qB2
x*aS
mQ
qO
qB2
x*-gO
qU
mR
qO
qB2
x*gO
qU
Cmpeq_pow_imm_negneg
qT
qB2
d6
Cmpeq_pow_imm_negpos
qT
qB2
dS
Cmpeq_pow_imm_posneg
qT
qB2
x*aX
Cmpeq_pow_imm_pospos
qT
qB2
x*x,oO1
Cmpeq_pow_imm_pospos_base
qT
qB2
q0(dD
Cmpeq_powpow_imm_base
qO
qB2
dK
w51
qO
hY
gE1
d5
Cmpge_add_reduce
wA
wR1
qU
h91
qO
hY
g53
a71
qO((hY
g21
hA1
qO((hY
qE2
gK1
qO
hY*-aS
gL1
qO
hY*aS
mS
qO
hY*-gO
qU
mT
qO
hY*gO
qU
Cmpge_pow_imm_negneg
wA
d6
Cmpge_pow_imm_negpos
wA
dS
Cmpge_pow_imm_posneg
qT
hY*aX
Cmpge_pow_imm_pospos
qT
hY*x,oO1
Cmpge_pow_imm_pospos_base
wA
q0(dD
Cmpge_powpow_imm_base
qO
fp_greaterOrEq(dK
w61
qO
oG
gE1
d5
Cmpgt_add_reduce
qT
g11
wR1
qU
hB1
qO
oG
g53
a81
qO((oG
g21
hC1
qO((oG
qE2
gN1
qO
oG*-aS
gO1
qO
oG*aS
mU
qO
oG*-gO
qU
mV
qO
oG*gO
qU
Cmpgt_pow_imm_negneg
qT
g11
d6
Cmpgt_pow_imm_negpos
qT
g11
dS
Cmpgt_pow_imm_posneg
qT
oG*aX
Cmpgt_pow_imm_pospos
qT
oG*x,oO1
Cmpgt_pow_imm_pospos_base
qT
g11
q0(dD
Cmpgt_powpow_imm_base
qO
g11
dK
w71
qO
dU
gE1
d5
Cmple_add_reduce
qT
o11
wR1
qU
hD1
qO
dU
g53
a91
qO((dU
g21
hE1
qO((dU
qE2
gQ1
qO
dU*-aS
gR1
qO
dU*aS
mW
qO
dU*-gO
qU
mX
qO
dU*gO
qU
Cmple_pow_imm_negneg
qT
o11
d6
Cmple_pow_imm_negpos
qT
o11
dS
Cmple_pow_imm_posneg
qT
dU*aX
Cmple_pow_imm_pospos
qT
dU*x,oO1
Cmple_pow_imm_pospos_base
qT
qK1
dD
Cmple_powpow_imm_base
qO
o11
dK
w81
qO
aT
gE1
d5
Cmplt_add_reduce
qT
fp_less(wR1
qU
hF1
qO
aT
g53
aA1
qO((aT
g21
hG1
qO((aT
qE2
gT1
qO
aT*-aS
gU1
qO
aT*aS
mY
qO
aT*-gO
qU
mZ
qO
aT*gO
qU
Cmplt_pow_imm_negneg
qT
fp_less(d6
Cmplt_pow_imm_negpos
qT
fp_less(dS
Cmplt_pow_imm_posneg
qT
aT*aX
Cmplt_pow_imm_pospos
qT
aT*x,oO1
Cmplt_pow_imm_pospos_base
qT
fp_less(q0(dD
Cmplt_powpow_imm_base
qO
fp_less(dK
w91
qO
oY
gE1
d5
Cmpne_add_reduce
mK1
wR1
qU
hH1
qO
oY
g53
aB1
qO((oY
g21
hI1
qO((oY
qE2
gW1
qO
oY*-aS
gX1
qO
oY*aS
q01
qO
oY*-gO
qU
q11
qO
oY*gO
qU
Cmpne_pow_imm_negneg
mK1
d6
Cmpne_pow_imm_negpos
mK1
dS
Cmpne_pow_imm_posneg
qT
oY*aX
Cmpne_pow_imm_pospos
qT
oY*x,oO1
Cmpne_pow_imm_pospos_base
mK1
q0(dD
Cmpne_powpow_imm_base
qO
fp_nequal(dK
wA1
qE3
x
d71
gK
x
d71
mV1
d71
mW1
d71
oD2
d71
m92
x
gE1
d5
Cmpzz_add_reduce
qD2
wR1
gK
wR1
wX
gZ
wR1
wX
gG
wR1))gI
wR1
m92
wR1
qU
hJ1
qE3
x+gO
gK
x+gO
mV1+gO
mW1+gO
oD2+dP2
g53
aH1
qO
q0(0x0001l)*((aT
qF2
0x0002l)*((dU
qF2
0x0004l)*((oG
qF2
0x0008l)*((hY
qF2
0x0010l)*((oY
qF2
0x0020l)*((qB2
x
g21
hO1
qO
q0(0x0001l)*((aT
oP1
0x0002l)*((dU
oP1
0x0004l)*((oG
oP1
0x0008l)*((hY
oP1
0x0010l)*((oY
oP1
0x0020l)*((qB2
x
qE2
gZ1
wY1-q0(oZ
gK
x*-q0(oZ
mV1*-q0(oZ
mW1*-q0(oZ
oD2*-q0(oZ
m92
x*-aS
h01
wY1
q0(oZ
gK
x*q0(oZ
mV1*q0(oZ
mW1*q0(oZ
oD2*q0(oZ
m92
x*aS
q21
wY1-gO
gK
x*-gO
mV1*-gO
mW1*-gO
oD2*-dP2*-gO
qU
q31
wY1
gO
gK
x*gO
mV1*gO
mW1*gO
oD2*dP2*gO
qU
Cmpzz_pow_imm_negneg
qD2
dM
gK
dM
wX
gZ
dM
wX
gG
dM))gI
dM
m92
d6
Cmpzz_pow_imm_negpos
qD2
wR
gK
wR
wX
gZ
wR
wX
gG
wR))gI
wR
m92
dS
Cmpzz_pow_imm_posneg
qD2
x
q81
gK
x
q81
mV1
q81
mW1
q81
oD2
q81
m92
x*aX
Cmpzz_pow_imm_pospos
qD2
oW1
gK
oW1
wX
gZ
oW1
wX
gG
oW1))gI
oW1
m92
x*x,oO1
Cmpzz_pow_imm_pospos_base
qD2
q0(w0
gK
q0(w0
wX
gZ
q0(w0
wX
gG
q0(w0))gI
q0(w0
m92
q0(dD
Cmpzz_powpow_imm_base
qE3
wB
gK
wB
wX
gZ
wB
wX
gG
wB))gI
wB
m92
dK
Eq0
qT
qB2
x,q0(0l
qL2
aU
Eq1
qT
qB2
fp_not(x),q0(1l
qU
mZ2
wA
oW
0l
dO2
fp_abs(x))qR
oW
0l
gK2
d61
q03
wA
oW
1l))+qC3
fp_abs(x))qR
oW
1l
gL2
d61
hQ2
qO
x==mD1
hR2
qO
x==mD1
hS2
qO
x>mD1
oZ2
qO
x>=mD1
w02
qO
qM2
w12
qO
qM2
Gehalf
qT
hY,q0(0.5l
qU
q13
qT
g11
oW
0l
gM2
fp_abs
dR
oW
0l))gN2
d61
q23
qT
g11
oW
gO2
fp_abs
dR
oW
1l))qS
dI1,d61
hT2
qO
x
oK
qG3
hU2
qO
x>mD1
hV2
qO
x
oK
qG3
hW2
qO
x>mD1
w22
qO
x>=mD1
w32
qO
x>=mD1
w42
qO
qM2
w52
qO
x!=mD1
If10
qT
d81
dR2
10l)*fp_not(x
dR2
100l)*oG,q0(0l
wX
1000l)*dU,dT2
o51
qO
fp_abs(dW(x+gX):(y+wV1
qU
o61
qO
y+(dW
gX:h82
d91
qO
dW(y+gX):mD1
dA1
qO
dW
y:(y+q0(2l
qU
If_extract_and1_l(qZ
oY1:qL1
qU
If_extract_and1_nl(qZ
oY1:z;}
q3
If_extract_and2_l(qZ
qL1)):oY1;}
q3
If_extract_and2_nl(qZ
z:oY1;}
q3
If_extract_div
qO
y/(dW
x:q0(2l
qU
o71
qO
fp_min(y,(dW
gX:wV1
qU
o81
qO
y*(dW
gX:h82
dB1
qO
dW(y*gX):mD1
dC1
qO
dW
y:(y*q0(2l
qU
If_extract_or1_l(qZ
m31:qL1
qU
If_extract_or1_nl(qZ
m31:z;}
q3
If_extract_or2_l(qZ
qL1)):m31;}
q3
If_extract_or2_nl(qZ
z:m31;}
q3
If_extract_sin
qO
mB2
dW
y:aU
If_join_add
qO
aV(m71
aY)):(aY+dI1)+mB2
y+dI1
qU
If_join_add2
qT
x+(aV
q0(13l):q0(14l
qU
If_join_and
qO
aV
fp_and
m81
fp_and(aY+wC
If_join_max
qO
aV
fp_max
m81
fp_max(aY+wC
If_join_min
qO
aV
fp_min
m81
fp_min(aY+wC
If_join_mul
qO
aV(mB2
y)*aY)):(aY+dI1)*mB2
y+dI1
qU
If_join_mul2
qT
x*(aV
q0(30l):q0(40l
qU
If_join_or
qO
aV
fp_or
m81
fp_or(aY+wC
Ifabs
qT
q0(1l
m9
aT
q91
10l
m9
dU
q91
100l
m9
oG
q91
1000l
m9
hY
q91
10000l
m9
aT,q0(wI1
100000l
m9
dU,q0(wI1
1000000l
m9
oG,q0(wI1
10000000l
m9
hY,oF2
gB
x:-x
qU
Ifabsnot
hB
fp_truth(m91
dR2
1.2l)gB
z:mD1
Ifconst
hB
x+y+z*q0
hY2
Ififconst(gV2*vars){gV2&w=vars[0],&x
oI2,&y=vars[2],&z=vars[3]qA
aC
dW
dI1:y
gB
z:w)+aC
fp_truth(w
gB
z:oF2
gB
x:y);}
q3
Ifmerge(gV2*vars){gV2&b=vars[0],&d
oI2,&oL
x:b):aC
y
gB
x:d))+aC
b
gB
aC
d
gB
y:x):aC
d
gB
b:x
qU
Ifmerge2(qC,&b
oI2,&oL
a:b):aC
b
gB
a:b
qU
Ifmerge2b(qC,&b
oI2,&oL
a:b):aC
b
gB
b:a
qU
Ifnop
qO
x*oF2+mD1
Ifnot(qZ
z:mD1
L_abs
qO
hA2+gX,fp_and(fp_abs(x),y+gX
qU
w72
qO
hA2*y*fp_abs(y),y+q0(2l
qU
w82
qO
hA2*y*-wV1,y+q0(2l
qU
w92
qO
hA2+gX,fp_and(d81),y+gX
qU
hZ2
qO
x==mD1
d02
qO
x<mD1
wA2
qO
x<=mD1
wB2
qO
qM2
d12
qO
x
oK
qG3
d32
qO
x
oK
qG3
d42
qO
x
oK
qG3
d52
qO
x<mD1
d62
qO
x<mD1
wC2
qO
x<=mD1
wD2
qO
qM2
wE2
qO
x!=mD1
wF2
qO
x<=mD1
wG2
qO
x!=mD1
Lthalf
qT
aT,q0(0.5l
qU
Mergemulabs
hB
fp_abs(x)*fp_abs(y)*z;}
q3
Mixedminmax
hB
fp_max(z,fp_min(gS2
fp_max(z,y),x)wX
10l)*fp_min(z,fp_max
g33
y,x)wX
100l)*fp_min(fp_max(x,y),fp_min(y,z
wX
1000l)*fp_max(fp_min(x,y),fp_max(y,z
qU
Muland2
qO
a1;}
q3
Muland2plus
hB
a1*z;}
q3
Muland3
hB
a1*fp_notNot(z);}
q3
Mulandlt
qO
d81)*q0(fp_less(y,oF2
qU
Mulimmlog
qO
hP
wV1*x*y);}
q3
Mulnor2
qO
qA1;}
q3
Mulnor2plus
hB
qA1*z;}
q3
Mulnor3
hB
qA1*aN2);}
q3
Nand2
qO
aD
qU
Nand2plus
hB
fp_or(aD)),z);}
q3
Nand3
hB
fp_or(aD)),aN2
qU
Negceil
qT
fp_ceil(-aU
Negcos
qT
fp_cos(-aU
Negcosh
qT
aD2-aU
Negfloor
qT
fp_floor(-aU
Negsin
qT
mB2-aU
Negsinh
qT
fp_sinh(-aU
Neq0
qT(oY,oF2))+(fp_nequal(oF2,x
qU
Neq1
mK1
fp_not(x),q0(1l
qU
Nor2
qO
a3
qU
Nor2plus
hB
fp_and(a3)),z);}
q3
Nor3
hB
fp_and(a3)),aN2
qU
Not_eq
qO
x!=mD1
Not_ge
qO
x<mD1
Not_gt
qO
x<=mD1
Not_le
qO
x>mD1
Not_lt
qO
x>=mD1
Not_ne
qO
x==mD1
Notnot
qO
fp_truth(x)+fp_truth(y);}
q3
Posnot
g42
m91
dR2
1.2l
qU
Posnotnot
qT
fp_notNot(m91
dR2
1.2l
qU
Powimmaddimmlog
qT
qI
5l),hP
x
dR2
1l
qU
Powimmlog
qT
qI
3l),hP
x))+qI
5l),hP
x)*m91
qU
Powmulimm_fnen
qO
wV*y,(q0(-8l)qU
Powmulimm_fnep
qO
wV*y,(q0(4l)qU
Powmulimm_fnfn
qT
wV,(q0(-7.1l)qU
Powmulimm_fnfp
qO
wV*y,q0(7.1l
qU
Powmulimm_fpfp
qO
qI
5.1l)*x*y,q0(7.1l
qU
Sub1cos2
qT
dI1-mA2
mE),q0(2l
qU
Sub1sin2
qT
dI1-mA2
oX
2l
qU
Trig_modulo
qT
mE+gF)+mE+gF*gX
hV1)+mE+gF*wV1
dQ2+gF*q0(6l)dQ2+gF*q0(7l)dU2
a2+gF*gX
hV1
a2+gF*wV1
dU2*q0(6l)dU2*q0(7l)dQ2-gF)+mE-gF*gX
hV1)+mE-gF*wV1
dQ2-gF*q0(6l)dQ2-gF*q0(7l)dY2
a2-gF*gX
hV1
a2-gF*wV1
dY2*q0(6l)dY2*q0(7l)/q0(2l
qU
Trunc_from_if
qT
fp_trunc(x)*q0(4l
dR2
40l)*(x>oF2?fp_ceil(x):fp_floor(x
qU
Xaddnot
g42
x+q0(4l
qU
Xaddnotnot
qT
d81+aG2
qT3
cpp_50regressions{using
namespace
FUNCTIONPARSERTYPES;q3
t1
qT
x+gR2
0l),gQ2-2l),oF2
qU
t2
qT
fp_min
g33
dI1,x
qU
t3(qD;q0
b7[2]qA
userDefFuncSub<q0>((b7[0]=(fp_and
oK2),d81))),b7[1]=(fp_or
oK2),d81))),b7
qU
t4(qD,qZ3
b9[2]qA
userDefFuncSub<q0>((b9[0]=oK2-y)),b9[1]=(d81-y)),b9
qU
t5(qD;q0
b11[2]qA
userDefFuncSub<q0>((b11[0]=(m91)+dI1/m91)),b11[1]=(mE)),b11
qU
t6(qD;q0
b13[2]qA
userDefFuncSub<q0>((b13[0]=oK2+aG2),b13[1]=(d81+g13)),b13
qU
t7
qT
x-x;}
q3
t8
qO
qG2-x,-y
dR2
10l)*qG2-x,y
dR2
20l)*qG2
x,-y
dR2
30l)*qG2
x,y);}
q3
t9a
qT
x*q0
hY2
t9b
g5(a-b)*q0
hY2
t9c
g5(a-b)*q0
hY2
t9d
g5
a*b*q0
hY2
t36
qT-(x<oF2?x:-x)+-(x<wV1?gX:q0(3l
qU
t42
qO
h72
x*x
dR2
1.5l)*(mA2
y*y,q0(0.25l)))+fp_hypot(x,y);}
q3
t51
qT
hP-aU
t57
qT
aD2
fp_asinh(x
qU
t59
qO
aD2
x*x)+fp_tanh(y*y);}
q3
t60(qD,qZ3
b14[1];q0
b15[2]qA
fp_or(fp_or(wU1
b14[g03
b14)),userDefFuncSub<q0>((b15[g03
b15[1]=(y),b15))),userDefFuncValue<q0>((0)))qT3
cpp_99misc{using
namespace
FUNCTIONPARSERTYPES;q3
t1
qT
x*q0(4l)/gX+(dI1+(gX+g13))+x*x+x+(mF+qH3
dR2
3.0l)*q0(4.0l
dR2
5.0l)*q0(6.0l)*q0(7.0l)-q0(8.0l)*q0(9.0l
qU
t2
qT
gX*x+m91)/q0(.5l)+gX-m91)*mB2
aU
t3
hB
fp_and(m51),qB2
y,x
wX
1.0l
dR2
2.0l)-q0(3.1l)*q0(4e2l)/q0(.5l)+x*x+y*y+z*z+hA2,x)qD3
y,y);}
q3
t4
qO(((((x-y)-(((y)*gX)-g13)))*aG2
a2)*aY)-mE)*mB2
y);}
q3
t5(gV2*vars){gV2&__A5_x08=vars[0],&o__5_0AB_
oI2
qA
mA2
__A5_x08,o__5_0AB_);}
q3
t6(qD,qZ3
b18[2]qA(x>q0(1e-14l)&&y>q0(1e-14l)?x*y+t6<q0>((b18[0]=(x-dI1),b18[1]=(y-dI1),b18)):q0(0l
wX
1l);}
q3
t7
qT
mE)*mB2
dI1-x)*(dI1-mE/gX)*m91*wV1
qU
t8
qO
qG2
x,y)+(x>y?x:y);}
q3
t9
hB
q0(1.5l)+x*y-qH3
dR2
4.0l)/q0(8.0l)+z+z+z+z+x/(y*z);}
q3
t10
hB
dI1+mB2
fp_cos(fp_max(dI1+gX+g13
gE1
wV1,x+y+z)))+gX;}
q3
t11
hB(-x-x)+y+hP
qI
1.1l),z
qU
t12
qT
mF/hP
qI
10.0l),mF/hP
x)qU
t13
qO
qW
g13)*qW
aG2+mA2
y,g13
qB1
y,h82
t14
qT
x*gF+mB2
gX*gF
dR2
CONST);}
q3
t15
qO
qW
y)/hP
y)+hP
x)/hP
y)+hP
qW
y
qU
t16
qO
x<oF2?(y<oF2?x+y:x-y):(y>oF2?x*y:x+gX*y);}
q3
t17(qD,qZ3
b20[1];q0
b21[2];q0
b22[1];q0
b23[2]qA
wU1
b20[g03
b20))+userDefFuncSub<q0>((b21[g03
b21[1]=(y),b21))+wU1
b22[0]=(y),b22))+userDefFuncSub<q0>((b23[0]=(y+dI1),b23[1]=(x-gX),b23))-dI1;}
q3
t18
qO-(-(-(-wV1)))*-qW-mA2
y,-gX
qU
t19
qO
aT,y
dR2
10l)*dU,y
dR2
100l)*oG,y
dR2
1000l)*hY,y
dR2
10000l)*m51
dR2
100000l)*oY,y)+hA2,y)*gX
qD3
x,y)*q0(20l)+fp_not(x)*q0(200l)+fp_truth(x)*q0(2000l
dR2
4l)*fp_not(fp_and(aT,y),aT,g13)wX
40l)hY3
fp_not(oG,y)),oG,g13
qU
t20
qO
fp_and(fp_not<q0>(x!=y),fp_not(x))+fp_truth(y);}
q3
t21(qD;q0
b28[1]qA
wU1
b28[g03
b28))+userDefFuncValue<q0>((0))-d21
t22
qO(q0(3.5l)*gX
dR2
10l)*(x*g13)-(mB2
y)*gX
dR2
100l)*((x*gX)-(y*g13))*gX+q0(5.0l)/(gX*gX)+qI
1.1l),x*gX)+qI
1.1l)*gX,x*q0(2l
qU
t23
qT(x/(gX*fp_acos(q0(0.0l))))*q0(180l);}
q3
t24
qT(fp_min
g33
dI1,x))gP2
dI1))/gX
gP2
dI1)*g13+gR2
0l),gQ2-2l),oF2
qU
t25(qC,&b
oI2,&c=vars[2]qA
mA2
a,mA2
b,c))+mA2
a,-gX)*(-mA2
b,gX))+(-mA2
b,-c
qU
t26_deg
qT
mB2
d2r(x))+fp_cos(d2r(x*q0(1.5l)))+r2d(fp_asin(x/q0(110.0l)))+r2d(gD1/q0(120.0l)qU
t27
qO
fp_abs(x)+gD1)+fp_asin(x)+fp_atan(x)+qG2
x,y)+fp_ceil(x)+mE)+aD2
x)+mF/dM2
x)+mF/m91)+qW
y);}
q3
t28
qO
fp_exp(x)+fp_floor(x)+fp_int(x)+hP
x)+h1
x)+fp_max(x,y)gP2
y)+dI1/mE
a2)+fp_sinh(x)+h72
x)+dM2
x)+fp_tanh(x)+fp_ceil(y)+fp_trunc(y);}
q3
t29
qO
x-y*dI1;}
q3
t30
qO
x-y*dI1+fp_mod(x,y)+x/mA2
y,q0(1.1l))+qI
2l),g13)+fp_mod(wV1,g13)+qW
mA2
y,oF2))+qW
q0(0.5l
qU
t31
hB
x-(y*(y*(y*-dI1))*dI1)+hP
x*q22
y))-hP
qW
y))+q22
hP
dZ2)+qI
10.0l),hP
dZ2/hP
y+q0(6l))*hP
z+q0(6l))/hP
q0(10.0l)))-q22
hP
dZ2*y)-qI
5.0l),hP
x+dN2/hP
q0(5.0l)))+mA2
x*z+q0(17l),g13
qB1
x*z+q0(17l),gX)/mA2
x*z+q0(17l)qC2
t32
hB
x+y/y-gQ2
3l),aG2-x-gR2
4l),g13)+gR2
3l),aG2-gQ2
4l),q0(3l
wX
0l)+(z*dI1)+(x-gX+gX)+(x*gW2*gX)+y*oF2+fp_min(fp_min(gQ2
4.0l),x),mF),fp_min
g33
fp_min(y,q0(4.0l)),z)))+fp_max(fp_max(gR2
4.0l),x),mF),fp_max(gS2
fp_max(y,q0(4.0l)),z)))+(fp_abs(dI1)+fp_acos(mF)+fp_asin(mF)+fp_atan(mF)+fp_ceil(q0(1.1l))+fp_cos
q32
fp_cosh
q32
fp_floor(q0(1.1l))+hP
mF)+fp_sin
q32
fp_sinh
q32
dM2
mF)+fp_tanh(mF)+qG2
mF,mF))+(x-(y-z))+(x+y)+(x*y)+fp_max(gS2
gS2
gS2
x,x))))*-mF+(z-z)+dI1/m91/wW1
aY/wW1
dM2
z/wV1)+h1
dI1/dM2
z/wW1
mB2
y/wW1
mE/wV1))+hP
q0(30l)+x)*hP
q0(40l)+y)/hP
q0(50l)+z
a2/q0(57.295779513082320877l))+fp_asin(x/gJ3)*q0(57.295779513082320877l)+fp_floor(-x)+dI1/fp_ceil(x)+h72
wV1*q0(0.2l))+(-x+-x+-x+-x+-x+-aU
t33
qO
mB2
h72
gJ3-x*x+y*y))+fp_cos(h72
q0(15l)-x*x-y*y)a2*x+y*y);}
q3
t34(gV2*vars){gV2&t=vars[0],&rvar0
oI2,&rvar1=vars[2],&rvar2=vars[3]qA
rvar1+rvar2*rvar0-t;}
q3
t35(gV2*vars){gV2&wL=vars[0],&A_very_long_variable_name_2
oI2,&Yet_a_third_very_long_variable_name=vars[2]qA
wL-A_very_long_variable_name_2+Yet_a_third_very_long_variable_name*wL;}
q3
t37
qT
wV1+q0(7.5l)*q0(8l)hV1-qI
2l),aG2*gX+fp_mod(q0(7l),gX)gE1
x;}
q3
t38
hB
fp_asinh(x
dR2
1.5l)*fp_acosh(y+q0(3l
wX
2.5l)*fp_atanh(z);}
q3
t39
hB
m91+m41)-mE+mB2
y*q0(1.5l)))+z*z*z*mB2
z*z*z-x*x-y*y)-m41*m91+m41)+x*y*z+x*y*q0(2.5l)+x*y*z*mE)+x*y*mE)+x*z*mE)+y*z*q0(2.5l)+(x*y*z*mE)-x*y*z-y*mE)-x*z*y+x*y+x*z-mE)*aU
t40
hB
dC*dC+gX*dC-x*y*dC+x*dC;}
q3
t41
hB
x*g13+x*y+x*z+x*mB2
y*z)-(m91)+aY))*q0(4l)hB2
x
hB2
y
hB2
z;}
q3
t43
qT
hP
x*x)+fp_abs
hM2
fp_abs(x)+dI1
qU
t44
g52
x*x
w1
8l
wX
1.1l
o02
w1
7l
wX
1.2l
o02*x
w1
6l
wX
1.3l
aO2
w1
5l
wX
1.4l
aO2*x
w1
6l
wX
1.5l
aO2*x*x
w1
4l
wX
1.6l
aO2*x*x*x
w1
3l
wX
1.7l
aO2*x*x*x*x,dI1/gX
dR2
1.8l)*(h72
mA2
fp_abs(-h72
x)),g13)qU
t45
g52
x*x
w1
7l
wX
1.1l
o02*x
w1
5l
wX
1.2l
aO2*x
w1
3l
qU
t46
qO
fp_abs(fp_floor(gD1
dR2
4l)wX
1.1l)*fp_abs(fp_floor(fp_acos(y
dR2
1.5l)))o12
qW1(fp_acos(y)-gJ3
wX
1.2l)*gR2-4l),gD1
wX
1.3l)*gQ2
9l),gD1)-q0(9l
qU
t47
qO
q0(1.25l)*hM2
x)+fp_exp(-x
wX
1.5l)*hM2
y)-fp_exp(-y
wX
1.75l)*(hM2-x)+fp_exp(x))/gX
dR2
2.0l)*(hM2-x)-fp_exp(x))/gX
dR2
2.25l)*(aD2
y)+fp_sinh(y
qU
t48
qT
fp_sinh((hP
x)/wV1+dI1)*q0(5l
wX
1.2l)*aD2(hP
x)/hP
gX)+dI1)*hP
gX))+fp_not(fp_or
aC
x),fp_not(x/aG2
qU
t49
qT
qG2
oF2,x)+qI-4l)*(x-q0(100l)),q0(3.3l
qU
t50
qO
fp_or(aT,y),fp_less(y,x))+gX
mB1
aT,y),fp_less(y,x
wX
4l)mB1
dU,y),o11
y,x
wX
8l)mB1
aT,gT2
16l)hY3
aT,gT2
32l)mB1
dU,y),hY,y
wX
64l)hY3
dU,y),hY,y
wX
128l)mB1
oY,y),m51
wX
256l)mB1
oY,gT2
512l)mB1
dU,y),m51
qU
t52
qT
x+(mF+qH3
dR2
3.0l
dR2
4.0l)-q0(5.0l)-q0(6.0l)-q0(7.0l)-q0(8.0l))/q0(3.0l
dR2
4.0l)*(mF+mB2
qH3))+fp_cos(q0(4.0l)*q0(5.0l
dR2
6.0l))/qH3))+fp_cos(gW2)*dM2
q0(0.6l
dR2
0.2l))-q0(1.1l)/hP
q0(2.1l))*h72
q0(3.3l))+qI
2l),q0(3l
qU
t53
qO
hA2,y
dR2
4l)hY3
fp_int(x/gJ3),fp_int(y/gJ3
wX
8l)*((-dJ1-x)))+(dJ1-fp_not(y)))wX
16l)*(-x+fp_not(y
qU
t54
qO
aT,y)+dU,y)+oG,y)+hY,y)+m51)+oY,y)+hA2,y)qD3
x,y)+fp_not(x)+fp_truth(x)+fp_not(fp_and(aT,y),aT,g13)))qD3
fp_not(oG,y)),oG,g13
qU
t55
qO
fp_less(qW
q0(1.2l)),oF2)o12
mA2
y,q0(2.5l)),q0(0l
qM
x*x,q0(0l
wX
3l)*fp_less(mA2
y,g13),q0(0l
wX
4l)*fp_less(qW
aG2,dT2
t56
qT
fp_mod(q0(1.75e21l),aU
t58
qO
fp_less(-x,g13)+oG*-dI1,wV1)+aT*-g13,gJ3)+aT*-g13,y*dN2+aT*q0(4l),y*dN2+aT*q0(6l),y*-g13)o12-x,q0(11l))o12
wV1,-y);}
q3
t59
qT
fp_less(mE),m91))+(mE)-m91))+((fp_sinh(x)-aD2
x))-(fp_sinh(x)/aD2
x)wX
q0(1l
qU
I1
hB
dI1+gX+g13-q0(4l)*wV1*q0(6l)hV1+gJ3/gX-q0(9l)%gX+(x+y-q0(11l)*x+z/gJ3+x/(z+q0(31l)qU
I2
hB((fp_abs(x*y)<q0(20l))||(((x+y)>q0(30l))&&(z>wV1)))?fp_min(x,gX*y):fp_max(y,z*q0(2l
qU
I3
hB(x+y)+gX*(x-z
dR2
3l)*(x*y
dR2
4l)*(y/z)+wV1*fp_mod(x,z
dR2
6l)*(x<y
dR2
7l)*(x<=z
dR2
8l)*(x>gX*z
dR2
9l)*(y>=g13*z
dR2
10l)*(x+y!=z
dR2
11l)*(q0(100l)+x
dR2
12l)*(q0(101l)-y
dR2
13l)*(q0(102l)*z
dR2
14l)*(q0(103l)/x);}
}
#define Value_t double
template<>const
TestType<q0>RegressionTests<q0>::Tests[]={Uj
Wj
Yj
Sk
Tk
Uk
Wk
Yk
Sl
Tl
Ul
Wl{2,-11,11,N(0.3)qN,qG
Mod,qG
Mod
oC",z"
,g9"mod"
,"x%z"
}
,Yl
Sm
Tm
Um
Wm
Ym
Sn{1
d4
mM
Acos
qB
Acos
wY"acos"
,"acos"
aP2
dK1
Acos_deg
qB
Acos_deg
wY"acos_deg"
,"acos"
hD
1,400,mD
Acosh
qB
Acosh
wY
mR2,mR2
hD
1,400,gF1
Acosh_deg
qB
Acosh_deg
wY"acosh_deg"
,mR2
aP2
mM
Asin
qB
Asin
wY"asin"
,"a"
gA3
d4
dK1
Asin_deg
qB
Asin_deg
wY"asin_deg"
,"a"
gA3
d4
mM
Asinh
qB
Asinh
wY"a"
wL2,"a"
wL2
aP2
dK1
Asinh_deg
qB
Asinh_deg
wY"asinh_deg"
,"a"
wL2
hD
oA2
mD
Atan
qB
Atan
wY"atan"
,"atan(x)"
}
,{2,-4
o01
Atan2
qB
Atan2
aS2"/"
aA2,aA2"(x"
mI1{2,-4,4,N(0.05)g82
Atan2_deg
qB
Atan2_deg
aS2"/atan2_deg"
,aA2"(x"
mI1{1,oA2
gF1
Atan_deg
qB
Atan_deg
wY"atan_deg"
,"atan"
aP2
mM
Atanh
qB
Atanh
wY"atanh"
,"atanh"
hD-50000,50000,1000
qN
qB
Cbrt
qB
Cbrt
wY"cbrt"
,"cbrt"
hD-10,10,hF2
qB
Ceil
qB
Ceil
wY"ceil"
,"ceil"
hD-aR2
Cos
qB
Cos
wY"cos"
,"cos"
hD-aZ
g82
Cos_deg
qB
Cos_deg
wY"cos_deg"
,"cos"
hD-140,140,mD
Cosh
qB
Cosh
wY"cosh"
,"cosh"
hD-140,140,gF1
Cosh_deg
qB
Cosh_deg
wY"cosh_deg"
,"cosh"
hD-90,90,mM
Exp
qB
Exp
wY"exp"
,"exp"
hD-90,90,mM
Exp2
qB
Exp2
wY"exp2"
,"exp2"
hD-10,10,hF2
qB
Floor
qB
Floor
wY"floor"
,"floor(x)"
}
,{2,-4
o01
Hypot
qB
Hypot
aS2"/hypot"
,"hypot(x"
mI1
Tn
Un
WN1{1,N(1e-6),4000,mD
Log2
qB
Log2
wY"log2"
,"log2"
hD
N(1e-6),4000,mD
Log10
qB
Log10
wY"log10"
,"log10(x)"
}
,T4
U4{2,1,20,1
qN
qB
Pow_neg
qB
Pow_neg
aS2"/pow_neg"
,"pow(-x*0.25,y"
g31{2,N(0.01)o01
Pow_pos
qB
Pow_pos
aS2"/pow_pos"
,dB2
mI1{1,-aR2
Sin
qB
Sin,qH"/sin"
,gA3,-aZ
g82
Sin_deg
qB
Sin_deg,qH"/sin_deg"
,gA3,oA2
mD
Sinh
qB
Sinh,qH"/sinh"
,wL2
hD
oA2
gF1
Sinh_deg
qB
Sinh_deg,qH"/sinh_deg"
,wL2
hD
0,100000,1000
qN
qB
Sqrt
qB
Sqrt
wY"sqrt"
,"sqrt"
hD
N(-1.3),N(1.3),N(0.05)qN
qB
Tan
qB
Tan
wY"tan"
,"tan"
hD-89,89,N(0.25)g82
Tan_deg
qB
Tan_deg
wY"tan_deg"
,"tan"
hD-aR2
Tanh
qB
Tanh
wY"tanh"
,"tanh"
hD-aZ
g82
Tanh_deg
qB
Tanh_deg
wY"tanh_deg"
,"tanh"
hD-4000,4000,mD
Trunc
qB
Trunc
wY"trunc"
,"trunc"
hD
0,1,1
qN,hJ
E_d,hJ
E_d
a4"e_d"
aX2" naturalnumber"
d31
L2_d,hJ
L2_d
a4"l2_d"
aX2" logtwo"
d31
L10_d,hJ
L10_d
a4"l10_d"
aX2" logten"
d31
Pi_d,hJ
Pi_d
a4"pi_d"
aX2" pi"
}
,W4
YN1
SO1
TO1
UO1
WO1
YO1
Wn
Y4
Yn
So
To
S5
T5
U5
W5{qX3
N(0.1)qN
q4
Absyxpow_neg
q4
Absyxpow_neg
w11"absyxpow_neg"
,"(x^-4)^1.5"
}
,{qX3
N(0.1)qN
q4
Absyxpow_pos
q4
Absyxpow_pos
w11"absyxpow_pos"
,"(x^4)^1.5"
}
,{1
gS
Acos
q4
Acos
w11"acos"
,"acos(0.7"
h0
Acos_deg
q4
Acos_deg
w11"acos_deg"
,"acos(0.7"
m61
Acosh
q4
Acosh
w11
mR2,mR2
qN2
Acosh_deg
q4
Acosh_deg
w11"acosh_deg"
,mR2"("
dN
Uo
Wo
SP1
TP1
Yo
Sp
UP1{1
gS
Asin
q4
Asin
oZ1,"asin(0.7"
h0
Asin_deg
q4
Asin_deg
oZ1"_deg"
,"asin(0.7"
m61
Asinh
q4
Asinh
oZ1"h"
,"a"
wL2
qN2
Asinh_deg
q4
Asinh_deg
oZ1"h_deg"
,"a"
wL2"("
dN
Tp
Up{1
gS
Atan
q4
Atan
w11"atan"
,"atan"
hM1
Atan2
q4
Atan2
w11
aA2,aA2"(5,4"
h0
Atan2_deg
q4
Atan2_deg
w11"atan2_deg"
,aA2"(5,4)+x"
}
,Wp{1,0,1,1,true
q4
Atan_deg
q4
Atan_deg
w11"atan_deg"
,"atan"
hM1
Atanh
q4
Atanh
w11"atanh"
,"atanh(0.7"
m61
Cbrt
q4
Cbrt
w11"cbrt"
,"cbrt"
hM1
Ceil
q4
Ceil
w11"ceil"
,"ceil("
dN
Yp
WP1
YP1
SQ1
TQ1
UQ1
WQ1
YQ1
SR1
TR1
UR1
WR1
YR1
SS1
TS1
US1
WS1
YS1
ST1
TT1
UT1
WT1
YT1
SU1
TU1
UU1
WU1
YU1
SV1
TV1
UV1
WV1
YV1
SW1
TW1
UW1
WW1
YW1
SX1
TX1
UX1
WX1
YX1
SY1
TY1
UY1
WY1
YY1
SZ1
TZ1
UZ1
WZ1
YZ1{1
gS
Cos
q4
Cos
w11"cos"
,"cos"
qN2
Cos_deg
q4
Cos_deg
w11"cos_deg"
,"cos"
hM1
Cosh
q4
Cosh
w11"cosh"
,"cosh"
qN2
Cosh_deg
q4
Cosh_deg
w11"cosh_deg"
,"cosh("
dN
Sq
Tq
Sa1
Ta1
Ua1
Y5
Uq
Wq
Yq
S6
T6
U6
W6
Sr
Wa1
Ya1{1
gS
Exp
q4
Exp
aT2"p"
,"exp"
hM1
Exp2
q4
Exp2
aT2"p2"
,"exp2("
dN
Tr
Ur{1,hN1
Exp2xpow
q4
Exp2xpow
aT2"p2xpow"
,aJ
o22
Wr
Yr
Ss
Ts{1,hN1
Expxpow
q4
Expxpow
aT2"pxpow"
,aI
o22{1
gS
Floor
q4
Floor
w11"floor"
,"floor("
dN
Us
Sb1
Tb1
Ub1
Wb1
Yb1
Sc1
Tc1
Uc1
Wc1
Yc1
Sd1
Td1
Ud1
Wd1{1
gS
Hypot
q4
Hypot
w11"hypot"
,"hypot(5,4)+x"
}
,Yd1
Ws
Ys
St
Tt
Ut
Wt
Yt
Y6
Se1{1
gS
Log
q4
Log
w11"log"
,"log"
hM1
Log2
q4
Log2
w11"log2"
,"log2("
dN
Te1
Ue1{1
gS
Log10
q4
Log10
w11"log10"
,"log10("
dN
We1
Ye1
Sf1
Tf1
Uf1
Wf1
Yf1
S7
T7
Sg1
Tg1
Ug1
Wg1
U7
W7
Yg1{1
gS
Mulminus1
q4
Mulminus1
w11"mulminus1"
aY2"-1"
}
,Sh1
Th1{1
gS
Neg
q4
Neg
w11"neg"
,"((-((5))))+x"
}
,Y7
Uh1
Su
Wh1
Yh1
S8
Tu
Si1
T8
U8
Ti1
Ui1
W8
Wi1
Yi1
Sj1
Tj1
Uj1
Wj1
Y8
S9
T9
U9
W9
Y9
SA
TA
UA
Yj1{1
gS
Pow_neg
q4
Pow_neg,w21"_neg"
,"pow(-0.25,4"
m61
Pow_pos
q4
Pow_pos,w21"_pos"
,"pow(1.1, 7.1)+x"
}
,Uu
Wu
Yu
Sv
Tv
Uv
Wv{1,hN1
Powxpow
q4
Powxpow,0,q7"/powxpow"
,"(x^1.7)"
o22
Yv
Sw{1,N(0.01),10,N(0.05)qN
q4
Rsqrt
q4
Rsqrt
w11"rsqrt"
,"1/sqrt(x)"
}
,{1
gS
Sin
q4
Sin,aW,"sin(1.1"
h0
Sin_deg
q4
Sin_deg,aW"_deg"
,"sin("
dN
Sk1
Tk1
Uk1
Wk1
Yk1
Sl1
Tl1
Ul1
Wl1{1
gS
Sinh
q4
Sinh,aW"h"
,wL2
qN2
Sinh_deg
q4
Sinh_deg,aW"h_deg"
,wL2"("
dN
WA
YA
SB
TB
UB
WB
Yl1
Tw
Uw
Ww
Sm1{qX3
N(0.1)qN
q4
Sqrsqrt
q4
Sqrsqrt
w11"sqrsqrt"
,"sqrt"
dC2{1
gS
Sqrt
q4
Sqrt
w11"sqrt"
,"sqrt("
dN
Tm1
Um1{1,hN1
Sqrxpow
q4
Sqrxpow
w11"sqrxpow"
,"(x^2)^2402"
}
,{qX3
N(0.1)qN
q4
Sqrxpow_nonint
q4
Sqrxpow_nonint
w11"sqrxpow_nonint"
,"(x^2)^3.5"
}
,Wm1
Ym1
Sn1{1
gS
Tan
q4
Tan
w11"tan"
,"tan"
qN2
Tan_deg
q4
Tan_deg
w11"tan_deg"
,"tan"
hM1
Tanh
q4
Tanh
w11"tanh"
,"tanh"
qN2
Tanh_deg
q4
Tanh_deg
w11"tanh_deg"
,"tanh"
hM1
Trunc
q4
Trunc
w11"trunc"
,"trunc("
dN
YB
SC
Yw
Tn1
Un1
Wn1
Yn1
So1
To1
TC
Sx
UC{1,0,10,N(0.01)qN
q4
Ypowxpow
q4
Ypowxpow
w11"ypowxpow"
,"(x^38.5)^5"
}
,Uo1
Wo1
Yo1
Sp1
Tp1
Up1
Wp1
Yp1
Sq1
Tq1
Uq1
Wq1
Yq1
Sr1
Tr1
Ur1
Wr1
Yr1
Ss1
Ts1
Us1
Ws1
Ys1
St1
Tt1
Ut1
Wt1
Yt1
Su1
Tu1
Uu1
Wu1
Yu1
Sv1
Tv1
Uv1
Wv1
Yv1
Sw1
Tw1
Uw1
Ww1
Yw1
Tx
Ux
Sx1
Tx1
WC
YC
Wx
Yx
SD
Sy
TD
UD
WD
Ty
Uy
Wy
YD
SE
TE
UE
WE
YE
SF
TF
UF
Yy
Sz
Tz
Uz
Wz
Yz
WF
YF
SG
TG
UG
WG
YG
SH
TH
S_
T_
U_
W_
Y_
S01
UH
WH
YH
SI
TI
UI
WI
YI
SJ
T01
U01
W01
Y01
S11
T11
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
U11
W11
Y11
S21
T21
U21
SL
TL
UL
WL
YL
SM
TM
UM
WM
W21
Y21
S31
T31
U31
W31
YM
SN
TN
UN
WN
YN
SO
TO
UO
Y31
S41
T41
U41
W41
Y41
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
S51
T51
U51
W51
Y51
S61
Ux1
Wx1
Yx1
Sy1
UQ
WQ
YQ
SR
TR
UR
Ty1
Uy1
Wy1
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
TV
UV
WV
YV
SW
TW
UW
WW
T61
U61
YW
W61
Y61
S71
T71
SX
U71
TX
W71
Y71
S81
UX
WX
YX
SY
T81
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Yy1
Yb
Sc
U81
W81
Y81
S91
T91
U91
W91
Y91
Tc
Uc
Wc
SA1
TA1
UA1
WA1
YA1
SB1
Sz1
Tz1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
TB1
UB1
WB1
YB1
SC1
TC1
UC1
WC1
YC1
SD1
TD1
UD1
WD1
Ye
Sf
Tf
Uf
Wf
Yf
YD1
Sg
Uz1
Wz1
Yz1
S_1
T_1
U_1
Tg
SE1
TE1
UE1
WE1
Ug
YE1
SF1
TF1
UF1
WF1
#if !defined(FP_DISABLE_EVAL)
YF1
#endif /*!defined(FP_DISABLE_EVAL) */
SG1
TG1
UG1
WG1
YG1
SH1
TH1
UH1
WH1
Wg
Yg
YH1
Sh
Th
Uh
SI1
TI1
Wh
UI1
WI1
YI1
SJ1
Yh
TJ1
UJ1
WJ1
YJ1
Si
Ti
SK1
TK1
UK1
WK1
YK1
SL1
TL1
UL1
WL1
YL1
SM1
TM1
Ui
UM1
WM1
YM1
SN1
TN1
Wi
UN1
TestType<q0>()}
;
#undef Value_t
#undef N
#undef P
#ifdef FP_SUPPORT_COMPLEX_DOUBLE_TYPE
#define N(x,y) (q0(x,y))
#define Value_t std::complex<double>
namespace
cpp_02unit_functions{qM3
Cos_cd
qT
cos
hZ1
Sin_cd
qT
sin(x);}
}
template<>const
TestType<q0>RegressionTests<q0>::Tests[]={W_1
Y_1
S02
T02
U02
W02
Y02
S12
T12
U12
W12
Y12
S22
T22
U22
W22
Y22
S32
T32
U32
W32
Y32
S42
T42
U42
W42
Y42
S52{1,N(-hV3,+200.0),N(hV3,-200.0),N(5.0,-0.025)qN
qB
Cos_cd
hD2"cos_cd"
,"cos(x)"
}
,T52
U52
W52
Y52
S62
T62
U62{1,N(-hV3,+200.0),N(hV3,-200.0),N(5.0,-0.025)qN
qB
Sin_cd,hE2"_cd"
,qA2}
,W62
Y62
S72
T72
U72
W72
Y72
S82
T82
U82
W82
Y82
S92
T92
U92
W92
Y92
SA2
TA2
UA2
WA2
YA2
SB2
TB2
UB2
WB2
YB2
SC2
TC2
UC2
WC2
YC2
SD2
TD2
UD2
WD2
YD2
SE2
TE2
UE2
WE2
YE2
SF2
TF2
UF2
WF2
YF2
SG2
TG2
UG2
WG2
YG2
SH2
TH2
UH2
WH2
YH2
SI2
TI2
UI2
WI2
YI2
SJ2
TJ2
UJ2
WJ2
YJ2
SK2
TK2
UK2
WK2
YK2
SL2
TL2
UL2
WL2
YL2
SM2
TM2
UM2
WM2
YM2
SN2
TN2
UN2
WN2
YN2
SO2
TO2
UO2
WO2
YO2
SP2
TP2
UP2
WP2
YP2
SQ2
TQ2
UQ2
WQ2
YQ2
SR2
TR2
UR2
WR2
YR2
SS2
TS2
US2
WS2
YS2
ST2
TT2
UT2
WT2
YT2
SU2
TU2
UU2
WU2
YU2
SV2
TV2
UV2
WV2
YV2
SW2
TW2
UW2
WW2
YW2
SX2
TX2
UX2
WX2
YX2
SY2
TY2
UY2
WY2
YY2
SZ2
TZ2
UZ2
WZ2
YZ2
Sa2
Ta2
Ua2
Wa2
Ya2
Sb2
Tb2
Ub2
Wb2
Yb2
Sc2
Tc2
Uc2
Wc2
Yc2
Sd2
Td2
Ud2
Wd2
Yd2
Se2
Te2
Ue2
We2
Ye2
Sf2
Tf2
Uf2
Wf2
Yf2
Sg2
Tg2
Ug2
Wg2
Yg2
Sh2
Th2
Uh2
Wh2
Yh2
Si2
Ti2
Ui2
Wi2
Yi2
Sj2
Tj2
Uj2
Wj2
Yj2
Sk2
Tk2
Uk2
Wk2
Yk2
Sl2
Tl2
Ul2
Wl2
Yl2
Sm2
Tm2
Um2
Wm2
Ym2
Sn2
Tn2
Un2
Wn2
Yn2
So2
To2
Uo2
Wo2
Yo2
Sp2
Tp2
Up2
Wp2
Yp2
Sq2
Tq2
Uq2
Wq2
Yq2
Sr2
Tr2
Ur2
Wr2
Yr2
Ss2
Ts2
Us2
Ws2
Ys2
St2
Tt2
Ut2
Wt2
Yt2
Su2
Tu2
Uu2
Wu2
Yu2
Sv2
Tv2
Uv2
Wv2
Yv2
Sw2
Tw2
Uw2
Ww2
Yw2
Sx2
Tx2
Ux2
Wx2
Yx2
Sy2
Ty2
Uy2
Wy2
Yy2
Sz2
Tz2
Uz2
Wz2
Yz2
S_2
T_2
U_2
W_2
Y_2
S03
T03
U03
W03
TestType<q0>()}
;
#undef Value_t
#undef N
#endif /*FP_SUPPORT_COMPLEX_DOUBLE_TYPE */
#ifdef FP_SUPPORT_COMPLEX_FLOAT_TYPE
#define N(x,y) (q0(APP(x,f),APP(y,f)))
#define Value_t std::complex<float>
namespace
cpp_02unit_functions{qM3
Cos_cf
qT
cos
hZ1
Sin_cf
qT
sin(x);}
}
template<>const
TestType<q0>RegressionTests<q0>::Tests[]={W_1
Y_1
S02
T02
U02
W02
Y02
S12
T12
U12
W12
Y12
S22
T22
U22
W22
Y22
S32
T32
U32
W32
Y32
S42
T42
U42
W42
Y42
S52{1,N(-40.0,+0.5),N(40.0,-0.5),N(0.1,-0.00125)qN
qB
Cos_cf
hD2"cos_cf"
,"cos(x)"
}
,T52
W52
Y52
S62
T62
U62{1,N(-40.0,+0.5),N(40.0,-0.5),N(0.1,-0.00125)qN
qB
Sin_cf,hE2"_cf"
,qA2}
,W62
UF2
WF2
WG2
YG2
SH2
TH2
UH2
WH2
YH2
SI2
TI2
UI2
WI2
YI2
SJ2
TJ2
UJ2
WJ2
YJ2
SK2
TK2
UK2
WK2
YK2
SL2
TL2
UL2
WL2
YL2
SM2
TM2
UM2
WM2
YM2
SN2
TN2
UN2
WN2
YN2
SO2
TO2
UO2
WO2
YO2
SP2
TP2
UP2
WP2
YP2
SQ2
TQ2
UQ2
WQ2
YQ2
SR2
TR2
UR2
WR2
YR2
SS2
TS2
US2
WS2
YS2
ST2
TT2
UT2
WT2
YT2
SU2
TU2
UU2
WU2
YU2
SV2
TV2
UV2
WV2
YV2
SW2
TW2
UW2
WW2
YW2
SX2
TX2
UX2
WX2
YX2
SY2
TY2
UY2
WY2
YY2
SZ2
TZ2
UZ2
WZ2
YZ2
Sa2
Ta2
Ua2
Wa2
Ya2
Sb2
Tb2
Ub2
Wb2
Yb2
Sc2
Tc2
Uc2
Wc2
Yc2
Sd2
Td2
Ud2
Wd2
Yd2
Se2
Te2
Ue2
We2
Ye2
Sf2
Tf2
Uf2
Wf2
Yf2
Sg2
Tg2
Ug2
Wg2
Yg2
Sh2
Th2
Uh2
Wh2
Yh2
Si2
Ti2
Ui2
Wi2
Yi2
Sj2
Tj2
Uj2
Wj2
Yj2
Sk2
Tk2
Uk2
Wk2
Yk2
Sl2
Tl2
Ul2
Wl2
Yl2
Sm2
Tm2
Um2
Wm2
Ym2
Sn2
Tn2
Un2
Wn2
Yn2
So2
To2
Uo2
Wo2
Yo2
Sp2
Tp2
Up2
Wp2
Yp2
Sq2
Tq2
Uq2
Wq2
Yq2
Sr2
Tr2
Ur2
Wr2
Yr2
Ss2
Ts2
Us2
Ws2
Ys2
St2
Tt2
Ut2
Wt2
Yt2
Su2
Tu2
Uu2
Wu2
Yu2
Sv2
Tv2
Uv2
Wv2
Yv2
Sw2
Tw2
Uw2
Ww2
Yw2
Sx2
Tx2
Ux2
Wx2
Yx2
Sy2
Ty2
Uy2
Wy2
Yy2
Sz2
Tz2
Uz2
Wz2
Yz2
S_2
T_2
U_2
W_2
Y_2
S03
T03
U03
W03
TestType<q0>()}
;
#undef Value_t
#undef N
#endif /*FP_SUPPORT_COMPLEX_FLOAT_TYPE */
#ifdef FP_SUPPORT_COMPLEX_LONG_DOUBLE_TYPE
#define N(x,y) (q0(APP(x,l),APP(y,l)))
#define Value_t std::complex<long double>
template<>const
TestType<q0>RegressionTests<q0>::Tests[]={Y_1
T02
U02
Y02
S12
T12
U12
W12
S22
T22
U22
W22
S32
U32
W32
Y32
S42
U42
Y42
S52
T52
Y52
S62
T62
U62
UF2
WF2
WG2
YG2
SH2
TH2
UH2
WH2
YH2
SI2
TI2
UI2
WI2
YI2
SJ2
TJ2
UJ2
WJ2
YJ2
SK2
TK2
UK2
WK2
YK2
SL2
TL2
UL2
WL2
YL2
SM2
TM2
UM2
WM2
YM2
SN2
TN2
UN2
WN2
YN2
SO2
TO2
UO2
WO2
YO2
SP2
TP2
UP2
WP2
YP2
SQ2
TQ2
UQ2
WQ2
YQ2
SR2
TR2
UR2
WR2
YR2
SS2
TS2
US2
WS2
YS2
ST2
TT2
UT2
WT2
YT2
SU2
TU2
UU2
WU2
YU2
SV2
TV2
UV2
WV2
YV2
SW2
TW2
UW2
WW2
YW2
SX2
TX2
UX2
WX2
YX2
SY2
TY2
UY2
WY2
YY2
SZ2
TZ2
UZ2
WZ2
YZ2
Sa2
Ta2
Ua2
Wa2
Ya2
Sb2
Tb2
Ub2
Wb2
Yb2
Sc2
Tc2
Uc2
Wc2
Yc2
Sd2
Td2
Ud2
Wd2
Yd2
Se2
Te2
Ue2
We2
Ye2
Sf2
Tf2
Uf2
Yf2
Sg2
Tg2
Ug2
Wg2
Yg2
Sh2
Th2
Uh2
Wh2
Yh2
Si2
Ti2
Ui2
Wi2
Yi2
Sj2
Tj2
Uj2
Wj2
Yj2
Sk2
Tk2
Uk2
Wk2
Yk2
Sl2
Tl2
Ul2
Wl2
Yl2
Sm2
Tm2
Um2
Wm2
Ym2
Sn2
Tn2
Un2
Wn2
Yn2
So2
To2
Uo2
Wo2
Yo2
Sp2
Tp2
Up2
Wp2
Yp2
Sq2
Tq2
Uq2
Wq2
Yq2
Sr2
Tr2
Ur2
Wr2
Yr2
Ss2
Ts2
Ws2
Ys2
St2
Tt2
Ut2
Wt2
Yt2
Su2
Tu2
Uu2
Wu2
Yu2
Sv2
Tv2
Uv2
Wv2
Yv2
Sw2
Tw2
Uw2
Ww2
Yw2
Sx2
Tx2
Ux2
Wx2
Yx2
Sy2
Ty2
Uy2
Wy2
Yy2
Sz2
Tz2
Uz2
Wz2
Yz2
S_2
T_2
U_2
W_2
Y_2
S03
T03
U03
W03
TestType<q0>()}
;
#undef Value_t
#undef N
#endif /*FP_SUPPORT_COMPLEX_LONG_DOUBLE_TYPE */
#ifdef FP_SUPPORT_FLOAT_TYPE
#define N(x) (APP(x,f))
#define P(x) N(x##.0)
#define Value_t float
namespace
cpp_01unit_operators{qM3
Modf(qD,&z
oI2
qA
fmodf(x,z)qT3
cpp_02unit_functions{qM3
Acosf
qT
acosf
hZ1
g23
dY1
acosf(x
qS3
Acoshf
hY1
x+o32-1.0f
qS3
qU3
dY1
fp_acosh(x
qS3
Asinf
qT
asinf
hZ1
g43
dY1
asinf(x
qS3
Asinhf
hY1
x+o32+1.0f
qS3
qV3
dY1
fp_asinh(x
qS3
Atan2f
qO
o42
x,y);}
q0
Atan2f_deg
qO
r2d(o42
x,y
qS3
Atanf
qT
atanf
hZ1
Atanf_deg
dY1
atanf(x
qS3
Atanhf
hY1(1.0f+x)/(1.0f-x))*0.5f;}
q0
Cbrtf
qT
fp_cbrt
hZ1
Ceilf
qT
ceilf
hZ1
Cosf
qT
cosf
hZ1
Cosf_deg
qT
cosf(g51
Coshf
qT
coshf
hZ1
Coshf_deg
qT
coshf(g51
Exp2f
qI3(x*fp_const_log2<q0>(qS3
Expf
qI3
hZ1
Floorf
qT
floorf
hZ1
Hypotf
qO
o32+y*y);}
q0
Log2f
hY1
x)*1.4426950408889634073599246810018921374266f;}
q0
Log10f
qT
log10f
hZ1
Logf
hY1
x);}
q0
Pow_negf
qO
powf(-x*0.25f,y);}
q0
Pow_posf
qO
powf(x,y);}
q0
Sinf
qT
sinf
hZ1
Sinf_deg
qT
sinf(g51
Sinhf
qT
sinhf
hZ1
Sinhf_deg
qT
sinhf(g51
Sqrtf
qT
sqrtf
hZ1
Tanf
qT
tanf
hZ1
Tanf_deg
qT
tanf(g51
Tanhf
qT
tanhf
hZ1
Tanhf_deg
qT
tanhf(g51
Truncf
qT
fp_trunc(x)qT3
cpp_03unit_constants{qM3
E_f
qI3(x*0.0f+1.0f);}
q0
L2_f
hY1
x*0.0f+2.0f);}
q0
L10_f
hY1
x*0.0f+10.0f);}
q0
Pi_f
qT
o42
x*0.0f,-1.0f)qT3
cpp_10optimizer_bytecode{qM3
Acosf
qT
acosf(0.7f
hW
g23
dY1
acosf(0.7f)hW
Acoshf
hC2+sqrtf(1.1f*1.1f-1.0f)hW
qU3
dY1
fp_acosh(1.1f)hW
Asinf
qT
asinf(0.7f
hW
g43
dY1
asinf(0.7f)hW
Asinhf
hC2+sqrtf(1.1f*1.1f+1.0f)hW
qV3
dY1
fp_asinh(1.1f)hW
Atan2f
qT
o42
5.0f,qJ3
Atan2f_deg
dY1
o42
5.0f,4.0f)hW
Atanf
qT
atanf
wT1
Atanf_deg
dY1
atanf(1.1f)hW
Atanhf
hY1(1.0f+0.7f)/(1.0f-0.7f))*0.5f+x;}
q0
Cbrtf
qT
fp_cbrt
wT1
Ceilf
qT
ceilf
wT1
Cosf
qT
cosf
wT1
Cosf_deg
qT
cosf(g61
Coshf
qT
coshf
wT1
Coshf_deg
qT
coshf(g61
Exp2f
qI3(1.1f*0.693147180559945309417232121458176568075500134f
hW
Expf
qI3
wT1
Floorf
qT
floorf
wT1
Hypotf
qT
sqrtf(5.0f*5.0f+4.0f*qJ3
Log2f
hC2)*1.4426950408889634073599246810018921374266f+x;}
q0
Log10f
qT
log10f
wT1
Logf
hC2
hW
Pow_negf
qT
powf(-0.25f,qJ3
Pow_posf
qT
powf(1.1f,7.1f
hW
Sinf
qT
sinf
wT1
Sinf_deg
qT
sinf(g61
Sinhf
qT
sinhf
wT1
Sinhf_deg
qT
sinhf(g61
Sqrtf
qT
sqrtf
wT1
Tanf
qT
tanf
wT1
Tanf_deg
qT
tanf(g61
Tanhf
qT
tanhf
wT1
Tanhf_deg
qT
tanhf(g61
Truncf
qT
1.0f+x;}
}
template<>const
TestType<q0>RegressionTests<q0>::Tests[]={Uj
Wj
Yj
Sk
Tk
Uk
Wk
Yk
Sl
Tl
Ul
Wl{2,-11,11,N(0.3)qN,qG
Modf,0
oC",z"
,g9"modf"
,"x%z"
}
,Yl
Sm
Tm
Um
Wm
Ym
Sn{1
d4
mM
Acosf
hD2"acosf"
,"acos"
aP2
dK1
g23
hD2"acosf_deg"
,"acos"
hD
1,400,mD
Acoshf
hD2"acoshf"
,mR2
hD
1,400,gF1
qU3
hD2"acoshf_deg"
,mR2
aP2
mM
Asinf
hD2"asinf"
,"a"
gA3
d4
dK1
g43
hD2"asinf_deg"
,"a"
gA3
d4
mM
Asinhf
hD2"asinhf"
,"a"
wL2
aP2
dK1
qV3
hD2"asinhf_deg"
,"a"
wL2"(x)"
}
,{2,-4
o01
Atan2f,wM"/atan2f"
,aA2"(x"
mI1{2,-4,4,N(0.05)g82
Atan2f_deg,wM"/atan2f_deg"
,aA2"(x"
mI1{1,oA2
mD
Atanf
hD2"atanf"
,"atan"
hD
oA2
gF1
Atanf_deg
hD2"atanf_deg"
,"atan"
aP2
mM
Atanhf
hD2"atanhf"
,"atanh"
hD-50000,50000,1000
qN
qB
Cbrtf
hD2"cbrtf"
,"cbrt"
hD-10,10,hF2
qB
Ceilf
hD2"ceilf"
,"ceil"
hD-aR2
Cosf
hD2"cosf"
,"cos"
hD
oA2
5
g82
Cosf_deg
hD2"cosf_deg"
,"cos"
hD
hZ3
N(0.025)qN
qB
Coshf
hD2"coshf"
,"cosh"
hD
hZ3
gF1
Coshf_deg
hD2"coshf_deg"
,"cosh"
hD-90,90,mM
Exp2f
hD2"exp2f"
,"exp2"
hD-20,20,mM
Expf
hD2"expf"
,"exp"
hD-10,10,hF2
qB
Floorf
hD2"floorf"
,"floor(x)"
}
,{2,-4
o01
Hypotf,wM"/hypotf"
,"hypot(x"
mI1
Tn
Un{1,m0
Log2f
hD2"log2f"
,"log2"
hD
m0
Log10f
hD2"log10f"
,"log10"
hD
m0
Logf
hD2"logf"
,gE2
T4
U4{2,1,20,1
qN
qB
Pow_negf,wM"/pow_negf"
,"pow(-x*0.25,y"
g31{2,N(0.01)o01
Pow_posf,wM"/pow_posf"
,dB2
mI1{1,-aR2
Sinf,hE2"f"
,gA3,oA2
5
g82
Sinf_deg,hE2"f_deg"
,gA3,hZ3
mD
Sinhf,hE2"hf"
,wL2
hD
oA2
gF1
Sinhf_deg,hE2"hf_deg"
,wL2
hD
0,100000,1000
qN
qB
Sqrtf
hD2"sqrtf"
,"sqrt"
hD
N(-1.3),N(1.3),N(0.05)qN
qB
Tanf
hD2"tanf"
,"tan"
hD-89,89,N(0.25)g82
Tanf_deg
hD2"tanf_deg"
,"tan"
hD-aR2
Tanhf
hD2"tanhf"
,"tanh"
hD-aZ
g82
Tanhf_deg
hD2"tanhf_deg"
,"tanh"
hD
oA2
mD
Truncf
hD2"truncf"
,"trunc"
hD
0,1,1
qN,hJ
E_f,oB"e_f"
aX2" naturalnumber"
d31
L2_f,oB"l2_f"
aX2" logtwo"
d31
L10_f,oB"l10_f"
aX2" logten"
d31
Pi_f,oB"pi_f"
aX2" pi"
}
,W4
YN1
SO1
UO1
WO1
Wn
Y4
Yn
So
To
S5
W5{1
gS
Acosf,oD"acosf"
,"acos(0.7"
h0
g23,oD"acosf_deg"
,"acos(0.7)+x"
}
,Uo{1
gS
Acoshf,oD"acoshf"
,mR2
qN2
qU3,oD"acoshf_deg"
,mR2"("
dN
Wo
Yo
Sp{1
gS
Asinf,oD"asinf"
,"asin(0.7"
h0
g43,oD"asinf_deg"
,"asin(0.7)+x"
}
,Tp{1
gS
Asinhf,oD"asinhf"
,"a"
wL2
qN2
qV3,oD"asinhf_deg"
,"a"
wL2"("
dN
Up{1
gS
Atan2f,oD"atan2f"
,aA2"(5,4"
h0
Atan2f_deg,oD"atan2f_deg"
,aA2"(5,4)+x"
}
,Wp{1
gS
Atanf,oD"atanf"
,"atan"
qN2
Atanf_deg,oD"atanf_deg"
,"atan"
hM1
Atanhf,oD"atanhf"
,"atanh(0.7"
m61
Cbrtf,oD"cbrtf"
,"cbrt"
hM1
Ceilf,oD"ceilf"
,"ceil("
dN
Yp
WP1
YP1
SQ1
TQ1
UQ1
WQ1
YQ1
SR1
TR1
UR1
WR1
YR1
SS1
TS1
US1
WS1
YS1
ST1
TT1
UT1
WT1
YT1
SU1
TU1
UU1
WU1
YU1
SV1
TV1
UV1
WV1
YV1
SW1
TW1
UW1
WW1
YW1
SX1
TX1
UX1
WX1
YX1
SY1
TY1
UY1
WY1{1
gS
Cosf,oD"cosf"
,"cos"
qN2
Cosf_deg,oD"cosf_deg"
,"cos"
hM1
Coshf,oD"coshf"
,"cosh"
qN2
Coshf_deg,oD"coshf_deg"
,"cosh("
dN
Sq
Tq
Y5
Uq
Wq
Yq
S6
T6
U6
W6
Sr
Wa1
Ya1
Tr{1
gS
Exp2f,oD"exp2f"
,"exp2("
dN
Ur
Wr{1
gS
Expf,oD"expf"
,m12
dN
Yr
Ss
Ts{1
gS
Floorf,oD"floorf"
,"floor("
dN
Us
Sb1
Tb1
Ub1
Wb1
Yb1
Sc1
Tc1
Uc1
Wc1
Yc1
Sd1
Td1
Ud1
Wd1{1
gS
Hypotf,oD"hypotf"
,"hypot(5,4)+x"
}
,Ws
Ys
St
Tt
Ut
Wt
Yt
Y6
Se1
Te1
Ue1{1
gS
Log2f,oD"log2f"
,"log2"
hM1
Log10f,oD"log10f"
,"log10("
dN
We1
Ye1{1
gS
Logf,oD"logf"
,"log("
dN
Sf1
Tf1
Uf1
Wf1
Yf1
S7
T7
Wg1
U7
W7
Yg1
Y7
Su
Wh1
Yh1
S8
Tu
T8
U8
Ti1
Ui1
W8
Yi1
Sj1
Tj1
Uj1
Y8
S9
T9
U9
W9
Y9
SA
TA
UA{1
gS
Pow_negf,0,w21"_negf"
,"pow(-0.25,4"
m61
Pow_posf,0,w21"_posf"
,"pow(1.1, 7.1)+x"
}
,Uu
Wu
Yu
Sv
Tv
Uv
Wv
Yv
Sw
Sk1
Tk1
Uk1
Wk1
Yk1
Sl1
Tl1
Ul1
Wl1{1
gS
Sinf,0,aW"f"
,"sin(1.1"
h0
Sinf_deg,0,aW"f_deg"
,"sin("
dN{1
gS
Sinhf,0,aW"hf"
,wL2
qN2
Sinhf_deg,0,aW"hf_deg"
,wL2"("
dN
WA
YA
SB
TB
UB
WB
Tw
Uw
Ww{1
gS
Sqrtf,oD"sqrtf"
,"sqrt("
dN
Tm1
Um1
Sn1{1
gS
Tanf,oD"tanf"
,"tan"
qN2
Tanf_deg,oD"tanf_deg"
,"tan"
hM1
Tanhf,oD"tanhf"
,"tanh"
qN2
Tanhf_deg,oD"tanhf_deg"
,"tanh"
hM1
Truncf,oD"truncf"
,"trunc("
dN
YB
SC
Yw
Tn1
Un1
Wn1
Yn1
So1
To1
TC
Sx
UC
Tx
Ux
Wx
Yx
SD
Sy
TD
UD
WD
Ty
Uy
Wy
YD
SE
TE
UE
WE
YE
SF
TF
UF
Yy
Sz
Tz
Uz
Wz
Yz
WF
YF
SG
TG
UG
WG
YG
SH
TH
S_
T_
U_
W_
Y_
S01
UH
WH
YH
SI
TI
UI
WI
YI
SJ
T01
U01
W01
Y01
S11
T11
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
U11
W11
Y11
S21
T21
U21
SL
TL
UL
WL
YL
SM
TM
UM
WM
W21
Y21
S31
T31
U31
W31
YM
SN
TN
UN
WN
YN
SO
TO
UO
Y31
S41
T41
U41
W41
Y41
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
S51
T51
U51
W51
Y51
S61
Ux1
Wx1
Yx1
Sy1
UQ
WQ
YQ
SR
TR
UR
Ty1
Uy1
Wy1
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
TV
UV
WV
YV
SW
TW
UW
WW
T61
U61
YW
W61
Y61
S71
T71
SX
U71
TX
W71
Y71
S81
UX
WX
YX
SY
T81
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Yy1
Yb
Sc
U81
W81
Y81
S91
T91
U91
W91
Y91
Tc
Uc
Wc
SA1
TA1
UA1
WA1
YA1
SB1
Sz1
Tz1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
TB1
UB1
WB1
YB1
SC1
TC1
UC1
WC1
YC1
SD1
TD1
UD1
WD1
Ye
Sf
Tf
Uf
Wf
Yf
YD1
Wz1
Tg
SE1
TE1
UE1
WE1
Ug
YE1
SF1
TF1
UF1
WF1
#if !defined(FP_DISABLE_EVAL)
YF1
#endif /*!defined(FP_DISABLE_EVAL) */
SG1
TG1
UG1
WG1
YG1
SH1
TH1
UH1
WH1
Wg
Yg
YH1
Sh
Th
Uh
TI1
Wh
UI1
WI1
YI1
SJ1
Yh
TJ1
WJ1
Si
Ti
SK1
TL1
UL1
WL1
YL1
SM1
TM1
Ui
UM1
WM1
YM1
SN1
TN1
Wi
UN1
TestType<q0>()}
;
#undef Value_t
#undef N
#undef P
#endif /*FP_SUPPORT_FLOAT_TYPE */
#ifdef FP_SUPPORT_GMP_INT_TYPE
#define P(x) (APP(x,l))
#define Value_t GmpInt
template<>const
TestType<q0>RegressionTests<q0>::Tests[]={S
T
U
W
Y
S1
T1
U1
W1
Y1
S2
T2
U2
W2
Y2
S3
T3
U3
W3
Y3
S4
T4
U4
W4
Y4
S5
T5
U5
W5
Y5
S6
T6
U6
W6
Y6
S7
T7
U7
W7
Y7
S8
T8
U8
W8
Y8
S9
T9
U9
W9
Y9
SA
TA
UA
WA
YA
SB
TB
UB
WB
YB
SC
TC
UC
WC
YC
SD
TD
UD
WD
YD
SE
TE
UE
WE
YE
SF
TF
UF
WF
YF
SG
TG
UG
WG
YG
SH
TH
UH
WH
YH
SI
TI
UI
WI
YI
SJ
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
SL
TL
UL
WL
YL
SM
TM
UM
WM
YM
SN
TN
UN
WN
YN
SO
TO
UO
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
UQ
WQ
YQ
SR
TR
UR
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
SV
TV
UV
WV
YV
SW
TW
UW
WW
YW
SX
TX
UX
WX
YX
SY
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Yb
Sc
Tc
Uc
Wc
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
Ye
Sf
Tf
Uf
Wf
Yf
Sg
Tg
Ug
Wg
Yg
Sh
Th
Uh
Wh
Yh
Si
Ti
Ui
Wi
Yi
Sj
Tj
TestType<q0>()}
;
#undef Value_t
#undef P
#endif /*FP_SUPPORT_GMP_INT_TYPE */
#ifdef FP_SUPPORT_LONG_DOUBLE_TYPE
#define N(x) (APP(x,l))
#define P(x) N(x##.0)
#define Value_t long double
namespace
cpp_01unit_operators{qM3
Modl(qD,&z
oI2
qA
fmodl(x,z)qT3
cpp_02unit_functions{qM3
Acoshl
m1
x+o52-1.0l
qS3
Acoshl_deg
dY1
fp_acosh(x
qS3
Acosl
qT
acosl
hZ1
Acosl_deg
dY1
acosl(x
qS3
Asinhl
m1
x+o52+1.0l
qS3
Asinhl_deg
dY1
fp_asinh(x
qS3
Asinl
qT
asinl
hZ1
Asinl_deg
dY1
asinl(x
qS3
Atan2l
qO
o62
x,y);}
q0
Atan2l_deg
qO
r2d(o62
x,y
qS3
Atanhl
m1(1.0l+x)/(1.0l-x))*0.5l;}
q0
Atanl
qT
atanl
hZ1
Atanl_deg
dY1
atanl(x
qS3
Cbrtl
qT
fp_cbrt
hZ1
Ceill
qT
ceill
hZ1
Coshl
qT
coshl
hZ1
Coshl_deg
qT
coshl(g51
Cosl
qT
cosl
hZ1
Cosl_deg
qT
cosl(g51
Exp2l
qT
expl(x*fp_const_log2<q0>(qS3
Expl
qT
expl
hZ1
Floorl
qT
floorl
hZ1
Hypotl
qO
o52+y*y);}
q0
Log2l
m1
x)*1.4426950408889634073599246810018921374266l;}
q0
Log10l
qT
log10l
hZ1
Logl
m1
x);}
q0
Pow_negl
qO
powl(-x*0.25l,y);}
q0
Pow_posl
qO
powl(x,y);}
q0
Sinhl
qT
sinhl
hZ1
Sinhl_deg
qT
sinhl(g51
Sinl
qT
sinl
hZ1
Sinl_deg
qT
sinl(g51
Sqrtl
qT
sqrtl
hZ1
Tanhl
qT
tanhl
hZ1
Tanhl_deg
qT
tanhl(g51
Tanl
qT
tanl
hZ1
Tanl_deg
qT
tanl(g51
Truncl
qT
fp_trunc(x)qT3
cpp_03unit_constants{qM3
E_ld
qT
expl(x*0.0l+1.0l);}
q0
L2_ld
m1
x*0.0l+2.0l);}
q0
L10_ld
m1
x*0.0l+10.0l);}
q0
Pi_ld
qT
o62
x*0.0l,-1.0l)qT3
cpp_10optimizer_bytecode{qM3
Acoshl
m1
1.1l+sqrtl(1.1l*1.1l-1.0l)hW
Acoshl_deg
dY1
fp_acosh(1.1l)hW
Acosl
qT
acosl(0.7l
hW
Acosl_deg
dY1
acosl(0.7l)hW
Asinhl
m1
1.1l+sqrtl(1.1l*1.1l+1.0l)hW
Asinhl_deg
dY1
fp_asinh(1.1l)hW
Asinl
qT
asinl(0.7l
hW
Asinl_deg
dY1
asinl(0.7l)hW
Atan2l
qT
o62
5.0l,qK3
Atan2l_deg
dY1
o62
5.0l,4.0l)hW
Atanhl
m1(1.0l+0.7l)/(1.0l-0.7l))*0.5l+x;}
q0
Atanl
qT
atanl
dZ1
Atanl_deg
dY1
atanl(1.1l)hW
Cbrtl
qT
fp_cbrt
dZ1
Ceill
qT
ceill
dZ1
Coshl
qT
coshl
dZ1
Coshl_deg
qT
coshl(g71
Cosl
qT
cosl
dZ1
Cosl_deg
qT
cosl(g71
Exp2l
qT
expl(1.1l*0.693147180559945309417232121458176568075500134l
hW
Expl
qT
expl
dZ1
Floorl
qT
floorl
dZ1
Hypotl
qT
sqrtl(5.0l*5.0l+4.0l*qK3
Invsincostan
qO
x/m71
x/aY)+x/qH2+x*m71
x*aY)+x*qH2+1.0l/m71
1.0l/aY)+1.0l/qH2+1.0l*m71
1.0l*aY)+1.0l*qH2;}
q0
Log2l
m1
1.1l)*1.4426950408889634073599246810018921374266l+x;}
q0
Log10l
qT
log10l
dZ1
Logl
m1
1.1l
hW
Pow_negl
qT
powl(-0.25l,qK3
Pow_posl
qT
powl(1.1l,7.1l
hW
Sinhl
qT
sinhl
dZ1
Sinhl_deg
qT
sinhl(g71
Sinl
qT
sinl
dZ1
Sinl_deg
qT
sinl(g71
Sqrtl
qT
sqrtl
dZ1
Tanhl
qT
tanhl
dZ1
Tanhl_deg
qT
tanhl(g71
Tanl
qT
tanl
dZ1
Tanl_deg
qT
tanl(g71
Truncl
qT
1.0l+x;}
}
template<>const
TestType<q0>RegressionTests<q0>::Tests[]={Uj
Wj
Yj
Sk
Tk
Uk
Wk
Yk
Sl
Tl
Ul
Wl{2,-11,11,N(0.3)qN,qG
Modl,0
oC",z"
,g9"modl"
,"x%z"
}
,Yl
Sm
Tm
Um
Wm
Ym
Sn{1,1,400,mD
Acoshl
hD2"acoshl"
,mR2
hD
1,400,gF1
Acoshl_deg
hD2"acoshl_deg"
,mR2
aP2
mM
Acosl
hD2"acosl"
,"acos"
aP2
dK1
Acosl_deg
hD2"acosl_deg"
,"acos"
aP2
mM
Asinhl
hD2"asinhl"
,"a"
wL2
aP2
dK1
Asinhl_deg
hD2"asinhl_deg"
,"a"
wL2
aP2
mM
Asinl
hD2"asinl"
,"a"
gA3
d4
dK1
Asinl_deg
hD2"asinl_deg"
,"a"
qA2}
,{2,-4
o01
Atan2l,wM"/atan2l"
,aA2"(x"
mI1{2,-4,4,N(0.05)g82
Atan2l_deg,wM"/atan2l_deg"
,aA2"(x"
mI1{1
d4
mM
Atanhl
hD2"atanhl"
,"atanh"
hD
oA2
mD
Atanl
hD2"atanl"
,"atan"
hD
oA2
gF1
Atanl_deg
hD2"atanl_deg"
,"atan"
hD-50000,50000,1000
qN
qB
Cbrtl
hD2"cbrtl"
,"cbrt"
hD-10,10,hF2
qB
Ceill
hD2"ceill"
,"ceil"
hD-140,140,mD
Coshl
hD2"coshl"
,"cosh"
hD-140,140,gF1
Coshl_deg
hD2"coshl_deg"
,"cosh"
hD-aR2
Cosl
hD2"cosl"
,"cos"
hD-aZ
g82
Cosl_deg
hD2"cosl_deg"
,"cos"
hD-90,90,mM
Exp2l
hD2"exp2l"
,"exp2"
hD-90,90,mM
Expl
hD2"expl"
,"exp"
hD-10,10,hF2
qB
Floorl
hD2"floorl"
,"floor(x)"
}
,{2,-4
o01
Hypotl,wM"/hypotl"
,"hypot(x"
mI1
Tn
Un{1,m0
Log2l
hD2"log2l"
,"log2"
hD
m0
Log10l
hD2"log10l"
,"log10"
hD
m0
Logl
hD2"logl"
,gE2
T4
U4{2,1,20,1
qN
qB
Pow_negl,wM"/pow_negl"
,"pow(-x*0.25,y"
g31{2,N(0.01)o01
Pow_posl,wM"/pow_posl"
,dB2
mI1{1,oA2
mD
Sinhl,hE2"hl"
,wL2
hD
oA2
gF1
Sinhl_deg,hE2"hl_deg"
,wL2
hD-aR2
Sinl,hE2"l"
,gA3,-aZ
g82
Sinl_deg,hE2"l_deg"
,gA3,0,100000,1000
qN
qB
Sqrtl
hD2"sqrtl"
,"sqrt"
hD-aR2
Tanhl
hD2"tanhl"
,"tanh"
hD-aZ
g82
Tanhl_deg
hD2"tanhl_deg"
,"tanh"
hD
N(-1.3),N(1.3),N(0.05)qN
qB
Tanl
hD2"tanl"
,"tan"
hD-89,89,N(0.25)g82
Tanl_deg
hD2"tanl_deg"
,"tan"
hD
oA2
mD
Truncl
hD2"truncl"
,"trunc"
hD
0,1,1
qN,hJ
E_ld,oB"e_ld"
aX2" naturalnumber"
d31
L2_ld,oB"l2_ld"
aX2" logtwo"
d31
L10_ld,oB"l10_ld"
aX2" logten"
d31
Pi_ld,oB"pi_ld"
aX2" pi"
}
,W4
UO1
WO1
Wn
Y4
Yn
So
To
S5
W5
Uo{1
gS
Acoshl,oD"acoshl"
,mR2
qN2
Acoshl_deg,oD"acoshl_deg"
,mR2"("
dN
Wo{1
gS
Acosl,oD"acosl"
,"acos(0.7"
h0
Acosl_deg,oD"acosl_deg"
,"acos(0.7)+x"
}
,Yo
Sp
Tp{1
gS
Asinhl,oD"asinhl"
,"a"
wL2
qN2
Asinhl_deg,oD"asinhl_deg"
,"a"
wL2"("
dN
Up{1
gS
Asinl,oD"asinl"
,"asin(0.7"
h0
Asinl_deg,oD"asinl_deg"
,"asin(0.7"
m61
Atan2l,oD"atan2l"
,aA2"(5,4"
h0
Atan2l_deg,oD"atan2l_deg"
,aA2"(5,4)+x"
}
,Wp{1
gS
Atanhl,oD"atanhl"
,"atanh(0.7"
m61
Atanl,oD"atanl"
,"atan"
qN2
Atanl_deg,oD"atanl_deg"
,"atan"
hM1
Cbrtl,oD"cbrtl"
,"cbrt"
hM1
Ceill,oD"ceill"
,"ceil("
dN
Yp
WP1
YP1
SQ1
TQ1
UQ1
WQ1
YQ1
SR1
TR1
UR1
WR1
YR1
SS1
TS1
US1
WS1
YS1
ST1
TT1
UT1
WT1
YT1
SU1
TU1
UU1
WU1
YU1
SV1
TV1
UV1
WV1
YV1
SW1
TW1
UW1
WW1
YW1
SX1
TX1
UX1
WX1
YX1
SY1
TY1
UY1
WY1{1
gS
Coshl,oD"coshl"
,"cosh"
qN2
Coshl_deg,oD"coshl_deg"
,"cosh"
hM1
Cosl,oD"cosl"
,"cos"
qN2
Cosl_deg,oD"cosl_deg"
,"cos("
dN
Sq
Tq
Y5
Uq
Wq
Yq
S6
T6
U6
W6
Sr
Wa1
Ya1
Tr{1
gS
Exp2l,oD"exp2l"
,"exp2("
dN
Ur
Wr{1
gS
Expl,oD"expl"
,m12
dN
Yr
Ss
Ts{1
gS
Floorl,oD"floorl"
,"floor("
dN
Us
Sb1
Tb1
Ub1
Wb1
Yb1
Sc1
Uc1
Wc1
Yc1
Sd1
Td1
Ud1{1
gS
Hypotl,oD"hypotl"
,"hypot(5,4)+x"
}
,Ws
Ys
St
Tt
Ut
Wt
Yt
Y6{2,N(-0.7),N(0.7),N(0.28)qN
q4
Invsincostan,0
oC
gW"invsincostan"
,"x/sin("
wS1"cos("
wS1"tan("
wS1"csc("
wS1"sec("
wS1"cot("
aU2"  1/sin("
aU2" 1/cos("
aU2" 1/tan("
aU2" 1/csc("
aU2" 1/sec("
aU2" 1/cot(y"
g31{1
gS
Log2l,oD"log2l"
,"log2"
hM1
Log10l,oD"log10l"
,"log10"
hM1
Logl,oD"logl"
,"log("
dN
Sf1
Tf1
Uf1
S7
T7
U7
W7
Y7
Su
S8
Tu
T8
U8
W8
Tj1
Uj1
Y8
S9
T9
U9
W9
Y9
SA
TA
UA{1
gS
Pow_negl,0,w21"_negl"
,"pow(-0.25,4"
m61
Pow_posl,0,w21"_posl"
,"pow(1.1, 7.1)+x"
}
,Uu
Wu
Yu
Sv
Tv
Uv
Wv
Yv
Sw
Sk1
Tk1
Uk1
Wk1
Yk1
Sl1
Tl1
Ul1
Wl1{1
gS
Sinhl,0,aW"hl"
,wL2
qN2
Sinhl_deg,0,aW"hl_deg"
,wL2
hM1
Sinl,0,aW"l"
,"sin(1.1"
h0
Sinl_deg,0,aW"l_deg"
,"sin("
dN
WA
YA
SB
TB
UB
WB
Tw
Uw
Ww{1
gS
Sqrtl,oD"sqrtl"
,"sqrt("
dN
Sn1{1
gS
Tanhl,oD"tanhl"
,"tanh"
qN2
Tanhl_deg,oD"tanhl_deg"
,"tanh"
hM1
Tanl,oD"tanl"
,"tan"
qN2
Tanl_deg,oD"tanl_deg"
,"tan"
hM1
Truncl,oD"truncl"
,"trunc("
dN
YB
SC
Yw
So1
To1
TC
Sx
UC
Tx
Ux
Wx
Yx
SD
Sy
TD
UD
WD
Ty
Uy
Wy
YD
SE
TE
UE
WE
YE
SF
TF
UF
Yy
Sz
Tz
Uz
Wz
Yz
WF
YF
SG
TG
UG
WG
YG
SH
TH
S_
T_
U_
W_
Y_
S01
UH
WH
YH
SI
TI
UI
WI
YI
SJ
T01
U01
W01
Y01
S11
T11
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
U11
W11
Y11
S21
T21
U21
SL
TL
UL
WL
YL
SM
TM
UM
WM
W21
Y21
S31
T31
U31
W31
YM
SN
TN
UN
WN
YN
SO
TO
UO
Y31
S41
T41
U41
W41
Y41
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
S51
T51
U51
W51
Y51
S61
Ux1
Wx1
Yx1
Sy1
UQ
WQ
YQ
SR
TR
UR
Uy1
Wy1
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
TV
UV
WV
YV
SW
TW
UW
WW
T61
U61
YW
W61
Y61
S71
T71
SX
U71
TX
W71
Y71
S81
UX
WX
YX
SY
T81
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Yb
Sc
U81
W81
Y81
S91
T91
U91
W91
Y91
Tc
Uc
Wc
SA1
TA1
UA1
WA1
YA1
SB1
Sz1
Tz1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
TB1
UB1
WB1
YB1
SC1
TC1
UC1
WC1
YC1
SD1
TD1
UD1
WD1
Ye
Sf
Tf
Uf
Wf
Yf
YD1
Tg
SE1
TE1
UE1
WE1
Ug
YE1
SF1
TF1
UF1
WF1
#if !defined(FP_DISABLE_EVAL)
YF1
#endif /*!defined(FP_DISABLE_EVAL) */
SG1
TG1
UG1
WG1
YG1
SH1
TH1
UH1
WH1
Wg
Yg
YH1
Sh
Th
Uh
SI1
TI1
Wh
UI1
WI1
YI1
SJ1
Yh
TJ1
UJ1
WJ1
YJ1
Si
Ti
SK1
TK1
UK1
WK1
YK1
SL1
TL1
UL1
WL1
YL1
SM1
TM1
Ui
UM1
WM1
YM1
SN1
TN1
Wi
UN1
TestType<q0>()}
;
#undef Value_t
#undef N
#undef P
#endif /*FP_SUPPORT_LONG_DOUBLE_TYPE */
#ifdef FP_SUPPORT_LONG_INT_TYPE
#define P(x) (APP(x,l))
#define Value_t long
template<>const
TestType<q0>RegressionTests<q0>::Tests[]={S
T
U
W
Y
S1
T1
U1
W1
Y1
S2
T2
U2
W2
Y2
S3
T3
U3
W3
Y3
S4
T4
U4
W4
TO1
YO1
Y4
S5
T5
U5
W5
SP1
TP1
UP1
SQ1
SU1
TU1
UU1
SY1
TY1
YY1
SZ1
TZ1
UZ1
WZ1
YZ1
Sa1
Ta1
Ua1
Y5
S6
T6
U6
W6
Wa1
Ya1
Sb1
Wb1
Uc1
Sd1
Yd1
Y6
Wf1
S7
T7
Sg1
Tg1
Ug1
U7
W7
Sh1
Th1
Y7
Uh1
S8
Si1
T8
U8
W8
Wi1
Tj1
Uj1
Wj1
Y8
S9
T9
U9
W9
Y9
SA
TA
UA
Yj1
WA
YA
SB
TB
UB
WB
Yl1
Sm1
Wm1
Ym1
Sn1
YB
SC
TC
UC
Uo1
Wo1
Yo1
Sp1
Tp1
Up1
Wp1
Yp1
Sq1
Tq1
Uq1
Wq1
Yq1
Sr1
Tr1
Ur1
Wr1
Yr1
Ss1
Ts1
Us1
Ws1
Ys1
St1
Tt1
Ut1
Wt1
Yt1
Su1
Tu1
Uu1
Wu1
Yu1
Sv1
Tv1
Uv1
Wv1
Yv1
Sw1
Tw1
Uw1
Ww1
Yw1
Sx1
Tx1
WC
YC
SD
TD
UD
WD
YD
SE
TE
UE
WE
YE
SF
TF
UF
WF
YF
SG
TG
UG
WG
YG
SH
TH
UH
WH
YH
SI
TI
UI
WI
YI
SJ
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
SL
TL
UL
WL
YL
SM
TM
UM
WM
YM
SN
TN
UN
WN
YN
SO
TO
UO
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
Ux1
Wx1
Yx1
Sy1
UQ
WQ
YQ
SR
TR
UR
Uy1
Wy1
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
SV
TV
UV
WV
YV
SW
TW
UW
WW
YW
SX
TX
UX
WX
YX
SY
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Yb
Sc
Tc
Uc
Wc
Sz1
Tz1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
Ye
Sf
Tf
Uf
Wf
Yf
Sg
Uz1
Yz1
S_1
T_1
U_1
Tg
Ug
Wg
Yg
Sh
Th
Uh
Wh
Yh
Si
Ti
Ui
Wi
Yi
Sj
Tj
TestType<q0>()}
;
#undef Value_t
#undef P
#endif /*FP_SUPPORT_LONG_INT_TYPE */
#ifdef FP_SUPPORT_MPFR_FLOAT_TYPE
#define N(x) (q0(#x,0))
#define P(x) N(x)
#define Value_t MpfrFloat
static
gV2
mflit0_5("0.5"
,0),o72("0.25"
,0),mflit1_1("1.1"
,0),mflit0_7("0.7"
,0),mflit1_6("1.6"
,0),mflit1_5("1.5"
,0),mflitm1_1("-1.1"
,0),mflitm1_6("-1.6"
,0),mflitm1_5("-1.5"
,0),mflitm0_25("-0.25"
,0),gB3("7.1"
,0),mflit0_015625("0.015625"
,0),mflit0_0625("0.0625"
,0),mflit5_0625("5.0625"
,0),mflit1_2("1.2"
,0),mflitm5_1("-5.1"
,0),mflitm7_1("-7.1"
,0),mflit5_1("5.1"
,0),mflit_5(".5"
,0),mflit3_1("3.1"
,0),mflit4e2("4e2"
,0),mflit1em14("1e-14"
,0),mflit3_5("3.5"
,0),mflit57_295779513082320877("57.295779513082320877"
,0),mflit0_2("0.2"
,0),mflit7_5("7.5"
,0),aW2("2.5"
,0),mflit1_3("1.3"
,0),mflit1_4("1.4"
,0),mflit1_7("1.7"
,0),mflit1_8("1.8"
,0),mflit1_25("1.25"
,0),mflit1_75("1.75"
,0),mflit2_25("2.25"
,0),mflit3_3("3.3"
,0),mflit0_6("0.6"
,0),mflit2_1("2.1"
,0),mflit1_75e21("1.75e21"
,0);namespace
cpp_01unit_operators{qM3
And_d
qO
q0(d01?fp_abs(y)>=mflit0_5:q0(0
qS3
Div_d
qO(x-o72)/y;}
q0
Divmul_d
hB
x*y*x*x/z*(x-o72);}
q0
Modm(qD,&z
oI2
qA
x%z;}
q0
Not_d
qT
qK2<mflit0_5);}
q0
Notnot_d
qT
q0(d01);}
q0
Or_d
qO
qK2<mflit0_5?fp_abs(y)>=mflit0_5:dW2
qT3
cpp_02unit_functions{qM3
Acoshm
gN
acosh
hZ1
Acoshm_deg
dS2
acosh(x
qS3
Acosm
gN
acos
hZ1
Acosm_deg
dS2
acos(x
qS3
Asinhm
gN
asinh
hZ1
Asinhm_deg
dS2
asinh(x
qS3
Asinm
gN
asin
hZ1
Asinm_deg
dS2
asin(x
qS3
Atan2m
qO
q0::atan2(x,y);}
q0
Atan2m_deg
qO
r2d(q0::atan2(x,y
qS3
Atanhm
gN
atanh
hZ1
Atanm
gN
atan
hZ1
Atanm_deg
dS2
atan(x
qS3
Cbrtm
gN
cbrt
hZ1
Ceilm
gN
ceil
hZ1
Coshm
gN
cosh
hZ1
Coshm_deg
gN
cosh(g51
Cosm
gN
cos
hZ1
Cosm_deg
gN
cos(g51
Exp2m
gN
exp2
hZ1
Expm
gN
exp
hZ1
Floorm
gN
floor
hZ1
Hypotm
qO
q0::hypot(x,y);}
q0
If_d
hB
d01?y:z;}
q0
Int
qT
fp_floor(x+mflit0_5);}
q0
Log2m
gN
log2
hZ1
Log10m
gN
log10
hZ1
Logm
gN
log
hZ1
Pow_negm
qO
q0::pow(-x*o72,y);}
q0
Pow_posm
qO
q0::pow(x,y);}
q0
Sinhm
gN
sinh
hZ1
Sinhm_deg
gN
sinh(g51
Sinm
gN
sin
hZ1
Sinm_deg
gN
sin(g51
Sqrtm
gN
sqrt
hZ1
Tanhm
gN
tanh
hZ1
Tanhm_deg
gN
tanh(g51
Tanm
gN
tan
hZ1
Tanm_deg
gN
tan(g51
Truncm
gN
trunc(x)qT3
cpp_03unit_constants{qM3
E_mpfr
gN
exp(x*q0(0
dR2
1
qS3
L2_mpfr
gN
log(x*q0(0
dR2
2
qS3
L10_mpfr
gN
log(x*q0(0
dR2
10
qS3
Pi_mpfr
gN
atan2(x*q0(0),-dW2
qT3
cpp_10optimizer_bytecode{qM3
Acoshm
gN
acosh
gV
Acoshm_deg
dS2
acosh(wO
Acosm
gN
acos(mX1
Acosm_deg
dS2
acos(mflit0_7)hW
Asinhm
gN
asinh
gV
Asinhm_deg
dS2
asinh(wO
Asinm
gN
asin(mX1
Asinm_deg
dS2
asin(mflit0_7)hW
Atan2m
gN
atan2
dV2
hW
Atan2m_deg
dS2
atan2
dV2)hW
Atanhm
gN
atanh(mX1
Atanm
gN
atan
gV
Atanm_deg
dS2
atan(wO
Cbrtm
gN
cbrt
gV
Ceilm
gN
ceil
gV
Coshm
gN
cosh
gV
Coshm_deg
gN
cosh(aV2
Cosm
gN
cos
gV
Cosm_deg
gN
cos(aV2
Exp2m
gN
exp2
gV
Expm
gN
exp
gV
Floorm
gN
floor
gV
Hypotm
gN
hypot
dV2
hW
Int
qT
x+(((((fp_int(mflit1_1)qI2
mflit1_6))qI2
o92)qI2
mflitm1_1))qI2
mflitm1_6))qI2
mflitm1_5
qS3
Log2m
gN
log2
gV
Log10m
gN
log10
gV
Logm
gN
log
gV
Pow_negm
gN
pow(mflitm0_25,q0(4)hW
Pow_posm
gN
pow(mflit1_1,gB3
hW
Powhalf
qT
qW
mflit0_5);}
q0
Powminushalf
qT
qW-mflit0_5);}
q0
Sinhm
gN
sinh
gV
Sinhm_deg
gN
sinh(aV2
Sinm
gN
sin
gV
Sinm_deg
gN
sin(aV2
Sqrtm
gN
sqrt
gV
Tanhm
gN
tanh
gV
Tanhm_deg
gN
tanh(aV2
Tanm
gN
tan
gV
Tanm_deg
gN
tan(aV2
Truncm
qT
q0(1)+x
qT3
cpp_20optimizer_optimizations{qM3
Cmpeq_pow_imm_negneg
qT
qB2
qW
g63
Cmpeq_pow_imm_negpos
qT
qB2
oE2
Cmpeq_pow_imm_pospos_base
qT
qB2
oG2
Cmpge_pow_imm_negneg
wA
qW
g63
Cmpge_pow_imm_negpos
wA
oE2
Cmpge_pow_imm_pospos_base
wA
oG2
Cmpgt_pow_imm_negneg
qT
g11
qW
g63
Cmpgt_pow_imm_negpos
qT
g11
oE2
Cmpgt_pow_imm_pospos_base
qT
g11
oG2
Cmple_pow_imm_negneg
qT
o11
qW
g63
Cmple_pow_imm_negpos
qT
o11
oE2
Cmple_pow_imm_pospos_base
qT
o11
oG2
Cmplt_pow_imm_negneg
qT
fp_less(qW
g63
Cmplt_pow_imm_negpos
qT
fp_less(oE2
Cmplt_pow_imm_pospos_base
qT
fp_less(oG2
Cmpne_pow_imm_negneg
mK1
qW
g63
Cmpne_pow_imm_negpos
mK1
oE2
Cmpne_pow_imm_pospos_base
mK1
oG2
Cmpzz_pow_imm_negneg
qT
q0
d11
qW
gL
aE
qW
gL
m2
qW
gL
m3
qW
gL
m5
qW
gL
mN
qW
g63
Cmpzz_pow_imm_negpos
qT
q0
d11
h8
aE
h8
m2
h8
m3
h8
m5
h8
mN
oE2
Cmpzz_pow_imm_pospos_base
qT
q0
d11
gY
aE
gY
m2
gY
m3
gY
m5
gY
mN
oG2
Ifabsnot
hB
fp_truth(qC1!=q0(0)?z:y;}
q0
Posnot
g42
qC1;}
q0
Posnotnot
qT
fp_notNot(qC1;}
q0
Powmulimm_fnen
wT(q0(-8)qS3
Powmulimm_fnep
wT(q0(4)qS3
Powmulimm_fnfn
g52(mflitm5_1)*x,(mflitm7_1
qS3
Powmulimm_fnfp
wT
gB3);}
q0
Powmulimm_fpfp
qO
mA2
mflit5_1*x*y,gB3)qT3
cpp_50regressions{qM3
t42
qO
h72
x*x)+o82(mA2
y*y,o72))+fp_hypot(x,y)qT3
cpp_99misc{qM3
t2
qT
q0(2)*x+m91)/mflit_5+q0(2)-m91)*fp_sin
hZ1
t3
hB
fp_and(m51),qB2
y,x
wX
1
dR2
2)-mflit3_1*mflit4e2/mflit_5+x*x+y*y+z*z+hA2,x)qD3
y,y);}
#if !defined(FP_DISABLE_EVAL)
q0
t6(qD,qZ3
b19[2]qA(x>mflit1em14&&y>mflit1em14?x*y+t6<q0>((b19[0]=(x-dW2,b19[1]=(y-dW2,b19)):gK3
1);}
#endif /* !defined(FP_DISABLE_EVAL) */
q0
t9
hB
mflit1_5+x*y-q0(2
dR2
4)/q0(8)+z+z+z+z+x/(y*z);}
q0
t11
hB(-x-x)+y+hP
dL1,z
qS3
t22
qO(mflit3_5
qL3
wX
10)*(x*gE3-(mB2
y)qL3
wX
100)*((x
qL3))-(y*gE3)qL3
dR2
5)/(q0(2)qL3))+dL1,x
qL3))+dL1
qL3),x
qL3
qS3
t26_deg
qT
mB2
d2r(x))+fp_cos(d2r(x*o92)+r2d(fp_asin(x/q0(110)))+r2d(gD1/q0(120)qS3
t30
qO
x-y*q0(1)+fp_mod(x,y)+x/mA2
y,gU2
qI
2),gE3+fp_mod(q0(5),gE3+qW
mA2
y,q0(0)))+qW
mflit0_5);}
q0
t32
hB
x+y/y-gQ2
3),q0(4))-x-gR2
4),gE3+gR2
3),q0(4))-gQ2
4),q0(3
wX
0)+(z*dW2+(x-q0(2
dR2
2))+(x*mflit0_5
qL3))+y*q0(0)+fp_min(fp_min(gQ2
4),x),dW2,fp_min
g33
fp_min(y,q0(4)),z)))+fp_max(fp_max(gR2
4),x),dW2,fp_max(gS2
fp_max(y,q0(4)),z)))+(fp_abs(dW2+fp_acos(dW2+fp_asin(dW2+fp_atan(dW2+fp_ceil(gU2
fp_cos(q0(0))+aD2
q0(0))+fp_floor(gU2
hP
dW2+mB2
q0(0))+fp_sinh(q0(0))+dM2
dW2+fp_tanh(dW2+qG2
q0(1),dW2)+(x-(y-z))+(x+y)+(x*y)+fp_max(gS2
gS2
gS2
x,x))))*-q0(1)+(z-z
dR2
1)/m91/mE1
aY/mE1
dM2
z/q0(5))+h1
q0(1)/dM2
z/mE1
mB2
y/mE1
mE/q0(5)))+hP
q0(30)+x)*hP
q0(40)+y)/hP
q0(50)+z
a2/mflit57_295779513082320877)+fp_asin(x/q0(10))*mflit57_295779513082320877+fp_floor(-x
dR2
1)/fp_ceil(x)+h72
q0(5)*mflit0_2)+(-x+-x+-x+-x+-x+-x);}
q0
t37
qT
q0(5)+mflit7_5*q0(8)/q0(3)-qI
2),q0(4))qL3)+fp_mod(q0(7),q0(2
wX
4
hW
t38
hB
fp_asinh(x)+o82
fp_acosh(y+gE3+aW2*fp_atanh(z);}
q0
t39
hB
m91+aY*o92)-mE+mB2
y*o92)+z*z*z*mB2
z*z*z-x*x-y*y)-aY*o92*m91+aY*o92)+x*y*z+x*y*aW2+x*y*z*mE)+x*y*mE)+x*z*mE)+y*z*aW2+(x*y*z*mE)-x*y*z-y*mE)-x*z*y+x*y+x*z-mE)*x);}
q0
t44
g52
x*x
w6
8))gX2
g62
w6
7
wX1
g62*x
w6
6))+mflit1_3*g72
w6
5))+mflit1_4*g72*x
w6
6))+o82
g72*x*x
w6
4))+mflit1_6*g72*x*x*x
w6
3))+mflit1_7*g72*x*x*x*x
w6
2))+mflit1_8*(h72
mA2
fp_abs(-h72
x)),gE3
qS3
t45
g52
x*x
w6
7))gX2
g62*x
w6
5
wX1
g72*x
w6
3
qS3
t46
qO
fp_abs(fp_floor(gD1
dR2
4)))gX2
fp_abs(fp_floor(fp_acos(y)+o92)o12
qW1(fp_acos(y)-q0(10)wX1
gR2-4),gD1))+mflit1_3*gQ2
9),gD1)-q0(9
qS3
t47
qO
mflit1_25*hM2
x)+fp_exp(-x))+o82
hM2
y)-fp_exp(-y))+mflit1_75*(hM2-x)+fp_exp(x))/q0(2
wX
2)*(hM2-x)-fp_exp(x))/q0(2))+mflit2_25*(aD2
y)+fp_sinh(y
qS3
t48
qT
fp_sinh((hP
x)/q0(5
dR2
1))*q0(5
wX1
aD2(hP
x)/hP
q0(2
wX
1))*hP
q0(2)))+fp_not(fp_or
aC
x),fp_not(x/q0(4))qS3
t49
qT
qG2
q0(0),x)+qI-4)*(x-q0(100)),mflit3_3);}
q0
t52
qT
x+(q0(1
dR2
2
dR2
3
dR2
4)-q0(5)-q0(6)-q0(7)-q0(8))/q0(3
dR2
4)*(q0(1)+mB2
q0(2))+fp_cos(q0(4)*q0(5
dR2
6))/q0(2))+fp_cos(mflit0_5)*dM2
mflit0_6+mflit0_2)-mflit1_1/hP
mflit2_1)*h72
mflit3_3)+qI
2),q0(3
qS3
t55
qO
fp_less(qW
mflit1_2),q0(0))o12
mA2
y,aW2),gK3
2)*aT*x,gK3
3)*fp_less(mA2
y,gE3,gK3
4)*fp_less(qW
q0(4)),q0(0
qS3
t56
qT
fp_mod(mflit1_75e21,x);}
}
template<>const
TestType<q0>RegressionTests<q0>::Tests[]={Uj
Wj
Yj
Sk
Tk
Uk
Wk
Yk
Sl
Tl
Ul
Wl{2,-11,11,N(0.3)qN,qG
Modm,0
oC",z"
,g9"modm"
,"x%z"
}
,Yl
Sm
Tm
Um
Wm
Ym
Sn{1,1,400,mD
Acoshm
hD2"acoshm"
,mR2
hD
1,400,gF1
Acoshm_deg
hD2"acoshm_deg"
,mR2
aP2
mM
Acosm
hD2"acosm"
,"acos"
aP2
dK1
Acosm_deg
hD2"acosm_deg"
,"acos"
aP2
mM
Asinhm
hD2"asinhm"
,"a"
wL2
aP2
dK1
Asinhm_deg
hD2"asinhm_deg"
,"a"
wL2
aP2
mM
Asinm
hD2"asinm"
,"a"
gA3
d4
dK1
Asinm_deg
hD2"asinm_deg"
,"a"
qA2}
,{2,-4,4,N(0.15)qN
qB
Atan2m,wM"/atan2m"
,aA2"(x"
mI1{2,-4,4,N(0.15)g82
Atan2m_deg,wM"/atan2m_deg"
,aA2"(x"
mI1{1
d4
mM
Atanhm
hD2"atanhm"
,"atanh"
hD
oA2
mD
Atanm
hD2"atanm"
,"atan"
hD
oA2
gF1
Atanm_deg
hD2"atanm_deg"
,"atan"
hD-50000,50000,1000
qN
qB
Cbrtm
hD2"cbrtm"
,"cbrt"
hD-10,10,hF2
qB
Ceilm
hD2"ceilm"
,"ceil"
hD-140,140,mD
Coshm
hD2"coshm"
,"cosh"
hD-140,140,gF1
Coshm_deg
hD2"coshm_deg"
,"cosh"
hD-aR2
Cosm
hD2"cosm"
,"cos"
hD-aZ
g82
Cosm_deg
hD2"cosm_deg"
,"cos"
hD-90,90,N(0.02)qN
qB
Exp2m
hD2"exp2m"
,"exp2"
hD-90,90,N(0.02)qN
qB
Expm
hD2"expm"
,"exp"
hD-10,10,hF2
qB
Floorm
hD2"floorm"
,"floor(x)"
}
,{2,-4
o01
Hypotm,wM"/hypotm"
,"hypot(x"
mI1
Tn
Un{1,m0
Log2m
hD2"log2m"
,"log2"
hD
m0
Log10m
hD2"log10m"
,"log10"
hD
m0
Logm
hD2"logm"
,gE2
T4
U4{2,1,20,1
qN
qB
Pow_negm,wM"/pow_negm"
,"pow(-x*0.25,y"
g31{2,N(0.01)o01
Pow_posm,wM"/pow_posm"
,dB2
mI1{1,oA2
mD
Sinhm,hE2"hm"
,wL2
hD
oA2
gF1
Sinhm_deg,hE2"hm_deg"
,wL2
hD-aR2
Sinm,hE2"m"
,gA3,-aZ
g82
Sinm_deg,hE2"m_deg"
,gA3,0,100000,1000
qN
qB
Sqrtm
hD2"sqrtm"
,"sqrt"
hD-aR2
Tanhm
hD2"tanhm"
,"tanh"
hD-aZ
g82
Tanhm_deg
hD2"tanhm_deg"
,"tanh"
hD
N(-1.3),N(1.3),N(0.05)qN
qB
Tanm
hD2"tanm"
,"tan"
hD-89,89,N(0.25)g82
Tanm_deg
hD2"tanm_deg"
,"tan"
hD
oA2
mD
Truncm
hD2"truncm"
,"trunc"
hD
0,1,1
qN,hJ
E_mpfr,oB"e_mpfr"
aX2" naturalnumber"
d31
L2_mpfr,oB"l2_mpfr"
aX2" logtwo"
d31
L10_mpfr,oB"l10_mpfr"
aX2" logten"
d31
Pi_mpfr,oB"pi_mpfr"
aX2" pi"
}
,W4
Wn
Y4
Yn
So
To
S5
W5
Uo{1
gS
Acoshm,oD"acoshm"
,mR2
qN2
Acoshm_deg,oD"acoshm_deg"
,mR2"("
dN
Wo{1
gS
Acosm,oD"acosm"
,"acos(0.7"
h0
Acosm_deg,oD"acosm_deg"
,"acos(0.7)+x"
}
,Yo
Sp
Tp{1
gS
Asinhm,oD"asinhm"
,"a"
wL2
qN2
Asinhm_deg,oD"asinhm_deg"
,"a"
wL2"("
dN
Up{1
gS
Asinm,oD"asinm"
,"asin(0.7"
h0
Asinm_deg,oD"asinm_deg"
,"asin(0.7"
m61
Atan2m,oD"atan2m"
,aA2"(5,4"
h0
Atan2m_deg,oD"atan2m_deg"
,aA2"(5,4)+x"
}
,Wp{1
gS
Atanhm,oD"atanhm"
,"atanh(0.7"
m61
Atanm,oD"atanm"
,"atan"
qN2
Atanm_deg,oD"atanm_deg"
,"atan"
hM1
Cbrtm,oD"cbrtm"
,"cbrt"
hM1
Ceilm,oD"ceilm"
,"ceil("
dN
Yp{1
gS
Coshm,oD"coshm"
,"cosh"
qN2
Coshm_deg,oD"coshm_deg"
,"cosh"
hM1
Cosm,oD"cosm"
,"cos"
qN2
Cosm_deg,oD"cosm_deg"
,"cos("
dN
Sq
Tq
Y5
Uq
Wq
Yq
W6
Sr
Tr
Ur{1
gS
Exp2m,oD"exp2m"
,"exp2("
dN
Wr
Yr
Ss
Ts{1
gS
Expm,oD"expm"
,"exp"
hM1
Floorm,oD"floorm"
,"floor("
dN
Us{1
gS
Hypotm,oD"hypotm"
,"hypot(5,4)+x"
}
,Ws
Ys
St
Tt
Ut
Wt
Yt
Y6{1
gS
Log2m,oD"log2m"
,"log2"
hM1
Log10m,oD"log10m"
,"log10"
hM1
Logm,oD"logm"
,"log("
dN
S7
T7
U7
W7
Y7
Su
S8
Tu
T8
U8
W8
Y8
S9
T9
U9
W9
Y9
SA
TA
UA{1
gS
Pow_negm,0,w21"_negm"
,"pow(-0.25,4"
m61
Pow_posm,0,w21"_posm"
,"pow(1.1, 7.1)+x"
}
,Uu
Wu
Yu
Sv
Tv
Uv
Wv
Yv
Sw{1
gS
Sinhm,0,aW"hm"
,wL2
qN2
Sinhm_deg,0,aW"hm_deg"
,wL2
hM1
Sinm,0,aW"m"
,"sin(1.1"
h0
Sinm_deg,0,aW"m_deg"
,"sin("
dN
WA
YA
SB
TB
UB
WB
Tw
Uw
Ww{1
gS
Sqrtm,oD"sqrtm"
,"sqrt"
hM1
Tanhm,oD"tanhm"
,"tanh"
qN2
Tanhm_deg,oD"tanhm_deg"
,"tanh"
hM1
Tanm,oD"tanm"
,"tan"
qN2
Tanm_deg,oD"tanm_deg"
,"tan"
hM1
Truncm,oD"truncm"
,"trunc("
dN
Yw
TC
Sx
UC
Tx
Ux
Wx
Yx
SD
Sy
TD
UD
WD
Ty
Uy
Wy
YD
SE
TE
UE
WE
YE
SF
TF
UF
Yy
Sz
Tz
Uz
Wz
Yz
WF
YF
SG
TG
UG
WG
YG
SH
TH
S_
T_
U_
W_
Y_
S01
UH
WH
YH
SI
TI
UI
WI
YI
SJ
T01
U01
W01
Y01
S11
T11
TJ
UJ
WJ
YJ
SK
TK
UK
WK
YK
U11
W11
Y11
S21
T21
U21
SL
TL
UL
WL
YL
SM
TM
UM
WM
W21
Y21
S31
T31
U31
W31
YM
SN
TN
UN
WN
YN
SO
TO
UO
Y31
S41
T41
U41
W41
Y41
WO
YO
SP
TP
UP
WP
YP
SQ
TQ
S51
T51
U51
W51
Y51
S61
UQ
WQ
YQ
SR
TR
UR
WR
YR
SS
TS
US
WS
YS
ST
TT
UT
WT
YT
SU
TU
UU
WU
YU
TV
UV
WV
YV
SW
TW
UW
WW
T61
U61
YW
W61
Y61
S71
T71
SX
U71
TX
W71
Y71
S81
UX
WX
YX
SY
T81
TY
UY
WY
YY
SZ
TZ
UZ
WZ
YZ
Sa
Ta
Ua
Wa
Ya
Sb
Tb
Ub
Wb
Yb
Sc
U81
W81
Y81
S91
T91
U91
W91
Y91
Tc
Uc
Wc
SA1
TA1
UA1
WA1
YA1
SB1
Yc
Sd
Td
Ud
Wd
Yd
Se
Te
Ue
We
TB1
UB1
WB1
YB1
SC1
TC1
UC1
WC1
YC1
SD1
TD1
UD1
WD1
Tf
Uf
Wf
Yf
YD1
Tg
SE1
TE1
UE1
WE1
Ug
YE1
SF1
TF1
UF1
WF1
#if !defined(FP_DISABLE_EVAL)
YF1
#endif /*!defined(FP_DISABLE_EVAL) */
SG1
TG1
UG1
WG1
YG1
SH1
TH1
UH1
WH1
Wg
Yg
YH1
Sh
Th
Uh
SI1
TI1
Wh
UI1
WI1
YI1
SJ1
Yh
TJ1
UJ1
WJ1
YJ1
Si
Ti
SK1
TK1
UK1
WK1
YK1
SL1
TL1
UL1
WL1
YL1
SM1
TM1
Ui
UM1
WM1
YM1
SN1
TN1
Wi
UN1
TestType<q0>()}
;
#undef Value_t
#undef N
#undef P
#endif /*FP_SUPPORT_MPFR_FLOAT_TYPE */
